import type { NewsItem } from "../types.ts";

// aivideo.zone: AI video generation and editing. Every entry is tagged with
// the tools and models it is about — the site's subject pages are built from
// those tags (apps/aivideo/src/sections.ts), so a tag here is a promise that
// the piece genuinely concerns that tool, not a keyword sprinkled on.

export const items: NewsItem[] = [

  {
    slug: "sora-api-alternatives-video-apis-still-open",
    createdAt: "2026-10-05T15:30:00+04:00",
    updatedAt: "2026-10-06T01:30:00+04:00",
    site: "aivideo",
    image: "/covers/sora-api-alternatives-video-apis-still-open.jpg",
    imageAlt: "An empty neon socket on the left of a dark ground, and three glowing cables plugged into three small ports on the right",
    imageKind: "generated",
    imageWidth: 1536,
    imageHeight: 864,
    title: "After Sora: the AI video APIs still taking requests",
    titleSeo: "Sora API alternatives: AI video APIs still open",
    summary:
      "OpenAI switched off the Sora 2 API on 24 September with no replacement named. Four AI video APIs a Sora integration can move to — xAI, Google, MiniMax and Kling — and what each one asks of you.",
    date: "2026-10-05",
    category: "Guide",
    tags: ["Grok Imagine", "MiniMax", "Kling"],
    source: {
      name: "xAI developer docs",
      url: "https://docs.x.ai/developers/models",
      verifiedOn: "2026-10-06",
    },
    body: [
      "OpenAI's deprecation list gives the Videos API and every <strong>sora-2</strong> and <strong>sora-2-pro</strong> snapshot a removal date of <strong>24 September 2026</strong>, and in the column for a recommended replacement it gives nothing at all. Anything built on Sora has to move to someone else's model, and the request shapes differ enough that this is a port, not a find-and-replace.",
      "## xAI: Grok Imagine",
      "Priced the way Sora was, per second of output, with three video models to choose from. On xAI's models page as checked on 6 October, <strong>grok-imagine-video-1.5-lite</strong> costs <strong>$0.020</strong> a second, <strong>grok-imagine-video</strong> <strong>$0.050</strong> and <strong>grok-imagine-video-1.5</strong> <strong>$0.080</strong>. Video 1.5 does text-to-video, image-to-video and reference-to-video, with native 1080p for the first two. One detail worth knowing before you port prompts: xAI's release notes say its text-to-video runs as a text-to-image step followed by image-to-video, so the first frame is a still the model chose.",
      "## Google: the Gemini API",
      "Google's video models live in the Gemini API. The newest, <strong>gemini-omni-1.1-flash</strong>, became generally available on <strong>27 August</strong>, with video extension, interpolation between two images, and output at 360p, 720p, 1080p or 4K. Beside it is <strong>veo-3.1</strong>, where Google's changelog sent users of <strong>veo-2.0</strong> and <strong>veo-3.0</strong> when it shut those down on 30 June — a reminder that a migration target can have a migration of its own.",
      "## MiniMax: H3 through the API",
      "MiniMax serves <strong>H3</strong>, its model for video and sound generated together, through the API at platform.minimax.io. Its licence notes say the API is available globally, which matters because the open weights are not: the H3 licence excludes the European Union, the United Kingdom, South Korea and the United States. For a team in those places the hosted API is the way to use H3 without applying for a separate licence.",
      "## Kling",
      "Kling sells API access through its developer platform. Kling 4.0 is in limited early access, with the full model due in October, so check the platform for which Kling models the API serves before you plan around 4.0's thirty-second clips.",
      "## What does not carry over",
      "Prompts. Each of these models has its own idea of how a scene should be written: xAI and Kling take references and keyframes in their own ways, MiniMax H3 has a structured format with numbered shots and tagged dialogue, and Lightricks' own guide warns against pasting another model's prompt into LTX unchanged. Budget time for rewriting the prompts, not just the client code.",
    ],
    faq: [
      {
        q: "When did the Sora API shut down?",
        a: "OpenAI's deprecations page lists <strong>24 September 2026</strong> as the removal date for the Videos API and the sora-2 and sora-2-pro models, with no replacement listed.",
      },
      {
        q: "How much does the Grok Imagine video API cost?",
        a: "On xAI's models page as checked on 6 October 2026: <strong>$0.020</strong> per second for grok-imagine-video-1.5-lite, <strong>$0.050</strong> for grok-imagine-video and <strong>$0.080</strong> for grok-imagine-video-1.5.",
      },
      {
        q: "Can I use MiniMax H3 in the US or the EU?",
        a: "Through MiniMax's API, yes: MiniMax says the API is available globally. The open weights are licensed worldwide except the European Union, the United Kingdom, South Korea and the United States, where MiniMax asks organisations to apply for a separate licence.",
      },
    ],
  },

  {
    slug: "ai-video-prompt-formats-ltx-minimax-h3-kling",
    createdAt: "2026-10-05T11:10:00+04:00",
    updatedAt: "2026-10-05T11:10:00+04:00",
    site: "aivideo",
    image: "/covers/ai-video-prompt-formats-ltx-minimax-h3-kling.jpg",
    imageAlt: "Three neon consoles in orange, violet and cyan, each with a small screen, joined by glowing lines to one shared screen above them",
    imageKind: "generated",
    imageWidth: 1536,
    imageHeight: 864,
    title: "One scene, three AI video prompts: LTX, MiniMax H3 and Kling",
    cardTitle: "One scene, three prompt formats",
    titleSeo: "One scene, three AI video prompts",
    summary:
      "A screenwriter's guide to the three ways AI video models want a scene written: LTX reads a flowing paragraph, MiniMax H3 a tagged shot list with timed cuts, Kling a timeline pinned to keyframes. The same scene in each.",
    date: "2026-10-05",
    category: "Guide",
    tags: ["Screenwriters", "LTX", "MiniMax", "Kling"],
    action: {
      url: "https://docs.ltx.io/api-documentation/implementation-guides/prompting-guide",
      label: "LTX prompting guide",
      title: "Lightricks' own guide to writing prompts for LTX video models",
      icon: "document",
    },
    source: {
      name: "Lightricks, MiniMax and Kling prompting guides",
      url: "https://docs.ltx.io/api-documentation/implementation-guides/prompting-guide",
      verifiedOn: "2026-10-06",
    },
    body: [
      "Three AI video models now generate picture and sound together, cut between shots inside one clip, and put words in a character's mouth. Each publishes a guide to writing for it, and the three guides disagree about the form a scene should take. Lightricks says it plainly: a prompt written for another model loses its tag syntax and shot-list formatting on the way into LTX, and tends to underperform. What follows is one scene written three ways, from those guides.",
      "The scene: a woman waits at a rainy bus stop at night; she checks her phone and says \"He's late\"; a bus pulls in.",
      "## LTX: write it as prose",
      "Lightricks wants a single flowing paragraph in the present tense — roughly four to eight sentences for a single take — with dialogue in quotation marks and emotion shown through physical cues rather than named. For LTX-2.5's multi-shot scenes the cut goes into the prose too: name the transition, re-establish the new framing, say whether the sound carries across. It recommends two to four shots per generation.",
      "<code>A wide shot frames a bus stop at night, rain streaking through a streetlight's cone. A woman in a grey coat stands under the shelter, glancing at her phone; its light catches her face. She exhales and says quietly, \"He's late.\" A hard cut moves to a close-up of the phone screen as rain ticks on the shelter roof; the ambience continues across the cut. Headlights sweep across the glass as a bus pulls in.</code>",
      "One more line in the guide changes how a writer paces a scene: LTX-2.5's duration predictor times the clip to the action as written, and will not add a pause you did not prompt for. If the beat matters, write \"a beat of silence\" into the scene.",
      "## MiniMax H3: a tagged script",
      "MiniMax's prompt guide for H3 is the most like a screenplay, and the strictest. The prompt has three named fields: <code>integrated_multimodal_description</code> for everything seen and heard in order, <code>overall_soundscape</code> for ambience and physical sound, and <code>non_diegetic_music</code> for score the characters cannot hear. Shots are numbered; every shot after the first opens with its cut time; a speaker gets a stable ID and their line goes inside a dialogue tag with the language named.",
      "<code>integrated_multimodal_description: [Shot 1] Live-action, cinematic, a wide shot frames a woman in a grey coat under a bus shelter at night as rain falls past a streetlight. She glances at her phone, and the tired woman with a low, quiet voice (S1) says: &lt;d&gt;[English] He's late.&lt;/d&gt; [Shot 2] At 00:04.000, the camera cuts to a close-up of the phone screen as headlights sweep across the shelter glass.</code>",
      "<code>overall_soundscape: Steady rain drums on the shelter roof and runs off the gutter. A bus engine approaches and its brakes hiss as it stops.</code> <code>non_diegetic_music: N/A</code>",
      "The guide also asks for camera moves written as sentences with an amplitude and a speed — \"the camera pushes in with small amplitude at slow speed\" — rather than labels stacked at the end, and keeps on-screen text in double quotation marks exactly as it should appear.",
      "## Kling: a timeline and keyframes",
      "Kling 4.0 takes up to ten keyframes and prompts of up to 8,000 tokens, and its keyframes guide lays a prompt out as a timeline: <code>0–5s:</code>, <code>5–10s:</code> and so on, each segment saying what happens. The keyframes fix the important moments; the prompt, in Kling's words, explains how the video moves between them. For this scene that is two keyframes — the woman at the stop, the bus arriving — and a timeline that carries her from one to the other.",
      "<code>0–4s: wide shot, a woman in a grey coat waits under a bus shelter at night in heavy rain; she checks her phone and says quietly, \"He's late.\" 4–8s: headlights sweep across the shelter glass as a bus pulls in and stops beside her.</code>",
      "## Which to write first",
      "Write the scene once as prose — it is the form closest to how a writer thinks, and it is what LTX wants anyway. Converting prose into H3's fields is mechanical: split it at the cuts, give each speaker an ID, move the rain into the soundscape. Converting it into Kling's timeline means deciding which moments are keyframes, which is a directing decision rather than a formatting one.",
    ],
    faq: [
      {
        q: "Can I use the same prompt for LTX, MiniMax H3 and Kling?",
        a: "Not unchanged. Lightricks' guide says prompts written for other models, Kling's included, lose their tag syntax and shot-list formatting in LTX and tend to underperform; MiniMax H3 expects its own three-field format, and Kling 4.0 works best with a timeline tied to keyframes.",
      },
      {
        q: "How do I write dialogue in an AI video prompt?",
        a: "For LTX, put the spoken line in quotation marks. For MiniMax H3, give the speaker an ID such as (S1) and put the line inside a dialogue tag with the language named: &lt;d&gt;[English] …&lt;/d&gt;.",
      },
      {
        q: "How many shots can one LTX-2.5 prompt hold?",
        a: "Lightricks recommends two to four shots per generation, with each cut named in the prose.",
      },
    ],
  },

  {
    slug: "editing-ai-video-in-comfyui-nodes",
    createdAt: "2026-10-04T13:00:00+04:00",
    updatedAt: "2026-10-04T13:00:00+04:00",
    site: "aivideo",
    image: "/covers/editing-ai-video-in-comfyui-nodes.jpg",
    imageAlt: "Neon scissors cutting through a magenta film strip, with two cyan cubes on a looping cable and a yellow ring beside it",
    imageKind: "generated",
    imageWidth: 1536,
    imageHeight: 864,
    title: "Editing AI video in ComfyUI: the nodes that arrived in September",
    cardTitle: "Editing AI video in ComfyUI",
    titleSeo: "Editing AI video in ComfyUI: September's nodes",
    summary:
      "ComfyUI is no longer only where AI video gets generated. September's releases added nodes to join clips, loop over them, erase objects, edit footage with a prompt and grade in film colour spaces. What each one does.",
    date: "2026-10-04",
    category: "Guide",
    tags: ["ComfyUI"],
    action: {
      url: "https://github.com/Comfy-Org/ComfyUI/releases",
      label: "ComfyUI releases",
      title: "Every ComfyUI release and its notes, on GitHub",
      icon: "download",
    },
    source: {
      name: "ComfyUI release notes on GitHub",
      url: "https://github.com/Comfy-Org/ComfyUI/releases",
      verifiedOn: "2026-10-06",
    },
    body: [
      "A generated clip is rarely the finished shot. It needs joining to the next one, a stray object taken out, its colour brought into line with the rest of the edit. Until recently that meant leaving ComfyUI for an editor. Two September releases, <strong>0.36</strong> on 15 September and <strong>0.38</strong> on 29 September, moved a good part of that work inside the graph.",
      "## Joining and repeating: Video Concatenate and Generic Loops",
      "<strong>Video Concatenate</strong> is a core node in 0.36: it joins clips end to end inside a workflow, so a sequence generated shot by shot comes out as one file without a trip through an editor. The same release added <strong>Generic Loops</strong>: a <strong>Start Loop</strong> and an <strong>End Loop</strong> node, and whatever sits between them runs a set number of times or once for every item in a list — the shape you need to run the same treatment over every clip in a batch.",
      "## Editing with a prompt: Flux Video Edit",
      "0.36 also added a partner node for <strong>BFL's Flux Video Edit</strong>, which changes existing footage from a text instruction. Partner nodes run on the provider's servers and are billed through your Comfy account rather than on your own GPU, so this one is a paid call, not a local model.",
      "## Removing things: Bria Video Eraser",
      "The <strong>Bria</strong> partner nodes in 0.36 include an image editor and a <strong>Video Eraser</strong> for taking an object out of a clip — the cleanup pass every generated shot seems to need somewhere. It is a partner node as well, so hosted and paid in the same way.",
      "## Grading: LogC3 and ACEScct",
      "0.38 taught the <strong>Convert Color Space</strong> node <strong>LogC3</strong> and <strong>ACEScct</strong>, and fixed its handling of negative values. That is the colour plumbing professional grading runs on: footage can now leave ComfyUI in a space a colourist expects, or come in from one, instead of everything being flattened to sRGB on the way.",
      "## Restyling and restoring",
      "0.38 also added support for <strong>ID-V2V</strong> on <strong>Wan 2.1 / VACE</strong>, for video-to-video work, and optimised <strong>SeedVR2</strong>, the restoration and upscaling model, which is the usual last step before a generated clip goes out at a higher resolution.",
      "## What it adds up to",
      "None of this makes ComfyUI a timeline editor; there is no cutting to music and no trimming by eye. What it removes is the export-and-reimport between generating a shot and cleaning it up — and a cleanup that lives in the graph runs again, unchanged, on the next take.",
    ],
    faq: [
      {
        q: "Can ComfyUI join video clips together?",
        a: "Yes. ComfyUI 0.36, released on 15 September 2026, added a core <strong>Video Concatenate</strong> node that joins clips inside a workflow.",
      },
      {
        q: "Do ComfyUI's partner nodes run locally?",
        a: "No. Partner nodes such as Flux Video Edit and Bria Video Eraser call the provider's hosted service and are paid for through your Comfy account.",
      },
    ],
  },

  {
    slug: "kling-4-vs-kling-3-what-changes",
    createdAt: "2026-10-03T16:00:00+04:00",
    updatedAt: "2026-10-03T16:00:00+04:00",
    site: "aivideo",
    image: "/covers/kling-4-vs-kling-3-what-changes.jpg",
    imageAlt: "Two neon film strips, one above the other: a short, dim magenta strip and below it a bright cyan strip twice its length",
    imageKind: "illustration",
    imageWidth: 1536,
    imageHeight: 864,
    title: "Kling 4.0 vs Kling 3.0: what actually changes",
    summary:
      "Kling 4.0 doubles the clip length to 30 seconds, adds up to ten keyframes, stereo sound and 10-bit HDR, and more than doubles the references one AI video can take. Kling's own comparison, line by line.",
    date: "2026-10-03",
    category: "Guide",
    tags: ["Kling"],
    action: {
      url: "https://kling.ai/blog/kling-4-vs-3",
      label: "Kling's comparison",
      title: "Kling 4.0 against the 3.0 series, in Kling's own table",
      icon: "document",
    },
    source: {
      name: "Kling AI",
      url: "https://kling.ai/blog/kling-4-vs-3",
      verifiedOn: "2026-10-06",
    },
    body: [
      "Kling published its own comparison of 4.0 against the 3.0 series on 30 September. Most of the headline numbers moved; a few did not, and those matter as much when deciding whether to wait for 4.0.",
      "## Length: up to 30 seconds",
      "Kling 3.0 generated <strong>3 to 15 seconds</strong>. Kling 4.0 generates <strong>3 to 30 seconds</strong> natively — long enough for a scene with a beginning, a turn and an end in one clip rather than three stitched together.",
      "## Keyframes: from two to ten",
      "3.0 had start and end frames and nothing in between. 4.0 keeps those and adds <strong>multiple keyframes, up to ten</strong>: images pinned to moments in the clip that the model has to pass through. That is the change that turns a prompt into something closer to a storyboard.",
      "## Picture: same resolutions, deeper colour",
      "Resolution does not change: <strong>720p, 1080p and 4K</strong> in both. What changes is dynamic range, from <strong>8-bit SDR</strong> to <strong>10-bit HDR</strong> at 1080p and 4K — though Kling's announcement describes HDR as coming soon rather than available now. 4.0 also adds <strong>21:9</strong> ultrawide to the standard aspect ratios.",
      "## Sound: stereo",
      "3.0's audio was single-channel. 4.0's is <strong>two-channel stereo</strong>, and spoken languages grow from Chinese, English, Japanese, Korean and Spanish to add Portuguese, German, French, Hindi and more.",
      "## References: up to fifteen",
      "This is the largest jump. 3.0 took up to <strong>seven</strong> images or subjects, or one video of up to 15 seconds plus four images or subjects. 4.0 takes up to <strong>fifteen</strong> reference assets in one generation: up to <strong>ten images</strong>, <strong>seven subjects</strong>, and <strong>five videos</strong> totalling 30 seconds.",
      "## Editing: one workflow",
      "In 3.0, editing lived in separate Omni workflows. 4.0 folds text-to-video, image-to-video, references, continuation and editing into one multimodal workflow.",
      "## When you can use it",
      "Kling says <strong>4.0 Flash</strong> went to a limited group of users for early access on <strong>28 September</strong>, and the full version launches in <strong>October</strong>. Until then, 3.0 is what most accounts have, and nothing in the table makes a 3.0 project obsolete — a fifteen-second clip with start and end frames is still that.",
    ],
    faq: [
      {
        q: "How long can a Kling 4.0 video be?",
        a: "From <strong>3 to 30 seconds</strong>, generated natively. Kling 3.0 went up to 15 seconds.",
      },
      {
        q: "Does Kling 4.0 support 4K?",
        a: "Yes, at 720p, 1080p and 4K — the same resolutions as 3.0. 10-bit HDR at 1080p and 4K is new in 4.0; Kling's announcement describes it as coming soon.",
      },
      {
        q: "How many reference images does Kling 4.0 take?",
        a: "Up to ten images and seven subjects, plus up to five reference videos totalling 30 seconds — no more than fifteen assets in one generation.",
      },
      {
        q: "Is Kling 4.0 available now?",
        a: "Kling 4.0 Flash has been in early access for a limited group since 28 September 2026. Kling says the full version launches in October.",
      },
    ],
  },

  {
    slug: "ltx-2-5-september-loras-long-clips-hdr",
    createdAt: "2026-10-02T19:20:00+04:00",
    updatedAt: "2026-10-02T19:20:00+04:00",
    site: "aivideo",
    image: "/covers/ltx-2-5-september-loras-long-clips-hdr.jpg",
    imageAlt: "An open case holding two rows of glowing yellow and magenta cartridges, with one cartridge lifted out above the rest",
    imageKind: "generated",
    imageWidth: 1536,
    imageHeight: 864,
    title: "LTX-2.5's September: fourteen LoRAs, long clips and an HDR master",
    cardTitle: "LTX-2.5 gets fourteen LoRAs and HDR",
    titleSeo: "LTX-2.5: 14 new LoRAs, long AI video and HDR",
    summary:
      "Lightricks spent September turning LTX-2.5 into a post-production kit: fourteen LoRAs for jobs like mattes, deblurring and day-for-night, long AI video in overlapping windows, and an SDR-to-HDR pass that writes EXR.",
    date: "2026-10-02",
    category: "News",
    tags: ["LTX"],
    action: {
      url: "https://github.com/Lightricks/LTX-2/releases",
      label: "LTX-2 releases",
      title: "Lightricks' LTX-2 code releases and their notes, on GitHub",
      icon: "download",
    },
    source: {
      name: "Lightricks on GitHub and Hugging Face",
      url: "https://github.com/Lightricks/LTX-2/releases",
      verifiedOn: "2026-10-06",
    },
    body: [
      "Seven weeks after LTX-2.5's open weights came out, most of what Lightricks has shipped for it is not about generating a new shot. It is about fixing, converting and finishing one — the work that normally happens in a compositing or grading tool.",
      "## Fourteen adapters in a month",
      "Between <strong>8 and 28 September</strong> Lightricks published fourteen adapters for the 22-billion-parameter LTX-2.5 on Hugging Face: twelve IC-LoRAs, which condition generation on footage or images you supply, and two plain LoRAs. In order: <strong>Day-To-Night</strong>; <strong>Deblur</strong>, <strong>Clean-Plate</strong> and <strong>Water-Simulation</strong>; <strong>Ingredients</strong>, <strong>Colorization</strong>, <strong>Decompression</strong> and the <strong>Cinemagraph</strong> LoRA; the <strong>Slow-Motion-Control</strong> LoRA; <strong>Layout-To-Render</strong>; <strong>Restore</strong> and <strong>Refine-Details</strong>; and finally <strong>Alpha-Gen</strong> and <strong>SDR-To-HDR</strong>.",
      "Three of them are worth singling out. <strong>Alpha-Gen</strong> takes an ordinary RGB clip and returns an alpha matte — a key without a green screen — at up to 1920×1088 and 145 frames. <strong>Layout-To-Render</strong> turns a 3D viewport or clay animation, plus one styled image of the first frame, into a finished shot, which is how a previs becomes a render. <strong>SDR-To-HDR</strong> converts 8-bit footage to 16-bit HDR.",
      "## Longer clips in overlapping windows",
      "Release <strong>1.4.0</strong> of the LTX-2 code, on <strong>29 September</strong>, added chunked long-video generation: the clip is made in <strong>97-frame windows</strong>, each carrying <strong>25 frames</strong> over from the one before, with a crossfade at the seams. It is the model's way past its single-pass length without the jump a hard join leaves.",
      "## An HDR master, in one pass",
      "The same release made SDR-to-HDR a single stage. It writes a <strong>10-bit BT.2020 / HLG</strong> master alongside <strong>EXR</strong> frames, in <strong>ACEScg</strong> by default, or <strong>ACEScct</strong> or linear sRGB. <strong>1.4.1</strong> on 30 September streams the HDR output straight to EXR and HLG, and <strong>1.4.2</strong> on 2 October added the pipeline that runs Alpha-Gen.",
      "## And on smaller machines",
      "1.4.0 also tiles the IC-LoRA transformer in <strong>1024×1536</strong> windows, which is what lets these adapters run on frames larger than the GPU would otherwise hold. Release <strong>1.3.0</strong> in August had already fixed installation on macOS — Apple Silicon runs through MPS — and fp8 with LoRAs on pre-Ada cards such as the RTX 3060 and A100.",
    ],
    faq: [
      {
        q: "Can LTX-2.5 remove a background without a green screen?",
        a: "Yes, with the <strong>Alpha-Gen</strong> IC-LoRA Lightricks published on 28 September 2026: it takes an RGB clip and returns an alpha matte, at up to 1920×1088 and 145 frames. The LTX-2 1.4.2 release added the pipeline that runs it.",
      },
      {
        q: "How does LTX-2.5 make long videos?",
        a: "Since LTX-2 1.4.0, in overlapping 97-frame windows that carry 25 frames from one window into the next, with a crossfade at each seam.",
      },
      {
        q: "Can LTX output HDR?",
        a: "Yes. The SDR-To-HDR IC-LoRA converts 8-bit footage to 16-bit HDR, and LTX-2 1.4.0 writes a 10-bit BT.2020/HLG master plus EXR frames in ACEScg, ACEScct or linear sRGB.",
      },
    ],
  },

  {
    slug: "kling-4-keyframes-shot-list-for-screenwriters",
    createdAt: "2026-10-01T17:30:00+04:00",
    updatedAt: "2026-10-01T17:30:00+04:00",
    site: "aivideo",
    image: "/covers/kling-4-keyframes-shot-list-for-screenwriters.jpg",
    imageAlt: "Five tall blank panels in a row, outlined in magenta and blue neon on a dark ground",
    imageKind: "generated",
    imageWidth: 1536,
    imageHeight: 864,
    title: "Writing a shot list for Kling 4.0's ten keyframes",
    titleSeo: "Kling 4.0 keyframes: an AI video shot list",
    summary:
      "Kling 4.0 lets one 30-second AI video pass through up to ten pinned keyframes, with a prompt of up to 8,000 tokens to carry it between them. How Kling's guide says to plan that, written up for screenwriters.",
    date: "2026-10-01",
    category: "Guide",
    tags: ["Screenwriters", "Kling"],
    action: {
      url: "https://kling.ai/blog/kling-4-multiple-keyframes-guide",
      label: "Kling's keyframes guide",
      title: "Kling's own guide to multiple keyframes in Kling 4.0",
      icon: "document",
    },
    source: {
      name: "Kling AI",
      url: "https://kling.ai/blog/kling-4-multiple-keyframes-guide",
      verifiedOn: "2026-10-06",
    },
    body: [
      "A screenwriter already writes the thing Kling 4.0 asks for. Its new multiple-keyframes feature — up to <strong>ten</strong> images pinned to moments in a clip of up to <strong>30 seconds</strong> — is a shot list with pictures, and Kling's own guide to it, published on 30 September, reads like advice on blocking a scene.",
      "## Keyframes are the beats, the prompt is the action",
      "Kling's guide puts the division in one sentence: the keyframes show the important moments, and the prompt explains how the video moves between them. A keyframe is not a shot; it is a state the scene must reach — the door open, the letter read, the face turned. Everything that happens on the way there belongs in the words.",
      "## Lay the prompt out as a timeline",
      "Kling 4.0 accepts prompts of up to <strong>8,000 tokens</strong>, and the guide recommends spending them on a timeline: one segment per stretch of time, written as <code>0–5s:</code>, <code>5–10s:</code> and so on, each saying what happens and how the camera sees it. Its own example runs from <strong>0–5s</strong>, a kitchen at sunrise and a woman walking to the counter, into <strong>5–12s</strong>, where she picks up a product and the camera moves closer: one segment per change in the situation.",
      "## Fewer keyframes than you think",
      "Ten is a ceiling, not a target. The guide's test for whether a moment deserves one is whether anything important changes there; if nothing does, it says, you probably do not need another keyframe — more keyframes do not automatically mean more control. Every extra one is another point the model has to hit exactly, and the motion between closely spaced ones has nowhere to go.",
      "## The four ways it goes wrong",
      "Kling lists the common mistakes, and each one has a screenwriting equivalent. <strong>Too many keyframes</strong>: over-blocking a scene until no one can move. <strong>Changing too many things at once</strong> between two keyframes — costume, light, location and action in one step — which a cut could handle but a continuous shot cannot. <strong>Inconsistent references</strong>: keyframes and reference images that disagree, so a character looks different from one moment to the next. And <strong>conflicting prompts</strong>, where the words pull one way and the pictures another, and the creative direction, as Kling puts it, becomes unclear.",
      "## A way to start",
      "Write the scene as you would for a reader first. Mark the moments where the situation changes — those are your keyframes, and a 30-second scene rarely has more than five. Draw or generate one image for each. Then write the timeline: what moves between each pair, in present tense, with the camera's part named. Kling 4.0 is in limited early access with the full model due in October, so a plan written this way now is ready the day the account has it.",
    ],
    faq: [
      {
        q: "How many keyframes does Kling 4.0 support?",
        a: "Up to <strong>ten</strong>, in a clip of up to 30 seconds. Kling 3.0 had start and end frames only.",
      },
      {
        q: "How long can a Kling 4.0 prompt be?",
        a: "Up to <strong>8,000 tokens</strong>, according to Kling's keyframes guide.",
      },
      {
        q: "How should a Kling 4.0 prompt be structured?",
        a: "Kling's guide recommends a timeline — segments such as 0–5s, 5–10s — describing how the video moves between the keyframes, which mark the important moments.",
      },
    ],
  },

  {
    slug: "kling-4-0-announced-flash-early-access",
    createdAt: "2026-09-30T20:30:00+04:00",
    updatedAt: "2026-09-30T20:30:00+04:00",
    site: "aivideo",
    image: "/covers/kling-4-0-announced-flash-early-access.jpg",
    imageAlt: "A neon film strip stretched across a dark violet ground, held at its corners by four glowing pins",
    imageKind: "generated",
    imageWidth: 1536,
    imageHeight: 864,
    title: "Kling 4.0: 30-second clips, ten keyframes, full launch in October",
    cardTitle: "Kling 4.0: 30 seconds, ten keyframes",
    titleSeo: "Kling 4.0: 30-second AI video, ten keyframes",
    summary:
      "Kling AI announced Kling 4.0 on 30 September: native AI video of up to 30 seconds, up to ten keyframes, stereo sound and up to fifteen references. A Flash version is in limited early access; the full model comes in October.",
    date: "2026-09-30",
    category: "News",
    tags: ["Kling"],
    action: {
      url: "https://kling.ai/blog/kling-4-ai-video-model",
      label: "Kling's announcement",
      title: "Kling AI's announcement of Kling 4.0",
      icon: "document",
    },
    source: {
      name: "Kling AI",
      url: "https://kling.ai/blog/kling-4-ai-video-model",
      verifiedOn: "2026-10-06",
    },
    body: [
      "Kling AI has announced <strong>Kling 4.0</strong>, the next generation of its video model, on <strong>30 September</strong>. Early access to the new creation experience began rolling out to a limited group of users on 28 September, as <strong>Kling 4.0 Flash</strong>; the full model is due in <strong>October 2026</strong>.",
      "## Longer clips with more control",
      "4.0 generates video natively from <strong>3 to 30 seconds</strong>, twice the 15 seconds Kling 3.0 reached. It supports up to <strong>ten keyframes</strong> — images the clip has to pass through at chosen moments — on top of the start and end frames 3.0 already had.",
      "## Picture and sound",
      "Output goes up to <strong>4K</strong>, and 4.0 adds the <strong>21:9</strong> ultrawide frame. Kling says <strong>10-bit HDR</strong> at 1080p and 4K is coming soon. Audio moves to <strong>two-channel stereo</strong>, and the spoken languages add Portuguese, German, French, Hindi and others to Chinese, English, Japanese, Korean and Spanish.",
      "## References",
      "One generation can take up to <strong>fifteen</strong> reference assets combined, including up to five reference videos. Text-to-video, image-to-video, references, continuation and editing now live in a single workflow rather than separate tools.",
    ],
    faq: [
      {
        q: "When does Kling 4.0 come out?",
        a: "Kling says the full Kling 4.0 model arrives in <strong>October 2026</strong>. Kling 4.0 Flash has been in early access for a limited group of users since 28 September.",
      },
      {
        q: "How long are Kling 4.0 videos?",
        a: "Between <strong>3 and 30 seconds</strong>, generated natively.",
      },
    ],
  },

  {
    slug: "comfyui-0-38-seedance-2-5-draft-minimax-h3-controlnet",
    createdAt: "2026-09-30T11:00:00+04:00",
    updatedAt: "2026-09-30T11:00:00+04:00",
    site: "aivideo",
    image: "/covers/comfyui-0-38-seedance-2-5-draft-minimax-h3-controlnet.jpg",
    imageAlt: "A stack of magenta monitors with yellow screens, wired to a keypad and a small control panel with two round dials",
    imageKind: "generated",
    imageWidth: 1536,
    imageHeight: 864,
    title: "ComfyUI 0.38 adds Seedance 2.5 drafts and ControlNet for MiniMax H3",
    cardTitle: "ComfyUI 0.38: Seedance drafts, H3 ControlNet",
    titleSeo: "ComfyUI 0.38: Seedance 2.5, MiniMax H3 ControlNet",
    summary:
      "ComfyUI 0.38 brings Fun-ControlNet-Union 2.0 to MiniMax H3, a Draft mode for ByteDance's Seedance 2.5, film colour spaces for grading and a lighter install — and drops its Sora nodes now that OpenAI's AI video API is gone.",
    date: "2026-09-30",
    category: "News",
    tags: ["ComfyUI", "MiniMax"],
    action: {
      url: "https://github.com/Comfy-Org/ComfyUI/releases/tag/v0.38.0",
      label: "Release notes",
      title: "ComfyUI 0.38.0 release notes on GitHub",
      icon: "download",
    },
    source: {
      name: "ComfyUI on GitHub",
      url: "https://github.com/Comfy-Org/ComfyUI/releases/tag/v0.38.0",
      verifiedOn: "2026-10-06",
    },
    body: [
      "ComfyUI <strong>0.38.0</strong> came out on <strong>29 September</strong>. For anyone running video models locally, the headline is control over MiniMax's open H3 model; for anyone using hosted ones, it is three new partner nodes.",
      "## MiniMax H3: ControlNet",
      "H3, MiniMax's 33-billion-parameter model for video with sound, gets <strong>Fun-ControlNet-Union 2.0</strong>: generation guided by a structure such as pose or depth taken from another clip. The release also adds tile blending to H3's VAE, so tiled decodes no longer leave seams, and fixes a crash in it.",
      "## Partner nodes: Seedance, Hunyuan, Seedream",
      "Three hosted models arrive as partner nodes: a <strong>Draft mode</strong> for ByteDance's <strong>Seedance 2.5</strong> video model, for quick previews before a full render; <strong>Hunyuan Image 3.5</strong> for text-to-image and editing; and <strong>Seedream 5.0 Flash</strong>.",
      "## Colour for grading",
      "The <strong>Convert Color Space</strong> node learns <strong>HDR LogC3</strong> and <strong>ACEScct</strong>, and stops mishandling negative values — the plumbing that lets footage leave ComfyUI in a space a colourist works in.",
      "## Lighter and faster",
      "ComfyUI no longer depends on <strong>torchaudio</strong>, one fewer package to match against your PyTorch build. The release adds <strong>ID-V2V</strong> support on Wan 2.1 / VACE, optimises the <strong>SeedVR2</strong> upscaler, and adds <strong>w6a8</strong> quantisation.",
      "## Sora's nodes are gone",
      "The deprecated <strong>Sora</strong> nodes have been removed. OpenAI shut the Sora 2 API down on 24 September, so the nodes had nothing left to call; a workflow that still contains them will report them as missing.",
    ],
    faq: [
      {
        q: "Does ComfyUI support ControlNet for MiniMax H3?",
        a: "Yes. ComfyUI 0.38.0, released on 29 September 2026, added Fun-ControlNet-Union 2.0 for MiniMax H3.",
      },
      {
        q: "Why did my Sora nodes disappear from ComfyUI?",
        a: "ComfyUI 0.38 removed the deprecated Sora nodes after OpenAI shut down the Sora 2 API on 24 September 2026.",
      },
    ],
  },

  {
    slug: "sora-api-shut-down-september-24",
    createdAt: "2026-09-24T14:20:00+04:00",
    updatedAt: "2026-09-30T13:10:00+04:00",
    site: "aivideo",
    image: "/covers/sora-api-shut-down-september-24.jpg",
    imageAlt: "A dark screen framed in magenta neon, with a cable running from a wall socket to a loose plug on the floor",
    imageKind: "generated",
    imageWidth: 1536,
    imageHeight: 864,
    title: "OpenAI shuts down the Sora 2 API, with no replacement named",
    cardTitle: "The Sora 2 API shuts down",
    titleSeo: "Sora 2 API shut down: no replacement named",
    summary:
      "OpenAI removed its Videos API and every sora-2 and sora-2-pro model on 24 September, six months after giving notice, and named no successor. It ends OpenAI's AI video offer for developers; the Sora app closed in April.",
    date: "2026-09-24",
    category: "News",
    action: {
      url: "https://help.openai.com/en/articles/20001152-what-to-know-about-the-sora-discontinuation",
      label: "OpenAI's notice",
      title: "OpenAI's help article on the Sora discontinuation",
      icon: "document",
    },
    source: {
      name: "OpenAI",
      url: "https://developers.openai.com/api/docs/deprecations",
      verifiedOn: "2026-10-06",
    },
    updates: [
      {
        on: "2026-09-30",
        text: "ComfyUI 0.38, released on 29 September, removed its deprecated Sora nodes. A workflow that still contains them will report them as missing.",
      },
    ],
    body: [
      "<strong>24 September 2026</strong> is the date OpenAI's deprecations page gives for removing the <strong>Videos API</strong> and the models behind it: <strong>sora-2</strong>, <strong>sora-2-pro</strong>, and the dated snapshots <strong>sora-2-2025-10-06</strong>, <strong>sora-2-2025-12-08</strong> and <strong>sora-2-pro-2025-10-06</strong>. Requests to them now fail.",
      "## Six months' notice, and no successor",
      "The notice went out on <strong>24 March 2026</strong>. Where the deprecations table normally names the model to move to, the Sora rows have a dash. OpenAI is not pointing video developers at a newer OpenAI model, because there is none.",
      "## The app went first",
      "The consumer side closed earlier. OpenAI's help article on the discontinuation says the Sora web and mobile apps were discontinued on <strong>26 April 2026</strong>, and pointed users to an export page to download what they had made.",
      "## What to do with an integration",
      "Move it. Every other major video API — xAI's Grok Imagine, Google's Gemini models, MiniMax, Kling, Lightricks' LTX — takes requests in its own shape, and prompts written for Sora will need rewriting as well as the client code.",
    ],
    faq: [
      {
        q: "Is the Sora API still working?",
        a: "No. OpenAI removed the Videos API and the sora-2 and sora-2-pro models on <strong>24 September 2026</strong>.",
      },
      {
        q: "What replaced the Sora API?",
        a: "Nothing from OpenAI: its deprecations page lists no replacement for the Sora models.",
      },
      {
        q: "When did the Sora app close?",
        a: "OpenAI's help article says the Sora web and mobile apps were discontinued on <strong>26 April 2026</strong>.",
      },
    ],
  },

  {
    slug: "comfyui-0-36-video-concatenate-flux-video-edit",
    createdAt: "2026-09-16T12:45:00+04:00",
    updatedAt: "2026-09-16T12:45:00+04:00",
    site: "aivideo",
    image: "/covers/comfyui-0-36-video-concatenate-flux-video-edit.jpg",
    imageAlt: "A neon film loop seen from above: a magenta ring with cyan sprocket holes, its joins marked by three yellow ticks",
    imageKind: "illustration",
    imageWidth: 1536,
    imageHeight: 864,
    title: "ComfyUI 0.36 learns to join clips, loop, and edit video with Flux",
    cardTitle: "ComfyUI 0.36: join, loop, edit",
    titleSeo: "ComfyUI 0.36: AI video editing nodes and loops",
    summary:
      "ComfyUI 0.36 adds a core node to join clips and a way to loop part of a graph, plus partner nodes for BFL's Flux Video Edit, Bria's Video Eraser and Pruna's P-Video-2 — AI video editing without leaving the workflow.",
    date: "2026-09-16",
    category: "News",
    tags: ["ComfyUI"],
    action: {
      url: "https://github.com/Comfy-Org/ComfyUI/releases/tag/v0.36.0",
      label: "Release notes",
      title: "ComfyUI 0.36.0 release notes on GitHub",
      icon: "download",
    },
    source: {
      name: "ComfyUI on GitHub",
      url: "https://github.com/Comfy-Org/ComfyUI/releases/tag/v0.36.0",
      verifiedOn: "2026-10-06",
    },
    body: [
      "ComfyUI <strong>0.36.0</strong>, released on <strong>15 September</strong>, is mostly about what happens to a clip after it is generated.",
      "## In the core: Video Concatenate and Generic Loops",
      "<strong>Video Concatenate</strong> joins clips end to end inside a workflow. <strong>Generic Loops</strong> adds a <strong>Start Loop</strong> and an <strong>End Loop</strong> node: the part of the graph between them runs a set number of times or once per item in a list, so one treatment can run over a batch of clips instead of being wired up once per clip.",
      "## Partner nodes for editing",
      "The hosted side grows: <strong>BFL Flux Video Edit</strong> changes existing footage from a text instruction; <strong>Bria</strong> brings an image editor and a <strong>Video Eraser</strong> for removing objects; <strong>Pruna P-Video-2</strong> adds text-to-video and image-to-video. The release also adds <strong>MAI Image 2.6</strong> through OpenRouter and <strong>Gemini 3.8 Flash</strong>.",
      "## MiniMax H3 and more",
      "MiniMax's open <strong>H3</strong> video model gets further VAE optimisations that cut its memory use, and a fix for its fun-ControlNet. Outside video, the release adds the <strong>Yue2</strong> music model and <strong>Marigold v2</strong>, with frontend 1.52.7 and templates 0.11.62.",
    ],
    faq: [
      {
        q: "What is new in ComfyUI 0.36?",
        a: "A core Video Concatenate node, Generic Loops, and partner nodes for BFL Flux Video Edit, Bria's image editor and Video Eraser, Pruna P-Video-2, MAI Image 2.6 and Gemini 3.8 Flash. It was released on 15 September 2026.",
      },
    ],
  },

  {
    slug: "grok-imagine-image-quality-retires-november-2",
    createdAt: "2026-09-03T11:30:00+04:00",
    updatedAt: "2026-09-03T11:30:00+04:00",
    site: "aivideo",
    image: "/covers/grok-imagine-image-quality-retires-november-2.jpg",
    imageAlt: "A small magenta frame and a larger glowing cyan frame side by side, a yellow arrow curving from the first to the second",
    imageKind: "generated",
    imageWidth: 1536,
    imageHeight: 864,
    title: "xAI will retire grok-imagine-image-quality on 2 November",
    cardTitle: "A Grok Imagine image model retires",
    titleSeo: "grok-imagine-image-quality retires on 2 November",
    summary:
      "The still that starts an image-to-video AI video clip often comes from an image model. xAI is retiring one of Grok Imagine's on 2 November and moving its requests to Image 2.0, which gained an automatic quality setting last week.",
    date: "2026-09-03",
    category: "News",
    tags: ["Grok Imagine"],
    action: {
      url: "https://docs.x.ai/developers/models",
      label: "xAI's models",
      title: "xAI's list of current models and their prices",
      icon: "list",
    },
    source: {
      name: "xAI developer docs",
      url: "https://docs.x.ai/developers/release-notes",
      verifiedOn: "2026-10-06",
    },
    body: [
      "xAI's release notes for <strong>2 September</strong> give <strong>grok-imagine-image-quality</strong> a retirement date of <strong>2 November 2026</strong>.",
      "## What happens to requests",
      "They keep working, on a different model. xAI says requests to the old name will be served by <strong>grok-imagine-image-2.0</strong> at <strong>quality low</strong>, with the same request shape and a lower price per image. The original <strong>Image 1.0</strong> model is not affected. An integration does not break on 2 November, but its pictures may change, so it is worth testing against Image 2.0 now rather than finding out from a user.",
      "## Image 2.0 changed last week",
      "The model taking over is not the one that launched. On <strong>28 August</strong> xAI gave Image 2.0's <strong>quality</strong> parameter an <strong>auto</strong> setting and made it the default, which picks low for generation and medium for editing. Editing now takes up to <strong>five</strong> source images instead of three, and two wider aspect ratios arrived: <strong>21:9</strong> and <strong>5:2</strong>.",
      "## Why it matters for video",
      "In an image-to-video workflow the first frame decides most of what the clip looks like, and 21:9 is the cinema frame. A still made at the right aspect ratio is a still that does not need cropping before it is animated.",
    ],
    faq: [
      {
        q: "When is grok-imagine-image-quality retired?",
        a: "On <strong>2 November 2026</strong>. Requests to it will then be served by grok-imagine-image-2.0 at quality low.",
      },
      {
        q: "What aspect ratios does Grok Imagine Image 2.0 support?",
        a: "Since 28 August 2026 these include <strong>21:9</strong> and <strong>5:2</strong>, alongside the existing ratios.",
      },
    ],
  },

  {
    slug: "gemini-omni-flash-ga-gemini-api",
    createdAt: "2026-08-28T12:10:00+04:00",
    updatedAt: "2026-08-28T12:10:00+04:00",
    site: "aivideo",
    image: "/covers/gemini-omni-flash-ga-gemini-api.jpg",
    imageAlt: "Neon rectangles nested one inside another in alternating cyan and magenta, around a small yellow rectangle at the centre",
    imageKind: "illustration",
    imageWidth: 1536,
    imageHeight: 864,
    title: "Gemini Omni 1.1 Flash is generally available, now up to 4K",
    titleSeo: "Gemini Omni 1.1 Flash: AI video up to 4K, now GA",
    summary:
      "Google made gemini-omni-1.1-flash generally available in the Gemini API on 27 August, adding AI video extension, interpolation between two images and output up to 4K. The preview it replaces shuts down on 30 September.",
    date: "2026-08-28",
    category: "News",
    action: {
      url: "https://ai.google.dev/gemini-api/docs/changelog",
      label: "Gemini API changelog",
      title: "Google's changelog for the Gemini API",
      icon: "document",
    },
    source: {
      name: "Gemini API changelog",
      url: "https://ai.google.dev/gemini-api/docs/changelog",
      verifiedOn: "2026-10-06",
    },
    body: [
      "Google's Gemini API changelog for <strong>27 August</strong> lists <strong>gemini-omni-1.1-flash</strong> as generally available. Two months ago it was a preview that made short clips; the release version does considerably more.",
      "## From preview to release",
      "<strong>gemini-omni-flash-preview</strong> arrived on <strong>30 June</strong>: clips of <strong>3 to 10 seconds</strong> at <strong>720p</strong>, with conversational editing through the Interactions API — asking for a change to a clip rather than regenerating it. The GA model adds <strong>video extension</strong>, <strong>interpolation</strong> between two images, and a choice of <strong>360p, 720p, 1080p or 4K</strong>.",
      "## Move off the preview by 30 September",
      "The preview shuts down on <strong>30 September</strong>. It is the second shutdown in Google's video line this summer: <strong>veo-2.0</strong> and <strong>veo-3.0</strong> were switched off on 30 June, with users pointed to veo-3.1.",
    ],
    faq: [
      {
        q: "When does gemini-omni-flash-preview shut down?",
        a: "On <strong>30 September 2026</strong>. Google made gemini-omni-1.1-flash generally available on 27 August as its replacement.",
      },
      {
        q: "What resolutions does Gemini Omni 1.1 Flash support?",
        a: "360p, 720p, 1080p and 4K.",
      },
    ],
  },

  {
    slug: "ltx-2-5-vs-minimax-h3-open-video-models",
    createdAt: "2026-08-20T14:00:00+04:00",
    updatedAt: "2026-08-20T14:00:00+04:00",
    site: "aivideo",
    image: "/covers/ltx-2-5-vs-minimax-h3-open-video-models.jpg",
    imageAlt: "Two glowing monoliths side by side, one magenta and one cyan, each flanked by a thin yellow light post",
    imageKind: "generated",
    imageWidth: 1536,
    imageHeight: 864,
    title: "LTX-2.5 or MiniMax H3: two open AI video models with sound",
    cardTitle: "LTX-2.5 or MiniMax H3?",
    titleSeo: "LTX-2.5 vs MiniMax H3: open AI video models",
    summary:
      "Two open-weights AI video models that generate sound with the picture came out within a fortnight of each other. LTX-2.5 and MiniMax H3 compared on size, output, references and the licence terms that decide who may run them.",
    date: "2026-08-20",
    category: "Guide",
    tags: ["LTX", "MiniMax"],
    action: {
      url: "https://huggingface.co/Lightricks/LTX-2.5",
      label: "LTX-2.5 model card",
      title: "Lightricks' LTX-2.5 weights and model card on Hugging Face",
      icon: "download",
    },
    source: {
      name: "LTX-2.5 and MiniMax H3 model cards",
      url: "https://huggingface.co/Lightricks/LTX-2.5",
      verifiedOn: "2026-10-06",
    },
    body: [
      "In August two companies published the weights of a video model that also makes the soundtrack: MiniMax opened <strong>H3</strong> on <strong>3 August</strong> and Lightricks released <strong>LTX-2.5</strong> on <strong>11 August</strong>. On paper they do the same job. The model cards show how differently.",
      "## Size",
      "H3 is the larger: a <strong>33-billion-parameter</strong> dense transformer with Qwen3-VL-32B as its text encoder. LTX-2.5 is a <strong>22-billion-parameter</strong> diffusion transformer with a Gemma 4 text encoder. MiniMax's own SGLang example runs H3 on four GPUs; Lightricks ships LTX-2.5 in <strong>int8</strong> and <strong>NVFP4</strong> quantised versions and a <strong>distilled 8-step</strong> checkpoint, which is where it gets onto smaller hardware.",
      "## What comes out",
      "Open H3 generates at <strong>768p</strong>, <strong>4 to 15 seconds</strong> at 24 fps, with <strong>32 kHz stereo</strong> audio and dialogue in eleven languages; higher-resolution variants are hosted only. LTX-2.5 defaults to 24 fps and reaches <strong>3840×2176</strong> through spatial upscaling. Both cut between shots inside one clip: H3 with numbered shots in the prompt, LTX-2.5 with native multi-shot generation that keeps identities consistent across wide, medium and close shots.",
      "## References",
      "H3's open release has two checkpoints. <strong>FL2VA</strong> works from up to two images, a first and last frame. <strong>Ref2VA</strong> takes up to nine images, three videos of 2 to 15 seconds and three audio files, twelve files in all. LTX-2.5 works from text, a first image or an audio track — the three starting points Lightricks' own API lists for it.",
      "## The licences",
      "This is where they differ most. LTX-2.5 is under the <strong>LTX-2 Community License</strong>: free, commercial use included, for organisations under <strong>$10 million</strong> in annual revenue, with a paid agreement above that. H3's licence covers the world <strong>except the European Union, the United Kingdom, South Korea and the United States</strong>, where MiniMax asks organisations to apply for a separate licence. Elsewhere, commercial products over <strong>$20 million</strong> in yearly revenue need MiniMax's written authorisation, and any commercial product using H3 has to display \"MiniMax H3\" in its interface.",
      "## Which to try",
      "If you are in one of H3's excluded territories, the question is settled before the specs: LTX-2.5, or H3 through MiniMax's hosted API. Outside them, H3 has the richer reference inputs and LTX-2.5 the quantised checkpoints for smaller hardware — and both run in ComfyUI.",
    ],
    faq: [
      {
        q: "Can I use MiniMax H3's open weights in the EU, the UK or the US?",
        a: "Not under the standard licence, which excludes the European Union, the United Kingdom, South Korea and the United States. MiniMax invites organisations there to apply for a separate licence, and its hosted API is available globally.",
      },
      {
        q: "Is LTX-2.5 free for commercial use?",
        a: "Under the LTX-2 Community License, yes, for organisations with less than $10 million in annual revenue. Above that, Lightricks requires a paid agreement.",
      },
      {
        q: "Do LTX-2.5 and MiniMax H3 generate audio?",
        a: "Yes, both generate sound together with the picture. H3 outputs 32 kHz stereo with dialogue in eleven languages.",
      },
    ],
  },

  {
    slug: "comfyui-0-32-ltx-2-5-grok-imagine-image-2",
    createdAt: "2026-08-12T15:05:00+04:00",
    updatedAt: "2026-08-12T15:05:00+04:00",
    site: "aivideo",
    image: "/covers/comfyui-0-32-ltx-2-5-grok-imagine-image-2.jpg",
    imageAlt: "Glowing cubes on a dark circuit-board grid, four magenta and one cyan at the centre, linked by thin neon traces",
    imageKind: "generated",
    imageWidth: 1536,
    imageHeight: 864,
    title: "ComfyUI 0.32 runs LTX-2.5 and adds Grok Imagine Image 2.0",
    cardTitle: "ComfyUI 0.32: LTX-2.5 and Grok Imagine",
    titleSeo: "ComfyUI 0.32: LTX-2.5 and Grok Imagine Image 2.0",
    summary:
      "ComfyUI 0.32 shipped on 11 August with support for LTX-2.5, Lightricks' new open AI video model, partner nodes for Grok Imagine Image 2.0 and Qwen-Image 3.0 Pro, and a higher minimum PyTorch.",
    date: "2026-08-12",
    category: "News",
    tags: ["ComfyUI", "Grok Imagine", "LTX"],
    action: {
      url: "https://github.com/Comfy-Org/ComfyUI/releases/tag/v0.32.0",
      label: "Release notes",
      title: "ComfyUI 0.32.0 release notes on GitHub",
      icon: "download",
    },
    source: {
      name: "ComfyUI on GitHub",
      url: "https://github.com/Comfy-Org/ComfyUI/releases/tag/v0.32.0",
      verifiedOn: "2026-10-06",
    },
    body: [
      "ComfyUI <strong>0.32.0</strong> came out late on <strong>11 August</strong>, the day Lightricks released LTX-2.5 — so the new model ran in ComfyUI from its first day.",
      "## LTX-2.5",
      "The release adds support for <strong>LTX-2.5</strong> for local generation, and <strong>LTX 2.5 partner nodes</strong> for running it on Lightricks' hosted service instead.",
      "## Partner nodes: Grok Imagine and Qwen",
      "Two hosted image models arrive as partner nodes: xAI's <strong>Grok Imagine Image 2.0</strong> and <strong>Qwen-Image 3.0 Pro</strong> — both useful as the source of a first frame for image-to-video.",
      "## MiniMax H3 gets lighter",
      "MiniMax's <strong>H3</strong> video model, opened the week before, gets an optimised VAE, a fix for <strong>VAEDecodeTiled</strong> with nested tensors, and a fix for its peak memory use. The release also fixes tiled audio decoding.",
      "## Before you update",
      "The minimum <strong>PyTorch</strong> version is now <strong>2.7</strong>. An older environment needs upgrading first, or ComfyUI will not start. The release also brings <strong>comfy kitchen</strong> attention and templates 0.11.39.",
    ],
    faq: [
      {
        q: "Does ComfyUI support LTX-2.5?",
        a: "Yes, from ComfyUI 0.32.0, released on 11 August 2026 — the day LTX-2.5 came out. It also has partner nodes for Lightricks' hosted LTX 2.5.",
      },
      {
        q: "What PyTorch version does ComfyUI 0.32 need?",
        a: "PyTorch <strong>2.7</strong> or newer.",
      },
    ],
  },

  {
    slug: "ltx-2-5-open-weights-comfyui",
    createdAt: "2026-08-12T10:20:00+04:00",
    updatedAt: "2026-08-12T10:20:00+04:00",
    site: "aivideo",
    image: "/covers/ltx-2-5-open-weights-comfyui.jpg",
    imageAlt: "An open crate with a glowing violet screen rising out of it, between two panels each showing a neon diamond",
    imageKind: "generated",
    imageWidth: 1536,
    imageHeight: 864,
    title: "Lightricks releases LTX-2.5 with open weights and multi-shot video",
    cardTitle: "LTX-2.5 is out, with open weights",
    titleSeo: "LTX-2.5: open AI video model with multi-shot",
    summary:
      "Lightricks released LTX-2.5 on 11 August: a 22-billion-parameter open-weights AI video model that generates sound with the picture, cuts between shots in one clip and upscales to 3840×2176. It ran in ComfyUI on day one.",
    date: "2026-08-12",
    category: "News",
    tags: ["LTX", "ComfyUI"],
    action: {
      url: "https://huggingface.co/Lightricks/LTX-2.5",
      label: "Model card",
      title: "LTX-2.5 weights and model card on Hugging Face",
      icon: "download",
    },
    source: {
      name: "Lightricks on Hugging Face",
      url: "https://huggingface.co/Lightricks/LTX-2.5",
      verifiedOn: "2026-10-06",
    },
    body: [
      "Lightricks released <strong>LTX-2.5</strong> on <strong>11 August</strong>, with the weights on Hugging Face from the start.",
      "## One clip, several shots",
      "It is a <strong>22-billion-parameter</strong> diffusion transformer that generates video and audio together. The new trick is <strong>native multi-shot</strong>: one generation can cut between connected wide, medium and close shots and keep the people in them consistent. A Gemma 4 text encoder reads the prompt, and a new diffusion-based video decoder turns the result into frames.",
      "## Output",
      "Clips default to <strong>24 fps</strong> and reach <strong>3840×2176</strong> through spatial upscaling. The frame count has to be a multiple of eight plus one, and width and height divisible by 32. An optional <strong>duration predictor</strong> sizes the clip to the action described, and a <strong>prompt enhancer</strong> rewrites a rough prompt before generation.",
      "## Checkpoints",
      "Lightricks publishes a trainable <strong>bf16 dev</strong> checkpoint, a <strong>distilled</strong> one that needs eight steps, and <strong>int8</strong> and <strong>NVFP4</strong> quantised versions for smaller or newer GPUs.",
      "## Licence",
      "The <strong>LTX-2 Community License</strong> makes it free to use, commercially included, for organisations with less than <strong>$10 million</strong> in annual revenue; above that, Lightricks wants a paid agreement.",
      "## In ComfyUI",
      "ComfyUI 0.32, out late the same day, supports LTX-2.5 locally and adds partner nodes for Lightricks' hosted version.",
    ],
    faq: [
      {
        q: "Is LTX-2.5 open source?",
        a: "Its weights are open, on Hugging Face, under the LTX-2 Community License: free, commercial use included, below $10 million in annual revenue.",
      },
      {
        q: "What resolution does LTX-2.5 generate?",
        a: "Up to <strong>3840×2176</strong> through spatial upscaling, at 24 fps by default.",
      },
    ],
  },

  {
    slug: "minimax-h3-open-weights",
    createdAt: "2026-08-04T12:15:00+04:00",
    updatedAt: "2026-08-04T12:15:00+04:00",
    site: "aivideo",
    image: "/covers/minimax-h3-open-weights.jpg",
    imageAlt: "A round vault door swung open, with glowing film frames and a strip of film streaming out through it",
    imageKind: "generated",
    imageWidth: 1536,
    imageHeight: 864,
    title: "MiniMax opens the weights of H3, its video-and-sound model",
    cardTitle: "MiniMax opens H3's weights",
    titleSeo: "MiniMax H3 open weights: AI video with sound",
    summary:
      "MiniMax has published the weights of H3, the AI video model it launched on 31 July: a 33-billion-parameter transformer that generates picture and stereo sound together. The licence leaves out the EU, UK, South Korea and US.",
    date: "2026-08-04",
    category: "News",
    tags: ["MiniMax"],
    action: {
      url: "https://huggingface.co/MiniMaxAI/MiniMax-H3",
      label: "Model card",
      title: "MiniMax H3 weights and model card on Hugging Face",
      icon: "download",
    },
    source: {
      name: "MiniMax on Hugging Face",
      url: "https://huggingface.co/MiniMaxAI/MiniMax-H3",
      verifiedOn: "2026-10-06",
    },
    body: [
      "MiniMax launched <strong>H3</strong> on <strong>31 July</strong> and opened its base weights on <strong>3 August</strong>, on Hugging Face and ModelScope.",
      "## Two checkpoints",
      "The open release has two, both in BF16. <strong>FL2VA</strong> generates from text and up to two images — a first frame, a last frame, or both. <strong>Ref2VA</strong> takes references: up to nine images, three videos of 2 to 15 seconds and three audio files, twelve files in all. Two further variants, <strong>H3-Context-IR</strong> and <strong>H3-Regenerate-2K</strong>, stay on MiniMax's own service.",
      "## What it makes",
      "Clips of <strong>4 to 15 seconds</strong> at 24 fps with <strong>32 kHz stereo</strong> sound, in six aspect ratios from 21:9 to 9:16. Characters can speak in <strong>eleven languages</strong>: Arabic, Chinese, English, French, German, Italian, Japanese, Korean, Portuguese, Russian and Spanish. The open base generates at 768p.",
      "## Under the hood",
      "A <strong>33-billion-parameter</strong> dense single-stream transformer, with <strong>Qwen3-VL-32B</strong> reading the prompt. It runs on SGLang, vLLM, diffusers and ComfyUI; MiniMax's SGLang example uses four GPUs, and MiniMax says sparse attention is coming later.",
      "## Who may use the weights",
      "The <strong>MiniMax H3 Community License</strong> applies worldwide <strong>except the European Union, the United Kingdom, South Korea and the United States</strong>. MiniMax says that is about regulation still being settled there, invites organisations in those places to apply for a licence, and keeps its API open globally. Where the licence does apply, commercial products with more than <strong>$20 million</strong> in yearly revenue need MiniMax's written authorisation, and any commercial product built on H3 must show \"MiniMax H3\" in its interface.",
    ],
    faq: [
      {
        q: "Is MiniMax H3 open source?",
        a: "Its weights are open under the MiniMax H3 Community License, which covers the world except the EU, the UK, South Korea and the US.",
      },
      {
        q: "How long are MiniMax H3 videos?",
        a: "From <strong>4 to 15 seconds</strong>, at 24 fps with 32 kHz stereo audio.",
      },
      {
        q: "Does MiniMax H3 generate speech?",
        a: "Yes, dialogue in eleven languages: Arabic, Chinese, English, French, German, Italian, Japanese, Korean, Portuguese, Russian and Spanish.",
      },
    ],
  },

  {
    slug: "grok-imagine-video-1-5-references-text-to-video",
    createdAt: "2026-08-01T13:40:00+04:00",
    updatedAt: "2026-08-01T13:40:00+04:00",
    site: "aivideo",
    image: "/covers/grok-imagine-video-1-5-references-text-to-video.jpg",
    imageAlt: "Glowing cyan cards arranged in an arc around a magenta card showing a sound wave, on a reflective violet floor",
    imageKind: "generated",
    imageWidth: 1536,
    imageHeight: 864,
    title: "Grok Imagine Video 1.5 takes up to seven references, in 1080p",
    cardTitle: "Grok Imagine 1.5: seven references",
    titleSeo: "Grok Imagine 1.5: AI video from seven references",
    summary:
      "xAI's Grok Imagine Video 1.5 now does text-to-video and reference-to-video, with up to seven image and voice references per AI video and native 1080p. In the Grok apps and, partly, in the xAI API.",
    date: "2026-08-01",
    category: "News",
    tags: ["Grok Imagine"],
    action: {
      url: "https://grok.com/imagine",
      label: "Open Grok Imagine",
      title: "Grok Imagine on grok.com, where Video 1.5 is available",
      icon: "play",
    },
    source: {
      name: "xAI",
      url: "https://x.ai/news/grok-imagine-video-1-5-references",
      verifiedOn: "2026-10-06",
    },
    body: [
      "xAI updated <strong>Grok Imagine Video 1.5</strong> on <strong>31 July</strong>, adding text-to-video and reference-to-video to the image-to-video it already did.",
      "## Seven references",
      "One generation can now take up to <strong>seven</strong> references, and they can be voices as well as images — a face, a product, a location and the voice that should speak. In the API, reference-to-video can also use preset voices.",
      "## 1080p",
      "Text-to-video and image-to-video now render at native <strong>1080p</strong>. xAI's release notes add a detail worth knowing when writing prompts: text-to-video runs as a text-to-image step followed by image-to-video.",
      "## Who gets it",
      "In the Grok apps — grok.com/imagine, iOS and Android — text-to-video and 1080p are generally available, and references are rolling out, first to <strong>SuperGrok Heavy</strong> and <strong>Plus</strong> subscribers in the US. In the xAI API, text-to-video and image references are live now; voice references are available on request.",
    ],
    faq: [
      {
        q: "How many references can Grok Imagine use?",
        a: "Up to <strong>seven</strong> per generation, images or voices, since the Grok Imagine Video 1.5 update of 31 July 2026.",
      },
      {
        q: "Does Grok Imagine generate 1080p video?",
        a: "Yes. Video 1.5 renders text-to-video and image-to-video at native 1080p.",
      },
    ],
  },

];
