import type { NewsItem } from "../types.ts";

export const items: NewsItem[] = [
  {
    slug: "casa-del-lago-unam-sustentable",
    site: "cmx",
    title: "Casa del Lago capta su propia lluvia",
    summary:
      "Dos años de obra en el recinto de Chapultepec: 60 mil litros de agua de lluvia por temporada, 60% menos consumo eléctrico y el primer plan integral de este tipo en un centro cultural de la UNAM.",
    date: "2026-08-29",
    category: "Cultura",
    source: {
      name: "Chilango",
      url: "https://www.chilango.com/noticias/casa-del-lago-unam-se-renueva-con-arte-tecnologia-y-sustentabilidad/",
      verifiedOn: "2026-08-30",
    },
    body: [
      "Hay una manera fácil de anunciar que un centro cultural se volvió sustentable: se planta una azotea verde, se toma la foto y se corta el listón. Casa del Lago hizo lo contrario. Los dos años de obra que acaba de terminar no se ven desde el jardín, y el resultado se mide en litros y en kilovatios.",
      "## Los números",
      "El recinto instaló un sistema de <strong>captación de lluvia</strong> que aprovecha los escurrimientos de cerca de <strong>200 metros cuadrados de azoteas</strong>. Durante la temporada puede recolectar hasta <strong>60 mil litros</strong>, destinados a abastecer los módulos sanitarios administrativos.",
      "A eso se suman <strong>paneles solares</strong> e iluminación de alta eficiencia, con los que se prevé reducir alrededor del <strong>60% del consumo eléctrico</strong> del recinto. Los trabajos se hicieron con apoyo de la Tesorería de la UNAM, la Dirección General del Patrimonio Universitario y la Dirección General de Obras y Conservación, y abarcaron espacios artísticos, servicios y sistemas de operación.",
      "Con esto, Casa del Lago se convierte en el <strong>primer centro cultural de la UNAM</strong> en aplicar una estrategia integral de infraestructura con enfoque sustentable.",
      "## Por qué era difícil",
      "Casa del Lago está metida en la primera sección del <strong>Bosque de Chapultepec</strong>, y eso convierte cualquier obra en una negociación con tres cosas a la vez: los árboles, el subsuelo y el reglamento de patrimonio. El edificio abrió como espacio cultural en <strong>1959</strong>, lo que significa que no se le puede tocar la fachada con la libertad con que se toca un inmueble nuevo.",
      "De ahí que la intervención se haya ido al agua y a la energía y no a la imagen. No quedaba mucho más margen. Y de ahí también que sea interesante: es tubería, medidores y bajantes en un edificio al que hay que tratar como monumento mientras se le cambia por dentro.",
      "## Lo que significa para quien va",
      "Poco, y esa es la idea. La programación no cambia, los horarios no cambian y el jardín sigue igual. Lo que cambia es que el recinto deja de gastar lo que gastaba, y que los baños del área administrativa funcionan en temporada de lluvias con agua que cayó en el propio techo.",
      "El dato que conviene guardar es el del 60% eléctrico. Si se cumple, es la clase de cifra que otros recintos universitarios van a tener que explicar por qué no alcanzan.",
      "## El lugar, para quien no lo ubica",
      "Casa del Lago lleva desde 1959 siendo el espacio más experimental de la cultura universitaria: es donde la UNAM prueba lo que todavía no cabe en un museo. Está a la orilla del lago menor de Chapultepec, se entra caminando, y la entrada general es libre.",
    ],
    expertise:
      "La captación de lluvia sólo rinde en temporada, que en la ciudad va de junio a octubre. Los 60 mil litros son un máximo estacional, no un promedio anual, y el sistema alimenta sanitarios administrativos, no todo el recinto. Es una cifra real y acotada &mdash; que es más de lo que suele decirse en un anuncio de este tipo.",
  },
  {
    slug: "metrobus-cierres-por-mantenimiento",
    site: "cmx",
    title: "El Metrobús cerrará 15 estaciones por turnos",
    summary:
      "Líneas 2, 3 y 5, en fines de semana alternados hasta noviembre. Tres de los cierres caen en estaciones de transbordo del Centro, y uno no dura un fin de semana sino dos.",
    date: "2026-08-25",
    category: "Movilidad",
    source: {
      name: "Time Out México",
      url: "https://www.timeoutmexico.mx/ciudad-de-mexico/que-hacer/metrobus-estaciones-cerradas-cdmx-cuales-son",
      verifiedOn: "2026-08-30",
    },
    body: [
      "Las autoridades capitalinas programaron el cierre por mantenimiento de <strong>quince estaciones del Metrobús</strong> repartidas entre las líneas 2, 3 y 5. Los trabajos son de <strong>guías táctiles y cortinas</strong> &mdash; es decir, la franja con relieve que permite a una persona ciega caminar por el andén, y las puertas del propio andén.",
      "El calendario está armado para molestar lo menos posible: los cierres son de dos días, caen en fin de semana y van alternados, de modo que nunca hay dos estaciones contiguas cerradas a la vez. A cambio, se estiran de agosto a noviembre. Conviene leerlo una vez y anotar las tres fechas que le toquen a uno, porque durante esos dos días el autobús <strong>no hace ascenso ni descenso</strong> en la estación, en ambos sentidos: no es una parada saltada de vez en cuando, es la estación fuera de servicio.",
      "## Línea 3, la que toca el Centro",
      "Es el tramo que más gente va a resentir, porque va de Tenayuca a Pueblo Santa Cruz Atoyac cruzando el corazón de la ciudad. El calendario publicado:",
      "<strong>12 y 13 de septiembre</strong>, Obrero Mundial. <strong>19 y 20 de septiembre</strong>, Centro Médico. <strong>26 y 27 de septiembre</strong>, Balderas. <strong>3 y 4 de octubre</strong>, Juárez. <strong>10 y 11 de octubre</strong>, Hidalgo. <strong>17 y 18 de octubre</strong>, Mina. <strong>24 y 25 de octubre</strong>, Guerrero.",
      "Ahí está el detalle que no aparece en el comunicado: <strong>Balderas, Juárez e Hidalgo son transbordo con el Metro</strong>, y caen en tres fines de semana seguidos. Para quien usa el Metrobús justamente para conectar con la red subterránea, octubre trae tres sábados con el enlace roto.",
      "La buena noticia es que en ese tramo las estaciones están cerca unas de otras: entre Juárez e Hidalgo hay menos de un kilómetro, y entre Hidalgo y Mina, otro tanto. La alternativa práctica no es esperar otro autobús, es bajarse en la anterior y caminar diez minutos por Reforma.",
      "## La excepción del calendario",
      "Un cierre no sigue el patrón. <strong>Poniente 128</strong>, también de la línea 3, cierra <strong>del 7 al 20 de noviembre</strong>: dos semanas completas, no un fin de semana. Si es su estación, no es un contratiempo de sábado sino un cambio de rutina de catorce días, y vale la pena resolver el trayecto alterno antes y no el lunes 9 a las siete de la mañana.",
      "## Líneas 2 y 5",
      "La <strong>línea 2</strong>, de Tacubaya a Tepalcates, cerró Amores el 15 y 16 de agosto, Doctor Vértiz el 22 y 23, Centro SCOP el 29 y 30, y le queda <strong>UPIICSA el 5 y 6 de septiembre</strong> &mdash; la única pendiente de esa línea.",
      "La <strong>línea 5</strong>, de Río de los Remedios a Prepa 1, cerró Venustiano Carranza el 15 y 16 de agosto, Barrio San Antonio el 22 y 23, y DIF Xochimilco el 29 y 30. Su calendario ya está cumplido.",
      "## Por qué un mantenimiento de andén se anuncia así",
      "Cambiar una guía táctil obliga a levantar el piso del andén, y una cortina se sustituye con el andén vacío. Ninguna de las dos cosas se hace con gente pasando, y ninguna se hace de noche en dos horas. De ahí el formato: fin de semana completo, estación cerrada, ambos sentidos.",
      "Lo que se repone es, en los dos casos, infraestructura de accesibilidad. Es la clase de obra que sólo nota quien la necesita &mdash; y que, mientras dura, es justamente quien más resiente la estación cerrada.",
    ],
    expertise:
      "Si su estación aparece en la lista, la pregunta útil no es qué día cierra sino cuál es la estación anterior en su sentido. En línea 3 casi siempre está a menos de un kilómetro y el trayecto a pie por Reforma o por el Eje Central es directo. En línea 2, entre UPIICSA y sus vecinas, las distancias son mayores y ahí sí conviene el transbordo.",
  },
  {
    slug: "fin-de-semana-del-31-de-octubre",
    site: "cmx",
    title: "Desfile y Fórmula 1, el mismo fin de semana",
    summary:
      "El Gran Desfile de Día de Muertos y la clasificación del Gran Premio caen a la misma hora del sábado 31 de octubre, en extremos opuestos de la ciudad. Cómo se resuelve.",
    date: "2026-08-30",
    category: "Ciudad",
    source: {
      name: "Time Out México",
      url: "https://www.timeoutmexico.mx/ciudad-de-mexico/que-hacer/gran-premio-de-la-ciudad-de-mexico",
      verifiedOn: "2026-08-30",
    },
    body: [
      "Alguien en r/MexicoCity lo planteó antes que nadie en la prensa, y lo planteó como un problema personal:",
      "> The Day of the Dead parade and Qualifying will both be on Oct 31. This will be my first time to Mexico, and both of these will be new experiences.\n— Publicado en r/MexicoCity, con trece respuestas y ninguna coincidencia entre ellas",
      "Tiene razón en el dato y tiene razón en el dilema. El <strong>sábado 31 de octubre de 2026</strong> la Ciudad de México monta sus dos espectáculos más grandes del año con horas que se encima, en puntos opuestos del mapa, y hasta ahora nadie ha publicado un horario que los ponga uno junto al otro. Esta nota hace eso.",
      "## Qué pasa exactamente ese sábado",
      "El <strong>Gran Desfile de Día de Muertos</strong> recorre Paseo de la Reforma con carros alegóricos, catrinas monumentales y danza. Dura <strong>más de cuatro horas</strong> y avanza despacio, que es como debe verse: no es un desfile para cruzarlo, es uno para quedarse en un punto y dejar que pase entero.",
      "La <strong>clasificación del Gran Premio de la Ciudad de México</strong> es a las <strong>3pm</strong> en el Autódromo Hermanos Rodríguez, en la Ciudad Deportiva, a unos catorce kilómetros del corredor del desfile. Antes hubo Práctica 3 a las 11:30am. Al día siguiente, domingo 1 de noviembre, la carrera es a las 2pm.",
      "Dicho de otra forma: el sábado no es un día con dos eventos. Es un día con dos eventos y un traslado imposible en medio.",
      "## Por qué el traslado es el problema, y no el horario",
      "Podría parecer que basta con salir temprano del desfile. No es así, y la razón es que el desfile <em>es</em> el cierre de calles. Reforma se cierra desde temprano y el operativo se extiende al corredor hacia el Centro. Un coche que quede del lado poniente de ese cierre a la hora de la clasificación no llega al autódromo: no por distancia, sino porque las salidas naturales hacia el oriente pasan justamente por donde está el desfile.",
      "La alternativa que sí funciona es la que el propio circuito publica como acceso: el <strong>Metro Ciudad Deportiva</strong>, de la línea 9, deja a pie del autódromo y no depende de ninguna vialidad de superficie. Desde el corredor del desfile se llega en Metro con un transbordo, y esa es la única versión del plan que no descansa en la suerte.",
      "## Las tres formas sensatas de armar el fin de semana",
      "<strong>Ver el desfile completo y sacrificar la clasificación.</strong> Es la opción para quien nunca ha visto el desfile. La clasificación se transmite y se sabe el resultado en diez minutos; el desfile no se repite hasta el año que viene y no se entiende en video. Quien ya tiene boleto para la carrera del domingo pierde poco.",
      "<strong>Ver la clasificación y agarrar el desfile por el final.</strong> El desfile dura más de cuatro horas y el tramo final, hacia el Zócalo, sigue vivo bastante después de que arrancó. Salir del autódromo en cuanto termine la clasificación y entrar por Metro al Centro alcanza para ver la última hora larga. Se pierde el arranque, que es el mejor tramo.",
      "<strong>Repartir el fin de semana en lugar del día.</strong> Práctica 2 el viernes a las 4pm, desfile el sábado, carrera el domingo a las 2pm. Es la que más gente terminó recomendando en el hilo de Reddit, y es la única que no obliga a elegir: la clasificación es la sesión más fácil de ceder porque la parrilla se sabe igual.",
      "## Lo que todavía no se anuncia",
      "La <strong>temática del desfile 2026</strong> no está publicada. Por la convocatoria de participación se anticipa un homenaje a figuras como José Alfredo Jiménez, Juan Rulfo, Lola Beltrán o Juan Gabriel, pero eso es previsión, no confirmación, y por eso aquí no aparece como un hecho. Lo que sí está confirmado es que habrá instalaciones y ofrendas en las <strong>16 alcaldías</strong>, no sólo sobre el corredor.",
      "Tampoco está publicada la ruta con horarios de paso. Cuando salga, el dato que importa no será por dónde va, sino a qué hora llega a cada punto: es lo que convierte una espera de tres horas en una de veinte minutos.",
    ],
    expertise:
      "El desfile nació de una escena de ficción: la secuencia inicial de <em>Spectre</em>, de 2015, inventó un desfile de Día de Muertos que la ciudad no tenía, y la ciudad lo montó de verdad al año siguiente. Once ediciones después convoca a más de un millón trescientas mil personas. La Fórmula 1, en cambio, lleva en el Hermanos Rodríguez desde 1963 con interrupciones largas. El evento joven es el que cierra Reforma.",
  },
  {
    slug: "plaza-de-la-conchita-jardin-polinizador",
    site: "cmx",
    title: "La Plaza de la Conchita tendrá jardín polinizador",
    summary:
      "Coyoacán interviene 3,352 metros cuadrados de áreas verdes en la Plaza de la Conchita para convertirlas en jardín polinizador, con autorización del INAH y presupuesto participativo.",
    date: "2026-08-28",
    category: "Ciudad",
    source: {
      name: "El Universal Metrópoli",
      url: "https://www.eluniversal.com.mx/metropoli/rehabilitan-plaza-de-la-conchita-en-coyoacan-tendra-nuevo-jardin-polinizador/",
      verifiedOn: "2026-08-30",
    },
    body: [
      "Rehabilitar una plaza del siglo XVI es un ejercicio de contención: casi todo lo que se puede hacer, no se debe. La intervención en la <strong>Plaza de la Conchita</strong> se está haciendo bajo esa regla, y por eso la parte visible es la vegetación y no la obra.",
      "## Qué se está haciendo",
      "La alcaldía Coyoacán interviene <strong>3 mil 352 metros cuadrados de áreas verdes</strong>. Lo que entra es <strong>vegetación endémica</strong>, elegida porque atrae fauna: la meta declarada es convertir el sitio en un <strong>jardín polinizador</strong>.",
      "En paralelo van la limpieza, el mantenimiento y la <strong>restitución de piezas de piedra bola y adoquín</strong> &mdash; es decir, reponer lo que ya había, pieza por pieza, en vez de sustituir el piso.",
      "La intervención cuenta con la <strong>autorización del Instituto Nacional de Antropología e Historia</strong>. Ese permiso es el que define el alcance de todo lo anterior.",
      "## Por qué un jardín polinizador y no un jardín",
      "La diferencia entre los dos es la lista de especies. Un jardín ornamental se elige por cómo se ve; uno polinizador se elige por lo que come: plantas nativas con floración escalonada, para que haya néctar en más meses del año.",
      "En una ciudad donde las áreas verdes están fragmentadas, cada parche de este tipo funciona como escala en una ruta. Un solo jardín no repuebla nada; una cadena de ellos sí, y ésa es la apuesta que está detrás de una obra que en el papel parece jardinería.",
      "## Quién lo paga, y eso importa",
      "El proyecto junta dos bolsas. Una es la obra que hace directamente la demarcación &mdash; vegetación, limpieza, piedra. La otra es <strong>Presupuesto Participativo</strong>, recursos votados y avalados por la comunidad vecinal, destinados al cuidado de las jardineras.",
      "Es una distinción práctica, no burocrática: la primera bolsa construye y la segunda mantiene. Las plazas rehabilitadas suelen fallar en la segunda.",
      "## Lo que la alcaldía dice que está cuidando",
      "> Sus andadores y áreas verdes contribuyen a conservar la imagen tradicional que distingue a este barrio, siendo uno de los principales puntos de encuentro de vecinas, vecinos y turistas, por lo que los trabajos a realizar tienen como objetivo mejorar sus condiciones sin alterar los elementos que forman parte de su identidad.\n— Alcaldía Coyoacán",
      "La frase que hay que subrayar es <em>sin alterar</em>. La Conchita es de los pocos rincones del centro de Coyoacán que todavía se sienten como pueblo y no como corredor turístico, y la manera más rápida de perder eso es mejorarlo demasiado.",
    ],
    expertise:
      "Conviene ir a verla ya empezada y otra vez en unos meses. Un jardín polinizador recién plantado no se parece a lo que va a ser: las especies nativas tardan en cuajar y el resultado se juzga en la segunda temporada de lluvias, no en la inauguración.",
  },
  {
    slug: "semovi-nuevo-contrato-ecobici",
    site: "cmx",
    title: "Semovi endurece el contrato de Ecobici",
    summary:
      "El nuevo contrato de Ecobici corre hasta 2036 y sube el sistema de 9,308 a 15 mil bicicletas. Hoy sólo una de cada diez trae localizador satelital; ahora todas deberán traerlo.",
    date: "2026-08-27",
    category: "Movilidad",
    source: {
      name: "El Universal Metrópoli",
      url: "https://www.eluniversal.com.mx/metropoli/semovi-impone-mas-obligaciones-a-nuevo-contrato-de-ecobici/",
      verifiedOn: "2026-08-30",
    },
    body: [
      "Hay una cifra en el nuevo contrato de Ecobici que explica por qué había que cambiarlo: <strong>sólo una de cada diez bicicletas trae localizador satelital</strong>. El resto del sistema, hasta ahora, se supervisaba sobre todo con los reportes que entregaba el propio proveedor.",
      "## Lo que crece",
      "El contrato fue adjudicado a la empresa <strong>5M2</strong> para operar y ampliar el sistema <strong>hasta 2036</strong>.",
      "Ecobici pasa de <strong>9 mil 308 a 15 mil bicicletas</strong>, y las cicloestaciones de <strong>687 a mil 111</strong>. El sistema llegará a <strong>Iztapalapa, Iztacalco y Tlalpan</strong>, con lo que tendrá presencia en <strong>nueve alcaldías</strong>.",
      "Esas tres alcaldías son la novedad de fondo. Ecobici nació como un sistema del poniente y el centro; extenderlo al oriente y al sur cambia el perfil del viaje que sirve &mdash; menos trayecto corto entre colonias caminables, más conexión hacia el transporte masivo.",
      "## Lo que cambia en las reglas",
      "El secretario de Movilidad, Héctor Ulises García, explicó que la diferencia principal frente al contrato anterior son las <strong>penalizaciones específicas</strong> por retrasos en la reposición de bicicletas y en la adquisición de refacciones.",
      "> Los bienes e insumos pertenecían hoy al prestador del servicio. No existían penalizaciones por retrasos en la reposición de bicicletas o en la adquisición de refacciones. Sólo una de cada 10 bicicletas, el día de hoy, cuenta con localizador satelital.\n— Héctor Ulises García, secretario de Movilidad",
      "Ahora todas las unidades deberán traer <strong>localizador satelital</strong>, y la Semovi podrá supervisar de forma permanente la calidad del servicio en vez de leer informes.",
      "## El taller del sur, que es lo más práctico de la lista",
      "El secretario de Administración y Finanzas, Juan Pablo de Botton, destacó la instalación de un <strong>nuevo taller de mantenimiento en la zona sur</strong>, para que las bicicletas se reparen y vuelvan al servicio más rápido. El contrato también contempla más disponibilidad de refacciones, algunas de importación.",
      "Una bicicleta descompuesta no es una bicicleta menos: es una bicicleta que ocupa un anclaje. El cuello de botella de estos sistemas casi nunca es el número de unidades compradas, sino cuántos días tarda una en volver.",
      "## Flujos de calor",
      "El esquema de seguimiento permitirá evaluar cuántas bicicletas están funcionando y cómo opera el sistema, e incorporará herramientas para definir el <strong>rebalanceo</strong> mediante <em>flujos de calor</em>: mapas que identifican las zonas donde hace falta disponibilidad.",
      "El rebalanceo &mdash; mover bicicletas de donde sobran a donde faltan &mdash; es el trabajo invisible del que depende que una cicloestación tenga algo a las ocho de la mañana. Hacerlo con datos propios y no con la intuición del operador es, en la práctica, el cambio más grande del contrato.",
    ],
    expertise:
      "Las dos cifras que conviene seguir no son las 15 mil bicicletas ni las mil 111 estaciones, sino cuántas unidades están efectivamente operando y cuánto tarda una reparación. Un sistema puede crecer 60% en flota y empeorar para el usuario si la proporción de bicicletas fuera de servicio crece igual.",
  },
  {
    slug: "betsabee-romero-homenaje-a-monsivais",
    site: "cmx",
    title: "Betsabeé Romero arma a Monsiváis en el Estanquillo",
    summary:
      "Salas de lupas, lentes grabados, máscaras de lucha libre y televisores de bulbo: Betsabeé Romero convierte el Museo del Estanquillo en una lectura de Monsiváis. Abrió el 29 de agosto.",
    date: "2026-08-26",
    category: "Arte",
    source: {
      name: "El Universal Cultura",
      url: "https://www.eluniversal.com.mx/cultura/la-artista-betsabee-romero-rinde-homenaje-a-carlos-monsivais-con-nueva-exposicion/",
      verifiedOn: "2026-08-30",
    },
    body: [
      "El Museo del Estanquillo guarda la colección de Carlos Monsiváis y lleva casi veinte años exhibiéndola. En todo ese tiempo nunca había albergado una instalación. La primera es un homenaje al propio Monsiváis, y la firma Betsabeé Romero.",
      "<strong>&laquo;Porque ahora pienso en ti, más que ayer, mucho más&raquo;</strong> abrió el <strong>sábado 29 de agosto a las 12 horas</strong>, en Isabel La Católica 26, Centro Histórico. Se conmemora el <strong>aniversario 16</strong> del fallecimiento del escritor.",
      "## El título es de Juan Gabriel",
      "La frase viene de &laquo;Hasta que te conocí&raquo;. Romero la eligió porque, dice, en estos momentos &mdash;&nbsp;junto con el entusiasmo que hubo en las calles durante el Mundial y la polémica de la inteligencia artificial&nbsp;&mdash; ha pensado en Monsiváis.",
      "Que un homenaje a un cronista se titule con un verso de Juan Gabriel es exactamente el chiste: Monsiváis fue quien insistió en que la cultura popular mexicana era el tema, no el adorno.",
      "## Las salas",
      "Romero adaptó la sala 3 del museo como una serie de habitaciones, cada una sobre un aspecto de la escritura del autor.",
      "<strong>La sala de la lupa feroz</strong> aborda a Monsiváis como memorista, buscador de &laquo;lo desaparecido, lo minúsculo y lo invisible&raquo;: una instalación de lupas con imágenes grabadas que se proyectan sobre libros del autor, en pasajes que las referencian.",
      "<strong>La sala de los lentes</strong> es la más literal y la más conmovedora. Hay lentes grabados con paisajes citadinos que se reflejan sobre unas manos de papel; las líneas de esas manos son en realidad las <strong>líneas de metro que pasan por la colonia Portales</strong>, donde vivió. Las manos llevan curitas: Monsiváis escribía a mano y de tanto hacerlo se lastimaba.",
      "<strong>El Santo y las máscaras de la ciudad</strong> se ocupa de la lucha libre. <strong>La televisión tatuada</strong> es un cuarto de televisores de bulbo cuyas pantallas llevan los rostros de las celebridades sobre las que escribió: Juan Gabriel, María Félix, Salvador Novo.",
      "## Por qué grabado",
      "Romero ha trabajado el grabado en soportes muy distintos, y explica que la técnica conecta con el escritor por la vía del coleccionismo: Monsiváis no reunió pintura, reunió gráfica.",
      "> La gráfica popular, para mí, fue la parte más liberal y propositiva de toda la Escuela Mexicana. También quise hacer homenaje a esa forma de coleccionar, que es coherente hasta en lo que colecciona.\n— Betsabeé Romero",
      "## Cuándo cierra",
      "No hay fecha de cierre publicada, así que aquí no aparece ninguna. Lo que sí está confirmado es la apertura y el domicilio, y que el museo cumple veinte años este año.",
    ],
    expertise:
      "Vale la pena entrar con un libro de Monsiváis leído, cualquiera. Buena parte de la instalación funciona por reconocimiento: las lupas proyectan sobre páginas concretas y los rostros de los televisores son los de sus crónicas. Sin esa lectura previa la sala se ve bien; con ella, se lee.",
  },
];
