import type { NewsItem } from "../types.ts";

export const items: NewsItem[] = [
  {
    slug: "venecia-2026-dos-leones-antes-del-jurado",
    site: "cmx",
    image: "/covers/venecia-2026-dos-leones-antes-del-jurado.jpg",
    imageAlt: "Dos leones de papel dorado colocados frente a un telón, y detrás una fila de asientos vacíos",
    imageKind: "generated",
    imageWidth: 1536,
    imageHeight: 864,
    title: "Venecia entrega dos premios antes de que empiece el festival",
    cardTitle: "Dos Leones antes del jurado",
    titleSeo: "Venecia 2026: Leones de Oro honoríficos",
    summary:
      "La 83ª Mostra abre el 2 de septiembre en el Lido. Los Leones de Oro honoríficos ya tienen dueño: Ellen Burstyn y George Clooney.",
    date: "2026-09-01",
    category: "Cine",
    source: {
      name: "Screen International",
      url: "https://www.screendaily.com/news/venice-film-festival-reveals-2026-lineup/5218820.article",
      verifiedOn: "2026-09-01",
    },
    body: [
      "Un festival con jurado es un festival que dice no saber todavía. Venecia se guarda una excepción: dos premios que decide sola, sin deliberar, y que anuncia antes de proyectar nada",
      "## Los dos nombres",
      "Los <strong>Leones de Oro honoríficos</strong> de 2026 son para <strong>Ellen Burstyn</strong> y <strong>George Clooney</strong>. No compiten contra nadie, no dependen del jurado y no se anuncian al final: son la lectura que el festival hace de una carrera entera",
      "## Lo que sí está en disputa",
      "El resto sigue las reglas normales. La <strong>83ª Mostra</strong> corre del <strong>2 al 12 de septiembre de 2026</strong> en el <strong>Lido</strong>, con <strong>Alberto Barbera</strong> como director artístico. El jurado lo preside <strong>Maggie Gyllenhaal</strong>, con Kaouther Ben Hania, Daniel Blumberg, Francesco Casetti, Xavier Giannoli, Shahrbanoo Sadat y Johnnie To. Siete personas para <strong>veinte títulos</strong>, anunciados el 23 de julio",
      "Abre <strong>Ink</strong>, de <strong>Danny Boyle</strong>, con Guy Pearce. Cierra <strong>God Laughs</strong>, de Giovanni Veronesi. En competencia están Werner Herzog, Martin McDonagh, Hirokazu Koreeda, Lee Chang-dong, Nanni Moretti, Florian Zeller y Shinya Tsukamoto",
      "## Por qué un festival reparte premios que no compiten",
      "Porque mide dos cosas distintas. El León de Oro premia una película: un objeto terminado, comparable con otros diecinueve durante once días. El honorífico premia una permanencia, que ningún jurado reunido para once días puede evaluar",
      "Separarlos también le resuelve un problema práctico. Una carrera de cincuenta años dentro de una competencia la desequilibra: el nombre pesa más que la película que trajo. Sacándolo de la contienda, el festival puede rendirle homenaje sin que eso le cueste el premio a otro",
    ],
    expertise:
      "El honorífico es el que conviene mirar para entender qué está pensando un festival de sí mismo. La competencia la arma un jurado que cambia cada año; los honoríficos los decide la dirección, y ahí se ve qué tradición cree estar continuando. Este año son una actriz del Hollywood de los setenta y un actor que se hizo director: dos versiones de una carrera larga, ninguna de ellas europea",
  },
  {
    slug: "ecobici-15-mil-bicicletas-tres-alcaldias",
    site: "cmx",
    image: "/covers/ecobici-15-mil-bicicletas-tres-alcaldias.jpg",
    imageAlt: "Tres bicicletas de papel recortado en fila, con un arco satelital sobre ellas",
    imageKind: "generated",
    imageWidth: 1536,
    imageHeight: 864,
    title: "Ecobici pasa a 15 mil bicicletas y llega a tres alcaldías nuevas",
    cardTitle: "Ecobici pasa a 15 mil bicicletas",
    titleSeo: "Ecobici pasa a 15 mil bicicletas",
    summary:
      "De 9 308 a 15 000 bicicletas y de 687 a 1 111 cicloestaciones. Iztapalapa, Iztacalco y Tlalpan entran al sistema a partir de septiembre",
    date: "2026-08-28",
    category: "Movilidad",
    source: {
      name: "La Crónica de Hoy",
      url: "https://www.cronica.com.mx/metropoli/2026/08/28/ecobici-crecera-a-15-mil-bicicletas-y-llegara-a-iztapalapa-iztacalco-y-tlalpan/",
      verifiedOn: "2026-09-01",
    },
    body: [
      "El dato que cambia el sistema no es el número de bicicletas. Es que el <strong>100%</strong> de la flota va a llevar localizador satelital, cuando hoy sólo lo tiene el <strong>10%</strong>",
      "## Las cifras",
      "Ecobici pasa de <strong>9 308 a 15 000 bicicletas</strong> &mdash; un aumento de alrededor del <strong>60%</strong> &mdash; y de <strong>687 a 1 111 cicloestaciones</strong>, es decir <strong>424 nuevas</strong>. La transformación arranca en <strong>septiembre de 2026</strong>",
      "## Tres alcaldías que faltaban",
      "El sistema se extiende a <strong>Iztapalapa</strong>, <strong>Iztacalco</strong> y <strong>Tlalpan</strong>, y con ellas pasa de <strong>seis a nueve alcaldías</strong>. Las que ya operaban son Azcapotzalco, Álvaro Obregón, Benito Juárez, Coyoacán, Cuauhtémoc y Miguel Hidalgo",
      "Aquí está el punto de fondo. Esas tres alcaldías concentran cerca de <strong>60 mil viajes diarios en bicicleta</strong>, y sólo Iztapalapa representa el <strong>19%</strong> de los viajes ciclistas de toda la ciudad. Durante quince años el sistema público de bicicletas estuvo donde ya había infraestructura, no donde ya había ciclistas",
      "## Qué cuesta y quién lo paga",
      "El contrato es plurianual a <strong>diez años</strong>, con una inversión máxima anunciada de <strong>2 434 millones de pesos</strong>. El subsidio de la ciudad queda fijo en <strong>135 millones de pesos anuales</strong> durante esos diez años. La membresía anual para el usuario es de <strong>588 pesos</strong>",
      "Un subsidio fijo a diez años con una flota que crece 60% significa, en la práctica, que el costo público por bicicleta baja cada año del contrato. Esa es la apuesta",
      "## El GPS y el problema real",
      "El sistema también abre un <strong>centro de mantenimiento en la zona sur</strong>",
      "El localizador en toda la flota no está ahí para vigilar al usuario: está para el rebalanceo. El defecto cotidiano de cualquier sistema de bicicleta pública es la estación vacía a las ocho de la mañana y llena a las seis de la tarde, y eso se resuelve sabiendo dónde está cada unidad en tiempo real. Con 10% de cobertura eso era una estimación; con 100% es un dato",
      "## Los funcionarios que lo anunciaron",
      "El anuncio corrió a cargo de <strong>Clara Brugada</strong>, jefa de Gobierno de la Ciudad de México, <strong>Héctor Ulises García Nieto</strong>, secretario de Movilidad, y <strong>Juan Pablo de Botton Falcón</strong>, secretario de Administración y Finanzas",
    ],
    expertise:
      "El número a seguir no será el de bicicletas sino el de estaciones llenas en hora pico. Un sistema que crece 60% en flota pero mantiene la misma logística de rebalanceo entrega más bicicletas mal repartidas, no más viajes. El centro de mantenimiento del sur y el GPS al 100% son, en ese sentido, la parte relevante del anuncio",
  },
  {
    slug: "juegos-mundiales-robots-humanoides-2026",
    featured: 1,
    site: "cmx",
    image: "/covers/juegos-mundiales-robots-humanoides-2026.jpg",
    imageAlt: "Un robot de papel recortado a media zancada sobre un carril de pista, con un cronómetro arriba",
    imageKind: "generated",
    imageWidth: 1536,
    imageHeight: 864,
    title: "Un robot corrió los 100 metros en 8.86",
    summary:
      "En los Juegos Mundiales de Robots Humanoides de Pekín, Tiangong Ultra bajó de la marca de Usain Bolt. Hace un año el mismo robot corría los 100 metros en 21.50 segundos.",
    date: "2026-08-30",
    category: "Mundo",
    source: {
      name: "Wikipedia: World Humanoid Robot Games",
      url: "https://en.wikipedia.org/wiki/World_Humanoid_Robot_Games",
      verifiedOn: "2026-08-30",
    },
    body: [
      "La cifra que importa no es <strong>8.86 segundos</strong>. Es <strong>21.50</strong> &mdash; lo que el mismo robot tardaba hace <strong>doce meses</strong>",
      "## Qué son estos juegos",
      "Los <strong>Juegos Mundiales de Robots Humanoides</strong> se celebraron del <strong>22 al 26 de agosto de 2026</strong> en <strong>Pekín</strong>. Compitieron <strong>2 056 robots</strong> de <strong>666 equipos</strong> en <strong>51 pruebas</strong>: 30 competitivas y 21 de escenario. La edición inaugural, en 2025, tuvo 280 equipos y poco más de 500 robots en 26 pruebas",
      "## Las marcas",
      "El robot <strong>Tiangong Ultra</strong> corrió los <strong>100 metros en 8.86 segundos</strong> en una semifinal, por debajo del récord humano de Usain Bolt (<strong>9.58</strong>, de 2009). En los <strong>400 metros</strong> marcó <strong>38.15</strong>, contra el récord humano de 43.03. En <strong>1 500 metros</strong> hizo <strong>2:21.64</strong>. En salto de altura el nuevo récord quedó en <strong>2.88 metros</strong>, 43 centímetros por encima de la marca de Javier Sotomayor",
      "## Por qué no significa lo que parece",
      "Un robot no corre como un humano. No tiene que respirar, no acumula ácido láctico y puede estar diseñado con proporciones que a un cuerpo humano le costarían la espalda. Comparar sus tiempos con los de Bolt es entretenido y no mide lo mismo",
      "Lo que sí mide es la velocidad de mejora. Reducir a la mitad el tiempo de los 100 metros en un año, y triplicar la altura del salto respecto a los 0.95 metros de 2025, describe una curva de progreso que casi ninguna otra área de la robótica tiene",
      "## Lo que siguió sin funcionar",
      "Robots que tropezaron, que se rompieron y alguno que se incendió. Y el reproche que se repitió en la cobertura: corren rapidísimo y todavía no saben conectar un cable. La destreza fina &mdash; agarrar, orientar, insertar &mdash; sigue siendo mucho más difícil que correr en línea recta",
    ],
    expertise:
      "Los récords de velocidad son la parte fotogénica y la menos informativa. Correr es un problema de equilibrio dinámico repetitivo, que el aprendizaje por refuerzo resuelve bien porque se puede simular millones de veces. Manipular objetos del mundo real no se simula igual de bien, y por eso el salto de una prueba a la otra no ocurre solo",
  },
  {
    slug: "s301-la-estrella-mas-rapida",
    site: "cmx",
    image: "/covers/s301-la-estrella-mas-rapida.jpg",
    imageAlt: "Una estrella diminuta que deja una estela curva de puntos al pasar junto a un círculo negro",
    imageKind: "generated",
    imageWidth: 1536,
    imageHeight: 864,
    title: "La estrella más rápida de la Vía Láctea",
    summary:
      "S301 da una vuelta al agujero negro del centro de la galaxia cada 8.7 años, al 8 por ciento de la velocidad de la luz. Es la estrella más rápida registrada, y sirve para medir algo que nunca se ha medido.",
    date: "2026-08-30",
    category: "Mundo",
    source: {
      name: "Smithsonian Magazine",
      url: "https://www.smithsonianmag.com/smart-news/this-star-orbits-our-galaxys-heart-at-a-record-breaking-speed-and-could-help-uncover-secrets-about-the-behemoth-black-hole-there-180989393/",
      verifiedOn: "2026-08-30",
    },
    body: [
      "Una estrella entera moviéndose al <strong>8 por ciento de la velocidad de la luz</strong>. No un fotón, no una partícula: una estrella, con su masa y su tamaño, a <strong>90 millones de kilómetros por hora</strong>",
      "## Qué es S301",
      "Es una estrella que orbita <strong>Sagitario A*</strong>, el agujero negro supermasivo del centro de la Vía Láctea. Completa una vuelta cada <strong>8.7 años</strong>, y en su punto más cercano pasa a sólo <strong>12 veces</strong> la distancia entre la Tierra y el Sol. Es la estrella más rápida registrada en nuestra galaxia",
      "La detectó el <strong>Very Large Telescope Interferometer</strong> del Observatorio Europeo Austral, en Chile, en la primavera de 2023. El estudio se publicó el <strong>19 de agosto de 2026</strong> en <em>Nature</em>, firmado por Stefan Gillessen, del Instituto Max Planck de Física Extraterrestre, y Juan Osorno, del Observatorio de París",
      "## Para qué sirve una estrella así",
      "Para pesar un agujero negro basta con ver cómo giran las cosas a su alrededor. Para saber si <em>gira</em> él mismo, hace falta algo más fino. La relatividad general predice que un agujero negro en rotación arrastra el espacio-tiempo a su alrededor, y que ese arrastre tuerce ligeramente las órbitas cercanas",
      "S301 es la sonda ideal porque pasa muy cerca y muy rápido. Si su órbita se desvía en la próxima década de lo que predice un agujero negro quieto, la desviación mide el giro",
      "> La estrella entra en una dirección, cada vez más rápido, y luego da una vuelta muy cerrada alrededor del agujero negro.\n— Stefan Gillessen, Instituto Max Planck de Física Extraterrestre",
      "El giro de Sagitario A* nunca se ha medido directamente. Ziri Younsi, del University College de Londres, califica el hallazgo de importantísimo: la medición pondría a prueba la relatividad y, de paso, diría algo sobre la historia de la Vía Láctea, porque la rotación de un agujero negro guarda memoria de cómo creció",
      "## El calendario",
      "Nada de esto se resuelve pronto. Hace falta seguir la órbita durante los próximos <strong>diez años</strong> para ver la desviación. Es ciencia de paciencia: la estrella lleva girando ahí desde antes de que existiera el telescopio que la vio, y seguirá girando después",
    ],
    expertise:
      "El número que suele repetirse mal es el 8 por ciento de la velocidad de la luz, como si fuera el récord en sí. Lo interesante es el otro: 8.7 años por vuelta. Una órbita corta significa que un equipo humano puede ver varias completas en una carrera profesional, y ésa es la razón real por la que S301 sirve y otras estrellas más cercanas no",
  },
  {
    slug: "museo-del-gato-reforma",
    featured: 2,
    site: "cmx",
    image: "/covers/museo-del-gato-reforma.jpg",
    imageAlt: "La silueta de un gato enroscado en una ventana iluminada de una fachada de papel",
    imageKind: "generated",
    imageWidth: 1536,
    imageHeight: 864,
    title: "Abrió un museo del gato en Reforma",
    summary:
      "El Museo del Gato abrió el 8 de agosto en Paseo de la Reforma 87, en la Tabacalera. Lo opera La Gatería, el primer café de gatos de América Latina, y financia un programa móvil de esterilización.",
    date: "2026-08-30",
    category: "Ciudad",
    source: {
      name: "Milenio",
      url: "https://www.milenio.com/comunidad/museo-del-gato-en-cdmx-fecha-de-apertura-ubicacion-horarios-costo",
      verifiedOn: "2026-08-30",
    },
    body: [
      "En el número <strong>87 de Paseo de la Reforma</strong>, en la <strong>Tabacalera</strong>, abrió el <strong>8 de agosto</strong> un museo dedicado enteramente al gato doméstico",
      "## Qué es",
      "Lo opera <strong>La Gatería</strong>, que fue el <strong>primer café de gatos de América Latina</strong>. El recorrido mezcla historia, arte y experiencias inmersivas alrededor de una sola especie, y está pensado para visitantes de todas las edades",
      "## Horarios y costo",
      "Abre de <strong>lunes a viernes de 11:00 a 21:00</strong>, <strong>sábados de 10:00 a 21:00</strong> y <strong>domingos de 10:00 a 20:00</strong>. La entrada cuesta <strong>350 pesos</strong> de lunes a jueves y <strong>380 pesos</strong> de viernes a domingo",
      "Conviene tener el dato claro antes de ir: es una atracción privada con precio de atracción privada, no un museo público de los que cuestan entre 40 y 90 pesos. Es una visita que se planea, no una a la que se entra de paso",
      "## La parte que no se ve en el recorrido",
      "El proyecto sostiene un <strong>programa móvil de esterilización</strong> para perros y gatos en situación vulnerable en la Ciudad de México y su periferia. Es la razón por la que el boleto se parece más al de un zoológico que al de una galería: una parte del precio financia una operación que ocurre fuera del edificio",
      "## Dónde queda",
      "Reforma 87 está a la altura de la Tabacalera, entre el Monumento a la Revolución y la Alameda &mdash; una de las pocas zonas de la ciudad donde tres museos quedan a diez minutos caminando uno de otro. El Museo del Gato no compite con ellos; los complementa para quien va con niños y no aguanta dos salas de pintura seguidas",
    ],
    expertise:
      "El costo es lo que decide si la visita vale la pena, y depende de con quién se vaya. Para un adulto solo, 350 pesos por una sola especie es caro contra lo que hay a diez minutos a la redonda. Para una familia con niños que ya no quieren ver otro cuadro, es de las pocas cosas en el centro que se sostiene una hora entera sin negociación",
  },
  {
    slug: "casa-del-lago-unam-sustentable",
    site: "cmx",
    image: "/covers/casa-del-lago-unam-sustentable.jpg",
    imageAlt: "Un techo de pabellón con lluvia de tiras de papel cayendo hacia una cisterna",
    imageKind: "generated",
    imageWidth: 1536,
    imageHeight: 864,
    title: "Casa del Lago capta su propia lluvia",
    summary:
      "Dos años de obra en el recinto de Chapultepec: 60 mil litros de agua de lluvia por temporada, 60% menos consumo eléctrico y el primer plan integral de este tipo en un centro cultural de la UNAM.",
    date: "2026-08-29",
    category: "Cultura",
    source: {
      name: "Chilango",
      url: "https://www.chilango.com/noticias/casa-del-lago-unam-se-renueva-con-arte-tecnologia-y-sustentabilidad/",
      verifiedOn: "2026-08-30",
    },
    body: [
      "Hay una manera fácil de anunciar que un centro cultural se volvió sustentable: se planta una azotea verde, se toma la foto y se corta el listón. Casa del Lago hizo lo contrario. Los dos años de obra que acaba de terminar no se ven desde el jardín, y el resultado se mide en litros y en kilovatios.",
      "## Los números",
      "El recinto instaló un sistema de <strong>captación de lluvia</strong> que aprovecha los escurrimientos de cerca de <strong>200 metros cuadrados de azoteas</strong>. Durante la temporada puede recolectar hasta <strong>60 mil litros</strong>, destinados a abastecer los módulos sanitarios administrativos.",
      "A eso se suman <strong>paneles solares</strong> e iluminación de alta eficiencia, con los que se prevé reducir alrededor del <strong>60% del consumo eléctrico</strong> del recinto. Los trabajos se hicieron con apoyo de la Tesorería de la UNAM, la Dirección General del Patrimonio Universitario y la Dirección General de Obras y Conservación, y abarcaron espacios artísticos, servicios y sistemas de operación.",
      "Con esto, Casa del Lago se convierte en el <strong>primer centro cultural de la UNAM</strong> en aplicar una estrategia integral de infraestructura con enfoque sustentable.",
      "## Por qué era difícil",
      "Casa del Lago está metida en la primera sección del <strong>Bosque de Chapultepec</strong>, y eso convierte cualquier obra en una negociación con tres cosas a la vez: los árboles, el subsuelo y el reglamento de patrimonio. El edificio abrió como espacio cultural en <strong>1959</strong>, lo que significa que no se le puede tocar la fachada con la libertad con que se toca un inmueble nuevo.",
      "De ahí que la intervención se haya ido al agua y a la energía y no a la imagen. No quedaba mucho más margen. Y de ahí también que sea interesante: es tubería, medidores y bajantes en un edificio al que hay que tratar como monumento mientras se le cambia por dentro.",
      "## Lo que significa para quien va",
      "Poco, y esa es la idea. La programación no cambia, los horarios no cambian y el jardín sigue igual. Lo que cambia es que el recinto deja de gastar lo que gastaba, y que los baños del área administrativa funcionan en temporada de lluvias con agua que cayó en el propio techo.",
      "El dato que conviene guardar es el del 60% eléctrico. Si se cumple, es la clase de cifra que otros recintos universitarios van a tener que explicar por qué no alcanzan.",
      "## El lugar, para quien no lo ubica",
      "Casa del Lago lleva desde 1959 siendo el espacio más experimental de la cultura universitaria: es donde la UNAM prueba lo que todavía no cabe en un museo. Está a la orilla del lago menor de Chapultepec, se entra caminando, y la entrada general es libre.",
    ],
    expertise:
      "La captación de lluvia sólo rinde en temporada, que en la ciudad va de junio a octubre. Los 60 mil litros son un máximo estacional, no un promedio anual, y el sistema alimenta sanitarios administrativos, no todo el recinto. Es una cifra real y acotada &mdash; que es más de lo que suele decirse en un anuncio de este tipo.",
  },
  {
    slug: "metrobus-cierres-por-mantenimiento",
    site: "cmx",
    image: "/covers/metrobus-cierres-por-mantenimiento.jpg",
    imageAlt: "Una línea de transporte con estaciones marcadas, cortada por tramos con conos y barreras",
    imageKind: "generated",
    imageWidth: 1536,
    imageHeight: 864,
    title: "El Metrobús cerrará 15 estaciones por turnos",
    cardTitle: "El Metrobús cerrará 15 estaciones",
    summary:
      "Líneas 2, 3 y 5, en fines de semana alternados hasta noviembre. Tres de los cierres caen en estaciones de transbordo del Centro, y uno no dura un fin de semana sino dos.",
    date: "2026-08-25",
    category: "Movilidad",
    source: {
      name: "Time Out México",
      url: "https://www.timeoutmexico.mx/ciudad-de-mexico/que-hacer/metrobus-estaciones-cerradas-cdmx-cuales-son",
      verifiedOn: "2026-08-30",
    },
    body: [
      "Las autoridades capitalinas programaron el cierre por mantenimiento de <strong>quince estaciones del Metrobús</strong> repartidas entre las líneas 2, 3 y 5. Los trabajos son de <strong>guías táctiles y cortinas</strong> &mdash; es decir, la franja con relieve que permite a una persona ciega caminar por el andén, y las puertas del propio andén.",
      "El calendario está armado para molestar lo menos posible: los cierres son de dos días, caen en fin de semana y van alternados, de modo que nunca hay dos estaciones contiguas cerradas a la vez. A cambio, se estiran de agosto a noviembre. Conviene leerlo una vez y anotar las tres fechas que le toquen a uno, porque durante esos dos días el autobús <strong>no hace ascenso ni descenso</strong> en la estación, en ambos sentidos: no es una parada saltada de vez en cuando, es la estación fuera de servicio.",
      "## Línea 3, la que toca el Centro",
      "Es el tramo que más gente va a resentir, porque va de Tenayuca a Pueblo Santa Cruz Atoyac cruzando el corazón de la ciudad. El calendario publicado:",
      "<strong>12 y 13 de septiembre</strong>, Obrero Mundial. <strong>19 y 20 de septiembre</strong>, Centro Médico. <strong>26 y 27 de septiembre</strong>, Balderas. <strong>3 y 4 de octubre</strong>, Juárez. <strong>10 y 11 de octubre</strong>, Hidalgo. <strong>17 y 18 de octubre</strong>, Mina. <strong>24 y 25 de octubre</strong>, Guerrero.",
      "Ahí está el detalle que no aparece en el comunicado: <strong>Balderas, Juárez e Hidalgo son transbordo con el Metro</strong>, y caen en tres fines de semana seguidos. Para quien usa el Metrobús justamente para conectar con la red subterránea, octubre trae tres sábados con el enlace roto.",
      "La buena noticia es que en ese tramo las estaciones están cerca unas de otras: entre Juárez e Hidalgo hay menos de un kilómetro, y entre Hidalgo y Mina, otro tanto. La alternativa práctica no es esperar otro autobús, es bajarse en la anterior y caminar diez minutos por Reforma.",
      "## La excepción del calendario",
      "Un cierre no sigue el patrón. <strong>Poniente 128</strong>, también de la línea 3, cierra <strong>del 7 al 20 de noviembre</strong>: dos semanas completas, no un fin de semana. Si es su estación, no es un contratiempo de sábado sino un cambio de rutina de catorce días, y vale la pena resolver el trayecto alterno antes y no el lunes 9 a las siete de la mañana.",
      "## Líneas 2 y 5",
      "La <strong>línea 2</strong>, de Tacubaya a Tepalcates, cerró Amores el 15 y 16 de agosto, Doctor Vértiz el 22 y 23, Centro SCOP el 29 y 30, y le queda <strong>UPIICSA el 5 y 6 de septiembre</strong> &mdash; la única pendiente de esa línea.",
      "La <strong>línea 5</strong>, de Río de los Remedios a Prepa 1, cerró Venustiano Carranza el 15 y 16 de agosto, Barrio San Antonio el 22 y 23, y DIF Xochimilco el 29 y 30. Su calendario ya está cumplido.",
      "## Por qué un mantenimiento de andén se anuncia así",
      "Cambiar una guía táctil obliga a levantar el piso del andén, y una cortina se sustituye con el andén vacío. Ninguna de las dos cosas se hace con gente pasando, y ninguna se hace de noche en dos horas. De ahí el formato: fin de semana completo, estación cerrada, ambos sentidos.",
      "Lo que se repone es, en los dos casos, infraestructura de accesibilidad. Es la clase de obra que sólo nota quien la necesita &mdash; y que, mientras dura, es justamente quien más resiente la estación cerrada.",
    ],
    expertise:
      "Si su estación aparece en la lista, la pregunta útil no es qué día cierra sino cuál es la estación anterior en su sentido. En línea 3 casi siempre está a menos de un kilómetro y el trayecto a pie por Reforma o por el Eje Central es directo. En línea 2, entre UPIICSA y sus vecinas, las distancias son mayores y ahí sí conviene el transbordo.",
  },
  {
    slug: "fin-de-semana-del-31-de-octubre",
    site: "cmx",
    image: "/covers/fin-de-semana-del-31-de-octubre.jpg",
    imageAlt: "El cuadro partido a la mitad: flores de cempasúchil de un lado, una franja a cuadros del otro",
    imageKind: "generated",
    imageWidth: 1536,
    imageHeight: 864,
    title: "Desfile y Fórmula 1, el mismo fin de semana",
    summary:
      "El Gran Desfile de Día de Muertos y la clasificación del Gran Premio caen a la misma hora del sábado 31 de octubre, en extremos opuestos de la ciudad. Cómo se resuelve.",
    date: "2026-08-30",
    category: "Ciudad",
    source: {
      name: "Time Out México",
      url: "https://www.timeoutmexico.mx/ciudad-de-mexico/que-hacer/gran-premio-de-la-ciudad-de-mexico",
      verifiedOn: "2026-08-30",
    },
    body: [
      "Alguien en r/MexicoCity lo planteó antes que nadie en la prensa, y lo planteó como un problema personal:",
      "> The Day of the Dead parade and Qualifying will both be on Oct 31. This will be my first time to Mexico, and both of these will be new experiences.\n— Publicado en r/MexicoCity, con trece respuestas y ninguna coincidencia entre ellas",
      "Tiene razón en el dato y tiene razón en el dilema. El <strong>sábado 31 de octubre de 2026</strong> la Ciudad de México monta sus dos espectáculos más grandes del año con horas que se encima, en puntos opuestos del mapa, y hasta ahora nadie ha publicado un horario que los ponga uno junto al otro. Esta nota hace eso.",
      "## Qué pasa exactamente ese sábado",
      "El <strong>Gran Desfile de Día de Muertos</strong> recorre Paseo de la Reforma con carros alegóricos, catrinas monumentales y danza. Dura <strong>más de cuatro horas</strong> y avanza despacio, que es como debe verse: no es un desfile para cruzarlo, es uno para quedarse en un punto y dejar que pase entero.",
      "La <strong>clasificación del Gran Premio de la Ciudad de México</strong> es a las <strong>3pm</strong> en el Autódromo Hermanos Rodríguez, en la Ciudad Deportiva, a unos catorce kilómetros del corredor del desfile. Antes hubo Práctica 3 a las 11:30am. Al día siguiente, domingo 1 de noviembre, la carrera es a las 2pm.",
      "Dicho de otra forma: el sábado no es un día con dos eventos. Es un día con dos eventos y un traslado imposible en medio.",
      "## Por qué el traslado es el problema, y no el horario",
      "Podría parecer que basta con salir temprano del desfile. No es así, y la razón es que el desfile <em>es</em> el cierre de calles. Reforma se cierra desde temprano y el operativo se extiende al corredor hacia el Centro. Un coche que quede del lado poniente de ese cierre a la hora de la clasificación no llega al autódromo: no por distancia, sino porque las salidas naturales hacia el oriente pasan justamente por donde está el desfile.",
      "La alternativa que sí funciona es la que el propio circuito publica como acceso: el <strong>Metro Ciudad Deportiva</strong>, de la línea 9, deja a pie del autódromo y no depende de ninguna vialidad de superficie. Desde el corredor del desfile se llega en Metro con un transbordo, y esa es la única versión del plan que no descansa en la suerte.",
      "## Las tres formas sensatas de armar el fin de semana",
      "<strong>Ver el desfile completo y sacrificar la clasificación.</strong> Es la opción para quien nunca ha visto el desfile. La clasificación se transmite y se sabe el resultado en diez minutos; el desfile no se repite hasta el año que viene y no se entiende en video. Quien ya tiene boleto para la carrera del domingo pierde poco.",
      "<strong>Ver la clasificación y agarrar el desfile por el final.</strong> El desfile dura más de cuatro horas y el tramo final, hacia el Zócalo, sigue vivo bastante después de que arrancó. Salir del autódromo en cuanto termine la clasificación y entrar por Metro al Centro alcanza para ver la última hora larga. Se pierde el arranque, que es el mejor tramo.",
      "<strong>Repartir el fin de semana en lugar del día.</strong> Práctica 2 el viernes a las 4pm, desfile el sábado, carrera el domingo a las 2pm. Es la que más gente terminó recomendando en el hilo de Reddit, y es la única que no obliga a elegir: la clasificación es la sesión más fácil de ceder porque la parrilla se sabe igual.",
      "## Lo que todavía no se anuncia",
      "La <strong>temática del desfile 2026</strong> no está publicada. Por la convocatoria de participación se anticipa un homenaje a figuras como José Alfredo Jiménez, Juan Rulfo, Lola Beltrán o Juan Gabriel, pero eso es previsión, no confirmación, y por eso aquí no aparece como un hecho. Lo que sí está confirmado es que habrá instalaciones y ofrendas en las <strong>16 alcaldías</strong>, no sólo sobre el corredor.",
      "Tampoco está publicada la ruta con horarios de paso. Cuando salga, el dato que importa no será por dónde va, sino a qué hora llega a cada punto: es lo que convierte una espera de tres horas en una de veinte minutos.",
    ],
    expertise:
      "El desfile nació de una escena de ficción: la secuencia inicial de <em>Spectre</em>, de 2015, inventó un desfile de Día de Muertos que la ciudad no tenía, y la ciudad lo montó de verdad al año siguiente. Once ediciones después convoca a más de un millón trescientas mil personas. La Fórmula 1, en cambio, lleva en el Hermanos Rodríguez desde 1963 con interrupciones largas. El evento joven es el que cierra Reforma.",
  },
  {
    slug: "plaza-de-la-conchita-jardin-polinizador",
    site: "cmx",
    image: "/covers/plaza-de-la-conchita-jardin-polinizador.jpg",
    imageAlt: "Una plaza vista desde arriba con un área verde recortada, flores, abejas y mariposas",
    imageKind: "generated",
    imageWidth: 1536,
    imageHeight: 864,
    title: "La Plaza de la Conchita tendrá jardín polinizador",
    summary:
      "Coyoacán interviene 3,352 metros cuadrados de áreas verdes en la Plaza de la Conchita para convertirlas en jardín polinizador, con autorización del INAH y presupuesto participativo.",
    date: "2026-08-28",
    category: "Ciudad",
    source: {
      name: "El Universal Metrópoli",
      url: "https://www.eluniversal.com.mx/metropoli/rehabilitan-plaza-de-la-conchita-en-coyoacan-tendra-nuevo-jardin-polinizador/",
      verifiedOn: "2026-08-30",
    },
    body: [
      "Rehabilitar una plaza del siglo XVI es un ejercicio de contención: casi todo lo que se puede hacer, no se debe. La intervención en la <strong>Plaza de la Conchita</strong> se está haciendo bajo esa regla, y por eso la parte visible es la vegetación y no la obra.",
      "## Qué se está haciendo",
      "La alcaldía Coyoacán interviene <strong>3 mil 352 metros cuadrados de áreas verdes</strong>. Lo que entra es <strong>vegetación endémica</strong>, elegida porque atrae fauna: la meta declarada es convertir el sitio en un <strong>jardín polinizador</strong>.",
      "En paralelo van la limpieza, el mantenimiento y la <strong>restitución de piezas de piedra bola y adoquín</strong> &mdash; es decir, reponer lo que ya había, pieza por pieza, en vez de sustituir el piso.",
      "La intervención cuenta con la <strong>autorización del Instituto Nacional de Antropología e Historia</strong>. Ese permiso es el que define el alcance de todo lo anterior.",
      "## Por qué un jardín polinizador y no un jardín",
      "La diferencia entre los dos es la lista de especies. Un jardín ornamental se elige por cómo se ve; uno polinizador se elige por lo que come: plantas nativas con floración escalonada, para que haya néctar en más meses del año.",
      "En una ciudad donde las áreas verdes están fragmentadas, cada parche de este tipo funciona como escala en una ruta. Un solo jardín no repuebla nada; una cadena de ellos sí, y ésa es la apuesta que está detrás de una obra que en el papel parece jardinería.",
      "## Quién lo paga, y eso importa",
      "El proyecto junta dos bolsas. Una es la obra que hace directamente la demarcación &mdash; vegetación, limpieza, piedra. La otra es <strong>Presupuesto Participativo</strong>, recursos votados y avalados por la comunidad vecinal, destinados al cuidado de las jardineras.",
      "Es una distinción práctica, no burocrática: la primera bolsa construye y la segunda mantiene. Las plazas rehabilitadas suelen fallar en la segunda.",
      "## Lo que la alcaldía dice que está cuidando",
      "> Sus andadores y áreas verdes contribuyen a conservar la imagen tradicional que distingue a este barrio, siendo uno de los principales puntos de encuentro de vecinas, vecinos y turistas, por lo que los trabajos a realizar tienen como objetivo mejorar sus condiciones sin alterar los elementos que forman parte de su identidad.\n— Alcaldía Coyoacán",
      "La frase que hay que subrayar es <em>sin alterar</em>. La Conchita es de los pocos rincones del centro de Coyoacán que todavía se sienten como pueblo y no como corredor turístico, y la manera más rápida de perder eso es mejorarlo demasiado.",
    ],
    expertise:
      "Conviene ir a verla ya empezada y otra vez en unos meses. Un jardín polinizador recién plantado no se parece a lo que va a ser: las especies nativas tardan en cuajar y el resultado se juzga en la segunda temporada de lluvias, no en la inauguración.",
  },
  {
    slug: "semovi-nuevo-contrato-ecobici",
    site: "cmx",
    image: "/covers/semovi-nuevo-contrato-ecobici.jpg",
    imageAlt: "Una fila de bicicletas en su anclaje, en capas de papel, con un marcador de posición encima",
    imageKind: "generated",
    imageWidth: 1536,
    imageHeight: 864,
    title: "Semovi endurece el contrato de Ecobici",
    summary:
      "El nuevo contrato de Ecobici corre hasta 2036 y sube el sistema de 9,308 a 15 mil bicicletas. Hoy sólo una de cada diez trae localizador satelital; ahora todas deberán traerlo.",
    date: "2026-08-27",
    category: "Movilidad",
    source: {
      name: "El Universal Metrópoli",
      url: "https://www.eluniversal.com.mx/metropoli/semovi-impone-mas-obligaciones-a-nuevo-contrato-de-ecobici/",
      verifiedOn: "2026-08-30",
    },
    body: [
      "Hay una cifra en el nuevo contrato de Ecobici que explica por qué había que cambiarlo: <strong>sólo una de cada diez bicicletas trae localizador satelital</strong>. El resto del sistema, hasta ahora, se supervisaba sobre todo con los reportes que entregaba el propio proveedor.",
      "## Lo que crece",
      "El contrato fue adjudicado a la empresa <strong>5M2</strong> para operar y ampliar el sistema <strong>hasta 2036</strong>.",
      "Ecobici pasa de <strong>9 mil 308 a 15 mil bicicletas</strong>, y las cicloestaciones de <strong>687 a mil 111</strong>. El sistema llegará a <strong>Iztapalapa, Iztacalco y Tlalpan</strong>, con lo que tendrá presencia en <strong>nueve alcaldías</strong>.",
      "Esas tres alcaldías son la novedad de fondo. Ecobici nació como un sistema del poniente y el centro; extenderlo al oriente y al sur cambia el perfil del viaje que sirve &mdash; menos trayecto corto entre colonias caminables, más conexión hacia el transporte masivo.",
      "## Lo que cambia en las reglas",
      "El secretario de Movilidad, Héctor Ulises García, explicó que la diferencia principal frente al contrato anterior son las <strong>penalizaciones específicas</strong> por retrasos en la reposición de bicicletas y en la adquisición de refacciones.",
      "> Los bienes e insumos pertenecían hoy al prestador del servicio. No existían penalizaciones por retrasos en la reposición de bicicletas o en la adquisición de refacciones. Sólo una de cada 10 bicicletas, el día de hoy, cuenta con localizador satelital.\n— Héctor Ulises García, secretario de Movilidad",
      "Ahora todas las unidades deberán traer <strong>localizador satelital</strong>, y la Semovi podrá supervisar de forma permanente la calidad del servicio en vez de leer informes.",
      "## El taller del sur, que es lo más práctico de la lista",
      "El secretario de Administración y Finanzas, Juan Pablo de Botton, destacó la instalación de un <strong>nuevo taller de mantenimiento en la zona sur</strong>, para que las bicicletas se reparen y vuelvan al servicio más rápido. El contrato también contempla más disponibilidad de refacciones, algunas de importación.",
      "Una bicicleta descompuesta no es una bicicleta menos: es una bicicleta que ocupa un anclaje. El cuello de botella de estos sistemas casi nunca es el número de unidades compradas, sino cuántos días tarda una en volver.",
      "## Flujos de calor",
      "El esquema de seguimiento permitirá evaluar cuántas bicicletas están funcionando y cómo opera el sistema, e incorporará herramientas para definir el <strong>rebalanceo</strong> mediante <em>flujos de calor</em>: mapas que identifican las zonas donde hace falta disponibilidad.",
      "El rebalanceo &mdash; mover bicicletas de donde sobran a donde faltan &mdash; es el trabajo invisible del que depende que una cicloestación tenga algo a las ocho de la mañana. Hacerlo con datos propios y no con la intuición del operador es, en la práctica, el cambio más grande del contrato.",
    ],
    expertise:
      "Las dos cifras que conviene seguir no son las 15 mil bicicletas ni las mil 111 estaciones, sino cuántas unidades están efectivamente operando y cuánto tarda una reparación. Un sistema puede crecer 60% en flota y empeorar para el usuario si la proporción de bicicletas fuera de servicio crece igual.",
  },
  {
    slug: "betsabee-romero-homenaje-a-monsivais",
    site: "cmx",
    image: "/covers/betsabee-romero-homenaje-a-monsivais.jpg",
    imageAlt: "Un muro de objetos enmarcados: lupas, una máscara de luchador y un televisor antiguo",
    imageKind: "generated",
    imageWidth: 1536,
    imageHeight: 864,
    title: "Betsabeé Romero arma a Monsiváis en el Estanquillo",
    summary:
      "Salas de lupas, lentes grabados, máscaras de lucha libre y televisores de bulbo: Betsabeé Romero convierte el Museo del Estanquillo en una lectura de Monsiváis. Abrió el 29 de agosto.",
    date: "2026-08-26",
    category: "Arte",
    source: {
      name: "El Universal Cultura",
      url: "https://www.eluniversal.com.mx/cultura/la-artista-betsabee-romero-rinde-homenaje-a-carlos-monsivais-con-nueva-exposicion/",
      verifiedOn: "2026-08-30",
    },
    body: [
      "El Museo del Estanquillo guarda la colección de Carlos Monsiváis y lleva casi veinte años exhibiéndola. En todo ese tiempo nunca había albergado una instalación. La primera es un homenaje al propio Monsiváis, y la firma Betsabeé Romero.",
      "<strong>&laquo;Porque ahora pienso en ti, más que ayer, mucho más&raquo;</strong> abrió el <strong>sábado 29 de agosto a las 12 horas</strong>, en Isabel La Católica 26, Centro Histórico. Se conmemora el <strong>aniversario 16</strong> del fallecimiento del escritor.",
      "## El título es de Juan Gabriel",
      "La frase viene de &laquo;Hasta que te conocí&raquo;. Romero la eligió porque, dice, en estos momentos &mdash;&nbsp;junto con el entusiasmo que hubo en las calles durante el Mundial y la polémica de la inteligencia artificial&nbsp;&mdash; ha pensado en Monsiváis.",
      "Que un homenaje a un cronista se titule con un verso de Juan Gabriel es exactamente el chiste: Monsiváis fue quien insistió en que la cultura popular mexicana era el tema, no el adorno.",
      "## Las salas",
      "Romero adaptó la sala 3 del museo como una serie de habitaciones, cada una sobre un aspecto de la escritura del autor.",
      "<strong>La sala de la lupa feroz</strong> aborda a Monsiváis como memorista, buscador de &laquo;lo desaparecido, lo minúsculo y lo invisible&raquo;: una instalación de lupas con imágenes grabadas que se proyectan sobre libros del autor, en pasajes que las referencian.",
      "<strong>La sala de los lentes</strong> es la más literal y la más conmovedora. Hay lentes grabados con paisajes citadinos que se reflejan sobre unas manos de papel; las líneas de esas manos son en realidad las <strong>líneas de metro que pasan por la colonia Portales</strong>, donde vivió. Las manos llevan curitas: Monsiváis escribía a mano y de tanto hacerlo se lastimaba.",
      "<strong>El Santo y las máscaras de la ciudad</strong> se ocupa de la lucha libre. <strong>La televisión tatuada</strong> es un cuarto de televisores de bulbo cuyas pantallas llevan los rostros de las celebridades sobre las que escribió: Juan Gabriel, María Félix, Salvador Novo.",
      "## Por qué grabado",
      "Romero ha trabajado el grabado en soportes muy distintos, y explica que la técnica conecta con el escritor por la vía del coleccionismo: Monsiváis no reunió pintura, reunió gráfica.",
      "> La gráfica popular, para mí, fue la parte más liberal y propositiva de toda la Escuela Mexicana. También quise hacer homenaje a esa forma de coleccionar, que es coherente hasta en lo que colecciona.\n— Betsabeé Romero",
      "## Cuándo cierra",
      "No hay fecha de cierre publicada, así que aquí no aparece ninguna. Lo que sí está confirmado es la apertura y el domicilio, y que el museo cumple veinte años este año.",
    ],
    expertise:
      "Vale la pena entrar con un libro de Monsiváis leído, cualquiera. Buena parte de la instalación funciona por reconocimiento: las lupas proyectan sobre páginas concretas y los rostros de los televisores son los de sus crónicas. Sin esa lectura previa la sala se ve bien; con ella, se lee.",
  },
];
