import type { NewsItem } from "../types.ts";

// The group's own feed carries what moves the markets the network operates
// in — not internal plumbing. How leads and CRMs are wired is not news to
// anyone outside the company, and advertising it reads badly to a client.
export const items: NewsItem[] = [
  {
    slug: "uae-fuel-prices-september-2026",
    site: "dst",
    image: "/covers/uae-fuel-prices-september-2026.jpg",
    imageAlt: "Torn paper rectangles standing in a row, each one taller than the last",
    imageKind: "generated",
    imageWidth: 1536,
    imageHeight: 864,
    title: "Diesel jumped 13% on 1 September. Petrol went up about 6%",
    cardTitle: "September fuel prices: diesel +13%",
    titleSeo: "UAE petrol and diesel prices, September 2026",
    summary:
      "Super 98 is Dh3.80, Special 95 is Dh3.69, E-Plus is Dh3.61 and diesel is Dh4.30 a litre. Diesel is the number that matters, and not because of cars.",
    date: "2026-09-01",
    category: "Energy",
    source: {
      name: "Khaleej Times",
      url: "https://www.khaleejtimes.com/business/energy/uae-petrol-diesel-prices-september-2026-announced",
      verifiedOn: "2026-09-02",
    },
    body: [
      "UAE retail fuel prices are reset at the start of each month, and the September 2026 reset is lopsided in a way worth reading properly.",
      "## The prices, from 1 September 2026",
      "<strong>Super 98</strong>: <strong>Dh3.80</strong> a litre, up from Dh3.60 &mdash; a rise of <strong>5.6%</strong>. <strong>Special 95</strong>: <strong>Dh3.69</strong>, up from Dh3.49, a rise of <strong>5.7%</strong>. <strong>E-Plus 91</strong>: <strong>Dh3.61</strong>, up from Dh3.41, a rise of <strong>5.9%</strong>.",
      "Each of the three petrol grades rose by exactly <strong>20 fils</strong>. That is the flat part of the announcement.",
      "## Diesel is the outlier",
      "<strong>Diesel</strong> went to <strong>Dh4.30</strong> a litre from Dh3.80 &mdash; up <strong>50 fils</strong>, a rise of <strong>13.2%</strong>, more than double the petrol move in percentage terms and two and a half times it in fils.",
      "For a private driver that is a rounding error, because most private cars here run on petrol. Diesel is what moves goods: delivery vans, tippers, generators on construction sites, and the trucks that supply every shop and every project in the emirate. A 13% step on that input does not stay in the fuel bill. It arrives later, in smaller pieces, spread across delivery charges and contract prices.",
      "## What it costs a driver",
      "The petrol rise works out at roughly <strong>Dh10 to Dh15</strong> extra on a full tank, depending on whether you are filling a compact car or an SUV. That is a monthly change of a few tens of dirhams for ordinary use &mdash; noticeable on a statement, not on a decision.",
      "The point of tracking it is not the tank. It is that fuel is one of the few local prices published as a clean number on a fixed schedule, which makes it a usable early indicator: it moves before the costs downstream of it do.",
      "## Where the move came from",
      "Khaleej Times attributes the direction to regional supply disruption, including attacks on shipping and oil infrastructure in the Red Sea. Retail fuel here tracks international product prices with a one-month lag by design, which is why the reset arrives as a step on the first of the month rather than as drift.",
      "That lag cuts both ways. A month of falling crude shows up on a forecourt board here at the start of the following month, not the following week.",
    ],
    expertise:
      "If you are budgeting rather than just filling a tank, watch the <strong>diesel-to-petrol gap</strong> rather than either price alone. Diesel now sits <strong>61 fils above Special 95</strong>, having been <strong>31 fils</strong> above it in August &mdash; the spread doubled in one reset. A widening spread is a logistics cost signal, and it is the part of the announcement that reaches people who never buy diesel.",
  },
  {
    slug: "apple-hands-the-company-to-an-engineer",
    site: "dst",
    image: "/covers/apple-hands-the-company-to-an-engineer.jpg",
    imageAlt: "A row of identical paper squares with one lifted out of the line and tilted above it",
    imageKind: "generated",
    imageWidth: 1536,
    imageHeight: 864,
    title: "The biggest company in the world just put a hardware engineer in charge",
    cardTitle: "Apple's new CEO built the hardware",
    titleSeo: "Apple promotes a hardware engineer to CEO",
    summary:
      "John Ternus became Apple's chief executive on 1 September after twenty-five years inside the building. The interesting part is not that Apple replaced its CEO. It is who it did not look for.",
    date: "2026-09-01",
    category: "Tech",
    source: {
      name: "Apple Newsroom",
      url: "https://www.apple.com/newsroom/2026/04/tim-cook-to-become-apple-executive-chairman-john-ternus-to-become-apple-ceo/",
      verifiedOn: "2026-09-02",
    },
    body: [
      "Every succession is an argument about what a company thinks it is. Apple made its argument on <strong>1 September 2026</strong>, when <strong>John Ternus</strong> became chief executive and <strong>Tim Cook</strong> moved to executive chairman after fifteen years in the job.",
      "## Who got the job",
      "Ternus joined Apple in <strong>2001</strong> and had been <strong>senior vice president of Hardware Engineering</strong>: the person responsible for the physical iPhone, iPad, Mac, Apple Watch and AirPods. Twenty-five years inside one company, all of them on the side of the business that has to be manufactured.",
      "That is not the profile the last decade of business writing would have predicted. The received wisdom says a company facing a software problem hires a software answer, preferably from outside, preferably with a mandate to break things.",
      "## What Apple did instead",
      "It promoted the person who makes the objects, and it did so on a schedule announced in public <strong>four and a half months in advance</strong> &mdash; the change was announced on <strong>20 April</strong> and took effect on 1 September.",
      "Cook does not leave. As <strong>executive chairman</strong> he keeps a defined remit that Apple describes as engaging with policymakers around the world &mdash; which is a way of saying the company decided its regulatory relationships were a job in themselves, not a thing a chief executive does between product reviews. <strong>Arthur Levinson</strong>, chairman for the past fifteen years, became lead independent director the same day.",
      "## The inheritance, in numbers",
      "Under Cook, Apple went from a market value of about <strong>$350 billion</strong> to roughly <strong>$4 trillion</strong>. Revenue rose from <strong>$108 billion</strong> in FY2011 to <strong>$416 billion</strong> in FY2025. Services became a business of more than <strong>$100 billion</strong> on its own. The company added over <strong>100,000</strong> employees and now counts more than <strong>2.5 billion</strong> active devices across <strong>200-plus countries and territories</strong>.",
      "Those are the numbers a successor is measured against, and they are the reason the safe-looking choice is not obviously the safe choice. A company that large does not get to grow by another order of magnitude; the next fifteen years will be judged on something other than the chart.",
      "## Why it is worth watching from here",
      "Apple sells in more than two hundred countries and territories, which means this is one of the very few corporate decisions that lands in every market at once, including this one. Nothing changes for anyone buying a phone this week. What changes is who decides what the phone is in 2031.",
    ],
    expertise:
      "The detail worth copying, whatever the size of the company, is the <strong>134 days</strong> between announcement and handover. Succession is usually revealed and executed on the same morning, which tells staff, customers and counterparties that a decision was made without them. A dated handover published in advance converts the same event into a schedule &mdash; and a schedule is something other people can plan around.",
  },
  {
    slug: "186-new-developers-entered-dubai-in-2026",
    site: "dst",
    image: "/covers/186-new-developers-entered-dubai-in-2026.jpg",
    imageAlt: "A dense field of paper tower silhouettes with smaller new ones filling the gaps, a blank licence card in front",
    imageKind: "generated",
    imageWidth: 1536,
    imageHeight: 864,
    title: "186 new developers entered Dubai this year",
    summary:
      "Between January and mid-August 2026 the Dubai Land Department registered 186 new real estate development companies — about 25 a month. 180 of them were licensed by one authority.",
    date: "2026-08-15",
    category: "Market",
    source: {
      name: "Gulf News",
      url: "https://gulfnews.com/business/property/dubai-attracts-186-new-property-developers-in-first-seven-months-of-2026-1.500641994",
      verifiedOn: "2026-09-01",
    },
    body: [
      "A developer count is a duller number than a transaction volume, and a more honest one. Transactions measure what buyers did last quarter; new licences measure what companies believe about the next three years, because a development licence is only worth taking out if you intend to build.",
      "Between the start of 2026 and <strong>mid-August</strong>, <strong>186</strong> new real estate development companies were registered in Dubai, according to Dubai Land Department data. That works out at roughly <strong>25 a month</strong>.",
      "## Where the licences came from",
      "The split is lopsided, and the lopsidedness is the interesting part:",
      "<strong>Department of Economy and Tourism &mdash; 180.</strong> <strong>Trakhees</strong> (Dubai Ports, Customs and Free Zone Corporation) &mdash; <strong>3</strong>. <strong>Mohammed bin Rashid Establishment for Small and Medium Enterprises Development</strong> &mdash; <strong>2</strong>. <strong>Expo City Dubai</strong> &mdash; <strong>1</strong>.",
      "Ninety-seven per cent of the new entrants took the mainland route. That is not the shape a market has when its growth is coming from free-zone structures or offshore holding vehicles &mdash; it is the shape of companies setting up to sell to the emirate&rsquo;s own buyers under the emirate&rsquo;s own regulator.",
      "## What 25 a month actually means",
      "Two readings sit on top of this figure and they do not cancel each other out.",
      "The first is confidence: nobody licenses a development company into a market they expect to thin out. The second is competition. A buyer choosing off-plan in late 2026 is choosing among more names than a buyer in 2024 was, and a meaningful share of those names have no delivered project behind them yet.",
      "## The question a licence does not answer",
      "A development licence says a company may build. It does not say the company has land, funding, a contractor, or an escrow account with anything in it. Those are separate registrations, and the gap between them is where an off-plan buyer&rsquo;s risk actually lives.",
    ],
    expertise:
      "The count of developers is a market-level signal, not a shortlist. Before committing to an off-plan unit from a name registered this year, the two checks worth doing are the project&rsquo;s escrow account number and the developer&rsquo;s completed-project history &mdash; both are on the Dubai Land Department&rsquo;s own systems, and 186 new companies is precisely the reason to do them.",
  },
  {
    slug: "dubai-tokenised-property-secondary-market",
    featured: 1,
    site: "dst",
    image: "/covers/dubai-tokenised-property-secondary-market.jpg",
    imageAlt: "A paper building facade cut into tiles, a few of them floating free",
    imageKind: "generated",
    imageWidth: 1536,
    imageHeight: 864,
    title: "Dubai opens a regulated market for tokenised property",
    cardTitle: "Tokenised property gets a market",
    summary:
      "Fractional stakes in Dubai Land Department title deeds became tradable between investors on February 20, 2026, under VARA supervision — the pilot behind it had drawn investors from over 50 nationalities and more than Dh18.5 million.",
    date: "2026-02-20",
    category: "Crypto",
    source: {
      name: "Gulf News",
      url: "https://gulfnews.com/business/property/prypco-rolls-out-dubai-marketplace-after-nod-for-property-stakes-trading-1.500438076",
      verifiedOn: "2026-08-26",
    },
    body: [
      "On <strong>February 20, 2026</strong> a regulated marketplace opened in Dubai for trading fractional stakes in property already registered with the Dubai Land Department. It runs under the Virtual Assets Regulatory Authority, in partnership with the DLD, and is open to UAE residents over 18 with a valid Emirates ID.",
      "The pilot that preceded it drew investors from more than 50 nationalities and over <strong>Dh18.5 million</strong> in tokenised property investments, with one offering fully funded in one minute and 58 seconds.",
      "The authorities describe the rollout as controlled rather than a broad market opening.",
    ],
    expertise:
      "The part worth noticing is what is being tokenised. This is not a crypto product with property attached — the token points at a title deed in a government registry, and the price is in dirhams. That makes it a liquidity mechanism for an asset class whose defining problem has always been that selling takes months, and it is the government registry, not a blockchain, that makes the claim enforceable. The unresolved question is the same one every fractional scheme meets: a secondary market only prices an asset once there are enough buyers on the other side, and a pilot funded in under two minutes says more about scarcity of supply than about depth of demand.",
  },
  {
    slug: "gitex-moves-to-expo-city-2026",
    featured: 2,
    site: "dst",
    image: "/covers/gitex-moves-to-expo-city-2026.jpg",
    imageAlt: "Two exhibition halls in cut paper with a broad arrow crossing between them",
    imageKind: "generated",
    imageWidth: 1536,
    imageHeight: 864,
    title: "GITEX leaves the World Trade Centre after 45 years",
    cardTitle: "GITEX leaves the World Trade Centre",
    summary:
      "Dubai's largest technology show moves to the Dubai Exhibition Centre at Expo City for its 2026 edition, and shifts from its long-standing October slot to December 7–11.",
    date: "2025-10-08",
    category: "Tech",
    source: {
      name: "Dubai Media Office",
      url: "https://mediaoffice.ae/en/news/2025/october/08-10/gitex-global-to-begin-a-new-chapter-at-expo-city-dubai-in-2026",
      verifiedOn: "2026-08-26",
    },
    body: [
      "GITEX GLOBAL leaves Dubai World Trade Centre, its home for 45 years, for the Dubai Exhibition Centre at Expo City Dubai. The 2026 edition runs <strong>December 7–11</strong> — the summit day at DWTC on the 7th, the exhibition at Expo City from the 8th.",
      "The new venue is around 1.5 times the size of the old one. The organisers put the expected 2026 scale at more than 200,000 attendees from over 180 countries, 6,800 exhibiting companies and 400+ government entities.",
      "Gulfood moves to the same venue in 2026.",
    ],
    expertise:
      "Two things change here for anyone planning around the show, and only one of them is the address. The October slot had been fixed long enough that half the region's product launches, funding announcements and hiring rounds were timed against it; moving to December pushes all of that into the last weeks of the financial year. The venue change is the smaller story — a bigger hall for a show that had outgrown its old one — but the calendar change is the one that quietly reshuffles a year of planning, and the attendance figures above are projections, not a count.",
  },
  {
    slug: "dubai-property-sales-h1-2026",
    site: "dst",
    title: "Dubai property sales reach Dh286b in H1",
    summary:
      "Dubai recorded Dh286.43 billion of property sales across 79,229 transactions in the first half of 2026 — an average of 433 sales and about Dh1.57 billion changing hands every day.",
    date: "2026-07-14",
    category: "Market",
    image: "/news/dubai-property-h1-2026.svg",
    imageAlt:
      "Dubai property sales in H1 2026: Dh286.43 billion across 79,229 transactions, 433 sales a day, with January at Dh72.16 billion against June at Dh32.66 billion.",
    imageKind: "diagram",
    imageCredit: "DST",
    imageWidth: 1200,
    imageHeight: 600,
    imageNarrow: "/news/dubai-property-h1-2026-narrow.svg",
    source: {
      name: "Khaleej Times",
      url: "https://www.khaleejtimes.com/business/dubai-property-sales-hit-dh286b-as-market-momentum-stays-strong-in-h1-2026",
      verifiedOn: "2026-08-25",
    },
    body: [
      "Dubai closed the first half of 2026 with <strong>Dh286.43 billion</strong> in property sales across 79,229 transactions — roughly 433 sales a day and close to Dh1.57 billion changing hands daily.",
      "January was the strongest month of the period, at Dh72.16 billion across 15,896 transactions. June closed with 13,766 sales worth Dh32.66 billion.",
    ],
    expertise:
      "The two published months are worth dividing out. January averaged Dh4.54 million per sale; June averaged Dh2.37 million. So while transactions fell 13% between them, value fell 55% — the gap is the average ticket, which fell 48%. On those figures the market shifted toward cheaper stock rather than simply slowing down. Two months are not a trend, and summer is reliably the quieter half of a Dubai year, but it is the average ticket that carries the information here: a headline total mixes price and volume together and hides which one moved.",
  },
];
