import type { NewsItem } from "../types.ts";

// The group's own feed carries what moves the markets the network operates
// in — not internal plumbing. How leads and CRMs are wired is not news to
// anyone outside the company, and advertising it reads badly to a client.
export const items: NewsItem[] = [
  {
    slug: "the-detector-for-claudes-watermark-is-not-for-you",
    site: "dst",
    image: "/covers/the-detector-for-claudes-watermark-is-not-for-you.jpg",
    imageAlt: "A sealed paper envelope beside an open one of the same size, its flap folded back",
    imageKind: "generated",
    imageWidth: 1536,
    imageHeight: 864,
    title: "Claude marks everything it writes, and almost nobody can read the mark",
    cardTitle: "Marked text, private detector",
    titleSeo: "Claude's watermark and who can read it",
    summary:
      "Anthropic began watermarking Claude's output on 2 August. The mark is in the model's word choices, and the tool that reads it is in private preview.",
    date: "2026-09-08",
    category: "AI",
    source: {
      name: "Anthropic",
      url: "https://www.anthropic.com/news/claude-text-watermark",
      verifiedOn: "2026-09-08",
    },
    body: [
      "Two things shipped this summer, and only one of them shipped to everyone. Every model Anthropic has launched since <strong>2 August 2026</strong> marks the text it writes. The tool that reads the mark went to a list.",
      "## What the mark is",
      "Not a phrase, not a character, not a header. At each step the model has several words that would do, and it picks with a random number; the change, set out in an explainer on <strong>14 August 2026</strong>, is that the randomness now comes from a <strong>secret key</strong> plus the words already on the page. The output reads the same. The pattern of choices is the signal, and without the key it is indistinguishable from an ordinary run of the model.",
      "It applies to the <strong>API</strong> and the apps alike, including through <strong>AWS</strong>, <strong>Google Cloud</strong> and <strong>Microsoft Foundry</strong>, in every country rather than only where a regulator asked for it. There is no switch.",
      "## Who gets the reader",
      "The detection API is in <strong>private preview</strong>: regulators, law enforcement, media, fact-checkers, independent researchers, educational organisations, EU civil society groups, and firms with their own compliance obligations. That is a considered decision, not a staged rollout — a public detector would let anyone edit a text, test it, edit again, and stop the instant it came back clean.",
      "## The asymmetry is the story",
      "For everyone outside the list, the practical position is new and slightly strange: the text in front of you may carry a verdict about its own origin, and you have no way to ask for it. Provenance stops being something a reader can check and becomes a service an institution requests — on its own subjects, on its own timetable.",
      "## What it will not settle",
      "A hit means the text <em>may</em> have passed through Claude. The signal thins where the model had few real alternatives — dense fact, figures, code — and a short passage has too little of it to read. It survives copying and light editing; translation or a genuine rewrite takes it off. Images and vector files are handled by a different mechanism entirely, <strong>C2PA</strong> provenance metadata, which a screenshot removes.",
    ],
    expertise:
      "For anyone whose business rests on published text, the useful move is not to hunt for the mark but to keep your own record. Detection you cannot run is detection you cannot plan around, and reconstructing after the fact — which draft came from where, what was edited by hand, which source was checked on which day — is far harder than writing it down at the time. That record is also the thing a regulator, a client or a court actually asks for, and unlike a watermark it survives translation, paraphrase and a change of file format. Treat the watermark as somebody else's evidence and your own log as yours.",
  },

  {
    slug: "dubai-property-passes-half-a-trillion-in-eight-months",
    site: "dst",
    image: "/covers/dubai-property-passes-half-a-trillion-in-eight-months.jpg",
    imageAlt: "A tall stack of thin paper bars on a slate ground, the topmost bar shorter than the one below it, a single brass rule drawn across the stack",
    imageKind: "generated",
    imageWidth: 1536,
    imageHeight: 864,
    title: "Dubai property passed half a trillion dirhams before September began",
    cardTitle: "Half a trillion in eight months",
    titleSeo: "Dubai property: Dh523bn in eight months",
    summary:
      "January to August closed at Dh523.44 billion across 148,564 transactions. August alone was Dh46.22 billion — and sales were barely more than half of it.",
    date: "2026-09-07",
    category: "Real estate",
    source: {
      name: "Voice of Emirates",
      url: "https://www.voiceofemirates.com/en/business/business-reports/2026/09/01/sales-recorded-349-83-billion-dirhams-aed-523-44-billion-in-dubai-real-estate-transactions-in-8-months/",
      verifiedOn: "2026-09-07",
    },
    body: [
      "The headline number is the one nobody can hold in their head, so start with the one you can: in August, Dubai registered a property transaction roughly every three minutes of the working month.",
      "## The eight months",
      "From January to the end of August the emirate recorded <strong>Dh523.44 billion</strong> across <strong>148,564 transactions</strong>. Sales were <strong>Dh349.83 billion</strong> over 112,020 of them; mortgages <strong>Dh134.34 billion</strong> over 30,645; gifts <strong>Dh39.27 billion</strong> over 5,899.",
      "## August on its own",
      "<strong>Dh46.22 billion</strong> across <strong>15,960 transactions</strong>. Sales accounted for <strong>Dh27.89 billion</strong> and 11,600 of them — 10,124 residential units, 684 buildings, 793 plots of land. Mortgages added Dh14.36 billion, gifts Dh3.97 billion.",
      "## The number that is not about buying",
      "A third of the eight-month value is not a sale at all. <strong>Dh134.34 billion of mortgages</strong> is money moving against property that already has an owner, and <strong>Dh39.27 billion of gifts</strong> is property changing hands inside families without a price. Read only the sales line and you have described two thirds of the market.",
      "## What it does not say",
      "None of this is a price. Value and count together give an average, and an average across villas on the Palm and studios in Jumeirah Village Circle describes nothing anyone can buy. The figure that moves a decision is the price per square foot in one tower, and that is not in this release.",
    ],
    expertise:
      "The mortgage share is the line worth watching month to month, because it is the one that responds to something other than sentiment. Sales volume can be pushed by a launch calendar — a developer opening a tower moves thousands of transactions in a week — but mortgage value tracks what banks will lend against, and banks re-underwrite continuously. When mortgage value grows faster than sales value, the existing stock is being revalued upward; when it lags, new supply is carrying the market on payment plans rather than on credit. Eight months in, the two are moving close enough together that neither is telling a story the other contradicts.",
  },

  {
    slug: "openai-ships-gpt-6-astra",
    site: "dst",
    image: "/covers/openai-ships-gpt-6-astra.jpg",
    imageAlt: "Six paper rectangles in a row on a slate blue ground, each one taller than the one before it, the last of them in warm amber",
    imageKind: "generated",
    imageWidth: 1536,
    imageHeight: 864,
    title: "OpenAI’s new model is built to use a computer, not to chat",
    cardTitle: "GPT-6 Astra is out",
    titleSeo: "GPT-6 Astra: price, availability, benchmarks",
    summary:
      "GPT-6 Astra shipped on 3 September at $10 and $50 per million tokens, through the OpenAI API, Microsoft Azure and AWS Bedrock. It is not top of every table, and enterprise access is off by default.",
    date: "2026-09-06",
    category: "AI",
    source: {
      name: "OpenAI",
      url: "https://openai.com/index/gpt-6-astra/",
      verifiedOn: "2026-09-06",
    },
    body: [
      "The benchmark that says most about this release is not a maths score. It is <strong>72.6%</strong> on a computer-use test that the previous model passed at 65.7% — while taking about <strong>47% less time per task</strong>, roughly forty minutes instead of seventy-five. That is a procurement number, not a research one.",
      "## What shipped, and where",
      "<strong>OpenAI</strong> released <strong>GPT-6 Astra</strong> on <strong>3 September 2026</strong>, first to a limited set of organisations and then to ChatGPT <strong>Plus, Pro, Business and Enterprise</strong> users. For developers it is <strong>gpt-6-astra</strong> in the OpenAI API, and it is also available through <strong>Microsoft Azure</strong> and <strong>Amazon Bedrock</strong>.",
      "One line matters for anyone running a workspace: <strong>enterprise access is off by default at launch</strong>, and an administrator has to turn it on.",
      "## What it costs",
      "<strong>$10 per million input tokens and $50 per million output tokens</strong> at standard rates, with separate rates for cache reads and writes. A <strong>Fast mode</strong> in the API runs up to twice the speed at twice the price. Usage is included in existing subscription allowances, with credits available on top.",
      "## What it is actually for",
      "Long tasks in real software, rather than answers in a chat window. OpenAI reports <strong>59.3%</strong> on Agents’ Last Exam — professional work in real applications, from financial modelling to media production — against 55.5% for Claude Opus 5 and 53.6% for its own previous model, while using about <strong>65% fewer output tokens</strong>. On <strong>BenchCAD</strong>, which asks a model to rebuild a 3D object as CAD code, it reports <strong>95.9%</strong> at an estimated API cost roughly 43% below its predecessor.",
      "The company also claims a <strong>1.9×</strong> faster completion of browser tasks when the model is paired with an updated Codex harness.",
      "## Where it is not first",
      "Worth reading before anyone quotes a clean sweep. On <strong>Humanity’s Last Exam</strong> with tools, Astra scores <strong>57.2%</strong> — below <strong>Claude Fable 5.1</strong> at 65.0% and below two other Claude models in the same table. On the <strong>Artificial Analysis Intelligence Index</strong> it scores <strong>61.2</strong> against Fable 5.1’s 65.7. The gains are concentrated in computer use, coding and science, and OpenAI’s own tables say so.",
      "## The security clause",
      "Astra is the first model OpenAI has classified as meeting the <strong>Critical threshold in cybersecurity</strong> under its Preparedness Framework. It scored <strong>100%</strong> on ExploitBench, and during an internal evaluation it found and used <strong>two previously unknown vulnerabilities</strong>, which OpenAI says it is disclosing to the maintainers. The shipped model refuses the more advanced offensive tasks, and extra safety checks can pause or stop a job mid-run — in the API, the task simply stops.",
    ],
    expertise:
      "For a business the useful frame is not «is it smarter» but «what does an hour of it cost, and who signs off». Three things follow from this release. First, the price is a specialist’s: at $50 per million output tokens nobody should be routing a support inbox through it, and the efficiency claims — fewer output tokens, less wall-clock time per task — are the argument for using it on long agentic work where a cheaper model burns the saving in retries. Second, the availability path runs through Azure and Bedrock, which for most regulated buyers is the only path that clears procurement at all; the API listing is the easy part. Third, plan for the interruptions: OpenAI is explicit that the new safety checks can pause or stop legitimate work, and that in the API a stopped task does not resume. Any workflow you build on this needs to survive being halted halfway, which is a design constraint rather than a footnote.",
  },

  {
    slug: "dld-puts-the-developer-journey-in-one-place",
    site: "dst",
    image: "/covers/dld-puts-the-developer-journey-in-one-place.jpg",
    imageAlt: "Three separate paper forms on a slate ground merging into a single wider sheet, a thin brass line running through all of them",
    imageKind: "generated",
    imageWidth: 1536,
    imageHeight: 864,
    title: "Dubai Land Department folds project registration, sales and escrow into one platform",
    cardTitle: "One platform for the developer journey",
    titleSeo: "DLD launches Initial Registration for developers",
    summary:
      "‘Initial Registration’ went live on 3 September. Project registration, transaction registration and escrow oversight stop being three separate errands.",
    date: "2026-09-06",
    category: "Real estate",
    source: {
      name: "Dubai Land Department",
      url: "https://dubailand.gov.ae/en/news-media/dubai-land-department-launches-initial-registration-a-smarter-journey-for-developers-and-greater-efficiency-for-the-real-estate-sector/",
      verifiedOn: "2026-09-06",
    },
    body: [
      "The most expensive thing in a developer’s back office is not a fee. It is the same set of facts being typed into three systems that do not speak to one another.",
      "## What launched",
      "On <strong>3 September 2026</strong> the <strong>Dubai Land Department</strong> launched <strong>Initial Registration</strong>, a platform that consolidates <strong>project registration</strong>, <strong>real estate transaction registration</strong> and <strong>escrow account management</strong> into a single connected journey.",
      "A component called <strong>Project 360</strong> gives a consolidated view of escrow accounts and project financial data, with the stated aim of reducing discrepancies between sales records, escrow records and ownership records.",
      "## Who said what",
      "<strong>Eng. Abdullah Ahmed Al Shehi</strong>, CEO of the Real Estate Regulatory Agency (RERA) at DLD: «The launch of the ‘Initial Registration’ platform represents an investment in the real estate sector’s efficiency and readiness for its next phase of growth.»",
      "DLD frames it against the federal target announced by <strong>Sheikh Mohammed bin Rashid Al Maktoum</strong>: <strong>50% of government sectors, services and operations</strong> running through autonomous AI within two years.",
      "## The part that matters commercially",
      "Escrow is where off-plan risk actually lives. A buyer’s money sits in an account governed by construction milestones, and every dispute in an off-plan sale eventually becomes an argument about whether the sales ledger, the escrow ledger and the ownership register agree. Putting all three behind one interface does not make them agree by itself — but it makes disagreement visible to the regulator on the day it appears rather than at audit.",
    ],
    expertise:
      "For anyone operating on the buy side, the useful question is what this changes about diligence. Nothing in the announcement alters a buyer’s rights: escrow rules, milestone releases and the register are the same law they were last week. What changes is the speed at which a mismatch surfaces — and mismatches are how off-plan projects fail quietly for months before they fail publicly. The second-order effect is on small developers. A consolidated platform with defined user permissions and separate roles for submitting and reviewing transactions is easy for a firm with a compliance department and a real cost for a firm where one person does everything; the migration is where that shows up. Watch whether DLD publishes a phased onboarding schedule, because the interval when some developers are on the new platform and some are on the old one is exactly the interval when records diverge.",
  },

  {
    slug: "brent-is-forty-four-per-cent-above-last-september",
    site: "dst",
    image: "/covers/brent-is-forty-four-per-cent-above-last-september.jpg",
    imageAlt: "A stepped column of cream paper bars rising steeply on a slate ground, the topmost bar cut back slightly at its right edge",
    imageKind: "generated",
    imageWidth: 1536,
    imageHeight: 864,
    title: "Brent is 44% above where it was a year ago",
    cardTitle: "Brent is 44% above last September",
    titleSeo: "Brent crude at $96.90: a year’s move in context",
    summary:
      "Brent traded at $96.90 on 4 September, down 2.5% on the day but up 11% on the month and 44% on the year. The pump price rise of 1 September was the local edge of this.",
    date: "2026-09-05",
    category: "Market",
    source: {
      name: "Fortune",
      url: "https://fortune.com/article/price-of-oil-09-04-2026/",
      verifiedOn: "2026-09-06",
    },
    body: [
      "A daily oil price tells you almost nothing. The same number read against last year tells you what every budget in the region is being rewritten around.",
      "## The number",
      "<strong>Brent crude</strong> stood at <strong>$96.90 a barrel</strong> on <strong>4 September 2026</strong>: <strong>down 2.49%</strong> on the day, <strong>up 10.98%</strong> against a month earlier, and <strong>up 43.98%</strong> against <strong>$67.30</strong> a year before.",
      "## What that does locally",
      "It is the same curve that produced the <strong>1 September</strong> pump revision in the UAE, where diesel rose about <strong>13%</strong> and petrol about <strong>6%</strong> in one monthly step. Fuel here is repriced monthly against the market rather than smoothed, so a year like this arrives in twelve visible instalments rather than invisibly.",
      "## Why the daily move is the least interesting part",
      "A 2.5% fall in a session is noise on a market that has moved 44% in a year. The trend is what changes behaviour: logistics contracts written on last year’s assumptions are being repriced, freight surcharges are back in commercial conversations, and any project with a long procurement tail has a fuel line that no longer matches its feasibility study.",
      "## The other side of the same coin",
      "For a Gulf economy the price is not simply a cost. High crude widens fiscal room, supports state capital spending and tends to show up in construction pipelines and hiring twelve to eighteen months later — which is why the region’s reaction to an oil rally is never the same as Europe’s.",
    ],
    expertise:
      "The trap in a year-on-year figure is the base. September 2025 was a soft month for crude, so part of the 44% is where the comparison starts rather than where the market has gone; the month-on-month rise of about 11% is the harder number, because it has no base effect to hide behind. For anyone building a 2027 budget in this market, the practical move is to stop forecasting the price and start writing contracts that survive being wrong about it — fuel escalation clauses with a published index, and freight quotes with a stated validity window rather than an assumed one. And treat the pump as a lagging indicator, not a signal: the UAE’s monthly reset means the retail number you see on 1 October is a report on September, not a forecast of October.",
  },

  {
    slug: "dmcc-gives-lab-grown-diamonds-their-own-desk",
    site: "dst",
    image: "/covers/dmcc-gives-lab-grown-diamonds-their-own-desk.jpg",
    imageAlt: "Two cut-paper gem shapes side by side on a slate ground, one pale grey-blue and one cream, a thin brass line between them",
    imageKind: "generated",
    imageWidth: 1536,
    imageHeight: 864,
    title: "DMCC splits lab-grown diamonds off into a trading desk of their own",
    cardTitle: "Lab-grown diamonds get their own desk",
    titleSeo: "DMCC gives lab-grown diamonds their own desk",
    summary:
      "UAE lab-grown diamond volumes rose 91.5% in a year to 76.9 million carats. DMCC has stopped treating them as a footnote to the natural stone trade.",
    date: "2026-09-03",
    category: "Trade",
    source: {
      name: "Dubai Government Media Office",
      url: "https://www.mediaoffice.ae/en/news/2026/august/30-08/dmcc-establishes-lab-grown-diamond-sector-as-uae-trade-hits-recod",
      verifiedOn: "2026-09-03",
    },
    body: [
      "A market gets its own desk when the old desk stops describing it. On 30 August the <strong>DMCC</strong> gave lab-grown diamonds one.",
      "## What changed",
      "DMCC has established a <strong>Lab-Grown Diamond Vertical</strong> as a standalone platform, separate from the natural diamond and coloured stone activities it had been filed under. The stated reason is that the two have different economics: one is mined, and one is manufactured and therefore scalable.",
      "## The numbers behind it",
      "UAE lab-grown diamond trade reached <strong>76.9 million carats</strong> in 2025, a <strong>91.5% increase</strong> year on year. Volumes have risen <strong>109% since 2022</strong>, when they stood at 36.8 million carats.",
      "Value moved differently. The trade was worth <strong>$1.3 billion</strong>, up <strong>7.5%</strong> — volume nearly doubling while value rose by single digits is the price curve doing what a manufactured good's price curve does.",
      "For scale, the UAE's total diamond trade was <strong>$41.7 billion</strong> in 2025. Lab-grown is about three per cent of that by value and a great deal more than that by carat.",
      "## Why a vertical rather than a category",
      "<strong>Ahmed Bin Sulayem</strong>, DMCC's Executive Chairman and CEO, put it as a question of infrastructure rather than of taste: lab-grown diamonds, he said, have reached the point where they need dedicated market infrastructure and a distinct economic case of their own.",
      "The practical content of that is grading, certification, storage and dispute rules written for a product whose supply is a function of factory capacity rather than of geology.",
    ],
    expertise:
      "The divergence between the two figures is the whole story and it is easy to misread. A 91.5% rise in carats against a 7.5% rise in value means the average price per carat fell sharply over the year — which is what happens to any manufactured good as production capacity catches up with demand, and is not by itself a sign of weak demand. The reason a separate vertical matters commercially is that a falling unit price is intolerable inside a category whose valuation conventions were written for a scarce good: the same warehouse and financing terms cannot serve both. For anyone setting up a stones business in a DMCC free zone, the change to watch for is whether the licence activity list splits in the same way the vertical has.",
  },

  {
    slug: "gitex-2026-lands-in-december",
    site: "dst",
    image: "/covers/gitex-2026-lands-in-december.jpg",
    imageAlt: "Twelve pale paper rectangles in a row on deep blue, the last three lifted onto a higher line",
    imageKind: "generated",
    imageWidth: 1536,
    imageHeight: 864,
    title: "GITEX has moved to December, and that changes the season",
    cardTitle: "GITEX is a December show now",
    titleSeo: "GITEX Global 2026: 7–11 December, Expo City",
    summary:
      "The show that owned Dubai's October for forty-five years now runs 7–11 December at Expo City. October's hotel week has lost its anchor tenant.",
    date: "2026-09-02",
    category: "Tech",
    source: {
      name: "Dubai Media Office",
      url: "https://mediaoffice.ae/en/news/2025/october/13-10/gitex-global-2026",
      verifiedOn: "2026-09-02",
    },
    body: [
      "A trade show changing venue is administrative news. A trade show changing <em>month</em> is a different thing entirely, because a city's hotel rates, flight loads and meeting calendars are built around it.",
      "## The dates",
      "<strong>GITEX Global 2026</strong> runs <strong>7–11 December</strong> at the <strong>Dubai Exhibition Centre in Expo City Dubai</strong>. The <strong>GITEX Scale Summit</strong> opens the week on <strong>7 December</strong>; the exhibition floor is open <strong>8–11 December</strong>.",
      "This follows the move already announced in October 2025, when the show confirmed it was leaving the Dubai World Trade Centre after <strong>forty-five years</strong>. What was not obvious at the time is that the venue change came with a calendar change.",
      "## Why the month matters more than the address",
      "October in Dubai has been GITEX month since the 1980s. Hotels priced against it, adjacent conferences scheduled themselves to catch its arrivals, and a great deal of business that had nothing to do with technology was transacted in the fortnight around it.",
      "December is a different market. It sits inside the high season proper, when leisure demand is already strong and rooms are already expensive. A business event landing in that window competes with holiday traffic rather than creating its own.",
      "## What is genuinely uncertain",
      "Two things nobody can answer yet. First, whether October retains a technology anchor or simply loses one. Second, whether the exhibitors who treated GITEX as the end of the third quarter adjust their own product cycles, or quietly deprioritise a show that no longer lands where their financial year does.",
      "Both will be visible in the 2027 announcements, not in this year's floor plan.",
    ],
    expertise:
      "For anyone booking around it: the useful number is not the exhibition dates but the two days either side of them. Expo City is a considerable distance from the Deira and Bur Dubai hotel stock that historically absorbed GITEX overflow, and the Red Line takes roughly forty minutes from Union to the Expo terminus. Proximity is priced accordingly, and the December high season means there is no soft pricing to fall back on.",
  },
  {
    slug: "296-homes-above-ten-million-dollars",
    site: "dst",
    image: "/covers/296-homes-above-ten-million-dollars.jpg",
    imageAlt: "Two upright paper strips, one cream and one orange, standing on a torn cream sheet against deep blue",
    imageKind: "generated",
    imageWidth: 1536,
    imageHeight: 864,
    title: "Dubai sold 296 homes above $10m in six months",
    cardTitle: "296 sales above $10m in half a year",
    summary:
      "Knight Frank's half-year count puts $5.1bn of $10m-plus deals on the record for H1 2026 — up 16% in number and 14% in value on last year.",
    date: "2026-09-02",
    category: "Market",
    source: {
      name: "Knight Frank",
      url: "https://www.knightfrank.ae/research",
      verifiedOn: "2026-09-02",
    },
    body: [
      "The headline number for Dubai property is usually total sales volume, which mostly measures how much stock was released. The more revealing number is much smaller: how many homes changed hands above ten million dollars.",
      "## The count",
      "<strong>296</strong> sales above <strong>$10m</strong> in the first half of 2026, worth <strong>$5.1bn</strong> in total. That is <strong>16% more transactions</strong> and <strong>14% more value</strong> than the same period last year. The split across quarters was <strong>165 in Q1</strong> and <strong>131 in Q2</strong>.",
      "Above <strong>$25m</strong>, the second quarter recorded <strong>26 sales</strong> — a record for a single quarter.",
      "## Where they were",
      "<strong>Dubai Hills Estate</strong> accounted for <strong>51</strong> of the 296, the largest single concentration. Average prices across the segment rose about <strong>9%</strong> year on year.",
      "## What the quarterly split actually says",
      "165 falling to 131 looks like a slowdown, and it may be one. It is worth noting the alternative reading before treating it as a trend: at this price the market is thin enough that a handful of individual transactions moves the quarterly figure by double digits, and the $25m-plus record sits inside the weaker quarter.",
      "Value rising more slowly than volume — 14% against 16% — is the number that carries more information. It means the average $10m-plus sale was slightly cheaper this year than last. More buyers, marginally smaller cheques.",
    ],
    expertise:
      "Read the 14%-versus-16% gap before the headline. When count grows faster than value in a luxury segment, the entry band is filling up faster than the top — more homes clearing the $10m line, not more homes selling far above it. That is what a broadening market looks like, and it is a different condition from the one where a few trophy sales carry the total.",
  },
  {
    slug: "middle-east-energy-2026-opens",
    site: "dst",
    image: "/covers/middle-east-energy-2026-opens.jpg",
    imageAlt: "A dense block of small amber paper squares set on a pale panel against a deep blue ground",
    imageKind: "generated",
    imageWidth: 1536,
    imageHeight: 864,
    title: "Middle East Energy opened this week with 1,900 exhibitors",
    cardTitle: "1,900 exhibitors, three days, one hall",
    titleSeo: "Middle East Energy 2026 opens in Dubai",
    summary:
      "The power-sector show marks fifty years at the World Trade Centre from 1 to 3 September, with 35,000 expected from more than 150 countries.",
    date: "2026-09-01",
    category: "Energy",
    source: {
      name: "Middle East Energy",
      url: "https://www.middleeast-energy.com/",
      verifiedOn: "2026-09-02",
    },
    body: [
      "Dubai's exhibition calendar restarts in September, and it restarts with power.",
      "## The event",
      "<strong>Middle East Energy</strong> runs <strong>1–3 September 2026</strong> at the <strong>Dubai World Trade Centre</strong>, marking <strong>fifty years</strong> of the show. The organisers expect more than <strong>1,900 exhibitors</strong> and over <strong>35,000 attendees</strong> from more than <strong>150 countries</strong>, with <strong>250-plus speakers</strong> across the conference programme.",
      "## Why a fifty-year-old trade show is still the regional benchmark",
      "Energy events elsewhere have fragmented into renewables shows, grid shows and hydrogen shows that barely speak to one another. This one has stayed a single floor covering generation, transmission and distribution, storage, and the consumption side.",
      "That matters in a region where the same utility is often buying all of it at once. The Gulf's transition is not a replacement of one system by another; it is a very large conventional grid absorbing solar at speed while demand keeps climbing. Vendors who only sell one half of that are not much use to the buyer.",
      "## The number to keep",
      "150 countries against 1,900 exhibitors is the ratio worth noting. This is not a domestic market with international guests; it is a sourcing floor where the buying is regional and the supply chain is global. That is also why September works as a date — it is the start of the procurement year for utilities whose peak load has just passed.",
    ],
    expertise:
      "The half-century framing is a marketing line, but the venue choice is not. Staying at the World Trade Centre in the year GITEX leaves it for Expo City tells you which shows still need Sheikh Zayed Road and the Metro on their doorstep. A trade floor whose visitors arrive in fleets of company cars behaves differently from one whose visitors arrive alone.",
  },
  {
    slug: "international-property-show-2026",
    site: "dst",
    image: "/covers/international-property-show-2026.jpg",
    imageAlt: "Three upright paper rectangles in teal, pale blue and gold standing apart on a slate ground",
    imageKind: "generated",
    imageWidth: 1536,
    imageHeight: 864,
    title: "The International Property Show returns for a 22nd year",
    cardTitle: "IPS 2026: three days, five halls",
    titleSeo: "International Property Show 2026 in Dubai",
    summary:
      "IPS runs 7–9 September across five halls at the World Trade Centre, timed to Dubai Land Department's own calendar and co-located with AIM Congress.",
    date: "2026-09-02",
    category: "Market",
    source: {
      name: "International Property Show",
      url: "https://www.ipsdubai.ae/",
      verifiedOn: "2026-09-02",
    },
    body: [
      "Property exhibitions are usually sales floors dressed as conferences. This one is worth reading differently, because of who stands behind it.",
      "## The dates",
      "<strong>IPS 2026</strong> runs <strong>7–9 September</strong> in <strong>Halls 4–8</strong> of the <strong>Dubai World Trade Centre</strong>. It is the <strong>22nd edition</strong>, and it is co-located with the <strong>AIM Congress</strong>, the investment-promotion event.",
      "## The detail that changes how you read it",
      "IPS is aligned with the <strong>Dubai Land Department</strong>. That alignment is the reason it is not simply a bigger version of a developer roadshow: the regulator's own calendar — registration reforms, escrow rules, brokerage licensing — tends to surface at it before it surfaces anywhere else.",
      "The co-location with AIM Congress points the same way. AIM is about attracting foreign direct investment at a national level; putting a residential property show next to it treats housing as part of the investment case for the country, not as a separate consumer market.",
      "## What to actually watch for",
      "Not the launches. Developers launch continuously and a September stand tells you nothing a July press release did not. The useful signal at a regulator-aligned show is procedural: what the Land Department says about registration, off-plan protections and broker conduct, and whether any of it comes with a date attached.",
    ],
    expertise:
      "Five halls for a 22nd-edition show is a size worth pausing on. Dubai's property exhibitions have historically ballooned during release cycles and shrunk when supply tightened, so hall count is a rough proxy for how much unsold inventory needs a shop window. Compare it against the same show's footprint in previous years rather than against other events this month.",
  },
  {
    slug: "uae-fuel-prices-september-2026",
    site: "dst",
    image: "/covers/uae-fuel-prices-september-2026.jpg",
    imageAlt: "Torn paper rectangles standing in a row, each one taller than the last",
    imageKind: "generated",
    imageWidth: 1536,
    imageHeight: 864,
    title: "Diesel jumped 13% on 1 September. Petrol went up about 6%",
    cardTitle: "September fuel prices: diesel +13%",
    titleSeo: "UAE petrol and diesel prices, September 2026",
    summary:
      "Super 98 is Dh3.80, Special 95 is Dh3.69, E-Plus is Dh3.61 and diesel is Dh4.30 a litre. Diesel is the number that matters, and not because of cars.",
    date: "2026-09-01",
    category: "Energy",
    source: {
      name: "Khaleej Times",
      url: "https://www.khaleejtimes.com/business/energy/uae-petrol-diesel-prices-september-2026-announced",
      verifiedOn: "2026-09-02",
    },
    body: [
      "UAE retail fuel prices are reset at the start of each month, and the September 2026 reset is lopsided in a way worth reading properly.",
      "## The prices, from 1 September 2026",
      "<strong>Super 98</strong>: <strong>Dh3.80</strong> a litre, up from Dh3.60 — a rise of <strong>5.6%</strong>. <strong>Special 95</strong>: <strong>Dh3.69</strong>, up from Dh3.49, a rise of <strong>5.7%</strong>. <strong>E-Plus 91</strong>: <strong>Dh3.61</strong>, up from Dh3.41, a rise of <strong>5.9%</strong>.",
      "Each of the three petrol grades rose by exactly <strong>20 fils</strong>. That is the flat part of the announcement.",
      "## Diesel is the outlier",
      "<strong>Diesel</strong> went to <strong>Dh4.30</strong> a litre from Dh3.80 — up <strong>50 fils</strong>, a rise of <strong>13.2%</strong>, more than double the petrol move in percentage terms and two and a half times it in fils.",
      "For a private driver that is a rounding error, because most private cars here run on petrol. Diesel is what moves goods: delivery vans, tippers, generators on construction sites, and the trucks that supply every shop and every project in the emirate. A 13% step on that input does not stay in the fuel bill. It arrives later, in smaller pieces, spread across delivery charges and contract prices.",
      "## What it costs a driver",
      "The petrol rise works out at roughly <strong>Dh10 to Dh15</strong> extra on a full tank, depending on whether you are filling a compact car or an SUV. That is a monthly change of a few tens of dirhams for ordinary use — noticeable on a statement, not on a decision.",
      "The point of tracking it is not the tank. It is that fuel is one of the few local prices published as a clean number on a fixed schedule, which makes it a usable early indicator: it moves before the costs downstream of it do.",
      "## Where the move came from",
      "Khaleej Times attributes the direction to regional supply disruption, including attacks on shipping and oil infrastructure in the Red Sea. Retail fuel here tracks international product prices with a one-month lag by design, which is why the reset arrives as a step on the first of the month rather than as drift.",
      "That lag cuts both ways. A month of falling crude shows up on a forecourt board here at the start of the following month, not the following week.",
    ],
    expertise:
      "If you are budgeting rather than just filling a tank, watch the <strong>diesel-to-petrol gap</strong> rather than either price alone. Diesel now sits <strong>61 fils above Special 95</strong>, having been <strong>31 fils</strong> above it in August — the spread doubled in one reset. A widening spread is a logistics cost signal, and it is the part of the announcement that reaches people who never buy diesel.",
  },
  {
    slug: "apple-hands-the-company-to-an-engineer",
    site: "dst",
    image: "/covers/apple-hands-the-company-to-an-engineer.jpg",
    imageAlt: "A row of identical paper squares with one lifted out of the line and tilted above it",
    imageKind: "generated",
    imageWidth: 1536,
    imageHeight: 864,
    title: "The biggest company in the world just put a hardware engineer in charge",
    cardTitle: "Apple's new CEO built the hardware",
    titleSeo: "Apple promotes a hardware engineer to CEO",
    summary:
      "John Ternus became Apple's chief executive on 1 September after twenty-five years inside the building. The interesting part is not that Apple replaced its CEO. It is who it did not look for.",
    date: "2026-09-01",
    category: "Tech",
    source: {
      name: "Apple Newsroom",
      url: "https://www.apple.com/newsroom/2026/04/tim-cook-to-become-apple-executive-chairman-john-ternus-to-become-apple-ceo/",
      verifiedOn: "2026-09-02",
    },
    body: [
      "Every succession is an argument about what a company thinks it is. Apple made its argument on <strong>1 September 2026</strong>, when <strong>John Ternus</strong> became chief executive and <strong>Tim Cook</strong> moved to executive chairman after fifteen years in the job.",
      "## Who got the job",
      "Ternus joined Apple in <strong>2001</strong> and had been <strong>senior vice president of Hardware Engineering</strong>: the person responsible for the physical iPhone, iPad, Mac, Apple Watch and AirPods. Twenty-five years inside one company, all of them on the side of the business that has to be manufactured.",
      "That is not the profile the last decade of business writing would have predicted. The received wisdom says a company facing a software problem hires a software answer, preferably from outside, preferably with a mandate to break things.",
      "## What Apple did instead",
      "It promoted the person who makes the objects, and it did so on a schedule announced in public <strong>four and a half months in advance</strong> — the change was announced on <strong>20 April</strong> and took effect on 1 September.",
      "Cook does not leave. As <strong>executive chairman</strong> he keeps a defined remit that Apple describes as engaging with policymakers around the world — which is a way of saying the company decided its regulatory relationships were a job in themselves, not a thing a chief executive does between product reviews. <strong>Arthur Levinson</strong>, chairman for the past fifteen years, became lead independent director the same day.",
      "## The inheritance, in numbers",
      "Under Cook, Apple went from a market value of about <strong>$350 billion</strong> to roughly <strong>$4 trillion</strong>. Revenue rose from <strong>$108 billion</strong> in FY2011 to <strong>$416 billion</strong> in FY2025. Services became a business of more than <strong>$100 billion</strong> on its own. The company added over <strong>100,000</strong> employees and now counts more than <strong>2.5 billion</strong> active devices across <strong>200-plus countries and territories</strong>.",
      "Those are the numbers a successor is measured against, and they are the reason the safe-looking choice is not obviously the safe choice. A company that large does not get to grow by another order of magnitude; the next fifteen years will be judged on something other than the chart.",
      "## Why it is worth watching from here",
      "Apple sells in more than two hundred countries and territories, which means this is one of the very few corporate decisions that lands in every market at once, including this one. Nothing changes for anyone buying a phone this week. What changes is who decides what the phone is in 2031.",
    ],
    expertise:
      "The detail worth copying, whatever the size of the company, is the <strong>134 days</strong> between announcement and handover. Succession is usually revealed and executed on the same morning, which tells staff, customers and counterparties that a decision was made without them. A dated handover published in advance converts the same event into a schedule — and a schedule is something other people can plan around.",
  },
  {
    slug: "186-new-developers-entered-dubai-in-2026",
    site: "dst",
    image: "/covers/186-new-developers-entered-dubai-in-2026.jpg",
    imageAlt: "A dense field of paper tower silhouettes with smaller new ones filling the gaps, a blank licence card in front",
    imageKind: "generated",
    imageWidth: 1536,
    imageHeight: 864,
    title: "186 new developers entered Dubai this year",
    summary:
      "Between January and mid-August 2026 the Dubai Land Department registered 186 new real estate development companies — about 25 a month. 180 of them were licensed by one authority.",
    date: "2026-08-15",
    category: "Market",
    source: {
      name: "Gulf News",
      url: "https://gulfnews.com/business/property/dubai-attracts-186-new-property-developers-in-first-seven-months-of-2026-1.500641994",
      verifiedOn: "2026-09-01",
    },
    body: [
      "A developer count is a duller number than a transaction volume, and a more honest one. Transactions measure what buyers did last quarter; new licences measure what companies believe about the next three years, because a development licence is only worth taking out if you intend to build.",
      "Between the start of 2026 and <strong>mid-August</strong>, <strong>186</strong> new real estate development companies were registered in Dubai, according to Dubai Land Department data. That works out at roughly <strong>25 a month</strong>.",
      "## Where the licences came from",
      "The split is lopsided, and the lopsidedness is the interesting part:",
      "<strong>Department of Economy and Tourism — 180.</strong> <strong>Trakhees</strong> (Dubai Ports, Customs and Free Zone Corporation) — <strong>3</strong>. <strong>Mohammed bin Rashid Establishment for Small and Medium Enterprises Development</strong> — <strong>2</strong>. <strong>Expo City Dubai</strong> — <strong>1</strong>.",
      "Ninety-seven per cent of the new entrants took the mainland route. That is not the shape a market has when its growth is coming from free-zone structures or offshore holding vehicles — it is the shape of companies setting up to sell to the emirate’s own buyers under the emirate’s own regulator.",
      "## What 25 a month actually means",
      "Two readings sit on top of this figure and they do not cancel each other out.",
      "The first is confidence: nobody licenses a development company into a market they expect to thin out. The second is competition. A buyer choosing off-plan in late 2026 is choosing among more names than a buyer in 2024 was, and a meaningful share of those names have no delivered project behind them yet.",
      "## The question a licence does not answer",
      "A development licence says a company may build. It does not say the company has land, funding, a contractor, or an escrow account with anything in it. Those are separate registrations, and the gap between them is where an off-plan buyer’s risk actually lives.",
    ],
    expertise:
      "The count of developers is a market-level signal, not a shortlist. Before committing to an off-plan unit from a name registered this year, the two checks worth doing are the project’s escrow account number and the developer’s completed-project history — both are on the Dubai Land Department’s own systems, and 186 new companies is precisely the reason to do them.",
  },
  {
    slug: "dubai-tokenised-property-secondary-market",
    featured: 1,
    site: "dst",
    image: "/covers/dubai-tokenised-property-secondary-market.jpg",
    imageAlt: "A paper building facade cut into tiles, a few of them floating free",
    imageKind: "generated",
    imageWidth: 1536,
    imageHeight: 864,
    title: "Dubai opens a regulated market for tokenised property",
    cardTitle: "Tokenised property gets a market",
    summary:
      "Fractional stakes in Dubai Land Department title deeds became tradable between investors on February 20, 2026, under VARA supervision — the pilot behind it had drawn investors from over 50 nationalities and more than Dh18.5 million.",
    date: "2026-02-20",
    category: "Crypto",
    source: {
      name: "Gulf News",
      url: "https://gulfnews.com/business/property/prypco-rolls-out-dubai-marketplace-after-nod-for-property-stakes-trading-1.500438076",
      verifiedOn: "2026-08-26",
    },
    body: [
      "On <strong>February 20, 2026</strong> a regulated marketplace opened in Dubai for trading fractional stakes in property already registered with the Dubai Land Department. It runs under the Virtual Assets Regulatory Authority, in partnership with the DLD, and is open to UAE residents over 18 with a valid Emirates ID.",
      "The pilot that preceded it drew investors from more than 50 nationalities and over <strong>Dh18.5 million</strong> in tokenised property investments, with one offering fully funded in one minute and 58 seconds.",
      "The authorities describe the rollout as controlled rather than a broad market opening.",
    ],
    expertise:
      "The part worth noticing is what is being tokenised. This is not a crypto product with property attached — the token points at a title deed in a government registry, and the price is in dirhams. That makes it a liquidity mechanism for an asset class whose defining problem has always been that selling takes months, and it is the government registry, not a blockchain, that makes the claim enforceable. The unresolved question is the same one every fractional scheme meets: a secondary market only prices an asset once there are enough buyers on the other side, and a pilot funded in under two minutes says more about scarcity of supply than about depth of demand.",
  },
  {
    slug: "gitex-moves-to-expo-city-2026",
    featured: 2,
    site: "dst",
    image: "/covers/gitex-moves-to-expo-city-2026.jpg",
    imageAlt: "Two exhibition halls in cut paper with a broad arrow crossing between them",
    imageKind: "generated",
    imageWidth: 1536,
    imageHeight: 864,
    title: "GITEX leaves the World Trade Centre after 45 years",
    cardTitle: "GITEX leaves the World Trade Centre",
    summary:
      "Dubai's largest technology show moves to the Dubai Exhibition Centre at Expo City for its 2026 edition, and shifts from its long-standing October slot to December 7–11.",
    date: "2025-10-08",
    category: "Tech",
    source: {
      name: "Dubai Media Office",
      url: "https://mediaoffice.ae/en/news/2025/october/08-10/gitex-global-to-begin-a-new-chapter-at-expo-city-dubai-in-2026",
      verifiedOn: "2026-08-26",
    },
    body: [
      "GITEX GLOBAL leaves Dubai World Trade Centre, its home for 45 years, for the Dubai Exhibition Centre at Expo City Dubai. The 2026 edition runs <strong>December 7–11</strong> — the summit day at DWTC on the 7th, the exhibition at Expo City from the 8th.",
      "The new venue is around 1.5 times the size of the old one. The organisers put the expected 2026 scale at more than 200,000 attendees from over 180 countries, 6,800 exhibiting companies and 400+ government entities.",
      "Gulfood moves to the same venue in 2026.",
    ],
    expertise:
      "Two things change here for anyone planning around the show, and only one of them is the address. The October slot had been fixed long enough that half the region's product launches, funding announcements and hiring rounds were timed against it; moving to December pushes all of that into the last weeks of the financial year. The venue change is the smaller story — a bigger hall for a show that had outgrown its old one — but the calendar change is the one that quietly reshuffles a year of planning, and the attendance figures above are projections, not a count.",
  },
  {
    slug: "dubai-property-sales-h1-2026",
    site: "dst",
    title: "Dubai property sales reach Dh286b in H1",
    summary:
      "Dubai recorded Dh286.43 billion of property sales across 79,229 transactions in the first half of 2026 — an average of 433 sales and about Dh1.57 billion changing hands every day.",
    date: "2026-07-14",
    category: "Market",
    image: "/news/dubai-property-h1-2026.svg",
    imageAlt:
      "Dubai property sales in H1 2026: Dh286.43 billion across 79,229 transactions, 433 sales a day, with January at Dh72.16 billion against June at Dh32.66 billion.",
    imageKind: "diagram",
    imageCredit: "DST",
    imageWidth: 1200,
    imageHeight: 600,
    imageNarrow: "/news/dubai-property-h1-2026-narrow.svg",
    source: {
      name: "Khaleej Times",
      url: "https://www.khaleejtimes.com/business/dubai-property-sales-hit-dh286b-as-market-momentum-stays-strong-in-h1-2026",
      verifiedOn: "2026-08-25",
    },
    body: [
      "Dubai closed the first half of 2026 with <strong>Dh286.43 billion</strong> in property sales across 79,229 transactions — roughly 433 sales a day and close to Dh1.57 billion changing hands daily.",
      "January was the strongest month of the period, at Dh72.16 billion across 15,896 transactions. June closed with 13,766 sales worth Dh32.66 billion.",
    ],
    expertise:
      "The two published months are worth dividing out. January averaged Dh4.54 million per sale; June averaged Dh2.37 million. So while transactions fell 13% between them, value fell 55% — the gap is the average ticket, which fell 48%. On those figures the market shifted toward cheaper stock rather than simply slowing down. Two months are not a trend, and summer is reliably the quieter half of a Dubai year, but it is the average ticket that carries the information here: a headline total mixes price and volume together and hides which one moved.",
  },
];
