import type { NewsItem } from "../types.ts";

// The group's own feed carries what moves the markets the network operates
// in — not internal plumbing. How leads and CRMs are wired is not news to
// anyone outside the company, and advertising it reads badly to a client.
export const items: NewsItem[] = [
  {
    slug: "dmcc-gives-lab-grown-diamonds-their-own-desk",
    site: "dst",
    image: "/covers/dmcc-gives-lab-grown-diamonds-their-own-desk.jpg",
    imageAlt: "Two cut-paper gem shapes side by side on a slate ground, one pale grey-blue and one cream, a thin brass line between them",
    imageKind: "generated",
    imageWidth: 1536,
    imageHeight: 864,
    title: "DMCC splits lab-grown diamonds off into a trading desk of their own",
    cardTitle: "Lab-grown diamonds get their own desk",
    titleSeo: "DMCC gives lab-grown diamonds their own desk",
    summary:
      "UAE lab-grown diamond volumes rose 91.5% in a year to 76.9 million carats. DMCC has stopped treating them as a footnote to the natural stone trade.",
    date: "2026-09-03",
    category: "Trade",
    source: {
      name: "Dubai Government Media Office",
      url: "https://www.mediaoffice.ae/en/news/2026/august/30-08/dmcc-establishes-lab-grown-diamond-sector-as-uae-trade-hits-recod",
      verifiedOn: "2026-09-03",
    },
    body: [
      "A market gets its own desk when the old desk stops describing it. On 30 August the <strong>DMCC</strong> gave lab-grown diamonds one.",
      "## What changed",
      "DMCC has established a <strong>Lab-Grown Diamond Vertical</strong> as a standalone platform, separate from the natural diamond and coloured stone activities it had been filed under. The stated reason is that the two have different economics: one is mined, and one is manufactured and therefore scalable.",
      "## The numbers behind it",
      "UAE lab-grown diamond trade reached <strong>76.9 million carats</strong> in 2025, a <strong>91.5% increase</strong> year on year. Volumes have risen <strong>109% since 2022</strong>, when they stood at 36.8 million carats.",
      "Value moved differently. The trade was worth <strong>$1.3 billion</strong>, up <strong>7.5%</strong> &mdash; volume nearly doubling while value rose by single digits is the price curve doing what a manufactured good's price curve does.",
      "For scale, the UAE's total diamond trade was <strong>$41.7 billion</strong> in 2025. Lab-grown is about three per cent of that by value and a great deal more than that by carat.",
      "## Why a vertical rather than a category",
      "<strong>Ahmed Bin Sulayem</strong>, DMCC's Executive Chairman and CEO, put it as a question of infrastructure rather than of taste: lab-grown diamonds, he said, have reached the point where they need dedicated market infrastructure and a distinct economic case of their own.",
      "The practical content of that is grading, certification, storage and dispute rules written for a product whose supply is a function of factory capacity rather than of geology.",
    ],
    expertise:
      "The divergence between the two figures is the whole story and it is easy to misread. A 91.5% rise in carats against a 7.5% rise in value means the average price per carat fell sharply over the year — which is what happens to any manufactured good as production capacity catches up with demand, and is not by itself a sign of weak demand. The reason a separate vertical matters commercially is that a falling unit price is intolerable inside a category whose valuation conventions were written for a scarce good: the same warehouse and financing terms cannot serve both. For anyone setting up a stones business in a DMCC free zone, the change to watch for is whether the licence activity list splits in the same way the vertical has.",
  },

  {
    slug: "gitex-2026-lands-in-december",
    site: "dst",
    image: "/covers/gitex-2026-lands-in-december.jpg",
    imageAlt: "Twelve pale paper rectangles in a row on deep blue, the last three lifted onto a higher line",
    imageKind: "generated",
    imageWidth: 1536,
    imageHeight: 864,
    title: "GITEX has moved to December, and that changes the season",
    cardTitle: "GITEX is a December show now",
    titleSeo: "GITEX Global 2026: 7–11 December, Expo City",
    summary:
      "The show that owned Dubai's October for forty-five years now runs 7–11 December at Expo City. October's hotel week has lost its anchor tenant.",
    date: "2026-09-02",
    category: "Tech",
    source: {
      name: "Dubai Media Office",
      url: "https://mediaoffice.ae/en/news/2025/october/13-10/gitex-global-2026",
      verifiedOn: "2026-09-02",
    },
    body: [
      "A trade show changing venue is administrative news. A trade show changing <em>month</em> is a different thing entirely, because a city's hotel rates, flight loads and meeting calendars are built around it.",
      "## The dates",
      "<strong>GITEX Global 2026</strong> runs <strong>7&ndash;11 December</strong> at the <strong>Dubai Exhibition Centre in Expo City Dubai</strong>. The <strong>GITEX Scale Summit</strong> opens the week on <strong>7 December</strong>; the exhibition floor is open <strong>8&ndash;11 December</strong>.",
      "This follows the move already announced in October 2025, when the show confirmed it was leaving the Dubai World Trade Centre after <strong>forty-five years</strong>. What was not obvious at the time is that the venue change came with a calendar change.",
      "## Why the month matters more than the address",
      "October in Dubai has been GITEX month since the 1980s. Hotels priced against it, adjacent conferences scheduled themselves to catch its arrivals, and a great deal of business that had nothing to do with technology was transacted in the fortnight around it.",
      "December is a different market. It sits inside the high season proper, when leisure demand is already strong and rooms are already expensive. A business event landing in that window competes with holiday traffic rather than creating its own.",
      "## What is genuinely uncertain",
      "Two things nobody can answer yet. First, whether October retains a technology anchor or simply loses one. Second, whether the exhibitors who treated GITEX as the end of the third quarter adjust their own product cycles, or quietly deprioritise a show that no longer lands where their financial year does.",
      "Both will be visible in the 2027 announcements, not in this year's floor plan.",
    ],
    expertise:
      "For anyone booking around it: the useful number is not the exhibition dates but the two days either side of them. Expo City is a considerable distance from the Deira and Bur Dubai hotel stock that historically absorbed GITEX overflow, and the Red Line takes roughly forty minutes from Union to the Expo terminus. Proximity is priced accordingly, and the December high season means there is no soft pricing to fall back on.",
  },
  {
    slug: "296-homes-above-ten-million-dollars",
    site: "dst",
    image: "/covers/296-homes-above-ten-million-dollars.jpg",
    imageAlt: "Two upright paper strips, one cream and one orange, standing on a torn cream sheet against deep blue",
    imageKind: "generated",
    imageWidth: 1536,
    imageHeight: 864,
    title: "Dubai sold 296 homes above $10m in six months",
    cardTitle: "296 sales above $10m in half a year",
    summary:
      "Knight Frank's half-year count puts $5.1bn of $10m-plus deals on the record for H1 2026 — up 16% in number and 14% in value on last year.",
    date: "2026-09-02",
    category: "Market",
    source: {
      name: "Knight Frank",
      url: "https://www.knightfrank.ae/research",
      verifiedOn: "2026-09-02",
    },
    body: [
      "The headline number for Dubai property is usually total sales volume, which mostly measures how much stock was released. The more revealing number is much smaller: how many homes changed hands above ten million dollars.",
      "## The count",
      "<strong>296</strong> sales above <strong>$10m</strong> in the first half of 2026, worth <strong>$5.1bn</strong> in total. That is <strong>16% more transactions</strong> and <strong>14% more value</strong> than the same period last year. The split across quarters was <strong>165 in Q1</strong> and <strong>131 in Q2</strong>.",
      "Above <strong>$25m</strong>, the second quarter recorded <strong>26 sales</strong> &mdash; a record for a single quarter.",
      "## Where they were",
      "<strong>Dubai Hills Estate</strong> accounted for <strong>51</strong> of the 296, the largest single concentration. Average prices across the segment rose about <strong>9%</strong> year on year.",
      "## What the quarterly split actually says",
      "165 falling to 131 looks like a slowdown, and it may be one. It is worth noting the alternative reading before treating it as a trend: at this price the market is thin enough that a handful of individual transactions moves the quarterly figure by double digits, and the $25m-plus record sits inside the weaker quarter.",
      "Value rising more slowly than volume &mdash; 14% against 16% &mdash; is the number that carries more information. It means the average $10m-plus sale was slightly cheaper this year than last. More buyers, marginally smaller cheques.",
    ],
    expertise:
      "Read the 14%-versus-16% gap before the headline. When count grows faster than value in a luxury segment, the entry band is filling up faster than the top &mdash; more homes clearing the $10m line, not more homes selling far above it. That is what a broadening market looks like, and it is a different condition from the one where a few trophy sales carry the total.",
  },
  {
    slug: "middle-east-energy-2026-opens",
    site: "dst",
    image: "/covers/middle-east-energy-2026-opens.jpg",
    imageAlt: "A dense block of small amber paper squares set on a pale panel against a deep blue ground",
    imageKind: "generated",
    imageWidth: 1536,
    imageHeight: 864,
    title: "Middle East Energy opened this week with 1,900 exhibitors",
    cardTitle: "1,900 exhibitors, three days, one hall",
    titleSeo: "Middle East Energy 2026 opens in Dubai",
    summary:
      "The power-sector show marks fifty years at the World Trade Centre from 1 to 3 September, with 35,000 expected from more than 150 countries.",
    date: "2026-09-01",
    category: "Energy",
    source: {
      name: "Middle East Energy",
      url: "https://www.middleeast-energy.com/",
      verifiedOn: "2026-09-02",
    },
    body: [
      "Dubai's exhibition calendar restarts in September, and it restarts with power.",
      "## The event",
      "<strong>Middle East Energy</strong> runs <strong>1&ndash;3 September 2026</strong> at the <strong>Dubai World Trade Centre</strong>, marking <strong>fifty years</strong> of the show. The organisers expect more than <strong>1,900 exhibitors</strong> and over <strong>35,000 attendees</strong> from more than <strong>150 countries</strong>, with <strong>250-plus speakers</strong> across the conference programme.",
      "## Why a fifty-year-old trade show is still the regional benchmark",
      "Energy events elsewhere have fragmented into renewables shows, grid shows and hydrogen shows that barely speak to one another. This one has stayed a single floor covering generation, transmission and distribution, storage, and the consumption side.",
      "That matters in a region where the same utility is often buying all of it at once. The Gulf's transition is not a replacement of one system by another; it is a very large conventional grid absorbing solar at speed while demand keeps climbing. Vendors who only sell one half of that are not much use to the buyer.",
      "## The number to keep",
      "150 countries against 1,900 exhibitors is the ratio worth noting. This is not a domestic market with international guests; it is a sourcing floor where the buying is regional and the supply chain is global. That is also why September works as a date &mdash; it is the start of the procurement year for utilities whose peak load has just passed.",
    ],
    expertise:
      "The half-century framing is a marketing line, but the venue choice is not. Staying at the World Trade Centre in the year GITEX leaves it for Expo City tells you which shows still need Sheikh Zayed Road and the Metro on their doorstep. A trade floor whose visitors arrive in fleets of company cars behaves differently from one whose visitors arrive alone.",
  },
  {
    slug: "international-property-show-2026",
    site: "dst",
    image: "/covers/international-property-show-2026.jpg",
    imageAlt: "Three upright paper rectangles in teal, pale blue and gold standing apart on a slate ground",
    imageKind: "generated",
    imageWidth: 1536,
    imageHeight: 864,
    title: "The International Property Show returns for a 22nd year",
    cardTitle: "IPS 2026: three days, five halls",
    titleSeo: "International Property Show 2026 in Dubai",
    summary:
      "IPS runs 7–9 September across five halls at the World Trade Centre, timed to Dubai Land Department's own calendar and co-located with AIM Congress.",
    date: "2026-09-02",
    category: "Market",
    source: {
      name: "International Property Show",
      url: "https://www.ipsdubai.ae/",
      verifiedOn: "2026-09-02",
    },
    body: [
      "Property exhibitions are usually sales floors dressed as conferences. This one is worth reading differently, because of who stands behind it.",
      "## The dates",
      "<strong>IPS 2026</strong> runs <strong>7&ndash;9 September</strong> in <strong>Halls 4&ndash;8</strong> of the <strong>Dubai World Trade Centre</strong>. It is the <strong>22nd edition</strong>, and it is co-located with the <strong>AIM Congress</strong>, the investment-promotion event.",
      "## The detail that changes how you read it",
      "IPS is aligned with the <strong>Dubai Land Department</strong>. That alignment is the reason it is not simply a bigger version of a developer roadshow: the regulator's own calendar &mdash; registration reforms, escrow rules, brokerage licensing &mdash; tends to surface at it before it surfaces anywhere else.",
      "The co-location with AIM Congress points the same way. AIM is about attracting foreign direct investment at a national level; putting a residential property show next to it treats housing as part of the investment case for the country, not as a separate consumer market.",
      "## What to actually watch for",
      "Not the launches. Developers launch continuously and a September stand tells you nothing a July press release did not. The useful signal at a regulator-aligned show is procedural: what the Land Department says about registration, off-plan protections and broker conduct, and whether any of it comes with a date attached.",
    ],
    expertise:
      "Five halls for a 22nd-edition show is a size worth pausing on. Dubai's property exhibitions have historically ballooned during release cycles and shrunk when supply tightened, so hall count is a rough proxy for how much unsold inventory needs a shop window. Compare it against the same show's footprint in previous years rather than against other events this month.",
  },
  {
    slug: "uae-fuel-prices-september-2026",
    site: "dst",
    image: "/covers/uae-fuel-prices-september-2026.jpg",
    imageAlt: "Torn paper rectangles standing in a row, each one taller than the last",
    imageKind: "generated",
    imageWidth: 1536,
    imageHeight: 864,
    title: "Diesel jumped 13% on 1 September. Petrol went up about 6%",
    cardTitle: "September fuel prices: diesel +13%",
    titleSeo: "UAE petrol and diesel prices, September 2026",
    summary:
      "Super 98 is Dh3.80, Special 95 is Dh3.69, E-Plus is Dh3.61 and diesel is Dh4.30 a litre. Diesel is the number that matters, and not because of cars.",
    date: "2026-09-01",
    category: "Energy",
    source: {
      name: "Khaleej Times",
      url: "https://www.khaleejtimes.com/business/energy/uae-petrol-diesel-prices-september-2026-announced",
      verifiedOn: "2026-09-02",
    },
    body: [
      "UAE retail fuel prices are reset at the start of each month, and the September 2026 reset is lopsided in a way worth reading properly.",
      "## The prices, from 1 September 2026",
      "<strong>Super 98</strong>: <strong>Dh3.80</strong> a litre, up from Dh3.60 &mdash; a rise of <strong>5.6%</strong>. <strong>Special 95</strong>: <strong>Dh3.69</strong>, up from Dh3.49, a rise of <strong>5.7%</strong>. <strong>E-Plus 91</strong>: <strong>Dh3.61</strong>, up from Dh3.41, a rise of <strong>5.9%</strong>.",
      "Each of the three petrol grades rose by exactly <strong>20 fils</strong>. That is the flat part of the announcement.",
      "## Diesel is the outlier",
      "<strong>Diesel</strong> went to <strong>Dh4.30</strong> a litre from Dh3.80 &mdash; up <strong>50 fils</strong>, a rise of <strong>13.2%</strong>, more than double the petrol move in percentage terms and two and a half times it in fils.",
      "For a private driver that is a rounding error, because most private cars here run on petrol. Diesel is what moves goods: delivery vans, tippers, generators on construction sites, and the trucks that supply every shop and every project in the emirate. A 13% step on that input does not stay in the fuel bill. It arrives later, in smaller pieces, spread across delivery charges and contract prices.",
      "## What it costs a driver",
      "The petrol rise works out at roughly <strong>Dh10 to Dh15</strong> extra on a full tank, depending on whether you are filling a compact car or an SUV. That is a monthly change of a few tens of dirhams for ordinary use &mdash; noticeable on a statement, not on a decision.",
      "The point of tracking it is not the tank. It is that fuel is one of the few local prices published as a clean number on a fixed schedule, which makes it a usable early indicator: it moves before the costs downstream of it do.",
      "## Where the move came from",
      "Khaleej Times attributes the direction to regional supply disruption, including attacks on shipping and oil infrastructure in the Red Sea. Retail fuel here tracks international product prices with a one-month lag by design, which is why the reset arrives as a step on the first of the month rather than as drift.",
      "That lag cuts both ways. A month of falling crude shows up on a forecourt board here at the start of the following month, not the following week.",
    ],
    expertise:
      "If you are budgeting rather than just filling a tank, watch the <strong>diesel-to-petrol gap</strong> rather than either price alone. Diesel now sits <strong>61 fils above Special 95</strong>, having been <strong>31 fils</strong> above it in August &mdash; the spread doubled in one reset. A widening spread is a logistics cost signal, and it is the part of the announcement that reaches people who never buy diesel.",
  },
  {
    slug: "apple-hands-the-company-to-an-engineer",
    site: "dst",
    image: "/covers/apple-hands-the-company-to-an-engineer.jpg",
    imageAlt: "A row of identical paper squares with one lifted out of the line and tilted above it",
    imageKind: "generated",
    imageWidth: 1536,
    imageHeight: 864,
    title: "The biggest company in the world just put a hardware engineer in charge",
    cardTitle: "Apple's new CEO built the hardware",
    titleSeo: "Apple promotes a hardware engineer to CEO",
    summary:
      "John Ternus became Apple's chief executive on 1 September after twenty-five years inside the building. The interesting part is not that Apple replaced its CEO. It is who it did not look for.",
    date: "2026-09-01",
    category: "Tech",
    source: {
      name: "Apple Newsroom",
      url: "https://www.apple.com/newsroom/2026/04/tim-cook-to-become-apple-executive-chairman-john-ternus-to-become-apple-ceo/",
      verifiedOn: "2026-09-02",
    },
    body: [
      "Every succession is an argument about what a company thinks it is. Apple made its argument on <strong>1 September 2026</strong>, when <strong>John Ternus</strong> became chief executive and <strong>Tim Cook</strong> moved to executive chairman after fifteen years in the job.",
      "## Who got the job",
      "Ternus joined Apple in <strong>2001</strong> and had been <strong>senior vice president of Hardware Engineering</strong>: the person responsible for the physical iPhone, iPad, Mac, Apple Watch and AirPods. Twenty-five years inside one company, all of them on the side of the business that has to be manufactured.",
      "That is not the profile the last decade of business writing would have predicted. The received wisdom says a company facing a software problem hires a software answer, preferably from outside, preferably with a mandate to break things.",
      "## What Apple did instead",
      "It promoted the person who makes the objects, and it did so on a schedule announced in public <strong>four and a half months in advance</strong> &mdash; the change was announced on <strong>20 April</strong> and took effect on 1 September.",
      "Cook does not leave. As <strong>executive chairman</strong> he keeps a defined remit that Apple describes as engaging with policymakers around the world &mdash; which is a way of saying the company decided its regulatory relationships were a job in themselves, not a thing a chief executive does between product reviews. <strong>Arthur Levinson</strong>, chairman for the past fifteen years, became lead independent director the same day.",
      "## The inheritance, in numbers",
      "Under Cook, Apple went from a market value of about <strong>$350 billion</strong> to roughly <strong>$4 trillion</strong>. Revenue rose from <strong>$108 billion</strong> in FY2011 to <strong>$416 billion</strong> in FY2025. Services became a business of more than <strong>$100 billion</strong> on its own. The company added over <strong>100,000</strong> employees and now counts more than <strong>2.5 billion</strong> active devices across <strong>200-plus countries and territories</strong>.",
      "Those are the numbers a successor is measured against, and they are the reason the safe-looking choice is not obviously the safe choice. A company that large does not get to grow by another order of magnitude; the next fifteen years will be judged on something other than the chart.",
      "## Why it is worth watching from here",
      "Apple sells in more than two hundred countries and territories, which means this is one of the very few corporate decisions that lands in every market at once, including this one. Nothing changes for anyone buying a phone this week. What changes is who decides what the phone is in 2031.",
    ],
    expertise:
      "The detail worth copying, whatever the size of the company, is the <strong>134 days</strong> between announcement and handover. Succession is usually revealed and executed on the same morning, which tells staff, customers and counterparties that a decision was made without them. A dated handover published in advance converts the same event into a schedule &mdash; and a schedule is something other people can plan around.",
  },
  {
    slug: "186-new-developers-entered-dubai-in-2026",
    site: "dst",
    image: "/covers/186-new-developers-entered-dubai-in-2026.jpg",
    imageAlt: "A dense field of paper tower silhouettes with smaller new ones filling the gaps, a blank licence card in front",
    imageKind: "generated",
    imageWidth: 1536,
    imageHeight: 864,
    title: "186 new developers entered Dubai this year",
    summary:
      "Between January and mid-August 2026 the Dubai Land Department registered 186 new real estate development companies — about 25 a month. 180 of them were licensed by one authority.",
    date: "2026-08-15",
    category: "Market",
    source: {
      name: "Gulf News",
      url: "https://gulfnews.com/business/property/dubai-attracts-186-new-property-developers-in-first-seven-months-of-2026-1.500641994",
      verifiedOn: "2026-09-01",
    },
    body: [
      "A developer count is a duller number than a transaction volume, and a more honest one. Transactions measure what buyers did last quarter; new licences measure what companies believe about the next three years, because a development licence is only worth taking out if you intend to build.",
      "Between the start of 2026 and <strong>mid-August</strong>, <strong>186</strong> new real estate development companies were registered in Dubai, according to Dubai Land Department data. That works out at roughly <strong>25 a month</strong>.",
      "## Where the licences came from",
      "The split is lopsided, and the lopsidedness is the interesting part:",
      "<strong>Department of Economy and Tourism &mdash; 180.</strong> <strong>Trakhees</strong> (Dubai Ports, Customs and Free Zone Corporation) &mdash; <strong>3</strong>. <strong>Mohammed bin Rashid Establishment for Small and Medium Enterprises Development</strong> &mdash; <strong>2</strong>. <strong>Expo City Dubai</strong> &mdash; <strong>1</strong>.",
      "Ninety-seven per cent of the new entrants took the mainland route. That is not the shape a market has when its growth is coming from free-zone structures or offshore holding vehicles &mdash; it is the shape of companies setting up to sell to the emirate&rsquo;s own buyers under the emirate&rsquo;s own regulator.",
      "## What 25 a month actually means",
      "Two readings sit on top of this figure and they do not cancel each other out.",
      "The first is confidence: nobody licenses a development company into a market they expect to thin out. The second is competition. A buyer choosing off-plan in late 2026 is choosing among more names than a buyer in 2024 was, and a meaningful share of those names have no delivered project behind them yet.",
      "## The question a licence does not answer",
      "A development licence says a company may build. It does not say the company has land, funding, a contractor, or an escrow account with anything in it. Those are separate registrations, and the gap between them is where an off-plan buyer&rsquo;s risk actually lives.",
    ],
    expertise:
      "The count of developers is a market-level signal, not a shortlist. Before committing to an off-plan unit from a name registered this year, the two checks worth doing are the project&rsquo;s escrow account number and the developer&rsquo;s completed-project history &mdash; both are on the Dubai Land Department&rsquo;s own systems, and 186 new companies is precisely the reason to do them.",
  },
  {
    slug: "dubai-tokenised-property-secondary-market",
    featured: 1,
    site: "dst",
    image: "/covers/dubai-tokenised-property-secondary-market.jpg",
    imageAlt: "A paper building facade cut into tiles, a few of them floating free",
    imageKind: "generated",
    imageWidth: 1536,
    imageHeight: 864,
    title: "Dubai opens a regulated market for tokenised property",
    cardTitle: "Tokenised property gets a market",
    summary:
      "Fractional stakes in Dubai Land Department title deeds became tradable between investors on February 20, 2026, under VARA supervision — the pilot behind it had drawn investors from over 50 nationalities and more than Dh18.5 million.",
    date: "2026-02-20",
    category: "Crypto",
    source: {
      name: "Gulf News",
      url: "https://gulfnews.com/business/property/prypco-rolls-out-dubai-marketplace-after-nod-for-property-stakes-trading-1.500438076",
      verifiedOn: "2026-08-26",
    },
    body: [
      "On <strong>February 20, 2026</strong> a regulated marketplace opened in Dubai for trading fractional stakes in property already registered with the Dubai Land Department. It runs under the Virtual Assets Regulatory Authority, in partnership with the DLD, and is open to UAE residents over 18 with a valid Emirates ID.",
      "The pilot that preceded it drew investors from more than 50 nationalities and over <strong>Dh18.5 million</strong> in tokenised property investments, with one offering fully funded in one minute and 58 seconds.",
      "The authorities describe the rollout as controlled rather than a broad market opening.",
    ],
    expertise:
      "The part worth noticing is what is being tokenised. This is not a crypto product with property attached — the token points at a title deed in a government registry, and the price is in dirhams. That makes it a liquidity mechanism for an asset class whose defining problem has always been that selling takes months, and it is the government registry, not a blockchain, that makes the claim enforceable. The unresolved question is the same one every fractional scheme meets: a secondary market only prices an asset once there are enough buyers on the other side, and a pilot funded in under two minutes says more about scarcity of supply than about depth of demand.",
  },
  {
    slug: "gitex-moves-to-expo-city-2026",
    featured: 2,
    site: "dst",
    image: "/covers/gitex-moves-to-expo-city-2026.jpg",
    imageAlt: "Two exhibition halls in cut paper with a broad arrow crossing between them",
    imageKind: "generated",
    imageWidth: 1536,
    imageHeight: 864,
    title: "GITEX leaves the World Trade Centre after 45 years",
    cardTitle: "GITEX leaves the World Trade Centre",
    summary:
      "Dubai's largest technology show moves to the Dubai Exhibition Centre at Expo City for its 2026 edition, and shifts from its long-standing October slot to December 7–11.",
    date: "2025-10-08",
    category: "Tech",
    source: {
      name: "Dubai Media Office",
      url: "https://mediaoffice.ae/en/news/2025/october/08-10/gitex-global-to-begin-a-new-chapter-at-expo-city-dubai-in-2026",
      verifiedOn: "2026-08-26",
    },
    body: [
      "GITEX GLOBAL leaves Dubai World Trade Centre, its home for 45 years, for the Dubai Exhibition Centre at Expo City Dubai. The 2026 edition runs <strong>December 7–11</strong> — the summit day at DWTC on the 7th, the exhibition at Expo City from the 8th.",
      "The new venue is around 1.5 times the size of the old one. The organisers put the expected 2026 scale at more than 200,000 attendees from over 180 countries, 6,800 exhibiting companies and 400+ government entities.",
      "Gulfood moves to the same venue in 2026.",
    ],
    expertise:
      "Two things change here for anyone planning around the show, and only one of them is the address. The October slot had been fixed long enough that half the region's product launches, funding announcements and hiring rounds were timed against it; moving to December pushes all of that into the last weeks of the financial year. The venue change is the smaller story — a bigger hall for a show that had outgrown its old one — but the calendar change is the one that quietly reshuffles a year of planning, and the attendance figures above are projections, not a count.",
  },
  {
    slug: "dubai-property-sales-h1-2026",
    site: "dst",
    title: "Dubai property sales reach Dh286b in H1",
    summary:
      "Dubai recorded Dh286.43 billion of property sales across 79,229 transactions in the first half of 2026 — an average of 433 sales and about Dh1.57 billion changing hands every day.",
    date: "2026-07-14",
    category: "Market",
    image: "/news/dubai-property-h1-2026.svg",
    imageAlt:
      "Dubai property sales in H1 2026: Dh286.43 billion across 79,229 transactions, 433 sales a day, with January at Dh72.16 billion against June at Dh32.66 billion.",
    imageKind: "diagram",
    imageCredit: "DST",
    imageWidth: 1200,
    imageHeight: 600,
    imageNarrow: "/news/dubai-property-h1-2026-narrow.svg",
    source: {
      name: "Khaleej Times",
      url: "https://www.khaleejtimes.com/business/dubai-property-sales-hit-dh286b-as-market-momentum-stays-strong-in-h1-2026",
      verifiedOn: "2026-08-25",
    },
    body: [
      "Dubai closed the first half of 2026 with <strong>Dh286.43 billion</strong> in property sales across 79,229 transactions — roughly 433 sales a day and close to Dh1.57 billion changing hands daily.",
      "January was the strongest month of the period, at Dh72.16 billion across 15,896 transactions. June closed with 13,766 sales worth Dh32.66 billion.",
    ],
    expertise:
      "The two published months are worth dividing out. January averaged Dh4.54 million per sale; June averaged Dh2.37 million. So while transactions fell 13% between them, value fell 55% — the gap is the average ticket, which fell 48%. On those figures the market shifted toward cheaper stock rather than simply slowing down. Two months are not a trend, and summer is reliably the quieter half of a Dubai year, but it is the average ticket that carries the information here: a headline total mixes price and volume together and hides which one moved.",
  },
];
