import type { NewsItem } from "../types.ts";

export const items: NewsItem[] = [
  {
    slug: "the-sixth-phase-finishes-this-quarter-and-the-park-passes-4000mw",
    createdAt: "2026-08-25T18:18:34+04:00",
    updatedAt: "2026-09-08T00:12:45+04:00",
    site: "eco",
    image: "/covers/the-sixth-phase-finishes-this-quarter-and-the-park-passes-4000mw.jpg",
    imageAlt: "Rows of sage paper rectangles tilted at the same angle across a forest green ground, the last row a shade paler than the rest",
    imageKind: "generated",
    imageWidth: 1536,
    imageHeight: 864,
    title: "The last 800MW of the solar park's sixth phase is due this quarter",
    cardTitle: "800MW left in phase six",
    titleSeo: "MBR Solar Park: 800MW due in Q4 2026",
    summary:
      "DEWA puts the Mohammed bin Rashid Al Maktoum Solar Park at 3,860MW today, with the remaining 800MW of phase six scheduled to be commissioned by the end of the year.",
    date: "2026-09-07",
    category: "Energy",
    source: {
      name: "Gulf Business, reporting DEWA",
      url: "https://gulfbusiness.com/en/2026/utilities/dewa-accelerates-clean-energy-transition/",
      verifiedOn: "2026-09-07",
    },
    body: [
      "A solar park is one of the few large things that can be described honestly by a single number, because the number is what it produces rather than what it cost.",
      "## Where the park stands",
      "The <strong>Mohammed bin Rashid Al Maktoum Solar Park</strong> is at <strong>3,860MW</strong>. The remaining <strong>800MW</strong> of its sixth phase is scheduled to be commissioned by the <strong>fourth quarter of 2026</strong>, and the park is expected to pass <strong>8,000MW by 2030</strong>.",
      "## What that is as a share",
      "<strong>DEWA</strong> puts clean energy at more than <strong>21.5 per cent</strong> of its total production capacity. The park is the bulk of it, on a single site south of the city.",
      "## The part that is not solar",
      "Two projects in the same programme do something photovoltaics cannot. The <strong>250MW Hatta hydroelectric plant</strong> — the first pumped-storage scheme in the GCC — holds <strong>1,500MWh</strong> for the hours after sunset. The first phase of the <strong>Warsan green data centre</strong>, more than <strong>100MW</strong>, is due in the second half of this year.",
      "## Why storage is the harder number",
      "Capacity says what can be generated at noon. Storage says what is available at eight in the evening, when demand in a Gulf city is still high and the panels have stopped. A park that grows faster than its storage moves the problem rather than solving it.",
    ],
    expertise:
      "Read the two figures as a ratio rather than as a pair of achievements. Nearly 4,000MW of daytime generation against 1,500MWh of pumped storage means the storage covers minutes of full output, not hours — it is there to smooth and to firm, not to carry the evening. That is a normal position for a grid at this stage, and it is why gas capacity is not being retired alongside the solar build. The number that will say the transition has changed character is not the next gigawatt on the park; it is the first battery procurement measured in gigawatt-hours rather than megawatts, which is what the seventh phase tender has been shaped to buy.",
  },

  {
    slug: "dubai-holds-its-first-environment-conference-this-week",
    createdAt: "2026-09-06T08:48:11+04:00",
    updatedAt: "2026-09-08T00:12:45+04:00",
    site: "eco",
    image: "/covers/dubai-holds-its-first-environment-conference-this-week.jpg",
    imageAlt: "Six sage paper leaves arranged in a ring on a deep forest green ground, with a warm cream circle at the centre",
    imageKind: "generated",
    imageWidth: 1536,
    imageHeight: 864,
    title: "Dubai holds its first environment conference on 7 and 8 September",
    cardTitle: "A first environment conference",
    titleSeo: "Dubai Environment Conference and Exhibition 2026",
    summary:
      "The Dubai Environment and Climate Change Authority stages the emirate’s first Environment Conference and Exhibition at the Grand Hyatt, across six themes that include food security, the circular economy and environmental AI.",
    date: "2026-09-06",
    category: "Environment",
    source: {
      name: "Gulf News",
      url: "https://gulfnews.com/uae/environment/dubai-to-host-first-environment-conference-and-exhibition-in-september-1.500637032",
      verifiedOn: "2026-09-06",
    },
    body: [
      "A city that has hosted a UN climate summit holding its first environment conference sounds like a contradiction. It is not: one was the world’s meeting, and this is the emirate’s own.",
      "## What and when",
      "The <strong>Dubai Environment Conference &amp; Exhibition</strong> runs on <strong>7 and 8 September 2026</strong> at the <strong>Grand Hyatt Dubai</strong>, organised by the <strong>Dubai Environment and Climate Change Authority</strong> under the patronage of <strong>Sheikh Ahmed bin Saeed Al Maktoum</strong>, Chairman of the Dubai Supreme Council of Energy. Its theme is «Protecting Our Environment, Preserving Our Future».",
      "## The six subjects",
      "<strong>Biodiversity</strong>, <strong>natural resources</strong>, <strong>food security</strong>, <strong>climate change</strong>, the <strong>circular economy</strong> and <strong>environmental artificial intelligence</strong>.",
      "## What is on the floor",
      "Alongside panel discussions and research presentations, an exhibition of environmental technologies covering <strong>air, soil and water quality</strong>, sustainable food supply chains, <strong>recycling and electronic waste</strong>, water resource management, <strong>coastal monitoring</strong>, and satellite tracking of vegetation with real-time environmental data collection.",
      "## Who said what",
      "<strong>Ahmed Mohammed bin Thani</strong>, Director-General of DECCA: «The conference and exhibition represent a new milestone in Dubai’s efforts to consolidate its position as a global centre for environmental innovation and leadership.»",
    ],
    expertise:
      "The programme is more revealing than the framing. Five of the six themes are conventional environmental policy; the sixth, environmental artificial intelligence, is the one that tells you what the authority thinks its next few years look like, and it sits beside two hard monitoring subjects — coastal observation and satellite vegetation tracking. Read together, those three suggest the emphasis is shifting from targets to measurement, which is the less glamorous half of environmental policy and the half that determines whether any target means anything. That is worth watching for a specific reason: a target can only be checked against a published series, and monitoring infrastructure is what eventually makes independent verification possible at all. The test for this conference, and for the next one, is whether anything demonstrated on the exhibition floor turns into a public dataset with a stable address and a documented method. Food security appearing as a headline theme is the other signal — in a desert economy that imports most of what it eats, it is a water and logistics subject wearing an agricultural label.",
  },

  {
    slug: "solar-is-now-the-largest-installed-technology-on-earth",
    createdAt: "2026-09-06T08:48:11+04:00",
    updatedAt: "2026-09-06T08:48:11+04:00",
    site: "eco",
    image: "/covers/solar-is-now-the-largest-installed-technology-on-earth.jpg",
    imageAlt: "A large sage paper square on a deep forest green ground beside three smaller moss squares of decreasing size, a warm cream line beneath them all",
    imageKind: "generated",
    imageWidth: 1536,
    imageHeight: 864,
    title: "Solar passed 600 GW in a single year and is now the largest installed technology on earth",
    cardTitle: "Solar, now the largest fleet",
    titleSeo: "IEA: solar PV additions passed 600 GW in 2025",
    summary:
      "The IEA’s Global Energy Review 2026 puts 2025 solar additions above 600 GW for the first time, taking the cumulative fleet to about 2,800 GW — more installed capacity than any other generating technology.",
    date: "2026-09-06",
    category: "Energy",
    source: {
      name: "International Energy Agency",
      url: "https://www.iea.org/reports/global-energy-review-2026/technology-solar-pv-and-wind",
      verifiedOn: "2026-09-06",
    },
    body: [
      "There is a moment when a technology stops being an alternative and becomes the default, and it is visible only in the capacity tables.",
      "## The threshold",
      "Solar PV additions in <strong>2025</strong> rose around <strong>12%</strong> and passed <strong>600 GW</strong> for the first time, taking cumulative installed solar capacity to roughly <strong>2,800 GW</strong> — making solar the technology with the <strong>largest installed capacity globally</strong>.",
      "## How broad it is",
      "<strong>Thirty countries</strong> each installed more than <strong>1 GW</strong> in the year, nearly double the number that did so in <strong>2020</strong>. Solar accounted for more than <strong>three quarters</strong> of the <strong>800 GW</strong> of renewable capacity added worldwide; wind took about <strong>20%</strong>.",
      "## Wind, quietly",
      "Wind additions reached roughly <strong>160 GW</strong>, a record, with growth up nearly <strong>40%</strong> on the previous year despite continuing supply chain difficulties.",
      "## Where it happened",
      "<strong>China</strong> added close to <strong>500 GW</strong> of renewables, over <strong>60%</strong> of the global total, including <strong>370 GW</strong> of solar and <strong>117 GW</strong> of wind. <strong>India</strong> grew fastest among major markets at around <strong>60%</strong>, on <strong>50 GW</strong> of solar. The <strong>European Union</strong> added a record <strong>85 GW</strong>, with Spain and Germany leading the solar expansion.",
    ],
    expertise:
      "Installed capacity is the number that changes first and explains least. A gigawatt of solar and a gigawatt of gas do not produce the same electricity, because the solar plant works when the sun is up and the gas plant works when it is told to; the crossover being reported here is a nameplate crossover, and the generation crossover happens later and by a smaller margin. That is not a reason to dismiss it. Capacity leads because it is where the money and the manufacturing go, and 30 countries clearing a gigawatt in a year is a supply-chain fact that will still be true in five years regardless of any single government’s policy. The concentration is the caveat worth carrying: with China responsible for more than 60% of additions, the global figure is substantially one country’s industrial policy, and the module prices that make a Gulf solar tender viable are set by that same industry. For a region building at utility scale, the second-order consequence of a fleet this large is that the binding constraint moves from panels to everything around them — grid connections, storage duration and the hours after sunset, which is exactly why tenders here now arrive with battery capacity attached rather than as solar alone.",
  },

  {
    slug: "dp-world-names-its-first-methanol-dual-fuel-ship",
    createdAt: "2026-09-03T07:30:21+04:00",
    updatedAt: "2026-09-06T08:48:11+04:00",
    site: "eco",
    image: "/covers/dp-world-names-its-first-methanol-dual-fuel-ship.jpg",
    imageAlt: "A simple sage paper ship hull on a deep green ground with two cream fuel droplets above it, one larger than the other",
    imageKind: "generated",
    imageWidth: 1536,
    imageHeight: 864,
    title: "DP World names its first ship that can run on methanol",
    cardTitle: "A first methanol dual-fuel ship",
    titleSeo: "DP World names a methanol dual-fuel ship",
    summary:
      "The 1,250 TEU DP World London can burn methanol or conventional fuel. It was delivered in April and first bunkered methanol in Rotterdam in June.",
    date: "2026-09-03",
    category: "Shipping",
    source: {
      name: "Dubai Government Media Office",
      url: "https://www.mediaoffice.ae/en/news/2026/august/31-08/dp-worlds-shipping-solutions-names-its-first-methanol-dual-fuel-vessel",
      verifiedOn: "2026-09-03",
    },
    body: [
      "Shipping is hard to decarbonise for an unglamorous reason: a ship lasts twenty-five years, so the fuel decision is made once and lived with. On <strong>31 August</strong> DP World named a ship that defers the decision.",
      "## The vessel",
      "<strong>DP World London</strong>: <strong>1,250 TEU</strong>, <strong>148 metres</strong>, Portuguese-flagged, owned by the German operator <strong>Elbdeich Reederei</strong> and run by DP World's Shipping Solutions. She was <strong>delivered in April 2026</strong>.",
      "## What dual-fuel means here",
      "A five-cylinder main engine that can run on <strong>either methanol or conventional marine fuel</strong>, with <strong>exhaust gas recirculation</strong> fitted to cut emissions and meet international standards.",
      "## The date that matters more than the naming",
      "The first methanol bunkering took place in <strong>Rotterdam on 25 June 2026</strong>. A dual-fuel engine that has never taken the alternative fuel is a conventional ship with an option attached; the bunkering is what makes it real.",
      "## What was not said",
      "The announcement gives no emissions-reduction percentage, no fleet-wide count of methanol-capable vessels and no order book. <strong>Martin Gaard Christiansen</strong>, CEO of Shipping Solutions EAM, framed the ship in terms of heritage and direction rather than tonnes avoided.",
    ],
    expertise:
      "Dual-fuel is a hedge, and it should be read as one rather than as a conversion. The environmental result depends entirely on what goes into the tank: methanol made from natural gas offers modest well-to-wake savings, while green methanol made from renewable power and captured carbon offers large ones, and the announcement does not say which was bunkered in Rotterdam. That is the question to ask of any methanol vessel claim. The vessel size is also worth noting — at 1,250 TEU this is a feeder, not a mainline container ship, which is the sensible place to start because feeders return to the same few ports and can therefore rely on bunkering infrastructure that barely exists anywhere else.",
  },

  {
    slug: "a-60-percent-carbon-cut-changes-hands",
    createdAt: "2026-09-02T12:10:41+04:00",
    updatedAt: "2026-09-06T08:48:11+04:00",
    site: "eco",
    image: "/covers/a-60-percent-carbon-cut-changes-hands.jpg",
    imageAlt: "A tall paper column beside a much shorter one of the same width, a leaf leaning against the base of the shorter",
    imageKind: "generated",
    imageWidth: 1536,
    imageHeight: 864,
    title: "A 60% carbon cut just changed hands",
    cardTitle: "Apple's climate number gets a new owner",
    summary:
      "Apple says its carbon footprint is 60% below 2015. On 1 September the person who has to keep saying that became someone else — and he is the one who signed off the hardware.",
    date: "2026-09-01",
    category: "Environment",
    source: {
      name: "Apple Newsroom",
      url: "https://www.apple.com/newsroom/2026/04/tim-cook-to-become-apple-executive-chairman-john-ternus-to-become-apple-ceo/",
      verifiedOn: "2026-09-02",
    },
    body: [
      "Corporate climate figures are usually discussed as though they belong to the company. They belong to a person, and on <strong>1 September 2026</strong> Apple's changed owner.",
      "## The size of Apple's cut",
      "Apple states that its carbon footprint is <strong>60% below 2015 levels</strong>. That reduction was achieved over the fifteen years <strong>Tim Cook</strong> was chief executive, a period in which the company also went from <strong>$108 billion</strong> of revenue in FY2011 to <strong>$416 billion</strong> in FY2025 and added more than <strong>100,000</strong> employees.",
      "Cutting absolute emissions by 60% while quadrupling revenue is the difficult version of the exercise. The easy version — the one most published figures describe — is intensity: emissions per unit of something that is itself growing.",
      "## Who now owns it",
      "<strong>John Ternus</strong>, chief executive since 1 September, joined Apple in <strong>2001</strong> and spent his career in <strong>hardware engineering</strong>, latterly as the senior vice president responsible for it. He was not adjacent to the footprint. Materials, manufacturing and packaging are hardware decisions, and hardware is what he ran.",
      "That is an unusual and rather demanding inheritance. A chief executive who arrives from finance or from software can treat the environmental programme as something reported to them. This one signed off the products it measures.",
      "## Where the difficulty sits",
      "There are more than <strong>2.5 billion</strong> active Apple devices in use across <strong>200-plus countries and territories</strong>. Every one of them was manufactured, shipped and will eventually be disposed of, and the great majority of a device maker's footprint sits in exactly those three places rather than in its offices.",
      "So the number that changed hands is not an office number. It is a supply chain number, and supply chains are slow: a decision taken about a material this year shows up in a footprint several years later, under whoever is running the company by then.",
      "## What to watch, and when",
      "Not the announcement. The next annual environmental report is the first document in which a 60% figure is either extended or quietly restated, and it will be the first one this chief executive is answerable for. Fifteen years of reductions is a long enough run that continuing it is unremarkable and breaking it is very visible — which is, in practice, the strongest incentive a climate target ever has.",
    ],
    expertise:
      "When you read any corporate climate claim, check three things before the percentage: the <strong>base year</strong>, whether the figure is <strong>absolute or per-unit</strong>, and whether it includes the supply chain. Apple's claim is against <strong>2015</strong> and is stated as a footprint rather than an intensity, which is the harder of the two to move. A figure quoted without its base year is not a claim, it is a decoration.",
  },
  {
    slug: "uae-mangroves-halfway-to-100-million",
    createdAt: "2026-09-01T15:07:36+04:00",
    updatedAt: "2026-09-06T08:48:11+04:00",
    site: "eco",
    image: "/covers/uae-mangroves-halfway-to-100-million.jpg",
    imageAlt: "Paper mangrove roots and canopy filling the left half of the frame, open water on the right",
    imageKind: "generated",
    imageWidth: 1536,
    imageHeight: 864,
    title: "The UAE is halfway to 100 million mangroves",
    summary:
      "Roughly 51 million trees planted against a 2030 target of 100 million — a target that was raised from 30 million. Marine protected areas stand at 12% against a 30% goal.",
    date: "2026-08-22",
    category: "Environment",
    source: {
      name: "Gulf News",
      url: "https://gulfnews.com/uae/environment/uae-reaches-51-of-target-to-plant-100-million-mangrove-trees-by-2030-1.500648706",
      verifiedOn: "2026-09-01",
    },
    body: [
      "Halfway with four years to run sounds comfortable until you remember what the denominator used to be. The UAE’s 2030 mangrove target was originally <strong>30 million</strong> trees. It was raised to <strong>100 million</strong> — so the current <strong>51 million</strong> is not half of the original ambition, it is nearly twice it.",
      "## Where the programme stands",
      "Approximately <strong>51 million</strong> mangroves have been planted, <strong>51%</strong> of the <strong>100 million</strong> target for <strong>2030</strong>.",
      "Hiba Obaid Al Shehhi, Assistant Undersecretary for the Biodiversity and Aquatic Life Sector at the Ministry of Climate Change and Environment, described a shift in approach: marine conservation is no longer focused solely on protecting existing natural resources, but increasingly involves <strong>restoring damaged ecosystems</strong>.",
      "## The other numbers in the same programme",
      "<strong>Marine and coastal protected areas: 12%</strong> of national waters, against a <strong>30% target for 2030</strong>. There are <strong>16</strong> protected areas in the UAE.",
      "This is the figure carrying the real gap. Mangrove planting is a schedule; raising protected coverage from 12% to 30% is a set of decisions about who may fish, anchor and build where — and those move slowly for reasons that have nothing to do with horticulture.",
      "## Coral",
      "A project in <strong>Fujairah</strong> aims to establish <strong>1.5 million coral colonies over five years</strong>, covering more than <strong>300,000 square metres</strong>. Since 2018, <strong>66,173</strong> coral pieces have been cultivated across <strong>22,827 square metres</strong>. Research has mapped <strong>210 coral locations</strong> and identified more than <strong>55 hard coral species</strong>.",
      "Set those side by side and the scale of the new project is clear: it proposes to do roughly twenty times as much area in five years as the previous eight produced.",
      "## Artificial habitat",
      "By the end of 2025, <strong>22,982</strong> artificial cave structures had been deployed under a programme running since <strong>2016</strong>.",
      "## Why mangroves, specifically",
      "A mangrove is three pieces of infrastructure at once: a carbon store that holds far more per hectare below ground than above it, a nursery that fish stocks depend on, and a wave break that reduces what a coastline has to be engineered to withstand. Counting trees is a proxy for all three, which is why the count gets published.",
    ],
    expertise:
      "Planted mangrove counts and surviving mangrove counts are different measurements, and the gap between them is where these programmes are actually judged. Survival depends on tidal elevation at the planting site more than on the number of seedlings put in — a stand set even slightly too high or too low in the tidal frame will thin out over its first three years regardless of how carefully it was planted.",
  },
  {
    slug: "eco-dst-llc-launched",
    createdAt: "2026-08-25T18:18:34+04:00",
    updatedAt: "2026-09-06T08:48:11+04:00",
    site: "eco",
    title: "DST opens a non-commercial environmental direction",
    summary:
      "DST split its environmental work out of a single paragraph on the main site and gave it its own address, eco.dst.llc — a running portfolio where each funded planting gets its own mapped record.",
    date: "2026-03-14",
    category: "Company",
    body: [
      "DST moved its environmental activity off a single paragraph on the main site and gave it a dedicated address, eco.dst.llc. The change is structural, not cosmetic: instead of a general sustainability statement, the site is a running portfolio where each planting or initiative gets its own record — species, planter, and coordinates included.",
      "The first record covers Douglas fir saplings planted in the Sverdlovsk region of Russia, with a location precise enough to check on a map rather than a stock photo standing in for the place.",
      "Nothing on eco.dst.llc is sold or counted as an offset. It's a public log of funded activity DST does because it wants to, kept separate from the group's commercial verticals so the two claims never blur together.",
    ],
    expertise:
      "Environmental line items in company reports are easy to state and hard to verify. Publishing each planting as its own record with coordinates is a deliberate choice: it invites anyone to go and check, instead of asking them to take a summary figure on faith.",
    image: "/stories/douglas-fir-shilovka-01.jpg",
    imageAlt:
      "Cut-paper illustration: three interlocking rings of different sizes.",
    imageKind: "photo",
    geo: {
      name: "Nikolo-Pavlovsky district, Sverdlovsk region — near Shilovka, on the Shaytanka river",
      lat: 57.769599,
      lng: 60.140435,
    },
    related: [
      {
        href: "/portfolio/shilovka-shaytanka/",
        title: "Douglas fir saplings, Sverdlovsk region",
        text: "The first record published on eco.dst.llc — species, planter, and mapped coordinates.",
        image: "/stories/douglas-fir-shilovka-01.jpg",
        imageAlt: "A young Douglas fir sapling freshly planted in tall grass near the Shaytanka river.",
        eyebrow: "Eco portfolio",
      },
      {
        // eco's linking rule: related cards point only into eco itself or
        // to dst.llc, never across to an unrelated vertical.
        href: "https://dst.llc",
        image: "/covers/group.jpg",
        imageAlt: "Cut-paper illustration: three interlocking rings of different sizes.",
        title: "DST",
        text: "The operating group behind eco.dst.llc and its other ventures.",
        eyebrow: "DST",
      },
    ],
    form: {
      title: "Want updates on new eco records?",
      description: "Leave an email and we'll let you know when a new planting or initiative is added to the portfolio.",
      submitLabel: "Notify me",
      meta: { source: "eco-news-launch" },
    },
  },
];
