import type { NewsItem } from "../types.ts";

export const items: NewsItem[] = [
  {
    slug: "venice-opens-the-autumn-with-a-british-film",
    site: "ldn",
    image: "/covers/venice-opens-the-autumn-with-a-british-film.jpg",
    imageAlt: "A paper stage curtain drawn back from a blank screen, a band of lagoon water below and a small winged lion above",
    imageKind: "generated",
    imageWidth: 1536,
    imageHeight: 864,
    title: "Venice opens the autumn, and a British film opens Venice",
    cardTitle: "A British film opens Venice",
    titleSeo: "Venice Film Festival 2026 opens",
    summary:
      "Danny Boyle's Ink starts the 83rd Mostra on 2 September. It is the first of the three festivals that decide what London's cinemas show in October.",
    date: "2026-09-01",
    category: "Film",
    source: {
      name: "Screen International",
      url: "https://www.screendaily.com/news/venice-film-festival-reveals-2026-lineup/5218820.article",
      verifiedOn: "2026-09-01",
    },
    body: [
      "The autumn film season does not begin in London. It begins on a strip of sand outside Venice, and by the time it reaches a cinema here the argument about what is good has largely been had without us.",
      "## What opens on 2 September",
      "The <strong>83rd Venice Film Festival</strong> runs from <strong>2 to 12 September 2026</strong> on the <strong>Lido</strong>, under artistic director <strong>Alberto Barbera</strong>. The competition jury is chaired by <strong>Maggie Gyllenhaal</strong>.",
      "It opens with <strong>Ink</strong>, directed by <strong>Danny Boyle</strong>, with Guy Pearce. It closes with <strong>God Laughs</strong>, by Giovanni Veronesi. Honorary Golden Lions go to <strong>Ellen Burstyn</strong> and <strong>George Clooney</strong>.",
      "## The British end of the competition",
      "Two of the twenty competition titles announced on 23 July come from directors working out of these islands: Boyle&rsquo;s <strong>Ink</strong>, and <strong>Wild Horse Nine</strong> from <strong>Martin McDonagh</strong>.",
      "Around them: Werner Herzog with <strong>Bucking Fastard</strong>, Hirokazu Koreeda with <strong>Look Back</strong>, Lee Chang-dong with <strong>Possible Love</strong>, plus Nanni Moretti, Florian Zeller and Shinya Tsukamoto. Barbera warned that this year&rsquo;s selection runs long; the longest is Ilya Khrzhanovsky&rsquo;s <strong>Dau</strong>, at <strong>210 minutes</strong>.",
      "## Why a Londoner should care about the Lido",
      "Venice is the first of three festivals &mdash; Venice, Telluride, Toronto &mdash; that between them settle which autumn films get bought, which get a proper release and which quietly go to a streaming service. A title that lands well on the Lido this fortnight is a title that turns up on a London screen with a poster full of stars on it.",
      "It is also the reason the next fortnight matters here specifically. The <strong>BFI London Film Festival</strong> publishes its full programme on <strong>Wednesday 2 September</strong> &mdash; the same day Venice opens &mdash; and runs <strong>7 to 18 October</strong>. A good part of what appears on that programme is being shown to an audience for the first time this week.",
      "## The honest caveat",
      "A Golden Lion is a jury of seven people in a room. It predicts distribution far better than it predicts what anyone will actually enjoy, and the films that turn out to matter from a given September are regularly the ones that left Venice with nothing.",
    ],
    expertise:
      "The useful thing to do with the Venice reviews is not to build a watchlist from the winners. It is to note the titles that reviewers disagree about most sharply &mdash; those are the ones worth seeing at a festival rather than waiting for, because a consensus film will still be a consensus film in March, and a divisive one is best seen before you have been told what to think of it.",
  },
  {
    slug: "va-exhibitions-closing-dates",
    site: "ldn",
    image: "/covers/va-exhibitions-closing-dates.jpg",
    imageAlt: "A row of gallery doorways receding, the nearest shutter half lowered under a clock",
    imageKind: "generated",
    imageWidth: 1536,
    imageHeight: 864,
    title: "The V&A closing dates worth putting in a diary",
    summary:
      "Four V&A exhibitions have published closing dates and one opens in November. Schiaparelli goes first, on 8 November — and it is the one with the shortest run left.",
    date: "2026-08-29",
    category: "Exhibitions",
    source: {
      name: "Victoria and Albert Museum",
      url: "https://www.vam.ac.uk/exhibitions/schiaparelli-fashion-becomes-art",
      verifiedOn: "2026-08-30",
    },
    body: [
      "Museums announce openings loudly and closings quietly, which is exactly backwards from the visitor&rsquo;s point of view. An opening is an invitation with no deadline attached; a closing date is the only piece of information that ever makes anybody actually go.",
      "So here are the V&amp;A&rsquo;s, in the order they run out.",
      "## 8 November &mdash; Schiaparelli: Fashion Becomes Art",
      "Closing <strong>Sunday 8 November 2026</strong> at V&amp;A South Kensington. Tickets are <strong>&pound;28</strong> on weekdays and <strong>&pound;30</strong> at weekends.",
      "This is the first British exhibition devoted to Elsa Schiaparelli, and the scale of it is the reason it is worth the deadline: over <strong>400 objects</strong>, including <strong>100 ensembles</strong>, alongside some <strong>50 artworks</strong> by Dal&iacute;, Picasso and Man Ray.",
      "That mix is the whole argument of the show. Schiaparelli worked with the Surrealists rather than borrowing from them &mdash; the lobster, the shoe worn as a hat, the trompe-l&rsquo;&oelig;il knits are collaborations, not references. Hanging the paintings beside the clothes is the only way to make that case, and it is the reason this is a fashion exhibition that people who do not go to fashion exhibitions tend to come out of talking.",
      "## 15 November &mdash; Inside Aardman",
      "<em>Inside Aardman: Wallace &amp; Gromit and Friends</em> closes <strong>15 November 2026</strong> at <strong>Young V&amp;A</strong> in Bethnal Green. Tickets <strong>&pound;12.50</strong>.",
      "Worth knowing which building this is in: Young V&amp;A is a different site from South Kensington, and a family planning a single day out cannot do this one and Schiaparelli without crossing London in between.",
      "## 10 January &mdash; two shows, two buildings",
      "<em>The Music is Black: A British Story</em> closes <strong>10 January 2027</strong> at <strong>V&amp;A East</strong>, <strong>&pound;22.50</strong>. <em>Rising Voices: Contemporary Art from Asia, Australia and the Pacific</em> closes the same day at South Kensington, <strong>&pound;17</strong>.",
      "Sharing a closing date across two sites is a scheduling detail with a practical consequence: the first weekend of January will be the busy one at both, and the quiet weeks are the ones before Christmas.",
      "## 7 November &mdash; the one that opens",
      "<em>Constantinople to Istanbul: One City, Two Empires</em> opens <strong>Saturday 7 November 2026</strong> at South Kensington &mdash; the day before Schiaparelli closes.",
      "Which makes that weekend the only one where both are on. If there is a single date in this piece to write down, it is <strong>Saturday 7 or Sunday 8 November</strong>.",
      "## What is not here",
      "Opening dates for the other shows are not listed above because the museum has not published them all, and a guide that guesses at one is worse than a guide that leaves it out. What is printed here is what the V&amp;A itself has stated, checked on the day this was written.",
    ],
    expertise:
      "Weekday tickets to Schiaparelli are &pound;2 cheaper, which is not the reason to go on a weekday. The reason is that a 400-object show with 100 ensembles is a slow one &mdash; the garments reward standing still in front of them &mdash; and a Saturday in the final fortnight of a closing exhibition is the one condition under which that is impossible.",
  },
  {
    slug: "notting-hill-carnival-turns-60",
    featured: 2,
    site: "ldn",
    image: "/covers/notting-hill-carnival-turns-60.jpg",
    imageAlt: "A blank plaque on a brick wall with feathers and ribbons fanning out behind it",
    imageKind: "generated",
    imageWidth: 1536,
    imageHeight: 864,
    title: "Notting Hill Carnival turns sixty",
    summary:
      "A plaque at Westbourne Park names seventy people who built Carnival — unveiled for its sixtieth year, and for seventy years since London Transport went recruiting in the Caribbean.",
    date: "2026-08-28",
    category: "Carnival",
    source: {
      name: "BBC London",
      url: "https://www.bbc.co.uk/news/articles/cx2zndw0wdwo",
      verifiedOn: "2026-08-30",
    },
    body: [
      "Carnival&rsquo;s sixtieth year was marked with something more durable than a parade: a plaque at Westbourne Park Underground station naming <strong>70 people</strong> who helped create it.",
      "The station is not a neutral choice. Westbourne Park sits at the northern end of the parade route and is one of the main stations people use to get there &mdash; the plaque is at the top of the road, where the thing itself starts.",
      "## Two anniversaries, deliberately joined",
      "The unveiling marks Carnival&rsquo;s sixtieth, and also <strong>70 years since London Transport began recruiting staff in the Caribbean</strong>. In <strong>1956</strong>, unable to find enough people to run the capital&rsquo;s expanding bus and Underground network, London Transport sent recruitment officers across the Atlantic. Those who came were employed right across the network, and many stayed for the rest of their working lives.",
      "> Carnival is a celebration of the Caribbean communities that have shaped our city, and the men and women recruited in 1956 helped create the transport system the capital relies on today.\n— Andy Lord, London&rsquo;s transport commissioner",
      "## Whose names are on it",
      "Costume designers, mas players, steel pan players and sound system operators &mdash; the four crafts Carnival is actually made of, rather than the officials who administer it.",
      "The first two names listed are <strong>Claudia Jones</strong> and <strong>Rhaune Laslett</strong>. Jones, born in Trinidad and the founder of the West Indian Gazette, organised an indoor Caribbean carnival in London from <strong>1959</strong> until her death in <strong>1964</strong>. Laslett was instrumental in setting up the Notting Hill street festival that grew into the Carnival.",
      "That is two different events, five years apart, one indoors and one in the street &mdash; and putting both names first is an argument about where Carnival came from, made in brass.",
      "## Who put it there",
      "The plaque was organised by the <strong>Nubian Jak Community Trust</strong>. Its chief executive, Dr Jak Beula, said installing it at Westbourne Park fulfilled a long-held ambition and would give people a way to learn about Carnival&rsquo;s origins in Britain.",
      "TfL, whose own history the plaque is half about, also ran a decorated bus in the Sunday parade and showed an exhibition of artwork by its staff at Paddington.",
      "## The number that explains the station choice",
      "More than <strong>two million journeys</strong> are made on the transport network for Carnival each year, according to the TfL colleague network group that works on it.",
      "Which is why the standing advice is to travel to <strong>Paddington and walk</strong>: the stations nearer the route cannot absorb that, and Westbourne Park itself &mdash; the one with the plaque on it &mdash; is among the first to come under pressure.",
    ],
    expertise:
      "The plaque outlasts the weekend, and it is easier to read in October than in August. Westbourne Park is a ten-minute walk from Portobello Road, so it fits onto an ordinary Saturday in the area rather than requiring a trip of its own &mdash; which is more or less the point of putting it on a station rather than in a museum.",
  },
  {
    slug: "partial-lunar-eclipse-over-london",
    site: "ldn",
    image: "/covers/partial-lunar-eclipse-over-london.jpg",
    imageAlt: "A dark disc hanging over a row of rooftops at night",
    imageKind: "generated",
    imageWidth: 1536,
    imageHeight: 864,
    title: "A partial lunar eclipse, visible from London",
    summary:
      "London's second eclipse in a fortnight: 93% of the Moon in shadow at 5.12am on Friday 28 August, no glasses needed, and Parliament Hill the one obvious place to stand.",
    date: "2026-08-28",
    category: "Sky",
    source: {
      name: "Evening Standard",
      url: "https://www.standard.co.uk/news/london/partial-lunar-eclipse-2026-london-uk-viewing-time-blood-moon-b1294744.html",
      verifiedOn: "2026-08-30",
    },
    body: [
      "Two eclipses in sixteen days is not a thing London gets often, and the second was the easier one to watch: nothing to buy, nothing to protect your eyes with, and no crowd &mdash; because it happened while the city was asleep.",
      "## The timings",
      "The partial lunar eclipse ran in the early hours of <strong>Friday 28 August</strong>. It began at about <strong>3.33am</strong> London time and reached maximum at about <strong>5.12am</strong>, with roughly <strong>93% of the Moon&rsquo;s visible diameter</strong> covered by Earth&rsquo;s shadow, according to the Royal Museums Greenwich.",
      "Then it ran out of sky. Moonset was around <strong>6.15am</strong> and the eclipse formally ended at <strong>6.51am</strong> &mdash; by which point the Moon was already below the London horizon. The last forty minutes of it happened to somebody else.",
      "## Why it goes red",
      "At maximum the Moon takes on a deep coppery red, the thing people call a blood moon. The cause is the Earth&rsquo;s atmosphere: sunlight passing through it is scattered and bent, and the red end of that light is what carries on to the lunar surface. What you are looking at, strictly, is every sunrise and sunset on Earth projected at once onto a rock a quarter of a million miles away.",
      "Because the Moon sat low over the south-western horizon throughout, it also read as unusually large against the skyline &mdash; the moon illusion, which is in the eye rather than the sky, but is no less convincing for it.",
      "## No glasses this time",
      "This is the part people got wrong after August. The <strong>partial solar eclipse on 12 August</strong> filled the parks and emptied the shops of protective glasses &mdash; more than <strong>90% of the Sun</strong> was covered, the most in UK skies since the total eclipse of <strong>1999</strong>.",
      "A lunar eclipse is the opposite case. Looking straight at it does no harm at all. Binoculars or a telescope are worth having, not for safety but for the surface detail.",
      "## Where to stand, when it happens again",
      "Astronomers give one instruction: get high, with a clear view to the <strong>south-west</strong>. The difficulty in London is that most of the major parks that filled up for the solar eclipse are shut in the small hours. <strong>Hampstead Heath is open 24 hours</strong>, which makes <strong>Parliament Hill</strong> the obvious answer &mdash; height, an open southern aspect, and legally accessible at 5am.",
      "The forecast on the day promised cloud and light rain, which is the ordinary English ending to a story like this one.",
    ],
    expertise:
      "The 5.12am maximum was the whole event. An eclipse listed as running from 3.33 to 6.51 sounds like a window; in practice the interesting phase is the twenty minutes either side of maximum, and the last stretch of this one was below the horizon anyway. Setting an alarm for the start time was the reliable way to stand outside for ninety minutes watching almost nothing.",
  },
  {
    slug: "ten-exhibitions-on-in-london",
    featured: 1,
    site: "ldn",
    image: "/covers/ten-exhibitions-on-in-london.jpg",
    imageAlt: "Ten empty picture frames of different sizes hung across a gallery wall",
    imageKind: "generated",
    imageWidth: 1536,
    imageHeight: 864,
    title: "What is actually hanging in London right now",
    summary:
      "Ten shows are on the critics' list. Six of them close before January, one has sold more advance tickets than anything in Tate's 128-year history, and two of the best are free.",
    date: "2026-08-27",
    category: "Art",
    source: {
      name: "Time Out London",
      url: "https://www.timeout.com/london/art/top-10-art-exhibitions-in-london",
      verifiedOn: "2026-08-30",
    },
    body: [
      "There is no shortage of exhibitions in London. There is a shortage of weekends &mdash; which is why the only useful way to read a top-ten list is by closing date, not by star rating.",
      "Here is the current critics&rsquo; ten, sorted by how long you have left.",
      "## Closing first",
      "<strong>NIGO: From Japan with Love</strong> at the Design Museum, Kensington, closes <strong>4 October</strong>. The first London retrospective for the man behind Bape and Human Made and Kenzo&rsquo;s creative director since 2021: <strong>700 objects</strong>, <strong>600 of them from his own archive</strong> &mdash; records, toys, magazines, music videos and a great deal of clothing, from the 1980s on. It is also the clearest explanation anyone has staged of where &laquo;scarcity by design&raquo; came from.",
      "<strong>Anish Kapoor</strong> at the Hayward, South Bank, closes <strong>18 October</strong>. His second solo show there &mdash; the last was in 1998 &mdash; with the greatest hits and some monumental new work. The voids are the reason to go: sculptures painted in a black that absorbs <strong>99.965% of visible light</strong>, which is the record for the darkest manmade substance, and which your eyes simply refuse to read as a surface.",
      "<strong>Musquiqui Chihying: A Life of Navigation</strong>, also South Bank, closes <strong>18 October</strong>, and it is <strong>free</strong>. Four works by the Taiwanese artist and filmmaker on how people navigate high-stress city life. Small, funny, and the best value on this list by a distance.",
      "<strong>Schiaparelli: Fashion Becomes Art</strong> at the V&amp;A closes <strong>8 November</strong>. The first British exhibition on Elsa Schiaparelli, with Dal&iacute;, Man Ray and Leonor Fini hung alongside the clothes, dresses worn by Ariana Grande and Dua Lipa, and the lobster telephone.",
      "## The winter shows",
      "<strong>Frida: The Making of an Icon</strong> at Tate Modern runs to <strong>3 January 2027</strong>, and it has already sold more advance tickets than any exhibition in Tate&rsquo;s <strong>128-year history</strong>. The strongest part is the beginning: <strong>23 paintings</strong> and <strong>11 works on paper</strong> by Kahlo, with the photographs she sat for, her jewellery and Indigenous Mexican clothing from her wardrobe. The later rooms are about the phenomenon rather than the painter, which is a fair subject but a different one.",
      "<strong>Ana Mendieta</strong> at Tate Modern runs to <strong>17 January 2027</strong> &mdash; her first major UK gallery exhibition, spanning performance, sculpture, land art, photography and video, with many pieces never shown in this country. The <em>Siluetas</em> series is what people come out talking about.",
      "## The one that closes this week",
      "<strong>Tracey Emin: A Second Life</strong> at Tate Modern is the only five-star show on the list and it closes <strong>31 August</strong>. If you are reading this on the day, that is the decision made for you.",
      "## What we would put first",
      "If there is one afternoon: <strong>Chihying at the Hayward</strong>, because it is free, then <strong>Kapoor</strong> upstairs in the same building. Two shows, one address, one ticket between them.",
      "If there is one ticket: <strong>Schiaparelli</strong>. Frida will be the busier show and the better-known name, but the V&amp;A has assembled something that does not exist anywhere else and dismantles it in November.",
    ],
    expertise:
      "Star ratings and closing dates pull in opposite directions. The five-star show on this list has days left; two of the three-star ones run into next year. A list read top-down sends you to the thing that is about to vanish and leaves the rest unseen &mdash; which is exactly backwards, because the ones with months left are the ones you can plan around a quiet Tuesday.",
  },
];
