import type { NewsItem } from "../types.ts";

export const items: NewsItem[] = [
  {
    slug: "michael-ball-takes-the-coliseum-as-willy-wonka",
    site: "ldn",
    image: "/covers/michael-ball-takes-the-coliseum-as-willy-wonka.jpg",
    imageAlt: "A tall red paper top hat on a warm off-white ground with a charcoal ticket shape tucked into its band",
    imageKind: "generated",
    imageWidth: 1536,
    imageHeight: 864,
    title: "Charlie and the Chocolate Factory returns, with Michael Ball at the Coliseum",
    cardTitle: "Michael Ball is the Coliseum's Wonka",
    titleSeo: "Michael Ball is the Coliseum's Willy Wonka",
    summary:
      "A new production runs 4 June to 18 September 2027 at the London Coliseum, directed by Nikolai Foster. Priority booking opens on 29 September.",
    date: "2026-09-03",
    category: "Theatre",
    source: {
      name: "Charlie and the Chocolate Factory",
      url: "https://charliethemusical.com/",
      verifiedOn: "2026-09-03",
    },
    body: [
      "The last West End Wonka ran for three years at Drury Lane and then vanished for a decade. He is back, in the largest theatre in London.",
      "## The run",
      "<strong>4 June to 18 September 2027</strong> at the <strong>London Coliseum</strong>, billed as a strictly limited season. <strong>Michael Ball OBE</strong> plays Willy Wonka.",
      "## Who is making it",
      "Directed by <strong>Nikolai Foster</strong>, artistic director of Curve in Leicester. Set design by <strong>Leslie Travers</strong>, costumes by the Olivier-winning <strong>Katrina Lindsay</strong>. The book is <strong>David Greig</strong>'s, the music <strong>Marc Shaiman</strong>'s, with lyrics by <strong>Scott Wittman</strong> and Shaiman.",
      "## The songs",
      "The score keeps the 1971 film's best-known numbers &mdash; <em>Pure Imagination</em>, <em>The Candy Man</em>, <em>I've Got a Golden Ticket</em> &mdash; alongside the original Shaiman and Wittman material written for the stage version.",
      "## Booking",
      "The production's own site has priority sign-up open now, with tickets from <strong>29 September</strong>.",
    ],
    expertise:
      "The venue is the detail that changes the show. The Coliseum seats around 2,350 and is English National Opera's house, which makes it the largest theatre in the West End and a very different room from the Theatre Royal Drury Lane, where the 2013 production ran. Chocolate rivers and glass lifts scale up well; intimate scenes do not, and how Foster handles that is the interesting question. Practically: a strictly limited summer season at a house that size means a great many seats and a short window, so the good news for anyone booking is that the balcony at the Coliseum has the steepest rake in London and the worst reputation — the rear stalls are usually the better value at the same price.",
  },

  {
    slug: "bayeux-tapestry-at-the-british-museum",
    site: "ldn",
    image: "/covers/bayeux-tapestry-at-the-british-museum.jpg",
    imageAlt: "A single long narrow ribbon of undyed linen-coloured paper stretching across an empty cream ground",
    imageKind: "generated",
    imageWidth: 1536,
    imageHeight: 864,
    title: "The Bayeux Tapestry is in England for the first time in 900 years",
    cardTitle: "The Bayeux Tapestry comes to London",
    titleSeo: "Bayeux Tapestry at the British Museum",
    summary:
      "Seventy metres of eleventh-century embroidery go on show from 10 September until 11 July 2027. Tickets are £33, and the next release is on 21 October.",
    date: "2026-09-02",
    category: "Exhibitions",
    source: {
      name: "The British Museum",
      url: "https://www.britishmuseum.org/exhibitions",
      verifiedOn: "2026-09-02",
    },
    body: [
      "The object that tells England the story of its own conquest has spent almost its entire existence in Normandy. From 10 September it is in Bloomsbury.",
      "## The dates and the price",
      "The <strong>Bayeux Tapestry</strong> is at the <strong>British Museum</strong> from <strong>10 September 2026</strong> to <strong>11 July 2027</strong>. Tickets are <strong>&pound;33</strong>. The next general release is <strong>21 October</strong>, covering <strong>1 January to 31 March 2027</strong>; Members can book from <strong>6 October</strong>.",
      "It is roughly <strong>seventy metres</strong> long, and this is the first time it has been in England in something close to <strong>a thousand years</strong>.",
      "## What you are actually looking at",
      "Not a tapestry &mdash; it is embroidery, wool on linen, which is why it survived. It carries <strong>more than 600 figures</strong>, of whom <strong>three are women</strong>. That ratio is not a curiosity; it is the argument the object makes about whose eleventh century was worth recording.",
      "Director <strong>Dr Nicholas Cullinan</strong> has described the loan as a once-in-a-lifetime event, and on the arithmetic of the last millennium that is difficult to dispute.",
      "## Seventy metres is a problem, not a boast",
      "The length is the whole difficulty of showing it. A seventy-metre object cannot be taken in from a viewpoint; it has to be walked, in one direction, at whatever pace the person in front of you has chosen. Museums that have shown long narrative works know that the crowd, not the case, sets the experience.",
      "Which is the practical reason to care about the booking dates. The difference between a September slot and a wet Tuesday in February is not the object. It is how many people are between you and it.",
      "## Beyond London",
      "<strong>Bayeux Around Britain</strong> runs alongside it at more than <strong>60 sites</strong>, which is the sensible response to a single object that cannot be in sixty places.",
    ],
    expertise:
      "If the timed slots for autumn have gone, the 21 October release for January to March is the one to plan for, and the Members' window on 6 October is worth the membership arithmetic on its own for a group booking. Long linear displays reward the last hour of the day rather than the first: the opening slots absorb the people who booked earliest and travelled furthest.",
  },
  {
    slug: "nature-and-us-opens-a-gallery-shut-since-1943",
    site: "ldn",
    image: "/covers/nature-and-us-opens-a-gallery-shut-since-1943.jpg",
    imageAlt: "A tall paper archway in red, orange and deep red opening onto a pale cream interior",
    imageKind: "generated",
    imageWidth: 1536,
    imageHeight: 864,
    title: "A gallery closed to the public since 1943 reopens this month",
    cardTitle: "Shut since 1943, open from 16 September",
    titleSeo: "Nature & Us opens at the Natural History Museum",
    summary:
      "The Natural History Museum's new free gallery puts a 400,000-year-old hand-axe beside a Star Wars toy that spent the 1980s under the sea.",
    date: "2026-09-02",
    category: "Museums",
    source: {
      name: "Londonist",
      url: "https://londonist.com/",
      verifiedOn: "2026-09-02",
    },
    body: [
      "Museums usually reopen rooms that closed for refurbishment. This one closed during the Second World War and stayed shut.",
      "## The opening",
      "<strong>Nature &amp; Us</strong> opens at the <strong>Natural History Museum</strong> on <strong>16 September 2026</strong>. Entry is <strong>free</strong>. The space it occupies has been closed to the public since <strong>1943</strong>.",
      "## The objects doing the work",
      "Three of them explain the gallery's argument better than any wall text could.",
      "A <strong>400,000-year-old hand-axe</strong> &mdash; the point at which the relationship starts being one-directional. A <strong>touchable replica of one of Britain's first domesticated dogs</strong>, which is the moment another species was rebuilt to suit us. And a <strong>1980s Star Wars toy encrusted with bryozoans</strong>, dredged from the sea, where the process has run the other way and nature has claimed the manufactured object back.",
      "## Why the last one is the best exhibit",
      "The hand-axe and the dog are the story museums have told for decades. The colonised toy is the harder idea: that the boundary between the natural and the made has stopped being a boundary. A plastic figure that spent forty years growing a reef is not pollution illustrated, it is a habitat.",
      "It also does something a diorama cannot. Everyone over forty recognises the toy. Recognition is what turns a display case into an uncomfortable thought.",
      "## The free part is not incidental",
      "A gallery about humanity's relationship with the natural world that charged admission would be making a slightly awkward argument. Free entry means it can be visited in twenty minutes, repeatedly, by people who live nearby &mdash; which is how a permanent gallery actually earns its place.",
    ],
    expertise:
      "New free galleries at South Kensington follow a predictable curve: heavy for the first six weekends, then quiet on weekday mornings within a term. The museum's least-used entrance is the Exhibition Road side, which also puts you nearer this end of the building than the queue on Cromwell Road does.",
  },
  {
    slug: "lady-in-blue-takes-the-fourth-plinth",
    site: "ldn",
    image: "/covers/lady-in-blue-takes-the-fourth-plinth.jpg",
    imageAlt: "A small blue paper figure standing on a pale stone-coloured block above a red band",
    imageKind: "generated",
    imageWidth: 1536,
    imageHeight: 864,
    title: "The Fourth Plinth changes hands on 10 September",
    cardTitle: "Lady in Blue takes the Fourth Plinth",
    titleSeo: "Tschabalala Self's Lady in Blue unveiled",
    summary:
      "Tschabalala Self's Lady in Blue goes up in Trafalgar Square from 10 September and stays until summer 2028 — the longest commitment in public art here.",
    date: "2026-09-02",
    category: "Art",
    source: {
      name: "Mayor of London",
      url: "https://www.london.gov.uk/programmes-strategies/arts-and-culture/current-culture-projects/fourth-plinth-trafalgar-square",
      verifiedOn: "2026-09-02",
    },
    body: [
      "Trafalgar Square has three permanent statues and one argument. The argument moves on again this month.",
      "## The commission",
      "<strong>Tschabalala Self</strong>'s <strong>Lady in Blue</strong> is unveiled on the <strong>Fourth Plinth</strong> on <strong>10 September 2026</strong> and remains until <strong>summer 2028</strong>.",
      "## Nearly two years is the interesting number",
      "Most public art in London is temporary in the sense of a season. The Fourth Plinth works on a scale of roughly two years, which is long enough for a work to stop being news and become part of the walk to Charing Cross.",
      "That transition is the whole point of the commission and the part nobody photographs. A sculpture is judged in its first week by people who came to see it and in its second year by people who did not. Very few survive the second audience.",
      "## Why the plinth was empty in the first place",
      "It was built in 1841 for an equestrian statue that was never funded. London spent more than a century and a half failing to agree on what should stand there, then solved the problem by deciding nothing permanent ever would.",
      "It is difficult to think of a better solution to a disagreement about national memory than a rota.",
    ],
    expertise:
      "The plinth is on the north-west corner, which means the light is behind it for most of the afternoon. Anyone photographing it will get a silhouette between roughly noon and four; morning gives the front of the work, and the National Gallery steps give the only elevated public view of it without a crowd in the frame.",
  },
  {
    slug: "frieze-sculpture-in-regents-park",
    site: "ldn",
    image: "/covers/frieze-sculpture-in-regents-park.jpg",
    imageAlt: "Upright abstract paper shapes in orange, green and charcoal standing on a band of green paper grass",
    imageKind: "generated",
    imageWidth: 1536,
    imageHeight: 864,
    title: "Eleven artists are installing work in Regent's Park for free",
    cardTitle: "Frieze Sculpture: free, and outdoors",
    titleSeo: "Frieze Sculpture 2026 in Regent's Park",
    summary:
      "From 16 September to 1 November, eleven artists take over the English Gardens on the theme of hybridity. No ticket, no booking, no queue.",
    date: "2026-09-02",
    category: "Art",
    source: {
      name: "Frieze",
      url: "https://www.frieze.com/fairs/frieze-sculpture",
      verifiedOn: "2026-09-02",
    },
    body: [
      "The most expensive week in the London art calendar has one part that costs nothing.",
      "## The dates",
      "<strong>Frieze Sculpture</strong> runs from <strong>16 September</strong> to <strong>1 November 2026</strong> in the <strong>English Gardens</strong> of <strong>Regent's Park</strong>. <strong>Eleven artists</strong> are showing, on the theme of <strong>hybridity</strong>. It is <strong>free</strong>, and it opens more than two weeks before the fair itself.",
      "## Six weeks is a long time for outdoor sculpture",
      "It runs from mid-September to the beginning of November, which in this city means the work will be seen in three quite different conditions: late summer, the two good weeks of autumn colour, and the first genuinely dark afternoons.",
      "Outdoor sculpture is rarely designed for that range. A piece that reads well against green in September can look abandoned against wet bare branches in November, and the ones that survive both are usually the ones that were made with weather in mind rather than with a gallery in mind.",
      "## Hybridity, in a park",
      "The theme is doing more work than a theme usually does here. The English Gardens are themselves a hybrid &mdash; a designed landscape pretending to be a natural one, in the middle of a city, laid out by an architect. Putting work about mixed categories into a place that is itself a category error is a genuinely good curatorial joke.",
      "## The practical point",
      "No ticket, no timed slot, no bag search. During Frieze week the park is the only part of the London art calendar you can walk into on the way to something else.",
    ],
    expertise:
      "Go before the fair opens in early October rather than during it. The same eleven works are there, and the difference is several thousand fewer people with lanyards. Regent's Park at eight in the morning is also the only time the sculptures can be photographed without a person in the shot.",
  },
  {
    slug: "apples-chairman-now-has-a-policy-job",
    site: "ldn",
    image: "/covers/apples-chairman-now-has-a-policy-job.jpg",
    imageAlt: "Two paper columns flanking a red panel, a small folded white sheet floating between them, low steps beneath",
    imageKind: "generated",
    imageWidth: 1536,
    imageHeight: 864,
    title: "Apple has created a job whose stated task is talking to governments",
    cardTitle: "Apple's chairman: a policy job",
    titleSeo: "Apple&rsquo;s chairman now has a policy remit",
    summary:
      "Tim Cook stopped being chief executive on 1 September. His new role comes with a remit Apple wrote down: engaging with policymakers around the world.",
    date: "2026-09-01",
    category: "Tech",
    source: {
      name: "Apple Newsroom",
      url: "https://www.apple.com/newsroom/2026/04/tim-cook-to-become-apple-executive-chairman-john-ternus-to-become-apple-ceo/",
      verifiedOn: "2026-09-02",
    },
    body: [
      "The headline on 1 September was that Apple changed chief executive. The more revealing detail is what it decided the outgoing one should do next.",
      "## The wording",
      "<strong>Tim Cook</strong> became <strong>executive chairman</strong>, and Apple described the role as including engaging with policymakers around the world. Not an honorary chairmanship, not a general advisory arrangement &mdash; a named remit, held by the person who ran the company for fifteen years.",
      "<strong>John Ternus</strong>, at Apple since <strong>2001</strong> and previously <strong>senior vice president of Hardware Engineering</strong>, took the chief executive's job the same day. <strong>Arthur Levinson</strong>, chairman for the past fifteen years, became lead independent director.",
      "## What that says about the shape of the work",
      "A company splits a job in two when one half has grown enough to need its own person. Apple has effectively concluded that dealing with regulators is no longer something a chief executive does between other things.",
      "That is a judgement about the environment rather than about either man. A firm selling into <strong>200-plus countries and territories</strong> with more than <strong>2.5 billion</strong> active devices is answerable to a great many rule-making bodies at once, and those rules increasingly govern the product itself &mdash; what a store may charge, what a device must be able to connect to, what a service must let a user take away.",
      "## Why it reads differently from London",
      "Britain and the European Union have spent this decade writing exactly that kind of rule, which makes them a substantial share of the diary attached to Cook's new job. The practical effect for anyone here is not abstract: the terms on which a phone works, what can be installed on it and what a marketplace may charge are now set as much in regulatory proceedings as in product decisions.",
      "So a governance line in a corporate announcement is, indirectly, a statement about how much of the product is decided in rooms with no engineers in them.",
      "## What has not changed",
      "Nothing for anyone using an Apple device this week. Ternus inherits a company that grew from about <strong>$350 billion</strong> to roughly <strong>$4 trillion</strong> in market value under Cook, with revenue up from <strong>$108 billion</strong> in FY2011 to <strong>$416 billion</strong> in FY2025. Continuity was rather the point of promoting a twenty-five-year insider.",
    ],
    expertise:
      "Watch which of the two now appears in regulatory proceedings. The division only means anything if Cook genuinely fronts them and Ternus genuinely does not; if the chief executive keeps turning up at hearings, the split was cosmetic and the workload simply moved. That is visible in public filings and published hearing lists, and it will be clear within a year.",
  },
  {
    slug: "venice-opens-the-autumn-with-a-british-film",
    site: "ldn",
    image: "/covers/venice-opens-the-autumn-with-a-british-film.jpg",
    imageAlt: "A paper stage curtain drawn back from a blank screen, a band of lagoon water below and a small winged lion above",
    imageKind: "generated",
    imageWidth: 1536,
    imageHeight: 864,
    title: "Venice opens the autumn, and a British film opens Venice",
    cardTitle: "A British film opens Venice",
    titleSeo: "Venice Film Festival 2026 opens",
    summary:
      "Danny Boyle's Ink starts the 83rd Mostra on 2 September. It is the first of the three festivals that decide what London's cinemas show in October.",
    date: "2026-09-01",
    category: "Film",
    source: {
      name: "Screen International",
      url: "https://www.screendaily.com/news/venice-film-festival-reveals-2026-lineup/5218820.article",
      verifiedOn: "2026-09-01",
    },
    body: [
      "The autumn film season does not begin in London. It begins on a strip of sand outside Venice, and by the time it reaches a cinema here the argument about what is good has largely been had without us.",
      "## What opens on 2 September",
      "The <strong>83rd Venice Film Festival</strong> runs from <strong>2 to 12 September 2026</strong> on the <strong>Lido</strong>, under artistic director <strong>Alberto Barbera</strong>. The competition jury is chaired by <strong>Maggie Gyllenhaal</strong>.",
      "It opens with <strong>Ink</strong>, directed by <strong>Danny Boyle</strong>, with Guy Pearce. It closes with <strong>God Laughs</strong>, by Giovanni Veronesi. Honorary Golden Lions go to <strong>Ellen Burstyn</strong> and <strong>George Clooney</strong>.",
      "## The British end of the competition",
      "Two of the twenty competition titles announced on 23 July come from directors working out of these islands: Boyle&rsquo;s <strong>Ink</strong>, and <strong>Wild Horse Nine</strong> from <strong>Martin McDonagh</strong>.",
      "Around them: Werner Herzog with <strong>Bucking Fastard</strong>, Hirokazu Koreeda with <strong>Look Back</strong>, Lee Chang-dong with <strong>Possible Love</strong>, plus Nanni Moretti, Florian Zeller and Shinya Tsukamoto. Barbera warned that this year&rsquo;s selection runs long; the longest is Ilya Khrzhanovsky&rsquo;s <strong>Dau</strong>, at <strong>210 minutes</strong>.",
      "## Why a Londoner should care about the Lido",
      "Venice is the first of three festivals &mdash; Venice, Telluride, Toronto &mdash; that between them settle which autumn films get bought, which get a proper release and which quietly go to a streaming service. A title that lands well on the Lido this fortnight is a title that turns up on a London screen with a poster full of stars on it.",
      "It is also the reason the next fortnight matters here specifically. The <strong>BFI London Film Festival</strong> publishes its full programme on <strong>Wednesday 2 September</strong> &mdash; the same day Venice opens &mdash; and runs <strong>7 to 18 October</strong>. A good part of what appears on that programme is being shown to an audience for the first time this week.",
      "## The honest caveat",
      "A Golden Lion is a jury of seven people in a room. It predicts distribution far better than it predicts what anyone will actually enjoy, and the films that turn out to matter from a given September are regularly the ones that left Venice with nothing.",
    ],
    expertise:
      "The useful thing to do with the Venice reviews is not to build a watchlist from the winners. It is to note the titles that reviewers disagree about most sharply &mdash; those are the ones worth seeing at a festival rather than waiting for, because a consensus film will still be a consensus film in March, and a divisive one is best seen before you have been told what to think of it.",
  },
  {
    slug: "va-exhibitions-closing-dates",
    site: "ldn",
    image: "/covers/va-exhibitions-closing-dates.jpg",
    imageAlt: "A row of gallery doorways receding, the nearest shutter half lowered under a clock",
    imageKind: "generated",
    imageWidth: 1536,
    imageHeight: 864,
    title: "The V&A closing dates worth putting in a diary",
    summary:
      "Four V&A exhibitions have published closing dates and one opens in November. Schiaparelli goes first, on 8 November — and it is the one with the shortest run left.",
    date: "2026-08-29",
    category: "Exhibitions",
    source: {
      name: "Victoria and Albert Museum",
      url: "https://www.vam.ac.uk/exhibitions/schiaparelli-fashion-becomes-art",
      verifiedOn: "2026-08-30",
    },
    body: [
      "Museums announce openings loudly and closings quietly, which is exactly backwards from the visitor&rsquo;s point of view. An opening is an invitation with no deadline attached; a closing date is the only piece of information that ever makes anybody actually go.",
      "So here are the V&amp;A&rsquo;s, in the order they run out.",
      "## 8 November &mdash; Schiaparelli: Fashion Becomes Art",
      "Closing <strong>Sunday 8 November 2026</strong> at V&amp;A South Kensington. Tickets are <strong>&pound;28</strong> on weekdays and <strong>&pound;30</strong> at weekends.",
      "This is the first British exhibition devoted to Elsa Schiaparelli, and the scale of it is the reason it is worth the deadline: over <strong>400 objects</strong>, including <strong>100 ensembles</strong>, alongside some <strong>50 artworks</strong> by Dal&iacute;, Picasso and Man Ray.",
      "That mix is the whole argument of the show. Schiaparelli worked with the Surrealists rather than borrowing from them &mdash; the lobster, the shoe worn as a hat, the trompe-l&rsquo;&oelig;il knits are collaborations, not references. Hanging the paintings beside the clothes is the only way to make that case, and it is the reason this is a fashion exhibition that people who do not go to fashion exhibitions tend to come out of talking.",
      "## 15 November &mdash; Inside Aardman",
      "<em>Inside Aardman: Wallace &amp; Gromit and Friends</em> closes <strong>15 November 2026</strong> at <strong>Young V&amp;A</strong> in Bethnal Green. Tickets <strong>&pound;12.50</strong>.",
      "Worth knowing which building this is in: Young V&amp;A is a different site from South Kensington, and a family planning a single day out cannot do this one and Schiaparelli without crossing London in between.",
      "## 10 January &mdash; two shows, two buildings",
      "<em>The Music is Black: A British Story</em> closes <strong>10 January 2027</strong> at <strong>V&amp;A East</strong>, <strong>&pound;22.50</strong>. <em>Rising Voices: Contemporary Art from Asia, Australia and the Pacific</em> closes the same day at South Kensington, <strong>&pound;17</strong>.",
      "Sharing a closing date across two sites is a scheduling detail with a practical consequence: the first weekend of January will be the busy one at both, and the quiet weeks are the ones before Christmas.",
      "## 7 November &mdash; the one that opens",
      "<em>Constantinople to Istanbul: One City, Two Empires</em> opens <strong>Saturday 7 November 2026</strong> at South Kensington &mdash; the day before Schiaparelli closes.",
      "Which makes that weekend the only one where both are on. If there is a single date in this piece to write down, it is <strong>Saturday 7 or Sunday 8 November</strong>.",
      "## What is not here",
      "Opening dates for the other shows are not listed above because the museum has not published them all, and a guide that guesses at one is worse than a guide that leaves it out. What is printed here is what the V&amp;A itself has stated, checked on the day this was written.",
    ],
    expertise:
      "Weekday tickets to Schiaparelli are &pound;2 cheaper, which is not the reason to go on a weekday. The reason is that a 400-object show with 100 ensembles is a slow one &mdash; the garments reward standing still in front of them &mdash; and a Saturday in the final fortnight of a closing exhibition is the one condition under which that is impossible.",
  },
  {
    slug: "notting-hill-carnival-turns-60",
    featured: 2,
    site: "ldn",
    image: "/covers/notting-hill-carnival-turns-60.jpg",
    imageAlt: "A blank plaque on a brick wall with feathers and ribbons fanning out behind it",
    imageKind: "generated",
    imageWidth: 1536,
    imageHeight: 864,
    title: "Notting Hill Carnival turns sixty",
    summary:
      "A plaque at Westbourne Park names seventy people who built Carnival — unveiled for its sixtieth year, and for seventy years since London Transport went recruiting in the Caribbean.",
    date: "2026-08-28",
    category: "Carnival",
    source: {
      name: "BBC London",
      url: "https://www.bbc.co.uk/news/articles/cx2zndw0wdwo",
      verifiedOn: "2026-08-30",
    },
    body: [
      "Carnival&rsquo;s sixtieth year was marked with something more durable than a parade: a plaque at Westbourne Park Underground station naming <strong>70 people</strong> who helped create it.",
      "The station is not a neutral choice. Westbourne Park sits at the northern end of the parade route and is one of the main stations people use to get there &mdash; the plaque is at the top of the road, where the thing itself starts.",
      "## Two anniversaries, deliberately joined",
      "The unveiling marks Carnival&rsquo;s sixtieth, and also <strong>70 years since London Transport began recruiting staff in the Caribbean</strong>. In <strong>1956</strong>, unable to find enough people to run the capital&rsquo;s expanding bus and Underground network, London Transport sent recruitment officers across the Atlantic. Those who came were employed right across the network, and many stayed for the rest of their working lives.",
      "> Carnival is a celebration of the Caribbean communities that have shaped our city, and the men and women recruited in 1956 helped create the transport system the capital relies on today.\n— Andy Lord, London&rsquo;s transport commissioner",
      "## Whose names are on it",
      "Costume designers, mas players, steel pan players and sound system operators &mdash; the four crafts Carnival is actually made of, rather than the officials who administer it.",
      "The first two names listed are <strong>Claudia Jones</strong> and <strong>Rhaune Laslett</strong>. Jones, born in Trinidad and the founder of the West Indian Gazette, organised an indoor Caribbean carnival in London from <strong>1959</strong> until her death in <strong>1964</strong>. Laslett was instrumental in setting up the Notting Hill street festival that grew into the Carnival.",
      "That is two different events, five years apart, one indoors and one in the street &mdash; and putting both names first is an argument about where Carnival came from, made in brass.",
      "## Who put it there",
      "The plaque was organised by the <strong>Nubian Jak Community Trust</strong>. Its chief executive, Dr Jak Beula, said installing it at Westbourne Park fulfilled a long-held ambition and would give people a way to learn about Carnival&rsquo;s origins in Britain.",
      "TfL, whose own history the plaque is half about, also ran a decorated bus in the Sunday parade and showed an exhibition of artwork by its staff at Paddington.",
      "## The number that explains the station choice",
      "More than <strong>two million journeys</strong> are made on the transport network for Carnival each year, according to the TfL colleague network group that works on it.",
      "Which is why the standing advice is to travel to <strong>Paddington and walk</strong>: the stations nearer the route cannot absorb that, and Westbourne Park itself &mdash; the one with the plaque on it &mdash; is among the first to come under pressure.",
    ],
    expertise:
      "The plaque outlasts the weekend, and it is easier to read in October than in August. Westbourne Park is a ten-minute walk from Portobello Road, so it fits onto an ordinary Saturday in the area rather than requiring a trip of its own &mdash; which is more or less the point of putting it on a station rather than in a museum.",
  },
  {
    slug: "partial-lunar-eclipse-over-london",
    site: "ldn",
    image: "/covers/partial-lunar-eclipse-over-london.jpg",
    imageAlt: "A dark disc hanging over a row of rooftops at night",
    imageKind: "generated",
    imageWidth: 1536,
    imageHeight: 864,
    title: "A partial lunar eclipse, visible from London",
    summary:
      "London's second eclipse in a fortnight: 93% of the Moon in shadow at 5.12am on Friday 28 August, no glasses needed, and Parliament Hill the one obvious place to stand.",
    date: "2026-08-28",
    category: "Sky",
    source: {
      name: "Evening Standard",
      url: "https://www.standard.co.uk/news/london/partial-lunar-eclipse-2026-london-uk-viewing-time-blood-moon-b1294744.html",
      verifiedOn: "2026-08-30",
    },
    body: [
      "Two eclipses in sixteen days is not a thing London gets often, and the second was the easier one to watch: nothing to buy, nothing to protect your eyes with, and no crowd &mdash; because it happened while the city was asleep.",
      "## The timings",
      "The partial lunar eclipse ran in the early hours of <strong>Friday 28 August</strong>. It began at about <strong>3.33am</strong> London time and reached maximum at about <strong>5.12am</strong>, with roughly <strong>93% of the Moon&rsquo;s visible diameter</strong> covered by Earth&rsquo;s shadow, according to the Royal Museums Greenwich.",
      "Then it ran out of sky. Moonset was around <strong>6.15am</strong> and the eclipse formally ended at <strong>6.51am</strong> &mdash; by which point the Moon was already below the London horizon. The last forty minutes of it happened to somebody else.",
      "## Why it goes red",
      "At maximum the Moon takes on a deep coppery red, the thing people call a blood moon. The cause is the Earth&rsquo;s atmosphere: sunlight passing through it is scattered and bent, and the red end of that light is what carries on to the lunar surface. What you are looking at, strictly, is every sunrise and sunset on Earth projected at once onto a rock a quarter of a million miles away.",
      "Because the Moon sat low over the south-western horizon throughout, it also read as unusually large against the skyline &mdash; the moon illusion, which is in the eye rather than the sky, but is no less convincing for it.",
      "## No glasses this time",
      "This is the part people got wrong after August. The <strong>partial solar eclipse on 12 August</strong> filled the parks and emptied the shops of protective glasses &mdash; more than <strong>90% of the Sun</strong> was covered, the most in UK skies since the total eclipse of <strong>1999</strong>.",
      "A lunar eclipse is the opposite case. Looking straight at it does no harm at all. Binoculars or a telescope are worth having, not for safety but for the surface detail.",
      "## Where to stand, when it happens again",
      "Astronomers give one instruction: get high, with a clear view to the <strong>south-west</strong>. The difficulty in London is that most of the major parks that filled up for the solar eclipse are shut in the small hours. <strong>Hampstead Heath is open 24 hours</strong>, which makes <strong>Parliament Hill</strong> the obvious answer &mdash; height, an open southern aspect, and legally accessible at 5am.",
      "The forecast on the day promised cloud and light rain, which is the ordinary English ending to a story like this one.",
    ],
    expertise:
      "The 5.12am maximum was the whole event. An eclipse listed as running from 3.33 to 6.51 sounds like a window; in practice the interesting phase is the twenty minutes either side of maximum, and the last stretch of this one was below the horizon anyway. Setting an alarm for the start time was the reliable way to stand outside for ninety minutes watching almost nothing.",
  },
  {
    slug: "ten-exhibitions-on-in-london",
    featured: 1,
    site: "ldn",
    image: "/covers/ten-exhibitions-on-in-london.jpg",
    imageAlt: "Ten empty picture frames of different sizes hung across a gallery wall",
    imageKind: "generated",
    imageWidth: 1536,
    imageHeight: 864,
    title: "What is actually hanging in London right now",
    summary:
      "Ten shows are on the critics' list. Six of them close before January, one has sold more advance tickets than anything in Tate's 128-year history, and two of the best are free.",
    date: "2026-08-27",
    category: "Art",
    source: {
      name: "Time Out London",
      url: "https://www.timeout.com/london/art/top-10-art-exhibitions-in-london",
      verifiedOn: "2026-08-30",
    },
    body: [
      "There is no shortage of exhibitions in London. There is a shortage of weekends &mdash; which is why the only useful way to read a top-ten list is by closing date, not by star rating.",
      "Here is the current critics&rsquo; ten, sorted by how long you have left.",
      "## Closing first",
      "<strong>NIGO: From Japan with Love</strong> at the Design Museum, Kensington, closes <strong>4 October</strong>. The first London retrospective for the man behind Bape and Human Made and Kenzo&rsquo;s creative director since 2021: <strong>700 objects</strong>, <strong>600 of them from his own archive</strong> &mdash; records, toys, magazines, music videos and a great deal of clothing, from the 1980s on. It is also the clearest explanation anyone has staged of where &laquo;scarcity by design&raquo; came from.",
      "<strong>Anish Kapoor</strong> at the Hayward, South Bank, closes <strong>18 October</strong>. His second solo show there &mdash; the last was in 1998 &mdash; with the greatest hits and some monumental new work. The voids are the reason to go: sculptures painted in a black that absorbs <strong>99.965% of visible light</strong>, which is the record for the darkest manmade substance, and which your eyes simply refuse to read as a surface.",
      "<strong>Musquiqui Chihying: A Life of Navigation</strong>, also South Bank, closes <strong>18 October</strong>, and it is <strong>free</strong>. Four works by the Taiwanese artist and filmmaker on how people navigate high-stress city life. Small, funny, and the best value on this list by a distance.",
      "<strong>Schiaparelli: Fashion Becomes Art</strong> at the V&amp;A closes <strong>8 November</strong>. The first British exhibition on Elsa Schiaparelli, with Dal&iacute;, Man Ray and Leonor Fini hung alongside the clothes, dresses worn by Ariana Grande and Dua Lipa, and the lobster telephone.",
      "## The winter shows",
      "<strong>Frida: The Making of an Icon</strong> at Tate Modern runs to <strong>3 January 2027</strong>, and it has already sold more advance tickets than any exhibition in Tate&rsquo;s <strong>128-year history</strong>. The strongest part is the beginning: <strong>23 paintings</strong> and <strong>11 works on paper</strong> by Kahlo, with the photographs she sat for, her jewellery and Indigenous Mexican clothing from her wardrobe. The later rooms are about the phenomenon rather than the painter, which is a fair subject but a different one.",
      "<strong>Ana Mendieta</strong> at Tate Modern runs to <strong>17 January 2027</strong> &mdash; her first major UK gallery exhibition, spanning performance, sculpture, land art, photography and video, with many pieces never shown in this country. The <em>Siluetas</em> series is what people come out talking about.",
      "## The one that closes this week",
      "<strong>Tracey Emin: A Second Life</strong> at Tate Modern is the only five-star show on the list and it closes <strong>31 August</strong>. If you are reading this on the day, that is the decision made for you.",
      "## What we would put first",
      "If there is one afternoon: <strong>Chihying at the Hayward</strong>, because it is free, then <strong>Kapoor</strong> upstairs in the same building. Two shows, one address, one ticket between them.",
      "If there is one ticket: <strong>Schiaparelli</strong>. Frida will be the busier show and the better-known name, but the V&amp;A has assembled something that does not exist anywhere else and dismantles it in November.",
    ],
    expertise:
      "Star ratings and closing dates pull in opposite directions. The five-star show on this list has days left; two of the three-star ones run into next year. A list read top-down sends you to the thing that is about to vanish and leaves the rest unseen &mdash; which is exactly backwards, because the ones with months left are the ones you can plan around a quiet Tuesday.",
  },
];
