import type { NewsItem } from "../types.ts";

export const items: NewsItem[] = [
  {
    slug: "free-zone-distributors-need-a-second-auditors-report",
    site: "llc",
    image: "/covers/free-zone-distributors-need-a-second-auditors-report.jpg",
    imageAlt: "Two pale jade paper documents on a deep teal-green ground, the second one smaller and set slightly behind the first, with a small brass clip joining them",
    imageKind: "generated",
    imageWidth: 1536,
    imageHeight: 864,
    title: "Free zone distributors will need a second auditor’s report to keep the 0%",
    cardTitle: "A second report for the 0% rate",
    titleSeo: "Free zone distributors: AUP report",
    summary:
      "FTA Decision No. 6 of 2026 adds an ISRS 4400 agreed-upon procedures report on top of audited accounts for free zone companies distributing goods from a Designated Zone. Nothing is filed until 2027, but the transactions being tested are happening now.",
    date: "2026-09-06",
    category: "Tax",
    source: {
      name: "GFLO Consultancy",
      url: "https://gflolaw.com/en/new-fta-reporting-requirements/",
      verifiedOn: "2026-09-06",
    },
    body: [
      "The expensive part of a tax rate is rarely the rate. It is the evidence you have to be able to produce two years later to show you were entitled to it.",
      "## What was decided",
      "<strong>Decision No. 6 of 2026</strong> was issued by the <strong>Federal Tax Authority</strong> on <strong>2 June 2026</strong> and published on <strong>14 July 2026</strong>. It applies to any Qualifying Free Zone Person carrying out the qualifying activity of <strong>distribution of goods or materials in or from a Designated Zone</strong>, as defined in Ministerial Decision No. 229 of 2025, and it bites on <strong>tax periods commencing on or after 1 January 2026</strong>.",
      "It changes none of the substantive conditions for the 0% rate. It adds an evidentiary layer on top of them: an <strong>agreed-upon procedures (AUP) report</strong> under <strong>ISRS 4400</strong>, prepared by an independent auditor licensed in the UAE, alongside the audited financial statements that were already required.",
      "## What an AUP report is not",
      "An AUP engagement produces <strong>no opinion</strong>. The auditor performs pre-agreed procedures and reports factual findings. Two things have to be shown: that customers <strong>resell the goods, or process and alter them for resale</strong>, and that anything imported <strong>enters the UAE through a Designated Zone</strong>.",
      "## What the auditor will actually look at",
      "Article 3 lists the procedures — inspection of <strong>customer trade licences</strong> to confirm the licensed activity is consistent with reselling; <strong>signed, dated reseller declarations</strong> from customers for the relevant tax period; <strong>sales agreements, invoices and purchase orders</strong> read for terms indicating onward sale, such as bulk quantities or resale pricing; <strong>customs declarations, import permits and bills of lading</strong>; confirmation with the free zone authority that the area used is formally a Designated Zone; and internal <strong>inventory, warehousing and logistics records</strong>.",
      "Sampling is not left to judgement. The Decision prescribes a statistical formula with a <strong>10% margin of error</strong>, and the sample details go into an appendix.",
      "## The date that matters",
      "For a calendar-year taxpayer the first report covers <strong>1 January to 31 December 2026</strong> and is due <strong>30 days after the corporate tax return deadline</strong> — in practice <strong>30 October 2027</strong>. There is nothing to file today. The transactions being tested are the ones going through the warehouse this month.",
      "## If it is missing",
      "The conditions for the qualifying distribution activity are <strong>not considered to be met</strong>. That puts the 0% rate on that income, and the QFZP status attached to it, at risk.",
    ],
    expertise:
      "Read this as a documentation project, not an audit fee. The procedures are all retrospective inspections of paperwork that either exists at the moment of the transaction or does not exist at all: a customer’s signed reseller declaration for the 2026 period is easy to collect in 2026 and awkward to collect in late 2027, when the customer may have changed hands, changed activity or stopped buying. The same is true of bills of lading and warehousing logs held by third-party logistics providers on retention schedules of their own. The sensible response is to add the declaration to the customer onboarding pack now and to agree a records-retention clause with the 3PL, so that the auditor in 2027 is inspecting a file rather than reconstructing one. The second-order point is about who this catches. A group whose free zone entity sells to end users rather than resellers has a substantive problem that no report will fix; a group that genuinely sells to resellers has an administrative one. The Decision is worth using as a prompt to work out, honestly, which of those describes the business.",
  },

  {
    slug: "the-global-minimum-tax-grows-a-side-door",
    site: "llc",
    image: "/covers/the-global-minimum-tax-grows-a-side-door.jpg",
    imageAlt: "A tall pale jade paper wall on a deep teal-green ground with a narrow gap cut through it near one edge, a small brass marker beside the gap",
    imageKind: "generated",
    imageWidth: 1536,
    imageHeight: 864,
    title: "The 15% global minimum tax now has a side door, and it opened this January",
    cardTitle: "A side door in the global minimum tax",
    titleSeo: "Pillar Two safe harbours from 2026",
    summary:
      "The OECD’s Side-by-Side package adds four safe harbours and extends a fifth. The largest exempts groups headquartered in qualified jurisdictions from the income inclusion and undertaxed profits rules for financial years beginning 1 January 2026.",
    date: "2026-09-06",
    category: "Tax",
    source: {
      name: "EY Tax News Update",
      url: "https://taxnews.ey.com/news/2026-0226-oecd-releases-side-by-side-package-on-pillar-two-global-minimum-tax-detailed-review",
      verifiedOn: "2026-09-06",
    },
    body: [
      "A minimum tax works by being unavoidable. On <strong>5 January 2026</strong> the members of the Inclusive Framework agreed a package that makes parts of it avoidable on purpose.",
      "## What the package contains",
      "Five measures. The <strong>Side-by-Side Safe Harbour</strong> exempts groups whose ultimate parent sits in a <strong>qualified jurisdiction</strong> from the <strong>income inclusion rule</strong> and the <strong>undertaxed profits rule</strong>. The <strong>UPE Safe Harbour</strong> reduces UTPR top-up tax to zero for constituent entities in the parent’s own jurisdiction. A <strong>Simplified ETR Safe Harbour</strong> removes the detailed computation where a jurisdiction’s rate already reaches 15%. A <strong>Substance-Based Tax Incentive Safe Harbour</strong> lets certain qualified incentives count towards covered taxes. And the <strong>Transitional CbCR Safe Harbour</strong> is extended by a year.",
      "## Who walks through the door",
      "The <strong>United States</strong> currently qualifies as having a Qualified Side-by-Side Regime. A US-headquartered group electing the safe harbour avoids IIR and UTPR liability — but remains subject to <strong>qualified domestic minimum top-up taxes</strong> in the countries where it operates. The domestic layer is the part that did not move.",
      "## The dates",
      "Financial years <strong>2024 and 2025 are unaffected</strong>. The Side-by-Side and UPE safe harbours apply to financial years beginning <strong>on or after 1 January 2026</strong>, and so does the substance-based incentive measure. The Simplified ETR Safe Harbour arrives for years beginning after <strong>31 December 2026</strong>, though jurisdictions may allow it earlier. The extended transitional safe harbour now reaches financial years ending before <strong>30 June 2029</strong>.",
      "## What is not finished",
      "Each jurisdiction has to write the safe harbours into its own law, on its own timetable. <strong>Anti-arbitrage rules</strong> are still under development, further simplifications for investment entities and minority-owned entities were slated for the first half of 2026, and the OECD keeps a <strong>Central Record of Legislation</strong> naming which regimes count as qualified. A full stocktake of the minimum tax is due to conclude by <strong>2029</strong>.",
    ],
    expertise:
      "For a UAE holding structure the practical reading is narrow and specific. The safe harbours change the mechanics of the top-down rules, not the bottom-up one: a domestic minimum top-up tax is still collected where the profit arises, which is why the UAE’s own regime is unaffected by whether a parent elects the side door somewhere else. What does change is the question a group needs to answer about itself — the relevant fact is now the jurisdiction of the <em>ultimate parent</em> and whether it appears in the Central Record, not the group’s own effective rate. That is a different diligence question from the one asked in 2024, and it moves with a list the OECD maintains rather than with anything in the group’s accounts. The instability to watch is the word ‘qualified’. A regime is qualified because the Inclusive Framework says so, and what is granted by agreement can be withdrawn by agreement; a structure whose economics depend on one jurisdiction keeping that label is exposed to a political process, not a tax computation. Plan on the domestic layer, which is durable, and treat the side door as relief rather than as architecture.",
  },

  {
    slug: "small-business-relief-still-files-a-return",
    site: "llc",
    image: "/covers/small-business-relief-still-files-a-return.jpg",
    imageAlt: "A small cut-paper form sheet on a teal ground beside a much larger one, both with the same ruled lines",
    imageKind: "generated",
    imageWidth: 1536,
    imageHeight: 864,
    title: "Relief from the tax is not relief from the return",
    cardTitle: "Small Business Relief still files",
    titleSeo: "Relief still means filing a return",
    summary:
      "The FTA has reminded companies under the Dh3 million threshold that electing Small Business Relief means a simplified return, not no return. The deadline is 30 September.",
    date: "2026-09-03",
    category: "Tax",
    source: {
      name: "Federal Tax Authority",
      url: "https://www.zawya.com/en/press-release/government-news/fta-confirms-taxable-persons-eligible-for-the-small-business-relief-must-submit-simplified-corporate-tax-returns-418896",
      verifiedOn: "2026-09-03",
    },
    body: [
      "The most expensive misreading of UAE corporate tax is the one that sounds like good news. On 3 August the <strong>Federal Tax Authority</strong> issued a reminder aimed squarely at it.",
      "## The reminder",
      "Businesses eligible for <strong>Small Business Relief</strong> must still submit a corporate tax return. The relief reduces what the return contains; it does not remove the obligation to file one.",
      "## What the relief actually does",
      "Small Business Relief treats an eligible resident person as having earned <strong>no taxable income</strong> for corporate tax purposes, provided revenue does not exceed <strong>Dh3 million</strong> in the relevant tax period <em>and in all previous tax periods</em>. That second clause is the one that catches people: a single earlier year above the threshold ends eligibility.",
      "The relief is not automatic. It is <strong>elected through the corporate tax return itself</strong>, which is the mechanical reason a return has to exist at all.",
      "## The date",
      "A business whose financial year ended <strong>31 December 2025</strong> must file and pay by <strong>30 September 2026</strong>. The general rule is nine months from the end of the tax period.",
      "## The obligations that survive the relief",
      "The FTA lists them plainly: register for corporate tax, submit the simplified return, and maintain records sufficient to support what the return says. <strong>H.E. Abdulaziz Mohammed Al Mulla</strong>, the Authority's Director General, framed the announcement as part of a service-improvement programme rather than a change of rule.",
    ],
    expertise:
      "The phrase to read twice is \"and all previous tax periods\". Eligibility is not assessed year by year against a Dh3 million line; one prior period over it disqualifies the company permanently for this relief, so a business that had a strong 2024 and a quiet 2025 does not qualify on the strength of 2025. The other trap is the word simplified. A simplified return is still a return with a filing date attached, and the late-filing penalty does not care that the tax due was nil — which is exactly the combination that produces a fine on a company that owed nothing.",
  },

  {
    slug: "e-invoicing-provider-deadline-moves-to-october",
    site: "llc",
    image: "/covers/e-invoicing-provider-deadline-moves-to-october.jpg",
    imageAlt: "A cut-paper invoice sheet on a teal ground with a jade arrow bending around it to a second sheet",
    imageKind: "generated",
    imageWidth: 1536,
    imageHeight: 864,
    title: "The e-invoicing provider deadline moved, the go-live date did not",
    cardTitle: "E-invoicing deadline moves to October",
    titleSeo: "ASP deadline moves to 30 October",
    summary:
      "Companies above Dh50 million now have until 30 October to appoint an accredited service provider. Phase 1 still goes live on 1 January 2027.",
    date: "2026-09-03",
    category: "Tax",
    source: {
      name: "Deloitte Middle East",
      url: "https://www.deloitte.com/middle-east/en/services/tax/perspectives/uae-e-invoicing-asp-appointment-deadline-extended-but-go-live-remains-01012027.html",
      verifiedOn: "2026-09-03",
    },
    body: [
      "An extension that does not move the finish line is not an extension of the project. It is a shorter runway to the same aircraft.",
      "## What moved",
      "The <strong>Ministry of Finance</strong> has pushed the deadline for appointing an <strong>Accredited Service Provider</strong> from <strong>31 July 2026</strong> to <strong>30 October 2026</strong> — roughly three months.",
      "## What did not",
      "<strong>Phase 1 go-live remains 1 January 2027.</strong> The extension applies to the appointment step only.",
      "## Who this is about",
      "Phase 1 covers businesses with <strong>revenue of Dh50 million or more</strong>. The mandate itself applies to <strong>business-to-business and business-to-government</strong> transactions.",
      "## What an ASP is for",
      "An Accredited Service Provider is licensed by the Ministry of Finance and the FTA, and handles <strong>transmission, validation and reporting to the Federal Tax Authority</strong>, alongside readiness assessment and testing. An in-scope business cannot exchange compliant e-invoices without one.",
      "A voluntary phase has been open since July 2026, which is the window in which testing is meant to happen.",
    ],
    expertise:
      "Read the extension as a warning rather than a reprieve. Appointing a provider is the short part; mapping master data, tax codes and document types onto the required schema is the long part, and it cannot start in earnest until the provider is chosen. A company that uses the full extension to 30 October leaves itself nine weeks to integrate and test before 1 January. The other thing worth checking early is which of your document types are actually in scope — B2B and B2G are named, and a business whose revenue is largely B2C may find the mandate touches a much smaller share of its invoicing than the headline revenue threshold suggests.",
  },

  {
    slug: "apple-published-its-succession-134-days-early",
    site: "llc",
    image: "/covers/apple-published-its-succession-134-days-early.jpg",
    imageAlt: "Two paper discs set far apart on a long pale band running across the frame",
    imageKind: "generated",
    imageWidth: 1536,
    imageHeight: 864,
    title: "Apple published its succession 134 days before it happened",
    cardTitle: "134 days of notice",
    titleSeo: "The 134-day succession notice",
    summary:
      "Announced 20 April, effective 1 September. The gap is the part a company of any size can copy, and almost none do.",
    date: "2026-09-01",
    category: "Business",
    source: {
      name: "Apple Newsroom",
      url: "https://www.apple.com/newsroom/2026/04/tim-cook-to-become-apple-executive-chairman-john-ternus-to-become-apple-ceo/",
      verifiedOn: "2026-09-02",
    },
    body: [
      "On <strong>20 April 2026</strong> Apple said that <strong>Tim Cook</strong> would become executive chairman and <strong>John Ternus</strong> would become chief executive. The change took effect on <strong>1 September 2026</strong>. Between those two dates there were <strong>134 days</strong> in which everyone who deals with Apple knew exactly what was coming and exactly when.",
      "## Why that gap is unusual",
      "The default corporate pattern is to announce a leadership change and enact it in the same press release, often before markets open. It is defensible — it shortens the window in which a departing executive is a lame duck — and it has one large cost: every counterparty learns simultaneously that a decision affecting them was taken entirely without them.",
      "A dated handover inverts that. Suppliers, regulators, large customers and staff all get the same information at the same time, with months to act on it. Nobody has to guess, and nobody gets to claim they were surprised.",
      "## What was actually specified",
      "Not just the names. Apple set out the shape of all three roles: Ternus, previously <strong>senior vice president of Hardware Engineering</strong> and at the company since <strong>2001</strong>, takes the chief executive's job; Cook takes <strong>executive chairman</strong> with a stated remit that includes engaging with policymakers around the world; and <strong>Arthur Levinson</strong>, non-executive chairman for fifteen years, becomes <strong>lead independent director</strong>.",
      "Three defined positions, one effective date. That is a governance document, not an announcement.",
      "## The transferable part",
      "None of this depends on being Apple. A company with twelve people has the same problem in miniature: the founder is the single point of failure, everyone knows it, and nobody will say so until the week it becomes urgent.",
      "The mechanism that Apple used costs nothing to imitate — name the successor, name the date, name what the outgoing person will still do — and it converts the most disruptive event in a company's life into a scheduled one. The reason it is rare is not expense. It is that it requires the decision to be genuinely made before it is announced.",
      "## For a company being set up now",
      "The version of this that matters at incorporation is duller and even easier: write down who signs if the person who normally signs is unreachable, and put a date on when that arrangement is reviewed. Most structures are drafted as though the people in them are permanent. Apple, at <strong>$416 billion</strong> of annual revenue, did not assume that. A new company has less excuse.",
    ],
    expertise:
      "Read the sequence rather than the headline: the board approved the plan, the plan was published with an effective date, and the outgoing chief executive kept a <strong>named and bounded</strong> role rather than a vague advisory one. Vague continuing roles are where succession goes wrong — an unbounded «founder emeritus» leaves it unclear who decides, which is the exact ambiguity the exercise was meant to remove.",
  },
  {
    slug: "difc-passes-10000-active-companies",
    site: "llc",
    image: "/covers/difc-passes-10000-active-companies.jpg",
    imageAlt: "Six paper columns rising in a staircase, a thin ruled line crossing above them",
    imageKind: "generated",
    imageWidth: 1536,
    imageHeight: 864,
    title: "DIFC passes 10,000 companies for the first time",
    titleSeo: "DIFC passes 10,000 companies",
    summary:
      "2,318 new firms joined in the first half of 2026, taking the active register to 10,018 — 30% growth in twelve months. Regulated financial firms reached 1,134.",
    date: "2026-07-28",
    category: "Free zones",
    source: {
      name: "Government of Dubai Media Office",
      url: "https://mediaoffice.ae/en/news/2026/july/28-07/difc-records-industry-leading-achievements-in-h1-2026",
      verifiedOn: "2026-09-01",
    },
    body: [
      "Round numbers are arbitrary and people notice them anyway. The Dubai International Financial Centre ended the first half of 2026 with <strong>10,018 active registered companies</strong> — the first time the centre has held more than ten thousand.",
      "## The half-year figures",
      "<strong>2,318</strong> new active registered companies joined in the six months to June, and the register grew <strong>30%</strong> over the preceding twelve months.",
      "Two sub-totals matter more than the headline, because they say what kind of centre this is becoming rather than how large it is.",
      "<strong>Regulated financial services firms rose 16% to 1,134.</strong> These are the entities under the DFSA’s supervision — banks, asset managers, brokers, insurers. Everything else on the register is a company that chose the jurisdiction; these are companies that also submitted to its regulator.",
      "<strong>AI, FinTech and innovation firms reached 1,933, up 39% year on year.</strong> That is now a larger population than the regulated financial firms, inside a financial centre.",
      "## Family businesses, quietly",
      "Family-business-related entities reached <strong>1,408</strong>, up <strong>36%</strong>. This is the least visible of the four numbers and arguably the most consequential: a family holding structure is a decades-long commitment to a legal system, not a lease.",
      "## Who arrived",
      "Firms establishing regional offices in DIFC since the first half of 2025 include <strong>Citadel</strong>, <strong>Bank of Canada</strong>, <strong>JP Morgan International Advisors</strong>, <strong>ICICI Prudential Asset Management</strong>, <strong>Allianz Trade Middle East</strong> and <strong>Sun Life</strong>.",
      "## What this changes for a company choosing a jurisdiction",
      "A register of ten thousand is a different product from a register of three thousand. It means depth of local counsel, auditors who have seen your structure before, and a secondary market in office space — and it also means DIFC is no longer the quiet option. Costs in a jurisdiction follow demand for it.",
    ],
    expertise:
      "DIFC and the mainland are not competing offers for most companies — they answer different questions. DIFC is worth its premium when the business needs common law, a DFSA licence, or a family or fund structure that a mainland licence cannot hold. For a trading or services company selling into the UAE, the mainland route remains simpler and cheaper, and 10,018 registrations does not change that arithmetic.",
  },
  {
    slug: "free-zone-mainland-access-resolution-11-2025",
    site: "llc",
    // Layout appends " — Company Formation in Dubai", so the headline has
    // 31 characters to work with and still has to stand alone in dst.llc's
    // aggregated feed.
    title: "Free zones get mainland access",
    summary:
      "Dubai's Executive Council Resolution No. (11) of 2025 lets free zone companies trade in mainland Dubai on a DET branch licence or a temporary activity permit, instead of setting up a separate mainland company.",
    date: "2025-03-03",
    category: "Regulation",
    image: "/news/free-zone-mainland-routes.svg",
    imageAlt:
      "Cut-paper illustration: a balance beam with two shallow trays, one holding a stack of discs.",
    imageKind: "diagram",
    imageCredit: "DST, from the resolution text",
    imageWidth: 1200,
    imageHeight: 600,
    source: {
      name: "Dubai Legislation Portal",
      url: "https://dlp.dubai.gov.ae/Legislation%20Reference/2025/Executive%20Council%20Resolution%20No.%20(11)%20of%202025%20Regulating%20the%20Conduct%20of%20Free%20Zone%20Establishments%E2%80%99%20Activities.html",
      verifiedOn: "2026-08-25",
    },
    // Emphasis is on the facts a reader would come back to check — the
    // instrument, the fees, the standing obligation — not scattered for
    // effect, which is the state in which it stops meaning anything.
    body: [
      "<strong>Executive Council Resolution No. (11) of 2025</strong>, issued on March 3, 2025, allows a free zone establishment to conduct its activities outside the free zone but within Dubai — provided it holds the right authorisation from the Department of Economy and Tourism.",
      "The resolution sets out three routes: a branch licence for a branch established in the mainland, a branch licence held by the free zone entity for mainland activities, and an activity permit covering specific activities for up to six months. The published fees are <strong>AED 10,000 per year</strong> for the free-zone-based branch licence and <strong>AED 5,000</strong> for the activity permit.",
      "Companies taking either route must <strong>keep financial records for their mainland activities separate</strong> from the records covering activity inside the free zone. Existing establishments were given one year from the effective date to comply, with an extension possible.",
    ],
    expertise:
      "Before this, the free zone question was close to binary: take the free zone package and accept that serving mainland clients directly is off the table, or incorporate on the mainland from the start. A branch licence turns that into a sequencing decision rather than a permanent fork — you can start in a free zone and add mainland reach later. The separate-books requirement is the part worth planning for early: it is an ongoing accounting obligation, not a one-off filing.",
    // The news is the trigger; the depth lives on the topic pages, which
    // are the ones that should rank for the underlying question.
    related: [
      {
        href: "/zones/",
        image: "/covers/zones.jpg",
        imageAlt: "Cut-paper illustration: a grid of walled enclosures seen from above, one corner left open.",
        title: "Dubai free zone comparison",
        text: "Which free zone actually fits an activity — compared by fit rather than ranked into a top-10.",
        eyebrow: "Free zones",
      },
      {
        href: "/mainland/",
        image: "/covers/mainland.jpg",
        imageAlt: "Cut-paper illustration: a flat shoreline of layered strips meeting a cluster of towers.",
        title: "Mainland company setup",
        text: "When a mainland licence is genuinely required, and how it differs from holding a branch.",
        eyebrow: "Mainland",
      },
      {
        href: "/taxation/",
        image: "/covers/taxation.jpg",
        imageAlt: "Cut-paper illustration: a balance beam with two shallow trays, one holding a stack of discs.",
        title: "Corporate tax and filing",
        text: "What the tax and filing obligations look like once activity runs on both sides.",
        eyebrow: "Tax",
      },
    ],
  },
];
