import type { NewsItem } from "../types.ts";

export const items: NewsItem[] = [
  {
    slug: "oxford-street-goes-traffic-free",
    site: "lnd",
    image: "/covers/oxford-street-goes-traffic-free.jpg",
    imageAlt: "A long empty cream band between two dark blue blocks, with small vehicles held at either end",
    imageKind: "generated",
    imageWidth: 1536,
    imageHeight: 864,
    title: "Oxford Street loses its traffic in the second half of October",
    cardTitle: "Oxford Street goes traffic-free",
    titleSeo: "Oxford Street pedestrianisation: what changes",
    summary:
      "Nine hundred metres from Orchard Street to Great Portland Street, including Oxford Circus, close to buses, taxis, cycles and everything else on wheels.",
    date: "2026-09-02",
    category: "Transport",
    source: {
      name: "Mayor of London",
      url: "https://www.london.gov.uk/",
      verifiedOn: "2026-09-02",
    },
    body: [
      "One is obliged to note that London has been discussing this since the 1970s. It happens next month.",
      "## What closes, and when",
      "The traffic-free stretch runs from <strong>Orchard Street</strong> to <strong>Great Portland Street</strong> &mdash; roughly <strong>0.9 km</strong>, and it includes <strong>Oxford Circus</strong>. It goes traffic-free in the <strong>second half of October 2026</strong>.",
      "Closed to <strong>buses, taxis, private hire vehicles, cycles, e-scooters and pedicabs</strong>. Not a partial scheme, and not one with a cyclists' exemption.",
      "The <strong>Oxford Street Development Corporation</strong> took on planning powers for the area on <strong>10 August 2026</strong>. <strong>Four north&ndash;south crossing points</strong> are retained, and <strong>two new public squares</strong> are planned, though their locations have not yet been revealed.",
      "## The part that will cause the most correspondence",
      "Excluding cycles from a pedestrianisation scheme is, one suspects, going to prove rather more contentious than excluding cars. The reasoning is straightforward &mdash; a crowd walking at its own pace in all directions is not a surface that mixes well with anything travelling at fifteen miles an hour &mdash; but it is a genuine loss of an east&ndash;west route, and the alternatives are not obviously good.",
      "## What happens to the buses is the real question",
      "Oxford Street's bus corridor is not a convenience; for a great many people it is the only way across the West End that does not involve stairs. Those routes must go somewhere, and Wigmore Street and Great Marlborough Street are not generous.",
      "A transition scheme comes first, with permanent changes at the <strong>end of 2027</strong>. The interval is the point: it is a fourteen-month opportunity to discover what one has got wrong while it is still cheap to correct.",
    ],
    expertise:
      "Retaining four north&ndash;south crossings is the detail worth watching. Pedestrianised high streets fail most often not because they are unpleasant but because they sever the streets that cross them, stranding the blocks either side. Four crossings over nine hundred metres is a gap of well over two hundred metres between them, which is a long way to walk to get to the other side of a road one is standing beside.",
  },
  {
    slug: "open-house-festival-turns-35",
    site: "lnd",
    image: "/covers/open-house-festival-turns-35.jpg",
    imageAlt: "A dense field of small paper house shapes in blues and cream, one red house with an open doorway",
    imageKind: "generated",
    imageWidth: 1536,
    imageHeight: 864,
    title: "For nine days, buildings that are never open, open",
    cardTitle: "Open House: nine days, 33 boroughs",
    titleSeo: "Open House Festival 2026: 12–20 September",
    summary:
      "The 35th Open House runs 12–20 September across all 33 boroughs, free. Booking opened at midday on 19 August, but a great deal needs no booking at all.",
    date: "2026-09-02",
    category: "Architecture",
    source: {
      name: "Open City",
      url: "https://open-city.org.uk/",
      verifiedOn: "2026-09-02",
    },
    body: [
      "Thirty-five years ago somebody had the rather good idea of simply asking building owners whether the public might come in. A surprising number said yes, and have gone on saying yes.",
      "## The dates",
      "<strong>Open House Festival 2026</strong> runs <strong>12&ndash;20 September</strong>. It is the <strong>35th</strong> edition, it covers all <strong>33 boroughs</strong>, and it is <strong>free</strong>. Booking opened at <strong>midday on 19 August</strong>.",
      "## What one should do about the ballot having already happened",
      "The famous buildings went within the hour, as they do every year, and there is no particular use in being cross about it. The festival's actual value was never the six places everybody wanted.",
      "A very large proportion of the programme is <strong>walk-up</strong> &mdash; no booking, no ballot, simply a door that is open and somebody standing beside it who is pleased to be asked. These are the private houses, the small practices, the places of worship and the working buildings, and they are almost always the better afternoon.",
      "## Why all 33 boroughs is the line to read",
      "It would be very much easier to run this festival in four boroughs. Architecture tourism in London means the City, Westminster, Southwark and a small part of Hackney, and a programme confined to those would still be substantial.",
      "Insisting on all thirty-three changes what the festival is about. It stops being a tour of celebrated buildings and becomes an account of how the city is actually built &mdash; which, one might gently suggest, is a rather more interesting subject than another look at a well-photographed atrium.",
    ],
    expertise:
      "The practical approach is to abandon the idea of a list and pick a single borough for a whole day. Open House travel time is the thing that ruins itineraries: three bookings in three directions consumes the day in transit, whereas six walk-up buildings within a mile of one another is an unhurried afternoon and generally the one people remember.",
  },
  {
    slug: "bus-routes-67-and-149-consultation",
    site: "lnd",
    image: "/covers/bus-routes-67-and-149-consultation.jpg",
    imageAlt: "A long dark navy paper strip above a much shorter pale blue one on a white ground",
    imageKind: "generated",
    imageWidth: 1536,
    imageHeight: 864,
    title: "Two north London bus routes are being redrawn — and one goes",
    cardTitle: "Route 67 withdrawn, 149 rerouted",
    titleSeo: "TfL consultation on routes 67 and 149",
    summary:
      "TfL proposes withdrawing the 67 and rerouting the 149. Edmonton Green loses a direct link and peak waits go from seven minutes to eight. It closes 20 September.",
    date: "2026-09-02",
    category: "Transport",
    source: {
      name: "Transport for London",
      url: "https://haveyoursay.tfl.gov.uk/",
      verifiedOn: "2026-09-02",
    },
    body: [
      "Bus consultations attract almost no attention until the bus stops coming, at which point they attract a great deal.",
      "## The proposals",
      "<strong>Transport for London</strong> proposes to <strong>withdraw route 67</strong> and to <strong>reroute route 149</strong> to run <strong>Wood Green to London Bridge</strong>. Peak frequency on the 149 would move from a bus every <strong>seven minutes</strong> to one every <strong>eight</strong>. <strong>Edmonton Green</strong> loses its direct link.",
      "The consultation closes on <strong>Sunday 20 September 2026</strong>.",
      "## Seven minutes to eight does not sound like anything",
      "It is worth being precise about what that change actually is. A minute on the headway is roughly a <strong>12% reduction in buses per hour</strong> on the corridor at the busiest time of day. On a route that is already full at the front end, a 12% cut in capacity is not experienced as a slightly longer wait; it is experienced as the occasional bus one cannot board.",
      "## The withdrawal is the substantive item",
      "Rerouting moves a service. Withdrawal removes one, and the people most affected by a removed bus route are, reliably, the people least likely to respond to an online consultation about it &mdash; which is precisely why the closing date is worth repeating.",
      "Edmonton Green's loss of a direct link is the sort of change that reads as tidy on a network map and as a bus, a wait and a second bus on a Tuesday morning.",
      "## What a consultation response is actually for",
      "Not a vote. TfL is not counting objections; it is looking for journeys it has not modelled. A response that says which trip one makes, at what time, and what one would do instead is worth a great deal more than a response saying the proposal is a bad one.",
    ],
    expertise:
      "The useful thing to put in a consultation response is an interchange that the proposal creates and the timetable does not support &mdash; a connection where the two services are not coordinated, or where the wait exceeds the ride. Those are the objections that have historically produced amendments, because they identify a modelling error rather than a preference.",
  },
  {
    slug: "totally-thames-2026",
    site: "lnd",
    image: "/covers/totally-thames-2026.jpg",
    imageAlt: "A row of stubby red paper columns standing in a band of blue water below a large cream sheet",
    imageKind: "generated",
    imageWidth: 1536,
    imageHeight: 864,
    title: "A hundred events and a light work on a bridge that carries nothing",
    cardTitle: "Totally Thames: a month on the river",
    titleSeo: "Totally Thames 2026 runs all September",
    summary:
      "Through September the river hosts 100-plus events from Richmond to Barking and Dagenham, including Catherine Yass's work on Blackfriars' disused columns.",
    date: "2026-09-02",
    category: "Culture",
    source: {
      name: "Thames Festival Trust",
      url: "https://totallythames.org/",
      verifiedOn: "2026-09-02",
    },
    body: [
      "There is a set of red columns in the Thames beside Blackfriars that hold up nothing whatsoever. This month they become the best thing in the festival.",
      "## The month",
      "<strong>Totally Thames</strong> runs <strong>1&ndash;30 September 2026</strong>, with more than <strong>100 events</strong> between <strong>Richmond</strong> and <strong>Barking and Dagenham</strong>.",
      "<strong>Catherine Yass</strong>'s <strong>Turning the Tide</strong> occupies the disused columns of the old <strong>Blackfriars Railway Bridge</strong> from <strong>17 to 20 September</strong>.",
      "## Why those columns are the right site",
      "They are the remains of a bridge demolished in 1985 because it could not carry modern trains. The piers were left because removing them was more trouble than leaving them, and they have stood in the water ever since as an unusually honest piece of civic archaeology: infrastructure that failed, kept in place because demolition was inconvenient.",
      "Using them for four nights is a considerably better idea than any of the periodic proposals to build something on top.",
      "## Richmond to Barking is the ambitious part",
      "That is very nearly the whole tidal river, and it deliberately includes the stretches east of the Isle of Dogs that London's cultural programming habitually forgets. The Thames downstream of Tower Bridge is where the river actually worked for four centuries, and it is the part with the fewest festivals.",
      "One might observe that a river festival confined to the postcard reach would be a rather poor river festival.",
      "## The tide, which nobody schedules around",
      "The Thames moves about seven metres between low and high water at London Bridge. A foreshore event is governed by that and not by the programme, so anything happening on the shore has a real start time and an absolutely non-negotiable finish.",
    ],
    expertise:
      "For foreshore events, check the tide table rather than the listing. Access to the Thames foreshore is only safe for a window either side of low water, and the published event time assumes one has arrived at the start of it. The stairs at Gabriel's Wharf and Bermondsey are the usual descents, and both are cut off well before the advertised end of an afternoon.",
  },
  {
    slug: "fifteen-years-of-apple-in-numbers",
    site: "lnd",
    image: "/covers/fifteen-years-of-apple-in-numbers.jpg",
    imageAlt: "Torn paper bars rising steadily from left to right, one of them red, a long wedge tapering away beneath them",
    imageKind: "generated",
    imageWidth: 1536,
    imageHeight: 864,
    title: "Fifteen years, four trillion dollars, and a closing balance",
    cardTitle: "Fifteen years, in figures",
    titleSeo: "Tim Cook's fifteen years at Apple, in numbers",
    summary:
      "Tim Cook handed Apple over on 1 September. The figures he leaves behind are worth reading slowly, because one of them is rather harder than it looks.",
    date: "2026-09-01",
    category: "Tech",
    source: {
      name: "Apple Newsroom",
      url: "https://www.apple.com/newsroom/2026/04/tim-cook-to-become-apple-executive-chairman-john-ternus-to-become-apple-ceo/",
      verifiedOn: "2026-09-02",
    },
    body: [
      "There is a particular pleasure in a set of accounts that closes cleanly, and <strong>Tim Cook</strong>'s do. He ceased to be Apple's chief executive on <strong>1 September 2026</strong>, fifteen years after taking the post, and became executive chairman. <strong>John Ternus</strong> has the job now.",
      "## The ledger",
      "Market value at the start: roughly <strong>$350 billion</strong>. At the end: about <strong>$4 trillion</strong>. Revenue: <strong>$108 billion</strong> in FY2011, <strong>$416 billion</strong> in FY2025. Services, which barely counted as a line at the beginning, is a business of more than <strong>$100 billion</strong> by itself. Headcount up by over <strong>100,000</strong>. Active devices in use: more than <strong>2.5 billion</strong>, across <strong>200-plus countries and territories</strong>.",
      "One may quarrel with what any of it means. One cannot easily quarrel with the arithmetic.",
      "## The figure that deserves more attention than it gets",
      "Buried among the rest: the carbon footprint is <strong>60% below 2015 levels</strong>. That is the entry worth pausing on, because it runs the opposite way to everything above it. Revenue roughly quadrupled; the emissions fell by three-fifths in absolute terms. Almost every corporate environmental claim one encounters is a ratio dressed up as a reduction. This one is not.",
      "## The successor",
      "<strong>Ternus</strong> joined in <strong>2001</strong> and was <strong>senior vice president of Hardware Engineering</strong> &mdash; responsible for the physical iPhone, iPad, Mac, Apple Watch and AirPods. Twenty-five years in the building, and the promotion was announced on <strong>20 April</strong> to take effect on 1 September, so nobody had to be startled by it.",
      "Cook's description of him, for the record: he &laquo;has the mind of an engineer, the soul of an innovator, and the heart to lead with integrity&raquo;. Handsome, if a trifle upholstered.",
      "## What the next set of accounts cannot look like",
      "Whoever came next was never going to repeat an elevenfold increase in market value; there is simply not that much room above four trillion dollars. Which means the interesting question is no longer growth at all, but whether a company of this size can still be surprising &mdash; a rather more difficult thing to put in a table.",
    ],
    expertise:
      "If you take one habit from these figures, take the base-year check. <strong>&laquo;60% below 2015&raquo;</strong> is a real claim because it names its starting point and is stated in absolute terms; <strong>&laquo;60% more efficient&raquo;</strong> would say almost nothing, since efficiency per unit improves while the total rises. Most published environmental numbers are the second kind. It takes three seconds to tell them apart, and it is worth the three seconds.",
  },
  {
    slug: "venice-has-programmed-a-film-of-210-minutes",
    site: "lnd",
    image: "/covers/venice-has-programmed-a-film-of-210-minutes.jpg",
    imageAlt: "A paper reel of film unspooling far past the edge of a small cinema seat",
    imageKind: "generated",
    imageWidth: 1536,
    imageHeight: 864,
    title: "Venice has programmed a film of two hundred and ten minutes",
    cardTitle: "A film of 210 minutes",
    titleSeo: "The longest film at Venice 2026",
    summary:
      "The 83rd Mostra opens on 2 September with twenty films in competition. Its artistic director has warned that the selection runs long, and the longest of them is three and a half hours.",
    date: "2026-09-01",
    category: "Film",
    source: {
      name: "Screen International",
      url: "https://www.screendaily.com/news/venice-film-festival-reveals-2026-lineup/5218820.article",
      verifiedOn: "2026-09-01",
    },
    body: [
      "There is a quiet confidence in putting a film of three and a half hours in front of an audience and simply trusting them to stay. Venice has done it, and rather than apologise for it, has said so in advance.",
      "## The long one",
      "Of the <strong>twenty titles</strong> announced for competition on 23 July, the longest is <strong>Dau</strong>, by <strong>Ilya Khrzhanovsky</strong>, at <strong>210 minutes</strong>. Artistic director <strong>Alberto Barbera</strong> has said that this year&rsquo;s selection runs long generally &mdash; which is a courteous way of telling people to look at the running times before they book two things in an evening.",
      "## The festival around it",
      "The <strong>83rd Venice Film Festival</strong> runs from <strong>2 to 12 September 2026</strong> on the <strong>Lido</strong>. The jury is chaired by <strong>Maggie Gyllenhaal</strong>. It opens with <strong>Ink</strong>, by Danny Boyle, with Guy Pearce, and closes with Giovanni Veronesi&rsquo;s <strong>God Laughs</strong>. Honorary Golden Lions go to <strong>Ellen Burstyn</strong> and <strong>George Clooney</strong>. Also in competition: Werner Herzog, Martin McDonagh, Hirokazu Koreeda, Lee Chang-dong, Nanni Moretti, Florian Zeller and Shinya Tsukamoto.",
      "## Why length is a decision and not an accident",
      "A long film is expensive to show. It occupies a screen that could have held two shorter ones, it thins out the number of times it can play in a day, and it asks something of an audience that no marketing department has ever found a way to make sound appealing.",
      "A festival is the one place where that arithmetic can be set aside, because nobody is counting the day&rsquo;s takings against the seat. Which is why the very long film tends to have its life at festivals and then a rather harder time afterwards &mdash; and why a running time of 210 minutes in a competition line-up is worth noticing. Somebody looked at it and decided it was worth the screen.",
      "## The civilised way to do it",
      "One is not obliged to treat a long film as an endurance test. Eat beforehand rather than during, sit further back than instinct suggests, and take the interval &mdash; if there is one &mdash; as intended rather than as a chance to check a telephone. The pleasure of a very long film is that it stops being a thing one is watching and becomes, for an afternoon, simply where one is.",
    ],
    expertise:
      "Running times are published with festival line-ups and almost never with general releases, which makes a festival programme the one reliable place to find out what you are committing to. If a long film matters to you, the festival screening is likely to be the best conditions it ever gets: a full house that chose to be there, one uninterrupted projection, and nobody leaving at the ninety-minute mark to catch a train.",
  },
  {
    slug: "eclipse-walk-tower-hamlets-cemetery-park",
    site: "lnd",
    image: "/covers/eclipse-walk-tower-hamlets-cemetery-park.jpg",
    imageAlt: "Small crescents of light scattered across paper grass beneath a leaf canopy",
    imageKind: "generated",
    imageWidth: 1536,
    imageHeight: 864,
    title: "An eclipse read through seven graves in Bow",
    summary:
      "The Friends of Tower Hamlets Cemetery Park built a walk around the 12 August eclipse, using tree canopies as pinhole projectors and seven 19th-century graves as the route.",
    date: "2026-08-12",
    category: "Community",
    source: {
      name: "East London Advertiser",
      url: "https://www.eastlondonadvertiser.co.uk/news/26486399.tower-hamlets-cemetery-park-marked-eclipse/",
      verifiedOn: "2026-09-01",
    },
    body: [
      "The best instrument for watching a partial eclipse is not a telescope. It is a tree.",
      "A leaf canopy is a field of thousands of small irregular gaps, and each one works as a pinhole camera. On an ordinary afternoon they project overlapping discs of the sun onto the ground, which read as dappled light. During an eclipse each disc becomes a crescent &mdash; and a whole woodland floor turns into a projection of what is happening overhead.",
      "## What happened at the cemetery park",
      "On the evening of <strong>12 August</strong>, the <strong>Friends of Tower Hamlets Cemetery Park</strong> ran an <strong>Eclipse Walk</strong> through the park in east London. A few minutes after <strong>7pm</strong>, the sun&rsquo;s projections through the canopy shifted from circles into scattered crescents across the grass.",
      "Participants also used eclipse glasses, pinhole cameras, colanders and perforated spoons &mdash; each of which does the same job as the canopy, with fewer holes.",
      "## Seven graves as a route",
      "The walk was designed by <strong>Dr Mayanka Mukherji</strong>, Heritage Projects Lead at the Friends of Tower Hamlets Cemetery Park, who connected seven 19th-century graves to themes of light and the sun.",
      "Among those whose graves the route passes: <strong>William Henry Perkin</strong>, the chemist; <strong>Lucy Atkinson</strong>, the explorer; <strong>Clara Grant</strong>, known as the &laquo;Bundle Woman of Bow&raquo;; and <strong>Elizabeth Best</strong>, a leader of the 1888 matchgirls&rsquo; strike.",
      "The walk also drew on eclipse stories from a range of cultures &mdash; the explanations people reached for before the mechanism was understood.",
      "## Why a cemetery is the right room for this",
      "Tower Hamlets Cemetery Park stopped being a working burial ground long ago and became something rarer in inner east London: seven and a half hectares of woodland that nobody cleared. That woodland is what made the projection work, and the graves under it are what gave the evening its second subject.",
      "It is a good example of what a local heritage group can do that a science centre cannot &mdash; hold an astronomical event and a neighbourhood&rsquo;s nineteenth century in the same ninety minutes, on foot.",
    ],
    expertise:
      "The canopy trick works on any partial eclipse and needs no equipment at all, which makes it the one to remember. Stand under a leafy tree and look at the ground rather than the sky &mdash; and if there is no tree, a colander held a metre above a sheet of paper does the same thing. Looking directly at a partially eclipsed sun without proper eclipse glasses causes damage that is not felt at the time.",
  },
  {
    slug: "sl12-superloop-gants-hill-rainham",
    featured: 1,
    site: "lnd",
    image: "/covers/sl12-superloop-gants-hill-rainham.jpg",
    imageAlt: "A looping bus route line threaded with stop markers, a double-decker at one end",
    imageKind: "generated",
    imageWidth: 1536,
    imageHeight: 864,
    title: "The Superloop reaches Havering on 5 September",
    summary:
      "The SL12 runs Gants Hill to Rainham from 5 September, free for its first week, and cuts a journey of just over an hour down to about forty minutes.",
    date: "2026-08-28",
    category: "Transport",
    source: {
      name: "Evening Standard",
      url: "https://www.standard.co.uk/news/london/new-superloop-bus-service-gants-hill-rainham-launch-date-b1294725.html",
      verifiedOn: "2026-08-30",
    },
    body: [
      "Outer London has a particular kind of journey: two places six miles apart, both perfectly well served towards the centre, and nothing sensible running between them. The SL12 is aimed squarely at one of those.",
      "The new express bus links <strong>Gants Hill</strong> in Redbridge with <strong>Rainham</strong> in Havering, and it opens on <strong>Saturday 5 September 2026</strong>. It is the first time the Superloop has reached Havering at all.",
      "## Free for a week, but tap anyway",
      "Travel on the SL12 is <strong>free until 12 September</strong>. That does not mean walking on: passengers still have to touch in with an Oyster or a contactless card, exactly as they would on any other bus. Nothing is deducted &mdash; the tap is how the trip gets counted.",
      "It is worth doing properly for a reason beyond the rules. A new outer-London route lives or dies on its first fortnight of numbers, and a passenger who boards without tapping is a passenger who, as far as the data is concerned, was not there.",
      "## Forty minutes instead of an hour",
      "The headline figure is the one that matters to anyone who already makes this trip: a journey that currently takes <strong>slightly over an hour</strong> comes down to about <strong>40 minutes</strong>.",
      "The route is built as a set of interchanges rather than a line between two points. It connects the <strong>Central, District, Overground and Elizabeth</strong> lines, and it passes both <strong>King George&rsquo;s Hospital</strong> and <strong>Queen&rsquo;s Hospital</strong> &mdash; which, for the boroughs it crosses, is probably the single most-used pair of destinations on it.",
      "## The timetable",
      "The SL12 runs from <strong>05:30 to 00:30 every day</strong>. Frequency is every <strong>12 minutes</strong> through the day from Monday to Saturday, and every <strong>15 minutes</strong> in the evenings and all day Sunday.",
      "That evening and Sunday frequency is the part to note. Fifteen minutes is close to the threshold at which people stop consulting a timetable and simply turn up &mdash; which is the difference between a bus you plan around and a bus you use.",
      "## What the Superloop has done so far",
      "The orange express network has been running since July 2023. Since then it has carried around <strong>81 million trips</strong> and added <strong>9.6 million bus kilometres a year</strong> to the network. Its ridership runs about <strong>12% higher</strong> than on standard bus routes.",
      "That last number is the argument for building more of them, and more are coming: further routes are planned for next year between <strong>Stratford and Chingford Hatch</strong>, and between <strong>Clapham Junction and Eltham</strong>.",
      "## Why this one is an outer-London story",
      "Every Superloop route so far has traced the same shape &mdash; an orbital, joining outer centres to each other instead of feeding everyone through zone 1. Gants Hill to Rainham is that idea at its purest: neither end is anywhere near the middle of London, and the current alternative involves going in to come back out.",
    ],
    expertise:
      "The free week ends on 12 September, which is a Saturday. If the plan is to try the route before committing to it, the useful days are the weekdays in between &mdash; a Sunday trial tells you about the 15-minute frequency, not the 12-minute one you would actually be relying on.",
  },
  {
    slug: "bank-holiday-tube-and-tfl-closures",
    site: "lnd",
    image: "/covers/bank-holiday-tube-and-tfl-closures.jpg",
    imageAlt: "Three parallel route lines in cut paper, two broken by gaps with a barrier across one",
    imageKind: "generated",
    imageWidth: 1536,
    imageHeight: 864,
    title: "Which lines are shut over the bank holiday",
    summary:
      "The Northern line is out above Archway, the Windrush line is on buses south of Canada Water, and Barons Court loses its westbound trains until November. The full outer-London list.",
    date: "2026-08-27",
    category: "Transport",
    source: {
      name: "MyLondon",
      url: "https://www.mylondon.news/news/transport/london-underground-tfl-lines-shut-34525472",
      verifiedOn: "2026-08-30",
    },
    body: [
      "Most of the network runs normally over the August bank holiday. That is the honest headline, and it is also useless &mdash; because the closures that do exist are all in the places outer London actually travels through.",
      "Two events are pulling the crowds in opposite directions this weekend: All Points East at Victoria Park in the east, and Notting Hill Carnival in the west. The engineering work is unrelated, and it lands on top.",
      "## The Northern line, above Archway",
      "<strong>Friday 28 to Saturday 29 August</strong>: no service between <strong>Camden Town and High Barnet</strong> during the Friday Night Tube, for track work.",
      "<strong>Saturday 29 to Monday 31 August</strong>: no service between <strong>Archway and High Barnet or Mill Hill East</strong>, including the Saturday Night Tube.",
      "This is the shape of nearly every bank holiday closure, and it is worth naming: the line is not shut, its top is. Barnet, Finchley and Mill Hill lose their railway for three days while the section through the middle of town runs a normal service and gets described in the headline as &laquo;running&raquo;.",
      "## South of the river, on buses",
      "<strong>Windrush line, Saturday 29 to Monday 31 August</strong>: no service between <strong>Surrey Quays and Clapham Junction</strong> for Network Rail maintenance. Rail replacement buses run <strong>Canada Water to Clapham Junction</strong> &mdash; note that the buses start one stop further north than the closure does.",
      "<strong>Weaver line, Monday 31 August to Thursday 3 September</strong>: no service between <strong>Hackney Downs and Enfield Town or Cheshunt after 10.45pm</strong>, again for Network Rail. This one runs into the working week, and it is the late-evening trains, which are the ones people notice.",
      "<strong>DLR, Sunday 30 to Monday 31 August</strong>: no service between <strong>Tower Gateway and Shadwell</strong>.",
      "<strong>London Trams</strong>: no service between <strong>Reeves Corner and East Croydon</strong> until Sunday 30 August, and between <strong>Arena and Elmers End</strong> before 8am and after 6.45pm on the Saturday, then all day Sunday.",
      "## The one that outlasts the weekend",
      "<strong>Barons Court</strong>: westbound <strong>District and Piccadilly</strong> trains will not call there <strong>until November</strong>, for planned maintenance.",
      "That is a station losing half its service for roughly three months, which is a far bigger deal than any of the weekend closures above and is the sort of thing that appears once in a list and then never again.",
      "## Carnival, in the west",
      "TfL is asking people to travel to <strong>Paddington and walk the last twenty minutes</strong>, because the stations nearer the route will be queued out or shut.",
      "<strong>Ladbroke Grove is closed all day.</strong> <strong>Westbourne Park</strong>: no entry from 11am. <strong>Notting Hill Gate</strong>: no entry 11am&ndash;6pm, with District and Circle trains not stopping. <strong>Holland Park</strong>: no entry 11am&ndash;3pm, station shut from 3pm. <strong>Queensway</strong>: no entry 11am&ndash;6pm, exit only. <strong>Royal Oak</strong>: no entry 11am&ndash;6pm, shut at 6pm. <strong>Latimer Road</strong> may close for short periods and shuts at 11pm. <strong>Shepherd&rsquo;s Bush</strong> loses its ticket facilities and down escalator after 4pm &mdash; platform access is via <strong>71 steps</strong>. Queues are expected outside <strong>Kensal Green</strong> all day, and <strong>Kensal Rise</strong> closes its Chamberlayne Road entrance at 6pm.",
      "Buses are diverted away from the whole area: daytime routes <strong>7, 18, 23, 27, 28, 31, 36, 52, 70, 228, 295, 302, 316 and 328</strong>, and night routes <strong>N7, N27, N28 and N31</strong>. Special limited-stop services run instead, including the <strong>148X</strong> from Notting Hill Gate to Victoria between 10am and 5pm, and on to Vauxhall until 10pm.",
    ],
    expertise:
      "Check the closure list by section rather than by line. A line reported as \"running\" over a bank holiday is routinely running only across the middle of itself, which is precisely the part of it an outer-borough journey does not use.",
  },
  {
    slug: "olympic-park-summer-school",
    site: "lnd",
    image: "/covers/olympic-park-summer-school.jpg",
    imageAlt: "Workshop tables seen from above in a park, a stadium arc curving behind",
    imageKind: "generated",
    imageWidth: 1536,
    imageHeight: 864,
    title: "East Summer School returns to the Olympic Park",
    summary:
      "Three hundred young people, twenty-four workshops, six institutions from BBC Music Studios to ABBA Voyage — and the only entry requirement is living or studying in one of four boroughs.",
    date: "2026-08-26",
    category: "Community",
    source: {
      name: "East London Advertiser",
      url: "https://www.eastlondonadvertiser.co.uk/news/26408418.east-summer-school-returning-queen-elizabeth-olympic-park/",
      verifiedOn: "2026-08-30",
    },
    body: [
      "East Bank was built on a promise that the cultural quarter would belong to the boroughs around it rather than to the people who could afford to visit it. East Summer School is the part of that promise with an attendance register.",
      "The programme ran across <strong>Queen Elizabeth Olympic Park from 27 July to 7 August 2026</strong>, for young people aged <strong>12 to 17</strong> who live or study in <strong>Hackney, Newham, Tower Hamlets or Waltham Forest</strong>. It is free to take part.",
      "## Who is actually teaching",
      "This is where it stops sounding like a council holiday scheme. The programme is delivered with the institutions based in the park&rsquo;s East Bank quarter: <strong>BBC Music Studios</strong>, <strong>Sadler&rsquo;s Wells East</strong>, <strong>UAL&rsquo;s London College of Fashion</strong>, <strong>UCL</strong>, <strong>V&amp;A East</strong> and <strong>ABBA Voyage</strong>.",
      "The sessions are specific rather than general-purpose: flood-resilient neighbourhood mapping at UCL, inclusive dance at Sadler&rsquo;s Wells East, fashion history at UAL, content creation for the BBC&rsquo;s Asian Network, exhibition curation at V&amp;A East, and backstage tours at ABBA Voyage.",
      "Backstage at ABBA Voyage is worth pausing on. It is one of the most technically advanced shows running anywhere, and the number of sixteen-year-olds who have been shown how it works is very small.",
      "## The numbers",
      "In <strong>2025</strong>, more than <strong>300 young people</strong> attended <strong>24 workshops</strong>. This year participants chose <strong>one activity per week</strong> rather than sampling everything &mdash; a change that trades breadth for actually finishing something.",
      "It ends with a <strong>showcase at the ArcelorMittal Orbit</strong>, where participants present their work to parents, carers and community supporters.",
      "## Why the four boroughs",
      "Queen Elizabeth Olympic Park sits across <strong>Newham, Tower Hamlets, Waltham Forest and Hackney</strong>, which is the reason a programme based there reaches an audience no single borough&rsquo;s own provision does. It is also the reason the eligibility rule is drawn the way it is: the park is the shared thing, so the catchment is everyone whose borough touches it.",
      "> Skills for the future are developing at pace, so we want to make sure children and young people from east London don&rsquo;t miss out, and that Queen Elizabeth Olympic Park institutions can help prepare them for the jobs of tomorrow.\n— Shazia Hussain, chief executive of the London Legacy Development Corporation",
      "## The machinery behind it",
      "East Summer School is led by the <strong>London Legacy Development Corporation</strong> and supported by the <strong>East End Community Foundation</strong>, now in its second year of backing it. It forms part of <strong>East Ed</strong>, an LLDC initiative connecting young people and educators with East Bank organisations, employers and universities.",
      "Which is the answer to the obvious question about a two-week summer course: on its own it is a fortnight, and inside East Ed it is an introduction with somewhere to go next.",
    ],
    expertise:
      "The eligibility line is <em>live or study</em> in one of the four boroughs, not live in them. A family in Redbridge or Barking with a child at school in Newham qualifies, and routinely assumes it does not &mdash; which is the most common reason a place on a scheme like this goes unfilled.",
  },
];
