import type { NewsItem } from "../types.ts";

export const items: NewsItem[] = [
  {
    slug: "venice-has-programmed-a-film-of-210-minutes",
    site: "lnd",
    image: "/covers/venice-has-programmed-a-film-of-210-minutes.jpg",
    imageAlt: "A paper reel of film unspooling far past the edge of a small cinema seat",
    imageKind: "generated",
    imageWidth: 1536,
    imageHeight: 864,
    title: "Venice has programmed a film of two hundred and ten minutes",
    cardTitle: "A film of 210 minutes",
    titleSeo: "The longest film at Venice 2026",
    summary:
      "The 83rd Mostra opens on 2 September with twenty films in competition. Its artistic director has warned that the selection runs long, and the longest of them is three and a half hours.",
    date: "2026-09-01",
    category: "Film",
    source: {
      name: "Screen International",
      url: "https://www.screendaily.com/news/venice-film-festival-reveals-2026-lineup/5218820.article",
      verifiedOn: "2026-09-01",
    },
    body: [
      "There is a quiet confidence in putting a film of three and a half hours in front of an audience and simply trusting them to stay. Venice has done it, and rather than apologise for it, has said so in advance.",
      "## The long one",
      "Of the <strong>twenty titles</strong> announced for competition on 23 July, the longest is <strong>Dau</strong>, by <strong>Ilya Khrzhanovsky</strong>, at <strong>210 minutes</strong>. Artistic director <strong>Alberto Barbera</strong> has said that this year&rsquo;s selection runs long generally &mdash; which is a courteous way of telling people to look at the running times before they book two things in an evening.",
      "## The festival around it",
      "The <strong>83rd Venice Film Festival</strong> runs from <strong>2 to 12 September 2026</strong> on the <strong>Lido</strong>. The jury is chaired by <strong>Maggie Gyllenhaal</strong>. It opens with <strong>Ink</strong>, by Danny Boyle, with Guy Pearce, and closes with Giovanni Veronesi&rsquo;s <strong>God Laughs</strong>. Honorary Golden Lions go to <strong>Ellen Burstyn</strong> and <strong>George Clooney</strong>. Also in competition: Werner Herzog, Martin McDonagh, Hirokazu Koreeda, Lee Chang-dong, Nanni Moretti, Florian Zeller and Shinya Tsukamoto.",
      "## Why length is a decision and not an accident",
      "A long film is expensive to show. It occupies a screen that could have held two shorter ones, it thins out the number of times it can play in a day, and it asks something of an audience that no marketing department has ever found a way to make sound appealing.",
      "A festival is the one place where that arithmetic can be set aside, because nobody is counting the day&rsquo;s takings against the seat. Which is why the very long film tends to have its life at festivals and then a rather harder time afterwards &mdash; and why a running time of 210 minutes in a competition line-up is worth noticing. Somebody looked at it and decided it was worth the screen.",
      "## The civilised way to do it",
      "One is not obliged to treat a long film as an endurance test. Eat beforehand rather than during, sit further back than instinct suggests, and take the interval &mdash; if there is one &mdash; as intended rather than as a chance to check a telephone. The pleasure of a very long film is that it stops being a thing one is watching and becomes, for an afternoon, simply where one is.",
    ],
    expertise:
      "Running times are published with festival line-ups and almost never with general releases, which makes a festival programme the one reliable place to find out what you are committing to. If a long film matters to you, the festival screening is likely to be the best conditions it ever gets: a full house that chose to be there, one uninterrupted projection, and nobody leaving at the ninety-minute mark to catch a train.",
  },
  {
    slug: "eclipse-walk-tower-hamlets-cemetery-park",
    site: "lnd",
    image: "/covers/eclipse-walk-tower-hamlets-cemetery-park.jpg",
    imageAlt: "Small crescents of light scattered across paper grass beneath a leaf canopy",
    imageKind: "generated",
    imageWidth: 1536,
    imageHeight: 864,
    title: "An eclipse read through seven graves in Bow",
    summary:
      "The Friends of Tower Hamlets Cemetery Park built a walk around the 12 August eclipse, using tree canopies as pinhole projectors and seven 19th-century graves as the route.",
    date: "2026-08-12",
    category: "Community",
    source: {
      name: "East London Advertiser",
      url: "https://www.eastlondonadvertiser.co.uk/news/26486399.tower-hamlets-cemetery-park-marked-eclipse/",
      verifiedOn: "2026-09-01",
    },
    body: [
      "The best instrument for watching a partial eclipse is not a telescope. It is a tree.",
      "A leaf canopy is a field of thousands of small irregular gaps, and each one works as a pinhole camera. On an ordinary afternoon they project overlapping discs of the sun onto the ground, which read as dappled light. During an eclipse each disc becomes a crescent &mdash; and a whole woodland floor turns into a projection of what is happening overhead.",
      "## What happened at the cemetery park",
      "On the evening of <strong>12 August</strong>, the <strong>Friends of Tower Hamlets Cemetery Park</strong> ran an <strong>Eclipse Walk</strong> through the park in east London. A few minutes after <strong>7pm</strong>, the sun&rsquo;s projections through the canopy shifted from circles into scattered crescents across the grass.",
      "Participants also used eclipse glasses, pinhole cameras, colanders and perforated spoons &mdash; each of which does the same job as the canopy, with fewer holes.",
      "## Seven graves as a route",
      "The walk was designed by <strong>Dr Mayanka Mukherji</strong>, Heritage Projects Lead at the Friends of Tower Hamlets Cemetery Park, who connected seven 19th-century graves to themes of light and the sun.",
      "Among those whose graves the route passes: <strong>William Henry Perkin</strong>, the chemist; <strong>Lucy Atkinson</strong>, the explorer; <strong>Clara Grant</strong>, known as the &laquo;Bundle Woman of Bow&raquo;; and <strong>Elizabeth Best</strong>, a leader of the 1888 matchgirls&rsquo; strike.",
      "The walk also drew on eclipse stories from a range of cultures &mdash; the explanations people reached for before the mechanism was understood.",
      "## Why a cemetery is the right room for this",
      "Tower Hamlets Cemetery Park stopped being a working burial ground long ago and became something rarer in inner east London: seven and a half hectares of woodland that nobody cleared. That woodland is what made the projection work, and the graves under it are what gave the evening its second subject.",
      "It is a good example of what a local heritage group can do that a science centre cannot &mdash; hold an astronomical event and a neighbourhood&rsquo;s nineteenth century in the same ninety minutes, on foot.",
    ],
    expertise:
      "The canopy trick works on any partial eclipse and needs no equipment at all, which makes it the one to remember. Stand under a leafy tree and look at the ground rather than the sky &mdash; and if there is no tree, a colander held a metre above a sheet of paper does the same thing. Looking directly at a partially eclipsed sun without proper eclipse glasses causes damage that is not felt at the time.",
  },
  {
    slug: "sl12-superloop-gants-hill-rainham",
    featured: 1,
    site: "lnd",
    image: "/covers/sl12-superloop-gants-hill-rainham.jpg",
    imageAlt: "A looping bus route line threaded with stop markers, a double-decker at one end",
    imageKind: "generated",
    imageWidth: 1536,
    imageHeight: 864,
    title: "The Superloop reaches Havering on 5 September",
    summary:
      "The SL12 runs Gants Hill to Rainham from 5 September, free for its first week, and cuts a journey of just over an hour down to about forty minutes.",
    date: "2026-08-28",
    category: "Transport",
    source: {
      name: "Evening Standard",
      url: "https://www.standard.co.uk/news/london/new-superloop-bus-service-gants-hill-rainham-launch-date-b1294725.html",
      verifiedOn: "2026-08-30",
    },
    body: [
      "Outer London has a particular kind of journey: two places six miles apart, both perfectly well served towards the centre, and nothing sensible running between them. The SL12 is aimed squarely at one of those.",
      "The new express bus links <strong>Gants Hill</strong> in Redbridge with <strong>Rainham</strong> in Havering, and it opens on <strong>Saturday 5 September 2026</strong>. It is the first time the Superloop has reached Havering at all.",
      "## Free for a week, but tap anyway",
      "Travel on the SL12 is <strong>free until 12 September</strong>. That does not mean walking on: passengers still have to touch in with an Oyster or a contactless card, exactly as they would on any other bus. Nothing is deducted &mdash; the tap is how the trip gets counted.",
      "It is worth doing properly for a reason beyond the rules. A new outer-London route lives or dies on its first fortnight of numbers, and a passenger who boards without tapping is a passenger who, as far as the data is concerned, was not there.",
      "## Forty minutes instead of an hour",
      "The headline figure is the one that matters to anyone who already makes this trip: a journey that currently takes <strong>slightly over an hour</strong> comes down to about <strong>40 minutes</strong>.",
      "The route is built as a set of interchanges rather than a line between two points. It connects the <strong>Central, District, Overground and Elizabeth</strong> lines, and it passes both <strong>King George&rsquo;s Hospital</strong> and <strong>Queen&rsquo;s Hospital</strong> &mdash; which, for the boroughs it crosses, is probably the single most-used pair of destinations on it.",
      "## The timetable",
      "The SL12 runs from <strong>05:30 to 00:30 every day</strong>. Frequency is every <strong>12 minutes</strong> through the day from Monday to Saturday, and every <strong>15 minutes</strong> in the evenings and all day Sunday.",
      "That evening and Sunday frequency is the part to note. Fifteen minutes is close to the threshold at which people stop consulting a timetable and simply turn up &mdash; which is the difference between a bus you plan around and a bus you use.",
      "## What the Superloop has done so far",
      "The orange express network has been running since July 2023. Since then it has carried around <strong>81 million trips</strong> and added <strong>9.6 million bus kilometres a year</strong> to the network. Its ridership runs about <strong>12% higher</strong> than on standard bus routes.",
      "That last number is the argument for building more of them, and more are coming: further routes are planned for next year between <strong>Stratford and Chingford Hatch</strong>, and between <strong>Clapham Junction and Eltham</strong>.",
      "## Why this one is an outer-London story",
      "Every Superloop route so far has traced the same shape &mdash; an orbital, joining outer centres to each other instead of feeding everyone through zone 1. Gants Hill to Rainham is that idea at its purest: neither end is anywhere near the middle of London, and the current alternative involves going in to come back out.",
    ],
    expertise:
      "The free week ends on 12 September, which is a Saturday. If the plan is to try the route before committing to it, the useful days are the weekdays in between &mdash; a Sunday trial tells you about the 15-minute frequency, not the 12-minute one you would actually be relying on.",
  },
  {
    slug: "bank-holiday-tube-and-tfl-closures",
    site: "lnd",
    image: "/covers/bank-holiday-tube-and-tfl-closures.jpg",
    imageAlt: "Three parallel route lines in cut paper, two broken by gaps with a barrier across one",
    imageKind: "generated",
    imageWidth: 1536,
    imageHeight: 864,
    title: "Which lines are shut over the bank holiday",
    summary:
      "The Northern line is out above Archway, the Windrush line is on buses south of Canada Water, and Barons Court loses its westbound trains until November. The full outer-London list.",
    date: "2026-08-27",
    category: "Transport",
    source: {
      name: "MyLondon",
      url: "https://www.mylondon.news/news/transport/london-underground-tfl-lines-shut-34525472",
      verifiedOn: "2026-08-30",
    },
    body: [
      "Most of the network runs normally over the August bank holiday. That is the honest headline, and it is also useless &mdash; because the closures that do exist are all in the places outer London actually travels through.",
      "Two events are pulling the crowds in opposite directions this weekend: All Points East at Victoria Park in the east, and Notting Hill Carnival in the west. The engineering work is unrelated, and it lands on top.",
      "## The Northern line, above Archway",
      "<strong>Friday 28 to Saturday 29 August</strong>: no service between <strong>Camden Town and High Barnet</strong> during the Friday Night Tube, for track work.",
      "<strong>Saturday 29 to Monday 31 August</strong>: no service between <strong>Archway and High Barnet or Mill Hill East</strong>, including the Saturday Night Tube.",
      "This is the shape of nearly every bank holiday closure, and it is worth naming: the line is not shut, its top is. Barnet, Finchley and Mill Hill lose their railway for three days while the section through the middle of town runs a normal service and gets described in the headline as &laquo;running&raquo;.",
      "## South of the river, on buses",
      "<strong>Windrush line, Saturday 29 to Monday 31 August</strong>: no service between <strong>Surrey Quays and Clapham Junction</strong> for Network Rail maintenance. Rail replacement buses run <strong>Canada Water to Clapham Junction</strong> &mdash; note that the buses start one stop further north than the closure does.",
      "<strong>Weaver line, Monday 31 August to Thursday 3 September</strong>: no service between <strong>Hackney Downs and Enfield Town or Cheshunt after 10.45pm</strong>, again for Network Rail. This one runs into the working week, and it is the late-evening trains, which are the ones people notice.",
      "<strong>DLR, Sunday 30 to Monday 31 August</strong>: no service between <strong>Tower Gateway and Shadwell</strong>.",
      "<strong>London Trams</strong>: no service between <strong>Reeves Corner and East Croydon</strong> until Sunday 30 August, and between <strong>Arena and Elmers End</strong> before 8am and after 6.45pm on the Saturday, then all day Sunday.",
      "## The one that outlasts the weekend",
      "<strong>Barons Court</strong>: westbound <strong>District and Piccadilly</strong> trains will not call there <strong>until November</strong>, for planned maintenance.",
      "That is a station losing half its service for roughly three months, which is a far bigger deal than any of the weekend closures above and is the sort of thing that appears once in a list and then never again.",
      "## Carnival, in the west",
      "TfL is asking people to travel to <strong>Paddington and walk the last twenty minutes</strong>, because the stations nearer the route will be queued out or shut.",
      "<strong>Ladbroke Grove is closed all day.</strong> <strong>Westbourne Park</strong>: no entry from 11am. <strong>Notting Hill Gate</strong>: no entry 11am&ndash;6pm, with District and Circle trains not stopping. <strong>Holland Park</strong>: no entry 11am&ndash;3pm, station shut from 3pm. <strong>Queensway</strong>: no entry 11am&ndash;6pm, exit only. <strong>Royal Oak</strong>: no entry 11am&ndash;6pm, shut at 6pm. <strong>Latimer Road</strong> may close for short periods and shuts at 11pm. <strong>Shepherd&rsquo;s Bush</strong> loses its ticket facilities and down escalator after 4pm &mdash; platform access is via <strong>71 steps</strong>. Queues are expected outside <strong>Kensal Green</strong> all day, and <strong>Kensal Rise</strong> closes its Chamberlayne Road entrance at 6pm.",
      "Buses are diverted away from the whole area: daytime routes <strong>7, 18, 23, 27, 28, 31, 36, 52, 70, 228, 295, 302, 316 and 328</strong>, and night routes <strong>N7, N27, N28 and N31</strong>. Special limited-stop services run instead, including the <strong>148X</strong> from Notting Hill Gate to Victoria between 10am and 5pm, and on to Vauxhall until 10pm.",
    ],
    expertise:
      "Check the closure list by section rather than by line. A line reported as \"running\" over a bank holiday is routinely running only across the middle of itself, which is precisely the part of it an outer-borough journey does not use.",
  },
  {
    slug: "olympic-park-summer-school",
    site: "lnd",
    image: "/covers/olympic-park-summer-school.jpg",
    imageAlt: "Workshop tables seen from above in a park, a stadium arc curving behind",
    imageKind: "generated",
    imageWidth: 1536,
    imageHeight: 864,
    title: "East Summer School returns to the Olympic Park",
    summary:
      "Three hundred young people, twenty-four workshops, six institutions from BBC Music Studios to ABBA Voyage — and the only entry requirement is living or studying in one of four boroughs.",
    date: "2026-08-26",
    category: "Community",
    source: {
      name: "East London Advertiser",
      url: "https://www.eastlondonadvertiser.co.uk/news/26408418.east-summer-school-returning-queen-elizabeth-olympic-park/",
      verifiedOn: "2026-08-30",
    },
    body: [
      "East Bank was built on a promise that the cultural quarter would belong to the boroughs around it rather than to the people who could afford to visit it. East Summer School is the part of that promise with an attendance register.",
      "The programme ran across <strong>Queen Elizabeth Olympic Park from 27 July to 7 August 2026</strong>, for young people aged <strong>12 to 17</strong> who live or study in <strong>Hackney, Newham, Tower Hamlets or Waltham Forest</strong>. It is free to take part.",
      "## Who is actually teaching",
      "This is where it stops sounding like a council holiday scheme. The programme is delivered with the institutions based in the park&rsquo;s East Bank quarter: <strong>BBC Music Studios</strong>, <strong>Sadler&rsquo;s Wells East</strong>, <strong>UAL&rsquo;s London College of Fashion</strong>, <strong>UCL</strong>, <strong>V&amp;A East</strong> and <strong>ABBA Voyage</strong>.",
      "The sessions are specific rather than general-purpose: flood-resilient neighbourhood mapping at UCL, inclusive dance at Sadler&rsquo;s Wells East, fashion history at UAL, content creation for the BBC&rsquo;s Asian Network, exhibition curation at V&amp;A East, and backstage tours at ABBA Voyage.",
      "Backstage at ABBA Voyage is worth pausing on. It is one of the most technically advanced shows running anywhere, and the number of sixteen-year-olds who have been shown how it works is very small.",
      "## The numbers",
      "In <strong>2025</strong>, more than <strong>300 young people</strong> attended <strong>24 workshops</strong>. This year participants chose <strong>one activity per week</strong> rather than sampling everything &mdash; a change that trades breadth for actually finishing something.",
      "It ends with a <strong>showcase at the ArcelorMittal Orbit</strong>, where participants present their work to parents, carers and community supporters.",
      "## Why the four boroughs",
      "Queen Elizabeth Olympic Park sits across <strong>Newham, Tower Hamlets, Waltham Forest and Hackney</strong>, which is the reason a programme based there reaches an audience no single borough&rsquo;s own provision does. It is also the reason the eligibility rule is drawn the way it is: the park is the shared thing, so the catchment is everyone whose borough touches it.",
      "> Skills for the future are developing at pace, so we want to make sure children and young people from east London don&rsquo;t miss out, and that Queen Elizabeth Olympic Park institutions can help prepare them for the jobs of tomorrow.\n— Shazia Hussain, chief executive of the London Legacy Development Corporation",
      "## The machinery behind it",
      "East Summer School is led by the <strong>London Legacy Development Corporation</strong> and supported by the <strong>East End Community Foundation</strong>, now in its second year of backing it. It forms part of <strong>East Ed</strong>, an LLDC initiative connecting young people and educators with East Bank organisations, employers and universities.",
      "Which is the answer to the obvious question about a two-week summer course: on its own it is a fortnight, and inside East Ed it is an introduction with somewhere to go next.",
    ],
    expertise:
      "The eligibility line is <em>live or study</em> in one of the four boroughs, not live in them. A family in Redbridge or Barking with a child at school in Newham qualifies, and routinely assumes it does not &mdash; which is the most common reason a place on a scheme like this goes unfilled.",
  },
];
