import type { NewsItem } from "../types.ts";

export const items: NewsItem[] = [
  {
    slug: "cuatro-cienegas-borrego-cimarron",
    site: "mxo",
    title: "Los bisontes funcionaron; ahora va el borrego",
    summary:
      "Cuarenta y siete bisontes devolvieron a Cuatro Ciénegas gato montés, pecaríes y venados. La siguiente pieza que la fundación quiere reponer es el borrego cimarrón: una manada fundacional de 12 a 15 ejemplares.",
    date: "2026-08-28",
    category: "Naturaleza",
    source: {
      name: "Milenio",
      url: "https://www.milenio.com/estados/borrego-cimarron-siguiente-introduccion-en-cuatro-cienegas-coahuila",
      verifiedOn: "2026-08-30",
    },
    body: [
      "La restauración ecológica suele medirse en promesas. En Cuatro Ciénegas se está midiendo en cámaras trampa, y lo que aparece en ellas es lo que nadie puso ahí.",
      "## Lo que pasó primero",
      "En el verano de <strong>2025</strong> llegaron a la reserva El Santuario los primeros <strong>tres bisontes americanos</strong>, procedentes del Museo del Desierto. En noviembre de ese año se sumaron otros <strong>44 ejemplares</strong>, y la manada quedó en <strong>47</strong>.",
      "A casi un año de la primera llegada, el monitoreo con cámaras trampa empezó a mostrar algo que no formaba parte del proyecto: la cadena alimentaria creció sola. Aparecieron <strong>gato montés</strong>, una manada de <strong>pecaríes</strong> y <strong>venados</strong>. Nadie los reintrodujo. Volvieron.",
      "## Por qué un bisonte trae un gato montés",
      "No es magia, es pasto. Un herbívoro grande que pace y se mueve cambia la altura y la composición de la vegetación, y con ella el suelo, la retención de agua y la cantidad de animales pequeños que pueden vivir ahí. Cuando hay más presa pequeña, aparece quien la caza. El bisonte no atrae al gato montés: le construye la despensa.",
      "Ese es el argumento entero de la reintroducción de especies clave, y es un argumento que casi siempre se defiende en teoría porque el resultado tarda décadas. Aquí tardó menos de un año en verse.",
      "## Lo que viene",
      "La <strong>Fundación Pro CuatroCiénegas</strong> quiere ahora al <strong>borrego cimarrón</strong>, una especie nativa de la zona. El plan que su director, Gerardo Ruiz Smith, describió a Milenio es una <strong>manada fundacional de entre 12 y 15 ejemplares</strong>, que en una primera etapa vivirá en un espacio protegido, con alimentación y cuidados controlados.",
      "El encierro no es un detalle administrativo: es la etapa que decide si el proyecto funciona. Los animales tienen que adaptarse al sitio y empezar a reproducirse antes de que se libere a nadie, y sólo conforme crezca la población se avanza gradualmente hacia la liberación dentro del predio.",
      "> Ya tenemos algunos fondos iniciales para empezar a planear y obtener los permisos para la infraestructura inicial que se estaría construyendo.\n— Gerardo Ruiz Smith, director de la Fundación Pro CuatroCiénegas, a Milenio",
      "Es una frase modesta y conviene leerla como está escrita: hay dinero para planear y para permisos, no para soltar borregos. La prioridad declarada de la fundación sigue siendo <strong>consolidar el proyecto del bisonte</strong> antes de concentrar esfuerzos en el siguiente.",
      "## Qué significa esto para quien quiera ir",
      "Cuatro Ciénegas es una reserva de la biosfera en el desierto de Coahuila, célebre por sus pozas de agua cristalina y por una biología que se estudia como análogo de vida temprana en la Tierra. Lo que cambia con este proyecto no es el paisaje, que ya era extraordinario, sino la probabilidad de ver fauna grande en él.",
      "Y cambia el tipo de visita. Una reserva con 47 bisontes y una cadena alimentaria en recuperación no se recorre igual que una laguna: se recorre despacio, temprano, y con la expectativa razonable de no ver nada. Esa es también la señal de que está funcionando.",
    ],
    expertise:
      "El dato que ordena todo lo demás es el orden de los factores. La fundación no reintrodujo depredadores ni presas: reintrodujo un herbívoro grande y esperó. Gato montés, pecaríes y venados llegaron por su cuenta. Un proyecto que hubiera empezado por soltar depredadores habría tenido titulares antes y resultados después &mdash; o ninguno.",
  },
  {
    slug: "tren-ligero-texcoco-la-paz",
    site: "mxo",
    title: "El tren de Texcoco: once estaciones, 30 minutos",
    summary:
      "El Edomex publicó el proyecto del Tren Ligero Texcoco–La Paz: 21 kilómetros, once estaciones, media hora de punta a punta contra los setenta minutos de hoy.",
    date: "2026-08-27",
    category: "Movilidad",
    source: {
      name: "Chilango",
      url: "https://www.chilango.com/noticias/transporte/publican-proyecto-tren-ligero-de-texcoco-a-la-paz-estaciones-trenes-tiempo-de-recorrido/",
      verifiedOn: "2026-08-30",
    },
    body: [
      "Un proyecto de transporte se vuelve real el día que publica su lista de estaciones. Antes de eso es una línea sobre un mapa; después es algo que se puede discutir casa por casa. El Tren Ligero Texcoco&ndash;La Paz acaba de cruzar esa frontera.",
      "El Gobierno del Estado de México publicó el proyecto en la plataforma <strong>Proyectos México</strong>, en etapa de preinversión, con un documento fechado el <strong>7 de agosto</strong>. El contrato que se licitará incluye obra civil y de sistemas, gestión ambiental y de urbanismo, y material rodante.",
      "## Las once estaciones",
      "De oriente a poniente: <strong>Texcoco, Autónoma de Chapingo, San Bernardino, Puerta Texcoco, Central de Abasto, Piedras Negras, Francisco Villa, Conalep Los Reyes, La Magdalena, Los Reyes y La Paz</strong>.",
      "Los dos extremos importan por razones distintas. En Texcoco, la terminal se ubicará en la <strong>antigua estación del ferrocarril México&ndash;Veracruz</strong>, sobre la calle Nezahualcóyotl, en el barrio de San Juanito &mdash; es decir, el tren regresa a un edificio que ya fue estación. En el poniente, la línea termina en <strong>Metro La Paz</strong>, cabecera de la Línea A, que es lo que convierte a esto en algo más que un tren local: conecta a Texcoco, Chimalhuacán y Nezahualcóyotl con la red del Metro de la Ciudad de México.",
      "## Los números",
      "<strong>21 kilómetros</strong> de longitud. <strong>30 minutos</strong> de terminal a terminal, contra los setenta que hoy toma el mismo trayecto: una reducción superior al <strong>50% del tiempo</strong>. Velocidad comercial de <strong>41 km/h</strong>, máxima de 80.",
      "El material rodante son <strong>14 trenes dobles</strong> &mdash; para comparar, el Tren Ligero de la Ciudad de México opera con cerca de 20 trenes dobles acoplados. La demanda que se busca cubrir con esos catorce es de <strong>127 mil usuarios al día</strong>.",
      "## El detalle que casi nadie está mirando",
      "La línea será de <strong>operación mixta</strong>: conviven servicio de carga y de pasajeros. Lo anunció la Secretaría de Movilidad mexiquense desde enero, y es la decisión más consecuente del proyecto.",
      "Una línea mixta cambia todo lo demás. Cambia el diseño de la vía, cambia la frecuencia posible para el pasajero, cambia el mantenimiento y cambia las ventanas horarias en que cada servicio puede circular. Explica también por qué la velocidad comercial se fija en 41 km/h y no más alta. No es un pero: es la razón por la que un proyecto de este tamaño resulta financiable en el oriente del Estado de México, donde la carga ya existe y el pasajero, hasta ahora, viaja en camión.",
      "## Lo que falta",
      "Preinversión significa que hay proyecto y no hay obra. Falta la licitación, falta el contrato y faltan las fechas. Aquí no aparece un año de inauguración porque nadie lo ha publicado, y una lista de estaciones no es un calendario.",
      "Lo que sí es firme es la geometría: once estaciones, dos terminales identificadas con dirección, y una conexión con la Línea A que define para quién se está construyendo.",
    ],
    expertise:
      "El ahorro real no son los 40 minutos del tren. Es que el trayecto Texcoco&ndash;Metro se vuelve predecible: hoy depende del tráfico de la carretera y por eso su duración varía entre un día y otro más de lo que dura el viaje en sí. Un tren de 30 minutos vale menos por rápido que por igual todos los días.",
  },
  {
    slug: "filij-2026-regresa-al-cenart",
    site: "mxo",
    title: "La FILIJ regresa al CENART con entrada gratuita",
    summary:
      "La 44 edición de la Feria Internacional del Libro Infantil y Juvenil será del 13 al 22 de noviembre en el CENART, con entrada gratuita y convocatoria abierta para visitas escolares.",
    date: "2026-08-28",
    category: "Ferias",
    source: {
      name: "Excélsior",
      url: "https://www.excelsior.com.mx/cultura/filij-2026-regresa-cenart-con-entrada-gratuita-fechas",
      verifiedOn: "2026-08-30",
    },
    body: [
      "Una feria del libro para niños se mide por una cosa: cuántos de los que entran salen leyendo algo que eligieron ellos. La FILIJ lleva 44 ediciones construida alrededor de esa idea, y la de 2026 vuelve al mismo sitio y con el mismo precio &mdash; ninguno.",
      "## Fechas y sede",
      "De acuerdo con el <strong>Fondo de Cultura Económica</strong>, la <strong>44 edición</strong> de la Feria Internacional del Libro Infantil y Juvenil se realizará del <strong>13 al 22 de noviembre</strong> en el <strong>Centro Nacional de las Artes</strong>. La <strong>entrada es gratuita</strong>.",
      "El FCE abrió además una <strong>convocatoria para visitas escolares</strong>, cuyos detalles se consultan por sus canales oficiales. Ese es el mecanismo por el que la feria llega a los niños que no habrían ido en fin de semana con la familia.",
      "## Qué es, más allá de los libros",
      "La FILIJ reúne editoriales, escritores, ilustradores y familias. La oferta editorial va del cuento ilustrado a la novela juvenil y el libro informativo, para todas las edades.",
      "Pero la feria no es una venta de libros con actividades encima. La programación cultural suele incluir <strong>cuentacuentos, talleres creativos, presentaciones de libros, teatro, música y danza</strong> &mdash; y en la práctica ésa es la parte que convierte una visita en una costumbre.",
      "La distinción importa para quien va con niños pequeños: se puede pasar una mañana completa sin comprar nada y que el día haya valido.",
      "## Cómo llegar",
      "El CENART está en <strong>Avenida Río Churubusco 79</strong>, colonia Country Club Churubusco, alcaldía Coyoacán.",
      "En transporte público, las estaciones de Metro más cercanas son <strong>General Anaya</strong> (Línea 2) y <strong>Ermita</strong> (Línea 12). De cualquiera de las dos son <strong>de 8 a 10 minutos caminando</strong>.",
      "## Y si ya se está ahí",
      "El CENART mantiene cartelera todo el año, con espectáculos, talleres y actividades infantiles. Noviembre es cuando el recinto se llena de niños, pero no es el único mes en que programa para ellos.",
    ],
    expertise:
      "Diez días es mucha feria y el error habitual es ir el primer o el último fin de semana. Entre semana la FILIJ se vacía de familias y se llena de grupos escolares en horario de mañana; una tarde de martes o miércoles es, con diferencia, el momento en que un niño puede acercarse a una mesa y hojear sin cola.",
  },
  {
    slug: "kusama-320-mil-visitantes",
    site: "mxo",
    title: "Kusama pasó de 320 mil visitantes",
    summary:
      "Más de 320 mil personas vieron «Obsesión Infinita» en el Museo Tamayo entre 2014 y 2015. Al final el museo abrió 36 horas seguidas y casi 10 mil personas entraron en ese maratón.",
    date: "2026-08-27",
    category: "Arte",
    source: {
      name: "El Universal Cultura",
      url: "https://www.eluniversal.com.mx/cultura/la-exposicion-de-yayoi-kusama-que-obsesiono-a-mexico/",
      verifiedOn: "2026-08-30",
    },
    body: [
      "Hubo una fila en Reforma que la gente aguantó acampando. No era por un concierto: era por una exposición de arte contemporáneo, en un museo público, un miércoles cualquiera de enero.",
      "## Los números",
      "<strong>&laquo;Obsesión Infinita&raquo;</strong>, de la artista japonesa <strong>Yayoi Kusama</strong>, se inauguró el <strong>26 de septiembre de 2014</strong> en el <strong>Museo Tamayo</strong> y cerró el <strong>18 de enero de 2015</strong>. Recibió a más de <strong>320 mil personas</strong>, según cifras del gobierno mexicano.",
      "Fue la primera retrospectiva de Kusama en América Latina, y la primera vez que se registraba esa cantidad de visitantes en una exposición en México.",
      "Conforme se acercaba el cierre, la fila creció hasta que el museo hizo lo que casi ningún museo hace: <strong>abrir 36 horas seguidas</strong>. En ese maratón final se registraron <strong>casi 10 mil personas</strong>.",
      "## Qué había adentro",
      "Más de <strong>100 obras creadas entre 1950 y 2013</strong>. Piezas de la serie <em>Infinity net</em>, la película <em>Kusama&rsquo;s Self-Obliteration</em>, y las instalaciones <em>Phalli&rsquo;s field</em>, <em>Obliteration room</em> e <em>Infinity mirror room</em>.",
      "Esas tres instalaciones explican buena parte de la fila. Son obras que no se ven: se entra en ellas, de una persona a la vez o de tres en tres. El aforo por hora de una <em>Infinity mirror room</em> es minúsculo por diseño, y eso convierte cualquier éxito de público en una cola.",
      "## No fue sólo México",
      "La exposición fue organizada por el museo <strong>Malba</strong> de Buenos Aires, donde convocó a <strong>180 mil asistentes</strong> y terminó con las calles vecinas decoradas con lunares. También pasó por Río de Janeiro, Brasilia y São Paulo, y de México viajó a Chile.",
      "Visto así, el dato mexicano se lee mejor: 320 mil contra 180 mil en la ciudad que la organizó.",
      "## La artista",
      "Kusama nació en <strong>Matsumoto en 1929</strong> y murió este año. Se mudó a Nueva York en <strong>1957</strong> y siguió pintando puntos en obras hechas de seriación y repetición; fue amiga de Andy Warhol y Georgia O&rsquo;Keeffe. Su trabajo llegó al MoMA de Nueva York, al Museo Ludwig en Alemania y a la Tate Modern de Londres, y en <strong>2016</strong> recibió la <strong>Orden de la Cultura</strong>, el premio más prestigioso que Japón otorga a sus artistas.",
      "Decía que dibujaba como veía el mundo: cubierto de manchas.",
    ],
    expertise:
      "El maratón de 36 horas es el dato que suelen citar mal. No fue un truco de mercadotecnia al inicio, fue una respuesta al final: el museo abrió de corrido porque la fila ya no cabía en los días que quedaban. Vale como advertencia práctica para cualquier exposición muy esperada &mdash; el mes barato para verla es el primero, no el último.",
  },
  {
    slug: "john-giorno-en-kurimanzutto",
    site: "mxo",
    title: "kurimanzutto recibe la obra poética de John Giorno",
    summary:
      "Poesía en los muros, en vinilos que el visitante elige, en un video de diez horas y en un teléfono. La primera individual de John Giorno en la Ciudad de México está en kurimanzutto hasta el 10 de octubre.",
    date: "2026-08-26",
    category: "Arte",
    source: {
      name: "El Universal Cultura",
      url: "https://www.eluniversal.com.mx/cultura/galeria-kurimanzutto-recibe-la-obra-poetica-del-artista-john-giorno/",
      verifiedOn: "2026-08-30",
    },
    body: [
      "Hay una línea telefónica en la librería de kurimanzutto. Se levanta el auricular y alguien recita. No hay menú, no hay espera: la poesía ya está sonando y uno se incorpora a la mitad.",
      "Es <em>Dial-A-Poem</em>, la obra más famosa de <strong>John Giorno</strong> (1936&ndash;2019), exhibida por primera vez en el <strong>MoMA</strong> de Nueva York en <strong>1970</strong>, y es la mejor puerta de entrada a lo que la galería montó.",
      "## La primera individual en la ciudad",
      "<strong>John Giorno: LIFE IS A KILLER</strong> es la primera exposición individual del artista, activista y poeta en la <strong>Ciudad de México</strong>. Reúne sus obras poéticas más representativas, desde los primeros trabajos hasta piezas de sus últimas series, de <strong>2015</strong>.",
      "Giorno fue contemporáneo de Andy Warhol y William S. Burroughs, y su idea rectora era simple y radical: la poesía no debía existir sólo en la página.",
      "> Era fiel creyente de que la poesía no debía existir sólo en la página, sino que era tan esencial para la comunicación de la humanidad, por lo que podía y debía existir en el mundo.\n— Corinna Durland, directora de la sede neoyorquina de kurimanzutto",
      "Por eso en la sala se puede <strong>leer</strong> poesía en los muros y <strong>oírla</strong> en un disco de vinilo, en un <strong>video de más de diez horas</strong> realizado por <strong>Rirkrit Tiravanija</strong>, o por teléfono.",
      "## Los cuadros que son frases",
      "Están las <em>Poem paintings</em>, iniciadas en Italia en los años setenta y punto de partida de su pintura. Llevan versos como &laquo;Everything is delusion including wisdom&raquo;, &laquo;Everyone gets lighter&raquo;, &laquo;Filling what is empty, emptying what is full&raquo; y el que da título a la muestra, &laquo;Life is a killer&raquo;.",
      "La mayoría son en blanco y negro, con una <strong>tipografía diseñada para él por Mark Michaelson en 1984</strong>. Las de fondo de arcoíris son de <strong>2015</strong> en adelante, hechas como gesto de apoyo a la libertad de las personas LGBT.",
      "También se exhibe una de sus obras más tempranas: un poema inspirado en el juicio de Bobby Seale, cofundador de las Panteras Negras.",
      "## El corazón: los vinilos",
      "El galerista lo llama así, y es literal. Giorno grabó bajo su propio sello discos con poemas y canciones hechos junto a sus amigos, entre ellos <strong>Debbie Harry</strong> y <strong>Patti Smith</strong>. Los vinilos pueden reproducirse dentro de la galería, y es <strong>el visitante quien elige cuál suena</strong>.",
      "Esa decisión curatorial hace mucho más de lo que parece: convierte a quien entra en programador de la sala. La exposición suena distinta según quién esté adentro.",
      "## La parte hecha para México",
      "El galerista José Kuri contó que al planear la muestra se preguntaron cómo conectar el trabajo del estadounidense con México. La respuesta fue un <strong>taller de traducción</strong> de sus poemas al español, en colaboración con la librería <strong>La Americana</strong>, que se publicará en un fanzine. Participan <strong>Brenda Lozano, Carla Faesler, Paloma Contreras, Isabel Zapata y Mateo Díaz Choza</strong>.",
      "## Dónde y hasta cuándo",
      "La muestra estará <strong>hasta el 10 de octubre</strong> en <strong>Gob. Rafael Rebollar 94, San Miguel Chapultepec</strong>.",
    ],
    expertise:
      "Hay que reservar tiempo para el teléfono y los vinilos, que es donde la exposición realmente pasa y donde nadie se detiene. Una sala de poesía se recorre por instinto como se recorre una de pintura &mdash; leyendo los muros y saliendo &mdash;, y así se pierde exactamente la mitad de la obra: la que suena.",
  },
];
