import type { NewsItem } from "../types.ts";

export const items: NewsItem[] = [

  {
    slug: "veinte-anos-del-festival-de-vida-y-muerte",
    site: "mxo",
    image: "/covers/veinte-anos-del-festival-de-vida-y-muerte.jpg",
    imageAlt: "Muchas flores de cempas\u00fachil de papel, naranjas, repartidas en cuatro hileras sobre un fondo azul verdoso, con una franja vac\u00eda a la mitad",
    imageKind: "generated",
    imageWidth: 1536,
    imageHeight: 864,
    title: "Veinte a\u00f1os del Festival de Vida y Muerte, y un estado invitado que cambia cada edici\u00f3n",
    cardTitle: "Veinte a\u00f1os del Festival de Vida y Muerte",
    titleSeo: "Festival de Vida y Muerte: 20 ediciones",
    summary:
      "Xcaret cumple veinte ediciones del 30 de octubre al 2 de noviembre. El invitado de 2026 es Guanajuato, y el Concierto de Gala se vende aparte.",
    date: "2026-09-08",
    city: "Riviera Maya",
    country: "M\u00e9xico",
    category: "Festivales",
    source: {
      name: "Festival de Vida y Muerte",
      url: "https://festivaldevidaymuerte.com/",
      verifiedOn: "2026-09-08",
    },
    body: [
      "Hay una decisi\u00f3n que este festival toma cada a\u00f1o y que ning\u00fan otro del pa\u00eds toma igual: invita a un estado a celebrar el D\u00eda de Muertos a su manera, dentro de un parque que est\u00e1 a mil kil\u00f3metros de ah\u00ed. En <strong>2026 el invitado es Guanajuato</strong>, y la edici\u00f3n es la <strong>n\u00famero 20</strong>.",
      "## Las fechas",
      "<strong>Del 30 de octubre al 2 de noviembre</strong>, en el Parque Xcaret, en la Riviera Maya. Son cuatro d\u00edas: dos antes de la fiesta y los dos d\u00edas de la fiesta misma, que se celebra el <strong>1 y el 2 de noviembre</strong>.",
      "## Qu\u00e9 se escucha",
      "El programa musical no es un cartel de festival al uso: mariachi, estudiantina, sones, huapango arribe\u00f1o y m\u00fasica tradicional de la Pen\u00ednsula de Yucat\u00e1n. Es decir, repertorio de la fecha, no de la temporada de conciertos.",
      "## El boleto que se compra aparte",
      "El <strong>Concierto de Gala</strong> del <strong>31 de octubre</strong> no entra con el acceso al parque; el organizador lo vende por separado. Los detalles y el resto del programa est\u00e1n en <a href=\"/eventos/festival-de-vida-y-muerte-2026/\" title=\"Festival de Vida y Muerte 2026\">la ficha del festival</a>.",
    ],
    faq: [
      {
        q: "\u00bfCu\u00e1ndo es el Festival de Vida y Muerte 2026?",
        a: "<strong>Del 30 de octubre al 2 de noviembre de 2026</strong>, en el Parque Xcaret, Riviera Maya.",
      },
      {
        q: "\u00bfQu\u00e9 estado es el invitado en 2026?",
        a: "<strong>Guanajuato</strong>. El festival cambia de estado invitado cada edici\u00f3n.",
      },
      {
        q: "\u00bfEl D\u00eda de Muertos y el festival son lo mismo?",
        a: "No. La fiesta es el <strong>1 y 2 de noviembre</strong> en todo el pa\u00eds; el festival dura cuatro d\u00edas y empieza dos antes.",
      },
    ],
    expertise:
      "Veinte ediciones convierten a este festival en algo distinto de una fiesta local: es una puesta en escena del D\u00eda de Muertos para quien llega de fuera, y conviene leerlo as\u00ed antes de comprar. Quien busca la celebraci\u00f3n dom\u00e9stica \u2014 la ofrenda de una casa, el pante\u00f3n de un pueblo la noche del 1 de noviembre \u2014 no la va a encontrar dentro de un parque, y no es un defecto del festival: son dos experiencias distintas que caen los mismos d\u00edas y obligan a elegir.",
  },
  {
    slug: "relojes-proteomicos-y-una-dosis-partida-en-dos",
    site: "mxo",
    image: "/covers/relojes-proteomicos-y-una-dosis-partida-en-dos.jpg",
    imageAlt: "Un enjambre de pequeños discos naranjas de papel a la izquierda que se dispersa hacia un único disco grande a la derecha, sobre fondo verde oscuro",
    imageKind: "generated",
    imageWidth: 1536,
    imageHeight: 864,
    title: "La misma cantidad de fármaco, partida en dos tomas, cambió lo que midieron seis relojes biológicos",
    cardTitle: "Seis relojes y una dosis partida",
    titleSeo: "Relojes proteómicos: qué miden y qué no",
    summary:
      "Seis modelos que estiman la edad biológica a partir de proteínas en sangre coincidieron en un ensayo clínico. La dosis partida en dos tomas dio la señal más clara.",
    date: "2026-09-08",
    category: "Ciencia",
    source: {
      name: "Nature Biotechnology",
      url: "https://www.nature.com/articles/s41587-026-03286-y",
      verifiedOn: "2026-09-08",
    },
    body: [
      "Un reloj proteómico no mide nada parecido a lo que sugiere su nombre. Toma una muestra de sangre, cuenta la cantidad de cada una de unas miles de proteínas que circulan en ella y devuelve un número expresado en años. Ese número es una estimación estadística: la edad que suele tener alguien cuyo perfil de proteínas se parece a este. Nada dentro del cuerpo lleva la cuenta.",
      "El <strong>7 de septiembre de 2026</strong>, <strong>Nature Biotechnology</strong> publicó un trabajo que aplicó seis de estos modelos a las mismas muestras y comparó sus respuestas. Es la primera vez que se comparan tantos a la vez dentro de un ensayo clínico con grupo placebo.",
      "## Por qué seis y no uno",
      "Los seis fueron construidos de maneras distintas. Cuatro aprendieron a adivinar la edad del calendario; dos aprendieron a estimar el riesgo de morir, que es una pregunta diferente y da respuestas diferentes. Unos usan aprendizaje automático clásico, otros redes profundas. El número de proteínas que consideran también varía.",
      "Esa diversidad es deliberada. Si un solo modelo detecta un cambio, lo detectado puede ser una peculiaridad del modelo. Si seis modelos con supuestos distintos apuntan en la misma dirección, la explicación más económica es que algo cambió en la sangre. Los seis apuntaron en la misma dirección en todos los grupos tratados; el grupo con placebo no se movió o envejeció ligeramente.",
      "## El detalle que nadie esperaba",
      "El ensayo probó tres pautas: 30 mg una vez al día, 30 mg dos veces al día y 60 mg una vez al día. Las dos últimas suman lo mismo en veinticuatro horas.",
      "No dieron el mismo resultado. La pauta de <strong>30 mg dos veces al día</strong> produjo la señal más amplia y más consistente entre los seis relojes, y también el mayor número de proteínas modificadas: 142 que no se movieron en ningún otro grupo. La de 60 mg de una sola vez quedó por detrás en ese aspecto, pese a ser la que más mejoró la capacidad pulmonar en el informe original del ensayo.",
      "La explicación que proponen los autores es farmacológica y comprobable. El compuesto se elimina en siete a once horas, así que una toma única genera un pico de concentración dos o tres veces más alto y luego un valle largo. Dos tomas menores mantienen un nivel más parejo. La hipótesis es que lo que responde a la exposición sostenida no es lo mismo que responde al pico.",
      "## Lo que el estudio no puede afirmar",
      "Cuarenta y dos personas aceptaron el análisis de proteínas, todas con la misma enfermedad pulmonar y una edad media de 67 años. Doce semanas es poco tiempo. Y hay un problema de fondo que los propios autores señalan en cada apartado: varias de las proteínas que más pesan en estos relojes son marcadores de fibrosis, precisamente lo que el fármaco fue diseñado para frenar.",
      "Es decir, el reloj puede estar leyendo una enfermedad que mejora en lugar de un envejecimiento que se frena. Distinguir las dos cosas exige repetir el experimento en personas que no tengan esa enfermedad, y eso todavía no se ha hecho.",
    ],
    expertise:
      "Conviene separar dos afirmaciones que suelen viajar juntas y no valen lo mismo. La primera es que estos modelos detectan cambios reales en la sangre y coinciden entre sí: eso el trabajo lo muestra con bastante solidez, y es un avance metodológico aprovechable por cualquier ensayo que ya extraiga sangre. La segunda es que alguien rejuveneció tres años, y eso el trabajo no lo muestra ni lo pretende. Un número en años es una unidad prestada para hacer legible una distancia estadística, no una medida del tiempo vivido. Cuando una nota de prensa convierta lo segundo en titular, el lugar donde verificarlo es el apartado de limitaciones del propio artículo, que en este caso es largo y explícito.",
  },

  {
    slug: "el-texto-lleva-marca-la-imagen-lleva-firma",
    site: "mxo",
    image: "/covers/el-texto-lleva-marca-la-imagen-lleva-firma.jpg",
    imageAlt: "Dos hojas de papel del mismo tamaño sobre fondo verde, la de la izquierda color terracota con un sello en la esquina y la de la derecha color crema y sin nada",
    imageKind: "generated",
    imageWidth: 1536,
    imageHeight: 864,
    title: "Anthropic marca el texto de una forma y las imágenes de otra, y una captura de pantalla borra una de las dos",
    cardTitle: "Dos maneras de marcar, una frágil",
    titleSeo: "Texto marcado, imagen firmada",
    summary:
      "Lo que Claude escribe lleva una marca dentro de las propias palabras. Lo que entrega como archivo lleva metadatos firmados, y esos se pierden al capturar la pantalla.",
    date: "2026-09-08",
    category: "Tecnología",
    source: {
      name: "Anthropic",
      url: "https://www.anthropic.com/news/claude-text-watermark",
      verifiedOn: "2026-09-08",
    },
    body: [
      "Desde el <strong>2 de agosto de 2026</strong> Anthropic marca lo que produce Claude. Marca dos cosas distintas de dos maneras distintas, y la diferencia entre ambas decide cuál de las dos sobrevive a que alguien le tome una foto a la pantalla.",
      "## El texto: la marca está adentro",
      "En cada palabra el modelo elige entre varias equivalentes usando un número al azar, y ese azar ahora se calcula a partir de una <strong>clave secreta</strong> y de lo ya escrito. El texto no cambia; cambia el patrón de las elecciones. Como la señal está en las palabras mismas, <strong>viaja con ellas</strong>: se copia, se pega, se cambia de programa y sigue ahí. La técnica es una variante de <strong>SynthID-Text</strong>, de <strong>Google DeepMind</strong>.",
      "## Los archivos: la firma está afuera",
      "Los formatos admitidos —<strong>.png</strong>, <strong>.jpg</strong> y <strong>.svg</strong>— no llevan marca de agua sino <strong>metadatos de procedencia firmados</strong> según el estándar <strong>C2PA</strong>. Es una etiqueta pegada al archivo, no algo mezclado con la imagen.",
      "## Por qué eso importa más de lo que parece",
      "Una etiqueta pegada se despega. Una <strong>captura de pantalla</strong> elimina por completo esos metadatos; una conversión de formato, también. La imagen se ve idéntica y ya no declara nada. Con el texto pasa lo contrario: aguanta el copiar y pegar y cierta edición, y lo que sí lo borra es una traducción o una reescritura a fondo.",
      "## Lo que ninguna de las dos prueba",
      "Un acierto quiere decir que el contenido <em>pudo</em> haber pasado por Claude, no que lo escribió. En textos muy cortos, o de pura cifra, no hay señal suficiente. Y la herramienta que lee la marca está en <strong>vista previa privada</strong>: se otorga por solicitud a reguladores, medios, verificadores, investigadores y organizaciones educativas, no al público.",
    ],
    expertise:
      "La asimetría entre los dos mecanismos ya se nota en el trabajo diario de cualquiera que publique en línea. Un archivo firmado es verificable por cualquiera, sin permiso ni clave, porque C2PA es un estándar abierto con herramientas libres: eso lo vuelve útil y frágil a la vez, porque basta una captura para dejarlo mudo. El texto es lo contrario, robusto pero ilegible sin la clave. La lectura práctica es que quien quiera conservar procedencia debe guardar el archivo original y no la versión que pasó por tres aplicaciones, y que para el texto no hay archivo original que guardar: solo el registro propio de cuándo y con qué se hizo.",
  },

  {
    slug: "la-feria-de-francisco-i-madero-abre-el-11-de-septiembre",
    site: "mxo",
    image: "/covers/la-feria-de-francisco-i-madero-abre-el-11-de-septiembre.jpg",
    imageAlt: "Banderines de papel terracota y crema colgados en dos hileras sobre fondo verde bosque, uno de ellos girado de canto",
    imageKind: "generated",
    imageWidth: 1536,
    imageHeight: 864,
    title: "La Feria de Francisco I. Madero abre el 11 de septiembre y cierra con el Grito adentro",
    cardTitle: "Feria Madero, del 11 al 19",
    titleSeo: "Feria Madero Coahuila: 11 al 19 de septiembre",
    summary:
      "Nueve días en Francisco I. Madero, Coahuila, con bailes, artesanía y gastronomía regional — y las fiestas patrias cayendo dentro del programa, no al lado de él.",
    date: "2026-09-07",
    category: "Ferias",
    source: {
      name: "Ferias en México",
      url: "https://www.feriasenmexico.com.mx/feria-madero-coahuila-2026/",
      verifiedOn: "2026-09-07",
    },
    body: [
      "Casi todas las ferias del país compiten con el 15 de septiembre. Ésta hizo lo contrario: se lo metió dentro.",
      "## Las fechas",
      "<strong>Del 11 al 19 de septiembre</strong>, en <strong>Francisco I. Madero</strong>, Coahuila, en el marco del aniversario de la fundación del poblado.",
      "## El programa",
      "<strong>Bailes masivos</strong>, exposiciones <strong>artesanales</strong> y de <strong>gastronomía típica</strong> de la región, presentaciones artísticas y musicales, concursos culturales, <strong>danzas folclóricas</strong> y juegos mecánicos.",
      "## Lo que cae en medio",
      "Como la feria cruza el <strong>15 y 16 de septiembre</strong>, el programa incluye los actos cívicos: honores a la bandera, el <strong>Grito de Independencia</strong> y espectáculos de pirotecnia. No son un añadido de última hora; están en el calendario de la feria.",
      "## Por qué eso cambia la feria",
      "Una feria de nueve días que contiene la noche del Grito no tiene un día fuerte: tiene dos temporadas. Los primeros días son de exposición y de familia; a partir del 14 la sede se convierte en la plaza del pueblo el día más concurrido del año.",
    ],
    expertise:
      "La Comarca Lagunera en septiembre es de días de más de treinta grados y noches que bajan de golpe, y una feria al aire libre de nueve días se vive de noche por esa razón — el programa artesanal y gastronómico funciona por la tarde, y los bailes cuando ya se puede estar de pie. Para quien viaje de fuera, la decisión relevante es la fecha, no el día de la semana: hospedarse en Francisco I. Madero la noche del 15 es otro mercado que hospedarse el 12, y Torreón, a menos de una hora, absorbe esa diferencia. Y conviene revisar el programa cívico por separado del artístico: los horarios de los actos oficiales se publican tarde y mueven todo lo demás de la noche.",
  },

  {
    slug: "gpt-6-astra-saturo-tres-examenes",
    site: "mxo",
    image: "/covers/gpt-6-astra-saturo-tres-examenes.jpg",
    imageAlt: "Sobre un fondo verde profundo, tres barras de papel crema de alturas crecientes y una cuarta en terracota, más baja que las dos que la preceden",
    imageKind: "generated",
    imageWidth: 1536,
    imageHeight: 864,
    title: "El modelo que saturó tres exámenes a la vez",
    cardTitle: "GPT-6 Astra saturó FrontierMath",
    titleSeo: "GPT-6 Astra: 97,6% en FrontierMath",
    summary:
      "OpenAI presentó GPT-6 Astra el 3 de septiembre. Saturó el nivel más difícil de FrontierMath con 97,6%, ARC-AGI-3 con 99,9% y sacó 96,0% en el examen de ciencias de posgrado.",
    date: "2026-09-06",
    category: "Mundo",
    source: {
      name: "OpenAI",
      url: "https://openai.com/index/gpt-6-astra/",
      verifiedOn: "2026-09-06",
    },
    body: [
      "Saturar un examen quiere decir que ya no sirve para medir: casi todas las preguntas quedan bien y las que fallan no distinguen a nadie. La semana pasada le pasó a tres a la vez",
      "## Los números",
      "<strong>OpenAI</strong> presentó <strong>GPT-6 Astra</strong> el <strong>3 de septiembre de 2026</strong>. En <strong>FrontierMath Tier 4</strong>, el nivel más difícil de un examen de matemáticas hecho con matemáticos profesionales, obtuvo <strong>97,6%</strong>. En <strong>ARC-AGI-3</strong>, <strong>99,9%</strong>. En <strong>GPQA Diamond</strong>, preguntas de nivel doctorado en biología, química y física, <strong>96,0%</strong>",
      "## Lo que dijeron los que ponen los exámenes",
      "<strong>Greg Kamradt</strong>, de la ARC Prize Foundation, sobre ARC-AGI-3: «Astra superó nuestra línea base de eficiencia humana en el 96% de los niveles», y lo llamó un cambio de escalón, no una mejora más",
      "<strong>Greg Burnham</strong>, de EpochAI, fue más corto: «La historia es: fin de una era, principio de otra»",
      "## La parte que no es un examen",
      "OpenAI publicó junto al anuncio <strong>dos resultados nuevos sobre los huecos entre números primos</strong> — la distancia que separa un primo del siguiente, uno de los problemas viejos de la teoría de números. No es una demostración célebre resuelta; es la diferencia entre un modelo que contesta preguntas de matemáticas y uno que aporta un renglón a un problema abierto",
      "## Y donde no ganó",
      "Conviene decirlo porque casi nadie lo dice. En <strong>Humanity’s Last Exam</strong>, con herramientas, Astra sacó <strong>57,2%</strong>, por debajo del <strong>65,0%</strong> de <strong>Claude Fable 5.1</strong> y de otros dos modelos de la misma tabla. En el índice de Artificial Analysis quedó en <strong>61,2</strong> contra 65,7. Las tablas son de OpenAI y ahí están",
    ],
    expertise:
      "Un examen saturado es una noticia de dos filos: dice que el modelo ya llegó al techo de esa prueba, y también que la prueba dejó de servir para comparar lo que venga después. FrontierMath se diseñó en 2024 justamente porque los exámenes anteriores se habían agotado, y duró dos años. Lo que conviene mirar de aquí en adelante no son los porcentajes sino los dos resultados sobre números primos: un porcentaje se compara con otro porcentaje, pero un resultado matemático lo revisan personas, con nombre, y o se sostiene o no. Ese es el único marcador que no se puede saturar",
  },

  {
    slug: "mexico-cuarto-lugar-mundial-en-pib-turistico",
    site: "mxo",
    image: "/covers/mexico-cuarto-lugar-mundial-en-pib-turistico.jpg",
    imageAlt: "Cuatro barras de papel de alturas decrecientes, la cuarta en un tono distinto y ligeramente separada de las otras tres",
    imageKind: "generated",
    imageWidth: 1536,
    imageHeight: 864,
    title: "México queda cuarto del mundo en aportación del turismo al PIB",
    cardTitle: "Cuarto lugar mundial en PIB turístico",
    titleSeo: "México, cuarto en PIB turístico",
    summary:
      "El WTTC presentó en Cancún sus cifras 2025: 149,400 millones de dólares de aportación al PIB y 237,900 millones en gasto de viajes de ocio. Solo Estados Unidos, China y Alemania están arriba.",
    date: "2026-09-06",
    category: "Turismo",
    source: {
      name: "La Región Tamaulipas",
      url: "https://laregiontam.com.mx/2026/09/05/mexico-se-consolida-como-potencia-turistica-mundial-y-alcanza-el-cuarto-lugar-en-pib-y-gasto-de-ocio/",
      verifiedOn: "2026-09-06",
    },
    body: [
      "Un país puede recibir muchísimos visitantes y aun así ganar poco con ellos. La cifra que presentó el WTTC esta semana mide lo contrario, y ahí México quedó cuarto del mundo.",
      "## Las cifras",
      "El <strong>Consejo Mundial de Viajes y Turismo (WTTC)</strong> presentó el <strong>5 de septiembre de 2026</strong>, desde <strong>Cancún, Quintana Roo</strong>, los datos correspondientes a <strong>2025</strong>: una aportación directa del turismo al PIB de <strong>149,400 millones de dólares</strong> y un <strong>gasto en viajes de ocio de 237,900 millones</strong>.",
      "En ambos indicadores México ocupa el <strong>cuarto lugar mundial</strong>. Por delante quedan <strong>Estados Unidos, China y Alemania</strong>.",
      "## El contexto global",
      "El sector creció <strong>4%</strong> en 2025, aporta <strong>11.6 billones de dólares</strong> a la economía mundial y sostiene <strong>366 millones de empleos</strong>. La presidenta del WTTC, <strong>Gloria Guevara</strong>, presentó los datos desde el Caribe mexicano; la cumbre global del organismo será del <strong>7 al 9 de octubre</strong> en <strong>La Valeta, Malta</strong>.",
      "## Por qué el gasto de ocio es el dato interesante",
      "El ranking de llegadas mide cuánta gente cruza la frontera. El de gasto de ocio mide cuánto deja cada quien. Que México esté cuarto en el segundo, y no solo en el primero, significa que el país no compite únicamente por volumen — algo que su vecino del norte, primer lugar de la lista, tiene resuelto desde hace décadas.",
    ],
    expertise:
      "Conviene leer estas dos cifras juntas y con cuidado. La aportación directa al PIB cuenta lo que producen hoteles, aerolíneas, restaurantes y operadores; el gasto de ocio cuenta lo que desembolsan los viajeros, nacionales incluidos. Que el segundo número sea 1.6 veces el primero no es una contradicción: buena parte de ese gasto se va en cadenas de suministro, importaciones y comisiones que no quedan en la cuenta directa. La consecuencia práctica para quien invierte o trabaja en el sector es que el margen no está en atraer más llegadas — está en retener más días y más consumo por viaje, que es exactamente lo que separa a un destino de playa de una plaza urbana con oferta cultural. Y hay una advertencia estándar: son cifras del propio consejo de la industria, calculadas con su metodología, no estadística oficial del INEGI.",
  },

  {
    slug: "el-decagono-de-saturno-estaba-en-el-archivo",
    site: "mxo",
    image: "/covers/el-decagono-de-saturno-estaba-en-el-archivo.jpg",
    imageAlt: "Tres marcos de papel apilados, con un contorno de diez lados apenas visible a través del primero",
    imageKind: "generated",
    imageWidth: 1536,
    imageHeight: 864,
    title: "El decágono de Saturno llevaba tres años fotografiado sin que nadie lo viera",
    cardTitle: "El decágono estaba en el archivo",
    titleSeo: "Saturno tiene un decágono",
    summary:
      "El Hubble confirmó una onda de diez lados en el polo sur de Saturno. Estaba en imágenes de 2023; hicieron falta dos aficionados en 2024 para saber qué era.",
    date: "2026-09-05",
    category: "Ciencia",
    source: {
      name: "EarthSky",
      url: "https://earthsky.org/space/saturns-south-pole-decagon-confirmed-a-mysterious-10-sided-figure/",
      verifiedOn: "2026-09-06",
    },
    body: [
      "El descubrimiento no ocurrió al apuntar un telescopio hacia algo nuevo, sino al volver a mirar fotos que ya estaban tomadas, archivadas y pagadas.",
      "## El hallazgo",
      "Una <strong>onda atmosférica de diez lados</strong> rodea el <strong>polo sur de Saturno</strong>. La confirmó el <strong>telescopio espacial Hubble</strong> y se publicó el <strong>2 de septiembre de 2026</strong> en <em>Science Advances</em>, en un trabajo encabezado por <strong>Agustín Sánchez-Lavega</strong>, de la Universidad del País Vasco.",
      "## La cronología",
      "<strong>2023</strong>: el Hubble capta indicios tenues de una figura de diez vértices que nadie estaba buscando.<br />",
      "<strong>2024</strong>: los aficionados <strong>Trevor Barry</strong> y <strong>Jean-Paul Oger</strong> notan desde tierra una banda ondulada en el polo sur.<br />",
      "<strong>Agosto y septiembre de 2025</strong>: las imágenes muestran el decágono completo.",
      "## Lo que lo hace distinto",
      "El hexágono del polo norte se ve desde hace <strong>más de cuarenta años</strong> y es estable. Este no: según <strong>Amy Simon</strong>, del Centro Goddard de la NASA, «parece estar fortaleciéndose». Es la primera vez que se puede seguir una de estas figuras desde que empieza.",
    ],
    expertise:
      "Hay aquí una lección sobre cómo se hace ciencia con presupuesto público. El programa OPAL de la NASA fotografía los planetas exteriores una vez al año desde hace más de una década, ocurra algo o no; el decágono estaba en esas imágenes tres años antes de que alguien tuviera la pregunta correcta. Como resume Mike Wong, de la Universidad de California en Berkeley, los hallazgos no salen de una observación sino de años y años de datos. Para la astronomía amateur — grande y bien equipada en México — el corolario es útil: la ventaja de un telescopio pequeño no es la resolución, es la frecuencia. Nadie con un equipo doméstico va a resolver una onda polar, pero sí puede ser quien note que algo cambió entre una noche y otra.",
  },

  {
    slug: "morelia-anuncia-96-peliculas-mexicanas",
    site: "mxo",
    image: "/covers/morelia-anuncia-96-peliculas-mexicanas.jpg",
    imageAlt: "Noventa y seis rectángulos de papel en cuadrícula, cuarenta de ellos en un tono distinto",
    imageKind: "generated",
    imageWidth: 1536,
    imageHeight: 864,
    title: "Morelia selecciona 96 películas mexicanas y cuatro de ellas vienen de comunidades indígenas",
    cardTitle: "Morelia anuncia 96 películas mexicanas",
    titleSeo: "FICM 2026: 96 cintas mexicanas",
    summary:
      "El 40% de la Selección Oficial del 24 Festival Internacional de Cine de Morelia está dirigido por mujeres. El festival va del 16 al 25 de octubre.",
    date: "2026-09-02",
    category: "Cine",
    source: {
      name: "IMCINE",
      url: "https://www.imcine.gob.mx/nota.php?id=326",
      verifiedOn: "2026-09-03",
    },
    body: [
      "Una cifra sirve para medir un festival y otra para medir un país. El <strong>24 Festival Internacional de Cine de Morelia</strong> publicó las dos al mismo tiempo.",
      "## La selección",
      "La <strong>Selección Oficial</strong> reúne <strong>96 películas mexicanas</strong>. El <strong>40%</strong> está dirigido por mujeres y <strong>cuatro</strong> por cineastas de comunidades indígenas.",
      "## Cómo está dividida",
      "Las secciones son <strong>Michoacán</strong> (cortometraje y largometraje), <strong>Cortometraje Mexicano</strong> — con sus ramas de animación, documental y ficción —, <strong>Largometraje Documental Mexicano</strong> y <strong>Largometraje Mexicano</strong>.",
      "## Las fechas",
      "Del <strong>16 al 25 de octubre de 2026</strong> en <strong>Morelia, Michoacán</strong>, con funciones presenciales y una extensión virtual a través de <strong>Nuestro Cine Mx</strong>.",
      "## El dato que explica la lista",
      "Buena parte de los títulos lleva marcado su apoyo público: <strong>FOCINE</strong>, <strong>EFICINE</strong>, <strong>PROCINE</strong> y el <strong>ECAMC</strong>. La selección de un festival privado — el FICM es una asociación civil sin fines de lucro, fundada en <strong>2003</strong> — termina siendo, de paso, el inventario más legible de lo que financió el Estado.",
    ],
    expertise:
      "Al leer una Selección Oficial conviene mirar primero la sección de cortometraje, no la de largo. En Morelia el corto no es la antesala del programa: es donde el festival construyó su reputación y donde aparecen los nombres que dentro de cinco años estarán en la competencia larga. La sección Michoacán cumple una función distinta — reservar lugar a la producción del estado anfitrión — y es la que mejor indica si un festival regional sigue siendo regional. Sobre la extensión virtual: históricamente no incluye todo el programa ni por el mismo tiempo, así que vale revisar título por título antes de dar por hecho que algo se podrá ver a distancia.",
  },

  {
    slug: "veinticinco-anos-para-llegar-a-la-cima",
    site: "mxo",
    image: "/covers/veinticinco-anos-para-llegar-a-la-cima.jpg",
    imageAlt: "Una escalera de papel que asciende en escalones iguales hasta un borde alto",
    imageKind: "generated",
    imageWidth: 1536,
    imageHeight: 864,
    title: "Veinticinco años dentro del mismo edificio",
    cardTitle: "De ingeniero a director general",
    titleSeo: "John Ternus, 25 años en Apple",
    summary:
      "John Ternus entró a Apple en 2001 y la dirige desde el 1 de septiembre de 2026. Es una carrera que la industria tecnológica dice ya no premiar.",
    date: "2026-09-01",
    category: "Tecnología",
    source: {
      name: "Apple Newsroom",
      url: "https://www.apple.com/newsroom/2026/04/tim-cook-to-become-apple-executive-chairman-john-ternus-to-become-apple-ceo/",
      verifiedOn: "2026-09-02",
    },
    body: [
      "La versión oficial de cómo se hace una carrera en tecnología es que uno cambia de empresa cada tres o cuatro años, porque la lealtad no paga y el ascenso llega desde fuera. El <strong>1 de septiembre de 2026</strong> la empresa más valiosa del mundo hizo lo contrario.",
      "## La trayectoria",
      "<strong>John Ternus</strong> entró a Apple en <strong>2001</strong>. Veinticinco años después, sin haber salido, es su director ejecutivo. Llegó al puesto desde la <strong>vicepresidencia senior de Ingeniería de Hardware</strong>: el responsable de que el iPhone, el iPad, la Mac, el Apple Watch y los AirPods existan como objetos fabricables.",
      "No es un perfil de estratega ni de finanzas. Es el perfil de alguien que pasó un cuarto de siglo resolviendo problemas físicos con tolerancias medidas en fracciones de milímetro.",
      "## A quién sustituye",
      "<strong>Tim Cook</strong> dirigió Apple quince años y ahora es <strong>presidente ejecutivo</strong> del consejo. Su descripción del sucesor, textual: tiene «la mente de un ingeniero, el alma de un innovador y el corazón para dirigir con integridad».",
      "Cook también hizo una carrera larga dentro de la casa antes de llegar al puesto. Dos relevos seguidos resueltos desde adentro no son casualidad: son una política.",
      "## Lo que heredó",
      "Valor de mercado de cerca de <strong>4 billones de dólares</strong>, frente a unos <strong>350 mil millones</strong> en 2011. Ingresos de <strong>416 mil millones</strong> en el año fiscal 2025, contra <strong>108 mil millones</strong> en 2011. Más de <strong>100 000</strong> empleados sumados en el periodo y más de <strong>2 500 millones</strong> de dispositivos activos en <strong>más de 200 países y territorios</strong>.",
      "## Por qué la promoción interna es la parte interesante",
      "Una empresa que asciende desde dentro está diciendo que su conocimiento crítico no está escrito en ningún manual: vive en gente que lleva décadas ahí. Es una fortaleza y una fragilidad al mismo tiempo, y explica por qué el anuncio se hizo el <strong>20 de abril</strong> para una fecha efectiva del 1 de septiembre — cuatro meses y medio de aviso público para un traspaso que, en teoría, no requería ninguna presentación.",
      "La duda legítima es la contraria: veinticinco años dentro enseñan a no romper lo que funciona, y hay momentos en los que eso es exactamente lo que hace falta romper.",
    ],
    expertise:
      "Para leer un ascenso interno conviene mirar la <strong>función de origen</strong>, no los años. Un director general que viene de finanzas u operaciones optimiza lo que ya existe; uno que viene de ingeniería de producto suele defender el producto por encima del margen. Ternus viene de la segunda, y eso se notará primero en decisiones aburridas — materiales, reparabilidad, cuánto dura un modelo en catálogo — mucho antes que en un anuncio.",
  },
  {
    slug: "venecia-2026-una-sola-pelicula-latinoamericana",
    site: "mxo",
    image: "/covers/venecia-2026-una-sola-pelicula-latinoamericana.jpg",
    imageAlt: "Un campo de cuadros de papel color crema y uno solo en terracota, apartado del resto",
    imageKind: "generated",
    imageWidth: 1536,
    imageHeight: 864,
    title: "América Latina llega a Venecia con una sola película",
    cardTitle: "Una sola película latinoamericana",
    titleSeo: "Venecia 2026: una película latinoamericana",
    summary:
      "La 83ª Mostra abre el 2 de septiembre. En la competencia anunciada en julio hay veinte títulos y uno solo cruza el Atlántico desde este lado",
    date: "2026-09-01",
    category: "Cine",
    source: {
      name: "Screen International",
      url: "https://www.screendaily.com/news/venice-film-festival-reveals-2026-lineup/5218820.article",
      verifiedOn: "2026-09-01",
    },
    body: [
      "El dato no es que Venecia sea eurocéntrica. Eso ya se sabe. El dato es cuánto: de los veinte títulos que la Mostra anunció el <strong>23 de julio</strong> para su competencia, exactamente <strong>uno</strong> viene de América Latina",
      "## Cuál es",
      "<strong>Ritorno a Buenos Aires</strong>, de <strong>Marco Bechis</strong>, una coproducción argentino-italiana. No hay película mexicana en competencia",
      "Bechis es el caso raro que la estadística no captura bien: nació en Santiago, creció entre Argentina e Italia, y su cine lleva cuarenta años moviéndose entre las dos orillas. Contarlo como «una película latinoamericana» es correcto y también insuficiente",
      "## Qué es la 83ª Mostra",
      "El festival corre del <strong>2 al 12 de septiembre de 2026</strong> en el <strong>Lido</strong> de Venecia, con <strong>Alberto Barbera</strong> como director artístico. El jurado de la competencia lo preside <strong>Maggie Gyllenhaal</strong>, y lo integran Kaouther Ben Hania, Daniel Blumberg, Francesco Casetti, Xavier Giannoli, Shahrbanoo Sadat y Johnnie To",
      "Abre <strong>Ink</strong>, de <strong>Danny Boyle</strong>, con Guy Pearce. Cierra <strong>God Laughs</strong>, de Giovanni Veronesi. Los Leones de Oro honoríficos son para <strong>Ellen Burstyn</strong> y <strong>George Clooney</strong>",
      "## Lo demás de la lista",
      "En competencia también están Werner Herzog (<strong>Bucking Fastard</strong>), Martin McDonagh (<strong>Wild Horse Nine</strong>), Hirokazu Koreeda (<strong>Look Back</strong>), Lee Chang-dong (<strong>Possible Love</strong>), Nanni Moretti, Florian Zeller y Shinya Tsukamoto",
      "Barbera advirtió que esta selección trae películas largas. La más larga es <strong>Dau</strong>, de Ilya Khrzhanovsky: <strong>210 minutos</strong>",
      "## Por qué importa el conteo",
      "Venecia es la primera de las tres puertas de la temporada de premios, y por donde entra una película en septiembre suele decidirse qué distribuidor la compra y en cuántos países se estrena. Una sola presencia latinoamericana en competencia no es una opinión sobre el cine de la región: es una previsión bastante concreta de qué tan seguido va a poder verse en salas el año que viene",
    ],
    expertise:
      "La competencia no es todo el festival. Orizzonti, la Settimana della Critica y las Giornate degli Autori suelen concentrar más presencia latinoamericana que la sección principal, y son las secciones donde se compran los derechos de las óperas primas. Si el interés es qué cine de la región va a llegar a las salas, esa lista dice más que la de los veinte",
  },
  {
    slug: "kia-ev3-pesqueria-nuevo-leon",
    site: "mxo",
    image: "/covers/kia-ev3-pesqueria-nuevo-leon.jpg",
    imageAlt: "Un auto de papel recortado con una batería en el piso y un cable de carga en curva",
    imageKind: "generated",
    imageWidth: 1536,
    imageHeight: 864,
    title: "El primer KIA eléctrico hecho en México se fabricará en Pesquería",
    cardTitle: "El primer KIA eléctrico de México",
    titleSeo: "El primer KIA eléctrico de México",
    summary:
      "649 millones de dólares para producir el EV3 en Nuevo León. Es el primer vehículo eléctrico fabricado en la historia del estado",
    date: "2026-08-05",
    category: "Industria",
    source: {
      name: "El Universal",
      url: "https://www.eluniversal.com.mx/estados/nuevo-leon-fabricara-el-primer-kia-electrico-hecho-en-mexico-presentan-el-ev3-con-inversion-de-649-millones-de-dolares/",
      verifiedOn: "2026-09-01",
    },
    body: [
      "México lleva casi un siglo ensamblando autos para otros mercados. Lo que no había hecho en Nuevo León era fabricar uno eléctrico",
      "## La inversión",
      "KIA anunció <strong>649 millones de dólares</strong> para su planta de <strong>Pesquería, Nuevo León</strong>, destinados a producir el <strong>EV3</strong>, su primer vehículo eléctrico fabricado en México",
      "Con esto, la inversión acumulada de la armadora en Pesquería llega a alrededor de <strong>4 mil millones de dólares</strong>",
      "## Lo que ya hay en Pesquería",
      "La operación de KIA en el estado sostiene <strong>16 mil empleos directos</strong> y más de <strong>80 mil</strong> si se cuentan cadena de suministro y red de distribución. La planta recibió el <strong>Gold Plant Quality Award</strong> de J.D. Power en 2026",
      "El gobernador <strong>Samuel García</strong> adelantó además un polo industrial de <strong>220 hectáreas</strong> en Pesquería para KIA y sus proveedores",
      "## Por qué importa dónde se fabrica una batería",
      "Un auto eléctrico no se ensambla igual que uno de combustión. La línea cambia, el proveedor cambia y, sobre todo, cambia el peso relativo de la batería dentro del costo del vehículo. Un país que ensambla eléctricos sin fabricar celdas capta una porción del valor mucho menor que la que capta ensamblando de combustión",
      "Por eso el anuncio se lee mejor como un primer paso que como una llegada: la línea de EV3 en Pesquería pone a México en el mapa de la electromovilidad, y la pregunta siguiente — quién hace las celdas y dónde — sigue abierta",
      "## La frase",
      "García lo presentó en la Explanada del Palacio de Gobierno: «este producto va a ser un exitazo... es el símbolo de la electromovilidad». Por KIA México habló su presidente, <strong>Young Sam Kim</strong>",
    ],
    expertise:
      "El indicador a vigilar no es el monto sino el contenido regional. La regla de origen del T-MEC exige porcentajes altos de valor norteamericano para que un vehículo cruce sin arancel, y en un eléctrico ese cálculo lo domina la batería. De ahí depende que el EV3 hecho en Pesquería se exporte o se quede en el mercado interno",
  },
  {
    slug: "moderna-vacuna-melanoma-fase-3",
    featured: 1,
    site: "mxo",
    image: "/covers/moderna-vacuna-melanoma-fase-3.jpg",
    imageAlt: "Una jeringa de papel en diagonal junto a barras que suben, sobre la forma de un escudo",
    imageKind: "generated",
    imageWidth: 1536,
    imageHeight: 864,
    title: "La vacuna contra el melanoma sí funcionó",
    summary:
      "El ensayo de fase 3 de la vacuna individualizada de Moderna y Merck se detuvo antes de tiempo por buenos resultados: retrasa la recaída del melanoma operado. Es la primera vez que una vacuna de ARN mensajero contra el cáncer lo logra.",
    date: "2026-08-30",
    category: "Mundo",
    source: {
      name: "BioPharma Dive",
      url: "https://www.biopharmadive.com/news/moderna-merck-cancer-vaccine-landmark-result-melanoma/828238/",
      verifiedOn: "2026-08-30",
    },
    body: [
      "Un ensayo clínico que se detiene antes de tiempo casi siempre es una mala noticia. Éste se detuvo porque los resultados eran tan claros que seguir habría sido injusto para el grupo de control",
      "## Qué se probó",
      "El ensayo <strong>INTerpath-001</strong>, de <strong>fase 3</strong>, inscribió a <strong>1 137 personas</strong> a las que ya se les había extirpado quirúrgicamente un melanoma. Dos tercios recibieron <strong>intismeran</strong> — la vacuna individualizada de ARN mensajero de <strong>Moderna</strong> — junto con <strong>Keytruda</strong>, la inmunoterapia de Merck. El resto recibió sólo Keytruda",
      "El comité independiente que vigila el estudio encontró mejoras <em>estadísticamente significativas y clínicamente relevantes</em> en el grupo combinado, y autorizó terminar el ensayo en el análisis intermedio",
      "## Qué significa «individualizada»",
      "No es una vacuna que se fabrique en lotes. Se secuencia el tumor de cada paciente, se identifican hasta <strong>34 neoantígenos</strong> — proteínas mutadas que sólo aparecen en sus células cancerosas — y se fabrica un ARN mensajero que le enseña a su sistema inmune a reconocer esas 34 señales concretas",
      "Es decir: cada dosis existe para una sola persona. Ése es el logro y también el problema, porque es un modelo de producción que ninguna farmacéutica ha operado a gran escala",
      "## Lo que todavía no se sabe",
      "Las cifras. Las empresas anunciaron que el ensayo tuvo éxito pero <strong>no publicaron los datos detallados</strong>; se presentarán en un congreso médico sin fecha anunciada. Los analistas esperaban al menos un 20 por ciento de reducción del riesgo, y consideraban que entre 35 y 40 por ciento sería un resultado claramente diferenciado",
      "Tampoco hay ruta regulatoria anunciada, ni precio, ni plazo. Hay ensayos en marcha en cáncer de riñón, vejiga y pulmón",
      "## Por qué se está contando como un hito",
      "Porque es el <strong>primer ensayo aleatorizado de fase 3</strong> que demuestra el beneficio de este tipo de vacuna. Las vacunas terapéuticas contra el cáncer llevan décadas de resultados prometedores en fases tempranas que no se sostenían después. Ésta se sostuvo",
    ],
    expertise:
      "Conviene separar dos cosas que el anuncio junta. Que el ensayo funcionara es un hecho verificado por un comité independiente; cuánto funcionó es todavía una cifra que nadie fuera de las empresas ha visto. Hasta que se presenten los datos en un congreso, cualquier titular con un porcentaje viene de expectativas de analistas, no del estudio",
  },
  {
    slug: "record-temperatura-oceano-2026",
    site: "mxo",
    image: "/covers/record-temperatura-oceano-2026.jpg",
    imageAlt: "Olas de papel en capas que pasan del azul frío al naranja cálido hacia el frente",
    imageKind: "generated",
    imageWidth: 1536,
    imageHeight: 864,
    title: "El océano nunca había estado tan caliente",
    summary:
      "El 22 de agosto la temperatura media de la superficie del mar llegó a 21.1 °C, récord absoluto. Lo insólito es la fecha: agosto debería ser temporada de enfriamiento, no de máximos.",
    date: "2026-08-30",
    category: "Mundo",
    source: {
      name: "Al Jazeera",
      url: "https://www.aljazeera.com/news/2026/8/25/global-ocean-temperatures-hit-record-high-as-el-nino-intensifies",
      verifiedOn: "2026-08-30",
    },
    body: [
      "El récord no es el número. Es el mes",
      "## El dato",
      "El <strong>22 de agosto</strong> la temperatura media de la superficie del océano global alcanzó <strong>21.1 °C</strong>, según el servicio europeo <strong>Copernicus</strong>. El máximo anterior para un solo día era de <strong>21.09 °C</strong>, medido en <strong>marzo de 2024</strong>",
      "## Por qué la fecha importa más que la cifra",
      "El océano global tiene su propio calendario. Alcanza sus temperaturas más altas en <strong>marzo y abril</strong>, después del verano austral, porque el hemisferio sur tiene mucha más superficie de agua que de tierra. Agosto es, en ese ciclo, temporada de bajada",
      "Batir en agosto un récord que pertenecía a marzo significa que la curva entera se movió, no que hubo un día raro",
      "## El Niño encima",
      "La <strong>NOAA</strong> informó el <strong>13 de agosto</strong> que El Niño se está fortaleciendo, con más de <strong>90 por ciento</strong> de probabilidad de un evento muy fuerte durante el otoño e invierno boreales y hasta 2027. Para el trimestre <strong>octubre–diciembre</strong> calcula un <strong>69 por ciento</strong> de probabilidad de un evento que supere a todos los registrados desde <strong>1950</strong>",
      "> El Niño está añadiendo calor al sistema, pero lo hace encima de décadas de calentamiento provocado por el ser humano.\n— Samantha Burgess, responsable de estrategia climática en Copernicus",
      "Las dos cosas se suman y no se confunden: El Niño es un ciclo que va y viene cada pocos años; la línea base sobre la que oscila es la que subió",
      "## Qué falta por ver",
      "El agua seguirá calentándose hasta que El Niño llegue a su punto máximo, previsto entre <strong>noviembre y enero</strong>. Para México eso se traduce en una temporada de huracanes y un invierno que conviene mirar con el pronóstico en la mano y no con la memoria del año pasado",
    ],
    expertise:
      "El error de lectura más común con estos récords es tratarlos como noticia de un día. La cifra útil no es 21.1 sino la comparación con marzo de 2024: un récord estacionalmente imposible, batido fuera de temporada. Eso es lo que distingue una anomalía de una tendencia, y es también lo único que se puede afirmar hoy sin esperar al pico de El Niño",
  },
  {
    slug: "capuchinos-cazan-cuando-falta-fruta",
    site: "mxo",
    image: "/covers/capuchinos-cazan-cuando-falta-fruta.jpg",
    imageAlt: "Un mono en la rama de una selva de papel, con frutas de un lado y ninguna del otro",
    imageKind: "generated",
    imageWidth: 1536,
    imageHeight: 864,
    title: "Cuando falta fruta, estos monos cazan",
    summary:
      "Cinco mil horas de observación en Brasil registraron 446 casos de capuchinos comiendo vertebrados. Cazan más cuando escasea la fruta, y eso da una pista sobre cómo empezamos a comer carne.",
    date: "2026-08-30",
    category: "Mundo",
    source: {
      name: "Smithsonian Magazine",
      url: "https://www.smithsonianmag.com/smart-news/when-fruit-is-scarce-these-monkeys-hunt-animals-the-behavior-may-offer-clues-about-the-origins-of-humans-meat-eating-habits-180989412/",
      verifiedOn: "2026-08-30",
    },
    body: [
      "El dato no es que un mono coma carne. Es <em>cuándo</em>: los capuchinos barbados cazan más justo en la temporada en que la fruta escasea",
      "## El estudio",
      "Entre <strong>mayo de 2006 y diciembre de 2010</strong>, en la Fazenda Boa Vista, en el noreste de <strong>Brasil</strong>, un equipo acumuló más de <strong>5 000 horas de observación</strong> y registró <strong>446 episodios</strong> de capuchinos comiendo vertebrados. Se publicó el <strong>26 de agosto de 2026</strong> en <em>PLOS One</em>",
      "La lista de presas es larga: lagartijas, roedores, serpientes, tlacuaches, iguanas, murciélagos, aves, y huevos y polluelos. La mayoría son lagartijas y roedores — animales pequeños, atrapables por un primate de cuatro kilos",
      "## El patrón",
      "La caza aumenta cuando el alimento vegetal se vuelve estacionalmente escaso. Participan machos y hembras de todas las edades, aunque es más frecuente entre machos adultos y juveniles. Cuando logran una presa, empiezan por el cerebro y las vísceras — las partes con más grasa y nutrientes por bocado",
      "## Por qué importa para nosotros",
      "La pregunta de fondo en evolución humana no es por qué comemos carne, sino cómo empezamos. Cazar animales grandes exige herramientas, coordinación y una anatomía que los primeros homininos no tenían. Cazar una lagartija no exige nada de eso",
      "> Puede haber sido también el caso de los homininos.\n— Susana Carvalho, primatóloga, Parque Nacional de Gorongosa",
      "El equipo lo describe como <em>un escalón</em> hacia la explotación de presas mayores: primero lo pequeño, en la temporada mala, por necesidad; y sólo mucho después lo grande, por estrategia. La otra autora principal es Noemi Spagnoletti, bióloga de la conservación de la Universidad Sapienza de Roma",
      "## Lo que no dice el estudio",
      "No dice que los capuchinos sean un modelo de nuestros antepasados: son un linaje distinto que llegó por su cuenta a una solución parecida. Eso es precisamente lo que lo hace útil. Cuando dos linajes lejanos resuelven igual el mismo problema, el problema explica la solución mejor que el parentesco",
    ],
    expertise:
      "Cuatro años y medio de observación para 446 episodios da menos de un caso cada cuatro días. Es un recordatorio de qué tan raro es el comportamiento que estamos llamando decisivo — y de por qué hacían falta 5 000 horas para verlo. La mayoría de los estudios de campo que se citan en discusiones sobre evolución humana no tienen ni una décima parte de ese esfuerzo detrás",
  },
  {
    slug: "hirosaki-mil-ochocientas-personas-castillo",
    site: "mxo",
    image: "/covers/hirosaki-mil-ochocientas-personas-castillo.jpg",
    imageAlt: "La torre de un castillo japonés sobre rodillos, con una cuerda gruesa tendida hacia el borde",
    imageKind: "generated",
    imageWidth: 1536,
    imageHeight: 864,
    title: "1 800 personas movieron un castillo a mano",
    summary:
      "El torreón del castillo de Hirosaki pesa 400 toneladas y lleva once años fuera de su sitio. En agosto, 1 800 voluntarios elegidos por sorteo lo jalaron con cuerdas dos metros y medio de regreso.",
    date: "2026-08-30",
    category: "Mundo",
    source: {
      name: "Smithsonian Magazine",
      url: "https://www.smithsonianmag.com/smart-news/1800-people-pull-a-400-ton-japanese-castle-keep-back-toward-its-original-location-after-a-decade-of-restoration-work-180989401/",
      verifiedOn: "2026-08-30",
    },
    body: [
      "Hubo <strong>ocho mil solicitudes</strong> para <strong>1 800 lugares</strong>. No para un concierto ni para una rifa: para jalar un edificio con una cuerda.",
      "## Qué se movió",
      "El torreón del <strong>castillo de Hirosaki</strong>, en la prefectura de <strong>Aomori</strong>, al norte de Japón, pesa unas <strong>400 toneladas</strong>. Los días <strong>22 y 23 de agosto</strong> los voluntarios lo desplazaron algo más de <strong>dos metros</strong> en total — poco más de un metro el primer día, casi otro tanto el segundo — tirando de cuerdas, con apoyo de maquinaria. Lo que falta, unos <strong>73 metros</strong>, lo harán las máquinas",
      "## Por qué estaba fuera de lugar",
      "En <strong>2015</strong> el torreón fue apartado <strong>78 metros</strong> de su posición para poder reparar los muros de piedra sobre los que se levanta, dañados desde un sismo de <strong>1983</strong>. Se movió entonces con la técnica tradicional del <em>hikiya</em>, que desplaza edificios enteros sobre rodillos sin desarmarlos",
      "Es decir: el castillo no se restauró alrededor de un andamio. Se hizo a un lado, esperó once años a que el suelo bajo él estuviera arreglado, y ahora regresa. Reabrirá al público en <strong>2033</strong>",
      "## La parte que no era necesaria",
      "Nada obligaba a que lo movieran personas. Las máquinas podían hacerlo entero, y de hecho harán casi todo el trayecto. Los dos metros a mano fueron una decisión de la ciudad, y la respuesta la explica: ocho mil solicitudes, de Hirosaki, del resto de Japón y del extranjero",
      "> Unas ocho mil solicitudes para 1 800 lugares, no sólo de la ciudad, sino de todo Japón y del extranjero.\n— Kensuke Hayasaka, división de parques y áreas verdes de Hirosaki",
      "Uno de los participantes, Takahiro Kogawa, lo describió como intentar mover una montaña. Otra, Mei Umetsu, dijo sentirse conmovida por poder participar de nuevo — había estado también en el traslado de 2015",
      "## Por qué vale contarlo aquí",
      "Porque es una respuesta poco común a un problema común. Una obra de restauración de dieciocho años es, para la ciudad que la aloja, casi dos décadas de andamios y de un monumento que no se puede visitar. Hirosaki convirtió dos días de esa espera en un acto al que se apuntaron ocho mil personas",
    ],
    expertise:
      "El dato que conviene retener no son las 400 toneladas sino los dos metros. Es una fracción diminuta de un traslado de 78; el resto lo hacen máquinas. La ciudad no ahorró trabajo con los voluntarios: compró participación. Es una idea barata y trasladable a cualquier restauración larga, y no requiere un castillo",
  },
  {
    slug: "cova-de-les-dones-inscripciones-romanas",
    site: "mxo",
    image: "/covers/cova-de-les-dones-inscripciones-romanas.jpg",
    imageAlt: "La boca de una cueva recortada en capas de roca, con un pasaje que se pierde en la oscuridad",
    imageKind: "generated",
    imageWidth: 1536,
    imageHeight: 864,
    title: "La cueva valenciana de las mujeres romanas",
    summary:
      "A 200 metros de la entrada de la Cova de les Dones, en Valencia, hay 110 inscripciones latinas: la mayor concentración conocida en un santuario rupestre romano. Nombran a una diosa llamada sólo «la Señora».",
    date: "2026-08-30",
    category: "Mundo",
    source: {
      name: "Smithsonian Magazine",
      url: "https://www.smithsonianmag.com/smart-news/deep-inside-spanish-cave-roman-women-may-have-worshipped-mysterious-goddess-180989414/",
      verifiedOn: "2026-08-30",
    },
    body: [
      "El nombre de la cueva ya lo decía y nadie lo había podido demostrar. La <strong>Cova de les Dones</strong> — la cueva de las mujeres — está cerca de <strong>Millares</strong>, un pueblo del interior montañoso de <strong>Valencia</strong>, a unos 65 kilómetros de la capital",
      "## Lo que hay adentro",
      "A más de <strong>200 metros</strong> de la entrada, en una cámara a la que hay que llegar a oscuras, los investigadores documentaron al menos <strong>110 inscripciones latinas</strong> en paredes y techos. Es la mayor concentración conocida en un santuario rupestre romano",
      "Alrededor de ellas aparecieron anillos de bronce, joyería, vasijas en forma de cáliz, fragmentos de cerámica, huesos de animales y <strong>fusayolas</strong> — los contrapesos de los husos con los que se hilaba. También una moneda del reinado del emperador <strong>Claudio</strong>, que fecha el conjunto hace unos <strong>2 000 años</strong>",
      "## La diosa sin nombre",
      "Las inscripciones se dirigen a una deidad femenina a la que llaman <em>Domina</em>: «la Señora». En tres de ellas aparece la palabra <strong>MALACI</strong>, que el equipo describe como una designación de diosa hasta ahora desconocida y cuyo significado sigue en estudio",
      "## Por qué se cree que fueron mujeres",
      "Las fusayolas son el detalle que lo cambia todo. Hilar era trabajo de mujeres en el mundo romano, y encontrar sus herramientas depositadas como ofrenda, a doscientos metros bajo tierra, junto a inscripciones dirigidas a una diosa, es una coincidencia difícil de explicar de otro modo",
      "> Encajan con la evidencia epigráfica de la participación activa de mujeres en el santuario.\n— Virginia Barciela, arqueóloga de la Universidad de Alicante",
      "El equipo lo completan Silvia Alfayé Villa y Aitor Ruiz-Redondo, de la Universidad de Zaragoza, y Sergio García-Dils, de la UNED en Sevilla",
      "## Lo que no se sabe todavía",
      "Quién era <em>Domina</em>, si MALACI es un nombre, un epíteto o un topónimo, y por qué el culto se practicaba tan adentro. Doscientos metros de cueva no son un detalle logístico: significan bajar con lámpara de aceite, en fila, para dejar una ofrenda donde nadie más la vería",
    ],
    expertise:
      "La cueva llevaba siglos llamándose «de las mujeres» y era el tipo de topónimo que los arqueólogos suelen tratar como folclore tardío. Aquí resultó ser el resumen más corto del hallazgo. Vale como recordatorio de que el nombre de un sitio es un dato, aunque sea el último que se acepta como tal",
  },
  {
    slug: "telescopio-roman-lanzamiento",
    featured: 2,
    site: "mxo",
    image: "/covers/telescopio-roman-lanzamiento.jpg",
    imageAlt: "Un telescopio espacial de papel con un cono de visión muy amplio lleno de estrellas",
    imageKind: "generated",
    imageWidth: 1536,
    imageHeight: 864,
    title: "El telescopio Roman ya está en el espacio",
    summary:
      "La NASA lanzó el 30 de agosto el telescopio espacial Nancy Grace Roman: un campo de visión más de cien veces mayor que el del Hubble y las primeras imágenes previstas para diciembre.",
    date: "2026-08-30",
    category: "Mundo",
    source: {
      name: "Smithsonian Magazine",
      url: "https://www.smithsonianmag.com/smart-news/nasas-nancy-grace-roman-space-telescope-launches-to-find-exoplanets-and-unravel-mysteries-of-dark-matter-and-dark-energy-180989268/",
      verifiedOn: "2026-08-30",
    },
    body: [
      "Un mes de observaciones del Roman equivale a <strong>un siglo</strong> del Hubble mirando lo mismo. Ese solo dato explica para qué se construyó",
      "## El lanzamiento",
      "El <strong>telescopio espacial Nancy Grace Roman</strong> despegó el <strong>30 de agosto de 2026</strong> a las 7:26 de la mañana, hora del este, en un cohete <strong>Falcon Heavy</strong> de SpaceX desde el Centro Espacial Kennedy, en Florida. Pesa unas <strong>8 toneladas</strong> y mide cerca de <strong>13 metros de largo</strong> por cuatro de ancho",
      "Costó alrededor de <strong>4 300 millones de dólares</strong>, algo por debajo de lo presupuestado, y llegó al lanzamiento varios meses antes de lo previsto — dos frases que rara vez se escriben juntas sobre un observatorio espacial",
      "## Qué hace distinto",
      "Su instrumento principal es una cámara infrarroja de <strong>300 megapíxeles</strong> con la misma sensibilidad y nitidez que el Hubble, pero con un campo de visión <strong>al menos cien veces mayor</strong>. No ve más lejos: ve mucho más a la vez. Por eso puede recorrer el cielo unas <strong>mil veces más rápido</strong>",
      "## Qué va a buscar",
      "Tres grandes rastreos en <strong>cinco años</strong>: mapear <strong>una octava parte de todo el cielo</strong> con datos de más de <strong>mil millones de galaxias</strong>; vigilar explosiones estelares y objetos que cambian de brillo; y buscar planetas fuera del sistema solar hacia el centro de la galaxia. Llevará además un <strong>coronógrafo</strong> de 100 a 1 000 veces más potente que los anteriores, el aparato que tapa la luz de una estrella para que se vean los planetas a su alrededor",
      "Enviará cerca de <strong>un terabyte de datos al día</strong> desde el segundo punto de Lagrange, a un millón y medio de kilómetros de la Tierra, donde ya está el James Webb. Las <strong>primeras imágenes llegan en diciembre</strong>",
      "## Quién fue Nancy Grace Roman",
      "La primera mujer con un puesto ejecutivo en la NASA y su primera jefa de astronomía. Murió en <strong>2018</strong>. Se la llama la madre del Hubble porque fue quien defendió en los años sesenta, contra buena parte de su gremio, que valía la pena poner telescopios en el espacio",
    ],
    expertise:
      "El calendario es la parte útil para quien quiera seguirlo: las primeras imágenes son de diciembre, y los resultados que importan — energía oscura, exoplanetas — salen de rastreos de cinco años, no de una fotografía. Conviene esperar un anuncio bonito en diciembre y ciencia real hacia 2028",
  },
  {
    slug: "cuatro-cienegas-borrego-cimarron",
    site: "mxo",
    image: "/covers/cuatro-cienegas-borrego-cimarron.jpg",
    imageAlt: "Un borrego cimarrón en una loma del desierto, un bisonte al fondo y pozas de agua abajo",
    imageKind: "generated",
    imageWidth: 1536,
    imageHeight: 864,
    title: "Los bisontes funcionaron; ahora va el borrego",
    summary:
      "Cuarenta y siete bisontes devolvieron a Cuatro Ciénegas gato montés, pecaríes y venados. La siguiente pieza que la fundación quiere reponer es el borrego cimarrón: una manada fundacional de 12 a 15 ejemplares.",
    date: "2026-08-28",
    category: "Naturaleza",
    source: {
      name: "Milenio",
      url: "https://www.milenio.com/estados/borrego-cimarron-siguiente-introduccion-en-cuatro-cienegas-coahuila",
      verifiedOn: "2026-08-30",
    },
    body: [
      "La restauración ecológica suele medirse en promesas. En Cuatro Ciénegas se está midiendo en cámaras trampa, y lo que aparece en ellas es lo que nadie puso ahí.",
      "## Lo que pasó primero",
      "En el verano de <strong>2025</strong> llegaron a la reserva El Santuario los primeros <strong>tres bisontes americanos</strong>, procedentes del Museo del Desierto. En noviembre de ese año se sumaron otros <strong>44 ejemplares</strong>, y la manada quedó en <strong>47</strong>.",
      "A casi un año de la primera llegada, el monitoreo con cámaras trampa empezó a mostrar algo que no formaba parte del proyecto: la cadena alimentaria creció sola. Aparecieron <strong>gato montés</strong>, una manada de <strong>pecaríes</strong> y <strong>venados</strong>. Nadie los reintrodujo. Volvieron.",
      "## Por qué un bisonte trae un gato montés",
      "No es magia, es pasto. Un herbívoro grande que pace y se mueve cambia la altura y la composición de la vegetación, y con ella el suelo, la retención de agua y la cantidad de animales pequeños que pueden vivir ahí. Cuando hay más presa pequeña, aparece quien la caza. El bisonte no atrae al gato montés: le construye la despensa.",
      "Ese es el argumento entero de la reintroducción de especies clave, y es un argumento que casi siempre se defiende en teoría porque el resultado tarda décadas. Aquí tardó menos de un año en verse.",
      "## Lo que viene",
      "La <strong>Fundación Pro CuatroCiénegas</strong> quiere ahora al <strong>borrego cimarrón</strong>, una especie nativa de la zona. El plan que su director, Gerardo Ruiz Smith, describió a Milenio es una <strong>manada fundacional de entre 12 y 15 ejemplares</strong>, que en una primera etapa vivirá en un espacio protegido, con alimentación y cuidados controlados.",
      "El encierro no es un detalle administrativo: es la etapa que decide si el proyecto funciona. Los animales tienen que adaptarse al sitio y empezar a reproducirse antes de que se libere a nadie, y sólo conforme crezca la población se avanza gradualmente hacia la liberación dentro del predio.",
      "> Ya tenemos algunos fondos iniciales para empezar a planear y obtener los permisos para la infraestructura inicial que se estaría construyendo.\n— Gerardo Ruiz Smith, director de la Fundación Pro CuatroCiénegas, a Milenio",
      "Es una frase modesta y conviene leerla como está escrita: hay dinero para planear y para permisos, no para soltar borregos. La prioridad declarada de la fundación sigue siendo <strong>consolidar el proyecto del bisonte</strong> antes de concentrar esfuerzos en el siguiente.",
      "## Qué significa esto para quien quiera ir",
      "Cuatro Ciénegas es una reserva de la biosfera en el desierto de Coahuila, célebre por sus pozas de agua cristalina y por una biología que se estudia como análogo de vida temprana en la Tierra. Lo que cambia con este proyecto no es el paisaje, que ya era extraordinario, sino la probabilidad de ver fauna grande en él.",
      "Y cambia el tipo de visita. Una reserva con 47 bisontes y una cadena alimentaria en recuperación no se recorre igual que una laguna: se recorre despacio, temprano, y con la expectativa razonable de no ver nada. Esa es también la señal de que está funcionando.",
    ],
    expertise:
      "El dato que ordena todo lo demás es el orden de los factores. La fundación no reintrodujo depredadores ni presas: reintrodujo un herbívoro grande y esperó. Gato montés, pecaríes y venados llegaron por su cuenta. Un proyecto que hubiera empezado por soltar depredadores habría tenido titulares antes y resultados después — o ninguno.",
  },
  {
    slug: "tren-ligero-texcoco-la-paz",
    site: "mxo",
    image: "/covers/tren-ligero-texcoco-la-paz.jpg",
    imageAlt: "Una línea de tren ligero con estaciones marcadas y un tranvía al final, un lago detrás",
    imageKind: "generated",
    imageWidth: 1536,
    imageHeight: 864,
    title: "El tren de Texcoco: once estaciones, 30 minutos",
    summary:
      "El Edomex publicó el proyecto del Tren Ligero Texcoco–La Paz: 21 kilómetros, once estaciones, media hora de punta a punta contra los setenta minutos de hoy.",
    date: "2026-08-27",
    category: "Movilidad",
    source: {
      name: "Chilango",
      url: "https://www.chilango.com/noticias/transporte/publican-proyecto-tren-ligero-de-texcoco-a-la-paz-estaciones-trenes-tiempo-de-recorrido/",
      verifiedOn: "2026-08-30",
    },
    body: [
      "Un proyecto de transporte se vuelve real el día que publica su lista de estaciones. Antes de eso es una línea sobre un mapa; después es algo que se puede discutir casa por casa. El Tren Ligero Texcoco–La Paz acaba de cruzar esa frontera.",
      "El Gobierno del Estado de México publicó el proyecto en la plataforma <strong>Proyectos México</strong>, en etapa de preinversión, con un documento fechado el <strong>7 de agosto</strong>. El contrato que se licitará incluye obra civil y de sistemas, gestión ambiental y de urbanismo, y material rodante.",
      "## Las once estaciones",
      "De oriente a poniente: <strong>Texcoco, Autónoma de Chapingo, San Bernardino, Puerta Texcoco, Central de Abasto, Piedras Negras, Francisco Villa, Conalep Los Reyes, La Magdalena, Los Reyes y La Paz</strong>.",
      "Los dos extremos importan por razones distintas. En Texcoco, la terminal se ubicará en la <strong>antigua estación del ferrocarril México–Veracruz</strong>, sobre la calle Nezahualcóyotl, en el barrio de San Juanito — es decir, el tren regresa a un edificio que ya fue estación. En el poniente, la línea termina en <strong>Metro La Paz</strong>, cabecera de la Línea A, que es lo que convierte a esto en algo más que un tren local: conecta a Texcoco, Chimalhuacán y Nezahualcóyotl con la red del Metro de la Ciudad de México.",
      "## Los números",
      "<strong>21 kilómetros</strong> de longitud. <strong>30 minutos</strong> de terminal a terminal, contra los setenta que hoy toma el mismo trayecto: una reducción superior al <strong>50% del tiempo</strong>. Velocidad comercial de <strong>41 km/h</strong>, máxima de 80.",
      "El material rodante son <strong>14 trenes dobles</strong> — para comparar, el Tren Ligero de la Ciudad de México opera con cerca de 20 trenes dobles acoplados. La demanda que se busca cubrir con esos catorce es de <strong>127 mil usuarios al día</strong>.",
      "## El detalle que casi nadie está mirando",
      "La línea será de <strong>operación mixta</strong>: conviven servicio de carga y de pasajeros. Lo anunció la Secretaría de Movilidad mexiquense desde enero, y es la decisión más consecuente del proyecto.",
      "Una línea mixta cambia todo lo demás. Cambia el diseño de la vía, cambia la frecuencia posible para el pasajero, cambia el mantenimiento y cambia las ventanas horarias en que cada servicio puede circular. Explica también por qué la velocidad comercial se fija en 41 km/h y no más alta. No es un pero: es la razón por la que un proyecto de este tamaño resulta financiable en el oriente del Estado de México, donde la carga ya existe y el pasajero, hasta ahora, viaja en camión.",
      "## Lo que falta",
      "Preinversión significa que hay proyecto y no hay obra. Falta la licitación, falta el contrato y faltan las fechas. Aquí no aparece un año de inauguración porque nadie lo ha publicado, y una lista de estaciones no es un calendario.",
      "Lo que sí es firme es la geometría: once estaciones, dos terminales identificadas con dirección, y una conexión con la Línea A que define para quién se está construyendo.",
    ],
    expertise:
      "El ahorro real no son los 40 minutos del tren. Es que el trayecto Texcoco–Metro se vuelve predecible: hoy depende del tráfico de la carretera y por eso su duración varía entre un día y otro más de lo que dura el viaje en sí. Un tren de 30 minutos vale menos por rápido que por igual todos los días.",
  },
  {
    slug: "filij-2026-regresa-al-cenart",
    site: "mxo",
    image: "/covers/filij-2026-regresa-al-cenart.jpg",
    imageAlt: "Un libro abierto que se convierte en una carpa de papel, rodeado de animales de papel doblado",
    imageKind: "generated",
    imageWidth: 1536,
    imageHeight: 864,
    title: "La FILIJ regresa al CENART con entrada gratuita",
    summary:
      "La 44 edición de la Feria Internacional del Libro Infantil y Juvenil será del 13 al 22 de noviembre en el CENART, con entrada gratuita y convocatoria abierta para visitas escolares.",
    date: "2026-08-28",
    category: "Ferias",
    source: {
      name: "Excélsior",
      url: "https://www.excelsior.com.mx/cultura/filij-2026-regresa-cenart-con-entrada-gratuita-fechas",
      verifiedOn: "2026-08-30",
    },
    body: [
      "Una feria del libro para niños se mide por una cosa: cuántos de los que entran salen leyendo algo que eligieron ellos. La FILIJ lleva 44 ediciones construida alrededor de esa idea, y la de 2026 vuelve al mismo sitio y con el mismo precio — ninguno.",
      "## Fechas y sede",
      "De acuerdo con el <strong>Fondo de Cultura Económica</strong>, la <strong>44 edición</strong> de la Feria Internacional del Libro Infantil y Juvenil se realizará del <strong>13 al 22 de noviembre</strong> en el <strong>Centro Nacional de las Artes</strong>. La <strong>entrada es gratuita</strong>.",
      "El FCE abrió además una <strong>convocatoria para visitas escolares</strong>, cuyos detalles se consultan por sus canales oficiales. Ese es el mecanismo por el que la feria llega a los niños que no habrían ido en fin de semana con la familia.",
      "## Qué es, más allá de los libros",
      "La FILIJ reúne editoriales, escritores, ilustradores y familias. La oferta editorial va del cuento ilustrado a la novela juvenil y el libro informativo, para todas las edades.",
      "Pero la feria no es una venta de libros con actividades encima. La programación cultural suele incluir <strong>cuentacuentos, talleres creativos, presentaciones de libros, teatro, música y danza</strong> — y en la práctica ésa es la parte que convierte una visita en una costumbre.",
      "La distinción importa para quien va con niños pequeños: se puede pasar una mañana completa sin comprar nada y que el día haya valido.",
      "## Cómo llegar",
      "El CENART está en <strong>Avenida Río Churubusco 79</strong>, colonia Country Club Churubusco, alcaldía Coyoacán.",
      "En transporte público, las estaciones de Metro más cercanas son <strong>General Anaya</strong> (Línea 2) y <strong>Ermita</strong> (Línea 12). De cualquiera de las dos son <strong>de 8 a 10 minutos caminando</strong>.",
      "## Y si ya se está ahí",
      "El CENART mantiene cartelera todo el año, con espectáculos, talleres y actividades infantiles. Noviembre es cuando el recinto se llena de niños, pero no es el único mes en que programa para ellos.",
    ],
    expertise:
      "Diez días es mucha feria y el error habitual es ir el primer o el último fin de semana. Entre semana la FILIJ se vacía de familias y se llena de grupos escolares en horario de mañana; una tarde de martes o miércoles es, con diferencia, el momento en que un niño puede acercarse a una mesa y hojear sin cola.",
  },
  {
    slug: "kusama-320-mil-visitantes",
    site: "mxo",
    image: "/covers/kusama-320-mil-visitantes.jpg",
    imageAlt: "Un campo denso de círculos de papel de todos los tamaños con una sala espejada al centro",
    imageKind: "generated",
    imageWidth: 1536,
    imageHeight: 864,
    title: "Kusama pasó de 320 mil visitantes",
    summary:
      "Más de 320 mil personas vieron «Obsesión Infinita» en el Museo Tamayo entre 2014 y 2015. Al final el museo abrió 36 horas seguidas y casi 10 mil personas entraron en ese maratón.",
    date: "2026-08-27",
    category: "Arte",
    source: {
      name: "El Universal Cultura",
      url: "https://www.eluniversal.com.mx/cultura/la-exposicion-de-yayoi-kusama-que-obsesiono-a-mexico/",
      verifiedOn: "2026-08-30",
    },
    body: [
      "Hubo una fila en Reforma que la gente aguantó acampando. No era por un concierto: era por una exposición de arte contemporáneo, en un museo público, un miércoles cualquiera de enero.",
      "## Los números",
      "<strong>«Obsesión Infinita»</strong>, de la artista japonesa <strong>Yayoi Kusama</strong>, se inauguró el <strong>26 de septiembre de 2014</strong> en el <strong>Museo Tamayo</strong> y cerró el <strong>18 de enero de 2015</strong>. Recibió a más de <strong>320 mil personas</strong>, según cifras del gobierno mexicano.",
      "Fue la primera retrospectiva de Kusama en América Latina, y la primera vez que se registraba esa cantidad de visitantes en una exposición en México.",
      "Conforme se acercaba el cierre, la fila creció hasta que el museo hizo lo que casi ningún museo hace: <strong>abrir 36 horas seguidas</strong>. En ese maratón final se registraron <strong>casi 10 mil personas</strong>.",
      "## Qué había adentro",
      "Más de <strong>100 obras creadas entre 1950 y 2013</strong>. Piezas de la serie <em>Infinity net</em>, la película <em>Kusama’s Self-Obliteration</em>, y las instalaciones <em>Phalli’s field</em>, <em>Obliteration room</em> e <em>Infinity mirror room</em>.",
      "Esas tres instalaciones explican buena parte de la fila. Son obras que no se ven: se entra en ellas, de una persona a la vez o de tres en tres. El aforo por hora de una <em>Infinity mirror room</em> es minúsculo por diseño, y eso convierte cualquier éxito de público en una cola.",
      "## No fue sólo México",
      "La exposición fue organizada por el museo <strong>Malba</strong> de Buenos Aires, donde convocó a <strong>180 mil asistentes</strong> y terminó con las calles vecinas decoradas con lunares. También pasó por Río de Janeiro, Brasilia y São Paulo, y de México viajó a Chile.",
      "Visto así, el dato mexicano se lee mejor: 320 mil contra 180 mil en la ciudad que la organizó.",
      "## La artista",
      "Kusama nació en <strong>Matsumoto en 1929</strong> y murió este año. Se mudó a Nueva York en <strong>1957</strong> y siguió pintando puntos en obras hechas de seriación y repetición; fue amiga de Andy Warhol y Georgia O’Keeffe. Su trabajo llegó al MoMA de Nueva York, al Museo Ludwig en Alemania y a la Tate Modern de Londres, y en <strong>2016</strong> recibió la <strong>Orden de la Cultura</strong>, el premio más prestigioso que Japón otorga a sus artistas.",
      "Decía que dibujaba como veía el mundo: cubierto de manchas.",
    ],
    expertise:
      "El maratón de 36 horas es el dato que suelen citar mal. No fue un truco de mercadotecnia al inicio, fue una respuesta al final: el museo abrió de corrido porque la fila ya no cabía en los días que quedaban. Vale como advertencia práctica para cualquier exposición muy esperada — el mes barato para verla es el primero, no el último.",
  },
  {
    slug: "john-giorno-en-kurimanzutto",
    site: "mxo",
    image: "/covers/john-giorno-en-kurimanzutto.jpg",
    imageAlt: "Un teléfono de disco montado en una pared de galería, con discos de vinilo y una tira de papel",
    imageKind: "generated",
    imageWidth: 1536,
    imageHeight: 864,
    title: "kurimanzutto recibe la obra poética de John Giorno",
    cardTitle: "kurimanzutto recibe a John Giorno",
    summary:
      "Poesía en los muros, en vinilos que el visitante elige, en un video de diez horas y en un teléfono. La primera individual de John Giorno en la Ciudad de México está en kurimanzutto hasta el 10 de octubre.",
    date: "2026-08-26",
    category: "Arte",
    source: {
      name: "El Universal Cultura",
      url: "https://www.eluniversal.com.mx/cultura/galeria-kurimanzutto-recibe-la-obra-poetica-del-artista-john-giorno/",
      verifiedOn: "2026-08-30",
    },
    body: [
      "Hay una línea telefónica en la librería de kurimanzutto. Se levanta el auricular y alguien recita. No hay menú, no hay espera: la poesía ya está sonando y uno se incorpora a la mitad.",
      "Es <em>Dial-A-Poem</em>, la obra más famosa de <strong>John Giorno</strong> (1936–2019), exhibida por primera vez en el <strong>MoMA</strong> de Nueva York en <strong>1970</strong>, y es la mejor puerta de entrada a lo que la galería montó.",
      "## La primera individual en la ciudad",
      "<strong>John Giorno: LIFE IS A KILLER</strong> es la primera exposición individual del artista, activista y poeta en la <strong>Ciudad de México</strong>. Reúne sus obras poéticas más representativas, desde los primeros trabajos hasta piezas de sus últimas series, de <strong>2015</strong>.",
      "Giorno fue contemporáneo de Andy Warhol y William S. Burroughs, y su idea rectora era simple y radical: la poesía no debía existir sólo en la página.",
      "> Era fiel creyente de que la poesía no debía existir sólo en la página, sino que era tan esencial para la comunicación de la humanidad, por lo que podía y debía existir en el mundo.\n— Corinna Durland, directora de la sede neoyorquina de kurimanzutto",
      "Por eso en la sala se puede <strong>leer</strong> poesía en los muros y <strong>oírla</strong> en un disco de vinilo, en un <strong>video de más de diez horas</strong> realizado por <strong>Rirkrit Tiravanija</strong>, o por teléfono.",
      "## Los cuadros que son frases",
      "Están las <em>Poem paintings</em>, iniciadas en Italia en los años setenta y punto de partida de su pintura. Llevan versos como «Everything is delusion including wisdom», «Everyone gets lighter», «Filling what is empty, emptying what is full» y el que da título a la muestra, «Life is a killer».",
      "La mayoría son en blanco y negro, con una <strong>tipografía diseñada para él por Mark Michaelson en 1984</strong>. Las de fondo de arcoíris son de <strong>2015</strong> en adelante, hechas como gesto de apoyo a la libertad de las personas LGBT.",
      "También se exhibe una de sus obras más tempranas: un poema inspirado en el juicio de Bobby Seale, cofundador de las Panteras Negras.",
      "## El corazón: los vinilos",
      "El galerista lo llama así, y es literal. Giorno grabó bajo su propio sello discos con poemas y canciones hechos junto a sus amigos, entre ellos <strong>Debbie Harry</strong> y <strong>Patti Smith</strong>. Los vinilos pueden reproducirse dentro de la galería, y es <strong>el visitante quien elige cuál suena</strong>.",
      "Esa decisión curatorial hace mucho más de lo que parece: convierte a quien entra en programador de la sala. La exposición suena distinta según quién esté adentro.",
      "## La parte hecha para México",
      "El galerista José Kuri contó que al planear la muestra se preguntaron cómo conectar el trabajo del estadounidense con México. La respuesta fue un <strong>taller de traducción</strong> de sus poemas al español, en colaboración con la librería <strong>La Americana</strong>, que se publicará en un fanzine. Participan <strong>Brenda Lozano, Carla Faesler, Paloma Contreras, Isabel Zapata y Mateo Díaz Choza</strong>.",
      "## Dónde y hasta cuándo",
      "La muestra estará <strong>hasta el 10 de octubre</strong> en <strong>Gob. Rafael Rebollar 94, San Miguel Chapultepec</strong>.",
    ],
    expertise:
      "Hay que reservar tiempo para el teléfono y los vinilos, que es donde la exposición realmente pasa y donde nadie se detiene. Una sala de poesía se recorre por instinto como se recorre una de pintura — leyendo los muros y saliendo —, y así se pierde exactamente la mitad de la obra: la que suena.",
  },
];
