import type { NewsItem } from "../types.ts";

export const items: NewsItem[] = [
  {
    slug: "moderna-vacuna-melanoma-fase-3",
    featured: 1,
    site: "mxo",
    image: "/covers/moderna-vacuna-melanoma-fase-3.jpg",
    imageAlt: "Una jeringa de papel en diagonal junto a barras que suben, sobre la forma de un escudo",
    imageKind: "generated",
    imageWidth: 1536,
    imageHeight: 864,
    title: "La vacuna contra el melanoma sí funcionó",
    summary:
      "El ensayo de fase 3 de la vacuna individualizada de Moderna y Merck se detuvo antes de tiempo por buenos resultados: retrasa la recaída del melanoma operado. Es la primera vez que una vacuna de ARN mensajero contra el cáncer lo logra.",
    date: "2026-08-30",
    category: "Mundo",
    source: {
      name: "BioPharma Dive",
      url: "https://www.biopharmadive.com/news/moderna-merck-cancer-vaccine-landmark-result-melanoma/828238/",
      verifiedOn: "2026-08-30",
    },
    body: [
      "Un ensayo clínico que se detiene antes de tiempo casi siempre es una mala noticia. Éste se detuvo porque los resultados eran tan claros que seguir habría sido injusto para el grupo de control",
      "## Qué se probó",
      "El ensayo <strong>INTerpath-001</strong>, de <strong>fase 3</strong>, inscribió a <strong>1 137 personas</strong> a las que ya se les había extirpado quirúrgicamente un melanoma. Dos tercios recibieron <strong>intismeran</strong> &mdash; la vacuna individualizada de ARN mensajero de <strong>Moderna</strong> &mdash; junto con <strong>Keytruda</strong>, la inmunoterapia de Merck. El resto recibió sólo Keytruda",
      "El comité independiente que vigila el estudio encontró mejoras <em>estadísticamente significativas y clínicamente relevantes</em> en el grupo combinado, y autorizó terminar el ensayo en el análisis intermedio",
      "## Qué significa «individualizada»",
      "No es una vacuna que se fabrique en lotes. Se secuencia el tumor de cada paciente, se identifican hasta <strong>34 neoantígenos</strong> &mdash; proteínas mutadas que sólo aparecen en sus células cancerosas &mdash; y se fabrica un ARN mensajero que le enseña a su sistema inmune a reconocer esas 34 señales concretas",
      "Es decir: cada dosis existe para una sola persona. Ése es el logro y también el problema, porque es un modelo de producción que ninguna farmacéutica ha operado a gran escala",
      "## Lo que todavía no se sabe",
      "Las cifras. Las empresas anunciaron que el ensayo tuvo éxito pero <strong>no publicaron los datos detallados</strong>; se presentarán en un congreso médico sin fecha anunciada. Los analistas esperaban al menos un 20 por ciento de reducción del riesgo, y consideraban que entre 35 y 40 por ciento sería un resultado claramente diferenciado",
      "Tampoco hay ruta regulatoria anunciada, ni precio, ni plazo. Hay ensayos en marcha en cáncer de riñón, vejiga y pulmón",
      "## Por qué se está contando como un hito",
      "Porque es el <strong>primer ensayo aleatorizado de fase 3</strong> que demuestra el beneficio de este tipo de vacuna. Las vacunas terapéuticas contra el cáncer llevan décadas de resultados prometedores en fases tempranas que no se sostenían después. Ésta se sostuvo",
    ],
    expertise:
      "Conviene separar dos cosas que el anuncio junta. Que el ensayo funcionara es un hecho verificado por un comité independiente; cuánto funcionó es todavía una cifra que nadie fuera de las empresas ha visto. Hasta que se presenten los datos en un congreso, cualquier titular con un porcentaje viene de expectativas de analistas, no del estudio",
  },
  {
    slug: "record-temperatura-oceano-2026",
    site: "mxo",
    image: "/covers/record-temperatura-oceano-2026.jpg",
    imageAlt: "Olas de papel en capas que pasan del azul frío al naranja cálido hacia el frente",
    imageKind: "generated",
    imageWidth: 1536,
    imageHeight: 864,
    title: "El océano nunca había estado tan caliente",
    summary:
      "El 22 de agosto la temperatura media de la superficie del mar llegó a 21.1 °C, récord absoluto. Lo insólito es la fecha: agosto debería ser temporada de enfriamiento, no de máximos.",
    date: "2026-08-30",
    category: "Mundo",
    source: {
      name: "Al Jazeera",
      url: "https://www.aljazeera.com/news/2026/8/25/global-ocean-temperatures-hit-record-high-as-el-nino-intensifies",
      verifiedOn: "2026-08-30",
    },
    body: [
      "El récord no es el número. Es el mes",
      "## El dato",
      "El <strong>22 de agosto</strong> la temperatura media de la superficie del océano global alcanzó <strong>21.1 °C</strong>, según el servicio europeo <strong>Copernicus</strong>. El máximo anterior para un solo día era de <strong>21.09 °C</strong>, medido en <strong>marzo de 2024</strong>",
      "## Por qué la fecha importa más que la cifra",
      "El océano global tiene su propio calendario. Alcanza sus temperaturas más altas en <strong>marzo y abril</strong>, después del verano austral, porque el hemisferio sur tiene mucha más superficie de agua que de tierra. Agosto es, en ese ciclo, temporada de bajada",
      "Batir en agosto un récord que pertenecía a marzo significa que la curva entera se movió, no que hubo un día raro",
      "## El Niño encima",
      "La <strong>NOAA</strong> informó el <strong>13 de agosto</strong> que El Niño se está fortaleciendo, con más de <strong>90 por ciento</strong> de probabilidad de un evento muy fuerte durante el otoño e invierno boreales y hasta 2027. Para el trimestre <strong>octubre&ndash;diciembre</strong> calcula un <strong>69 por ciento</strong> de probabilidad de un evento que supere a todos los registrados desde <strong>1950</strong>",
      "> El Niño está añadiendo calor al sistema, pero lo hace encima de décadas de calentamiento provocado por el ser humano.\n— Samantha Burgess, responsable de estrategia climática en Copernicus",
      "Las dos cosas se suman y no se confunden: El Niño es un ciclo que va y viene cada pocos años; la línea base sobre la que oscila es la que subió",
      "## Qué falta por ver",
      "El agua seguirá calentándose hasta que El Niño llegue a su punto máximo, previsto entre <strong>noviembre y enero</strong>. Para México eso se traduce en una temporada de huracanes y un invierno que conviene mirar con el pronóstico en la mano y no con la memoria del año pasado",
    ],
    expertise:
      "El error de lectura más común con estos récords es tratarlos como noticia de un día. La cifra útil no es 21.1 sino la comparación con marzo de 2024: un récord estacionalmente imposible, batido fuera de temporada. Eso es lo que distingue una anomalía de una tendencia, y es también lo único que se puede afirmar hoy sin esperar al pico de El Niño",
  },
  {
    slug: "capuchinos-cazan-cuando-falta-fruta",
    site: "mxo",
    image: "/covers/capuchinos-cazan-cuando-falta-fruta.jpg",
    imageAlt: "Un mono en la rama de una selva de papel, con frutas de un lado y ninguna del otro",
    imageKind: "generated",
    imageWidth: 1536,
    imageHeight: 864,
    title: "Cuando falta fruta, estos monos cazan",
    summary:
      "Cinco mil horas de observación en Brasil registraron 446 casos de capuchinos comiendo vertebrados. Cazan más cuando escasea la fruta, y eso da una pista sobre cómo empezamos a comer carne.",
    date: "2026-08-30",
    category: "Mundo",
    source: {
      name: "Smithsonian Magazine",
      url: "https://www.smithsonianmag.com/smart-news/when-fruit-is-scarce-these-monkeys-hunt-animals-the-behavior-may-offer-clues-about-the-origins-of-humans-meat-eating-habits-180989412/",
      verifiedOn: "2026-08-30",
    },
    body: [
      "El dato no es que un mono coma carne. Es <em>cuándo</em>: los capuchinos barbados cazan más justo en la temporada en que la fruta escasea",
      "## El estudio",
      "Entre <strong>mayo de 2006 y diciembre de 2010</strong>, en la Fazenda Boa Vista, en el noreste de <strong>Brasil</strong>, un equipo acumuló más de <strong>5 000 horas de observación</strong> y registró <strong>446 episodios</strong> de capuchinos comiendo vertebrados. Se publicó el <strong>26 de agosto de 2026</strong> en <em>PLOS One</em>",
      "La lista de presas es larga: lagartijas, roedores, serpientes, tlacuaches, iguanas, murciélagos, aves, y huevos y polluelos. La mayoría son lagartijas y roedores &mdash; animales pequeños, atrapables por un primate de cuatro kilos",
      "## El patrón",
      "La caza aumenta cuando el alimento vegetal se vuelve estacionalmente escaso. Participan machos y hembras de todas las edades, aunque es más frecuente entre machos adultos y juveniles. Cuando logran una presa, empiezan por el cerebro y las vísceras &mdash; las partes con más grasa y nutrientes por bocado",
      "## Por qué importa para nosotros",
      "La pregunta de fondo en evolución humana no es por qué comemos carne, sino cómo empezamos. Cazar animales grandes exige herramientas, coordinación y una anatomía que los primeros homininos no tenían. Cazar una lagartija no exige nada de eso",
      "> Puede haber sido también el caso de los homininos.\n— Susana Carvalho, primatóloga, Parque Nacional de Gorongosa",
      "El equipo lo describe como <em>un escalón</em> hacia la explotación de presas mayores: primero lo pequeño, en la temporada mala, por necesidad; y sólo mucho después lo grande, por estrategia. La otra autora principal es Noemi Spagnoletti, bióloga de la conservación de la Universidad Sapienza de Roma",
      "## Lo que no dice el estudio",
      "No dice que los capuchinos sean un modelo de nuestros antepasados: son un linaje distinto que llegó por su cuenta a una solución parecida. Eso es precisamente lo que lo hace útil. Cuando dos linajes lejanos resuelven igual el mismo problema, el problema explica la solución mejor que el parentesco",
    ],
    expertise:
      "Cuatro años y medio de observación para 446 episodios da menos de un caso cada cuatro días. Es un recordatorio de qué tan raro es el comportamiento que estamos llamando decisivo &mdash; y de por qué hacían falta 5 000 horas para verlo. La mayoría de los estudios de campo que se citan en discusiones sobre evolución humana no tienen ni una décima parte de ese esfuerzo detrás",
  },
  {
    slug: "hirosaki-mil-ochocientas-personas-castillo",
    site: "mxo",
    image: "/covers/hirosaki-mil-ochocientas-personas-castillo.jpg",
    imageAlt: "La torre de un castillo japonés sobre rodillos, con una cuerda gruesa tendida hacia el borde",
    imageKind: "generated",
    imageWidth: 1536,
    imageHeight: 864,
    title: "1 800 personas movieron un castillo a mano",
    summary:
      "El torreón del castillo de Hirosaki pesa 400 toneladas y lleva once años fuera de su sitio. En agosto, 1 800 voluntarios elegidos por sorteo lo jalaron con cuerdas dos metros y medio de regreso.",
    date: "2026-08-30",
    category: "Mundo",
    source: {
      name: "Smithsonian Magazine",
      url: "https://www.smithsonianmag.com/smart-news/1800-people-pull-a-400-ton-japanese-castle-keep-back-toward-its-original-location-after-a-decade-of-restoration-work-180989401/",
      verifiedOn: "2026-08-30",
    },
    body: [
      "Hubo <strong>ocho mil solicitudes</strong> para <strong>1 800 lugares</strong>. No para un concierto ni para una rifa: para jalar un edificio con una cuerda.",
      "## Qué se movió",
      "El torreón del <strong>castillo de Hirosaki</strong>, en la prefectura de <strong>Aomori</strong>, al norte de Japón, pesa unas <strong>400 toneladas</strong>. Los días <strong>22 y 23 de agosto</strong> los voluntarios lo desplazaron algo más de <strong>dos metros</strong> en total &mdash; poco más de un metro el primer día, casi otro tanto el segundo &mdash; tirando de cuerdas, con apoyo de maquinaria. Lo que falta, unos <strong>73 metros</strong>, lo harán las máquinas",
      "## Por qué estaba fuera de lugar",
      "En <strong>2015</strong> el torreón fue apartado <strong>78 metros</strong> de su posición para poder reparar los muros de piedra sobre los que se levanta, dañados desde un sismo de <strong>1983</strong>. Se movió entonces con la técnica tradicional del <em>hikiya</em>, que desplaza edificios enteros sobre rodillos sin desarmarlos",
      "Es decir: el castillo no se restauró alrededor de un andamio. Se hizo a un lado, esperó once años a que el suelo bajo él estuviera arreglado, y ahora regresa. Reabrirá al público en <strong>2033</strong>",
      "## La parte que no era necesaria",
      "Nada obligaba a que lo movieran personas. Las máquinas podían hacerlo entero, y de hecho harán casi todo el trayecto. Los dos metros a mano fueron una decisión de la ciudad, y la respuesta la explica: ocho mil solicitudes, de Hirosaki, del resto de Japón y del extranjero",
      "> Unas ocho mil solicitudes para 1 800 lugares, no sólo de la ciudad, sino de todo Japón y del extranjero.\n— Kensuke Hayasaka, división de parques y áreas verdes de Hirosaki",
      "Uno de los participantes, Takahiro Kogawa, lo describió como intentar mover una montaña. Otra, Mei Umetsu, dijo sentirse conmovida por poder participar de nuevo &mdash; había estado también en el traslado de 2015",
      "## Por qué vale contarlo aquí",
      "Porque es una respuesta poco común a un problema común. Una obra de restauración de dieciocho años es, para la ciudad que la aloja, casi dos décadas de andamios y de un monumento que no se puede visitar. Hirosaki convirtió dos días de esa espera en un acto al que se apuntaron ocho mil personas",
    ],
    expertise:
      "El dato que conviene retener no son las 400 toneladas sino los dos metros. Es una fracción diminuta de un traslado de 78; el resto lo hacen máquinas. La ciudad no ahorró trabajo con los voluntarios: compró participación. Es una idea barata y trasladable a cualquier restauración larga, y no requiere un castillo",
  },
  {
    slug: "cova-de-les-dones-inscripciones-romanas",
    site: "mxo",
    image: "/covers/cova-de-les-dones-inscripciones-romanas.jpg",
    imageAlt: "La boca de una cueva recortada en capas de roca, con un pasaje que se pierde en la oscuridad",
    imageKind: "generated",
    imageWidth: 1536,
    imageHeight: 864,
    title: "La cueva valenciana de las mujeres romanas",
    summary:
      "A 200 metros de la entrada de la Cova de les Dones, en Valencia, hay 110 inscripciones latinas: la mayor concentración conocida en un santuario rupestre romano. Nombran a una diosa llamada sólo «la Señora».",
    date: "2026-08-30",
    category: "Mundo",
    source: {
      name: "Smithsonian Magazine",
      url: "https://www.smithsonianmag.com/smart-news/deep-inside-spanish-cave-roman-women-may-have-worshipped-mysterious-goddess-180989414/",
      verifiedOn: "2026-08-30",
    },
    body: [
      "El nombre de la cueva ya lo decía y nadie lo había podido demostrar. La <strong>Cova de les Dones</strong> &mdash; la cueva de las mujeres &mdash; está cerca de <strong>Millares</strong>, un pueblo del interior montañoso de <strong>Valencia</strong>, a unos 65 kilómetros de la capital",
      "## Lo que hay adentro",
      "A más de <strong>200 metros</strong> de la entrada, en una cámara a la que hay que llegar a oscuras, los investigadores documentaron al menos <strong>110 inscripciones latinas</strong> en paredes y techos. Es la mayor concentración conocida en un santuario rupestre romano",
      "Alrededor de ellas aparecieron anillos de bronce, joyería, vasijas en forma de cáliz, fragmentos de cerámica, huesos de animales y <strong>fusayolas</strong> &mdash; los contrapesos de los husos con los que se hilaba. También una moneda del reinado del emperador <strong>Claudio</strong>, que fecha el conjunto hace unos <strong>2 000 años</strong>",
      "## La diosa sin nombre",
      "Las inscripciones se dirigen a una deidad femenina a la que llaman <em>Domina</em>: «la Señora». En tres de ellas aparece la palabra <strong>MALACI</strong>, que el equipo describe como una designación de diosa hasta ahora desconocida y cuyo significado sigue en estudio",
      "## Por qué se cree que fueron mujeres",
      "Las fusayolas son el detalle que lo cambia todo. Hilar era trabajo de mujeres en el mundo romano, y encontrar sus herramientas depositadas como ofrenda, a doscientos metros bajo tierra, junto a inscripciones dirigidas a una diosa, es una coincidencia difícil de explicar de otro modo",
      "> Encajan con la evidencia epigráfica de la participación activa de mujeres en el santuario.\n— Virginia Barciela, arqueóloga de la Universidad de Alicante",
      "El equipo lo completan Silvia Alfayé Villa y Aitor Ruiz-Redondo, de la Universidad de Zaragoza, y Sergio García-Dils, de la UNED en Sevilla",
      "## Lo que no se sabe todavía",
      "Quién era <em>Domina</em>, si MALACI es un nombre, un epíteto o un topónimo, y por qué el culto se practicaba tan adentro. Doscientos metros de cueva no son un detalle logístico: significan bajar con lámpara de aceite, en fila, para dejar una ofrenda donde nadie más la vería",
    ],
    expertise:
      "La cueva llevaba siglos llamándose «de las mujeres» y era el tipo de topónimo que los arqueólogos suelen tratar como folclore tardío. Aquí resultó ser el resumen más corto del hallazgo. Vale como recordatorio de que el nombre de un sitio es un dato, aunque sea el último que se acepta como tal",
  },
  {
    slug: "telescopio-roman-lanzamiento",
    featured: 2,
    site: "mxo",
    image: "/covers/telescopio-roman-lanzamiento.jpg",
    imageAlt: "Un telescopio espacial de papel con un cono de visión muy amplio lleno de estrellas",
    imageKind: "generated",
    imageWidth: 1536,
    imageHeight: 864,
    title: "El telescopio Roman ya está en el espacio",
    summary:
      "La NASA lanzó el 30 de agosto el telescopio espacial Nancy Grace Roman: un campo de visión más de cien veces mayor que el del Hubble y las primeras imágenes previstas para diciembre.",
    date: "2026-08-30",
    category: "Mundo",
    source: {
      name: "Smithsonian Magazine",
      url: "https://www.smithsonianmag.com/smart-news/nasas-nancy-grace-roman-space-telescope-launches-to-find-exoplanets-and-unravel-mysteries-of-dark-matter-and-dark-energy-180989268/",
      verifiedOn: "2026-08-30",
    },
    body: [
      "Un mes de observaciones del Roman equivale a <strong>un siglo</strong> del Hubble mirando lo mismo. Ese solo dato explica para qué se construyó",
      "## El lanzamiento",
      "El <strong>telescopio espacial Nancy Grace Roman</strong> despegó el <strong>30 de agosto de 2026</strong> a las 7:26 de la mañana, hora del este, en un cohete <strong>Falcon Heavy</strong> de SpaceX desde el Centro Espacial Kennedy, en Florida. Pesa unas <strong>8 toneladas</strong> y mide cerca de <strong>13 metros de largo</strong> por cuatro de ancho",
      "Costó alrededor de <strong>4 300 millones de dólares</strong>, algo por debajo de lo presupuestado, y llegó al lanzamiento varios meses antes de lo previsto &mdash; dos frases que rara vez se escriben juntas sobre un observatorio espacial",
      "## Qué hace distinto",
      "Su instrumento principal es una cámara infrarroja de <strong>300 megapíxeles</strong> con la misma sensibilidad y nitidez que el Hubble, pero con un campo de visión <strong>al menos cien veces mayor</strong>. No ve más lejos: ve mucho más a la vez. Por eso puede recorrer el cielo unas <strong>mil veces más rápido</strong>",
      "## Qué va a buscar",
      "Tres grandes rastreos en <strong>cinco años</strong>: mapear <strong>una octava parte de todo el cielo</strong> con datos de más de <strong>mil millones de galaxias</strong>; vigilar explosiones estelares y objetos que cambian de brillo; y buscar planetas fuera del sistema solar hacia el centro de la galaxia. Llevará además un <strong>coronógrafo</strong> de 100 a 1 000 veces más potente que los anteriores, el aparato que tapa la luz de una estrella para que se vean los planetas a su alrededor",
      "Enviará cerca de <strong>un terabyte de datos al día</strong> desde el segundo punto de Lagrange, a un millón y medio de kilómetros de la Tierra, donde ya está el James Webb. Las <strong>primeras imágenes llegan en diciembre</strong>",
      "## Quién fue Nancy Grace Roman",
      "La primera mujer con un puesto ejecutivo en la NASA y su primera jefa de astronomía. Murió en <strong>2018</strong>. Se la llama la madre del Hubble porque fue quien defendió en los años sesenta, contra buena parte de su gremio, que valía la pena poner telescopios en el espacio",
    ],
    expertise:
      "El calendario es la parte útil para quien quiera seguirlo: las primeras imágenes son de diciembre, y los resultados que importan &mdash; energía oscura, exoplanetas &mdash; salen de rastreos de cinco años, no de una fotografía. Conviene esperar un anuncio bonito en diciembre y ciencia real hacia 2028",
  },
  {
    slug: "cuatro-cienegas-borrego-cimarron",
    site: "mxo",
    image: "/covers/cuatro-cienegas-borrego-cimarron.jpg",
    imageAlt: "Un borrego cimarrón en una loma del desierto, un bisonte al fondo y pozas de agua abajo",
    imageKind: "generated",
    imageWidth: 1536,
    imageHeight: 864,
    title: "Los bisontes funcionaron; ahora va el borrego",
    summary:
      "Cuarenta y siete bisontes devolvieron a Cuatro Ciénegas gato montés, pecaríes y venados. La siguiente pieza que la fundación quiere reponer es el borrego cimarrón: una manada fundacional de 12 a 15 ejemplares.",
    date: "2026-08-28",
    category: "Naturaleza",
    source: {
      name: "Milenio",
      url: "https://www.milenio.com/estados/borrego-cimarron-siguiente-introduccion-en-cuatro-cienegas-coahuila",
      verifiedOn: "2026-08-30",
    },
    body: [
      "La restauración ecológica suele medirse en promesas. En Cuatro Ciénegas se está midiendo en cámaras trampa, y lo que aparece en ellas es lo que nadie puso ahí.",
      "## Lo que pasó primero",
      "En el verano de <strong>2025</strong> llegaron a la reserva El Santuario los primeros <strong>tres bisontes americanos</strong>, procedentes del Museo del Desierto. En noviembre de ese año se sumaron otros <strong>44 ejemplares</strong>, y la manada quedó en <strong>47</strong>.",
      "A casi un año de la primera llegada, el monitoreo con cámaras trampa empezó a mostrar algo que no formaba parte del proyecto: la cadena alimentaria creció sola. Aparecieron <strong>gato montés</strong>, una manada de <strong>pecaríes</strong> y <strong>venados</strong>. Nadie los reintrodujo. Volvieron.",
      "## Por qué un bisonte trae un gato montés",
      "No es magia, es pasto. Un herbívoro grande que pace y se mueve cambia la altura y la composición de la vegetación, y con ella el suelo, la retención de agua y la cantidad de animales pequeños que pueden vivir ahí. Cuando hay más presa pequeña, aparece quien la caza. El bisonte no atrae al gato montés: le construye la despensa.",
      "Ese es el argumento entero de la reintroducción de especies clave, y es un argumento que casi siempre se defiende en teoría porque el resultado tarda décadas. Aquí tardó menos de un año en verse.",
      "## Lo que viene",
      "La <strong>Fundación Pro CuatroCiénegas</strong> quiere ahora al <strong>borrego cimarrón</strong>, una especie nativa de la zona. El plan que su director, Gerardo Ruiz Smith, describió a Milenio es una <strong>manada fundacional de entre 12 y 15 ejemplares</strong>, que en una primera etapa vivirá en un espacio protegido, con alimentación y cuidados controlados.",
      "El encierro no es un detalle administrativo: es la etapa que decide si el proyecto funciona. Los animales tienen que adaptarse al sitio y empezar a reproducirse antes de que se libere a nadie, y sólo conforme crezca la población se avanza gradualmente hacia la liberación dentro del predio.",
      "> Ya tenemos algunos fondos iniciales para empezar a planear y obtener los permisos para la infraestructura inicial que se estaría construyendo.\n— Gerardo Ruiz Smith, director de la Fundación Pro CuatroCiénegas, a Milenio",
      "Es una frase modesta y conviene leerla como está escrita: hay dinero para planear y para permisos, no para soltar borregos. La prioridad declarada de la fundación sigue siendo <strong>consolidar el proyecto del bisonte</strong> antes de concentrar esfuerzos en el siguiente.",
      "## Qué significa esto para quien quiera ir",
      "Cuatro Ciénegas es una reserva de la biosfera en el desierto de Coahuila, célebre por sus pozas de agua cristalina y por una biología que se estudia como análogo de vida temprana en la Tierra. Lo que cambia con este proyecto no es el paisaje, que ya era extraordinario, sino la probabilidad de ver fauna grande en él.",
      "Y cambia el tipo de visita. Una reserva con 47 bisontes y una cadena alimentaria en recuperación no se recorre igual que una laguna: se recorre despacio, temprano, y con la expectativa razonable de no ver nada. Esa es también la señal de que está funcionando.",
    ],
    expertise:
      "El dato que ordena todo lo demás es el orden de los factores. La fundación no reintrodujo depredadores ni presas: reintrodujo un herbívoro grande y esperó. Gato montés, pecaríes y venados llegaron por su cuenta. Un proyecto que hubiera empezado por soltar depredadores habría tenido titulares antes y resultados después &mdash; o ninguno.",
  },
  {
    slug: "tren-ligero-texcoco-la-paz",
    site: "mxo",
    image: "/covers/tren-ligero-texcoco-la-paz.jpg",
    imageAlt: "Una línea de tren ligero con estaciones marcadas y un tranvía al final, un lago detrás",
    imageKind: "generated",
    imageWidth: 1536,
    imageHeight: 864,
    title: "El tren de Texcoco: once estaciones, 30 minutos",
    summary:
      "El Edomex publicó el proyecto del Tren Ligero Texcoco–La Paz: 21 kilómetros, once estaciones, media hora de punta a punta contra los setenta minutos de hoy.",
    date: "2026-08-27",
    category: "Movilidad",
    source: {
      name: "Chilango",
      url: "https://www.chilango.com/noticias/transporte/publican-proyecto-tren-ligero-de-texcoco-a-la-paz-estaciones-trenes-tiempo-de-recorrido/",
      verifiedOn: "2026-08-30",
    },
    body: [
      "Un proyecto de transporte se vuelve real el día que publica su lista de estaciones. Antes de eso es una línea sobre un mapa; después es algo que se puede discutir casa por casa. El Tren Ligero Texcoco&ndash;La Paz acaba de cruzar esa frontera.",
      "El Gobierno del Estado de México publicó el proyecto en la plataforma <strong>Proyectos México</strong>, en etapa de preinversión, con un documento fechado el <strong>7 de agosto</strong>. El contrato que se licitará incluye obra civil y de sistemas, gestión ambiental y de urbanismo, y material rodante.",
      "## Las once estaciones",
      "De oriente a poniente: <strong>Texcoco, Autónoma de Chapingo, San Bernardino, Puerta Texcoco, Central de Abasto, Piedras Negras, Francisco Villa, Conalep Los Reyes, La Magdalena, Los Reyes y La Paz</strong>.",
      "Los dos extremos importan por razones distintas. En Texcoco, la terminal se ubicará en la <strong>antigua estación del ferrocarril México&ndash;Veracruz</strong>, sobre la calle Nezahualcóyotl, en el barrio de San Juanito &mdash; es decir, el tren regresa a un edificio que ya fue estación. En el poniente, la línea termina en <strong>Metro La Paz</strong>, cabecera de la Línea A, que es lo que convierte a esto en algo más que un tren local: conecta a Texcoco, Chimalhuacán y Nezahualcóyotl con la red del Metro de la Ciudad de México.",
      "## Los números",
      "<strong>21 kilómetros</strong> de longitud. <strong>30 minutos</strong> de terminal a terminal, contra los setenta que hoy toma el mismo trayecto: una reducción superior al <strong>50% del tiempo</strong>. Velocidad comercial de <strong>41 km/h</strong>, máxima de 80.",
      "El material rodante son <strong>14 trenes dobles</strong> &mdash; para comparar, el Tren Ligero de la Ciudad de México opera con cerca de 20 trenes dobles acoplados. La demanda que se busca cubrir con esos catorce es de <strong>127 mil usuarios al día</strong>.",
      "## El detalle que casi nadie está mirando",
      "La línea será de <strong>operación mixta</strong>: conviven servicio de carga y de pasajeros. Lo anunció la Secretaría de Movilidad mexiquense desde enero, y es la decisión más consecuente del proyecto.",
      "Una línea mixta cambia todo lo demás. Cambia el diseño de la vía, cambia la frecuencia posible para el pasajero, cambia el mantenimiento y cambia las ventanas horarias en que cada servicio puede circular. Explica también por qué la velocidad comercial se fija en 41 km/h y no más alta. No es un pero: es la razón por la que un proyecto de este tamaño resulta financiable en el oriente del Estado de México, donde la carga ya existe y el pasajero, hasta ahora, viaja en camión.",
      "## Lo que falta",
      "Preinversión significa que hay proyecto y no hay obra. Falta la licitación, falta el contrato y faltan las fechas. Aquí no aparece un año de inauguración porque nadie lo ha publicado, y una lista de estaciones no es un calendario.",
      "Lo que sí es firme es la geometría: once estaciones, dos terminales identificadas con dirección, y una conexión con la Línea A que define para quién se está construyendo.",
    ],
    expertise:
      "El ahorro real no son los 40 minutos del tren. Es que el trayecto Texcoco&ndash;Metro se vuelve predecible: hoy depende del tráfico de la carretera y por eso su duración varía entre un día y otro más de lo que dura el viaje en sí. Un tren de 30 minutos vale menos por rápido que por igual todos los días.",
  },
  {
    slug: "filij-2026-regresa-al-cenart",
    site: "mxo",
    image: "/covers/filij-2026-regresa-al-cenart.jpg",
    imageAlt: "Un libro abierto que se convierte en una carpa de papel, rodeado de animales de papel doblado",
    imageKind: "generated",
    imageWidth: 1536,
    imageHeight: 864,
    title: "La FILIJ regresa al CENART con entrada gratuita",
    summary:
      "La 44 edición de la Feria Internacional del Libro Infantil y Juvenil será del 13 al 22 de noviembre en el CENART, con entrada gratuita y convocatoria abierta para visitas escolares.",
    date: "2026-08-28",
    category: "Ferias",
    source: {
      name: "Excélsior",
      url: "https://www.excelsior.com.mx/cultura/filij-2026-regresa-cenart-con-entrada-gratuita-fechas",
      verifiedOn: "2026-08-30",
    },
    body: [
      "Una feria del libro para niños se mide por una cosa: cuántos de los que entran salen leyendo algo que eligieron ellos. La FILIJ lleva 44 ediciones construida alrededor de esa idea, y la de 2026 vuelve al mismo sitio y con el mismo precio &mdash; ninguno.",
      "## Fechas y sede",
      "De acuerdo con el <strong>Fondo de Cultura Económica</strong>, la <strong>44 edición</strong> de la Feria Internacional del Libro Infantil y Juvenil se realizará del <strong>13 al 22 de noviembre</strong> en el <strong>Centro Nacional de las Artes</strong>. La <strong>entrada es gratuita</strong>.",
      "El FCE abrió además una <strong>convocatoria para visitas escolares</strong>, cuyos detalles se consultan por sus canales oficiales. Ese es el mecanismo por el que la feria llega a los niños que no habrían ido en fin de semana con la familia.",
      "## Qué es, más allá de los libros",
      "La FILIJ reúne editoriales, escritores, ilustradores y familias. La oferta editorial va del cuento ilustrado a la novela juvenil y el libro informativo, para todas las edades.",
      "Pero la feria no es una venta de libros con actividades encima. La programación cultural suele incluir <strong>cuentacuentos, talleres creativos, presentaciones de libros, teatro, música y danza</strong> &mdash; y en la práctica ésa es la parte que convierte una visita en una costumbre.",
      "La distinción importa para quien va con niños pequeños: se puede pasar una mañana completa sin comprar nada y que el día haya valido.",
      "## Cómo llegar",
      "El CENART está en <strong>Avenida Río Churubusco 79</strong>, colonia Country Club Churubusco, alcaldía Coyoacán.",
      "En transporte público, las estaciones de Metro más cercanas son <strong>General Anaya</strong> (Línea 2) y <strong>Ermita</strong> (Línea 12). De cualquiera de las dos son <strong>de 8 a 10 minutos caminando</strong>.",
      "## Y si ya se está ahí",
      "El CENART mantiene cartelera todo el año, con espectáculos, talleres y actividades infantiles. Noviembre es cuando el recinto se llena de niños, pero no es el único mes en que programa para ellos.",
    ],
    expertise:
      "Diez días es mucha feria y el error habitual es ir el primer o el último fin de semana. Entre semana la FILIJ se vacía de familias y se llena de grupos escolares en horario de mañana; una tarde de martes o miércoles es, con diferencia, el momento en que un niño puede acercarse a una mesa y hojear sin cola.",
  },
  {
    slug: "kusama-320-mil-visitantes",
    site: "mxo",
    image: "/covers/kusama-320-mil-visitantes.jpg",
    imageAlt: "Un campo denso de círculos de papel de todos los tamaños con una sala espejada al centro",
    imageKind: "generated",
    imageWidth: 1536,
    imageHeight: 864,
    title: "Kusama pasó de 320 mil visitantes",
    summary:
      "Más de 320 mil personas vieron «Obsesión Infinita» en el Museo Tamayo entre 2014 y 2015. Al final el museo abrió 36 horas seguidas y casi 10 mil personas entraron en ese maratón.",
    date: "2026-08-27",
    category: "Arte",
    source: {
      name: "El Universal Cultura",
      url: "https://www.eluniversal.com.mx/cultura/la-exposicion-de-yayoi-kusama-que-obsesiono-a-mexico/",
      verifiedOn: "2026-08-30",
    },
    body: [
      "Hubo una fila en Reforma que la gente aguantó acampando. No era por un concierto: era por una exposición de arte contemporáneo, en un museo público, un miércoles cualquiera de enero.",
      "## Los números",
      "<strong>&laquo;Obsesión Infinita&raquo;</strong>, de la artista japonesa <strong>Yayoi Kusama</strong>, se inauguró el <strong>26 de septiembre de 2014</strong> en el <strong>Museo Tamayo</strong> y cerró el <strong>18 de enero de 2015</strong>. Recibió a más de <strong>320 mil personas</strong>, según cifras del gobierno mexicano.",
      "Fue la primera retrospectiva de Kusama en América Latina, y la primera vez que se registraba esa cantidad de visitantes en una exposición en México.",
      "Conforme se acercaba el cierre, la fila creció hasta que el museo hizo lo que casi ningún museo hace: <strong>abrir 36 horas seguidas</strong>. En ese maratón final se registraron <strong>casi 10 mil personas</strong>.",
      "## Qué había adentro",
      "Más de <strong>100 obras creadas entre 1950 y 2013</strong>. Piezas de la serie <em>Infinity net</em>, la película <em>Kusama&rsquo;s Self-Obliteration</em>, y las instalaciones <em>Phalli&rsquo;s field</em>, <em>Obliteration room</em> e <em>Infinity mirror room</em>.",
      "Esas tres instalaciones explican buena parte de la fila. Son obras que no se ven: se entra en ellas, de una persona a la vez o de tres en tres. El aforo por hora de una <em>Infinity mirror room</em> es minúsculo por diseño, y eso convierte cualquier éxito de público en una cola.",
      "## No fue sólo México",
      "La exposición fue organizada por el museo <strong>Malba</strong> de Buenos Aires, donde convocó a <strong>180 mil asistentes</strong> y terminó con las calles vecinas decoradas con lunares. También pasó por Río de Janeiro, Brasilia y São Paulo, y de México viajó a Chile.",
      "Visto así, el dato mexicano se lee mejor: 320 mil contra 180 mil en la ciudad que la organizó.",
      "## La artista",
      "Kusama nació en <strong>Matsumoto en 1929</strong> y murió este año. Se mudó a Nueva York en <strong>1957</strong> y siguió pintando puntos en obras hechas de seriación y repetición; fue amiga de Andy Warhol y Georgia O&rsquo;Keeffe. Su trabajo llegó al MoMA de Nueva York, al Museo Ludwig en Alemania y a la Tate Modern de Londres, y en <strong>2016</strong> recibió la <strong>Orden de la Cultura</strong>, el premio más prestigioso que Japón otorga a sus artistas.",
      "Decía que dibujaba como veía el mundo: cubierto de manchas.",
    ],
    expertise:
      "El maratón de 36 horas es el dato que suelen citar mal. No fue un truco de mercadotecnia al inicio, fue una respuesta al final: el museo abrió de corrido porque la fila ya no cabía en los días que quedaban. Vale como advertencia práctica para cualquier exposición muy esperada &mdash; el mes barato para verla es el primero, no el último.",
  },
  {
    slug: "john-giorno-en-kurimanzutto",
    site: "mxo",
    image: "/covers/john-giorno-en-kurimanzutto.jpg",
    imageAlt: "Un teléfono de disco montado en una pared de galería, con discos de vinilo y una tira de papel",
    imageKind: "generated",
    imageWidth: 1536,
    imageHeight: 864,
    title: "kurimanzutto recibe la obra poética de John Giorno",
    summary:
      "Poesía en los muros, en vinilos que el visitante elige, en un video de diez horas y en un teléfono. La primera individual de John Giorno en la Ciudad de México está en kurimanzutto hasta el 10 de octubre.",
    date: "2026-08-26",
    category: "Arte",
    source: {
      name: "El Universal Cultura",
      url: "https://www.eluniversal.com.mx/cultura/galeria-kurimanzutto-recibe-la-obra-poetica-del-artista-john-giorno/",
      verifiedOn: "2026-08-30",
    },
    body: [
      "Hay una línea telefónica en la librería de kurimanzutto. Se levanta el auricular y alguien recita. No hay menú, no hay espera: la poesía ya está sonando y uno se incorpora a la mitad.",
      "Es <em>Dial-A-Poem</em>, la obra más famosa de <strong>John Giorno</strong> (1936&ndash;2019), exhibida por primera vez en el <strong>MoMA</strong> de Nueva York en <strong>1970</strong>, y es la mejor puerta de entrada a lo que la galería montó.",
      "## La primera individual en la ciudad",
      "<strong>John Giorno: LIFE IS A KILLER</strong> es la primera exposición individual del artista, activista y poeta en la <strong>Ciudad de México</strong>. Reúne sus obras poéticas más representativas, desde los primeros trabajos hasta piezas de sus últimas series, de <strong>2015</strong>.",
      "Giorno fue contemporáneo de Andy Warhol y William S. Burroughs, y su idea rectora era simple y radical: la poesía no debía existir sólo en la página.",
      "> Era fiel creyente de que la poesía no debía existir sólo en la página, sino que era tan esencial para la comunicación de la humanidad, por lo que podía y debía existir en el mundo.\n— Corinna Durland, directora de la sede neoyorquina de kurimanzutto",
      "Por eso en la sala se puede <strong>leer</strong> poesía en los muros y <strong>oírla</strong> en un disco de vinilo, en un <strong>video de más de diez horas</strong> realizado por <strong>Rirkrit Tiravanija</strong>, o por teléfono.",
      "## Los cuadros que son frases",
      "Están las <em>Poem paintings</em>, iniciadas en Italia en los años setenta y punto de partida de su pintura. Llevan versos como &laquo;Everything is delusion including wisdom&raquo;, &laquo;Everyone gets lighter&raquo;, &laquo;Filling what is empty, emptying what is full&raquo; y el que da título a la muestra, &laquo;Life is a killer&raquo;.",
      "La mayoría son en blanco y negro, con una <strong>tipografía diseñada para él por Mark Michaelson en 1984</strong>. Las de fondo de arcoíris son de <strong>2015</strong> en adelante, hechas como gesto de apoyo a la libertad de las personas LGBT.",
      "También se exhibe una de sus obras más tempranas: un poema inspirado en el juicio de Bobby Seale, cofundador de las Panteras Negras.",
      "## El corazón: los vinilos",
      "El galerista lo llama así, y es literal. Giorno grabó bajo su propio sello discos con poemas y canciones hechos junto a sus amigos, entre ellos <strong>Debbie Harry</strong> y <strong>Patti Smith</strong>. Los vinilos pueden reproducirse dentro de la galería, y es <strong>el visitante quien elige cuál suena</strong>.",
      "Esa decisión curatorial hace mucho más de lo que parece: convierte a quien entra en programador de la sala. La exposición suena distinta según quién esté adentro.",
      "## La parte hecha para México",
      "El galerista José Kuri contó que al planear la muestra se preguntaron cómo conectar el trabajo del estadounidense con México. La respuesta fue un <strong>taller de traducción</strong> de sus poemas al español, en colaboración con la librería <strong>La Americana</strong>, que se publicará en un fanzine. Participan <strong>Brenda Lozano, Carla Faesler, Paloma Contreras, Isabel Zapata y Mateo Díaz Choza</strong>.",
      "## Dónde y hasta cuándo",
      "La muestra estará <strong>hasta el 10 de octubre</strong> en <strong>Gob. Rafael Rebollar 94, San Miguel Chapultepec</strong>.",
    ],
    expertise:
      "Hay que reservar tiempo para el teléfono y los vinilos, que es donde la exposición realmente pasa y donde nadie se detiene. Una sala de poesía se recorre por instinto como se recorre una de pintura &mdash; leyendo los muros y saliendo &mdash;, y así se pierde exactamente la mitad de la obra: la que suena.",
  },
];
