import type { NewsItem } from "../types.ts";

export const items: NewsItem[] = [
  {
    slug: "broadway-week-which-shows-are-worth-it",
    site: "nyc42",
    title: "Broadway Week: which of the 25 is it for",
    summary:
      "Twenty-five shows take the two-for-one from 8 to 20 September. They are not equally worth it, and the reason has less to do with the shows than with what each one costs the rest of the year.",
    date: "2026-08-30",
    category: "Theatre",
    source: {
      name: "Time Out New York",
      url: "https://www.timeout.com/newyork/news/5-best-musicals-to-snag-2-for-1-tickets-to-during-nyc-broadway-week-082726",
      verifiedOn: "2026-08-30",
    },
    body: [
      "A two-for-one is not a discount on a show. It is a discount on <em>a seat</em>, and the two are only the same thing when the seat was going to be expensive anyway. That is the whole trick to reading a Broadway Week list, and it is why ranking these 25 productions by how good they are answers the wrong question.",
      "The <a href=\"/events/broadway-week-fall-2026/\" title=\"NYC Broadway Week 2026: dates, shows and the catch\">fall edition</a> runs <strong>8 to 20 September 2026</strong>, tickets have been on sale since 18 August, and the participating shows are &amp; Juliet, Aladdin, The Book of Mormon, Buena Vista Social Club, Chicago, The Great Gatsby, Hadestown, Harry Potter and the Cursed Child, Just in Time, The Lion King, The Lost Boys, Maybe Happy Ending, MJ, Oh Mary!, Operation Mincemeat, The Outsiders, Paranormal Activity, The Rocky Horror Show, Schmigadoon!, School Girls; Or, the African Mean Girls Play, Six, Stranger Things: The First Shadow, Titaníque, Two Strangers (Carry a Cake Across New York) and Wicked.",
      "Here is how we would spend it, with the reasoning stated so you can disagree with it on purpose.",
      "## 1. <a href=\"/events/broadway-week-harry-potter/\" title=\"Harry Potter and the Cursed Child at Broadway Week\">Harry Potter and the Cursed Child</a>",
      "The largest saving on the list, for a structural reason rather than a critical one: it is the longest and most technically elaborate thing on Broadway, it plays a big house, and it is not a show that turns up in the cheap-ticket channels week after week. <strong>Two-for-one on a rarely discounted ticket is worth more than two-for-one on a ticket that is discounted anyway</strong>, and this is the clearest case of that on the list.",
      "## 2. <a href=\"/events/broadway-week-hadestown/\" title=\"Hadestown at Broadway Week\">Hadestown</a>",
      "Anaïs Mitchell&rsquo;s Orpheus and Eurydice, staged as a smoky, jazz-inflected underworld. Second rather than first only because it is easier to reach cheaply by other means &mdash; but it is the one here most likely to be the best evening rather than the best deal, and Broadway Week is the excuse to stop putting it off.",
      "## 3. <a href=\"/events/broadway-week-stranger-things/\" title=\"Stranger Things: The First Shadow at Broadway Week\">Stranger Things: The First Shadow</a>",
      "Recent, effects-heavy, large house: the same logic as the Potter play. The difference between a good seat and a bad one is unusually wide in a show built on stagecraft, and the allocation, not you, decides which one you get. If what comes back is the back of the balcony, this is the one show on the list where the saving can cost you the point.",
      "## 4. <a href=\"/events/broadway-week-six/\" title=\"Six at Broadway Week\">Six</a>",
      "Eighty minutes, no interval, Tudor England staged as a pop concert. It is the shortest thing on the list, which makes it the easiest to pair with something else in one day and the easiest to take a teenager to. On a two-for-one it is the cheapest way this fortnight to put two people inside a Broadway theatre at all.",
      "## 5. <a href=\"/events/broadway-week-oh-mary/\" title=\"Oh Mary! at Broadway Week\">Oh Mary!</a>",
      "The comedy, and the one whose price has least to do with spectacle. It plays a smaller house, so the offer buys proximity rather than merely a seat &mdash; and in a small house proximity is most of what you were paying for.",
      "## What we would not spend it on, and why that is not an insult",
      "<a href=\"/events/broadway-week-the-lion-king/\" title=\"The Lion King at Broadway Week\">The Lion King</a>, <a href=\"/events/broadway-week-wicked/\" title=\"Wicked at Broadway Week\">Wicked</a> and <a href=\"/events/broadway-week-chicago/\" title=\"Chicago at Broadway Week\">Chicago</a> are three of the longest-running things on this list and three of the safest evenings in New York. They are also the three most reliably available at some reduced price in any given month. Using a Broadway Week ticket on them is not a mistake &mdash; it is simply the purchase where the offer is doing the least work.",
      "The same holds at the other end for the newest and smallest productions, for the opposite reason. <strong>A show still looking for its audience discounts itself.</strong> Broadway Week does not have to.",
      "## The catch nobody puts in the headline",
      "The offer exists for the fortnight. It does not exist for every performance of every show in the fortnight. Each production sets its own <strong>blackout dates</strong> and releases its own allocation, so &ldquo;is the offer on&rdquo; and &ldquo;is the offer on for the show I want, on the night I can go&rdquo; are two different questions, and only the second one matters.",
      "Check the individual listing before committing to an evening, and before booking anything around it. The most common way this goes wrong is not missing a show &mdash; it is a dinner reservation made for a night the show had blacked out.",
    ],
    expertise:
      "Broadway Week runs twice a year, in January and September. The September edition lands in the gap after the summer visitors and before the holiday run-up, which is why its released seats tend to be better than the winter edition&rsquo;s: the houses have more good inventory to give away in early September than they do in January.",
  },
  {
    slug: "brooklyn-museum-fall-2026",
    site: "nyc42",
    title: "The Brooklyn Museum sets out its autumn",
    summary:
      "Six new shows open in October: manga in the Great Hall, fifty European masterpieces from the Pearlman Collection, Hopi kachina dolls and an installation in the lobby about the Tuskegee Airmen.",
    date: "2026-08-28",
    category: "Museums",
    source: {
      name: "Time Out New York",
      url: "https://www.timeout.com/newyork/news/the-brooklyn-museum-announces-2026-fall-exhibitions-including-a-manga-takeover-and-50-new-european-masterpieces-082626",
      verifiedOn: "2026-08-30",
    },
    body: [
      "A museum programme is usually a list. This one is an argument &mdash; the Brooklyn Museum has put manga and European modernism in the same building on the same weekend, and dared anyone to say which is the serious half.",
      "## The Great Hall goes to manga",
      "<strong>Art of Manga</strong> runs <strong>3 October to 31 January 2027</strong> and is making its East Coast debut. It gathers original manga artwork, including pieces connected to <em>Inuyasha</em>, <em>JoJo&rsquo;s Bizarre Adventure</em>, <em>&#332;oku: The Inner Chambers</em> and <em>One Piece</em>.",
      "That is original artwork, which is the part worth registering. Manga is consumed as print and screen, so almost nobody has seen the drawn page &mdash; the pencil under the ink, the correction, the hand.",
      "Running beside it in the same Great Hall, on exactly the same dates, is <strong>Manga Before Manga: Japanese Art from the Collection</strong>, which digs into the historical roots of the form. Hanging the two together turns a fan show into an art-historical claim: that the visual grammar is centuries older than the medium.",
      "## Fifty-plus European masterpieces",
      "<strong>C&eacute;zanne to Modigliani: Gifts of Modern Art from the Pearlman Collection</strong> opens <strong>2 October and runs to 18 April 2027</strong>, with more than <strong>50 European masterpieces</strong>.",
      "These are gifts, not loans &mdash; work entering the collection. A loan show is a visit; a gift show is the museum telling you what it will look like for the next fifty years.",
      "## The rest of it, which is not filler",
      "<strong>Hopi Kachina Dolls: Blessings for a Balanced World</strong> (<strong>2 October &ndash; 27 June 2027</strong>) examines the kachina doll tradition through the perspective of Hopi girls and women &mdash; the people the tradition is actually addressed to, which is not how these objects are usually framed in a museum case.",
      "<strong>Michael Richards: Free F&rsquo;All</strong> (<strong>11 September &ndash; 6 June 2027</strong>) occupies the lobby. It honours the history of the Tuskegee Airmen and remembers the artist, who died on 11 September 2001. It is free to walk past and impossible to walk past.",
      "<strong>Mika Ninagawa: Feel the Flow(ers)</strong> arrives in October at the Toby Devan Lewis Education Center. And <strong>Iris van Herpen: Sculpting the Senses</strong> is still up, through <strong>6 December</strong> &mdash; couture that behaves like sculpture.",
      "## Why the dates matter more than the list",
      "Two of these run into next summer, three close in the winter, and van Herpen closes first. The only weekend on which the whole programme above is simultaneously on the walls falls between <strong>3 October and 6 December</strong>.",
      "That is the window, and it is the reason to read a season announcement in August.",
    ],
    expertise:
      "The Brooklyn Museum is the second-largest art museum in New York and the one most often skipped by a visitor with one weekend, because the Met and MoMA are closer to where they are already standing. Six concurrent shows with nothing in common is the argument for the subway ride &mdash; and the 2/3 to Eastern Parkway puts you at the door, not near it.",
  },
  {
    slug: "hudson-river-foliage-cruises",
    site: "nyc42",
    title: "Hudson foliage cruise tickets are on sale",
    summary:
      "Circle Line has two foliage sailings this September: an eight-hour run to Bear Mountain on the 19th and 20th, and a four-hour trip toward Hook Mountain on the 26th and 27th. Last year sold out.",
    date: "2026-08-26",
    category: "Outdoors",
    source: {
      name: "Time Out New York",
      url: "https://www.timeout.com/newyork/news/the-best-way-to-experience-nyc-fall-foliage-is-on-these-scenic-hudson-river-cruises-and-tickets-are-on-sale-right-now-082826",
      verifiedOn: "2026-08-30",
    },
    body: [
      "Central Park is the standard place to look at autumn in New York, and it is the wrong one. The colour on the Hudson is not a park&rsquo;s worth of trees &mdash; it is fifty miles of cliff face, and the only way to see it properly is from the water.",
      "Circle Line&rsquo;s foliage cruises are back for 2026 and <strong>tickets are on sale now</strong>. There are two, and they are genuinely different days out.",
      "## The full day: Bear Mountain, 19 and 20 September",
      "The <strong>eight-hour Bear Mountain Oktoberfest Cruise</strong> is the marquee trip. It sails <strong>50 miles north from Pier 83</strong> in Midtown, past the Palisades and under the George Washington Bridge, and docks at <strong>Bear Mountain State Park</strong>.",
      "Then it stops being a boat trip. You get <strong>three hours ashore</strong> &mdash; hiking the trails, the Trailside Zoo, or a walk round Hessian Lake &mdash; before the return leg. That is a proper day in the Hudson Highlands with no car, no rental and no Metro-North timetable to solve.",
      "## The half day: Hook Mountain, 26 and 27 September",
      "The <strong>four-hour Hudson River Fall Foliage Cruise</strong> sails toward <strong>Hook Mountain</strong> and back, past the coloured cliffs and the landmark bridges. Circle Line notes that <strong>bald eagles, hawks and ospreys</strong> are all plausible sightings on the route &mdash; the lower Hudson has become raptor country again, quietly, over about thirty years.",
      "## Both of them are Oktoberfest",
      "This is the detail that decides whether the trip is for you. Both sailings are floating Oktoberfest celebrations: pork schnitzel, bratwurst and Bavarian pretzels, a <strong>collectible mug</strong> refilled with Warsteiner, Spaten, Sam Adams Octoberfest or local pumpkin ale, live music, and commentary from Circle Line&rsquo;s guides.",
      "There are also televisions on the lounge deck for the Sunday football. A quiet contemplative sail up the river this is not.",
      "## Book it now, not in October",
      "Last year&rsquo;s sailings <strong>sold out completely</strong>, and the reason is arithmetic rather than hype: four dates, two boats, one city. By the time the leaves are worth photographing, the thing that takes you to them has gone.",
    ],
    expertise:
      "The two trips are sold as long and short versions of one thing, and they are not. Bear Mountain is a hike with a boat attached &mdash; wear the shoes. Hook Mountain is an afternoon on a deck. Choosing by duration rather than by what happens at the far end is how people end up in the wrong footwear on a mountain.",
  },
  {
    slug: "disney-cruises-return-to-nyc",
    site: "nyc42",
    title: "Disney will sail from New York again in 2027",
    summary:
      "The Disney Wish returns to New York in autumn 2027 after four years away: seven sailings, five of them to Bermuda, one a foliage run to Boston, Saint John and Halifax. Booking opens 8 September.",
    date: "2026-08-27",
    category: "Travel",
    source: {
      name: "Time Out New York",
      url: "https://www.timeout.com/newyork/news/disney-cruises-are-officially-returning-to-nyc-with-caribbean-sails-and-new-england-foliage-tours-set-for-2027-082726",
      verifiedOn: "2026-08-30",
    },
    body: [
      "For four years, leaving New York on a Disney ship has not been an option. That changes in <strong>autumn 2027</strong>, when the <strong>Disney Wish</strong> comes back to the city &mdash; and for anyone here, it turns a holiday that normally begins with a cab to LaGuardia into one that begins at a pier.",
      "## Seven sailings",
      "The Wish will sail from New York on <strong>seven voyages beginning in late September 2027</strong>, running <strong>four to seven nights</strong>.",
      "<strong>Five go to Bermuda</strong> &mdash; pink sand, blue water, and on three of those five an <strong>extra day on the island</strong>, which is the difference between seeing a port and seeing a place.",
      "One is the <strong>fall foliage run</strong>: a coastal route calling at <strong>Boston</strong>, <strong>Saint John, New Brunswick</strong> and <strong>Halifax, Nova Scotia</strong>, timed for peak colour along the Atlantic coast. It is Disney Cruise Line&rsquo;s first return to New England and Canada out of New York in nearly four years.",
      "## The one for people who read schedules",
      "After the New York run, the Wish makes a <strong>five-night repositioning cruise to San Juan</strong>, with a stop in Bermuda. Repositioning sailings are the odd ones in any schedule: the ship has to move anyway, so the itinerary is shaped by geography rather than by demand. They are also the ones that sell to people who have already done the standard route.",
      "## What is not announced",
      "<strong>Pricing has not been released.</strong> Disney has published the schedule, not the fares, so no figure appears here.",
      "What is published are the booking dates: <strong>31 August</strong> for select Castaway Club members, and <strong>8 September</strong> for everyone else. The Wish is one of the line&rsquo;s newer ships and it last sailed from New York in <strong>2023</strong>; the return is part of a wider autumn 2027 and spring 2028 schedule that also adds departures from San Juan, Port Canaveral, Fort Lauderdale, San Diego and Galveston.",
      "## A year out is the right time to hear this",
      "An announcement this far ahead is not a thing to act on today, with one exception: the two booking dates above are in the next fortnight, and the cabins that go first on a returning route are the ones people have been waiting four years for.",
    ],
    expertise:
      "Time Out&rsquo;s headline says Caribbean; the itineraries are Bermuda. Worth knowing before planning around a sailing time or a climate &mdash; Bermuda is a two-day sail off the Carolinas, not the tropics, and in late September it is a warm autumn rather than a summer.",
  },
];
