import type { NewsItem } from "../types.ts";

export const items: NewsItem[] = [
  {
    slug: "the-train-to-abu-dhabi-starts-running-on-30-september",
    createdAt: "2026-08-25T18:18:34+04:00",
    updatedAt: "2026-09-08T00:12:45+04:00",
    site: "riviera",
    image: "/covers/the-train-to-abu-dhabi-starts-running-on-30-september.jpg",
    imageAlt: "A chalk white paper line running the width of a mid-blue ground, two pale sky rectangles set on it at either end",
    imageKind: "generated",
    imageWidth: 1536,
    imageHeight: 864,
    title: "From 30 September there is a train to Abu Dhabi, and it does not leave from here",
    cardTitle: "The Abu Dhabi train opens",
    titleSeo: "Etihad Rail reaches Dubai 30 September",
    summary:
      "Etihad Rail's passenger service reaches Dubai on 30 September at Al Yalayis, roughly 57 minutes from Abu Dhabi — and about 40 kilometres from Meydan.",
    date: "2026-09-07",
    category: "Nearby",
    source: {
      name: "Gulf News",
      url: "https://gulfnews.com/living-in-uae/ask-us/uae-september-2026-new-etihad-rail-route-tax-changes-and-key-dates-to-know-1.500657564",
      verifiedOn: "2026-09-07",
    },
    body: [
      "The interesting thing about a first railway is not the journey time. It is that a city which has only ever measured distance in traffic suddenly has a number that does not change at five in the afternoon.",
      "## What opens",
      "On <strong>30 September</strong> the <strong>Etihad Rail</strong> passenger service extends to Dubai, linking <strong>Mohamed bin Zayed City</strong> station in Abu Dhabi with <strong>Al Yalayis</strong> station in Dubai. The scheduled journey between the two emirates is about <strong>57 minutes</strong>.",
      "## Where Al Yalayis is from Meydan",
      "South-west, out past Jebel Ali, roughly <strong>40 kilometres</strong> by road from Meydan — which is to say the station is not a local amenity here. Reaching it is a drive or a metro-and-taxi combination, and that leg is not 57 minutes.",
      "## Who it is actually for",
      "Anyone whose Abu Dhabi trip is currently a two-hour drive each way with no way to work through it. Against that, an hour on rails plus the run to Al Yalayis is still a different kind of day.",
      "## What it does not do yet",
      "It is one line and two stations, not a network. Nothing about the September opening connects Meydan, Business Bay or the airport to it directly; those are later phases and they have no dates attached.",
    ],
    expertise:
      "For a resident on this side of Meydan the honest calculation is door to door, and it turns on where in Abu Dhabi you are going rather than on the rail time. Mohamed bin Zayed City is not the corniche: an appointment on Al Maryah Island adds a taxi at the far end that eats most of what the train saved against driving. Where the service will change behaviour first is the reverse commute — someone living in Abu Dhabi and working in Dubai South or the free zones around Jebel Ali, for whom Al Yalayis is genuinely close to the destination. Watch the second phase of stations rather than the first: the moment a station opens inside the built-up part of Dubai, the arithmetic changes for everyone here at once.",
  },

  {
    slug: "a-500-metre-bridge-opens-on-the-way-into-town",
    createdAt: "2026-09-06T08:48:11+04:00",
    updatedAt: "2026-09-08T00:12:45+04:00",
    site: "riviera",
    image: "/covers/a-500-metre-bridge-opens-on-the-way-into-town.jpg",
    imageAlt: "A long chalk-white paper band arcing over a pale sky-blue band on a clear mid-blue ground, with a small sand-coloured marker at one end",
    imageKind: "generated",
    imageWidth: 1536,
    imageHeight: 864,
    title: "A 500-metre bridge opens at the Trade Centre, and the last one comes in October",
    cardTitle: "A 500-metre bridge at the Trade Centre",
    titleSeo: "A 500-metre bridge at the Trade Centre",
    summary:
      "The RTA opened a two-lane, 500-metre bridge serving traffic from the World Trade Centre and One Central towards Al Mustaqbal Street. The fifth and last bridge of the roundabout scheme is due in October 2026.",
    date: "2026-09-06",
    category: "Infrastructure",
    source: {
      name: "Dubai Media Office",
      url: "https://mediaoffice.ae/en/news/2026/august/13-08/rta-to-open-500-metre-bridge-on-friday",
      verifiedOn: "2026-09-06",
    },
    body: [
      "A district on the canal is judged by the twenty minutes at the other end of the journey, not by the view from the balcony. Those twenty minutes are being rebuilt.",
      "## What opened",
      "A <strong>500-metre, two-lane bridge</strong> carrying traffic from <strong>Dubai World Trade Centre</strong> and <strong>One Central</strong> towards <strong>Al Mustaqbal Street</strong> and the Za’abeel Palace Street intersection. On event days the RTA puts the saving at <strong>ten minutes down to two</strong>.",
      "## The scheme it belongs to",
      "The <strong>Al Mustaqbal Street Development Project</strong>, at <strong>AED 633 million</strong>, includes <strong>2,000 metres</strong> of bridges and tunnels and widens Al Mustaqbal Street from <strong>three lanes to four</strong> in each direction. Capacity rises <strong>33%</strong>, from <strong>6,600 to 8,800 vehicles per hour</strong>, and the modelled journey falls from <strong>13 minutes to 6</strong>.",
      "## What is still to come",
      "Overall completion is past <strong>50%</strong>; work at the <strong>World Trade Centre Roundabout</strong> is past <strong>85%</strong>. A further bridge was due at the end of August, the <strong>fifth and final bridge</strong> of the roundabout scheme is set for <strong>October 2026</strong>, and <strong>three tunnels</strong> totalling 1,500 metres follow in <strong>February 2027</strong>.",
      "## Who it is for",
      "<strong>Mattar Al Tayer</strong>, Director General of the RTA, framed the works as part of an integrated scheme to «accommodate urban development and population growth». The RTA counts around <strong>500,000 residents and visitors</strong> across the World Trade Centre, DIFC, Downtown Dubai and Business Bay as the beneficiaries.",
    ],
    expertise:
      "For anyone living along the canal, the number to watch is not the bridge but the tunnels in February 2027, because that is when the scheme stops taking capacity away while it adds it. Interim stages of a grade-separation project routinely make peak-hour journeys worse than the before case: traffic is diverted onto temporary alignments, and the new bridge feeds a junction downstream that has not been rebuilt yet. Expect the honest improvement to arrive after the last tunnel, not after the last bridge. The second point is about which trip actually improves. This scheme is aimed at the Trade Centre and Za’abeel movements, so it helps the run into DIFC and Downtown and does very little for the Al Khail and Ras Al Khor legs that carry the other half of the district’s commuting. Those are separate projects on separate timetables, and a resident choosing between two apartments should be asking which corridor they will be on at eight in the morning rather than reading a citywide headline about congestion.",
  },

  {
    slug: "rents-are-beating-prices-across-thirty-cities",
    createdAt: "2026-09-06T08:48:11+04:00",
    updatedAt: "2026-09-06T08:48:11+04:00",
    site: "riviera",
    image: "/covers/rents-are-beating-prices-across-thirty-cities.jpg",
    imageAlt: "Two chalk-white paper bars on a clear mid-blue ground, the taller one narrow and the shorter one wide, a thin pale sky line between them",
    imageKind: "generated",
    imageWidth: 1536,
    imageHeight: 864,
    title: "In thirty world cities, prime rents have beaten prices for four years running",
    cardTitle: "Rents beating prices, four years on",
    titleSeo: "Savills: prime rents beat values again",
    summary:
      "Savills’ half-year index puts prime capital values up 0.6% and prime rents up 1.1% across 30 cities. Rents have outpaced values since mid-2022, and the gap is a statement about borrowing costs rather than about buildings.",
    date: "2026-09-06",
    category: "Market",
    source: {
      name: "Savills",
      url: "https://www.savills.com/research_articles/255800/393831-0",
      verifiedOn: "2026-09-06",
    },
    body: [
      "When renting outperforms owning for four years in a row, that is not a property story. It is an interest rate story wearing a property costume.",
      "## The two headline figures",
      "Across the <strong>30 cities</strong> in the <strong>Savills World Cities Prime Residential Index</strong>, capital values rose <strong>0.6%</strong> and rents rose <strong>1.1%</strong> in the six months to <strong>June 2026</strong>. Rental growth was up from <strong>0.5%</strong> in the second half of 2025. The report was published on <strong>19 August 2026</strong>.",
      "## The four-year pattern",
      "Prime rents have outperformed capital values <strong>since mid-2022</strong>. Savills attributes it to elevated interest rates, affordability constraints and deferred purchase decisions — households choosing flexibility over ownership while the cost of the mortgage is the largest variable in the sum.",
      "## Where the growth was",
      "<strong>Cape Town</strong> and <strong>Lisbon</strong> were among the strongest rental markets. <strong>Tokyo</strong> led on capital values, up <strong>7.0%</strong> in six months and <strong>20.4%</strong> over the year to June. Sixty per cent of the index recorded stable or positive capital value growth.",
      "## What it does to yields",
      "Prime yields were broadly stable, which is what happens when rents and values move together. <strong>Amsterdam</strong> and <strong>Berlin</strong> recorded no yield movement at all; <strong>Lisbon</strong> and <strong>Los Angeles</strong> saw yields compress as values outran rents; <strong>Hong Kong</strong> and <strong>Cape Town</strong> saw yields expand as rents outran values.",
      "## Historical scale",
      "Before the global financial crisis, prime markets routinely delivered <strong>5% to 7%</strong> capital growth every six months. Through the 2010s that settled to <strong>2% to 4.5%</strong>. A half-year reading of 0.6% is a slow market by any measure the index has ever recorded.",
    ],
    expertise:
      "The reason this matters to a canal-side rental district is that yield expansion and yield compression are the same event seen from opposite sides of a transaction. A landlord reads the Savills pattern as good news: income growing faster than the asset means the cash return on capital already committed is improving. A buyer reads the same pattern as a warning that the entry price is being supported by rent rather than by capital appreciation, which is a much thinner cushion if rents stall. Both readings are correct, and which one applies depends entirely on whether the purchase is already made. The practical caution is about the word prime. Savills tracks the top slice of each market, and in a city where a large volume of new mid-market stock is completing, the prime index and the average apartment can move in different directions for years. Anyone using a global prime index to price a two-bedroom on a canal is using the wrong instrument; use it for direction and sentiment, and use local transaction records for the number.",
  },

  {
    slug: "the-junction-riviera-leaves-by-is-being-rebuilt",
    createdAt: "2026-09-03T07:30:21+04:00",
    updatedAt: "2026-09-06T08:48:11+04:00",
    site: "riviera",
    image: "/covers/the-junction-riviera-leaves-by-is-being-rebuilt.jpg",
    imageAlt: "Two paper roads with dashed lane markings crossing at right angles on a clear mid-blue ground, the pale blue one carried over the chalk-white one on a ramp",
    imageKind: "generated",
    imageWidth: 1536,
    imageHeight: 864,
    title: "The junction most of Riviera leaves by is being rebuilt",
    cardTitle: "Riviera's exit junction gets rebuilt",
    titleSeo: "Riviera's exit junction rebuild",
    summary:
      "RTA's second Al Meydan Street contract covers First Al Khail Street through Al Khail Road to Muscat Street, with a flyover interchange and cycle underpasses. Done by end-2028.",
    date: "2026-09-03",
    category: "Infrastructure",
    source: {
      name: "Dubai Government Media Office",
      url: "https://www.mediaoffice.ae/en/news/2026/august/30-08/rta-maydan-street",
      verifiedOn: "2026-09-03",
    },
    body: [
      "There are only so many ways out of Riviera, and the RTA has just put a contract on the busiest of them.",
      "## The relevant half of the award",
      "On <strong>30 August</strong> the RTA awarded two contracts on Al Meydan Street worth <strong>Dh1.161 billion</strong> together. The one that touches Riviera is the second: <strong>Al Meydan Street from First Al Khail Street, across Al Khail Road, to Muscat Street</strong>.",
      "It builds a <strong>grade-separated interchange at Al Meydan Street and Muscat Street</strong> — <strong>1,400 metres of bridges</strong>, rated at <strong>14,400 vehicles an hour</strong> — and adds roughly <strong>2 kilometres</strong> of new surface road linking through to Latifa bint Hamdan Street.",
      "## The part that is not about cars",
      "The same contract includes an <strong>integrated cycling network with underpasses</strong>. Riviera's own paths currently stop where the arterial roads start; underpasses are what turns them into a route rather than a loop.",
      "## The timetable",
      "<strong>End of 2028.</strong> Both contracts run to the same date.",
      "## The wider figures",
      "Across both contracts the RTA is rebuilding about <strong>17 kilometres</strong> of road and <strong>3,700 metres</strong> of bridges, claiming an <strong>18% increase</strong> in north–south capacity and a run from the Dubai–Al Ain Road to Umm Suqeim cut from <strong>30 minutes to 10</strong>. <strong>Mattar Al Tayer</strong>, the RTA's Director General, called the street one of Dubai's key strategic corridors.",
    ],
    expertise:
      "For a Riviera resident the honest reading is that the benefit is 2028 and the cost is now. Al Khail Road crossings are where the queues form on this stretch, and the fix for that is precisely the structure being built — which means the works sit on the exact movement most affected. Worth planning around: the Meydan Road approach is the alternative while the Muscat Street interchange is under construction, and it is the same approach that carries racecourse traffic on Friday evenings from November onwards. The cycle underpasses are the sleeper item here; if they are delivered as described they connect Riviera's paths to Meydan and Nad Al Sheba for the first time.",
  },

  {
    slug: "a-waitrose-opens-on-the-other-side-of-meydan",
    createdAt: "2026-09-03T07:30:21+04:00",
    updatedAt: "2026-09-06T08:48:11+04:00",
    site: "riviera",
    image: "/covers/a-waitrose-opens-on-the-other-side-of-meydan.jpg",
    imageAlt: "A small chalk-white shopfront on a clear mid-blue ground with a pale sky awning and a sand-coloured basket beside it",
    imageKind: "generated",
    imageWidth: 1536,
    imageHeight: 864,
    title: "A Waitrose opens on the other side of Meydan",
    cardTitle: "A Waitrose opens past Meydan",
    titleSeo: "A Waitrose opens across Meydan",
    summary:
      "Nad Al Sheba Gardens Mall opened in August: two storeys, a Waitrose anchor, cafés, fitness space and a nursery, inside a gated community east of the racecourse.",
    date: "2026-09-03",
    category: "Nearby",
    source: {
      name: "Retail & Leisure International",
      url: "https://www.rli.uk.com/new-mall-to-open-in-dubai-in-august/",
      verifiedOn: "2026-09-03",
    },
    body: [
      "Riviera's weekly shop has always meant choosing a direction rather than a shop. There is now one more direction.",
      "## What opened",
      "<strong>Nad Al Sheba Gardens Mall</strong>, a <strong>two-storey</strong> community scheme, opened in <strong>August 2026</strong> inside the Nad Al Sheba Gardens residential district — east of Meydan, on the far side of the racecourse from Riviera.",
      "## The anchor",
      "<strong>Waitrose</strong>, operating in the UAE under Spinneys' licence. Early tenants alongside it include <strong>Kokoro Handroll Bar</strong> and <strong>Bake My Day</strong>.",
      "## The rest of it",
      "Cafés and restaurants, health and fitness space, and a <strong>nursery</strong>. It is a neighbourhood centre by design, not a mall.",
      "## Who built it",
      "The community is <strong>developed by Meraas</strong> and <strong>owned by Shamal</strong>, whose CEO <strong>Abdulla Binhabtoor</strong> describes the district as a calm environment rather than a busy one. Nad Al Sheba Gardens sits about <strong>ten minutes from Downtown Dubai</strong>.",
    ],
    expertise:
      "The distance is short and the route is not. Nad Al Sheba Gardens is close to Riviera as the crow flies but the racecourse and its approach roads sit between them, so the drive is longer than the map suggests and is worst on race evenings from November. Judge it on what it is: a two-storey community centre inside a gated villa district, which means a genuinely good supermarket, a handful of cafés, and very little else — the kind of place that replaces a grocery run rather than an afternoon. Whether it is worth the trip from Riviera depends almost entirely on whether you want the Waitrose specifically, because everything else in it exists closer to home.",
  },

  {
    slug: "ras-al-khor-switches-to-winter-hours",
    createdAt: "2026-09-02T14:56:31+04:00",
    updatedAt: "2026-09-06T08:48:11+04:00",
    site: "riviera",
    image: "/covers/ras-al-khor-switches-to-winter-hours.jpg",
    imageAlt: "Three thin sand-coloured stems rising between a pale sky and a band of blue water",
    imageKind: "generated",
    imageWidth: 1536,
    imageHeight: 864,
    title: "The flamingo hide four kilometres away changes its hours on 1 October",
    cardTitle: "Ras Al Khor goes back to winter hours",
    titleSeo: "Ras Al Khor goes to winter hours",
    summary:
      "From October the sanctuary opens 7:30am to 5:30pm, and the birds that make it worth the trip start arriving in numbers. Entry and all three hides are free.",
    date: "2026-09-02",
    category: "Nearby",
    source: {
      name: "Visit Dubai",
      url: "https://www.visitdubai.com/en/places-to-visit/ras-al-khor-wildlife-sanctuary",
      verifiedOn: "2026-09-02",
    },
    body: [
      "Riviera's nearest genuinely wild place is four kilometres away at the head of the creek, and it is about to become worth visiting again.",
      "## The change",
      "<strong>Ras Al Khor Wildlife Sanctuary</strong> runs <strong>7:30am to 5:30pm from October to March</strong>, and <strong>6:00am to 6:00pm from April to September</strong>. <strong>Entry is free.</strong>",
      "There are <strong>three bird hides</strong> around the perimeter, free to enter and open daily — the <strong>Mangrove Hide</strong> to the south and the <strong>Flamingo Hide</strong> to the west being the two normally open.",
      "## What the winter hours actually mean",
      "The summer schedule opens at six in the morning because six in the morning is the only tolerable hour. The winter one starts ninety minutes later and closes half an hour earlier, which sounds like less access and is in practice a great deal more: the whole of a winter afternoon is usable, and the light at the end of it is the best the site gets.",
      "## The birds",
      "Flamingos are present year round, but the numbers move. Winter is when the population is large enough that the hide is looking at a flock rather than at a handful of birds, and it is the reason the sanctuary has a season at all in the way residents talk about it.",
      "## The part that is still open",
      "A development programme covering roughly <strong>6.4 square kilometres</strong> of the sanctuary has its first phase due for completion by the end of 2026, at a reported cost of <strong>Dh650 million</strong>. What that changes about public access has not been set out, and nothing here assumes it.",
    ],
    expertise:
      "The Flamingo Hide on the western edge is the one reachable from the MBR City side without going round the creek, which is what makes this a local trip from Riviera rather than a half-day. Hides face fixed directions, so the light matters more than the hour: the western hide has the sun behind the viewer in the afternoon and straight into the lens in the morning. Neither hide takes bookings and neither has shade on the approach.",
  },

  {
    slug: "dubai-completed-104-projects-in-six-months",
    createdAt: "2026-09-01T15:07:36+04:00",
    updatedAt: "2026-09-06T08:48:11+04:00",
    site: "riviera",
    image: "/covers/dubai-completed-104-projects-in-six-months.jpg",
    imageAlt: "Three finished paper buildings with their scaffolding peeled away and folded beside them",
    imageKind: "generated",
    imageWidth: 1536,
    imageHeight: 864,
    title: "104 projects finished in six months",
    summary:
      "Dubai completed 104 real estate projects in the first half of 2026 — up 52% — delivering more than 24,000 units worth around Dh111 billion.",
    date: "2026-08-20",
    category: "Development",
    source: {
      name: "Gulf News",
      url: "https://gulfnews.com/business/property/dubai-adds-more-than-24000-property-units-in-six-months-1.500646931",
      verifiedOn: "2026-09-01",
    },
    body: [
      "Launches are announcements; completions are handovers. Only one of the two puts keys in anyone’s hand, and the first half of 2026 was unusually good at the second kind.",
      "## The numbers",
      "<strong>104 real estate projects</strong> were completed in Dubai between January and June 2026, a <strong>52% increase</strong> on the same period a year earlier. Those projects added <strong>more than 24,000</strong> residential and commercial units, up <strong>36%</strong> year on year, with an investment value of around <strong>Dh111 billion</strong>.",
      "Sheikh Hamdan bin Mohammed bin Rashid Al Maktoum, Crown Prince of Dubai and Deputy Prime Minister, said the projects «added more than 24,000 new real estate units in Dubai, up 36% compared with last year».",
      "## Why the completion rate matters more than the launch rate",
      "Every off-plan market in the world can produce launch numbers. The question a buyer holding a 2027 handover date actually needs answered is whether this city’s contractors, utilities connections and inspection authorities can absorb the volume already sold.",
      "A 52% rise in completions against a 36% rise in units says something specific: the average completed project got <strong>smaller</strong>. More buildings, each delivering fewer homes. That is what a market looks like when mid-sized developers are finishing, rather than a handful of large towers landing at once.",
      "## What it does not tell you",
      "A completion figure is city-wide. It says nothing about whether a particular community got its promised retail, its landscaping, or its second access road — the parts that arrive after the handover certificate and are not counted in anyone’s half-year total.",
    ],
    expertise:
      "For anyone tracking a handover, the useful document is not the city-wide figure but the project’s own completion percentage on the Dubai Land Department’s project register, which is updated from the consultant’s reports rather than the developer’s marketing. A project sitting at the same percentage across two quarters is the signal worth acting on.",
  },
  {
    slug: "azizi-riviera-final-handover-phase",
    createdAt: "2026-08-25T18:18:34+04:00",
    updatedAt: "2026-09-06T08:48:11+04:00",
    site: "riviera",
    // Layout appends " — Azizi Riviera Guide".
    title: "Riviera's final handover phase",
    summary:
      "Azizi has entered the last stage of delivery at Riviera: 53 of the 75 buildings handed over, all of phases 1 to 3 complete, and the remaining 22 buildings scheduled through Q2 2026.",
    date: "2025-08-13",
    category: "Development",
    image: "/news/azizi-riviera-handover.svg",
    imageAlt:
      "The Azizi Riviera promenade at night: lit low-rise blocks along the canal.",
    imageKind: "diagram",
    imageCredit: "DST",
    imageWidth: 1200,
    imageHeight: 640,
    source: {
      name: "Middle East Construction News",
      url: "https://meconstructionnews.com/64270/azizi-riviera-in-mbr-city-enters-final-stage-of-delivery",
      verifiedOn: "2026-08-25",
    },
    body: [
      "Azizi has moved Riviera into its final stage of delivery. Of the 75 buildings in the master plan, <strong>53 had been handed over</strong> — all of phases 1, 2 and 3, plus five buildings from phase 4 — with the remaining 22 scheduled through the second quarter of 2026.",
      "Named handovers in that run included Riviera 63 in March, Riviera 61 in June, and Riviera 67 and Riviera 65 on July 1 and July 21. Azure was slated for August and Riviera 52 for September, with the rest of phase 4 following behind them.",
      "Completed, Riviera comes to roughly 16,000 residences across mid- and high-rise buildings along the canal.",
    ],
    expertise:
      "For anyone living here, the practical effect of a late-phase building is not the handover date itself but what surrounds it: a block that completes while neighbouring plots are still finishing gets construction noise, partial promenade retail, and a thinner set of open ground-floor units than the same building will have a year later. That gap has been closing steadily as phase 4 lands. Worth noting that the Q2 2026 target above comes from the August 2025 announcement — check the current position on any specific building before signing for it.",
    related: [
      {
        href: "/rent/",
        image: "/riviera.jpg",
        imageAlt: "The Azizi Riviera promenade at night: lit low-rise blocks along the canal.",
        title: "Renting in Riviera",
        text: "Matching a block to what matters — canal view, courtyard, distance from the promenade.",
        eyebrow: "Rent",
      },
    ],
  },
];
