import type { NewsItem } from "../types.ts";

export const items: NewsItem[] = [

  {
    slug: "solana-slots-are-250ms-and-every-block-limit-came-down-with-them",
    createdAt: "2026-09-22T02:48:00+04:00",
    updatedAt: "2026-09-22T02:48:00+04:00",
    site: "sol2go",
    image: "/covers/solana-slots-are-250ms-and-every-block-limit-came-down-with-them.jpg",
    imageAlt: "A pale square cut into upright strips of differing widths in mint, cream and grey-blue, standing together on a lilac ground",
    imageKind: "generated",
    imageWidth: 1536,
    imageHeight: 864,
    title: "Solana slots are 250ms now, and every per-block limit came down with them",
    cardTitle: "250ms slots, and smaller blocks",
    titleSeo: "Solana slot time is 250ms: what scaled with it",
    summary:
      "Solana cut its slot time to 250ms at epoch 1037 on 18 September, the fourth of five steps towards 200ms. Per-block compute fell from 60 million units to 37.5 million with it, so what this buys is latency, not capacity.",
    date: "2026-09-18",
    category: "Upgrades",
    featured: 1,
    source: {
      name: "Solana Compass",
      url: "https://solanacompass.com/news/solana-activates-250ms-slot-time-at-epoch-1037-fourth-step-of-simd-0525",
      verifiedOn: "2026-09-22",
    },
    body: [
      "A faster block is not a bigger one. Solana has just made its blocks arrive more often, and made each of them smaller by exactly as much — which is the part of the change that reaches anyone who has written a compute budget.",
      "## What went live, and when",
      "Slot time on mainnet dropped to <strong>250 milliseconds</strong> at the <strong>epoch 1037</strong> boundary, <strong>05:06 UTC on 18 September 2026</strong>. It is the <strong>fourth of five steps</strong> in <strong>SIMD-0525</strong>, which walks the network down from <strong>400ms</strong> to a <strong>200ms</strong> target. The 350ms step landed on 19 August at epoch 1019 and the 300ms step on 25 August at epoch 1023.",
      "## A gate that activates before it does anything",
      "The feature gate was <strong>pending at epoch 1035</strong>, went <strong>active at the epoch 1036 boundary</strong>, and <strong>first applied to block production at epoch 1037</strong>. That is not a delay and not a bug: gates under SIMD-0525 take effect one epoch after they activate. Anyone reading the explorer on the day the gate went active would have seen an upgrade that was switched on and changing nothing, and been right both times.",
      "## What came down with the slot",
      "Each step scales the per-slot resource limits in proportion, so the per-second execution budget stays roughly where it was. Against the 400ms baseline that means <strong>maximum block compute units fall from 60 million to 37.5 million</strong> and <strong>maximum data and coding shreds per slot from 32,768 to 20,480</strong>. A leader still gets four consecutive slots, but the window is now <strong>1.0 second</strong> rather than the 1.2 it was at 300ms and the 1.6 it was at the start. An epoch now runs <strong>roughly 30 hours</strong> instead of about 48, and the <strong>Validator Admission Ticket costs 1.0 SOL per epoch</strong>, down from 1.6.",
      "## The Foundation's own page has not caught up",
      "Solana's upgrade page for reduced slot times still lists the 250ms gate as live on devnet and testnet with a mainnet date “to be determined”, while the changelog of 18 September lists it among the notable mainnet gates. The changelog is the one that matches the chain.",
      "## What is left",
      "One step: <strong>200ms</strong>, with <strong>no announced activation date</strong>. Each stage is watched under production load before the next is queued, so the gap between steps is the observation, not the paperwork.",
    ],
    faq: [
      {
        q: "When did Solana's 250ms slot time go live?",
        a: "At the <strong>epoch 1037</strong> boundary, <strong>05:06 UTC on 18 September 2026</strong>, on mainnet.",
      },
      {
        q: "Does a shorter slot mean Solana can process more?",
        a: "No. Per-slot limits scale down in proportion, so the per-second budget is roughly unchanged. What improves is how soon a block arrives, not how much fits in an hour.",
      },
      {
        q: "How much compute does a block have now?",
        a: "<strong>37.5 million compute units</strong> at 250ms, against 60 million at the original 400ms slot.",
      },
      {
        q: "Is 250ms the end of it?",
        a: "No — <strong>200ms</strong> is the final step of SIMD-0525, and no activation date has been announced for it.",
      },
    ],
    expertise:
      "The number to design against is 37.5 million, not 250 milliseconds. A transaction that fit comfortably in a 60-million-unit block has had its share of the block quietly grow by sixty per cent, and at 200ms it will grow again — so anything already landing near the top of a block's budget is on a path to not landing at all, and it will fail on a day when nothing about the transaction changed. The staged rollout is the place to catch that: each step is observed under real load before the next is queued, which means there is a window between gates long enough to measure your own worst block against the new ceiling rather than discover it.",
  },


  {
    slug: "project-harmonia-opens-an-rfp-with-allfunds",
    createdAt: "2026-09-21T15:25:00+04:00",
    updatedAt: "2026-09-21T15:25:00+04:00",
    site: "sol2go",
    image: "/covers/project-harmonia-opens-an-rfp-with-allfunds.jpg",
    imageAlt: "Horizontal paper bands across the frame, with a wide lens-shaped overlap where two of them meet at the centre",
    imageKind: "generated",
    imageWidth: 1536,
    imageHeight: 864,
    title: "Project Harmonia opens an RFP connecting Allfunds to tokenized funds on Solana",
    cardTitle: "Project Harmonia opens its RFP",
    titleSeo: "Project Harmonia: Allfunds and Solana funds",
    summary:
      "Submissions close on 24 October. Two tracks, no admission fees, and a first cohort targeted to go live across Allfunds and Solana in Q4 2026 and Q1 2027.",
    date: "2026-09-21",
    category: "Institutional",
    source: {
      name: "Solana",
      url: "https://solana.com/news",
      verifiedOn: "2026-09-21",
    },
    body: [
      "Distribution is the part of fund management that nobody tokenizes, because it is not a ledger problem. <strong>Project Harmonia</strong> is an attempt at it anyway: an <strong>RFP</strong>, announced on <strong>16 September 2026</strong>, connecting <strong>Allfunds</strong> with tokenized funds on <strong>Solana</strong>.",
      "## What Allfunds is",
      "The world's largest fund distribution network: <strong>more than 3,300 asset managers and financial institutions</strong>, and <strong>roughly EUR 1.9 trillion in assets under administration</strong> as of <strong>30 June 2026</strong>.",
      "## The two tracks",
      "<strong>Track A</strong> is for funds already live on Solana. <strong>Track B</strong> is for funds still in development, admitted on a <strong>rolling basis over six to twelve months</strong>. There are <strong>no admission fees</strong> for either.",
      "## The dates",
      "<strong>Submissions close 24 October 2026.</strong> The first cohort is targeted to go live across Allfunds and Solana in <strong>Q4 2026 and Q1 2027</strong>.",
      "## Where this sits",
      "Solana already carries <strong>more than USD 4 billion in institutional real-world assets onchain</strong>. What this adds is not another issuance venue but a route into an existing distribution network — which is the step that decides whether a tokenized fund has buyers or only a token.",
    ],
    faq: [
      {
        q: "When does the Project Harmonia RFP close?",
        a: "<strong>24 October 2026</strong>. The first cohort is targeted to go live in <strong>Q4 2026 and Q1 2027</strong>.",
      },
      {
        q: "Is there a fee to apply?",
        a: "No — the RFP states <strong>no admission fees</strong> for either track.",
      },
      {
        q: "What is the difference between Track A and Track B?",
        a: "<strong>Track A</strong> is for funds already live on Solana; <strong>Track B</strong> is for funds in development, admitted on a rolling basis over six to twelve months.",
      },
    ],
    expertise:
      "The number worth holding on to here is not the EUR 1.9 trillion but the six-to-twelve-month rolling window on Track B, because it says what the bottleneck is expected to be. Issuing a tokenized share class is fast; getting it accepted by the systems a distributor's clients already use is not, and a rolling admission over a year is an organiser saying so in advance. Read this as infrastructure work with a deadline attached, not as a launch.",
  },
  {
    slug: "alpenglow-now-has-dates-and-the-first-one-is-a-stake-percentage",
    createdAt: "2026-09-06T09:36:42+04:00",
    updatedAt: "2026-09-08T00:12:45+04:00",
    site: "sol2go",
    image: "/covers/alpenglow-now-has-dates-and-the-first-one-is-a-stake-percentage.jpg",
    imageAlt: "Four lilac paper bars of increasing height on a deep violet ground, the tallest one topped with a small pale mint square",
    imageKind: "generated",
    imageWidth: 1536,
    imageHeight: 864,
    title: "Alpenglow finally has dates, and the first one is a stake percentage",
    cardTitle: "Alpenglow: the rollout calendar",
    titleSeo: "Alpenglow rollout: the Agave 4.3 dates",
    summary:
      "Anza's release schedule puts 10 per cent of stake on Agave 4.3 by 8 September, 25 per cent by 14 September, general adoption by 21 September and feature activation from 28 September.",
    date: "2026-09-07",
    category: "Upgrades",
    source: {
      name: "Anza, via Solana Compass",
      url: "https://solanacompass.com/news/anza-publishes-agave-43-release-schedule-alpenglow-consensus-targets-september-28-mainnet-activation",
      verifiedOn: "2026-09-07",
    },
    body: [
      "A consensus change does not ship on a date. It ships on a percentage, and the date is only when someone decides the percentage is high enough.",
      "## The schedule",
      "<strong>Anza</strong> has published the rollout for <strong>Agave 4.3</strong>: <strong>10 per cent</strong> of stake by <strong>8 September</strong>, <strong>25 per cent</strong> by <strong>14 September</strong>, general adoption recommended by <strong>21 September</strong>, and feature activation beginning <strong>28 September</strong>.",
      "## Why the week of silence in the middle matters",
      "The network runs 4.3 widely for a week before anything in it switches on. That week is the whole safety argument: if the release is going to misbehave under real load, it does so while the old consensus is still the one deciding what is final.",
      "## What activates",
      "<strong>Alpenglow</strong> replaces <strong>Tower BFT</strong> as the voting protocol and keeps <strong>Proof of History</strong> as the ordering mechanism. <strong>Votor</strong> finalises in two rounds, and on the fast path — <strong>80 per cent</strong> of stake agreeing — a block is final in roughly <strong>150 milliseconds</strong>.",
      "## The date is a start, not a finish",
      "<strong>28 September</strong> is when feature activation <em>begins</em>. Completion across the network is expected to run into October, which is why the same upgrade is honestly described with two different months.",
    ],
    expertise:
      "The number to watch through September is not the calendar, it is the stake curve against it — 10, 25 and general are targets, and a validator set that lags them is the signal that something in the release is unpleasant to run rather than that operators are slow. Alpenglow's fast path needs 80 per cent of stake voting in agreement, so a rollout that stalls at, say, 70 per cent does not fail; it simply falls back to the slower path and the 150-millisecond figure quietly stops applying. That is the failure mode to expect if anything goes wrong: not an outage, but a network that has activated the upgrade and is not getting the headline number from it.",
  },

  {
    slug: "rent-came-down-and-every-account-is-now-over-funded",
    createdAt: "2026-09-06T09:36:42+04:00",
    updatedAt: "2026-09-08T00:12:45+04:00",
    site: "sol2go",
    image: "/covers/rent-came-down-and-every-account-is-now-over-funded.jpg",
    imageAlt: "A tall stack of flat violet paper coins with the top third lifted clear of the rest",
    imageKind: "generated",
    imageWidth: 1536,
    imageHeight: 864,
    title: "Rent came down, and every account is now over-funded",
    cardTitle: "Rent came down. Your accounts are over-funded",
    titleSeo: "Rent fell: how to reclaim excess SOL",
    summary:
      "Solana cut rent, so every existing account now holds more SOL than it needs. A new Token Program instruction takes the surplus out without closing anything — and this is only phase one of five.",
    date: "2026-09-04",
    category: "Upgrades",
    featured: 1,
    source: {
      name: "Solana Foundation",
      url: "https://solana.com/news/how-to-reclaim-excess-sol-after-rent-reduction",
      verifiedOn: "2026-09-06",
    },
    body: [
      "Rent on Solana is a deposit, not a fee: an account holds a minimum balance to stay alive, and gets it back when it closes. Lower the minimum and nothing breaks — but every account that was funded under the old rule is now carrying more SOL than it needs, and nobody is going to hand it back on their own.",
      "## What changed",
      "The Foundation's own framing: rent “is getting cheaper, and that means you and your users are now sitting on excess lamports that can be reclaimed.” This is the <strong>first phase of a five-phase rent reduction roll-out</strong>, so the same surplus will appear again, four more times.",
      "## How you get it out",
      "The Token Program gained a <strong>WithdrawExcessLamports</strong> instruction. It “recovers SOL sitting above the rent-exempt minimum from a token account, mint, or multisig account — without touching token balances and without closing the account.” The program computes the source account's rent-exempt floor and moves everything above it to a destination you name.",
      "It requires authorisation from the account's authority: the owner for a token account, the mint authority or the mint itself for a mint.",
      "## Why this is worth an afternoon",
      "Individually the amounts are small. In aggregate they are not: a protocol holding tens of thousands of token accounts has a real balance sheet line sitting in rent-exempt floors that no longer exist. The accounts that matter most are the ones you opened on behalf of users, because that surplus is theirs and they have no way to know it is there.",
      "## The part not yet published",
      "The announcement does not name the SIMD or the feature gate that carried the change, nor the old and new lamports-per-byte rates, nor the dates of the remaining four phases. We are not filling those in.",
    ],
    expertise:
      "The design decision worth noticing is that this is an instruction rather than an automatic refund. A protocol change that silently moved lamports out of accounts would be a change to balances that no wallet asked for, and on a chain where a rent-exempt floor is load-bearing for account survival that is exactly the kind of automatic behaviour that produces closed accounts nobody intended to close. Making it opt-in puts the decision with whoever holds the authority — which also means that in five phases' time there will be a long tail of accounts nobody ever swept, and the total sitting in them will be a genuinely interesting number.",
  },

  {
    slug: "before-solana-gets-150ms-finality-two-gates-had-to-open",
    createdAt: "2026-09-06T09:36:42+04:00",
    updatedAt: "2026-09-06T14:57:39+04:00",
    site: "sol2go",
    image: "/covers/before-solana-gets-150ms-finality-two-gates-had-to-open.jpg",
    imageAlt: "Two narrow violet paper gates standing open in front of a long mint arrow crossing the frame",
    imageKind: "generated",
    imageWidth: 1536,
    imageHeight: 864,
    title: "Before Solana gets 150ms finality, two gates had to open",
    cardTitle: "The two gates Alpenglow needed first",
    titleSeo: "What Alpenglow needed before 150ms",
    summary:
      "Alpenglow targets roughly 150ms finality on Solana against today's 12.8 seconds. Two prerequisite feature gates went live on mainnet in July; the consensus change itself reaches devnet in Agave 4.3.",
    date: "2026-09-02",
    category: "Upgrades",
    featured: 2,
    source: {
      name: "Solana Foundation",
      url: "https://solana.com/upgrades/alpenglow",
      verifiedOn: "2026-09-06",
    },
    body: [
      "Alpenglow is the largest change to how Solana agrees with itself since the chain launched, and the headline number is the one everyone repeats. The number underneath it is the one that explains why this has taken a year.",
      "## The 150ms target, in numbers",
      "The Foundation states the target plainly: “roughly 150ms finality, compared with Solana's current roughly 400ms pre-confirmation latency and 12.8-second TowerBFT finality.” The 400ms figure is the one applications already feel. The 12.8 seconds is the one that matters to anything settling value, and it is the one Alpenglow is aimed at.",
      "More broadly, Alpenglow “makes changes to how Solana thinks about blockspace, finality, voting, and rewards” — four things at once, which is why it does not ship as a single switch.",
      "## What already happened",
      "<strong>BLS Pubkey Management in Vote Account (SIMD-0387)</strong> activated on mainnet on <strong>8 July 2026</strong>. The <strong>Validator Admission Ticket (SIMD-0357)</strong> activated on mainnet on <strong>22 July 2026</strong>. Neither turns Alpenglow on. They are the plumbing it needs to exist before the consensus change can be switched at all.",
      "## What has not happened yet",
      "Devnet activation is listed against <strong>Agave 4.3</strong>, and expected mainnet activation against <strong>Q3 2026</strong> — a quarter that ends this month. Read those two lines together and the honest summary is that the schedule is tight and the page has not been updated to say otherwise.",
      "## What to do about it",
      "If you run a validator, the July gates are already behind you and 4.3 is the release to be reading. If you build applications, nothing in your code changes on activation day — but a finality budget you wrote around 12.8 seconds is a design assumption worth revisiting rather than inheriting.",
    ],
    expertise:
      "The interesting thing about a two-stage rollout like this is what it tells you about the risk model. Both July gates are additive: a BLS public key in a vote account and an admission ticket are new fields and new checks, and neither changes what the network agrees is true. The consensus switch is not additive, and it is the only part that can split the network if it goes wrong — so it is deliberately last, deliberately on devnet first, and deliberately separated from the plumbing by three months. Anyone reading the July activations as “Alpenglow is live” has read the changelog and not the design.",
  },
];
