import type { NewsItem } from "../types.ts";

// Armenian first, English in `i18n.en` — see the note in ../events/tick.ts.

export const items: NewsItem[] = [

  {
    slug: "yerevan-2808th-anniversary-2026",
    createdAt: "2026-10-09T10:00:00+04:00",
    updatedAt: "2026-10-09T12:30:00+04:00",
    site: "tick",
    date: "2026-10-09",
    title: "Երևանի 2808-ամյակը. յոթ բեմի ծրագիրը՝ հոկտեմբերի 9–10-ին",
    cardTitle: "Երևանի օր. յոթ բեմ, յոթ երաժշտական ուղղություն",
    titleSeo: "Երևանի օրը՝ հոկտեմբերի 9–10-ի համերգների ծրագիր",
    summary:
      "Հոկտեմբերի 9-ին Դիանա Աբգարի այգում ելույթ կունենան Դիանա Արբենինան և «Նոչնիե սնայպերի»-ն։ Հոկտեմբերի 10-ին յոթ բեմ կաշխատի քաղաքի տարբեր հատվածներում՝ ջազից ու ռոքից մինչև ազգային, դասական և էլեկտրոնային երաժշտություն։",
    image: "/covers/yerevan-2808th-anniversary-2026.jpg",
    imageAlt: "Երևանի 2808-ամյակի նարնջագույն և կարմիր տոնական պաստառը՝ հոկտեմբերի 9–10-ի ամսաթվերով",
    imageKind: "illustration",
    imageCredit: "Երևանի քաղաքապետարան",
    imageWidth: 523,
    imageHeight: 349,
    category: "Երևան",
    city: "Երևան",
    country: "Հայաստան",
    source: {
      name: "Visit Yerevan՝ Երևանի պաշտոնական զբոսաշրջային կայք",
      url: "https://visityerevan.am/blog/details/156/am/",
      verifiedOn: "2026-10-09",
    },
    body: [
      "«Էրեբունի-Երևան 2808»-ի երկօրյա երաժշտական ծրագիրը քաղաքի տարբեր հրապարակներում ու այգիներում է։ Հոկտեմբերի 9-ի գլխավոր համերգը Դիանա Աբգարի անվան զբոսայգում է, իսկ հոկտեմբերի 10-ին միաժամանակ կաշխատի յոթ բեմ։ Միջոցառումների ուղեցույցը հրապարակել է Visit Yerevan-ը՝ Երևանի պաշտոնական զբոսաշրջային կայքը։",
      "## Հոկտեմբերի 9․ ռոք և գարեջրի փառատոն · <a href=\"https://www.google.com/maps/search/?api=1&amp;query=Diana+Abgar+Park%2C+Yerevan%2C+Armenia\" target=\"_blank\" rel=\"noopener noreferrer\">📍 Քարտեզ</a>",
      "Դիանա Աբգարի անվան զբոսայգում գարեջրի փառատոնը սկսվում է ժամը 16:00-ին։ Ժամը 21:00-ին բեմ կբարձրանան Դիանա Արբենինան և «Նոչնիե սնայպերի» խումբը։",
      "## Հոկտեմբերի 10․ յոթ բեմ ամբողջ քաղաքում",
      "## Փոփ․ Շառլ Ազնավուրի հրապարակ, 12:00–18:00 · <a href=\"https://www.google.com/maps/search/?api=1&amp;query=Charles+Aznavour+Square%2C+Yerevan%2C+Armenia\" target=\"_blank\" rel=\"noopener noreferrer\">📍 Քարտեզ</a>",
      "Ծրագրում են Արամ MP3-ը, Mohana Band-ը, D'Litte-ը, Project 12-ը, Yellow Heart-ը, Kami Friends-ը և այլ կատարողներ։",
      "## Ջազ․ Կասկադի Գաֆէսճեան քանդակների պարտեզ, 13:00–22:00 · <a href=\"https://www.google.com/maps/search/?api=1&amp;query=Cafesjian+Sculpture+Garden%2C+Yerevan%2C+Armenia\" target=\"_blank\" rel=\"noopener noreferrer\">📍 Քարտեզ</a>",
      "Ելույթ կունենան Հայաստանի պետական ջազ նվագախումբը, Karen Manukyan Trio-ն, Վահագն Հայրապետյանի The Armenian Colors Quartet-ը, Արտյոմ Մանուկյան տրիոն, Malkhas Jazz Trio-ն և այլ երաժիշտներ։ Հատուկ հյուր FKJ-ի ելույթը նախատեսված է 20:00-ին։",
      "## Ռոք․ Դիանա Աբգարի անվան զբոսայգի, 13:00–23:00 · <a href=\"https://www.google.com/maps/search/?api=1&amp;query=Diana+Abgar+Park%2C+Yerevan%2C+Armenia\" target=\"_blank\" rel=\"noopener noreferrer\">📍 Քարտեզ</a>",
      "Բեմում կլինեն FairWind-ը, Another Story-ն, The Beautified Project-ը, «Լավ էլի»-ն, «Նեմրան», «Բամբիռը» և այլ հայկական խմբեր։ Գարեջրի փառատոնը կշարունակվի զբոսայգում։",
      "## Ազգային երաժշտություն և գինի․ Հյուսիսային պողոտա · <a href=\"https://www.google.com/maps/search/?api=1&amp;query=Northern+Avenue%2C+Yerevan%2C+Armenia\" target=\"_blank\" rel=\"noopener noreferrer\">📍 Քարտեզ</a>",
      "Երաժշտական ծրագիրը 13:00–18:00 է, իսկ գինու փառատոնը՝ 12:00–23:00։ Հանդես կգան Սոնա Ռուբենյանը, Արփին և Highway Band-ը, «Թմբաթան», Ethno Colors-ը, «Ակունք» պետական ազգագրական համույթը, «Զվարթնոց» քանոնահարների անսամբլը և ազգային երգի ու պարի խմբեր։",
      "## Ռեփ․ Անգլիական այգի, 17:00–22:00 · <a href=\"https://www.google.com/maps/search/?api=1&amp;query=English+Park%2C+Yerevan%2C+Armenia\" target=\"_blank\" rel=\"noopener noreferrer\">📍 Քարտեզ</a>",
      "Համերգին կմասնակցեն A Chilla-ն, ՎՆԱՍ-ը, ԴԱՎ-ը, GALIFE-ը, Նարեկ Մեծ Հայքը, «Միշտ Հասարակ»-ը, 47-ը, Ֆելոն և Սերժոն։",
      "## Դասական և սիմֆոնիկ ֆոլք․ Ազատության հրապարակ, 17:00–20:30 · <a href=\"https://www.google.com/maps/search/?api=1&amp;query=Freedom+Square%2C+Yerevan%2C+Armenia\" target=\"_blank\" rel=\"noopener noreferrer\">📍 Քարտեզ</a>",
      "«Սիմֆոնիկ ֆոլք» ծրագրում հանդես կգան «Երևան» երիտասարդական նվագախումբը, Հայաստանի պետական սիմֆոնիկ նվագախումբը, Երևանի պետական կամերային երգչախումբը և «Կամերտոն» վոկալ ստուդիան։",
      "## Էլեկտրոնային երաժշտություն․ Հանրապետության հրապարակ, 17:00–23:00 · <a href=\"https://www.google.com/maps/search/?api=1&amp;query=Republic+Square+Singing+Fountains%2C+Yerevan%2C+Armenia\" target=\"_blank\" rel=\"noopener noreferrer\">📍 Քարտեզ</a>",
      "Երգող շատրվանների հարևանությամբ նվագելու են Guevo Aka Kai-ը, Roob-ը, Socko-ն և Alber Ensso-ն։ Հատուկ հյուր Vanco-ի ելույթը նախատեսված է 21:30-ին։",
      "Քաղաքապետարանի նախնական հայտարարությունը նաև հիշատակում է մանկական գոտի, սակայն հրապարակված ուղեցույցում դրա առանձին հասցեն ու ժամերը նշված չեն։",
    ],
    faq: [
      { q: "Ե՞րբ է նշվում Երևանի 2808-ամյակը", a: "Քաղաքապետարանի հրապարակած ծրագրի հիմնական միջոցառումները տեղի են ունենում հոկտեմբերի 9-ին և 10-ին։" },
      { q: "Որտե՞ղ է ուրբաթ օրվա ծրագիրը", a: "Հոկտեմբերի 9-ին միջոցառումները սկսվում են ժամը 16:00-ին Դիանա Աբգարի անվան այգում։" },
      { q: "Որտե՞ղ և ե՞րբ է ելույթ ունենալու FKJ-ը", a: "Հոկտեմբերի 10-ին՝ ժամը 20:00-ին, Կասկադի ջազի բեմում։" },
      { q: "Որտե՞ղ և ե՞րբ է ելույթ ունենալու Vanco-ն", a: "Հոկտեմբերի 10-ին՝ ժամը 21:30-ին, Հանրապետության հրապարակի էլեկտրոնային բեմում։" },
    ],
    i18n: {
      en: {
        imageAlt: "Orange and red Yerevan 2,808th anniversary poster with the 9–10 October dates",
        imageCredit: "Yerevan Municipality",
        title: "Yerevan's 2,808th anniversary: seven stages on 9–10 October",
        cardTitle: "Yerevan City Day: seven stages, seven sounds",
        titleSeo: "Yerevan City Day: concert programme for 9–10 October",
        summary:
          "Diana Arbenina and Night Snipers play Diana Abgar Park on 9 October. On 10 October, seven stages across the city span jazz, rock, Armenian music, pop, rap, classical and electronic music.",
        category: "Yerevan",
        city: "Yerevan",
        country: "Armenia",
        body: [
          "The two-day Erebuni-Yerevan 2808 programme spreads concerts across the city's squares and parks. Diana Abgar Park hosts the main concert on 9 October; seven stages operate across Yerevan on 10 October. The detailed guide is published by Visit Yerevan, the city's official tourism website.",
          "## 9 October: rock and a beer festival · <a href=\"https://www.google.com/maps/search/?api=1&amp;query=Diana+Abgar+Park%2C+Yerevan%2C+Armenia\" target=\"_blank\" rel=\"noopener noreferrer\">📍 Map</a>",
          "The beer festival at Diana Abgar Park starts at 16:00. Diana Arbenina and Night Snipers take the stage at 21:00.",
          "## 10 October: seven stages across the city",
          "## Pop — Charles Aznavour Square, 12:00–18:00 · <a href=\"https://www.google.com/maps/search/?api=1&amp;query=Charles+Aznavour+Square%2C+Yerevan%2C+Armenia\" target=\"_blank\" rel=\"noopener noreferrer\">📍 Map</a>",
          "The line-up includes Aram MP3, Mohana Band, D'Litte, Project 12, Yellow Heart, Kami Friends and others.",
          "## Jazz — Cafesjian Sculpture Garden at the Cascade, 13:00–22:00 · <a href=\"https://www.google.com/maps/search/?api=1&amp;query=Cafesjian+Sculpture+Garden%2C+Yerevan%2C+Armenia\" target=\"_blank\" rel=\"noopener noreferrer\">📍 Map</a>",
          "Performers include the Armenian State Jazz Orchestra, Karen Manukyan Trio, Vahagn Hayrapetyan's The Armenian Colors Quartet, Artyom Manukyan Trio, Malkhas Jazz Trio and others. Special guest FKJ is scheduled for 20:00.",
          "## Rock — Diana Abgar Park, 13:00–23:00 · <a href=\"https://www.google.com/maps/search/?api=1&amp;query=Diana+Abgar+Park%2C+Yerevan%2C+Armenia\" target=\"_blank\" rel=\"noopener noreferrer\">📍 Map</a>",
          "FairWind, Another Story, The Beautified Project, Lav Eli, Nemra, Bambir and other Armenian acts are on the bill. The beer festival continues in the park.",
          "## Armenian music and wine — Northern Avenue · <a href=\"https://www.google.com/maps/search/?api=1&amp;query=Northern+Avenue%2C+Yerevan%2C+Armenia\" target=\"_blank\" rel=\"noopener noreferrer\">📍 Map</a>",
          "Music runs from 13:00 to 18:00; the wine festival is open from 12:00 to 23:00. The programme includes Sona Rubenyan, Arpi & Highway Band, Tmbata, Ethno Colors, Akunk State Ethnographic Ensemble, Zvartnots Qanun Ensemble and folk song and dance groups.",
          "## Rap — English Park, 17:00–22:00 · <a href=\"https://www.google.com/maps/search/?api=1&amp;query=English+Park%2C+Yerevan%2C+Armenia\" target=\"_blank\" rel=\"noopener noreferrer\">📍 Map</a>",
          "A Chilla, VNAS, Dav, GALIFE, Narek Mets Hayk, Misht Hasarak, 47, Felo and Serjo perform.",
          "## Classical and Symphonic Folk — Freedom Square, 17:00–20:30 · <a href=\"https://www.google.com/maps/search/?api=1&amp;query=Freedom+Square%2C+Yerevan%2C+Armenia\" target=\"_blank\" rel=\"noopener noreferrer\">📍 Map</a>",
          "The Symphonic Folk programme features the Yerevan Youth Orchestra, Armenian State Symphony Orchestra, Yerevan State Chamber Choir and Kamerton Vocal Studio.",
          "## Electronic — Republic Square, 17:00–23:00 · <a href=\"https://www.google.com/maps/search/?api=1&amp;query=Republic+Square+Singing+Fountains%2C+Yerevan%2C+Armenia\" target=\"_blank\" rel=\"noopener noreferrer\">📍 Map</a>",
          "Guevo Aka Kai, Roob, Socko and Alber Ensso play near the Singing Fountains. Special guest Vanco is scheduled for 21:30.",
          "City Hall's earlier announcement also mentions a children's area, but the published guide does not give its location or hours.",
        ],
        faq: [
          { q: "When is Yerevan's 2,808th anniversary celebration?", a: "The main programme published by the city runs on 9 and 10 October." },
          { q: "Where does Friday's programme begin?", a: "At 16:00 on 9 October in Diana Abgar Park." },
          { q: "Where and when does FKJ perform?", a: "At 20:00 on 10 October on the Cascade jazz stage." },
          { q: "Where and when does Vanco perform?", a: "At 21:30 on 10 October on the electronic stage at Republic Square." },
        ],
      },
    },
  },
  {
    slug: "discover-armenia-from-the-sky-balloon-festival-2026",
    createdAt: "2026-10-09T10:00:00+04:00",
    updatedAt: "2026-10-09T10:00:00+04:00",
    site: "tick",
    date: "2026-10-09",
    title: "Փուչիկների միջազգային փառատոնը Երևանում շարունակվում է մինչև հոկտեմբերի 11-ը",
    cardTitle: "Երևանի երկնքում՝ 20 օդապարիկ",
    titleSeo: "Օդապարիկների փառատոնը Երևանում՝ մինչև հոկտեմբերի 11-ը",
    summary:
      "«Բացահայտիր Հայաստանը երկնքից» փառատոնի ութերորդ թողարկումը հոկտեմբերի 6–11-ն է․ Visit Yerevan-ը Երևանի թռիչքները նշում է առավոտյան ժամը 08:00-ին։",
    image: "/covers/discover-armenia-balloon-festival-2026.jpg",
    imageAlt: "Discover Armenia from the Sky փառատոնի պաստառը՝ Արարատի ֆոնին թռչող գունավոր օդապարիկներով",
    imageKind: "illustration",
    imageCredit: "Visit Yerevan",
    imageWidth: 1280,
    imageHeight: 720,
    category: "Փառատոներ",
    city: "Երևան",
    country: "Հայաստան",
    source: {
      name: "Visit Yerevan",
      url: "https://www.visityerevan.am/browse/events/en/",
      verifiedOn: "2026-10-09",
    },
    body: [
      "«Բացահայտիր Հայաստանը երկնքից» միջազգային օդապարիկների փառատոնի ութերորդ թողարկումն անցկացվում է հոկտեմբերի 6–11-ը։ Visit Yerevan-ի միջոցառումների էջը հոկտեմբերի 9-ին, 10-ին և 11-ին Երևանի համար նշում է առավոտյան ժամը 08:00-ը։",
      "Կազմակերպիչ Skyball-ի փառատոնը հավաքում է 20 օդապարիկ՝ Հայաստանից և այլ երկրներից։ Այն իրականացվում է ՀՀ էկոնոմիկայի նախարարության Զբոսաշրջության կոմիտեի աջակցությամբ։",
      "Visit Yerevan-ի էջում հրապարակված է միջոցառման ընդհանուր նկարագրությունը, բայց թռիչքի ճշգրիտ մեկնարկային վայրը և դիտման պայմանները նշված չեն․ դրանք ճշտեք կազմակերպչից մեկնելուց առաջ։",
    ],
    faq: [
      { q: "Մինչև ե՞րբ է անցկացվում օդապարիկների փառատոնը", a: "Հոկտեմբերի 6-ից 11-ը, 2026։" },
      { q: "Քանի՞ օդապարիկ է մասնակցում", a: "Visit Yerevan-ը նշում է 20 օդապարիկ Հայաստանից և այլ երկրներից։" },
      { q: "Որտե՞ղ ճշտել թռիչքի վայրը", a: "Visit Yerevan-ի հրապարակումը մեկնարկային վայրը չի նշում․ ճշտեք Skyball-ից մինչև գնալը։" },
    ],
    i18n: {
      en: {
        imageAlt: "Discover Armenia from the Sky festival poster with colourful balloons flying over Mount Ararat",
        imageCredit: "Visit Yerevan",
        title: "Yerevan's balloon festival runs until 11 October",
        cardTitle: "Twenty balloons over Yerevan",
        titleSeo: "Yerevan balloon festival runs until 11 October",
        summary:
          "The eighth Discover Armenia from the Sky festival runs from 6 to 11 October; Visit Yerevan lists its city flights at 08:00.",
        category: "Festivals",
        city: "Yerevan",
        country: "Armenia",
        body: [
          "The eighth Discover Armenia from the Sky international balloon festival runs from 6 to 11 October. Visit Yerevan's event listing gives 08:00 for the Yerevan dates on 9, 10 and 11 October.",
          "Organised by Skyball with support from the Tourism Committee of Armenia's Ministry of Economy, the festival brings together twenty balloons from Armenia and abroad.",
          "Visit Yerevan's listing does not give the precise launch site or viewing arrangements. Check with the organiser before setting out.",
        ],
        faq: [
          { q: "When does the balloon festival end?", a: "It runs from 6 to 11 October 2026." },
          { q: "How many balloons are taking part?", a: "Visit Yerevan lists twenty balloons from Armenia and abroad." },
          { q: "Where do the balloons launch from?", a: "The Visit Yerevan listing does not say; check with Skyball before going." },
        ],
      },
    },
  },

  {
    slug: "yerevan-fashion-week-2026",
    createdAt: "2026-10-04T15:00:00+04:00",
    updatedAt: "2026-10-09T12:00:00+04:00",
    site: "tick",
    date: "2026-10-01",
    title: "Yerevan Fashion Week 2026. ցուցադրություններ, Fashion Talks և բաց շոուրում",
    cardTitle: "Yerevan Fashion Week-ը՝ հոկտեմբերի 8–11-ին",
    titleSeo: "Yerevan Fashion Week 2026-ը՝ Էրեբունիում և Տերյան 91-ում",
    summary:
      "Հոկտեմբերի 8–11-ի ծրագիրը միավորում է Էրեբունիում բացվող «Հին աստվածներ» ցուցահանդեսը, 20-ից ավելի ցուցադրություն, Fashion Talks և հոկտեմբերի 9–11-ի անվճար շոուրումը Տերյան 91-ում։",
    image: "/covers/yerevan-fashion-week-2026.jpg",
    imageAlt: "Երկու զգեստ մանեկենների վրա՝ կարմիր և սպիտակ, բլրի վրայի հին ամրոցի պարսպի առջև",
    imageKind: "generated",
    imageWidth: 1536,
    imageHeight: 864,
    category: "Նորաձևություն",
    city: "Երևան",
    country: "Հայաստան",
    source: { name: "ՀՀ կրթության, գիտության, մշակույթի և սպորտի նախարարություն", url: "https://escs.gov.am/articles/news/400", verifiedOn: "2026-10-09" },
    body: [
      "Հայաստանի նորաձևության պալատի կազմակերպած Yerevan Fashion Week-ը չորրորդ անգամ է անցկացվում՝ հոկտեմբերի 8–11-ը։ ՀՀ կրթության, գիտության, մշակույթի և սպորտի նախարարության աջակցությամբ ու Երևանի քաղաքապետարանի հովանավորությամբ այս տարվա հայեցակարգն է «Վարդագույն քաղաք Երևան»-ը։ Ծրագիրը միավորում է ավելի քան 20 ցուցադրություն, ցուցահանդեսներ, հատուկ ինստալյացիաներ և մասնագիտական հանդիպումներ։",
      "## Բացումը՝ Էրեբունիում",
      "Հոկտեմբերի 8-ի բացման առանցքում Էրեբունի պատմահնագիտական արգելոց-թանգարանն ու ամրոցն են։ «Հին աստվածներ․ Էրեբունուց մինչև ժամանակակից Երևան» խորագրով ցուցադրությունում շուրջ 30 մանեկեն կներկայացնի հայ երիտասարդ դիզայներների աշխատանքները։ Հավաքածուները ներշնչված են հայկական դիցաբանությամբ, խորհրդանիշերով ու պատմական կերպարներով. նորաձևությունն այստեղ երկխոսում է հնագիտական միջավայրի, երաժշտության և մշակութային ժառանգության հետ։",
      "## Երիտասարդ դիզայներների մրցույթը",
      "Fashion Scout Armenia-ի չորրորդ թողարկման համար ստացվել է 75 հայտ, և միջազգային ժյուրին ընտրել է եզրափակչի մասնակիցներին։ Նրանք իրենց հավաքածուները կներկայացնեն հոկտեմբերի 9-ին՝ ժամը 11:00-ին, Տերյան 91 հասցեում։ Գլխավոր մրցանակը հաղթողին հնարավորություն կտա ցուցադրվել Լոնդոնի Fashion Scout-ում. նախատեսված են նաև Երևանի քաղաքապետի 1 միլիոն դրամ մրցանակը և Polimoda-ի ամառային դասընթացի կրթաթոշակը։",
      "## Շոուրում և քննարկումներ",
      "Հոկտեմբերի 9–11-ը Տերյան 91-ում գործող YFW Showroom-ը բաց է հանրության համար՝ անվճար մուտքով։ Այցելուները կարող են ծանոթանալ հայկական բրենդների հավաքածուներին և հանդիպել դիզայներներին։ Fashion Talks-ի տասը քննարկումները հայ և միջազգային մասնագետների հետ անդրադառնում են շուկա մուտք գործելուն, ձեռներեցությանը, կայունությանը, տեխնոլոգիաներին և նորաձևության ապագային։",
      "Միջազգային հյուրերի թվում են Vogue, Harper’s BAZAAR, ELLE, FashionUnited, Metal Magazine և Fucking Young! պարբերականների ներկայացուցիչներ, ինչպես նաև լրագրողներ, ոճաբաններ, բայերներ ու PR մասնագետներ։",
    ],
    faq: [
      { q: "Ե՞րբ է Yerevan Fashion Week 2026-ը", a: "Հոկտեմբերի 8-ից 11-ը, Երևանում։" },
      { q: "Որտե՞ղ է YFW Showroom-ը և վճարովի՞ է մուտքը", a: "Տերյան 91 հասցեում՝ հոկտեմբերի 9–11-ը. մուտքն ազատ է։" },
      { q: "Ե՞րբ և որտե՞ղ է Fashion Scout Armenia-ի եզրափակիչը", a: "Հոկտեմբերի 9-ին՝ ժամը 11:00-ին, Տերյան 91 հասցեում։" },
    ],
    i18n: {
      en: {
        imageAlt: "Two dresses on dress forms, one red and one cream, before an ancient fortress wall on a hill",
        title: "Yerevan Fashion Week 2026: shows, Fashion Talks and a public showroom",
        cardTitle: "Yerevan Fashion Week, 8–11 October",
        titleSeo: "Yerevan Fashion Week 2026 at Erebuni and 91 Teryan Street",
        summary:
          "The 8–11 October programme pairs the Old Gods exhibition at Erebuni with 20+ shows, Fashion Talks and a free public showroom at 91 Teryan Street from 9 to 11 October.",
        category: "Fashion",
        city: "Yerevan",
        country: "Armenia",
        body: [
          "The Fashion Chamber of Armenia is staging the fourth Yerevan Fashion Week from 8 to 11 October, with support from Armenia's Ministry of Education, Science, Culture and Sport and sponsorship from Yerevan Municipality. This year's theme is Pink City Yerevan. The programme brings together more than twenty shows, exhibitions, special installations and industry events.",
          "## An opening at Erebuni",
          "The 8 October opening takes place at the Erebuni Historical and Archaeological Museum-Reserve and fortress. The Old Gods: From Erebuni to Modern Yerevan exhibition presents work by young Armenian designers on around thirty mannequins. Drawing on Armenian mythology, symbols and historical figures, it brings fashion into conversation with the archaeological setting, music and cultural heritage.",
          "## Fashion Scout Armenia final",
          "The competition's fourth edition received 75 applications, and an international jury selected the finalists. They present their collections at 11:00 on 9 October at 91 Teryan Street. The main prize offers a showcase at Fashion Scout in London, alongside a one-million-dram Yerevan mayor's prize and a scholarship for a summer course at Polimoda.",
          "## Showroom and talks",
          "The YFW Showroom at 91 Teryan Street is open to the public with free entry from 9 to 11 October. Visitors can explore Armenian labels and meet designers. Ten Fashion Talks with Armenian and international experts cover market entry, entrepreneurship, sustainability, technology and fashion's future.",
          "International guests include representatives of Vogue, Harper's BAZAAR, ELLE, FashionUnited, Metal Magazine and Fucking Young!, as well as independent journalists, stylists, buyers and PR professionals.",
        ],
        faq: [
          { q: "When is Yerevan Fashion Week 2026?", a: "From 8 to 11 October, in Yerevan." },
          { q: "Where is the YFW Showroom, and is entry free?", a: "At 91 Teryan Street from 9 to 11 October; entry is free." },
          { q: "When and where is the Fashion Scout Armenia final?", a: "At 11:00 on 9 October at 91 Teryan Street." },
        ],
      },
    },
  },
];
