import type { NewsItem } from "../types.ts";

// Armenian first, English in `i18n.en` — see the note in ../events/tick.ts.

export const items: NewsItem[] = [

  {
    slug: "yerevan-2808th-anniversary-2026",
    createdAt: "2026-10-09T10:00:00+04:00",
    updatedAt: "2026-10-09T10:00:00+04:00",
    site: "tick",
    date: "2026-10-08",
    title: "Երևանը նշում է հիմնադրման 2808-ամյակը՝ համերգներով ու փառատոներով",
    cardTitle: "Երևանի 2808-ամյակը՝ հոկտեմբերի 9–10-ին",
    titleSeo: "Երևանի 2808-ամյակը՝ համերգներ և փառատոներ",
    summary:
      "Երևանի քաղաքապետարանը հրապարակել է հոկտեմբերի 9–10-ի ծրագիրը․ Դիանա Աբգարի այգում՝ գարեջրի փառատոն ու Դիանա Արբենինայի համերգ, հաջորդ օրը՝ երաժշտական բեմեր ամբողջ քաղաքում։",
    image: "/covers/yerevan-2808th-anniversary-2026.jpg",
    imageAlt: "Երևանի 2808-ամյակի նարնջագույն և կարմիր տոնական պաստառը՝ հոկտեմբերի 9–10-ի ամսաթվերով",
    imageKind: "illustration",
    imageCredit: "Երևանի քաղաքապետարան",
    imageWidth: 523,
    imageHeight: 349,
    category: "Երևան",
    city: "Երևան",
    country: "Հայաստան",
    source: {
      name: "Երևանի քաղաքապետարան",
      url: "https://www.yerevan.am/hy/news/se-r-to-n-erewa-n-miasin-nshenk-mayrak-aghak-i-2808-amyake/",
      verifiedOn: "2026-10-09",
    },
    body: [
      "Երևանի քաղաքապետարանը հրապարակել է մայրաքաղաքի 2808-ամյակին նվիրված՝ հոկտեմբերի 9–10-ի միջոցառումների ծրագիրը։",
      "## Ուրբաթ՝ Դիանա Աբգարի այգում",
      "Հոկտեմբերի 9-ին՝ ժամը 16:00-ից, այգում կսկսվի գարեջրի փառատոնը։ Երեկոյան նախատեսված է DJ համերգ, իսկ օրվա հատուկ հյուրն է Դիանա Արբենինան՝ մենահամերգով։",
      "## Շաբաթ՝ բեմեր քաղաքի տարբեր հատվածներում",
      "Հոկտեմբերի 10-ին՝ կեսօրից, Երևանի տարբեր հատվածներում նախատեսված են ջազի, ռոքի, էլեկտրոնային, ռեփի, դասական, ազգային և էստրադային համերգներ, մանկական գոտի, գինու և գարեջրի փառատոներ։ Քաղաքապետարանի հայտարարած հատուկ հյուրերն են VANCO-ն և FKJ-ը։",
      "Հրապարակված հայտարարության մեջ շաբաթ օրվա առանձին բեմերի հասցեներն ու ժամային ամբողջական ծրագիրը նշված չեն։",
    ],
    faq: [
      { q: "Ե՞րբ է նշվում Երևանի 2808-ամյակը", a: "Քաղաքապետարանի հրապարակած ծրագրի հիմնական միջոցառումները տեղի են ունենում հոկտեմբերի 9-ին և 10-ին։" },
      { q: "Որտե՞ղ է ուրբաթ օրվա ծրագիրը", a: "Հոկտեմբերի 9-ին միջոցառումները սկսվում են ժամը 16:00-ին Դիանա Աբգարի անվան այգում։" },
      { q: "Ովքե՞ր են շաբաթ օրվա հատուկ հյուրերը", a: "Քաղաքապետարանի հայտարարության համաձայն՝ VANCO-ն և FKJ-ը։" },
    ],
    i18n: {
      en: {
        imageAlt: "Orange and red Yerevan 2,808th anniversary poster with the 9–10 October dates",
        imageCredit: "Yerevan Municipality",
        title: "Yerevan marks its 2,808th anniversary with concerts and festivals",
        cardTitle: "Yerevan's 2,808th anniversary, 9–10 October",
        titleSeo: "Yerevan's 2,808th anniversary: concerts and festivals",
        summary:
          "The city has published its 9–10 October programme: a beer festival and Diana Arbenina in Diana Abgar Park on Friday, then music stages across Yerevan on Saturday.",
        category: "Yerevan",
        city: "Yerevan",
        country: "Armenia",
        body: [
          "Yerevan City Hall has published the programme for the capital's 2,808th anniversary, with celebrations on 9 and 10 October.",
          "## Friday in Diana Abgar Park",
          "The beer festival begins at 16:00 on 9 October. A DJ set follows, with Diana Arbenina as the evening's special guest for a solo concert.",
          "## Saturday across the city",
          "From midday on 10 October, different parts of Yerevan are to host jazz, rock, electronic, rap, classical, folk and pop concerts, alongside a children's area and wine and beer festivals. The special guests named by the municipality are VANCO and FKJ.",
          "The announcement does not give the individual Saturday stage addresses or a full timetable.",
        ],
        faq: [
          { q: "When is Yerevan's 2,808th anniversary celebration?", a: "The main programme published by the city runs on 9 and 10 October." },
          { q: "Where does Friday's programme begin?", a: "At 16:00 on 9 October in Diana Abgar Park." },
          { q: "Who are Saturday's special guests?", a: "VANCO and FKJ, according to the municipality's announcement." },
        ],
      },
    },
  },
  {
    slug: "discover-armenia-from-the-sky-balloon-festival-2026",
    createdAt: "2026-10-09T10:00:00+04:00",
    updatedAt: "2026-10-09T10:00:00+04:00",
    site: "tick",
    date: "2026-10-09",
    title: "Փուչիկների միջազգային փառատոնը Երևանում շարունակվում է մինչև հոկտեմբերի 11-ը",
    cardTitle: "Երևանի երկնքում՝ 20 օդապարիկ",
    titleSeo: "Օդապարիկների փառատոնը Երևանում՝ մինչև հոկտեմբերի 11-ը",
    summary:
      "«Բացահայտիր Հայաստանը երկնքից» փառատոնի ութերորդ թողարկումը հոկտեմբերի 6–11-ն է․ Visit Yerevan-ը Երևանի թռիչքները նշում է առավոտյան ժամը 08:00-ին։",
    image: "/covers/discover-armenia-balloon-festival-2026.jpg",
    imageAlt: "Discover Armenia from the Sky փառատոնի պաստառը՝ Արարատի ֆոնին թռչող գունավոր օդապարիկներով",
    imageKind: "illustration",
    imageCredit: "Visit Yerevan",
    imageWidth: 1280,
    imageHeight: 720,
    category: "Փառատոներ",
    city: "Երևան",
    country: "Հայաստան",
    source: {
      name: "Visit Yerevan",
      url: "https://www.visityerevan.am/browse/events/en/",
      verifiedOn: "2026-10-09",
    },
    body: [
      "«Բացահայտիր Հայաստանը երկնքից» միջազգային օդապարիկների փառատոնի ութերորդ թողարկումն անցկացվում է հոկտեմբերի 6–11-ը։ Visit Yerevan-ի միջոցառումների էջը հոկտեմբերի 9-ին, 10-ին և 11-ին Երևանի համար նշում է առավոտյան ժամը 08:00-ը։",
      "Կազմակերպիչ Skyball-ի փառատոնը հավաքում է 20 օդապարիկ՝ Հայաստանից և այլ երկրներից։ Այն իրականացվում է ՀՀ էկոնոմիկայի նախարարության Զբոսաշրջության կոմիտեի աջակցությամբ։",
      "Visit Yerevan-ի էջում հրապարակված է միջոցառման ընդհանուր նկարագրությունը, բայց թռիչքի ճշգրիտ մեկնարկային վայրը և դիտման պայմանները նշված չեն․ դրանք ճշտեք կազմակերպչից մեկնելուց առաջ։",
    ],
    faq: [
      { q: "Մինչև ե՞րբ է անցկացվում օդապարիկների փառատոնը", a: "Հոկտեմբերի 6-ից 11-ը, 2026։" },
      { q: "Քանի՞ օդապարիկ է մասնակցում", a: "Visit Yerevan-ը նշում է 20 օդապարիկ Հայաստանից և այլ երկրներից։" },
      { q: "Որտե՞ղ ճշտել թռիչքի վայրը", a: "Visit Yerevan-ի հրապարակումը մեկնարկային վայրը չի նշում․ ճշտեք Skyball-ից մինչև գնալը։" },
    ],
    i18n: {
      en: {
        imageAlt: "Discover Armenia from the Sky festival poster with colourful balloons flying over Mount Ararat",
        imageCredit: "Visit Yerevan",
        title: "Yerevan's balloon festival runs until 11 October",
        cardTitle: "Twenty balloons over Yerevan",
        titleSeo: "Yerevan balloon festival runs until 11 October",
        summary:
          "The eighth Discover Armenia from the Sky festival runs from 6 to 11 October; Visit Yerevan lists its city flights at 08:00.",
        category: "Festivals",
        city: "Yerevan",
        country: "Armenia",
        body: [
          "The eighth Discover Armenia from the Sky international balloon festival runs from 6 to 11 October. Visit Yerevan's event listing gives 08:00 for the Yerevan dates on 9, 10 and 11 October.",
          "Organised by Skyball with support from the Tourism Committee of Armenia's Ministry of Economy, the festival brings together twenty balloons from Armenia and abroad.",
          "Visit Yerevan's listing does not give the precise launch site or viewing arrangements. Check with the organiser before setting out.",
        ],
        faq: [
          { q: "When does the balloon festival end?", a: "It runs from 6 to 11 October 2026." },
          { q: "How many balloons are taking part?", a: "Visit Yerevan lists twenty balloons from Armenia and abroad." },
          { q: "Where do the balloons launch from?", a: "The Visit Yerevan listing does not say; check with Skyball before going." },
        ],
      },
    },
  },

  {
    slug: "yerevan-fashion-week-2026",
    createdAt: "2026-10-04T15:00:00+04:00",
    updatedAt: "2026-10-09T12:00:00+04:00",
    site: "tick",
    date: "2026-10-01",
    title: "Yerevan Fashion Week 2026. ցուցադրություններ, Fashion Talks և բաց շոուրում",
    cardTitle: "Yerevan Fashion Week-ը՝ հոկտեմբերի 8–11-ին",
    titleSeo: "Yerevan Fashion Week 2026-ը՝ Էրեբունիում և Տերյան 91-ում",
    summary:
      "Հոկտեմբերի 8–11-ի ծրագիրը միավորում է Էրեբունիում բացվող «Հին աստվածներ» ցուցահանդեսը, 20-ից ավելի ցուցադրություն, Fashion Talks և հոկտեմբերի 9–11-ի անվճար շոուրումը Տերյան 91-ում։",
    image: "/covers/yerevan-fashion-week-2026.jpg",
    imageAlt: "Երկու զգեստ մանեկենների վրա՝ կարմիր և սպիտակ, բլրի վրայի հին ամրոցի պարսպի առջև",
    imageKind: "generated",
    imageWidth: 1536,
    imageHeight: 864,
    category: "Նորաձևություն",
    city: "Երևան",
    country: "Հայաստան",
    source: { name: "ՀՀ կրթության, գիտության, մշակույթի և սպորտի նախարարություն", url: "https://escs.gov.am/articles/news/400", verifiedOn: "2026-10-09" },
    body: [
      "Հայաստանի նորաձևության պալատի կազմակերպած Yerevan Fashion Week-ը չորրորդ անգամ է անցկացվում՝ հոկտեմբերի 8–11-ը։ ՀՀ կրթության, գիտության, մշակույթի և սպորտի նախարարության աջակցությամբ ու Երևանի քաղաքապետարանի հովանավորությամբ այս տարվա հայեցակարգն է «Վարդագույն քաղաք Երևան»-ը։ Ծրագիրը միավորում է ավելի քան 20 ցուցադրություն, ցուցահանդեսներ, հատուկ ինստալյացիաներ և մասնագիտական հանդիպումներ։",
      "## Բացումը՝ Էրեբունիում",
      "Հոկտեմբերի 8-ի բացման առանցքում Էրեբունի պատմահնագիտական արգելոց-թանգարանն ու ամրոցն են։ «Հին աստվածներ․ Էրեբունուց մինչև ժամանակակից Երևան» խորագրով ցուցադրությունում շուրջ 30 մանեկեն կներկայացնի հայ երիտասարդ դիզայներների աշխատանքները։ Հավաքածուները ներշնչված են հայկական դիցաբանությամբ, խորհրդանիշերով ու պատմական կերպարներով. նորաձևությունն այստեղ երկխոսում է հնագիտական միջավայրի, երաժշտության և մշակութային ժառանգության հետ։",
      "## Երիտասարդ դիզայներների մրցույթը",
      "Fashion Scout Armenia-ի չորրորդ թողարկման համար ստացվել է 75 հայտ, և միջազգային ժյուրին ընտրել է եզրափակչի մասնակիցներին։ Նրանք իրենց հավաքածուները կներկայացնեն հոկտեմբերի 9-ին՝ ժամը 11:00-ին, Տերյան 91 հասցեում։ Գլխավոր մրցանակը հաղթողին հնարավորություն կտա ցուցադրվել Լոնդոնի Fashion Scout-ում. նախատեսված են նաև Երևանի քաղաքապետի 1 միլիոն դրամ մրցանակը և Polimoda-ի ամառային դասընթացի կրթաթոշակը։",
      "## Շոուրում և քննարկումներ",
      "Հոկտեմբերի 9–11-ը Տերյան 91-ում գործող YFW Showroom-ը բաց է հանրության համար՝ անվճար մուտքով։ Այցելուները կարող են ծանոթանալ հայկական բրենդների հավաքածուներին և հանդիպել դիզայներներին։ Fashion Talks-ի տասը քննարկումները հայ և միջազգային մասնագետների հետ անդրադառնում են շուկա մուտք գործելուն, ձեռներեցությանը, կայունությանը, տեխնոլոգիաներին և նորաձևության ապագային։",
      "Միջազգային հյուրերի թվում են Vogue, Harper’s BAZAAR, ELLE, FashionUnited, Metal Magazine և Fucking Young! պարբերականների ներկայացուցիչներ, ինչպես նաև լրագրողներ, ոճաբաններ, բայերներ ու PR մասնագետներ։",
    ],
    faq: [
      { q: "Ե՞րբ է Yerevan Fashion Week 2026-ը", a: "Հոկտեմբերի 8-ից 11-ը, Երևանում։" },
      { q: "Որտե՞ղ է YFW Showroom-ը և վճարովի՞ է մուտքը", a: "Տերյան 91 հասցեում՝ հոկտեմբերի 9–11-ը. մուտքն ազատ է։" },
      { q: "Ե՞րբ և որտե՞ղ է Fashion Scout Armenia-ի եզրափակիչը", a: "Հոկտեմբերի 9-ին՝ ժամը 11:00-ին, Տերյան 91 հասցեում։" },
    ],
    i18n: {
      en: {
        imageAlt: "Two dresses on dress forms, one red and one cream, before an ancient fortress wall on a hill",
        title: "Yerevan Fashion Week 2026: shows, Fashion Talks and a public showroom",
        cardTitle: "Yerevan Fashion Week, 8–11 October",
        titleSeo: "Yerevan Fashion Week 2026 at Erebuni and 91 Teryan Street",
        summary:
          "The 8–11 October programme pairs the Old Gods exhibition at Erebuni with 20+ shows, Fashion Talks and a free public showroom at 91 Teryan Street from 9 to 11 October.",
        category: "Fashion",
        city: "Yerevan",
        country: "Armenia",
        body: [
          "The Fashion Chamber of Armenia is staging the fourth Yerevan Fashion Week from 8 to 11 October, with support from Armenia's Ministry of Education, Science, Culture and Sport and sponsorship from Yerevan Municipality. This year's theme is Pink City Yerevan. The programme brings together more than twenty shows, exhibitions, special installations and industry events.",
          "## An opening at Erebuni",
          "The 8 October opening takes place at the Erebuni Historical and Archaeological Museum-Reserve and fortress. The Old Gods: From Erebuni to Modern Yerevan exhibition presents work by young Armenian designers on around thirty mannequins. Drawing on Armenian mythology, symbols and historical figures, it brings fashion into conversation with the archaeological setting, music and cultural heritage.",
          "## Fashion Scout Armenia final",
          "The competition's fourth edition received 75 applications, and an international jury selected the finalists. They present their collections at 11:00 on 9 October at 91 Teryan Street. The main prize offers a showcase at Fashion Scout in London, alongside a one-million-dram Yerevan mayor's prize and a scholarship for a summer course at Polimoda.",
          "## Showroom and talks",
          "The YFW Showroom at 91 Teryan Street is open to the public with free entry from 9 to 11 October. Visitors can explore Armenian labels and meet designers. Ten Fashion Talks with Armenian and international experts cover market entry, entrepreneurship, sustainability, technology and fashion's future.",
          "International guests include representatives of Vogue, Harper's BAZAAR, ELLE, FashionUnited, Metal Magazine and Fucking Young!, as well as independent journalists, stylists, buyers and PR professionals.",
        ],
        faq: [
          { q: "When is Yerevan Fashion Week 2026?", a: "From 8 to 11 October, in Yerevan." },
          { q: "Where is the YFW Showroom, and is entry free?", a: "At 91 Teryan Street from 9 to 11 October; entry is free." },
          { q: "When and where is the Fashion Scout Armenia final?", a: "At 11:00 on 9 October at 91 Teryan Street." },
        ],
      },
    },
  },
];
