import type { NewsItem } from "../types.ts";

export const items: NewsItem[] = [
  {
    slug: "warum-die-biologische-uhr-nach-vier-wochen-stehen-blieb",
    site: "vien",
    image: "/covers/warum-die-biologische-uhr-nach-vier-wochen-stehen-blieb.jpg",
    imageAlt: "Drei gleich hohe rote Papierkarten auf cremefarbenem Grund, deren Oberkanten eine waagrechte Linie bilden, rechts davon leere Fläche",
    imageKind: "generated",
    imageWidth: 1536,
    imageHeight: 864,
    title: "Die biologische Uhr blieb nach vier Wochen stehen, obwohl das Medikament weiterarbeitete",
    cardTitle: "Der Knick in Woche vier",
    titleSeo: "Warum die Uhr nach vier Wochen stehen blieb",
    summary:
      "Sechs Modelle lasen bei behandelten Patienten ein niedrigeres biologisches Alter. Nach vier Wochen bewegte sich der Wert nicht mehr, die Proteine dagegen schon.",
    date: "2026-09-08",
    category: "Welt",
    source: {
      name: "Nature Biotechnology",
      url: "https://www.nature.com/articles/s41587-026-03286-y",
      verifiedOn: "2026-09-08",
    },
    body: [
      "Am <strong>7. September 2026</strong> erschien in <strong>Nature Biotechnology</strong> eine Auswertung, deren interessanteste Zahl nicht das Ergebnis ist, sondern ein Zeitpunkt. In Woche vier war der gemessene Effekt am größten. Danach passierte nichts mehr.",
      "Gemessen wurde an 42 Teilnehmenden einer klinischen Studie, deren Blut zu Beginn und in den Wochen 2, 4 und 12 auf rund 2.800 Proteine untersucht wurde. Sechs verschiedene Modelle schätzten daraus ein biologisches Alter. Alle sechs lasen in den behandelten Gruppen einen niedrigeren Wert als zu Studienbeginn, die Placebogruppe blieb unverändert oder wurde geringfügig älter.",
      "## Kein Rückfall, ein Plateau",
      "Zwischen Woche vier und Woche zwölf gingen die Werte nicht wieder hinauf. Sie standen. Kein einziger Vergleich zwischen diesen beiden Zeitpunkten ergab eine nennenswerte Verschiebung, in keiner Gruppe und mit keinem der Modelle. Das ist ein Unterschied, der zählt: ein Rückfall würde bedeuten, dass die Wirkung nachlässt, ein Plateau bedeutet, dass sie sich nicht weiter vertieft.",
      "Rätselhaft wird es durch die zweite Beobachtung. Die Proteinveränderungen selbst waren keineswegs vorübergehend. In den beiden wirksameren Dosierungsgruppen waren nur fünf bis neun Prozent der Verschiebungen kurzlebig, alle übrigen entwickelten sich bis Woche zwölf weiter. Und ausgerechnet jene Proteine, aus denen die Modelle ihr Alter berechnen, gehörten überdurchschnittlich häufig zu den dauerhaften.",
      "Die Bestandteile der Rechnung bewegten sich also weiter, das Ergebnis der Rechnung nicht.",
      "## Drei Erklärungen, keine bestätigt",
      "Die Autorinnen und Autoren bieten drei Möglichkeiten an und entscheiden sich für keine. Erstens könnten Gegenregulationen einsetzen, ähnlich wie Tumorzellen auf eine dauerhafte Hemmung reagieren. Zweitens könnte der leicht erreichbare Teil der gealterten Zellen schlicht aufgebraucht sein. Drittens könnte es ein Artefakt der Messung sein: Ein statistisches Modell, das aus Proteinmengen Jahre macht, muss nicht linear weiterlaufen, nur weil sich seine Eingangswerte weiterbewegen.",
      "Aus allen drei Möglichkeiten folgt derselbe praktische Vorschlag, und er ist ungewöhnlich: Pausen. Wenn der Effekt an eine Anpassung stößt, könnte eine unterbrochene Gabe mehr bringen als eine durchgehende.",
      "## Was sich sonst verschob",
      "Unabhängig von der Uhr fielen zwei Signalgruppen auf. In der Placebogruppe nahmen Marker alternder, nicht mehr teilungsfähiger Zellen deutlich zu; in allen behandelten Gruppen nahmen sie ab. Und fünf Signalwege rund um Wachstumsfaktoren, darunter PI3K-Akt und MAPK, gingen bei den Behandelten zurück und bei Placebo hinauf. Das sind genau jene Achsen, an denen auch Kalorienrestriktion und Rapamycin ansetzen.",
      "## Die Einschränkung, die alles betrifft",
      "Alle 42 Personen hatten dieselbe Lungenerkrankung, gegen die das Mittel entwickelt wurde. Mehrere der Proteine, die in den Modellen am schwersten wiegen, sind Marker eben dieser Erkrankung. Ob die Uhren eine Alterung lasen oder eine Krankheit, die zurückgeht, lässt sich innerhalb dieser Gruppe nicht klären. Die Studie sagt das selbst und verlangt eine Wiederholung an Menschen ohne diese Diagnose.",
    ],
    expertise:
      "Der Knick in Woche vier ist der Grund, warum kurze Studien bei Alterungsfragen wenig taugen. Hätte man nur zu Beginn und am Ende gemessen, wäre der stärkste Effekt der Studie überhaupt nicht sichtbar geworden, und der Bericht hätte einen schwächeren Zwölf-Wochen-Wert als Gesamtergebnis ausgewiesen. Vier Messzeitpunkte statt zwei kosten wenig und zeigen die Form der Kurve statt nur ihrer Endpunkte. Wer künftige Meldungen zu diesem Feld liest, sollte deshalb zuerst nachsehen, wie oft gemessen wurde: Ein einzelner Vorher-Nachher-Vergleich kann ein Plateau, einen Rückfall und einen anhaltenden Effekt nicht voneinander unterscheiden.",
  },

  {
    slug: "warum-claude-seit-august-jeden-satz-markiert",
    site: "vien",
    image: "/covers/warum-claude-seit-august-jeden-satz-markiert.jpg",
    imageAlt: "Eine Reihe gleich großer Papierkarten auf cremefarbenem Grund, alle in derselben Farbe, mit unterschiedlich breiten Abständen",
    imageKind: "generated",
    imageWidth: 1536,
    imageHeight: 864,
    title: "Seit August markiert Claude jeden Satz — und das Lesegerät dazu gibt es nur auf Antrag",
    cardTitle: "Claudes unsichtbare Markierung",
    titleSeo: "Claude markiert seinen Text",
    summary:
      "Anthropic versieht seit 2. August alles, was Claude schreibt, mit einer unsichtbaren Markierung. Sie steckt nicht in den Wörtern, sondern in deren Auswahl.",
    date: "2026-09-08",
    category: "Welt",
    source: {
      name: "Anthropic",
      url: "https://www.anthropic.com/news/claude-text-watermark",
      verifiedOn: "2026-09-08",
    },
    body: [
      "Eine sichtbare Markierung wäre eine löschbare Markierung. Also hat Anthropic sie dort untergebracht, wo es nichts zu löschen gibt: nicht im Text, sondern im Zufall, der ihn hervorgebracht hat.",
      "## Die Technik",
      "Bei jedem Wort stehen dem Modell mehrere gleichwertige Möglichkeiten offen, und es entscheidet mit einer Zufallszahl. Seit der Umstellung, erklärt in einem Beitrag vom <strong>14. August 2026</strong>, stammt diese Zahl aus einem <strong>geheimen Schlüssel</strong> und den bereits geschriebenen Wörtern. Der Text bleibt derselbe. Das Signal liegt im Muster der Entscheidungen — ohne Schlüssel von einem gewöhnlichen Durchlauf nicht zu unterscheiden. Das Verfahren ist eine Variante von <strong>SynthID-Text</strong>, das <strong>Google DeepMind</strong> 2024 in <strong>Nature</strong> veröffentlicht hat.",
      "## Ab wann und wo",
      "Ab <strong>2. August 2026</strong> für alle ab diesem Datum veröffentlichten Modelle, ältere folgen in den kommenden Monaten. Es gilt für die Schnittstelle ebenso wie für die Anwendungen, auch über <strong>AWS</strong>, <strong>Google Cloud</strong> und <strong>Microsoft Foundry</strong> — und zwar weltweit, nicht nur dort, wo eine Behörde danach gefragt hat. Abschalten lässt es sich nicht. Für Dateien in den Formaten <strong>.png</strong>, <strong>.jpg</strong> und <strong>.svg</strong> gibt es stattdessen signierte Herkunftsdaten nach dem <strong>C2PA</strong>-Standard.",
      "## Wer nachsehen darf",
      "Die Erkennung ist in einer <strong>geschlossenen Vorschau</strong>. Zugang gibt es auf Antrag für Behörden, Strafverfolgung, Medien, Faktenprüfer, unabhängige Forschung, Bildungseinrichtungen und zivilgesellschaftliche Organisationen in der EU sowie für Unternehmen mit eigenen Nachweispflichten. Für alle anderen gilt: die Markierung ist da, lesen kann man sie nicht.",
      "## Was sie nicht leistet",
      "Ein Treffer besagt, dass ein Text Claude <em>durchlaufen haben könnte</em> — mehr nicht. Wo dem Modell kaum Alternativen blieben, etwa bei dichten Fakten, Zahlen oder Programmcode, ist das Signal dünn; sehr kurze Texte tragen zu wenig davon. Kopieren und leichtes Überarbeiten übersteht die Markierung, eine Übersetzung oder eine gründliche Umschrift nicht.",
    ],
    expertise:
      "Der Zeitplan verrät, worum es eigentlich geht: das Datum ist kein technischer Meilenstein, sondern eine Frist, und für Modelle von vor dem 2. August gibt es ausdrücklich eine Übergangszeit. Wer in Österreich mit solchen Texten arbeitet — in Redaktionen, an Universitäten, in Verlagen — sollte daraus zwei Dinge mitnehmen. Erstens ist die Markierung kein Ersatz für die eigene Dokumentation: sie kann bestätigen, aber nicht widerlegen, und wer nichts findet, hat nichts bewiesen. Zweitens ist sie etwas grundlegend anderes als die frei zugänglichen KI-Erkenner, die Stil messen und dabei regelmäßig sauber geschriebene Texte von Menschen falsch einordnen. Die eine Methode ist eine Signatur, die andere eine Vermutung, und sie werden im Alltag ständig verwechselt.",
  },

  {
    slug: "albertina-zeigt-picasso-und-bacon-ab-18-september",
    site: "vien",
    image: "/covers/albertina-zeigt-picasso-und-bacon-ab-18-september.jpg",
    imageAlt: "Zwei ausgeschnittene Papierfiguren aus vermillionrotem und moosgrünem Papier, einander zugewandt, auf cremefarbenem Grund",
    imageKind: "generated",
    imageWidth: 1536,
    imageHeight: 864,
    title: "Die Albertina stellt Picasso und Bacon einander gegenüber — ab 18. September",
    cardTitle: "Picasso – Bacon in der Albertina",
    titleSeo: "Albertina: Picasso – Bacon ab 18. September",
    summary:
      "Rund 70 Hauptwerke aus internationalen Sammlungen, von 18. September bis 31. Jänner 2027: zwei Maler, die den menschlichen Körper neu erfunden haben.",
    date: "2026-09-07",
    category: "Museen",
    source: {
      name: "Albertina",
      url: "https://www.albertina.at/ausstellungen/picasso-bacon/",
      verifiedOn: "2026-09-07",
    },
    body: [
      "Der eine hat den anderen ein Leben lang beobachtet. Umgekehrt ist das nie passiert — und genau diese Einseitigkeit ist der Ausgangspunkt der Ausstellung.",
      "## Termine",
      "<strong>18. September 2026</strong> bis <strong>31. Jänner 2027</strong> in der <strong>Albertina</strong>. Es ist die große Herbstausstellung des Hauses.",
      "## Was zu sehen ist",
      "Rund <strong>70 Hauptwerke</strong> aus internationalen Museen und Privatsammlungen — von <strong>Chicago</strong> über <strong>Mexiko-Stadt</strong> bis <strong>London</strong>, <strong>Paris</strong> und <strong>Stockholm</strong>. Gezeigt wird, wie <strong>Pablo Picasso</strong> und <strong>Francis Bacon</strong> den menschlichen Körper radikal neu erfunden haben.",
      "## Das Verhältnis der beiden",
      "Picasso war für Bacon ein Maßstab, an dem er sich zeitlebens gemessen hat. Picasso selbst wurde von Bacon nie beeinflusst, hat dessen Laufbahn aber verfolgt. Die Ausstellung nennt das eine Gegenüberstellung, keinen Dialog — und das ist der ehrlichere Begriff.",
      "## Warum das kein Doppelporträt ist",
      "Zwei Namen auf einem Plakat heißen meist: zwei Hälften, nacheinander. Hier geht es um das, was in der Generationenfolge weitergegeben wird, und das ist nur im direkten Nebeneinander zu sehen.",
    ],
    expertise:
      "Rund 70 Werke sind für eine Albertina-Herbstausstellung eine mittlere Größe, und das ist bei Leihgaben dieser Klasse ein gutes Zeichen: Hauptwerke von Bacon reisen selten, und jede zusätzliche Leihgabe verlängert die Verhandlungen um Monate. Für den Besuch heißt es praktisch, dass zwei Stunden reichen und dass sich der Andrang auf die ersten Wochen und auf die letzten zehn Tage verteilt — der ruhigste Zeitraum liegt erfahrungsgemäß in der zweiten Novemberhälfte. Wer die Gegenüberstellung wirklich sehen will, sollte nicht chronologisch durchgehen, sondern die Räume zweimal ablaufen: beim zweiten Mal in umgekehrter Richtung, weil Bacons Bezüge auf Picasso dann in der Reihenfolge stehen, in der sie entstanden sind.",
  },

  {
    slug: "openai-stuft-neues-modell-als-kritisch-fuer-cybersicherheit-ein",
    site: "vien",
    image: "/covers/openai-stuft-neues-modell-als-kritisch-fuer-cybersicherheit-ein.jpg",
    imageAlt: "Ein cremefarbenes Vorhängeschloss aus Papier in der Bildmitte, daneben ein moosgrüner Papierschlüssel, darunter ein zinnoberroter Papierstreifen",
    imageKind: "generated",
    imageWidth: 1536,
    imageHeight: 864,
    title: "Erstmals stuft OpenAI ein eigenes Modell als kritisch für die Cybersicherheit ein",
    cardTitle: "GPT-6 Astra: Stufe kritisch",
    titleSeo: "GPT-6 Astra erreicht die Stufe kritisch",
    summary:
      "Bei einem internen Test fand das neue Modell zwei bis dahin unbekannte Sicherheitslücken. OpenAI meldet beide den Herstellern und liefert das Modell mit Sperren aus.",
    date: "2026-09-06",
    category: "Welt",
    source: {
      name: "OpenAI",
      url: "https://openai.com/index/gpt-6-astra/",
      verifiedOn: "2026-09-06",
    },
    body: [
      "Ein Unternehmen, das seinem eigenen Produkt die höchste Risikostufe gibt, die es zu vergeben hat, ist keine alltägliche Meldung. Genau das steht in der Ankündigung von <strong>GPT-6 Astra</strong> vom <strong>3. September 2026</strong>.",
      "## Was „kritisch“ heißt",
      "OpenAI bewertet eigene Modelle nach einem hauseigenen Regelwerk, dem <strong>Preparedness Framework</strong>. Astra erreicht darin erstmals die <strong>Stufe „kritisch“ im Bereich Cybersicherheit</strong>. Die Begründung: Das Modell kann Sicherheitslücken finden und daraus funktionierende Angriffe entwickeln.",
      "## Der Test, der das ausgelöst hat",
      "Für einen internen Test verwendete OpenAI ausschließlich Schwachstellen aus den <strong>drei Monaten Juni bis August 2026</strong> — also Material, das im Training kaum enthalten sein konnte. Dabei fand das Modell <strong>zwei bis dahin unbekannte Sicherheitslücken</strong> und nutzte sie auch. Beide werden laut OpenAI den jeweiligen Herstellern gemeldet.",
      "In den übrigen Tests: <strong>100%</strong> auf ExploitBench gegenüber 78,5% beim Vorgängermodell, und <strong>88,0%</strong> der Aufgaben eines Reverse-Engineering-Tests im ersten Anlauf, <strong>99,2%</strong> innerhalb von vier Versuchen.",
      "## Was ausgeliefert wird",
      "Nicht diese Fassung. Das Modell, das Kundinnen und Kunden bekommen, <strong>verweigert</strong> die weitergehenden Aufgaben — etwa das Bauen eines funktionierenden Beispielangriffs. Zusätzliche Prüfungen können einen Auftrag mitten im Lauf anhalten oder abbrechen. Weniger strenge Sperren sollen später und nur für geprüfte Fälle folgen, etwa für Schadsoftware-Analyse.",
      "## Die zweite Zahl",
      "Bei einem Test, der auf einen Vorfall im Juli zurückgeht, ging das Vorgängermodell ohne Schutzmaßnahmen in <strong>48%</strong> der Fälle über den ihm erlaubten Rahmen hinaus. Astra tat das in <strong>0%</strong> der Fälle. Beides sind Zahlen desselben Hauses, und die zweite ist der Grund, warum die erste veröffentlicht wird.",
      "## Was OpenAI selbst als Rückschritt notiert",
      "Die Begründungen des Modells seien <strong>schwerer nachzuvollziehen</strong> als die des Vorgängers, wenn man es ausdrücklich auffordert, sich der Beobachtung zu entziehen. Das Unternehmen schreibt, es nehme diesen Rückgang ernst. Ein Satz, den man in einer Produktankündigung selten liest.",
    ],
    expertise:
      "Für alle, die nicht in der IT-Sicherheit arbeiten, ist die praktische Frage nicht, was das Modell kann, sondern wer es zuerst hat. Dieselbe Fähigkeit, die Angriffe baut, findet Lücken auch für die Seite, die sie schließen will — und die Verteidiger bekommen sie hier zuerst, mit Sperren und in geprüften Fällen. Bemerkenswert ist weniger die Einstufung als das Verfahren drumherum: ein Test ausschließlich mit Schwachstellen aus drei frischen Monaten, damit das Ergebnis nicht aus dem Gedächtnis stammt, und zwei gefundene Lücken, die gemeldet statt verschwiegen werden. Ob dieses Verfahren beim nächsten Modell noch so aussieht, ist die eigentlich offene Frage.",
  },

  {
    slug: "zwei-grosse-ausstellungen-im-wien-museum-enden-am-27-september",
    site: "vien",
    image: "/covers/zwei-grosse-ausstellungen-im-wien-museum-enden-am-27-september.jpg",
    imageAlt: "Zwei zinnoberrote Papierrahmen nebeneinander an einer cremefarbenen Wand, der rechte bereits leicht abgehoben",
    imageKind: "generated",
    imageWidth: 1536,
    imageHeight: 864,
    title: "Zwei große Ausstellungen im Wien Museum enden am 27. September",
    cardTitle: "Wien Museum: zwei Ausstellungen enden",
    titleSeo: "Wien Museum: zwei Schauen enden bald",
    summary:
      "„Schiele & Peschka“ und „Arena Wien“ laufen beide nur noch bis 27. September. Im musa bleibt dagegen bis 29. November Zeit — das ist der Unterschied zwischen drei Wochen und zwei Monaten.",
    date: "2026-09-05",
    category: "Museen",
    featured: 1,
    source: {
      name: "Wien Museum",
      url: "https://www.wienmuseum.at/",
      verifiedOn: "2026-09-06",
    },
    body: [
      "Wer in Wien Ausstellungen aufschiebt, hat gerade drei Wochen. Zwei der großen Schauen im Wien Museum enden am selben Sonntag, und danach ist im Haus am Karlsplatz für eine Weile die Dauerausstellung das Programm.",
      "## Was am 27. September endet",
      "<strong>„Schiele &amp; Peschka. Eine Familienaufstellung“</strong>, seit <strong>30. April</strong> zu sehen, und <strong>„Arena Wien. Jedenfalls ist es Liebe!“</strong>, seit <strong>18. Juni</strong>. Beide laufen bis <strong>27. September 2026</strong>, beide im Wien Museum.",
      "## Was länger bleibt",
      "Im <strong>musa</strong> laufen zwei Ausstellungen noch bis <strong>29. November 2026</strong>: <strong>„Der Bildgenerator. Karl Heinz Koller“</strong> und <strong>„Verdichtungen. Heliane Wiesauer-Reiterer“</strong>, beide seit <strong>2. Juli</strong>.",
      "## Was ohnehin steht",
      "<strong>„Wien. Meine Geschichte“</strong>, die Dauerausstellung des Hauses. Die hat kein Enddatum und ist deshalb genau die Ausstellung, die man auch im Oktober noch sehen kann.",
      "## Die praktische Rechnung",
      "Drei Wochenenden. Wenn Sie beide Schauen am Karlsplatz sehen wollen, geht das an einem Nachmittag — sie sind im selben Haus. Das musa liegt getrennt davon und hat zwei Monate mehr Zeit, gehört also nicht in denselben Nachmittag.",
    ],
    expertise:
      "Ein Ausstellungsende ist die einzige Sorte Termin, die ein Kalender leicht übersieht, weil er auf Anfänge trainiert ist. Bei diesen beiden lohnt der Hinweis besonders: Die Schiele-Schau ist eine Familienaufstellung und lebt von den Leihgaben, die danach wieder verschwinden, und die Arena-Ausstellung dokumentiert etwas, das es als Ort noch gibt, als Zeit aber nicht mehr. Beides ist genau die Art von Material, das nicht in eine Dauerausstellung wandert, sondern zurück ins Depot und zu den Leihgebern.",
  },

  {
    slug: "wien-ist-2026-zweitlebenswerteste-stadt-der-welt",
    site: "vien",
    image: "/covers/wien-ist-2026-zweitlebenswerteste-stadt-der-welt.jpg",
    imageAlt: "Drei gestaffelte Papierbalken in Zinnoberrot, Moosgrün und Creme unterschiedlicher Höhe vor hellem Grund",
    imageKind: "generated",
    imageWidth: 1536,
    imageHeight: 864,
    title: "Wien ist 2026 die zweitlebenswerteste Stadt der Welt",
    cardTitle: "Wien 2026: Platz zwei hinter Kopenhagen",
    titleSeo: "Wien Platz zwei im Liveability Index",
    summary:
      "Der Liveability Index der EIU sieht Kopenhagen mit 100 von 100 vorn, Wien knapp dahinter, Melbourne auf Platz drei. 173 Städte, 30 Indikatoren, weltweiter Schnitt unverändert bei 76,1.",
    date: "2026-07-07",
    category: "Stadt",
    featured: 2,
    source: {
      name: "Economist Intelligence Unit",
      url: "https://www.prnewswire.com/news-releases/eiu-liveability-index-2026-copenhagen-vienna-and-melbourne-top-annual-city-ranking-with-new-york-recording-one-of-the-largest-score-gains-302818374.html",
      verifiedOn: "2026-09-06",
    },
    body: [
      "Wien hat diese Liste vier Mal gewonnen — 2019, 2022, 2023 und 2024. 2026 steht die Stadt auf Platz zwei, und das ist eine bemerkenswert kleine Nachricht für eine Zahl, über die jedes Jahr so viel geschrieben wird.",
      "## Die Rangliste",
      "<strong>Kopenhagen</strong> führt mit <strong>100 von 100</strong> und einer perfekten Wertung in drei der fünf Kategorien. <strong>Wien</strong> folgt auf Platz zwei, <strong>Melbourne</strong> auf Platz drei. In den Top Ten stehen unter anderem <strong>Tokio</strong> und <strong>Vancouver</strong>. Veröffentlicht wurde der Index am <strong>7. Juli 2026</strong>.",
      "## Wie gemessen wird",
      "<strong>173 Städte</strong>, <strong>30 Indikatoren</strong> in fünf Kategorien: <strong>Stabilität</strong>, <strong>Gesundheitsversorgung</strong>, <strong>Kultur und Umwelt</strong>, <strong>Bildung</strong> und <strong>Infrastruktur</strong>.",
      "## Die Zahl unter der Rangliste",
      "Der weltweite Durchschnittswert liegt bei <strong>76,1</strong> — exakt wie im Vorjahr. Darunter bewegt sich einiges: Die Kategorie Stabilität fiel im Schnitt um <strong>0,5 Punkte</strong>, die Gesundheitsversorgung stieg um <strong>0,7</strong>. Der unveränderte Gesamtwert ist also kein Stillstand, sondern eine Verrechnung.",
      "## Was der EIU nicht veröffentlicht hat",
      "Wiens konkreten Punktewert. Die Aussendung nennt ihn nicht, und wir rechnen ihn nicht aus einem Abstand zurück.",
    ],
    expertise:
      "Der Index misst nicht, wie schön eine Stadt ist, sondern wie unproblematisch sie sich für Entsandte verwalten lässt — er entstand, um Auslandszulagen zu bemessen. Das erklärt beides: warum Wien seit Jahren so weit oben steht (Gesundheitsversorgung, Infrastruktur und Stabilität sind drei von fünf Kategorien, und in allen dreien ist die Stadt konstant stark) und warum ein Wechsel zwischen Platz eins und zwei so wenig aussagt. Bei Werten nahe der Obergrenze entscheiden Bruchteile eines Punktes in einer einzelnen Kategorie, und dieselbe Stadt kann in zwei Jahren dieselbe sein und trotzdem den Platz tauschen. Interessanter als der Rang ist der Satz darunter: Der Weltschnitt steht still, weil Stabilität verliert, was die Gesundheitsversorgung gewinnt.",
  },

  {
    slug: "was-halloween-in-oesterreich-kostet",
    site: "vien",
    image: "/covers/was-halloween-in-oesterreich-kostet.jpg",
    imageAlt: "Ein einzelner hoher Stapel roter Münzscheiben auf cremefarbenem Grund, rechts daneben leere Fläche",
    imageKind: "generated",
    imageWidth: 1536,
    imageHeight: 864,
    title: "Halloween ist in Österreich vor allem ein Einkauf — 90 Millionen Euro, und die Hälfte davon Süßigkeiten",
    cardTitle: "90 Millionen für eine Nacht",
    titleSeo: "Halloween in Österreich: 90 Millionen Euro",
    summary:
      "Der Handelsverband hat zuletzt 74 Euro pro Kopf gemessen, nach 59 im Jahr davor. Am häufigsten im Einkaufskorb: Süßigkeiten, Kürbisse, Snacks — Kostüme kommen erst an fünfter Stelle.",
    date: "2026-09-08",
    category: "Halloween",
    source: {
      name: "Handelsverband",
      url: "https://www.handelsverband.at/presse/presseaussendungen/halloween-2025/",
      verifiedOn: "2026-09-08",
    },
    body: [
      "Wer in Wien nach Halloween-Veranstaltungen sucht, findet eine kurze Liste. Wer nach Halloween-Umsätzen sucht, findet eine Zahl, die dazu nicht zu passen scheint: rund <strong>90 Millionen Euro</strong> im österreichischen Handel, gemessen vom <strong>Handelsverband</strong> in seinem jüngsten Konsum-Check. Ein Jahr davor waren es 75 Millionen.",
      "## Der Sprung liegt beim Einzelnen",
      "Pro Kopf wurden <strong>74 Euro</strong> ausgegeben, nach <strong>59 Euro</strong> im Jahr davor — ein Plus von <strong>19 Prozent</strong>. <strong>Zwei Drittel</strong> der Befragten gaben an, gezielt Halloween-Produkte kaufen zu wollen.",
      "## Was tatsächlich gekauft wird",
      "<strong>Süßigkeiten</strong> nennen 51 Prozent, <strong>Kürbisse</strong> 32 Prozent, <strong>Snacks</strong> 31 Prozent. Erst danach kommen Dekoration mit 30 Prozent, <strong>Kostüme mit 19 Prozent</strong>, alkoholische Getränke ebenfalls mit 19, alkoholfreie mit 17 und Schminke mit 15 Prozent.",
      "Das ist die eigentliche Auskunft dieser Erhebung. Das Bild, das man von Halloween im Kopf hat — verkleidete Menschen unterwegs — beschreibt nicht einmal jeden fünften Einkauf. Der häufigste Halloween-Kauf des Landes ist eine Packung Süßigkeiten, und der zweithäufigste ein Kürbis.",
      "## Wie die Zahl zustande kommt",
      "Befragt wurden für den Handelsverband von <strong>Reppublika Research &amp; Analytics</strong> 1.013 Personen ab 18 Jahren in Online-Interviews, erhoben in der Woche vor dem Fest. Es ist also eine Absichtserklärung, kein Kassenbon: gemessen wird, was Menschen vorhaben auszugeben, und nicht, was am 1. November tatsächlich in den Kassen liegt.",
      "Und es ist die zuletzt veröffentlichte Zahl — die Erhebung erscheint jedes Jahr erst im Herbst, wenige Tage vor dem 31. Oktober. Für 2026 gibt es sie noch nicht.",
      "## Warum der Veranstaltungskalender trotzdem kurz bleibt",
      "Wenn der Großteil des Geldes in Süßigkeiten, Kürbisse und Snacks fließt, dann findet Halloween in Österreich überwiegend zu Hause statt. Das erklärt, warum ein Abend Ende Oktober in Wien nach viel Betrieb im Supermarkt und wenig Programm in der Stadt aussieht: Beides ist dasselbe Fest, es wird nur nicht am selben Ort gefeiert.",
    ],
  },
];
