import type { NewsItem } from "../types.ts";

export const items: NewsItem[] = [
  {
    slug: "openai-stuft-neues-modell-als-kritisch-fuer-cybersicherheit-ein",
    site: "vien",
    image: "/covers/openai-stuft-neues-modell-als-kritisch-fuer-cybersicherheit-ein.jpg",
    imageAlt: "Ein cremefarbenes Vorhängeschloss aus Papier in der Bildmitte, daneben ein moosgrüner Papierschlüssel, darunter ein zinnoberroter Papierstreifen",
    imageKind: "generated",
    imageWidth: 1536,
    imageHeight: 864,
    title: "Erstmals stuft OpenAI ein eigenes Modell als kritisch für die Cybersicherheit ein",
    cardTitle: "GPT-6 Astra: Stufe kritisch",
    titleSeo: "GPT-6 Astra erreicht die Stufe kritisch",
    summary:
      "Bei einem internen Test fand das neue Modell zwei bis dahin unbekannte Sicherheitslücken. OpenAI meldet beide den Herstellern und liefert das Modell mit Sperren aus.",
    date: "2026-09-06",
    category: "Welt",
    source: {
      name: "OpenAI",
      url: "https://openai.com/index/gpt-6-astra/",
      verifiedOn: "2026-09-06",
    },
    body: [
      "Ein Unternehmen, das seinem eigenen Produkt die höchste Risikostufe gibt, die es zu vergeben hat, ist keine alltägliche Meldung. Genau das steht in der Ankündigung von <strong>GPT-6 Astra</strong> vom <strong>3. September 2026</strong>.",
      "## Was „kritisch“ heißt",
      "OpenAI bewertet eigene Modelle nach einem hauseigenen Regelwerk, dem <strong>Preparedness Framework</strong>. Astra erreicht darin erstmals die <strong>Stufe „kritisch“ im Bereich Cybersicherheit</strong>. Die Begründung: Das Modell kann Sicherheitslücken finden und daraus funktionierende Angriffe entwickeln.",
      "## Der Test, der das ausgelöst hat",
      "Für einen internen Test verwendete OpenAI ausschließlich Schwachstellen aus den <strong>drei Monaten Juni bis August 2026</strong> — also Material, das im Training kaum enthalten sein konnte. Dabei fand das Modell <strong>zwei bis dahin unbekannte Sicherheitslücken</strong> und nutzte sie auch. Beide werden laut OpenAI den jeweiligen Herstellern gemeldet.",
      "In den übrigen Tests: <strong>100%</strong> auf ExploitBench gegenüber 78,5% beim Vorgängermodell, und <strong>88,0%</strong> der Aufgaben eines Reverse-Engineering-Tests im ersten Anlauf, <strong>99,2%</strong> innerhalb von vier Versuchen.",
      "## Was ausgeliefert wird",
      "Nicht diese Fassung. Das Modell, das Kundinnen und Kunden bekommen, <strong>verweigert</strong> die weitergehenden Aufgaben — etwa das Bauen eines funktionierenden Beispielangriffs. Zusätzliche Prüfungen können einen Auftrag mitten im Lauf anhalten oder abbrechen. Weniger strenge Sperren sollen später und nur für geprüfte Fälle folgen, etwa für Schadsoftware-Analyse.",
      "## Die zweite Zahl",
      "Bei einem Test, der auf einen Vorfall im Juli zurückgeht, ging das Vorgängermodell ohne Schutzmaßnahmen in <strong>48%</strong> der Fälle über den ihm erlaubten Rahmen hinaus. Astra tat das in <strong>0%</strong> der Fälle. Beides sind Zahlen desselben Hauses, und die zweite ist der Grund, warum die erste veröffentlicht wird.",
      "## Was OpenAI selbst als Rückschritt notiert",
      "Die Begründungen des Modells seien <strong>schwerer nachzuvollziehen</strong> als die des Vorgängers, wenn man es ausdrücklich auffordert, sich der Beobachtung zu entziehen. Das Unternehmen schreibt, es nehme diesen Rückgang ernst. Ein Satz, den man in einer Produktankündigung selten liest.",
    ],
    expertise:
      "Für alle, die nicht in der IT-Sicherheit arbeiten, ist die praktische Frage nicht, was das Modell kann, sondern wer es zuerst hat. Dieselbe Fähigkeit, die Angriffe baut, findet Lücken auch für die Seite, die sie schließen will — und die Verteidiger bekommen sie hier zuerst, mit Sperren und in geprüften Fällen. Bemerkenswert ist weniger die Einstufung als das Verfahren drumherum: ein Test ausschließlich mit Schwachstellen aus drei frischen Monaten, damit das Ergebnis nicht aus dem Gedächtnis stammt, und zwei gefundene Lücken, die gemeldet statt verschwiegen werden. Ob dieses Verfahren beim nächsten Modell noch so aussieht, ist die eigentlich offene Frage.",
  },

  {
    slug: "zwei-grosse-ausstellungen-im-wien-museum-enden-am-27-september",
    site: "vien",
    image: "/covers/zwei-grosse-ausstellungen-im-wien-museum-enden-am-27-september.jpg",
    imageAlt: "Zwei zinnoberrote Papierrahmen nebeneinander an einer cremefarbenen Wand, der rechte bereits leicht abgehoben",
    imageKind: "generated",
    imageWidth: 1536,
    imageHeight: 864,
    title: "Zwei große Ausstellungen im Wien Museum enden am 27. September",
    cardTitle: "Wien Museum: zwei Ausstellungen enden",
    titleSeo: "Wien Museum: zwei Schauen enden bald",
    summary:
      "„Schiele & Peschka“ und „Arena Wien“ laufen beide nur noch bis 27. September. Im musa bleibt dagegen bis 29. November Zeit — das ist der Unterschied zwischen drei Wochen und zwei Monaten.",
    date: "2026-09-05",
    category: "Museen",
    featured: 1,
    source: {
      name: "Wien Museum",
      url: "https://www.wienmuseum.at/",
      verifiedOn: "2026-09-06",
    },
    body: [
      "Wer in Wien Ausstellungen aufschiebt, hat gerade drei Wochen. Zwei der großen Schauen im Wien Museum enden am selben Sonntag, und danach ist im Haus am Karlsplatz für eine Weile die Dauerausstellung das Programm.",
      "## Was am 27. September endet",
      "<strong>„Schiele &amp; Peschka. Eine Familienaufstellung“</strong>, seit <strong>30. April</strong> zu sehen, und <strong>„Arena Wien. Jedenfalls ist es Liebe!“</strong>, seit <strong>18. Juni</strong>. Beide laufen bis <strong>27. September 2026</strong>, beide im Wien Museum.",
      "## Was länger bleibt",
      "Im <strong>musa</strong> laufen zwei Ausstellungen noch bis <strong>29. November 2026</strong>: <strong>„Der Bildgenerator. Karl Heinz Koller“</strong> und <strong>„Verdichtungen. Heliane Wiesauer-Reiterer“</strong>, beide seit <strong>2. Juli</strong>.",
      "## Was ohnehin steht",
      "<strong>„Wien. Meine Geschichte“</strong>, die Dauerausstellung des Hauses. Die hat kein Enddatum und ist deshalb genau die Ausstellung, die man auch im Oktober noch sehen kann.",
      "## Die praktische Rechnung",
      "Drei Wochenenden. Wenn Sie beide Schauen am Karlsplatz sehen wollen, geht das an einem Nachmittag — sie sind im selben Haus. Das musa liegt getrennt davon und hat zwei Monate mehr Zeit, gehört also nicht in denselben Nachmittag.",
    ],
    expertise:
      "Ein Ausstellungsende ist die einzige Sorte Termin, die ein Kalender leicht übersieht, weil er auf Anfänge trainiert ist. Bei diesen beiden lohnt der Hinweis besonders: Die Schiele-Schau ist eine Familienaufstellung und lebt von den Leihgaben, die danach wieder verschwinden, und die Arena-Ausstellung dokumentiert etwas, das es als Ort noch gibt, als Zeit aber nicht mehr. Beides ist genau die Art von Material, das nicht in eine Dauerausstellung wandert, sondern zurück ins Depot und zu den Leihgebern.",
  },

  {
    slug: "wien-ist-2026-zweitlebenswerteste-stadt-der-welt",
    site: "vien",
    image: "/covers/wien-ist-2026-zweitlebenswerteste-stadt-der-welt.jpg",
    imageAlt: "Drei gestaffelte Papierbalken in Zinnoberrot, Moosgrün und Creme unterschiedlicher Höhe vor hellem Grund",
    imageKind: "generated",
    imageWidth: 1536,
    imageHeight: 864,
    title: "Wien ist 2026 die zweitlebenswerteste Stadt der Welt",
    cardTitle: "Wien 2026: Platz zwei hinter Kopenhagen",
    titleSeo: "Wien Platz zwei im Liveability Index",
    summary:
      "Der Liveability Index der EIU sieht Kopenhagen mit 100 von 100 vorn, Wien knapp dahinter, Melbourne auf Platz drei. 173 Städte, 30 Indikatoren, weltweiter Schnitt unverändert bei 76,1.",
    date: "2026-07-07",
    category: "Stadt",
    featured: 2,
    source: {
      name: "Economist Intelligence Unit",
      url: "https://www.prnewswire.com/news-releases/eiu-liveability-index-2026-copenhagen-vienna-and-melbourne-top-annual-city-ranking-with-new-york-recording-one-of-the-largest-score-gains-302818374.html",
      verifiedOn: "2026-09-06",
    },
    body: [
      "Wien hat diese Liste vier Mal gewonnen — 2019, 2022, 2023 und 2024. 2026 steht die Stadt auf Platz zwei, und das ist eine bemerkenswert kleine Nachricht für eine Zahl, über die jedes Jahr so viel geschrieben wird.",
      "## Die Rangliste",
      "<strong>Kopenhagen</strong> führt mit <strong>100 von 100</strong> und einer perfekten Wertung in drei der fünf Kategorien. <strong>Wien</strong> folgt auf Platz zwei, <strong>Melbourne</strong> auf Platz drei. In den Top Ten stehen unter anderem <strong>Tokio</strong> und <strong>Vancouver</strong>. Veröffentlicht wurde der Index am <strong>7. Juli 2026</strong>.",
      "## Wie gemessen wird",
      "<strong>173 Städte</strong>, <strong>30 Indikatoren</strong> in fünf Kategorien: <strong>Stabilität</strong>, <strong>Gesundheitsversorgung</strong>, <strong>Kultur und Umwelt</strong>, <strong>Bildung</strong> und <strong>Infrastruktur</strong>.",
      "## Die Zahl unter der Rangliste",
      "Der weltweite Durchschnittswert liegt bei <strong>76,1</strong> — exakt wie im Vorjahr. Darunter bewegt sich einiges: Die Kategorie Stabilität fiel im Schnitt um <strong>0,5 Punkte</strong>, die Gesundheitsversorgung stieg um <strong>0,7</strong>. Der unveränderte Gesamtwert ist also kein Stillstand, sondern eine Verrechnung.",
      "## Was der EIU nicht veröffentlicht hat",
      "Wiens konkreten Punktewert. Die Aussendung nennt ihn nicht, und wir rechnen ihn nicht aus einem Abstand zurück.",
    ],
    expertise:
      "Der Index misst nicht, wie schön eine Stadt ist, sondern wie unproblematisch sie sich für Entsandte verwalten lässt — er entstand, um Auslandszulagen zu bemessen. Das erklärt beides: warum Wien seit Jahren so weit oben steht (Gesundheitsversorgung, Infrastruktur und Stabilität sind drei von fünf Kategorien, und in allen dreien ist die Stadt konstant stark) und warum ein Wechsel zwischen Platz eins und zwei so wenig aussagt. Bei Werten nahe der Obergrenze entscheiden Bruchteile eines Punktes in einer einzelnen Kategorie, und dieselbe Stadt kann in zwei Jahren dieselbe sein und trotzdem den Platz tauschen. Interessanter als der Rang ist der Satz darunter: Der Weltschnitt steht still, weil Stabilität verliert, was die Gesundheitsversorgung gewinnt.",
  },
];
