import type { NewsItem } from "../types.ts";

export const items: NewsItem[] = [
  {
    slug: "what-a-dubai-visit-visa-asks-of-the-person-sponsoring-it",
    createdAt: "2026-08-25T18:18:34+04:00",
    updatedAt: "2026-09-08T00:12:45+04:00",
    site: "visas",
    image: "/covers/what-a-dubai-visit-visa-asks-of-the-person-sponsoring-it.jpg",
    imageAlt: "Three tobacco-brown paper cards of increasing height standing on a sand ground, each with a small cream band across it",
    imageKind: "generated",
    imageWidth: 1536,
    imageHeight: 864,
    title: "What a Dubai visit visa asks of the person sponsoring it",
    cardTitle: "Sponsoring a visitor: the salary floors",
    titleSeo: "Dubai visit visa: sponsor salary rules",
    summary:
      "GDRFA Dubai has set out what a resident must earn to bring someone over: Dh4,000 for a parent or child, Dh8,000 for a sibling, Dh15,000 for a friend.",
    date: "2026-09-07",
    category: "Visit visas",
    source: {
      name: "GDRFA Dubai, as summarised by KPMG",
      url: "https://kpmg.com/xx/en/our-insights/gms-flash-alert/2026/flash-alert-2026-210.html",
      verifiedOn: "2026-09-07",
    },
    body: [
      "The question a resident actually asks is never «can my mother visit». It is «what do I have to prove», and until this summer the answer depended on which Amer centre you walked into.",
      "## Three salary floors",
      "The <strong>General Directorate of Residency and Foreigners Affairs</strong> in Dubai set them out by closeness of relation. A <strong>first-degree relative</strong> — parent, spouse, child — needs a sponsor earning at least <strong>Dh4,000 a month</strong>. A <strong>second- or third-degree relative</strong> — sibling, grandparent, cousin — needs <strong>Dh8,000</strong>. A <strong>friend</strong> needs <strong>Dh15,000</strong>.",
      "## What the visa itself can be",
      "Single-entry or multiple-entry, valid for <strong>30, 60 or 90 days</strong>, with total stays of up to <strong>120 days a year</strong>. Single-entry visas run <strong>Dh200 to Dh400</strong> and multiple-entry <strong>Dh300 to Dh700</strong>, before the refundable deposit — Dh1,000 or Dh2,000 — VAT, medical insurance and service charges.",
      "## The documents",
      "The sponsor's Emirates ID and passport copy; the visitor's passport with at least six months left and a photograph; proof of income, as a salary certificate, labour contract or business documents; proof of where the visitor will stay; and an attested certificate for the relationship where one is claimed.",
      "## The line that catches people out",
      "The relationship has to be documented, not asserted. A cousin at the Dh8,000 tier and a friend at Dh15,000 are the same person to the counter unless the paperwork says otherwise — and attestation is the step that takes weeks, not the application.",
    ],
    expertise:
      "The deposit is the part worth planning around, because it is not a fee: it is money held against the visitor leaving on time, and it comes back only after departure is recorded. Two visitors on multiple-entry visas can therefore tie up Dh4,000 for months, which matters more to a household budget than the visa price everyone compares. The 120-day annual ceiling is the other quiet constraint — it is cumulative across visas, so a parent who came for 90 days in spring cannot take another 90 in autumn, and the second application is refused on a total nobody was tracking. Count the days already spent before choosing the validity, not after.",
  },

  {
    slug: "dubai-issued-66078-golden-visas-in-six-months",
    createdAt: "2026-09-06T08:48:11+04:00",
    updatedAt: "2026-09-08T00:12:45+04:00",
    site: "visas",
    image: "/covers/dubai-issued-66078-golden-visas-in-six-months.jpg",
    imageAlt: "A dense grid of small tobacco-brown paper rectangles on a warm sand ground, one of them lifted clear of the grid in ochre",
    imageKind: "generated",
    imageWidth: 1536,
    imageHeight: 864,
    title: "Dubai issued 66,078 golden visas in the first half of 2026",
    cardTitle: "66,078 golden visas in six months",
    titleSeo: "Dubai issued 66,078 golden visas in H1",
    summary:
      "GDRFA Dubai’s half-year figures: 66,078 golden visas, 29,456 five-year multiple-entry tourist visas and more than seven million visa and residency transactions between January and June.",
    date: "2026-09-06",
    category: "Golden visa",
    source: {
      name: "Gulf News",
      url: "https://gulfnews.com/uae/government/dubai-grants-66000-golden-visas-as-5-year-tourist-visa-surges-1.500608837",
      verifiedOn: "2026-09-06",
    },
    body: [
      "A residency category stops being exclusive at some point, and the only honest way to find that point is to count.",
      "## The numbers",
      "The <strong>General Directorate of Residency and Foreigners Affairs — Dubai</strong> reported <strong>66,078 golden visas</strong> issued between <strong>January and June 2026</strong>, alongside <strong>29,456</strong> five-year multiple-entry tourist visas. Across every category the directorate processed <strong>more than seven million</strong> visa and residency transactions in the same six months, with a reported <strong>95% customer satisfaction</strong> rate.",
      "## Who reported it",
      "<strong>Lieutenant General Mohammed Ahmed Al Marri</strong>, Director General of GDRFA Dubai: «The results reflect our commitment to delivering efficient, flexible and digitally driven services that enhance customer experience and support Dubai’s position as a leading global destination.» <strong>Major General Khalaf Ahmed Al Ghaith</strong>, Assistant Director General of the Entry Permits and Residency Sector, presented the sector detail.",
      "## What the two numbers say together",
      "Seven million transactions against 66,078 golden visas is the ratio worth holding on to. The golden visa is the category that gets written about; it is a fraction of a percent of what the directorate actually does, and the bulk of that work is ordinary entry permits, renewals, cancellations and status changes for people already here.",
      "## The five-year tourist visa",
      "At <strong>29,456</strong> issued in six months, the five-year multiple-entry visit visa is now a mainstream product rather than a curiosity — roughly <strong>one for every two</strong> golden visas granted in the same period.",
    ],
    expertise:
      "Half-year issuance figures are useful for one thing and misleading for another. They are a good measure of throughput: a directorate that clears seven million transactions in six months is not the bottleneck in anyone’s application, and the practical delays applicants meet are almost always upstream — a medical, an attestation, an employer’s establishment card. They are a poor measure of how hard the golden visa is to get, because the published total mixes categories with entirely different tests: an investor route, a specialist-talent nomination and a top-of-class student nomination all land in the same figure. Anyone reading 66,078 as evidence that the bar has dropped should note that no category-level breakdown was published, which is exactly the number that would settle the question. On the five-year visit visa, the practical caution is that it is a multiple-entry permission, not a residence: it does not carry an Emirates ID, it does not open a bank account on its own terms, and stays are still capped per entry. It is a travel document for people whose life is somewhere else.",
  },

  {
    slug: "europes-new-travel-permit-slips-to-2027",
    createdAt: "2026-09-06T08:48:11+04:00",
    updatedAt: "2026-09-06T08:48:11+04:00",
    site: "visas",
    image: "/covers/europes-new-travel-permit-slips-to-2027.jpg",
    imageAlt: "A tobacco-brown paper arrow on a warm sand ground, its tip cut off and set further along, leaving a clear gap in the middle",
    imageKind: "generated",
    imageWidth: 1536,
    imageHeight: 864,
    title: "Europe’s €20 travel permit slips to 2027 while the border queues stay",
    cardTitle: "ETIAS slips to 2027",
    titleSeo: "ETIAS delayed to 2027 as EES queues bite",
    summary:
      "eu-LISA has accepted that ETIAS cannot launch by the end of 2026. The biometric Entry/Exit System it depends on went fully live in April and is producing waits IATA has put at three to six hours.",
    date: "2026-09-06",
    category: "Travel",
    source: {
      name: "AFAR",
      url: "https://www.afar.com/magazine/europe-delays-etias-travel-authorization-until-2027",
      verifiedOn: "2026-09-06",
    },
    body: [
      "Two European border systems were meant to arrive in order. The first one arrived, and the queue it produced is why the second one has not.",
      "## What was reported",
      "The <strong>Financial Times</strong> reported that <strong>eu-LISA</strong>, the EU agency that operates the bloc’s large-scale IT systems, has acknowledged that launching <strong>ETIAS</strong> by the end of 2026 is <strong>no longer feasible</strong>. The launch moves to <strong>2027</strong>. The official ETIAS site was, at the time of the report, still showing the last quarter of 2026.",
      "## What ETIAS is",
      "A travel authorisation rather than a visa, in the manner of the American ESTA. It costs <strong>€20</strong> once, permits stays of up to <strong>90 days in any 180</strong>, and is valid for <strong>three years or until the passport expires</strong>, whichever comes first. It will apply to travellers from non-EU countries visiting the <strong>30 participating European states</strong>.",
      "## Why it slipped",
      "ETIAS sits on top of the <strong>Entry/Exit System</strong>, which became fully operational in <strong>April 2026</strong>. EES replaces passport stamps with fingerprints and facial recognition at the border, and <strong>IATA</strong> warned of «challenging waiting times» of <strong>three to six hours</strong> as the biometric enrolment worked through arriving passengers.",
      "## What it means for now",
      "Nothing new to apply for, and nothing new to pay, on any European trip taken before the launch. What remains is the first-entry biometric enrolment under EES, which is a one-off per traveller and is where the time goes.",
    ],
    expertise:
      "The useful planning assumption is that the two systems have opposite shapes. EES is a border-side cost paid once and then largely gone: the first crossing after enrolment is the slow one, and the ones after it should be faster than the old stamping. ETIAS is a pre-travel cost that is trivial in money and awkward in timing, because it is an approval that has to exist before boarding — airlines check it at the gate, and an application that goes to manual review does not care about a same-day flight. That is why the delay is worth noticing even though nothing is being asked of anyone today: the operational risk was never the €20, it was the traveller who books on a Thursday and flies on a Friday. Until a firm date exists, treat any commercial site offering to secure ETIAS in advance as selling something that cannot yet be bought. When the date does land, the thing to check is the transitional arrangement rather than the launch day itself — earlier EU planning described a grace period in which arrivals without an authorisation are still admitted, and the difference between the launch and the end of that period is what actually changes at the airport.",
  },

  {
    slug: "dubai-tourist-visas-inside-48-hours",
    createdAt: "2026-09-03T07:30:21+04:00",
    updatedAt: "2026-09-06T08:48:11+04:00",
    site: "visas",
    image: "/covers/dubai-tourist-visas-inside-48-hours.jpg",
    imageAlt: "Two cut-paper clock faces on a sand ground, the second much smaller than the first, an ochre arrow between them",
    imageKind: "generated",
    imageWidth: 1536,
    imageHeight: 864,
    title: "Dubai's single-entry tourist visa now clears in 48 hours",
    cardTitle: "Tourist visas inside 48 hours",
    titleSeo: "Dubai tourist visas inside 48 hours",
    summary:
      "GDRFA confirmed a two-working-day turnaround on 30- and 60-day single-entry visas. It is a processing change, not a new visa type.",
    date: "2026-09-03",
    category: "Visit visas",
    source: {
      name: "Khaleej Times",
      url: "https://www.khaleejtimes.com/life-and-living/visa-and-immigration-in-uae/uae-visa-rule-changes-2026",
      verifiedOn: "2026-09-03",
    },
    body: [
      "Most visa reforms change who may come. This one changes how long they wait to find out.",
      "## The change",
      "The <strong>General Directorate of Residency and Foreigners Affairs — Dubai (GDRFA)</strong> confirmed in <strong>June 2026</strong> that single-entry tourist visas are expected to be issued <strong>within 48 hours</strong>.",
      "The visas concerned are the standard <strong>30-day and 60-day single-entry</strong> ones. Applications go through GDRFA's own digital services, the GDRFA DXB app, or an authorised tourism office or travel agent.",
      "## What it is not",
      "This is <strong>not a new visa category</strong>. Nothing about eligibility, duration or fees changes. What changes is the service standard attached to a document that already existed.",
      "## The condition attached to the clock",
      "The 48 hours run from the point at which <strong>all documents have been submitted and verified</strong> — not from the moment an application is opened. An incomplete file does not start the clock; it queues behind its own missing pages.",
    ],
    expertise:
      "The distinction between a new visa and a faster visa matters more than it sounds, because it tells you what to do when the 48 hours pass without an answer. There is no separate fast-track product to escalate to and no premium tier to buy: a delay almost always means a document was rejected at verification rather than that the application is sitting in a queue, so the productive response is to re-check what was uploaded rather than to reapply. Also worth noting for anyone timing a trip: this covers single entry only. Multi-entry visit visas and the 90-day variants are a different application and carry no comparable published turnaround.",
  },

  {
    slug: "medical-visas-get-a-single-front-door",
    createdAt: "2026-09-03T07:30:21+04:00",
    updatedAt: "2026-09-03T07:30:21+04:00",
    site: "visas",
    image: "/covers/medical-visas-get-a-single-front-door.jpg",
    imageAlt: "Three separate cut-paper doorways on a sand ground merging into one taller ochre doorway",
    imageKind: "generated",
    imageWidth: 1536,
    imageHeight: 864,
    title: "Dubai's immigration and health authorities are wiring their systems together",
    cardTitle: "Medical visas get one front door",
    titleSeo: "Medical visas get a single front door",
    summary:
      "GDRFA and the Dubai Health Authority signed an MoU on 3 June to link visa, insurance and provider systems. The smart medical visa itself is still in development.",
    date: "2026-09-03",
    category: "Medical visas",
    source: {
      name: "Gulf News",
      url: "https://gulfnews.com/amp/story/uae/health/dubai-simplifies-medical-visas-to-boost-health-tourism-1.500561518",
      verifiedOn: "2026-09-03",
    },
    body: [
      "A patient travelling to Dubai for treatment has, until now, been managing three separate queues at once: a visa, an appointment, and an extension when the treatment ran long. None of the three knew about the other two.",
      "## What was signed",
      "On <strong>3 June 2026</strong> the <strong>GDRFA</strong> and the <strong>Dubai Health Authority</strong> signed a Memorandum of Understanding to link their electronic systems. It was signed by <strong>Lieutenant General Mohammed Ahmed Al Marri</strong>, GDRFA Dubai's Director General, and <strong>Dr Alawi Sheikh Ali</strong>, Director General of the DHA.",
      "## What it changes now",
      "Members of the <strong>Dubai Health Experience (DXH)</strong> network can submit medical visa applications on behalf of international patients more efficiently. The stated aim is a journey that begins before the patient arrives and continues through treatment and recovery, rather than three processes that happen to overlap.",
      "## What it does not change yet",
      "The <strong>smart medical visa</strong> itself is <strong>still in development</strong>. The officials describe it as a planned outcome of this agreement rather than something now available, and no launch date has been published. Anyone travelling for treatment this year applies exactly as before.",
    ],
    expertise:
      "Read the MoU for what it names rather than for what it promises. The concrete, dated change is that DXH-network providers can file on a patient's behalf — which is worth knowing, because it means the practical route for a medical traveller runs through the treating facility rather than through an immigration agent. Everything described as \"smart\" here is future tense. The gap between the announcement and a working product in this space has historically been long, and a patient booking treatment on the strength of a visa that has not launched is booking on a press release.",
  },

  {
    slug: "entry-visa-opens-to-six-more-nationalities",
    createdAt: "2026-09-01T15:07:36+04:00",
    updatedAt: "2026-09-06T08:48:11+04:00",
    site: "visas",
    image: "/covers/entry-visa-opens-to-six-more-nationalities.jpg",
    imageAlt: "Six blank passport-shaped cards in two rows, one carrying a single red stamp",
    imageKind: "generated",
    imageWidth: 1536,
    imageHeight: 864,
    title: "Six more nationalities can now get a visa on arrival",
    titleSeo: "Visa on arrival: six more nationalities",
    summary:
      "The ICP has added Indonesia, Vietnam, Thailand, the Philippines, Kenya and South Africa — and six new countries of residence. Dh100 for 14 days, Dh250 for 60.",
    date: "2026-06-25",
    category: "Residency",
    source: {
      name: "Khaleej Times",
      url: "https://www.khaleejtimes.com/uae/uae-expands-entry-visit-visa-eligibility",
      verifiedOn: "2026-09-01",
    },
    body: [
      "The rule that changed here is a conditional one, and the condition is the part people misread. This is not a passport-based entitlement. It is an entitlement that depends on <strong>where you live</strong> as much as on which passport you hold.",
      "## The six new nationalities",
      "The Federal Authority for Identity, Citizenship, Customs and Port Security has extended entry-visa eligibility to nationals of <strong>Indonesia</strong>, <strong>Vietnam</strong>, <strong>Thailand</strong>, <strong>the Philippines</strong>, <strong>Kenya</strong> and <strong>South Africa</strong>, joining India on the list.",
      "## The six new countries of residence",
      "The list of qualifying residences has widened too. Alongside the <strong>United States</strong>, the <strong>United Kingdom</strong> and <strong>EU member states</strong>, an applicant may now hold valid residency in <strong>Singapore</strong>, <strong>Japan</strong>, <strong>South Korea</strong>, <strong>Australia</strong>, <strong>New Zealand</strong> or <strong>Canada</strong>.",
      "Both conditions have to hold at once: an eligible nationality <em>and</em> a valid residence permit from an approved country. A Kenyan national resident in Kenya is not covered by this change; a Kenyan national resident in Canada is.",
      "## What each visa costs and does",
      "<strong>14-day visa — Dh100.</strong> Extendable once during the stay.",
      "<strong>60-day visa — Dh250.</strong> Single entry, and <strong>not extendable</strong>.",
      "The asymmetry is worth pausing on. The cheaper visa is the flexible one; the longer visa is the rigid one. Someone planning a two-month stay with an uncertain end date is choosing between a 60-day visa that cannot move and a 14-day visa that can be extended once — and the second is not obviously the wrong answer.",
      "## The overstay figure",
      "Overstaying carries a fine of <strong>Dh50 per day</strong>. On a non-extendable 60-day visa, that is the number to hold in mind when booking a return flight for the sixtieth day rather than the fifty-eighth.",
    ],
    expertise:
      "A visa on arrival is granted at the counter, not before the flight — which means the residence permit is the document to have ready in hand, not filed in an email. The single most common cause of a refusal in this category is a residence permit that expires during the intended stay, since the entry visa cannot outlive the residency that qualified it.",
  },
  {
    slug: "two-year-investor-visa-minimum-dropped",
    createdAt: "2026-08-25T18:18:34+04:00",
    updatedAt: "2026-09-06T08:48:11+04:00",
    site: "visas",
    // Layout appends " — Dubai Residency & Golden Visa", leaving 28
    // characters. "2-year" rather than "two-year" purely to fit.
    title: "2-year visa minimum dropped",
    summary:
      "The Dh750,000 property minimum on Dubai's two-year investor visa has been dropped for sole owners — a change that appeared in the Dubai Land Department's Cube Center without a formal announcement.",
    // Dated to the source's own publication, not to the change itself: the
    // change was never formally announced, so no reliable date for it
    // exists. The body says so rather than implying this is the date it
    // took effect.
    date: "2026-04-29",
    category: "Residency",
    image: "/news/investor-visa-thresholds.svg",
    imageAlt:
      "Cut-paper illustration: three tower blocks of different heights with a key shape at their base.",
    imageKind: "diagram",
    imageCredit: "DST",
    imageWidth: 1200,
    imageHeight: 600,
    source: {
      name: "Gulf News",
      url: "https://gulfnews.com/living-in-uae/visa-immigration/dubai-residency-by-investment-guide-1.500523250",
      verifiedOn: "2026-08-25",
    },
    body: [
      "Dubai has eased the property requirement on its two-year, property-linked investor visa: the previous <strong>Dh750,000 minimum has been dropped</strong> for sole owners of a fully paid property. For jointly owned property, the threshold reported is AED 400,000 per investor.",
      "The change carries an important caveat. As Gulf News reports it, <strong>no formal announcement was made</strong> — the updated requirements simply appeared on the Cube Center, a Dubai Land Department affiliate that handles services for property investors. There is no official effective date attached to it.",
      "The other two routes are unchanged: the five-year retirement visa still asks for <strong>AED 1 million</strong> in property and an applicant aged 55 or over, and the ten-year Golden Visa still asks for <strong>AED 2 million</strong>, held as one property or a portfolio.",
    ],
    expertise:
      "Two things are worth separating here. First, this affects the entry-level two-year visa only — the Golden Visa threshold has not moved, and the two get conflated constantly. Second, a requirement that changes inside a service platform without an announcement is not the same as one published in a resolution: it can be clarified, applied inconsistently between counters, or revised. Confirm the current position directly with the DLD or GDRFA before making a purchase that depends on it, rather than treating the figure above as settled.",
    related: [
      {
        href: "/golden/",
        image: "/covers/golden.jpg",
        imageAlt: "Cut-paper illustration: an upright rectangle with a rosette disc at its centre.",
        title: "Golden Visa via property",
        text: "The ten-year route in full: eligibility, thresholds and what the process actually involves.",
        eyebrow: "Golden Visa",
      },
      {
        href: "/properties/",
        image: "/covers/properties.jpg",
        imageAlt: "Cut-paper illustration: three tower blocks of different heights with a key shape at their base.",
        title: "Properties that qualify",
        text: "A filtered shortlist of listings that meet the investment threshold, by area and type.",
        eyebrow: "Properties",
      },
    ],
  },
];
