// Intrinsic size and modern-format variants for every picture in the
// network, generated by tools/images.mjs and committed — see the note at
// the top of that file for why it isn't computed during the build.
import manifest from "./images.json" with { type: "json" };

interface Variant {
  width: number;
  height: number;
  avif: [number, string][];
  webp: [number, string][];
}

const byHost = manifest as Record<string, Record<string, Variant>>;

export interface ImageSources {
  width: number;
  height: number;
  avif: string;
  webp: string;
}

/** Sources for a picture, or undefined when we have no variants for it —
    the caller then falls back to a plain <img> on the original file. */
export function imageSources(host: string | undefined, src: string): ImageSources | undefined {
  if (!host) return undefined;
  // The hub's aggregated feed carries cards from the verticals, whose
  // pictures are absolute URLs on the vertical's own host. Those resolve
  // against that host's entry, not the page's — otherwise the one place in
  // the network that shows other sites' pictures is the one place serving
  // them unoptimised.
  let lookupHost = host;
  let lookupSrc = src;
  if (/^https?:\/\//i.test(src)) {
    const url = new URL(src);
    lookupHost = url.hostname;
    lookupSrc = url.pathname;
  }
  // The hub also carries copies of the verticals' pictures under its own
  // paths, so the lookup is per host rather than global.
  const entry = byHost[lookupHost]?.[lookupSrc];
  if (!entry) return undefined;
  // A variant path is root-relative, which would resolve against the page's
  // own host — wrong when the picture belongs to another site in the
  // network, so those get the owning origin in front.
  const origin = lookupHost === host ? "" : `https://${lookupHost}`;
  const srcset = (list: [number, string][]) =>
    list.map(([w, url]) => `${origin}${url} ${w}w`).join(", ");
  return {
    width: entry.width,
    height: entry.height,
    avif: srcset(entry.avif),
    webp: srcset(entry.webp),
  };
}

export { byHost as imagesByHost };
