import type { EventItem } from "../types.ts";

export const items: EventItem[] = [
  {
    slug: "festival-cafe-y-chocolate-2026",
    site: "cmx",
    image: "/covers/festival-cafe-y-chocolate-2026.jpg",
    imageAlt: "Una taza de papel rosa pálido recortada sobre un fondo crema, con una flor naranja de cinco pétalos apoyada en su costado izquierdo y una vaina de cacao abierta, en color vino, junto a ella",
    imageKind: "generated",
    imageWidth: 1536,
    imageHeight: 864,
    title: "Festival Cultural del Café y el Chocolate, edición Día de Muertos",
    cardTitle: "Café y Chocolate, edición Día de Muertos",
    titleSeo: "Festival Café y Chocolate 2026 en Coyoacán",
    summary:
      "Tres días de café, cacao y todo lo que lleva una ofrenda, del 2 al 4 de octubre en el Museo Nacional de Culturas Populares, en Coyoacán, con entrada libre.",
    start: "2026-10-02",
    end: "2026-10-04",
    startTime: "11:00",
    endTime: "19:00",
    utcOffset: "-06:00",
    city: "Ciudad de México",
    venue: "Museo Nacional de Culturas Populares, Avenida Hidalgo 289, Del Carmen, Coyoacán",
    geo: { lat: 19.3499524, lng: -99.1610279 },
    category: "Festival",
    organizer: "Café y Chocolate Fest",
    tickets: { priceFrom: 0 },
    source: {
      name: "Café y Chocolate Fest",
      url: "https://www.instagram.com/cafeychocolatefest_/p/DcbwTXzk4xX/",
      verifiedOn: "2026-09-06",
    },
    body: [
      "El festival lleva años ocupando el patio del Museo Nacional de Culturas Populares en octubre. Esta edición se arma alrededor del Día de Muertos, que es la temporada en que el cacao deja de ser un antojo y vuelve a ser un ingrediente de ofrenda",
      "## Cuándo y dónde",
      "<strong>Viernes 2, sábado 3 y domingo 4 de octubre de 2026</strong>, de <strong>11:00 a 19:00</strong>, en el <strong>Museo Nacional de Culturas Populares</strong>, <strong>Avenida Hidalgo 289</strong>, colonia Del Carmen, Coyoacán",
      "## Cuánto cuesta",
      "Nada. <strong>Entrada libre</strong> los tres días",
      "## Qué hay",
      "Productores de café, cacao y chocolate; <strong>catas de café</strong> y <strong>talleres sensoriales</strong>; <strong>ceremonias de cacao</strong>; catrinas y alebrijes; música, danza y teatro; cuenta cuentos; y lo que se necesita para poner una ofrenda",
      "## Cómo llegar",
      "El museo está a cuatro calles del centro de Coyoacán. En Metro, <strong>Viveros/Derechos Humanos</strong> de la <strong>Línea 3</strong> queda a unos quince minutos caminando; <strong>Coyoacán</strong>, de la misma línea, a veinte. El fin de semana el centro se llena, así que llegar en transporte ahorra la vuelta buscando dónde dejar el coche",
    ],
    expertise:
      "Conviene separar este festival de los otros dos que ocurren cerca y en las mismas semanas: la Feria Artesanal del Café y el Chocolate, del 11 al 13 de septiembre, y Cacao Para Todos, en el Museo Diego Rivera Anahuacalli, del 29 de octubre al 1 de noviembre. Los tres son gratuitos, los tres son en Coyoacán y los nombres se parecen lo suficiente para que más de una agenda los confunda. Este es el del museo de Culturas Populares, y son el 2, 3 y 4 de octubre. El dato viene del cartel que publicó el propio organizador; el calendario en línea del museo no lo tiene cargado, lo cual dice más de la agenda del sitio que del festival",
  },

  {
    slug: "grito-2026-alcaldia-miguel-hidalgo",
    site: "cmx",
    image: "/covers/grito-2026-alcaldia-miguel-hidalgo.jpg",
    imageAlt: "Una campana de papel magenta colgada de un hilo sobre un fondo crema, y debajo una hilera de banderines triangulares del mismo color",
    imageKind: "generated",
    imageWidth: 1536,
    imageHeight: 864,
    title: "Grito de Independencia 2026 en la explanada de Miguel Hidalgo",
    cardTitle: "El Grito en Miguel Hidalgo",
    titleSeo: "El Grito 2026 en la alcaldía Miguel Hidalgo",
    summary:
      "Tres conciertos gratuitos en la explanada de la alcaldía el 15 de septiembre: Embajadores de la Cumbia Dinamita a las 19:00, Los Yaguaru a las 21:00 y Paty Cantú a las 23:15.",
    start: "2026-09-15",
    startTime: "15:00",
    utcOffset: "-06:00",
    city: "Ciudad de México",
    venue: "Explanada de la alcaldía Miguel Hidalgo, Avenida Parque Lira 94, Observatorio",
    geo: { lat: 19.4070465, lng: -99.1906501 },
    category: "Fiestas patrias",
    organizer: "Alcaldía Miguel Hidalgo",
    tickets: { priceFrom: 0 },
    source: {
      name: "Chilango",
      url: "http://www.chilango.com/que-hacer/grito-de-independencia-2026-concierto-gratis-los-yaguaru-y-paty-cantu-en-cdmx",
      verifiedOn: "2026-09-06",
    },
    body: [
      "El Zócalo no es el único lugar donde se grita. Cada alcaldía monta el suyo, y el de Miguel Hidalgo terminó con un cartel que aguanta la comparación",
      "## Cuándo y dónde",
      "<strong>Martes 15 de septiembre de 2026</strong>, en la <strong>explanada de la alcaldía Miguel Hidalgo</strong>, en <strong>Avenida Parque Lira 94</strong>, colonia Observatorio. Las actividades empiezan a las <strong>15:00</strong> y los conciertos a las <strong>19:00</strong>",
      "## El cartel, por horario",
      "<strong>19:00</strong> — <strong>Embajadores de la Cumbia Dinamita</strong>. <strong>21:00</strong> — <strong>Los Yaguaru</strong>. <strong>23:15</strong> — <strong>Paty Cantú</strong>",
      "## Cuánto cuesta",
      "Nada. <strong>Entrada libre</strong>",
      "## Cómo llegar sin coche",
      "Es de los puntos mejor conectados de la ciudad para una noche así: <strong>Parque Lira</strong> del Metrobús Línea 2, <strong>Constituyentes</strong> del Metro Línea 7, <strong>Los Pinos/Constituyentes</strong> del Cablebús Línea 3 y <strong>Tacubaya</strong>, que junta las líneas <strong>1, 7 y 9</strong> del Metro",
    ],
    expertise:
      "La decisión práctica no es a cuál ir sino cómo salir. El horario está armado al revés de lo que conviene: el número principal empieza a las 23:15, y el Metro cierra a medianoche entre semana. Quien se quede hasta el final de Paty Cantú va a estar buscando transporte a la una de la mañana en una explanada que acaba de vaciarse. Con cuatro estaciones alrededor, el plan sensato es llegar en transporte y regresar en otra cosa, o quedarse hasta Los Yaguaru y salir con la línea 7 todavía abierta",
  },

  {
    slug: "festival-xochiska-2026",
    site: "cmx",
    image: "/covers/festival-xochiska-2026.jpg",
    imageAlt: "Una máscara de papel recortada en dos colores sobre un fondo crema, con franjas verticales detrás",
    imageKind: "generated",
    imageWidth: 1536,
    imageHeight: 864,
    title: "Festival Xochiska 2026",
    summary:
      "Quince bandas de ska y punk más una función de lucha libre, el sábado 5 de septiembre en el Centro Deportivo Xochimilco, por $450.",
    start: "2026-09-05",
    startTime: "12:00",
    utcOffset: "-06:00",
    city: "Ciudad de México",
    venue: "Centro Deportivo Xochimilco, Francisco Goitia S/N, Santiago Tepalcatlalpan, Xochimilco",
    category: "Música",
    organizer: "Festival Xochiska",
    tickets: {
      priceFrom: 450,
      currency: "MXN",
    },
    source: {
      name: "Chilango",
      url: "http://www.chilango.com/que-hacer/musica/festival-xochiska-cdmx-victimas-del-doctor-cerebro",
      verifiedOn: "2026-09-03",
    },
    body: [
      "Hay festivales que ponen una segunda pista de baile. Éste pone un ring.",
      "## Cuándo y dónde",
      "<strong>Sábado 5 de septiembre de 2026</strong>, en el <strong>Centro Deportivo Xochimilco</strong> (Francisco Goitia S/N, Santiago Tepalcatlalpan). Las puertas abren a las <strong>11:00</strong> y la música empieza a las <strong>12:00</strong>.",
      "## El cartel",
      "Más de <strong>15 bandas</strong>, entre ellas <strong>Los Calzones</strong>, <strong>Sekta Core</strong>, <strong>Las Víctimas del Doctor Cerebro</strong> y <strong>Los Korukos</strong>.",
      "## Y la lucha libre",
      "En el mismo recinto hay una función a cargo de la <strong>Promotora del Sur</strong> que conmemora los <strong>40 años de carrera del Dr. Wagner</strong>. No es un intermedio: es la otra mitad del programa.",
      "## Boletos y acceso",
      "<strong>$450</strong> pesos, a través de la aplicación <strong>FANKI</strong>. El acceso es para mayores de <strong>18 años</strong> con INE o pasaporte; los menores deben ir acompañados.",
      "## Qué no entra",
      "Alimentos, bebidas alcohólicas, armas, cámaras profesionales, paraguas y vapeadores.",
    ],
    expertise:
      "Xochimilco es el punto de la ciudad donde el Metro se acaba y empieza otra cosa, así que el traslado merece pensarse antes que el cartel: Línea 2 hasta Tasqueña y de ahí el Tren Ligero hasta la estación Francisco Goitia, que deja el deportivo a distancia caminable. La vuelta es la parte delicada, porque el Tren Ligero tiene horario de cierre y un festival que arranca a mediodía puede terminar cerca de él. La lista de prohibiciones incluye paraguas, y septiembre es el mes más lluvioso del año en la ciudad — impermeable, no sombrilla. Y el requisito de identificación es literal: sin INE o pasaporte no hay acceso, aunque el boleto esté comprado.",
  },

  {
    slug: "gran-premio-ciudad-de-mexico-2026",
    featured: 1,
    site: "cmx",
    image: "/covers/gran-premio-ciudad-de-mexico-2026.jpg",
    imageAlt: "Una cinta de papel a cuadros que serpentea sobre fondo crema",
    imageKind: "generated",
    imageWidth: 1536,
    imageHeight: 864,
    title: "Gran Premio de la Ciudad de México 2026",
    summary:
      "La Fórmula 1 vuelve al Autódromo Hermanos Rodríguez del 30 de octubre al 1 de noviembre, con la carrera el domingo a las 2pm y un reglamento técnico nuevo.",
    start: "2026-10-30",
    end: "2026-11-01",
    startTime: "12:30",
    utcOffset: "-06:00",
    city: "Ciudad de México",
    venue: "Autódromo Hermanos Rodríguez, Viaducto Piedad s/n, Ciudad Deportiva",
    category: "Deporte",
    organizer: "Mexico GP",
    geo: {
      name: "Autódromo Hermanos Rodríguez",
      lat: 19.406245,
      lng: -99.094593,
    },
    tickets: {
      priceFrom: 3900,
      priceTo: 61750,
      currency: "MXN",
    },
    source: {
      name: "Time Out México",
      url: "https://www.timeoutmexico.mx/ciudad-de-mexico/que-hacer/gran-premio-de-la-ciudad-de-mexico",
      verifiedOn: "2026-08-30",
    },
    body: [
      "El fin de semana de carrera va del <strong>viernes 30 de octubre al domingo 1 de noviembre de 2026</strong> en el Autódromo Hermanos Rodríguez, en la Ciudad Deportiva. La carrera es el <strong>domingo a las 2pm</strong>",
      "## Lo que cambia este año no es la pista",
      "El trazado es el mismo; el reglamento no. Los motores de <strong>2026</strong> reparten su potencia casi mitad y mitad entre <strong>gasolina sustentable</strong> y <strong>energía eléctrica</strong>",
      "Al triplicarse la potencia eléctrica disponible <strong>desaparece el DRS</strong>. En su lugar hay <strong>aerodinámica activa</strong>: alerones que se cierran en curva para dar agarre y se aplanan en recta para ganar velocidad",
      "La consecuencia deportiva es la que hay que entender antes de sentarse en la tribuna. Durante quince años el rebase fue un botón: alcanzar al de adelante dentro de un segundo, abrir el DRS, pasar. Ahora el rebase es una decisión sobre cuándo soltar la carga eléctrica acumulada al frenar — el adelantamiento deja de ser un permiso y vuelve a ser una apuesta",
      "## Por qué esto importa en México en particular",
      "El Hermanos Rodríguez corre a <strong>2 240 metros de altitud</strong>, la mayor del calendario. Menos aire significa menos carga aerodinámica y menos refrigeración: los coches van con las alas más cargadas que en ningún otro circuito y aun así deslizan. Un reglamento que reparte potencia entre motor térmico y eléctrico llega aquí con una variable extra, porque la parte eléctrica no pierde nada por la altura y la térmica sí",
      "Súmese la recta principal, de las más largas del año, y el estadio — la sección lenta dentro del antiguo diamante de béisbol, con grada a los dos lados. Es el único lugar del calendario donde un piloto pasa por dentro de un estadio lleno a poco más de cien por hora",
      "## Boletos",
      "Los precios publicados van de <strong>$3,900</strong> a <strong>$61,750</strong> pesos. La diferencia entre los extremos no es sólo comodidad: las zonas caras miran la recta y la frenada de la primera curva, y las baratas suelen ver una sección de paso",
      "## Cómo llegar",
      "El transporte que indica el propio circuito es el <strong>Metro Ciudad Deportiva</strong>, que deja a pie del autódromo",
    ],
    programme: [
      { heading: "Práctica 1 — viernes 30, 12:30pm", text: "Primera salida a pista del fin de semana." },
      { heading: "Práctica 2 — viernes 30, 4pm", text: "La sesión larga del viernes, con luz de tarde." },
      { heading: "Práctica 3 — sábado 31, 11:30am", text: "Última puesta a punto antes de la clasificación." },
      { heading: "Clasificación — sábado 31, 3pm", text: "Define la parrilla del domingo." },
      { heading: "Carrera — domingo 1 de noviembre, 2pm", text: "La bandera a cuadros del fin de semana." },
    ],
    expertise:
      "El domingo de carrera cae el 1 de noviembre y el sábado 31 es el Gran Desfile de Día de Muertos sobre Reforma. Son dos extremos de la ciudad y el mismo fin de semana: se pueden hacer los dos, pero no improvisando el traslado — y el sábado, además, es día de clasificación por la tarde",
  },
  {
    slug: "gran-desfile-dia-de-muertos-2026",
    featured: 2,
    site: "cmx",
    image: "/covers/gran-desfile-dia-de-muertos-2026.jpg",
    imageAlt: "Papel picado en la parte alta y flores de cempasúchil abajo",
    imageKind: "generated",
    imageWidth: 1536,
    imageHeight: 864,
    title: "Gran Desfile de Día de Muertos 2026",
    summary:
      "Sábado 31 de octubre sobre Paseo de la Reforma: más de cuatro horas de carros alegóricos, catrinas monumentales y danza. La temática todavía no se anuncia.",
    start: "2026-10-31",
    utcOffset: "-06:00",
    city: "Ciudad de México",
    venue: "Paseo de la Reforma",
    category: "Festival",
    organizer: "Gobierno de la Ciudad de México",
    geo: {
      name: "Paseo de la Reforma",
      lat: 19.427003,
      lng: -99.167668,
    },
    source: {
      name: "Time Out México",
      url: "https://www.timeoutmexico.mx/ciudad-de-mexico/que-hacer/desfile-dia-de-muertos-cdmx-fecha-y-ruta",
      verifiedOn: "2026-08-30",
    },
    body: [
      "El desfile es el <strong>sábado 31 de octubre de 2026</strong> y recorre las avenidas principales de la ciudad, con <strong>Paseo de la Reforma</strong> como eje. Son <strong>más de cuatro horas</strong> de carros alegóricos, danza y catrinas monumentales",
      "## La tradición tiene diez años, no cien",
      "El dato que sorprende a quien lo ve por primera vez: el desfile nace de una escena de ficción. La secuencia inicial de <em>Spectre</em>, de <strong>2015</strong>, inventó un desfile de Día de Muertos que la Ciudad de México no tenía. La ciudad lo montó de verdad al año siguiente",
      "Hoy convoca a más de <strong>un millón trescientos mil asistentes</strong>. Es decir: una película imaginó una tradición mexicana, y México decidió que era buena idea y la construyó. Lo interesante no es la anécdota sino lo que revela — que el Día de Muertos ya era una fiesta lo bastante viva para absorber un desfile inventado sin que se le notara la costura",
      "Conviene no confundirlo con la fiesta misma. El Día de Muertos se celebra el <strong>1 y 2 de noviembre</strong>, en casas y panteones, y no se parece a esto. El desfile es el acto público de una ciudad; la ofrenda es otra cosa",
      "## Lo que sí está confirmado para 2026",
      "La <strong>temática todavía no se anuncia</strong>, así que aquí no aparece",
      "Lo que sí está confirmado es que habrá <strong>instalaciones y ofrendas en las 16 alcaldías</strong>, no sólo sobre el corredor del desfile. Para quien vive lejos del centro, ése es el dato útil: no hace falta ir a Reforma para ver algo",
      "## Cómo verlo",
      "Reforma se cierra desde temprano y el desfile avanza despacio, que es la condición de todo desfile con carros grandes: lo que para el espectador es lentitud, para la logística es la única velocidad posible",
    ],
    expertise:
      "El tramo entre el Ángel y el Zócalo es el más congestionado; el arranque, más arriba sobre Reforma, es donde todavía se ve pasar cada carro completo. Y como el desfile dura más de cuatro horas, llegar tarde no significa perdérselo: significa verlo desde el final de la ruta, con menos gente y con los carros ya en movimiento",
  },
  {
    slug: "del-color-de-la-sandia-cenart",
    site: "cmx",
    image: "/covers/del-color-de-la-sandia-cenart.jpg",
    imageAlt: "Dos rebanadas de sandía recortadas en papel",
    imageKind: "generated",
    imageWidth: 1536,
    imageHeight: 864,
    title: "Del color de la sandía",
    summary:
      "Ciclo de fiestas patrias en el Centro Nacional de las Artes durante septiembre: música mexicana, danza folclórica y ópera, buena parte con entrada libre.",
    start: "2026-09-02",
    startTime: "19:00",
    utcOffset: "-06:00",
    city: "Ciudad de México",
    venue: "Centro Nacional de las Artes, Country Club Churubusco",
    geo: { name: "Centro Nacional de las Artes", lat: 19.355607, lng: -99.137182 },
    category: "Festival",
    organizer: "Centro Nacional de las Artes",
    source: {
      name: "Time Out México",
      url: "https://www.timeoutmexico.mx/ciudad-de-mexico/arte/del-color-de-la-sandia-cenart-programa",
      verifiedOn: "2026-08-30",
    },
    body: [
      "El ciclo abre el <strong>miércoles 2 de septiembre a las 7pm</strong> en la Plaza de las Artes, con el concierto de entrada libre «Doctor Zoppa», y sigue a lo largo de septiembre en varios foros del CENART",
      "## Casi todo es gratis",
      "Lo que distingue a este programa de otra cartelera de fiestas patrias es cuánto de él no cuesta. De las funciones anunciadas, el <strong>recital de ópera</strong>, el <strong>ensamble de alientos y percusiones</strong> y el <strong>mariachi</strong> entran sin costo",
      "Lo que se paga son las funciones de danza y los conciertos de corridos: entre <strong>$180 y $250</strong>. Es una proporción poco común — en la mayoría de los ciclos institucionales lo gratuito es el relleno y lo pagado es el plato fuerte; aquí el recital de los Cantantes Solistas de la Ópera de Bellas Artes es gratuito y la danza folclórica cuesta",
      "## El título",
      "«Del color de la sandía» nombra los tres colores de la bandera con una fruta, que es la manera mexicana de decir las cosas patrias sin ponerse solemne. El programa se comporta igual: ópera y mariachi en el mismo cartel, sin jerarquía declarada entre uno y otro",
      "## Dónde ocurre cada cosa",
      "El ciclo usa varios foros del CENART, y no son intercambiables. La <strong>Plaza de las Artes</strong> y la <strong>Plaza de la Danza</strong> son al aire libre — se llega, se para uno, se va. El <strong>Auditorio Blas Galindo</strong> es sala cerrada con aforo, y ahí conviene llegar temprano aunque la entrada sea libre, porque libre no quiere decir ilimitada",
      "## Hasta cuándo",
      "No se anuncia fecha de cierre del ciclo, así que aquí no se inventa una. La programación publicada llega hasta mediados de septiembre",
    ],
    programme: [
      { heading: "2 de septiembre, 7pm — Doctor Zoppa", text: "Plaza de las Artes. Entrada libre." },
      { heading: "4 de septiembre, 6pm — Música Mexicana", text: "Recital de los Cantantes Solistas de la Ópera de Bellas Artes, Rodolfo Acosta y Arturo Barrera. Auditorio Blas Galindo. Entrada libre." },
      { heading: "4, 5 y 6 de septiembre — Miscelánea Mexicana", text: "Danza folclórica por la compañía Despliegues. $180." },
      { heading: "5 de septiembre, 7pm — Corridos de Música Mexicana", text: "«La Rielera», «La Adelita», «Siete Leguas». Auditorio Blas Galindo. $250." },
      { heading: "6 de septiembre, 1:30pm — Centzontli", text: "Ensamble de alientos y percusiones. Auditorio Blas Galindo. Entrada libre." },
      { heading: "11 de septiembre, 7pm — El Mariachi 2000 de Cutberto Pérez", text: "Auditorio Blas Galindo. Entrada libre." },
      { heading: "12 y 13 de septiembre, 4pm — Evocaciones de mi tierra", text: "Danza Tradicional Mexicana de la Facultad de Química de la UNAM. Plaza de la Danza." },
      { heading: "13 de septiembre, 12pm — Mexicano soy", text: "Orquesta Típica de la Ciudad de México. Auditorio Blas Galindo." },
    ],
    expertise:
      "Entrada libre en el Blas Galindo significa fila, no reservación. Para el recital de ópera del 4 de septiembre y el mariachi del 11 conviene estar en la puerta media hora antes; para lo que ocurre en las plazas, basta con llegar",
  },
  {
    slug: "monsivais-en-el-estanquillo",
    site: "cmx",
    image: "/covers/monsivais-en-el-estanquillo.jpg",
    imageAlt: "Siluetas de papel flotando en filas: un sombrero, una bicicleta, una guitarra, unos anteojos y un perro",
    imageKind: "generated",
    imageWidth: 1536,
    imageHeight: 864,
    title: "Porque ahora pienso en ti, más que ayer, mucho más",
    summary:
      "Cinco instalaciones inmersivas de Betsabeé Romero sobre el universo de Carlos Monsiváis: la primera instalación que el Museo del Estanquillo alberga en sus casi veinte años.",
    start: "2026-08-29",
    startTime: "12:00",
    utcOffset: "-06:00",
    city: "Ciudad de México",
    venue: "Museo del Estanquillo, Isabel La Católica 26, Centro Histórico",
    category: "Exposición",
    organizer: "Museo del Estanquillo",
    source: {
      name: "El Universal",
      url: "https://www.eluniversal.com.mx/cultura/la-artista-betsabee-romero-rinde-homenaje-a-carlos-monsivais-con-nueva-exposicion/",
      verifiedOn: "2026-08-30",
    },
    body: [
      "La exposición abrió el <strong>sábado 29 de agosto de 2026 a las 12 horas</strong> en el <strong>Museo del Estanquillo</strong>, Isabel La Católica 26, Centro Histórico",
      "Es la <strong>primera instalación</strong> que presenta, en casi veinte años, el museo que Carlos Monsiváis fundó con su propia colección. Se conmemora el <strong>aniversario 16</strong> de su fallecimiento",
      "## El título es una canción",
      "<strong>«Porque ahora pienso en ti, más que ayer, mucho más»</strong> es un verso de «Hasta que te conocí», de Juan Gabriel. Betsabeé Romero lo eligió por lo que ha estado pensando sobre Monsiváis en estos meses — entre el entusiasmo callejero del Mundial y la discusión sobre inteligencia artificial",
      "Titular con Juan Gabriel un homenaje a un cronista es el argumento entero en una línea: Monsiváis fue quien sostuvo que la cultura popular era el tema y no el adorno",
      "## Las salas",
      "Romero adaptó la sala 3 como una serie de habitaciones, cada una sobre un aspecto de su escritura",
      "<strong>La sala de la lupa feroz</strong>: lupas con imágenes grabadas que se proyectan sobre libros del autor, por el Monsiváis memorista que buscaba «lo desaparecido, lo minúsculo y lo invisible»",
      "<strong>La sala de los lentes</strong>: lentes grabados con paisajes citadinos reflejados sobre manos de papel, cuyas líneas son las <strong>líneas de metro que pasan por la colonia Portales</strong>, donde vivió. Las manos llevan curitas — escribía a mano y se lastimaba",
      "<strong>El Santo y las máscaras de la ciudad</strong>, sobre lucha libre, y <strong>La televisión tatuada</strong>, un cuarto de televisores de bulbo con los rostros de Juan Gabriel, María Félix y Salvador Novo",
      "## Por qué grabado",
      "Romero trabaja el grabado, y la técnica conecta con el homenajeado por la vía menos obvia: Monsiváis no coleccionó pintura, coleccionó gráfica popular. La artista lo dice como un elogio — que era coherente hasta en lo que coleccionaba",
      "## Cuándo cierra",
      "No hay fecha de cierre publicada. Conviene confirmar con el museo antes de ir sobre el filo",
    ],
    expertise:
      "Es una instalación, no una muestra de piezas: se recorre en un orden y buena parte del efecto está en lo que se proyecta sobre los libros. Media hora larga, y mejor entre semana — la sala 3 es pequeña y con gente adentro las proyecciones dejan de leerse",
  },
];
