import type { EventItem } from "../types.ts";

export const items: EventItem[] = [
  {
    slug: "festival-cafe-y-chocolate-2026",
    createdAt: "2026-08-30T11:52:01+04:00",
    updatedAt: "2026-09-08T15:51:10+04:00",
    site: "cmx",
    image: "/covers/festival-cafe-y-chocolate-2026.jpg",
    imageAlt: "Una taza de papel rosa pálido recortada sobre un fondo crema, con una flor naranja de cinco pétalos apoyada en su costado izquierdo y una vaina de cacao abierta, en color vino, junto a ella",
    imageKind: "generated",
    imageWidth: 1536,
    imageHeight: 864,
    title: "Festival Cultural del Café y el Chocolate, edición Día de Muertos",
    titleSeo: "Café y Chocolate 2026 en Coyoacán",
    cardTitle: "Café y Chocolate, edición Día de Muertos",
    summary:
      "Tres días de café, cacao y todo lo que lleva una ofrenda, del 2 al 4 de octubre en el Museo Nacional de Culturas Populares, en Coyoacán, con entrada libre.",
    start: "2026-10-02",
    end: "2026-10-04",
    startTime: "11:00",
    endTime: "19:00",
    utcOffset: "-06:00",
    city: "Ciudad de México",
    venue: "Museo Nacional de Culturas Populares, Avenida Hidalgo 289, Del Carmen, Coyoacán",
    geo: { name: "Museo Nacional de Culturas Populares", lat: 19.3499524, lng: -99.1610279 },
    category: "Festival",
    organizer: "Café y Chocolate Fest",
    tickets: { priceFrom: 0 },
    source: {
      name: "Café y Chocolate Fest",
      url: "https://www.instagram.com/cafeychocolatefest_/p/DcbwTXzk4xX/",
      verifiedOn: "2026-09-06",
    },
    body: [
      "El festival lleva años ocupando el patio del Museo Nacional de Culturas Populares en octubre. Esta edición se arma alrededor del Día de Muertos, que es la temporada en que el cacao deja de ser un antojo y vuelve a ser un ingrediente de ofrenda",
      "## Cuándo y dónde",
      "<strong>Viernes 2, sábado 3 y domingo 4 de octubre de 2026</strong>, de <strong>11:00 a 19:00</strong>, en el <strong>Museo Nacional de Culturas Populares</strong>, <strong>Avenida Hidalgo 289</strong>, colonia Del Carmen, Coyoacán",
      "## Cuánto cuesta",
      "Nada. <strong>Entrada libre</strong> los tres días",
      "## Qué hay",
      "Productores de café, cacao y chocolate; <strong>catas de café</strong> y <strong>talleres sensoriales</strong>; <strong>ceremonias de cacao</strong>; catrinas y alebrijes; música, danza y teatro; cuenta cuentos; y lo que se necesita para poner una ofrenda",
      "## Cómo llegar",
      "El museo está a cuatro calles del centro de Coyoacán. En Metro, <strong>Viveros/Derechos Humanos</strong> de la <strong>Línea 3</strong> queda a unos quince minutos caminando; <strong>Coyoacán</strong>, de la misma línea, a veinte. El fin de semana el centro se llena, así que llegar en transporte ahorra la vuelta buscando dónde dejar el coche",
    ],
    expertise:
      "Conviene separar este festival de los otros dos que ocurren cerca y en las mismas semanas: la Feria Artesanal del Café y el Chocolate, del 11 al 13 de septiembre, y Cacao Para Todos, en el Museo Diego Rivera Anahuacalli, del 29 de octubre al 1 de noviembre. Los tres son gratuitos, los tres son en Coyoacán y los nombres se parecen lo suficiente para que más de una agenda los confunda. Este es el del museo de Culturas Populares, y son el 2, 3 y 4 de octubre. El dato viene del cartel que publicó el propio organizador; el calendario en línea del museo no lo tiene cargado, lo cual dice más de la agenda del sitio que del festival",
  },

  {
    slug: "grito-2026-alcaldia-miguel-hidalgo",
    createdAt: "2026-09-06T22:44:30+04:00",
    updatedAt: "2026-09-08T15:51:10+04:00",
    site: "cmx",
    image: "/covers/grito-2026-alcaldia-miguel-hidalgo.jpg",
    imageAlt: "Una campana de papel magenta colgada de un hilo sobre un fondo crema, y debajo una hilera de banderines triangulares del mismo color",
    imageKind: "generated",
    imageWidth: 1536,
    imageHeight: 864,
    title: "Grito de Independencia 2026 en la explanada de Miguel Hidalgo",
    titleSeo: "El Grito 2026 en Miguel Hidalgo",
    cardTitle: "El Grito en Miguel Hidalgo",
    summary:
      "Tres conciertos gratuitos en la explanada de la alcaldía el 15 de septiembre: Embajadores de la Cumbia Dinamita a las 19:00, Los Yaguaru a las 21:00 y Paty Cantú a las 23:15.",
    start: "2026-09-15",
    startTime: "15:00",
    utcOffset: "-06:00",
    city: "Ciudad de México",
    venue: "Explanada de la alcaldía Miguel Hidalgo, Avenida Parque Lira 94, Observatorio",
    geo: { name: "Explanada de la alcaldía Miguel Hidalgo", lat: 19.4070465, lng: -99.1906501 },
    category: "Fiestas patrias",
    organizer: "Alcaldía Miguel Hidalgo",
    tickets: { priceFrom: 0 },
    source: {
      name: "Chilango",
      url: "http://www.chilango.com/que-hacer/grito-de-independencia-2026-concierto-gratis-los-yaguaru-y-paty-cantu-en-cdmx",
      verifiedOn: "2026-09-06",
    },
    body: [
      "El Zócalo no es el único lugar donde se grita. Cada alcaldía monta el suyo, y el de Miguel Hidalgo terminó con un cartel que aguanta la comparación",
      "## Cuándo y dónde",
      "<strong>Martes 15 de septiembre de 2026</strong>, en la <strong>explanada de la alcaldía Miguel Hidalgo</strong>, en <strong>Avenida Parque Lira 94</strong>, colonia Observatorio. Las actividades empiezan a las <strong>15:00</strong> y los conciertos a las <strong>19:00</strong>",
      "## El cartel, por horario",
      "<strong>19:00</strong> — <strong>Embajadores de la Cumbia Dinamita</strong>. <strong>21:00</strong> — <strong>Los Yaguaru</strong>. <strong>23:15</strong> — <strong>Paty Cantú</strong>",
      "## Cuánto cuesta",
      "Nada. <strong>Entrada libre</strong>",
      "## Cómo llegar sin coche",
      "Es de los puntos mejor conectados de la ciudad para una noche así: <strong>Parque Lira</strong> del Metrobús Línea 2, <strong>Constituyentes</strong> del Metro Línea 7, <strong>Los Pinos/Constituyentes</strong> del Cablebús Línea 3 y <strong>Tacubaya</strong>, que junta las líneas <strong>1, 7 y 9</strong> del Metro",
    ],
    expertise:
      "La decisión práctica no es a cuál ir sino cómo salir. El horario está armado al revés de lo que conviene: el número principal empieza a las 23:15, y el Metro cierra a medianoche entre semana. Quien se quede hasta el final de Paty Cantú va a estar buscando transporte a la una de la mañana en una explanada que acaba de vaciarse. Con cuatro estaciones alrededor, el plan sensato es llegar en transporte y regresar en otra cosa, o quedarse hasta Los Yaguaru y salir con la línea 7 todavía abierta",
  },

  {
    slug: "festival-xochiska-2026",
    createdAt: "2026-09-03T07:30:21+04:00",
    updatedAt: "2026-09-06T22:44:30+04:00",
    site: "cmx",
    image: "/covers/festival-xochiska-2026.jpg",
    imageAlt: "Una máscara de papel recortada en dos colores sobre un fondo crema, con franjas verticales detrás",
    imageKind: "generated",
    imageWidth: 1536,
    imageHeight: 864,
    title: "Festival Xochiska 2026",
    summary:
      "Quince bandas de ska y punk más una función de lucha libre, el sábado 5 de septiembre en el Centro Deportivo Xochimilco, por $450.",
    start: "2026-09-05",
    startTime: "12:00",
    utcOffset: "-06:00",
    city: "Ciudad de México",
    venue: "Centro Deportivo Xochimilco, Francisco Goitia S/N, Santiago Tepalcatlalpan, Xochimilco",
    category: "Música",
    organizer: "Festival Xochiska",
    tickets: {
      priceFrom: 450,
      currency: "MXN",
    },
    source: {
      name: "Chilango",
      url: "http://www.chilango.com/que-hacer/musica/festival-xochiska-cdmx-victimas-del-doctor-cerebro",
      verifiedOn: "2026-09-03",
    },
    body: [
      "Hay festivales que ponen una segunda pista de baile. Éste pone un ring.",
      "## Cuándo y dónde",
      "<strong>Sábado 5 de septiembre de 2026</strong>, en el <strong>Centro Deportivo Xochimilco</strong> (Francisco Goitia S/N, Santiago Tepalcatlalpan). Las puertas abren a las <strong>11:00</strong> y la música empieza a las <strong>12:00</strong>.",
      "## El cartel",
      "Más de <strong>15 bandas</strong>, entre ellas <strong>Los Calzones</strong>, <strong>Sekta Core</strong>, <strong>Las Víctimas del Doctor Cerebro</strong> y <strong>Los Korukos</strong>.",
      "## Y la lucha libre",
      "En el mismo recinto hay una función a cargo de la <strong>Promotora del Sur</strong> que conmemora los <strong>40 años de carrera del Dr. Wagner</strong>. No es un intermedio: es la otra mitad del programa.",
      "## Boletos y acceso",
      "<strong>$450</strong> pesos, a través de la aplicación <strong>FANKI</strong>. El acceso es para mayores de <strong>18 años</strong> con INE o pasaporte; los menores deben ir acompañados.",
      "## Qué no entra",
      "Alimentos, bebidas alcohólicas, armas, cámaras profesionales, paraguas y vapeadores.",
    ],
    expertise:
      "Xochimilco es el punto de la ciudad donde el Metro se acaba y empieza otra cosa, así que el traslado merece pensarse antes que el cartel: Línea 2 hasta Tasqueña y de ahí el Tren Ligero hasta la estación Francisco Goitia, que deja el deportivo a distancia caminable. La vuelta es la parte delicada, porque el Tren Ligero tiene horario de cierre y un festival que arranca a mediodía puede terminar cerca de él. La lista de prohibiciones incluye paraguas, y septiembre es el mes más lluvioso del año en la ciudad — impermeable, no sombrilla. Y el requisito de identificación es literal: sin INE o pasaporte no hay acceso, aunque el boleto esté comprado.",
  },

  {
    slug: "gran-premio-ciudad-de-mexico-2026",
    createdAt: "2026-08-30T20:37:08+04:00",
    updatedAt: "2026-09-07T18:02:29+04:00",
    featured: 1,
    site: "cmx",
    image: "/covers/gran-premio-ciudad-de-mexico-2026.jpg",
    imageAlt: "Una cinta de papel a cuadros que serpentea sobre fondo crema",
    imageKind: "generated",
    imageWidth: 1536,
    imageHeight: 864,
    title: "Gran Premio de la Ciudad de México 2026",
    summary:
      "La Fórmula 1 vuelve al Autódromo Hermanos Rodríguez del 30 de octubre al 1 de noviembre, con la carrera el domingo a las 2pm y un reglamento técnico nuevo.",
    start: "2026-10-30",
    end: "2026-11-01",
    startTime: "12:30",
    utcOffset: "-06:00",
    city: "Ciudad de México",
    venue: "Autódromo Hermanos Rodríguez, Viaducto Piedad s/n, Ciudad Deportiva",
    category: "Deporte",
    organizer: "Mexico GP",
    geo: {
      name: "Autódromo Hermanos Rodríguez",
      lat: 19.406245,
      lng: -99.094593,
    },
    tickets: {
      priceFrom: 3900,
      priceTo: 61750,
      currency: "MXN",
    },
    ticket: {
      url: "https://www.mexicogp.mx/boletos-generales/",
      label: "Boletos en el sitio oficial",
    },
    source: {
      name: "Time Out México",
      url: "https://www.timeoutmexico.mx/ciudad-de-mexico/que-hacer/gran-premio-de-la-ciudad-de-mexico",
      verifiedOn: "2026-08-30",
    },
    body: [
      "El fin de semana de carrera va del <strong>viernes 30 de octubre al domingo 1 de noviembre de 2026</strong> en el Autódromo Hermanos Rodríguez, en la Ciudad Deportiva. La carrera es el <strong>domingo a las 2pm</strong>",
      "## Lo que cambia este año no es la pista",
      "El trazado es el mismo; el reglamento no. Los motores de <strong>2026</strong> reparten su potencia casi mitad y mitad entre <strong>gasolina sustentable</strong> y <strong>energía eléctrica</strong>",
      "Al triplicarse la potencia eléctrica disponible <strong>desaparece el DRS</strong>. En su lugar hay <strong>aerodinámica activa</strong>: alerones que se cierran en curva para dar agarre y se aplanan en recta para ganar velocidad",
      "La consecuencia deportiva es la que hay que entender antes de sentarse en la tribuna. Durante quince años el rebase fue un botón: alcanzar al de adelante dentro de un segundo, abrir el DRS, pasar. Ahora el rebase es una decisión sobre cuándo soltar la carga eléctrica acumulada al frenar — el adelantamiento deja de ser un permiso y vuelve a ser una apuesta",
      "## Por qué esto importa en México en particular",
      "El Hermanos Rodríguez corre a <strong>2 240 metros de altitud</strong>, la mayor del calendario. Menos aire significa menos carga aerodinámica y menos refrigeración: los coches van con las alas más cargadas que en ningún otro circuito y aun así deslizan. Un reglamento que reparte potencia entre motor térmico y eléctrico llega aquí con una variable extra, porque la parte eléctrica no pierde nada por la altura y la térmica sí",
      "Súmese la recta principal, de las más largas del año, y el estadio — la sección lenta dentro del antiguo diamante de béisbol, con grada a los dos lados. Es el único lugar del calendario donde un piloto pasa por dentro de un estadio lleno a poco más de cien por hora",
      "## Boletos",
      "Los precios publicados van de <strong>$3,900</strong> a <strong>$61,750</strong> pesos. La diferencia entre los extremos no es sólo comodidad: las zonas caras miran la recta y la frenada de la primera curva, y las baratas suelen ver una sección de paso",
      "## Cómo llegar",
      "El transporte que indica el propio circuito es el <strong>Metro Ciudad Deportiva</strong>, que deja a pie del autódromo",
    ],
    programme: [
      { heading: "Práctica 1 — viernes 30, 12:30pm", text: "Primera salida a pista del fin de semana." },
      { heading: "Práctica 2 — viernes 30, 4pm", text: "La sesión larga del viernes, con luz de tarde." },
      { heading: "Práctica 3 — sábado 31, 11:30am", text: "Última puesta a punto antes de la clasificación." },
      { heading: "Clasificación — sábado 31, 3pm", text: "Define la parrilla del domingo." },
      { heading: "Carrera — domingo 1 de noviembre, 2pm", text: "La bandera a cuadros del fin de semana." },
    ],
    expertise:
      "El domingo de carrera cae el 1 de noviembre y el sábado 31 es el Gran Desfile de Día de Muertos sobre Reforma. Son dos extremos de la ciudad y el mismo fin de semana: se pueden hacer los dos, pero no improvisando el traslado — y el sábado, además, es día de clasificación por la tarde",
  },
  {
    slug: "gran-desfile-dia-de-muertos-2026",
    createdAt: "2026-08-30T20:37:08+04:00",
    updatedAt: "2026-09-08T22:51:25+04:00",
    featured: 2,
    site: "cmx",
    image: "/covers/gran-desfile-dia-de-muertos-2026.jpg",
    imageAlt: "Papel picado en la parte alta y flores de cempasúchil abajo",
    imageKind: "generated",
    imageWidth: 1536,
    imageHeight: 864,
    title: "Gran Desfile de Día de Muertos 2026",
    summary:
      "Sábado 31 de octubre sobre Paseo de la Reforma: más de cuatro horas de carros alegóricos, catrinas monumentales y danza. La temática todavía no se anuncia.",
    start: "2026-10-31",
    utcOffset: "-06:00",
    city: "Ciudad de México",
    venue: "Paseo de la Reforma",
    category: "Día de Muertos",
    organizer: "Gobierno de la Ciudad de México",
    geo: {
      name: "Paseo de la Reforma",
      lat: 19.427003,
      lng: -99.167668,
    },
    source: {
      name: "Time Out México",
      url: "https://www.timeoutmexico.mx/ciudad-de-mexico/que-hacer/desfile-dia-de-muertos-cdmx-fecha-y-ruta",
      verifiedOn: "2026-08-30",
    },
    body: [
      "El desfile es el <strong>sábado 31 de octubre de 2026</strong> y recorre las avenidas principales de la ciudad, con <strong>Paseo de la Reforma</strong> como eje. Son <strong>más de cuatro horas</strong> de carros alegóricos, danza y catrinas monumentales",
      "## La tradición tiene diez años, no cien",
      "El dato que sorprende a quien lo ve por primera vez: el desfile nace de una escena de ficción. La secuencia inicial de <em>Spectre</em>, de <strong>2015</strong>, inventó un desfile de Día de Muertos que la Ciudad de México no tenía. La ciudad lo montó de verdad al año siguiente",
      "Hoy convoca a más de <strong>un millón trescientos mil asistentes</strong>. Es decir: una película imaginó una tradición mexicana, y México decidió que era buena idea y la construyó. Lo interesante no es la anécdota sino lo que revela — que el Día de Muertos ya era una fiesta lo bastante viva para absorber un desfile inventado sin que se le notara la costura",
      "Conviene no confundirlo con la fiesta misma. El Día de Muertos se celebra el <strong>1 y 2 de noviembre</strong>, en casas y panteones, y no se parece a esto. El desfile es el acto público de una ciudad; la ofrenda es otra cosa",
      "## Lo que sí está confirmado para 2026",
      "La <strong>temática todavía no se anuncia</strong>, así que aquí no aparece",
      "Lo que sí está confirmado es que habrá <strong>instalaciones y ofrendas en las 16 alcaldías</strong>, no sólo sobre el corredor del desfile. Para quien vive lejos del centro, ése es el dato útil: no hace falta ir a Reforma para ver algo",
      "## Cómo verlo",
      "Reforma se cierra desde temprano y el desfile avanza despacio, que es la condición de todo desfile con carros grandes: lo que para el espectador es lentitud, para la logística es la única velocidad posible",
    ],
    faq: [
      {
        q: "¿Cuándo es el Gran Desfile de Día de Muertos 2026?",
        a: "El <strong>sábado 31 de octubre de 2026</strong>, con <strong>Paseo de la Reforma</strong> como eje del recorrido.",
      },
      {
        q: "¿El desfile es el Día de Muertos?",
        a: "No. La fiesta es el <strong>1 y 2 de noviembre</strong>, en casas y panteones. El desfile es el acto público de la ciudad y cae el sábado anterior.",
      },
      {
        q: "¿Cuánto dura?",
        a: "<strong>Más de cuatro horas.</strong> Llegar tarde no significa perdérselo: significa verlo desde el final de la ruta.",
      },
      {
        q: "¿Ya se sabe la temática de este año?",
        a: "Todavía no se anuncia. Lo confirmado son las <strong>instalaciones y ofrendas en las 16 alcaldías</strong>, no sólo sobre el corredor del desfile.",
      },
      {
        q: "¿Cuánta gente va?",
        a: "Más de <strong>un millón trescientos mil asistentes</strong>.",
      },
    ],
    expertise:
      "El tramo entre el Ángel y el Zócalo es el más congestionado; el arranque, más arriba sobre Reforma, es donde todavía se ve pasar cada carro completo. Y como el desfile dura más de cuatro horas, llegar tarde no significa perdérselo: significa verlo desde el final de la ruta, con menos gente y con los carros ya en movimiento",
  },
  {
    slug: "del-color-de-la-sandia-cenart",
    createdAt: "2026-08-30T20:37:08+04:00",
    updatedAt: "2026-09-06T08:48:11+04:00",
    site: "cmx",
    image: "/covers/del-color-de-la-sandia-cenart.jpg",
    imageAlt: "Dos rebanadas de sandía recortadas en papel",
    imageKind: "generated",
    imageWidth: 1536,
    imageHeight: 864,
    title: "Del color de la sandía",
    summary:
      "Ciclo de fiestas patrias en el Centro Nacional de las Artes durante septiembre: música mexicana, danza folclórica y ópera, buena parte con entrada libre.",
    start: "2026-09-02",
    startTime: "19:00",
    utcOffset: "-06:00",
    city: "Ciudad de México",
    venue: "Centro Nacional de las Artes, Country Club Churubusco",
    geo: { name: "Centro Nacional de las Artes", lat: 19.355607, lng: -99.137182 },
    category: "Festival",
    organizer: "Centro Nacional de las Artes",
    source: {
      name: "Time Out México",
      url: "https://www.timeoutmexico.mx/ciudad-de-mexico/arte/del-color-de-la-sandia-cenart-programa",
      verifiedOn: "2026-08-30",
    },
    body: [
      "El ciclo abre el <strong>miércoles 2 de septiembre a las 7pm</strong> en la Plaza de las Artes, con el concierto de entrada libre «Doctor Zoppa», y sigue a lo largo de septiembre en varios foros del CENART",
      "## Casi todo es gratis",
      "Lo que distingue a este programa de otra cartelera de fiestas patrias es cuánto de él no cuesta. De las funciones anunciadas, el <strong>recital de ópera</strong>, el <strong>ensamble de alientos y percusiones</strong> y el <strong>mariachi</strong> entran sin costo",
      "Lo que se paga son las funciones de danza y los conciertos de corridos: entre <strong>$180 y $250</strong>. Es una proporción poco común — en la mayoría de los ciclos institucionales lo gratuito es el relleno y lo pagado es el plato fuerte; aquí el recital de los Cantantes Solistas de la Ópera de Bellas Artes es gratuito y la danza folclórica cuesta",
      "## El título",
      "«Del color de la sandía» nombra los tres colores de la bandera con una fruta, que es la manera mexicana de decir las cosas patrias sin ponerse solemne. El programa se comporta igual: ópera y mariachi en el mismo cartel, sin jerarquía declarada entre uno y otro",
      "## Dónde ocurre cada cosa",
      "El ciclo usa varios foros del CENART, y no son intercambiables. La <strong>Plaza de las Artes</strong> y la <strong>Plaza de la Danza</strong> son al aire libre — se llega, se para uno, se va. El <strong>Auditorio Blas Galindo</strong> es sala cerrada con aforo, y ahí conviene llegar temprano aunque la entrada sea libre, porque libre no quiere decir ilimitada",
      "## Hasta cuándo",
      "No se anuncia fecha de cierre del ciclo, así que aquí no se inventa una. La programación publicada llega hasta mediados de septiembre",
    ],
    programme: [
      { heading: "2 de septiembre, 7pm — Doctor Zoppa", text: "Plaza de las Artes. Entrada libre." },
      { heading: "4 de septiembre, 6pm — Música Mexicana", text: "Recital de los Cantantes Solistas de la Ópera de Bellas Artes, Rodolfo Acosta y Arturo Barrera. Auditorio Blas Galindo. Entrada libre." },
      { heading: "4, 5 y 6 de septiembre — Miscelánea Mexicana", text: "Danza folclórica por la compañía Despliegues. $180." },
      { heading: "5 de septiembre, 7pm — Corridos de Música Mexicana", text: "«La Rielera», «La Adelita», «Siete Leguas». Auditorio Blas Galindo. $250." },
      { heading: "6 de septiembre, 1:30pm — Centzontli", text: "Ensamble de alientos y percusiones. Auditorio Blas Galindo. Entrada libre." },
      { heading: "11 de septiembre, 7pm — El Mariachi 2000 de Cutberto Pérez", text: "Auditorio Blas Galindo. Entrada libre." },
      { heading: "12 y 13 de septiembre, 4pm — Evocaciones de mi tierra", text: "Danza Tradicional Mexicana de la Facultad de Química de la UNAM. Plaza de la Danza." },
      { heading: "13 de septiembre, 12pm — Mexicano soy", text: "Orquesta Típica de la Ciudad de México. Auditorio Blas Galindo." },
    ],
    expertise:
      "Entrada libre en el Blas Galindo significa fila, no reservación. Para el recital de ópera del 4 de septiembre y el mariachi del 11 conviene estar en la puerta media hora antes; para lo que ocurre en las plazas, basta con llegar",
  },
  {
    slug: "monsivais-en-el-estanquillo",
    createdAt: "2026-08-30T11:52:01+04:00",
    updatedAt: "2026-09-07T13:32:58+04:00",
    site: "cmx",
    image: "/covers/monsivais-en-el-estanquillo.jpg",
    imageAlt: "Siluetas de papel flotando en filas: un sombrero, una bicicleta, una guitarra, unos anteojos y un perro",
    imageKind: "generated",
    imageWidth: 1536,
    imageHeight: 864,
    title: "Porque ahora pienso en ti, más que ayer, mucho más",
    titleSeo: "Monsiváis en el Museo del Estanquillo",
    summary:
      "Cinco instalaciones inmersivas de Betsabeé Romero sobre el universo de Carlos Monsiváis: la primera instalación que el Museo del Estanquillo alberga en sus casi veinte años.",
    start: "2026-08-29",
    startTime: "12:00",
    utcOffset: "-06:00",
    city: "Ciudad de México",
    venue: "Museo del Estanquillo, Isabel La Católica 26, Centro Histórico",
    category: "Exposición",
    organizer: "Museo del Estanquillo",
    source: {
      name: "El Universal",
      url: "https://www.eluniversal.com.mx/cultura/la-artista-betsabee-romero-rinde-homenaje-a-carlos-monsivais-con-nueva-exposicion/",
      verifiedOn: "2026-08-30",
    },
    body: [
      "La exposición abrió el <strong>sábado 29 de agosto de 2026 a las 12 horas</strong> en el <strong>Museo del Estanquillo</strong>, Isabel La Católica 26, Centro Histórico",
      "Es la <strong>primera instalación</strong> que presenta, en casi veinte años, el museo que Carlos Monsiváis fundó con su propia colección. Se conmemora el <strong>aniversario 16</strong> de su fallecimiento",
      "## El título es una canción",
      "<strong>«Porque ahora pienso en ti, más que ayer, mucho más»</strong> es un verso de «Hasta que te conocí», de Juan Gabriel. Betsabeé Romero lo eligió por lo que ha estado pensando sobre Monsiváis en estos meses — entre el entusiasmo callejero del Mundial y la discusión sobre inteligencia artificial",
      "Titular con Juan Gabriel un homenaje a un cronista es el argumento entero en una línea: Monsiváis fue quien sostuvo que la cultura popular era el tema y no el adorno",
      "## Las salas",
      "Romero adaptó la sala 3 como una serie de habitaciones, cada una sobre un aspecto de su escritura",
      "<strong>La sala de la lupa feroz</strong>: lupas con imágenes grabadas que se proyectan sobre libros del autor, por el Monsiváis memorista que buscaba «lo desaparecido, lo minúsculo y lo invisible»",
      "<strong>La sala de los lentes</strong>: lentes grabados con paisajes citadinos reflejados sobre manos de papel, cuyas líneas son las <strong>líneas de metro que pasan por la colonia Portales</strong>, donde vivió. Las manos llevan curitas — escribía a mano y se lastimaba",
      "<strong>El Santo y las máscaras de la ciudad</strong>, sobre lucha libre, y <strong>La televisión tatuada</strong>, un cuarto de televisores de bulbo con los rostros de Juan Gabriel, María Félix y Salvador Novo",
      "## Por qué grabado",
      "Romero trabaja el grabado, y la técnica conecta con el homenajeado por la vía menos obvia: Monsiváis no coleccionó pintura, coleccionó gráfica popular. La artista lo dice como un elogio — que era coherente hasta en lo que coleccionaba",
      "## Cuándo cierra",
      "No hay fecha de cierre publicada. Conviene confirmar con el museo antes de ir sobre el filo",
    ],
    expertise:
      "Es una instalación, no una muestra de piezas: se recorre en un orden y buena parte del efecto está en lo que se proyecta sobre los libros. Media hora larga, y mejor entre semana — la sala 3 es pequeña y con gente adentro las proyecciones dejan de leerse",
  },

  {
    slug: "nayarit-en-los-pinos-2026",
    createdAt: "2026-09-08T16:29:32+04:00",
    updatedAt: "2026-09-08T16:34:13+04:00",
    site: "cmx",
    image: "/covers/nayarit-en-los-pinos-2026.jpg",
    imageAlt: "Una olla de barro roja con su tapa puesta, sobre un fondo crema",
    imageKind: "generated",
    imageWidth: 1536,
    imageHeight: 864,
    title: "Nayarit en Los Pinos 2026",
    summary:
      "Dos días de cocina, artesanía y música de Nayarit en el Complejo Cultural Los Pinos, en la Ciudad de México, el 12 y 13 de septiembre, de 10:00 a 17:00 y con entrada libre.",
    start: "2026-09-12",
    end: "2026-09-13",
    startTime: "10:00",
    endTime: "17:00",
    utcOffset: "-06:00",
    venue: "Complejo Cultural Los Pinos, Bosque de Chapultepec I Sección",
    city: "Ciudad de México",
    country: "México",
    organizer: "Secretaría de Cultura del Gobierno de México",
    category: "Festival",
    tickets: { priceFrom: 0, currency: "MXN" },
    source: {
      name: "Chilango",
      url: "https://www.chilango.com/que-hacer/festival-nayarit-en-los-pinos-fecha-lugar-horarios-gastronomia-artesanias-cdmx/",
      verifiedOn: "2026-09-08",
    },
    body: [
      "Durante casi ochenta años, entrar aquí requería una invitación presidencial. Este fin de semana se entra gratis, y lo que hay adentro es Nayarit.",
      "## Los datos",
      "<strong>Sábado 12 y domingo 13 de septiembre de 2026</strong>, de <strong>10:00 a 17:00</strong>, en el <strong>Complejo Cultural Los Pinos</strong>, dentro de la Primera Sección del Bosque de Chapultepec. <strong>Entrada libre</strong>. Es una iniciativa de la <strong>Secretaría de Cultura</strong> del Gobierno de México.",
      "## Qué se presenta",
      "Una <strong>Gala de la Canción Mexicana de Concierto</strong> con la <strong>Orquesta de Cámara de Nayarit</strong> y <strong>Voces OCANAY</strong>; el <strong>Mariachi Tradicional Femenil Flor de la Sierra</strong>, agrupación wixárika integrada por mujeres de Nayarit y estados vecinos; y danza tradicional a cargo del <strong>Grupo de Danza Nayar</strong> y el <strong>Ballet Nuevo Nayarit</strong>. Alrededor: cocina y artesanía del estado.",
      "## Cómo llegar",
      "Por la estación <strong>Constituyentes</strong> de la Línea 7 del Metro, o por la estación <strong>Los Pinos / Constituyentes</strong> del Cablebús.",
    ],
    expertise:
      "El horario es la trampa de este festival: cierra a las 17:00, no de noche, y la programación fuerte —las agrupaciones musicales— se concentra en las horas centrales, justo cuando el complejo está más lleno. Llegar a las diez y salir a comer a la una es la manera de ver el recinto y el festival sin hacer cola por ninguno de los dos. Vale además recordar qué es este lugar: Los Pinos fue residencia oficial hasta 2018 y hoy funciona como centro cultural público, así que la visita al conjunto arquitectónico es tan parte del plan como el festival que lo ocupa este fin de semana.",
  },

  {
    slug: "desfile-alebrijes-monumentales-2026",
    createdAt: "2026-09-08T22:51:25+04:00",
    updatedAt: "2026-09-12T17:35:10+04:00",
    site: "cmx",
    image: "/covers/desfile-alebrijes-monumentales-2026.jpg",
    imageAlt: "Una criatura imaginaria de papel recortado, con el lomo de placas a rayas magenta y ocre, cuernos en espiral, cola larga y cuatro patas, sobre fondo crema",
    imageKind: "generated",
    imageWidth: 1536,
    imageHeight: 864,
    title: "Desfile de Alebrijes Monumentales 2026",
    summary:
      "Sábado 17 de octubre a mediodía: los alebrijes salen del Zócalo rumbo al Ángel de la Independencia, y se quedan sobre Paseo de la Reforma hasta el 8 de noviembre. Es la 18ª edición y entrar no cuesta nada.",
    start: "2026-10-17",
    startTime: "12:00",
    utcOffset: "-06:00",
    city: "Ciudad de México",
    venue: "Zócalo — Paseo de la Reforma",
    category: "Día de Muertos",
    organizer: "Museo de Arte Popular",
    tickets: { priceFrom: 0, currency: "MXN" },
    geo: {
      name: "Zócalo",
      lat: 19.432608,
      lng: -99.133209,
    },
    source: {
      name: "Museo de Arte Popular",
      url: "https://www.map.cdmx.gob.mx/convocatorias/concursos/86",
      verifiedOn: "2026-09-08",
    },
    body: [
      "El <strong>sábado 17 de octubre de 2026</strong>, a las <strong>12:00</strong>, decenas de alebrijes de varios metros de alto salen del Zócalo empujados por quienes los construyeron. Es la <strong>18ª edición</strong> del desfile que organiza el Museo de Arte Popular, y el primer acto grande de la temporada",
      "## La ruta",
      "Del <strong>Zócalo</strong> por 5 de Mayo y Avenida Juárez hasta <strong>Paseo de la Reforma</strong>, y por Reforma hasta el <strong>Ángel de la Independencia</strong>",
      "## Lo que pasa después del desfile",
      "Los alebrijes <strong>se quedan sobre Reforma hasta el 8 de noviembre</strong>. Ésa es la diferencia con cualquier otro desfile de la ciudad: no es un acto de una tarde sino una exposición al aire libre de tres semanas, y verla entre semana cuesta lo mismo que verla el sábado — nada",
      "## Qué es un alebrije",
      "Una criatura imposible armada con partes de animales que no coinciden. La forma nace en el siglo XX con Pedro Linares, en cartonería, y el concurso del museo la volvió monumental",
      "## Cuánto cuesta",
      "<strong>Nada.</strong> El desfile y la exposición sobre Reforma son de acceso libre",
    ],
    faq: [
      {
        q: "¿Cuándo es el Desfile de Alebrijes Monumentales 2026?",
        a: "El <strong>sábado 17 de octubre de 2026</strong> a las <strong>12:00</strong>, desde el Zócalo",
      },
      {
        q: "¿Cuál es la ruta?",
        a: "Del Zócalo por 5 de Mayo y Avenida Juárez a Paseo de la Reforma, y por Reforma hasta el <strong>Ángel de la Independencia</strong>",
      },
      {
        q: "¿Hasta cuándo se pueden ver los alebrijes?",
        a: "Se quedan sobre Paseo de la Reforma <strong>hasta el 8 de noviembre</strong>",
      },
      {
        q: "¿Cuesta algo?",
        a: "No. Tanto el desfile como la exposición sobre Reforma son <strong>de acceso libre</strong>",
      },
    ],
    expertise:
      "Quien sólo tiene un rato conviene que lo use en Reforma y no en el Zócalo. El arranque a mediodía concentra a toda la gente en la plaza y los alebrijes salen de uno en uno; sobre Reforma pasan ya separados y con espacio para verlos completos. Y si el sábado no se puede, la temporada no se pierde: las tres semanas siguientes son la parte larga del evento, con los alebrijes quietos, de cerca y sin multitud",
  },

  {
    slug: "mega-procesion-de-las-catrinas-2026",
    createdAt: "2026-09-08T22:51:25+04:00",
    updatedAt: "2026-09-12T17:35:10+04:00",
    site: "cmx",
    image: "/covers/mega-procesion-de-las-catrinas-2026.jpg",
    imageAlt: "Tres sombreros de ala ancha de papel rosa en diagonal, cada uno con flores rojas sobre el ala",
    imageKind: "generated",
    imageWidth: 1536,
    imageHeight: 864,
    title: "Mega Procesión de las Catrinas 2026",
    summary:
      "Domingo 25 de octubre: miles de catrinas caminan del Ángel de la Independencia al Zócalo. Es la 13ª edición, no cuesta nada y quien va maquillado es parte de la procesión.",
    start: "2026-10-25",
    utcOffset: "-06:00",
    city: "Ciudad de México",
    venue: "Ángel de la Independencia — Zócalo",
    category: "Día de Muertos",
    organizer: "Jessy Esquivias",
    tickets: { priceFrom: 0, currency: "MXN" },
    geo: {
      name: "Ángel de la Independencia",
      lat: 19.427021,
      lng: -99.167654,
    },
    source: {
      name: "Mega Procesión de las Catrinas",
      url: "https://megaprocesiondelascatrinas.com.mx/",
      verifiedOn: "2026-09-08",
    },
    body: [
      "La diferencia con el desfile del 31 es quién camina. Aquí no hay carros alegóricos ni un elenco contratado: caminan los asistentes, maquillados de catrina, y por eso la <strong>13ª edición</strong> es de las pocas cosas de la temporada en las que uno no es público",
      "## La fecha y la ruta",
      "<strong>Domingo 25 de octubre de 2026</strong>, del <strong>Ángel de la Independencia</strong> por Paseo de la Reforma y Avenida Juárez hasta el <strong>Zócalo</strong>. En la plaza hay escenario de <strong>14:00 a 20:00</strong>",
      "## Cuánto cuesta",
      "<strong>Nada.</strong> No hay registro ni boleto",
      "## De dónde viene la catrina",
      "De un grabado. José Guadalupe Posada dibujó una calavera con sombrero de ala ancha para burlarse de quien renegaba de su origen; Diego Rivera le puso el nombre y el vestido largo con los que hoy se la reconoce",
    ],
    faq: [
      {
        q: "¿Cuándo es la Mega Procesión de las Catrinas 2026?",
        a: "El <strong>domingo 25 de octubre de 2026</strong>, del Ángel de la Independencia al Zócalo",
      },
      {
        q: "¿Hay que pagar o registrarse?",
        a: "No. Es <strong>de acceso libre</strong> y sin registro",
      },
      {
        q: "¿En qué se distingue del Gran Desfile?",
        a: "En quién camina: el desfile del 31 tiene carros alegóricos y elenco, y aquí caminan los asistentes maquillados",
      },
      {
        q: "¿Qué pasa al llegar al Zócalo?",
        a: "Hay <strong>escenario de 14:00 a 20:00</strong>",
      },
    ],
    expertise:
      "El maquillaje es la logística real del día. Los puestos que lo hacen se instalan alrededor del Ángel y la fila crece conforme se acerca la hora de salida, así que quien piensa maquillarse ahí necesita llegar con bastante anticipación. La segunda cosa que conviene saber es que la ruta es larga y de subida y bajada suave sobre Reforma: es una caminata de verdad, no un paseo de veinte minutos, y el calzado importa más que el vestido",
  },

  {
    slug: "alumbrada-mixquic-2026",
    createdAt: "2026-09-08T22:51:25+04:00",
    updatedAt: "2026-09-08T22:51:25+04:00",
    site: "cmx",
    image: "/covers/alumbrada-mixquic-2026.jpg",
    imageAlt: "Una fila de velas encendidas recortadas en papel sobre fondo magenta, con flores doradas esparcidas abajo",
    imageKind: "generated",
    imageWidth: 1536,
    imageHeight: 864,
    title: "La Alumbrada de Mixquic 2026",
    summary:
      "El 1 y 2 de noviembre, en San Andrés Mixquic, el panteón se llena de velas y cempasúchil. Es lo más cerca que se puede estar de un Día de Muertos de pueblo sin salir de la Ciudad de México.",
    start: "2026-11-01",
    end: "2026-11-02",
    utcOffset: "-06:00",
    city: "Ciudad de México",
    venue: "San Andrés Mixquic, Tláhuac",
    category: "Día de Muertos",
    organizer: "Alcaldía Tláhuac",
    geo: {
      name: "San Andrés Mixquic",
      lat: 19.226389,
      lng: -98.9625,
    },
    source: {
      name: "Alcaldía Tláhuac",
      verifiedOn: "2026-09-08",
    },
    body: [
      "Mixquic es un pueblo dentro de la ciudad, en el extremo sureste de <strong>Tláhuac</strong>, y su Día de Muertos no se parece al de Reforma. La noche del <strong>2 de noviembre</strong> las familias van al panteón del antiguo convento agustino y lo llenan de veladoras y cempasúchil. A eso se le llama <strong>la Alumbrada</strong>",
      "## Las fechas",
      "<strong>1 y 2 de noviembre de 2026</strong>. El 1 es el día de los niños difuntos y el 2 el de los adultos, que es la noche de la Alumbrada",
      "## Qué se ve",
      "El panteón entero iluminado con velas, las tumbas cubiertas de flor de cempasúchil, y a las familias sentadas junto a ellas. No es un espectáculo montado para quien mira: es una visita, y quien llega es un invitado",
      "## Lo que todavía no está publicado",
      "El programa detallado de 2026 — horarios, cierres de calle, transporte especial — <strong>no se ha anunciado</strong>. Cuando la alcaldía lo publique aparece aquí",
    ],
    faq: [
      {
        q: "¿Cuándo es la Alumbrada de Mixquic 2026?",
        a: "El <strong>1 y 2 de noviembre de 2026</strong>. La noche de la Alumbrada es la del 2",
      },
      {
        q: "¿Dónde está Mixquic?",
        a: "En <strong>San Andrés Mixquic</strong>, al sureste de la alcaldía Tláhuac, dentro de la Ciudad de México",
      },
      {
        q: "¿Ya hay programa oficial de 2026?",
        a: "Todavía no. Cuando la alcaldía publique horarios y logística lo anotamos aquí",
      },
      {
        q: "¿En qué se distingue del desfile de Reforma?",
        a: "En que no es un acto público montado sino la celebración de un pueblo en su propio panteón",
      },
    ],
    expertise:
      "Dos cosas hacen difícil esta noche y las dos son de traslado. Mixquic está a más de treinta kilómetros del centro y la carretera de acceso se satura desde la tarde del 2; quien va en auto pasa más tiempo estacionándose que en el panteón. Y la segunda: es una celebración familiar en un cementerio, no una atracción — el modo de estar ahí es caminar despacio, no fotografiar tumbas de cerca",
  },

  {
    slug: "corona-capital-2026",
    createdAt: "2026-09-12T22:20:00+04:00",
    updatedAt: "2026-09-12T22:20:00+04:00",
    site: "cmx",
    image: "/covers/corona-capital-2026.jpg",
    imageAlt:
      "Un escenario de papel recortado en rojo con cortina festoneada y una banda roja horizontal al centro, con una fila de siluetas oscuras de público al pie, sobre fondo crema cálido",
    imageKind: "generated",
    imageWidth: 1536,
    imageHeight: 864,
    title: "Corona Capital 2026",
    summary:
      "El festival de música internacional más grande de la Ciudad de México va del 20 al 22 de noviembre en el Autódromo Hermanos Rodríguez, con Gorillaz, The Strokes y Twenty One Pilots encabezando.",
    start: "2026-11-20",
    end: "2026-11-22",
    utcOffset: "-06:00",
    venue: "Autódromo Hermanos Rodríguez",
    city: "Ciudad de México",
    country: "México",
    geo: {
      name: "Autódromo Hermanos Rodríguez",
      lat: 19.406245,
      lng: -99.094593,
    },
    organizer: "OCESA",
    category: "Música",
    tickets: { priceFrom: 2600, currency: "MXN" },
    ticket: {
      url: "https://www.coronacapital.com.mx/boletos",
      label: "Boletos y fases",
    },
    source: {
      name: "Corona Capital CDMX",
      url: "https://www.coronacapital.com.mx/boletos",
      verifiedOn: "2026-09-12",
    },
    speakersHeading: "Cabezas de cartel",
    speakers: [
      { name: "Gorillaz" },
      { name: "The Strokes" },
      { name: "Twenty One Pilots" },
      { name: "Mumford & Sons" },
      { name: "The Offspring" },
      { name: "The xx" },
      { name: "Daniel Caesar" },
      { name: "Lola Young" },
      { name: "Pierce the Veil" },
      { name: "James Blake" },
      { name: "Lil Yachty" },
      { name: "Underworld" },
      { name: "BUNT.", note: "in the round" },
      { name: "Mother Mother" },
      { name: "The Kooks" },
    ],
    body: [
      "El cartel ya está cerrado y la mitad de los boletos también: cuando revisamos la página el 12 de septiembre, la Fase 1 estaba agotada en los cuatro tipos de acceso general y el sábado ya iba en <strong>Fase 3</strong>. El Corona Capital 2026 se realiza el <strong>20, 21 y 22 de noviembre</strong> en el <strong>Autódromo Hermanos Rodríguez</strong>.",
      "## Quiénes encabezan",
      "<strong>Gorillaz</strong>, <strong>The Strokes</strong>, <strong>Twenty One Pilots</strong>, <strong>Mumford &amp; Sons</strong>, <strong>The Offspring</strong>, <strong>The xx</strong>, <strong>Daniel Caesar</strong>, <strong>Lola Young</strong>, <strong>Pierce the Veil</strong>, <strong>James Blake</strong>, <strong>Lil Yachty</strong>, <strong>Underworld</strong>, <strong>BUNT.</strong> en formato <em>in the round</em>, <strong>Mother Mother</strong> y <strong>The Kooks</strong>. Debajo de los encabezados el cartel sigue en orden alfabético con decenas de nombres más.",
      "## Los precios, fase por fase",
      "El <strong>abono</strong> de acceso general arrancó en <strong>$4,090</strong> en Fase 1 —agotada— y va en <strong>$4,760</strong> en Fase 2. Los boletos por día de acceso general empezaron en <strong>$2,200</strong>: el <strong>viernes</strong> y el <strong>domingo</strong> están en <strong>$2,600</strong> de Fase 2, y el <strong>sábado</strong> ya pasó dos fases y está en <strong>$3,500</strong>. Todos los precios son <strong>más cargo por servicios</strong>.",
      "## Los otros accesos",
      "Además del general, el festival vende <strong>Comfort Pass presentado por Banamex</strong>, <strong>Banamex Plus</strong>, <strong>Club Pass</strong> y <strong>Cavannas</strong>, y tiene una vía de compra separada para quien paga desde Estados Unidos.",
      "## Qué es el Corona Capital",
      "Se realizó por primera vez en <strong>2010</strong> y el propio festival se describe como el principal referente de música internacional en México, no solo para el público sino para la comunidad artística nacional y global. Lo organiza <strong>OCESA</strong>.",
      "## Cómo llegar",
      "El Autódromo Hermanos Rodríguez está en la <strong>Ciudad Deportiva</strong>, en Iztacalco. Es la misma sede del Gran Premio de México y la que mejor resuelve el transporte público de un festival de este tamaño en la ciudad.",
    ],
    faq: [
      {
        q: "¿Cuándo es el Corona Capital 2026?",
        a: "El viernes 20, sábado 21 y domingo 22 de noviembre de 2026, en el Autódromo Hermanos Rodríguez de la Ciudad de México.",
      },
      {
        q: "¿Cuánto cuestan los boletos?",
        a: "El abono de acceso general va en $4,760 de Fase 2; la Fase 1, de $4,090, está agotada. Los días sueltos de acceso general están en $2,600 el viernes y el domingo, y en $3,500 el sábado, que ya va en Fase 3. Todos los precios son más cargo por servicios.",
      },
      {
        q: "¿Quiénes tocan?",
        a: "Encabezan Gorillaz, The Strokes, Twenty One Pilots, Mumford & Sons, The Offspring, The xx, Daniel Caesar, Lola Young, Pierce the Veil, James Blake, Lil Yachty, Underworld, BUNT. en formato in the round, Mother Mother y The Kooks.",
      },
      {
        q: "¿Qué tipos de boleto hay además del general?",
        a: "Comfort Pass presentado por Banamex, Banamex Plus, Club Pass y Cavannas, además de una vía de compra para quien paga desde Estados Unidos.",
      },
      {
        q: "¿Dónde es?",
        a: "En el Autódromo Hermanos Rodríguez, en la Ciudad Deportiva, alcaldía Iztacalco, Ciudad de México.",
      },
    ],
    expertise:
      "La cuenta que conviene hacer antes de comprar: con el sábado en $3,500 y el viernes y el domingo en $2,600, tres días sueltos salen en $8,700, y el abono completo cuesta $4,760. Es decir, dos días sueltos cualesquiera ya se acercan al abono y el tercero sale prácticamente regalado —de modo que quien duda entre dos días y los tres está eligiendo, en realidad, entre pagar más por menos. La otra lectura del tablero de fases es el calendario: el sábado subió dos fases mientras los otros dos siguen en la segunda, y esa diferencia, más que el cartel, dice qué día se va a llenar primero.",
  },

  {
    slug: "festival-del-terror-six-flags-2026",
    createdAt: "2026-09-12T22:20:00+04:00",
    updatedAt: "2026-09-12T22:20:00+04:00",
    site: "cmx",
    image: "/covers/festival-del-terror-six-flags-2026.jpg",
    imageAlt:
      "La silueta plana en ciruela de una estructura de armadura curvada que cruza la parte alta del cuadro, con tres calaveras pequeñas de papel debajo, sobre fondo crema cálido",
    imageKind: "generated",
    imageWidth: 1536,
    imageHeight: 864,
    title: "Festival del Terror 2026 en Six Flags México",
    titleSeo: "Festival del Terror 2026, Six Flags Ciudad de México",
    summary:
      "El Festival del Terror de Six Flags México, en Tlalpan, va del 3 de septiembre al 16 de noviembre: ocho atracciones de terror, Kids Boo Fest y reglas de acceso que conviene leer antes de disfrazarse.",
    start: "2026-09-03",
    end: "2026-11-16",
    utcOffset: "-06:00",
    venue: "Six Flags México",
    city: "Ciudad de México",
    country: "México",
    geo: {
      name: "Six Flags México",
      lat: 19.2953,
      lng: -99.209786,
    },
    organizer: "Six Flags México",
    category: "Festival",
    tickets: { priceFrom: 550, currency: "MXN" },
    ticket: {
      url: "https://www.sixflags.com/mexico/events/festival-del-terror",
      label: "Fechas y boletos",
    },
    source: {
      name: "Six Flags México",
      url: "https://www.sixflags.com/mexico/events/festival-del-terror",
      verifiedOn: "2026-09-12",
    },
    body: [
      "Setenta y cinco días de temporada, que es lo que el parque llama su edición <strong>más grande de la historia</strong>: el Festival del Terror 2026 va del <strong>3 de septiembre al 16 de noviembre</strong> en Six Flags México, y su rasgo más mexicano es que se extiende más allá de Halloween, hasta el otro lado del Día de Muertos.",
      "## Lo que hay adentro",
      "<strong>Ocho Atracciones de Terror</strong>, Zonas de Espanto más extensas, espectáculos en vivo y una oferta de alimentos y bebidas ampliada. Para los más chicos está el <strong>Kids Boo Fest</strong>, dentro de la zona de juegos infantiles que el parque describe como la más grande de América Latina. Las criaturas empiezan a aparecer desde las primeras horas del día, no solo de noche: el parque opera de <strong>10:00 a 00:00</strong>.",
      "## El costo adicional que sorprende a muchos",
      "Aquí está la letra que conviene leer dos veces. El <strong>Pase Anual 2026 y 2027</strong>, las <strong>Membresías</strong> y la <strong>Admisión General</strong> incluyen el acceso al Festival del Terror, pero <strong>las Atracciones de Terror tienen costo adicional, sin excepciones</strong>. El <strong>Pase de Atracciones de Terror</strong> cuesta <strong>desde $550</strong> y requiere tener ya una admisión al parque; el <strong>Boleto de un Día + Atracciones de Terror</strong>, que junta las dos cosas, cuesta <strong>desde $1,549</strong>. Ambos son válidos únicamente para el día seleccionado en la compra, el acceso es por fila regular, y la mejora a <strong>Monster Pass</strong> se contrata aparte, directamente en el parque.",
      "## Las reglas de entrada",
      "Las personas <strong>mayores de 12 años no pueden entrar al parque</strong> con máscaras, disfraces, maquillaje de caracterización, sudaderas con cremallera frontal ni cualquier prenda o artículo que cubra el rostro. Y las <strong>Atracciones de Terror y Zonas de Espanto están recomendadas para mayores de 13 años</strong>, de modo que el Kids Boo Fest no es un detalle menor: es la parte del evento pensada para quien no cumple ese criterio.",
      "## Dónde es",
      "Six Flags México está en el <strong>kilómetro 1.5 del Boulevard Picacho-Ajusco</strong>, colonia Jardines del Ajusco, <strong>alcaldía Tlalpan</strong>, al sur de la Ciudad de México.",
    ],
    faq: [
      {
        q: "¿Cuándo es el Festival del Terror 2026?",
        a: "Del 3 de septiembre al 16 de noviembre de 2026 en Six Flags México, con el parque operando de 10:00 a 00:00.",
      },
      {
        q: "¿Las atracciones de terror están incluidas en el boleto?",
        a: "No. El Pase Anual 2026 y 2027, las membresías y la admisión general incluyen el acceso al Festival del Terror, pero las Atracciones de Terror tienen costo adicional, sin excepciones.",
      },
      {
        q: "¿Cuánto cuesta?",
        a: "El Pase de Atracciones de Terror cuesta desde $550 y requiere tener ya admisión al parque. El Boleto de un Día + Atracciones de Terror cuesta desde $1,549 e incluye ambas cosas. El precio mostrado es el más bajo disponible y cambia según la fecha elegida.",
      },
      {
        q: "¿Puedo entrar disfrazado?",
        a: "No si tienes más de 12 años. El parque no permite el ingreso con máscaras, disfraces, maquillaje de caracterización, sudaderas con cremallera frontal ni nada que cubra el rostro.",
      },
      {
        q: "¿Hay algo para niños pequeños?",
        a: "Sí, el Kids Boo Fest, dentro de la zona de juegos infantiles del parque. Las Atracciones de Terror y las Zonas de Espanto están recomendadas para mayores de 13 años.",
      },
      {
        q: "¿Dónde está Six Flags México?",
        a: "En el kilómetro 1.5 del Boulevard Picacho-Ajusco, colonia Jardines del Ajusco, alcaldía Tlalpan, al sur de la Ciudad de México.",
      },
    ],
    expertise:
      "La diferencia entre los dos boletos es de casi mil pesos y no significa lo mismo para todos. Quien ya tiene Pase Anual paga $550 y entra a las ocho atracciones; quien no lo tiene paga desde $1,549 por el día completo, que es prácticamente el costo de un pase anual con descuento. Dicho de otro modo: si piensas ir dos veces en la temporada, el pase se paga solo. La segunda cuenta es de calendario — la temporada dura hasta el 16 de noviembre, así que las dos semanas posteriores al 2 de noviembre son las mismas ocho atracciones con la mitad de la fila, y son las que casi nadie considera porque ya pasó Halloween.",
  },
];
