import type { EventItem } from "../types.ts";

export const items: EventItem[] = [

  {
    slug: "fall-celebrations-spirit-of-mexico-dubai-2026",
    createdAt: "2026-10-09T12:40:00+04:00",
    updatedAt: "2026-10-09T12:40:00+04:00",
    site: "dst",
    image: "/covers/fall-celebrations-spirit-of-mexico-dubai-2026.jpg",
    imageAlt: "Illustration of a marigold sun, papel picado banners and a stepped pink arch for a Mexican cultural evening in Dubai",
    imageKind: "illustration",
    imageCredit: "DST",
    imageWidth: 3072,
    imageHeight: 864,
    title: "Fall Celebrations: The Spirit of Mexico",
    titleSeo: "The Spirit of Mexico in Dubai: date and tickets",
    summary:
      "An evening of Mexican culture, food and tradition at Al Wasl Plaza, Expo City Dubai, on 24 October 2026, from 4pm to 10pm; entry AED 30.",
    start: "2026-10-24",
    startTime: "16:00",
    endTime: "22:00",
    utcOffset: "+04:00",
    city: "Dubai",
    country: "United Arab Emirates",
    venue: "Al Wasl Plaza, Expo City Dubai",
    geo: { name: "Al Wasl Plaza, Expo City Dubai", lat: 24.9614, lng: 55.1512 },
    organizer: "Expo City Dubai",
    category: "Culture",
    tickets: { priceFrom: 30, currency: "AED" },
    source: {
      name: "Visit Dubai",
      url: "https://www.visitdubai.com/en/festivals-and-events/dubai-events-calendar/fall-celebration-the-spirit-of-mexico",
      verifiedOn: "2026-10-09",
    },
    ticket: {
      url: "https://www.visitdubai.com/en/festivals-and-events/dubai-events-calendar/fall-celebration-the-spirit-of-mexico",
      label: "Event details and tickets",
    },
    body: [
      "Al Wasl Plaza hosts an evening of Mexican culture and tradition on <strong>Saturday 24 October 2026</strong>. The Visit Dubai listing gives the hours as <strong>4pm to 10pm</strong> and admission as <strong>AED 30</strong>.",
      "## Date, hours and venue",
      "<strong>Saturday 24 October, 4pm–10pm</strong>, at <strong>Al Wasl Plaza, Expo City Dubai</strong>. This is an evening event rather than an all-day festival, so the published six-hour window is the useful planning detail.",
      "## Tickets and getting there",
      "The listing shows tickets at <strong>AED 30</strong>. Check the organiser's page for availability and any updated entry conditions before setting out. Expo City Dubai is served by the Dubai Metro's Expo 2020 station.",
    ],
    faq: [
      { q: "When is The Spirit of Mexico in Dubai?", a: "Saturday 24 October 2026, from 4pm to 10pm." },
      { q: "Where is the event?", a: "At Al Wasl Plaza in Expo City Dubai." },
      { q: "How much is admission?", a: "Visit Dubai lists tickets at AED 30." },
    ],
  },
  {
    slug: "bolshoi-theatre-orchestra-dubai-opera-2026",
    createdAt: "2026-10-09T12:40:00+04:00",
    updatedAt: "2026-10-09T12:40:00+04:00",
    site: "dst",
    image: "/covers/bolshoi-orchestra-dubai-opera-2026.jpg",
    imageAlt: "Illustration of a conductor and orchestral instruments beneath the arches of a Dubai opera house",
    imageKind: "illustration",
    imageCredit: "DST",
    imageWidth: 3072,
    imageHeight: 864,
    title: "Bolshoi Theatre Orchestra at Dubai Opera",
    titleSeo: "Bolshoi Theatre Orchestra in Dubai: 3 December",
    summary:
      "The Bolshoi Theatre Orchestra makes its Dubai Opera debut on 3 December 2026, conducted by Valery Gergiev; tickets start at AED 350.",
    start: "2026-12-03",
    startTime: "20:00",
    utcOffset: "+04:00",
    city: "Dubai",
    country: "United Arab Emirates",
    venue: "Dubai Opera, Downtown Dubai",
    geo: { name: "Dubai Opera", lat: 25.033, lng: 55.2654 },
    organizer: "Dubai Opera and Art Seasons",
    category: "Classical music",
    tickets: { priceFrom: 350, currency: "AED" },
    source: {
      name: "Dubai Opera",
      url: "https://www.dubaiopera.com/en/events/concerts/symphonic-orchestra-concert",
      verifiedOn: "2026-10-09",
    },
    ticket: {
      url: "https://www.dubaiopera.com/en/events/concerts/symphonic-orchestra-concert",
      label: "Tickets at Dubai Opera",
    },
    body: [
      "Dubai Opera has booked a first for its main auditorium: the <strong>Bolshoi Theatre Orchestra</strong> performs there on <strong>Thursday 3 December 2026 at 8pm</strong>. The concert is presented with Art Seasons and conducted by <strong>Valery Gergiev</strong>.",
      "## Tickets and venue",
      "Dubai Opera lists tickets from <strong>AED 350</strong>. The concert is in the <strong>Main Auditorium</strong> at Dubai Opera, Sheikh Mohammed bin Rashid Boulevard, Downtown Dubai.",
      "## The orchestra",
      "The ensemble was formed in <strong>1776</strong> as part of the company that became the Bolshoi Theatre. Dubai Opera describes it as the orchestra's first performance at the venue; the event page lists Gergiev as conductor.",
    ],
    faq: [
      { q: "When is the Bolshoi Theatre Orchestra concert in Dubai?", a: "Thursday 3 December 2026 at 8pm." },
      { q: "Where is the concert?", a: "In the Main Auditorium at Dubai Opera, Downtown Dubai." },
      { q: "How much are tickets?", a: "Dubai Opera lists tickets from AED 350." },
      { q: "Who conducts the orchestra?", a: "Valery Gergiev." },
    ],
  },
  {
    slug: "moc27-motor-outdoor-camping-festival-dubai",
    createdAt: "2026-10-07T20:50:00+04:00",
    updatedAt: "2026-10-09T01:46:15+04:00",
    site: "dst",
    image: "/covers/moc27-motor-outdoor-camping-festival-dubai.jpg",
    imageAlt: "A small four-wheel drive on the crest of a pale dune under a white sun",
    imageKind: "generated",
    imageWidth: 1536,
    imageHeight: 864,
    title: "MOC27: Motor, Outdoor & Camping Festival",
    titleSeo: "MOC27 Motor, Outdoor & Camping Festival in Dubai",
    summary:
      "A four-day outdoor festival on The Sevens Stadium grounds in Dubai, 14–17 January 2027: 4x4 test drives, dirt bikes, camping, 200+ brands and 50 clubs across 350,000 square metres.",
    start: "2027-01-14",
    end: "2027-01-17",
    venue: "The Sevens Stadium grounds, Dubai–Al Ain Road",
    geo: { name: "The Sevens Stadium", lat: 24.994479, lng: 55.468241 },
    city: "Dubai",
    country: "United Arab Emirates",
    organizer: "JBCM Event Architects",
    category: "Festival",
    source: {
      name: "Khaleej Times",
      url: "https://www.khaleejtimes.com/business/dubai-adds-outdoor-lifestyle-festival-to-expanding-winter-events-calendar",
      verifiedOn: "2026-10-07",
    },
    body: [
      "Dubai has a motor show and it has desert parties. The people behind MOC27 say they are building neither: a four-day festival for families, organised around the clubs that actually spend their weekends off-road, under canvas and on two wheels.",
      "## MOC27 dates and venue",
      "The <strong>Motor, Outdoor & Camping Festival</strong> runs <strong>14–17 January 2027</strong> on the grounds of <strong>The Sevens Stadium</strong>, off the Dubai–Al Ain Road. The site covers <strong>350,000 square metres</strong>.",
      "## What is on",
      "<strong>4x4 test drives</strong> and <strong>dirt-bike sessions</strong>, camping demonstrations, and areas for cycling, hiking, overlanding, motorcycling and marine activities. Around them: family entertainment and activities for children, food zones, wellness and nature programmes, and entertainment in the evenings.",
      "## Who is taking part",
      "More than <strong>200 brands</strong> and <strong>50 clubs and community groups</strong>.",
      "## Who is behind it",
      "The concept is by <strong>JBCM Event Architects</strong>, with <strong>Oryx Signature</strong> handling marketing and production, and the festival has the support of Dubai's <strong>Department of Economy and Tourism</strong>. JBCM's chief executive, Justyn Cánovas, describes it as a festival for the whole family built around the clubs and communities that live the outdoors every day.",
      "## What is not announced yet",
      "Ticket prices and opening hours.",
    ],
    faq: [
      {
        q: "When is MOC27 in Dubai?",
        a: "<strong>14–17 January 2027</strong>.",
      },
      {
        q: "Where is the Motor, Outdoor & Camping Festival?",
        a: "On the grounds of <strong>The Sevens Stadium</strong>, off the Dubai–Al Ain Road.",
      },
      {
        q: "Can you test-drive cars at MOC27?",
        a: "Yes — <strong>4x4 test drives</strong> and <strong>dirt-bike sessions</strong> are part of the programme.",
      },
    ],
    expertise:
      "The Sevens is the ground that hosts the Emirates Dubai 7s every December, so the site is built for big crowds arriving by car — and by car is how nearly everyone will come, because it sits well out of the city on the Al Ain road. Mid-January is the coolest stretch of the Dubai year, which is what makes a camping festival plausible at all: the days are warm rather than hot, and the desert nights are cold enough that anyone staying for the evening programme will want a layer. The festival runs Thursday to Sunday, so the two days of the UAE weekend, 16 and 17 January, are the ones a family will reach for first — and the ones to arrive early on.",
  },
  {
    slug: "expand-north-star-2026",
    createdAt: "2026-08-25T18:18:34+04:00",
    updatedAt: "2026-09-06T08:48:11+04:00",
    site: "dst",
    image: "/covers/expand-north-star-2026.jpg",
    imageAlt: "A scatter of small cut-paper squares on a slate ground converging on one larger cream square, thin brass lines between them",
    imageKind: "generated",
    imageWidth: 1536,
    imageHeight: 864,
    title: "Expand North Star 2026",
    titleSeo: "Expand North Star 2026 in Dubai",
    summary:
      "The tenth edition of the startup and investor show runs 8–10 December at Dubai Exhibition Centre. Last year it drew 2,050 startups from 96 countries and 1,300 investors.",
    start: "2026-12-08",
    end: "2026-12-10",
    venue: "Dubai Exhibition Centre, Expo City",
    city: "Dubai",
    organizer: "GITEX Global",
    category: "Business",
    source: {
      name: "Expand North Star",
      url: "https://expandnorthstar.com/",
      verifiedOn: "2026-09-03",
    },
    body: [
      "GITEX fills the Trade Centre in October with companies that already have customers. Six weeks later the same organisers fill Expo City with the ones that do not yet.",
      "## Expand North Star 2026 dates",
      "<strong>Expand North Star</strong> runs <strong>8–10 December 2026</strong> at the <strong>Dubai Exhibition Centre</strong> in Expo City. It is the <strong>tenth edition</strong>, and it is organised by GITEX Global.",
      "## The size of it, as measured last year",
      "The 2025 edition drew <strong>2,050 exhibiting startups from 96 countries</strong>, <strong>more than 1,300 investors</strong>, <strong>6,500 founders</strong> and <strong>400 speakers</strong>, with <strong>5,340 pre-arranged meetings</strong> booked on site. The organisers describe the investor cohort as managing more than <strong>$1 trillion</strong> in assets between them.",
      "## What is inside it",
      "Five components carry the programme. <strong>Founders Academy</strong> is a three-day learning track. <strong>NS Play</strong> covers AR, VR and lifestyle technology. <strong>DigiHealth-Biotech</strong> takes healthcare. The <strong>Investor Programme</strong> is billed by the organisers as the largest VC gathering in the global south, and <strong>Supernova 0X</strong> is the pitch competition, structured by venture stage rather than by sector.",
      "Around them sit a Founder's Pass giving access to single-day startup pods, and thematic tracks on restructuring, alternative capital, commercial deep tech and emerging-market growth corridors.",
    ],
    expertise:
      "The number to plan around is 5,340 pre-arranged meetings, not the 2,050 exhibitors. This is a matching event rather than a browsing one, and the value is almost entirely in the meeting scheduler, which opens weeks before the doors do. A stand booked without the meetings booked is a stand in a hall of two thousand other stands. Note also the venue: Expo City is not the World Trade Centre, and the December date puts it well clear of GITEX week — anyone budgeting one Dubai trip for both is budgeting two.",
  },

  {
    slug: "future-world-forum-dubai-2026",
    createdAt: "2026-08-27T08:25:50+04:00",
    updatedAt: "2026-09-03T07:30:21+04:00",
    site: "dst",
    title: "Future World Forum Dubai",
    summary:
      "A one-day smart-city conference \u2014 fintech and crypto, AI, PropTech, cyber resilience, mobility \u2014 on November 16, 2026 in Dubai. Tickets from $49; the venue is still unannounced.",
    start: "2026-11-16",
    startTime: "10:00",
    endTime: "17:30",
    city: "Dubai",
    organizer: "Futur World Expo",
    category: "Conference",
    image: "/events/future-world-forum-dubai.jpg",
    imageAlt: "A conference venue at dusk under a Dubai skyline, its facade lit with the words Future World Forum Dubai",
    imageKind: "generated",
    imageWidth: 1380,
    imageHeight: 752,
    source: {
      name: "Eventbrite",
      url: "https://www.eventbrite.com/e/future-world-forum-dubai-tickets-1324931388449",
      verifiedOn: "2026-08-27",
    },
    ticket: {
      url: "https://www.eventbrite.com/e/future-world-forum-dubai-tickets-1324931388449",
      label: "Tickets",
    },
    tickets: {
      priceFrom: 49,
      priceTo: 3096,
      currency: "USD",
      salesEnd: "2026-09-25",
      refundPolicy: "Up to 7 days before the event",
    },
    body: [
      "The Future World Forum is a single-day conference and expo held in Dubai on <strong>Monday, November 16, 2026</strong>, running from 10:00 to 17:30. It bills itself as a gathering for urban innovation \u2014 the technologies, the money behind them, and the policy that decides which of the two moves first \u2014 and it puts five sectors that usually meet at separate events under one roof for a day.",
      "That framing is the point of it. A crypto conference draws people who already agree with each other about crypto; a smart-city forum draws the municipal side, the infrastructure side and the capital side into the same room, which is where most of the friction in these projects actually sits. Dubai is a reasonable place to try it: the city runs its own smart-city programme, the regulator has taken a defined position on digital assets rather than deferring, and the property sector is well ahead of most markets in putting transactions on a screen instead of a counter.",
      "The organiser sells this as a working day rather than a lecture series \u2014 the stated aims are partnerships, exhibitor visibility and access to policymakers, in that order. Exhibitor packages sit at the upper end of the ticket range.",
      "Tickets run from <strong>$49 to $3,096</strong>, refundable up to seven days before the date, and the listing closes sales on <strong>September 25, 2026</strong> \u2014 nearly two months ahead of the event, which is an unusually early cut-off and worth putting in the calendar if you are undecided.",
    ],
    programme: [
      {
        heading: "Fintech and crypto",
        text: "Blockchain in production rather than in principle, DeFi, and where digital-asset investment sits inside the UAE regulatory framework \u2014 the part of the programme with the clearest local hook, since the rules here are written rather than pending.",
      },
      {
        heading: "AI and data-driven operations",
        text: "Forecasting demand, tightening operations, cybersecurity, and the use of analytics in planning decisions that used to be made on committee judgement.",
      },
      {
        heading: "PropTech and smart real estate",
        text: "Digital twins for planning, building systems that report on themselves, and financing structures that follow from having reliable data about an asset \u2014 the track closest to how property is actually bought and sold in this market.",
      },
      {
        heading: "Cyber-resilient cities",
        text: "Protecting interconnected municipal systems and the data they generate. A single utility, transport network or permit system now has the blast radius of all three.",
      },
      {
        heading: "Smart infrastructure and mobility",
        text: "Intelligent transport, mobility-as-a-service, clean utilities and the circular economy \u2014 the physical layer under everything above it.",
      },
    ],
    audience: [
      "Government officials",
      "CIOs and CTOs",
      "Investors and VCs",
      "Developers and PropTech",
      "Data scientists and AI researchers",
      "Urban planners",
      "Finance, banking and crypto",
      "Tech companies",
    ],
    expertise:
      "Three things are worth knowing before booking. The venue is not announced \u2014 the listing gives the location as Dubai and nothing further, which for a paid conference eleven weeks out is unusual, and it makes the practical questions (which end of the city, how long from your hotel, is parking a problem) unanswerable for now. The organiser's own description is headed 2025 while the listing sells a Monday in November 2026, so one of the two has not been updated. And the public track record is thin: 22 events and 314 attendees in total across a year of hosting, an average in the low tens, against a ticket ceiling of three thousand dollars. None of that makes the event fictional, and the sector mix genuinely is a gap in Dubai's autumn calendar \u2014 nothing else here puts municipal, crypto and PropTech people in one room. It does mean the top tier buys access to something whose scale nobody has demonstrated yet, which is a different proposition from GITEX or Blockchain Life, where the numbers are at least published and checkable. At $49 the downside is a day; at $3,096 it is worth asking the organiser for the venue and the expected head count in writing before the September cut-off.",
  },
  {
    slug: "blockchain-life-dubai-2026",
    createdAt: "2026-08-26T04:47:11+04:00",
    updatedAt: "2026-09-07T16:06:17+04:00",
    site: "dst",
    image: "/covers/blockchain-life-dubai-2026.jpg",
    imageAlt: "An arena bowl seen from above as concentric paper rings, a chain of linked hexagons across the middle",
    imageKind: "generated",
    imageWidth: 1536,
    imageHeight: 864,
    title: "Blockchain Life 2026",
    titleSeo: "Blockchain Life 2026 in Dubai",
    summary:
      "The 17th edition of the web3, mining and crypto forum returns to Dubai on December 1–2, 2026, at Festival Arena, with an AI Future stage added to the programme.",
    start: "2026-12-01",
    end: "2026-12-02",
    venue: "Festival Arena",
    city: "Dubai",
    organizer: "Blockchain Life",
    category: "Conference",
    source: {
      name: "Blockchain Life",
      url: "https://blockchain-life.com/autumn2026/",
      verifiedOn: "2026-09-07",
    },
    // Six of the 200 the organiser advertises, taken from the edition's own
    // page. A head count is not a reason to fly anywhere; a name is. Errol
    // Musk is listed there too and is left out here: the page identifies him
    // by whose father he is, which is not a qualification.
    speakers: [
      { name: "Paolo Ardoino", role: "CEO", org: "Tether" },
      { name: "Sergey Nazarov", role: "Co-Founder", org: "Chainlink" },
      { name: "Ben Zhou", role: "Co-Founder and CEO", org: "Bybit" },
      { name: "Bobby Ong", role: "Co-Founder", org: "CoinGecko" },
      { name: "Pascal Gauthier", role: "Chairman and CEO", org: "Ledger" },
      { name: "Yat Siu", role: "Co-Founder and Executive Chairman", org: "Animoca Brands" },
    ],
    body: [
      "Blockchain Life holds its 17th forum at Festival Arena, Dubai Festival City, on <strong>December 1 and 2, 2026</strong>, covering web3, mining, cryptocurrencies and — new this edition — a dedicated AI Future stage.",
      "The organisers expect 15,000+ attendees from 130+ countries, 200+ speakers and 200+ booths.",
    ],
    expertise:
      "This one runs six days before GITEX opens at Expo City, which makes the first half of December the densest stretch of the Dubai tech calendar this year — a consequence of GITEX vacating its October slot that nobody planned. Anyone flying in for both can do it on one trip; anyone competing for the same audience's attention now has a week rather than two months of separation. As always, the headline numbers are the organisers' projections.",
  },
  {
    slug: "gitex-global-dubai-2026",
    createdAt: "2026-08-26T04:47:11+04:00",
    updatedAt: "2026-09-02T07:22:25+04:00",
    site: "dst",
    image: "/covers/gitex-global-dubai-2026.jpg",
    imageAlt: "A domed exhibition hall in cut paper with an avenue of small pavilions leading to it",
    imageKind: "generated",
    imageWidth: 1536,
    imageHeight: 864,
    title: "GITEX GLOBAL 2026",
    titleSeo: "GITEX Global 2026 in Dubai",
    summary:
      "GITEX runs December 7–11, 2026 — its first edition at the Dubai Exhibition Centre in Expo City, after 45 years at Dubai World Trade Centre.",
    start: "2026-12-07",
    end: "2026-12-11",
    venue: "Dubai Exhibition Centre, Expo City",
    geo: { name: "Dubai Exhibition Centre", lat: 24.966140, lng: 55.149662 },
    city: "Dubai",
    organizer: "Dubai World Trade Centre",
    category: "Exhibition",
    source: {
      name: "GITEX GLOBAL",
      url: "https://www.gitex.com/",
      verifiedOn: "2026-08-26",
    },
    body: [
      "The 46th GITEX runs from <strong>December 7 to 11, 2026</strong>. The summit day on the 7th is at Dubai World Trade Centre; the exhibition itself runs December 8–11 at the Dubai Exhibition Centre in Expo City Dubai — 2.2 million square feet, about 1.5 times the old halls.",
      "The venue puts expected participation at more than 200,000 attendees from 180+ countries, 6,800 exhibiting companies and 400+ government entities.",
    ],
    expertise:
      "Worth checking the split before booking anything: the two days are in two different places, roughly 30 kilometres apart, and the December dates replace an October slot the region had planned around for four decades. Expo City has the space and the parking the old site never did; what it does not have is the ring of hotels and offices that grew up around Trade Centre, so the logistics that used to be a taxi ride are now a commute.",
  },
  {
    slug: "step-conference-dubai-2026",
    createdAt: "2026-08-25T21:44:32+04:00",
    updatedAt: "2026-09-02T07:22:25+04:00",
    site: "dst",
    image: "/covers/step-conference-dubai-2026.jpg",
    imageAlt: "A flight of wide paper steps rising across the frame with low office blocks behind",
    imageKind: "generated",
    imageWidth: 1536,
    imageHeight: 864,
    title: "Step Conference 2026",
    titleSeo: "Step Conference 2026 in Dubai",
    summary:
      "Dubai's largest technology festival held its 14th edition on February 11–12, 2026 at Dubai Internet City, themed \"Intelligence Everywhere: The AI Economy\".",
    start: "2026-02-11",
    end: "2026-02-12",
    venue: "Dubai Internet City",
    geo: { name: "Dubai Internet City", lat: 25.102165, lng: 55.173901 },
    city: "Dubai",
    organizer: "Step Conference",
    category: "Conference",
    source: {
      name: "Step Conference",
      url: "https://dubai.stepconference.com/",
      verifiedOn: "2026-08-25",
    },
    body: [
      "Step held its 14th Dubai edition across February 11 and 12, 2026 at Dubai Internet City, under the theme \"Intelligence Everywhere: The AI Economy\" — startups, finance, digital media and the spread of AI through all three.",
      "The organisers put the expected scale at more than 8,000 attendees, over 400 showcasing startups, 100+ participating companies, and investors representing upwards of $9 billion in available funding.",
    ],
    // No `outcome` yet: the organisers published projections beforehand and
    // no final count afterwards, so there is nothing to report here that
    // wouldn't be invented. It gets written when a real figure exists.
    expertise:
      "Those figures are the ones the organisers published in advance, and no final count has been released since — worth keeping in mind whenever an event's scale is quoted back at you, here included. Attendance projections are marketing until somebody publishes the actual number, which most conferences never do.",
  },
  {
    slug: "world-governments-summit-2027",
    createdAt: "2026-08-25T18:18:34+04:00",
    updatedAt: "2026-09-07T16:06:17+04:00",
    site: "dst",
    image: "/covers/world-governments-summit-2027.jpg",
    imageAlt: "A round table seen from above with evenly spaced seats around its rim",
    imageKind: "generated",
    imageWidth: 1536,
    imageHeight: 864,
    title: "World Governments Summit 2027",
    titleSeo: "World Governments Summit 2027, Dubai",
    summary:
      "Dubai hosts the World Governments Summit on February 1–3, 2027, following the largest participation in the summit's history.",
    start: "2027-02-01",
    end: "2027-02-03",
    city: "Dubai",
    organizer: "World Governments Summit Organisation",
    category: "Conference",
    source: {
      name: "World Governments Summit",
      url: "https://www.worldgovernmentssummit.org/media-hub/news/detail/world-governments-summit-2027-set-from-1-to-3-february",
      verifiedOn: "2026-08-25",
    },
    body: [
      "The World Governments Summit returns to Dubai from February 1 to 3, 2027. The organisers announced the dates following the summit's largest-ever global participation at the previous edition.",
      "The summit is where a good deal of the policy direction that later shows up as regulation in the UAE gets aired first — government service design, AI in the public sector, and the economic agenda behind Dubai's longer-range plans.",
    ],
    expertise:
      "The gap between what gets aired here and what turns into an actual rule is often short. Free zone licensing, residency categories and digital government services all appeared as policy direction from a summit stage before they existed as a resolution — which makes the programme worth reading as an early draft of the next year's regulation rather than as a conference agenda.",
  },

  {
    slug: "dubai-ai-festival-2026",
    createdAt: "2026-09-08T16:29:32+04:00",
    updatedAt: "2026-09-08T16:29:32+04:00",
    site: "dst",
    image: "/covers/dubai-ai-festival-2026.jpg",
    imageAlt: "Five blank cream cards standing in a row on a deep slate blue ground, their tops uneven",
    imageKind: "generated",
    imageWidth: 1536,
    imageHeight: 864,
    title: "Dubai AI Festival 2026",
    summary:
      "Two days at Dubai World Trade Centre on 26–27 October, run by the Dubai AI Campus with DIFC, across eight tracks that put governance and literacy next to infrastructure and investment.",
    start: "2026-10-26",
    end: "2026-10-27",
    utcOffset: "+04:00",
    venue: "Dubai World Trade Centre",
    city: "Dubai",
    country: "United Arab Emirates",
    organizer: "Dubai AI Campus, in partnership with DIFC",
    category: "AI",
    source: {
      name: "Dubai AI Festival",
      url: "https://dubaiaifestival.com/",
      verifiedOn: "2026-09-08",
    },
    body: [
      "Most AI conferences are organised by the industry. This one is organised by a financial centre, and the difference shows in what it puts on the agenda.",
      "## Dubai AI Festival 2026 dates",
      "<strong>26–27 October 2026</strong> at the <strong>Dubai World Trade Centre</strong>. It is run by the <strong>Dubai AI Campus</strong> in partnership with <strong>DIFC</strong>, and managed by <strong>Terrapinn</strong>.",
      "## The eight tracks",
      "<strong>AI for all.</strong> <strong>Global AI governance.</strong> <strong>Immersive experiences.</strong> <strong>Innovation and ethics.</strong> <strong>Future of work.</strong> <strong>AI cornerstone.</strong> <strong>AI literacy.</strong> <strong>Infrastructure and investment.</strong>",
      "## Who the organisers are bringing",
      "The festival advertises <strong>20+ global unicorns</strong>, <strong>20+ government agencies and ministries</strong>, <strong>20+ global enterprises</strong> and <strong>20+ venture capital firms</strong>. Speaker numbers were still shown as placeholders on the festival site when this page was checked, so none are quoted here.",
    ],
    expertise:
      "Three of the eight tracks — governance, ethics, literacy — are not the ones a vendor-run event would spend a third of its floor on, and that is the tell about who is convening this. DIFC is a regulator as much as a landlord, and the questions it needs answered are about what can be deployed inside a financial free zone rather than what can be demonstrated. The week also matters: this sits two weeks after GITEX, which means the people who came for the trade show have gone home, and the room is smaller and more specific for it.",
  },
];
