import type { EventItem } from "../types.ts";

export const items: EventItem[] = [
  {
    slug: "world-green-economy-summit-2026",
    createdAt: "2026-08-25T18:18:34+04:00",
    updatedAt: "2026-09-07T16:06:17+04:00",
    site: "eco",
    image: "/covers/world-green-economy-summit-2026.jpg",
    imageAlt: "Four sage paper columns of increasing height on a deep forest green ground, a cream band tying their tops together",
    imageKind: "generated",
    imageWidth: 1536,
    imageHeight: 864,
    title: "World Green Economy Summit 2026",
    summary:
      "The twelfth edition runs 21–22 October at Dubai World Trade Centre, built around four pillars and the argument that the transition is now a scaling problem.",
    start: "2026-10-21",
    end: "2026-10-22",
    venue: "Dubai World Trade Centre",
    city: "Dubai",
    organizer: "Dubai Supreme Council of Energy, DEWA and the World Green Economy Organization",
    category: "Environment",
    source: {
      name: "Dubai Supreme Council of Energy",
      url: "https://dubaisce.gov.ae/en/world-green-economy-summit-2026-to-highlight-international-success-stories-through-four-main-thematic-pillars/",
      verifiedOn: "2026-09-03",
    },
    body: [
      "Climate conferences mostly argue about whether to act. This one has picked a different argument: what to do with the things that already work.",
      "## The dates",
      "<strong>21–22 October 2026</strong> at the <strong>Dubai World Trade Centre</strong>. It is the <strong>twelfth edition</strong>, organised by the <strong>Dubai Supreme Council of Energy</strong>, <strong>DEWA</strong> and the <strong>World Green Economy Organization</strong>.",
      "## The theme",
      "<strong>From Success to Scale: Showcasing the Green Economy.</strong> <strong>H.E. Saeed Mohammed Al Tayer</strong>, Vice Chairman of the DSCE and DEWA's MD and CEO, describes the summit as moving the conversation beyond climate action towards demonstrating how the transition is already happening and how to expand it.",
      "## The four pillars",
      "<strong>Energy technology and infrastructure.</strong> <strong>Business strategy and transition.</strong> <strong>Water and food security.</strong> <strong>Finance.</strong> Artificial intelligence, governance and system enablers run across all four rather than sitting in one.",
      "## The size of it",
      "The organisers expect <strong>more than 3,300 participants</strong> from <strong>over 30 countries</strong>, <strong>more than 80 international speakers</strong> — ministers, chief executives and innovators — and <strong>over 300 media representatives</strong>.",
    ],
    expertise:
      "The pillar to watch is finance, and not because it is the most interesting on paper. Two of the other three — energy infrastructure and water and food security — are subjects on which the UAE has projects to show, so the sessions there tend to be demonstrations. Finance is where the unresolved question sits: scaling a proven technology is a cost-of-capital problem, and that is the pillar where the arguments are still live. Note that the summit runs the week before Expo-scale events elsewhere in the calendar and sits at the Trade Centre rather than Expo City, which makes it a workable two-day trip on its own rather than something to bolt onto another visit.",
  },

  {
    slug: "wetex-2026",
    createdAt: "2026-08-25T18:18:34+04:00",
    updatedAt: "2026-09-07T16:11:31+04:00",
    site: "eco",
    image: "/covers/wetex-2026.jpg",
    imageAlt: "A water droplet overlapping a sun disc, with turbine blades and hills in layered paper below",
    imageKind: "generated",
    imageWidth: 1536,
    imageHeight: 864,
    title: "WETEX 2026",
    summary:
      "DEWA's Water, Energy, Technology and Environment Exhibition runs October 20–22, 2026 at Dubai World Trade Centre, billed by its organiser as the region's largest across energy, water and sustainability.",
    start: "2026-10-20",
    end: "2026-10-22",
    venue: "Dubai International Convention and Exhibition Centre, Dubai World Trade Centre",
    city: "Dubai",
    geo: {
      name: "Dubai World Trade Centre",
      lat: 25.224198,
      lng: 55.286468,
    },
    organizer: "Dubai Electricity and Water Authority (DEWA)",
    category: "Exhibition",
    source: {
      name: "Clocate",
      url: "https://www.clocate.com/wetex-and-dubai-sollar-show/18809/",
      verifiedOn: "2026-08-25",
    },
    body: [
      "WETEX — the Water, Energy, Technology and Environment Exhibition, held alongside the Dubai Solar Show — runs from October 20 to 22, 2026 at the Dubai International Convention and Exhibition Centre. It is organised annually by Dubai Electricity and Water Authority.",
      "The programme covers water technology, solar, climate solutions, waste treatment and wind energy, and it is the largest event of its kind in the region across the energy, water and sustainability sectors.",
    ],
    expertise:
      "Most of what is exhibited here is industrial-scale infrastructure — desalination, grid solar, waste treatment — rather than the kind of small, verifiable planting this portfolio records, and the two are easy to conflate under the same word. It is listed anyway because it is the one week in the year when the people actually running environmental projects in this region are in one room, which is worth more than any exhibitor's stand.",
  },

  {
    slug: "middle-east-energy-2027",
    createdAt: "2026-09-08T16:29:32+04:00",
    updatedAt: "2026-09-08T16:29:32+04:00",
    site: "eco",
    image: "/covers/middle-east-energy-2027.jpg",
    imageAlt: "A linocut of one electricity pylon on a green ground, its cables running out to both edges of the frame",
    imageKind: "generated",
    imageWidth: 1536,
    imageHeight: 864,
    title: "Middle East Energy 2027",
    summary:
      "The region's largest electrical infrastructure exhibition runs 11–13 May 2027 at Dubai Exhibition Centre in Expo City, across five sectors from transmission and distribution to battery storage.",
    start: "2027-05-11",
    end: "2027-05-13",
    utcOffset: "+04:00",
    venue: "Dubai Exhibition Centre, Expo City",
    city: "Dubai",
    country: "United Arab Emirates",
    organizer: "Informa Markets",
    category: "Exhibition",
    source: {
      name: "Middle East Energy",
      url: "https://www.middleeast-energy.com/en/home.html",
      verifiedOn: "2026-09-08",
    },
    body: [
      "A green economy summit argues about direction. This is the show where the cables, switchgear and batteries that would have to carry it are actually sold.",
      "## The dates",
      "<strong>11–13 May 2027</strong> at the <strong>Dubai Exhibition Centre</strong> in <strong>Expo City</strong>, organised by <strong>Informa Markets</strong> under the patronage of the <strong>UAE Ministry of Energy and Infrastructure</strong>.",
      "## The five sectors",
      "<strong>Transmission and distribution.</strong> <strong>Critical and backup power.</strong> <strong>Renewable and clean energy.</strong> <strong>Energy consumption and management.</strong> <strong>Battery and energy storage.</strong>",
      "## The size of it",
      "The organisers give <strong>35,000+</strong> attendees, <strong>1,900+</strong> exhibitors, <strong>150+</strong> countries and <strong>250+</strong> speakers, and describe it as the region's largest electrical infrastructure exhibition.",
    ],
    expertise:
      "Renewable and clean energy is one sector of five here, and that proportion is the honest picture of what an electrical grid is made of. The other four are the reason a solar project either connects or does not: transmission capacity, backup power, demand management and storage. For a portfolio that records small, verifiable work rather than infrastructure, the useful part of a show like this is not the stands — it is that the specifications and the prices are public for three days, which is the only cheap way to find out what a given claim about capacity actually costs.",
  },

  {
    slug: "adipec-2026",
    createdAt: "2026-09-08T19:46:47+04:00",
    updatedAt: "2026-09-08T19:46:47+04:00",
    site: "eco",
    image: "/covers/adipec-2026.jpg",
    imageAlt: "A row of narrow paper bars of differing heights and three green tones, standing along a cream band on a green ground",
    imageKind: "generated",
    imageWidth: 1536,
    imageHeight: 864,
    title: "ADIPEC 2026",
    summary:
      "The largest energy event in the region runs 2\u20135 November at ADNEC in Abu Dhabi, with thirteen conference programmes and an exhibition floor the organisers put at more than 2,250 companies.",
    start: "2026-11-02",
    end: "2026-11-05",
    utcOffset: "+04:00",
    venue: "ADNEC Centre Abu Dhabi",
    city: "Abu Dhabi",
    country: "United Arab Emirates",
    organizer: "dmg events",
    category: "Exhibition",
    source: {
      name: "ADIPEC",
      url: "https://www.adipec.com/",
      verifiedOn: "2026-09-08",
    },
    ticket: { url: "https://www.adipec.com/attend/", label: "Registration and passes" },
    body: [
      "Every other event on this list is about what the energy system should become. ADIPEC is where the industry that currently supplies it turns up in one building for four days, which is a different and more awkward subject.",
      "## The dates",
      "<strong>2\u20135 November 2026</strong> at <strong>ADNEC Centre Abu Dhabi</strong>, organised by <strong>dmg events</strong>. Doors are <strong>10:00\u201318:30</strong> from Monday to Wednesday and <strong>10:00\u201317:30</strong> on Thursday.",
      "## What is in it",
      "An exhibition and <strong>thirteen conference programmes</strong> running alongside it, with dedicated areas for <strong>AI and digitalisation</strong>, <strong>maritime and logistics</strong> and <strong>low-carbon chemicals</strong> beside the upstream and downstream halls.",
      "## What it costs",
      "The exhibition and the conference are priced separately, and only the conference prices are published: a <strong>four-day all-access delegate pass at $7,250</strong>, covering eleven strategic and two technical programmes, delegate lunches and the exhibition halls, or a <strong>four-day technical pass at $2,030</strong> for the SPE and downstream technical programmes. Discounts for SPE members are offered but not listed. Visitor registration for the exhibition is open and carries no published fee.",
      "## The size of it",
      "The organisers give <strong>2,250+ exhibitors</strong>, <strong>239,000+ attendees</strong>, <strong>16,500+ conference delegates</strong> and <strong>1,800+ speakers</strong>, across <strong>380+ sessions</strong>.",
    ],
    faq: [
      {
        q: "When and where is ADIPEC 2026?",
        a: "<strong>2\u20135 November 2026</strong> at <strong>ADNEC Centre Abu Dhabi</strong>. It opens at 10:00 every day and closes at 18:30 from Monday to Wednesday and 17:30 on Thursday.",
      },
      {
        q: "How much is an ADIPEC delegate pass?",
        a: "<strong>$7,250</strong> for the four-day all-access pass and <strong>$2,030</strong> for the four-day technical pass. SPE members are told to ask for member pricing rather than given a figure.",
      },
      {
        q: "Do I need a delegate pass to walk the exhibition?",
        a: "No \u2014 exhibition visitor registration is separate from the conference, and no fee is published for it. The delegate passes include the exhibition halls on top of the conference programmes.",
      },
      {
        q: "Is ADIPEC in Abu Dhabi or Dubai?",
        a: "<strong>Abu Dhabi</strong>, at ADNEC. It is roughly a ninety-minute drive from Dubai, which is why the week is usually planned as a stay rather than a day trip.",
      },
    ],
    expertise:
      "The thing worth reading closely is where the new halls are. AI and digitalisation, maritime and logistics, and low-carbon chemicals have their own areas this year, and none of them is an oil-and-gas category \u2014 they are the parts of the business where the spending decisions are still open. The pricing says something too: the technical pass is a quarter the price of the all-access one, so the papers and the engineering sessions are reachable at a cost that the strategic programme is not. For anyone comparing this with the Dubai shows in the same season, the difference is that WETEX and Middle East Energy sell equipment and ADIPEC sells positions \u2014 the exhibition is the smaller half of why people go.",
  },
];
