import type { EventItem } from "../types.ts";

export const items: EventItem[] = [
  {
    slug: "bermondsey-street-festival-2026",
    site: "ldn",
    image: "/covers/bermondsey-street-festival-2026.jpg",
    imageAlt: "A red paper bunting line strung across a warm off-white ground above two charcoal market stall shapes",
    imageKind: "generated",
    imageWidth: 1536,
    imageHeight: 864,
    title: "Bermondsey Street Festival 2026",
    summary:
      "The street shuts to traffic on Saturday 19 September, 10am to 5pm, for the festival's twentieth year. Free, volunteer-run, and spread across three areas.",
    start: "2026-09-19",
    startTime: "10:00",
    endTime: "17:00",
    utcOffset: "+01:00",
    venue: "Bermondsey Street, SE1",
    city: "London",
    organizer: "Bermondsey Street Festival",
    category: "Festival",
    source: {
      name: "Bermondsey Street Festival",
      url: "https://bermondseystreetfestival.com/",
      verifiedOn: "2026-09-03",
    },
    body: [
      "Bermondsey Street is a narrow Georgian run between London Bridge and the Blue. For one Saturday a year the cars come off it.",
      "## When",
      "<strong>Saturday 19 September 2026</strong>, <strong>10am to 5pm</strong>. It is <strong>free</strong>, and it is the festival's <strong>twentieth year</strong>.",
      "## Where, precisely",
      "The festival runs in three parts: <strong>On The Street</strong> along Bermondsey Street itself, the <strong>Family Fun Hub</strong>, and <strong>Tanner Street Park</strong>.",
      "## What is on it",
      "Music, food, independent stalls and street entertainers along the closed road, with the family programme handled separately so the two do not compete for the same pavement.",
      "## Who runs it",
      "Volunteers. It is funded by grant support from <strong>Southwark Council</strong> and by sponsorship — <strong>Team London Bridge</strong> and <strong>Store House</strong> as platinum sponsors, with <strong>Lolo</strong> and <strong>The Woolpack</strong> among the gold.",
    ],
    expertise:
      "This is a street party rather than an event with a site, and the difference shows in how you approach it. Bermondsey Street has no capacity to expand, so the crowd density is set by the width of the road: mid-morning is comfortable, and by two o'clock the stretch between Tanner Street and Long Lane is shoulder to shoulder. London Bridge is the obvious station and the busiest approach; Borough and Bermondsey both put you on the quieter end. Tanner Street Park is where to head if the street itself has filled — it is the part of the festival with room in it, and it is a two-minute walk from the middle of the crush.",
  },

  {
    slug: "bfi-london-film-festival-2026",
    site: "ldn",
    image: "/covers/bfi-london-film-festival-2026.jpg",
    imageAlt: "A fanned stack of red paper rectangles with a dark aperture ring resting over them",
    imageKind: "generated",
    imageWidth: 1536,
    imageHeight: 864,
    title: "BFI London Film Festival 2026",
    summary:
      "Andrew Scott and Olivia Colman open the 70th LFF on 7 October in Elsinore. The festival runs to 18 October, and tickets go on general sale on 17 September.",
    start: "2026-10-07",
    end: "2026-10-18",
    city: "London",
    venue: "BFI Southbank and other cinemas",
    category: "Festival",
    organizer: "British Film Institute",
    source: {
      name: "British Film Institute",
      url: "https://www.bfi.org.uk/london-film-festival/news/simon-stone-elsinore-70th-bfi-london-film-festival",
      verifiedOn: "2026-09-01",
    },
    body: [
      "A film festival reaching its seventieth edition has outlived most of the distribution models it was built to serve, which is a reasonable thing to think about while queueing for a ticket.",
      "The <strong>70th BFI London Film Festival runs from Wednesday 7 to Sunday 18 October 2026</strong>.",
      "## Elsinore opens it",
      "The festival opens on <strong>Wednesday 7 October</strong> at the <strong>Royal Festival Hall</strong> with the European premiere of <strong>Elsinore</strong>, directed by <strong>Simon Stone</strong> and drawn from the life of the actor <strong>Ian Charleson</strong>. <strong>Andrew Scott</strong> plays the central role, with Olivia Colman, Billie Piper, Johnny Flynn, Juliet Stevenson, Monica Dolan, Adeel Akhtar and Peter Mullan around him.",
      "Festival director Kristy Matheson, announcing it on 29 July: «Anchored by Andrew Scott’s astounding central performance, few films will leave a lasting imprint on audiences this year quite like Elsinore.»",
      "## Four competitions, not one",
      "The festival runs <strong>four competitive categories</strong>: <strong>Best Film</strong>, <strong>Best Documentary</strong> (the Grierson Award), <strong>Best First Feature</strong> (the Sutherland Award) and the <strong>Short Film Award</strong>. The <strong>Audience Awards</strong> return for 2026.",
      "<strong>Ten films</strong> are in Official Competition for Best Film, chosen from ten countries: the UK, Ireland, Brazil, Denmark, France, Germany, Hungary, Italy, Japan and Poland. The LFF Awards Jury announces the winner on <strong>Sunday 18 October</strong>.",
      "Festival director Kristy Matheson framed the selection around its returning names: «As we celebrate the 70th edition of the BFI London Film Festival, it’s an honour to have a number of alumni filmmakers represented in the Official Competition...»",
      "The shortlists for the other competitive categories are announced in September.",
      "## The useful fortnight",
      "The programme lands a fortnight before anything can be bought. That gap is the festival handing every buyer the same information and then making them wait — and the people who spend it building a shortlist are the ones who get the screenings they wanted.",
      "## What a festival screening is for",
      "Most of what plays at LFF will reach a cinema or a streaming service eventually. What will not repeat is the room: a first UK audience, frequently with the director in it, watching something before any consensus about it exists. That is the part the ticket buys.",
    ],
    programme: [
      { heading: "7–18 October — the festival", text: "Twelve days, opening at the Royal Festival Hall with <strong>Elsinore</strong>." },
      { heading: "2 September — the full programme", text: "The date the BFI gave for publishing everything that plays. <span class=\"tba\">To be announced</span>" },
      { heading: "17 September — tickets", text: "General sale, with BFI Members booking before it. Prices <span class=\"tba\">to be announced</span>" },
      { heading: "During September — the other shortlists", text: "Documentary, First Feature and Short Film. Titles <span class=\"tba\">to be announced</span>" },
      { heading: "18 October — the awards", text: "The LFF Awards Jury names the Best Film winner on the closing day." },
    ],
    expertise:
      "Competition titles are the hardest tickets and rarely the best use of a first festival. The films with distribution deals already signed will be in cinemas within months; the ones worth a festival seat are the documentaries and first features, which are the categories where a London screening is sometimes the only one a film gets in this country.",
  },
  {
    slug: "london-design-festival-2026",
    featured: 1,
    site: "ldn",
    image: "/covers/london-design-festival-2026.jpg",
    imageAlt: "A grid of paper furniture silhouettes in red and charcoal",
    imageKind: "generated",
    imageWidth: 1536,
    imageHeight: 864,
    title: "London Design Festival 2026",
    summary:
      "Nine days, eleven design districts and a light installation inside St Paul's Cathedral. The 24th festival runs 12–20 September, and most of it is free to walk into.",
    start: "2026-09-12",
    end: "2026-09-20",
    city: "London",
    venue: "Across London",
    category: "Festival",
    organizer: "London Design Festival",
    source: {
      name: "London Design Festival",
      url: "https://www.londondesignfestival.com/",
      verifiedOn: "2026-08-30",
    },
    body: [
      "The London Design Festival is not a venue you buy a ticket to. It is a week in which several hundred separate things happen across the city and agree to call themselves one event — and the trick to it is knowing that the good parts are free and the paid parts are optional.",
      "The <strong>24th edition runs from Saturday 12 to Sunday 20 September 2026</strong>.",
      "## Start with the Landmark",
      "Every year the festival commissions a small number of large installations, and every year those are what people actually remember. In 2026 the headline commission is <strong>The Point of Unity and Soul</strong>: contemporary light and media art staged inside <strong>St Paul’s Cathedral</strong>.",
      "A cathedral interior is an unusual thing to hand to a light artist, because it already does the job — Wren’s dome was designed around where daylight falls. Putting a media installation into that space is an argument with the building, not a decoration of it, and that is the reason to go and look.",
      "Alongside it, <strong>The Art of Sound</strong> brings Max Cooper and Chris Watson together for L-Acoustics, and <strong>The Speaking Oasis</strong> takes palm weaving — a craft, not a material anyone expects to see in an architecture programme — into architecture and design.",
      "## Eleven districts, and why that matters",
      "The festival is organised into <strong>eleven design districts</strong> for 2026: Bankside, Brompton, Blackhorse Creates, Chelsea, Dalston to Stokey, EC1, Fleet Street Quarter, Mayfair, Park Royal, Shoreditch and Soho.",
      "The districts are the practical unit of the festival. Each is a walkable cluster of studios, showrooms and installations, which means a day spent inside one district sees more than a day spent crossing London between three headline commissions. Blackhorse Creates and Park Royal are the two that pull furthest out of the centre, and they are also the two where the work is being made rather than displayed.",
      "## The talks are free, and they book out",
      "The <strong>Global Design Forum</strong> is the festival’s talks programme, and <strong>free tickets</strong> are available for 2026. The line-up announced so far includes a keynote from <strong>Es Devlin</strong>, a conversation between Sun Media Group’s Yang Lan and the Crafts Council’s Natalie Melton, and sessions on colour, shared ecologies and machine intelligence in design.",
      "Free and unlimited are different things. A free ticket to a named keynote is the kind that disappears in the first day of release.",
      "## The other festival happening the same week",
      "Open House Festival runs on <strong>exactly the same nine days</strong>, opening buildings across all 33 boroughs for free. The overlap is not a coincidence and it is not a clash: one lets you inside the buildings, the other fills them with what people are making now.",
    ],
    expertise:
      "Pick a district, not a shortlist. The festival map tempts everyone into a route of four famous installations spread across the city, which turns into a day of transport with four short stops in it. One district on foot — Bankside, Shoreditch or EC1 — is a better day and sees roughly ten times as much work.",
  },
  {
    slug: "open-house-festival-2026",
    site: "ldn",
    image: "/covers/open-house-festival-2026.jpg",
    imageAlt: "Layered paper building facades with one small red door standing open",
    imageKind: "generated",
    imageWidth: 1536,
    imageHeight: 864,
    title: "Open House Festival 2026",
    summary:
      "For nine days in September, buildings across all 33 boroughs open their doors for free. The 35th edition runs 12–20 September, and the ticketed places went on sale in August.",
    start: "2026-09-12",
    end: "2026-09-20",
    city: "London",
    venue: "All 33 London boroughs",
    category: "Architecture",
    organizer: "Open City",
    source: {
      name: "Open City",
      url: "https://open-city.org.uk/open-house-festival",
      verifiedOn: "2026-08-30",
    },
    body: [
      "Open House is the one week a year when the answer to «what is that building?» is «come in and see». The <strong>35th edition runs from Saturday 12 to Sunday 20 September 2026</strong>, and everything in it is <strong>free</strong>.",
      "## What it actually is",
      "Buildings and sites across <strong>all 33 London boroughs</strong> open to the public: private houses, working offices, infrastructure, places of worship, studios, and the occasional thing that is not really a building at all. The organisers describe it as opening up and celebrating the city’s built environment, which understates it — in practice it is the only legal way most people will ever stand inside a good deal of this city.",
      "The festival is run by Open City, and it exists because people volunteer to open their doors. The contributors are householders, architects, institutions and community groups, not a venue programme.",
      "## The part people get wrong",
      "Most of Open House is <strong>walk-up</strong>: turn up during the open hours, queue if there is a queue, go in. A smaller set of sites is <strong>ticketed</strong>, and those are the famous ones — the tall towers, the private houses, the buildings with a lift and a capacity limit.",
      "Ticketed bookings for 2026 went live at <strong>midday on Wednesday 19 August</strong>, and they require a free account registered in advance. If that date has passed by the time you read this, it does not mean the festival is closed: it means the ballot-like scramble is over and the several hundred walk-up sites are all still there.",
      "The programme itself was published on <strong>15 July</strong>, on the festival’s own website.",
      "## How to spend it",
      "The instinct is to chase one famous building. The better use of the week is to pick a borough — ideally one you do not live in — and treat its open sites as a walking route. The festival’s reach across all 33 boroughs is the point of it; the towers are simply the part that photographs.",
      "Access requirements can be discussed with the festival team in advance, and the organisers ask people to get in touch rather than turn up hoping.",
    ],
    expertise:
      "The queue is the honest signal. A site with no queue at 10am on the Saturday is not a lesser building — it is usually a building that did not make a list, and the volunteer standing in it will have half an hour to talk to you. That is the version of Open House people remember, and it is the opposite of the one they plan.",
  },
  {
    slug: "totally-thames-2026",
    site: "ldn",
    image: "/covers/totally-thames-2026.jpg",
    imageAlt: "A paper river winding under a bridge span",
    imageKind: "generated",
    imageWidth: 1536,
    imageHeight: 864,
    title: "Totally Thames 2026",
    summary:
      "A month of art, performance and river adventures along the Thames through September — a film installation on Blackfriars Bridge, a dance duet in the Brunel tunnel shaft, an opera about water.",
    start: "2026-09-01",
    end: "2026-09-30",
    city: "London",
    venue: "Along the Thames",
    category: "Festival",
    organizer: "Thames Festival Trust",
    source: {
      name: "Thames Festival Trust",
      url: "https://totallythames.org/",
      verifiedOn: "2026-08-30",
    },
    body: [
      "London spent centuries with its back to the river, and Totally Thames is a month-long argument for turning round. It runs the <strong>whole of September</strong>, from the 1st to the 30th, and it is spread the length of the tidal Thames rather than gathered on the South Bank.",
      "## The shape of it",
      "The festival is programmed by the Thames Festival Trust and mixes arts events, active adventures on the water, environmental projects and heritage and education programmes. What that means in practice is that a single September weekend might offer a film installation, a rowing trip and a talk about eels.",
      "The venues are the interesting part. Not theatres — a railway bridge, a lightship, a tunnel shaft, a Victorian pumping station, a community mooring. Each performance below is site-specific in the strict sense: it could not be moved somewhere else without ceasing to be itself.",
      "## What to look at first",
      "<strong>Turning the Tide</strong> is the one that needs no ticket and no plan: a site-specific film installation projected onto the columns of <strong>Blackfriars Railway Bridge</strong>, running Thursday 17 to Sunday 20 September. Bridge columns are an unusual screen — the image is broken by the structure rather than framed by it, and the river moves underneath the whole time.",
      "<strong>The Living Thames</strong>, on Friday 18 September, is the one to book: Dvořák’s American Quartet, Handel’s Water Music, Smetana’s Moldau and Strauss’s Blue Danube played with Thames field recordings, at <strong>Crossness Pumping Station</strong> — a piece of Victorian sewage infrastructure that happens to be one of the most extravagant interiors in London.",
      "## The river as a stage",
      "Several of the September pieces come through the Trust’s Seed Funder scheme, which backs work made for the river specifically. <strong>Where the River Holds Us</strong> is a site-responsive multisensory opera about water, memory, climate and belonging. <strong>River Recital presents SS Robin</strong> turns the historic <strong>SS Robin</strong> at Trinity Buoy Wharf into an immersive environment of sound and moving image. <strong>Nadi</strong> is a contemporary dance duet performed by former Rambert dancers in the shaft of the <strong>Brunel Museum</strong> tunnel — the first tunnel ever dug under a navigable river.",
      "That last one is worth the detour on its own. The shaft is a brick cylinder that was, briefly in the 1840s, an underground concert hall. Putting dancers back into it is less an intervention than a restoration.",
    ],
    programme: [
      { heading: "Sat 5 September — Aftertide", text: "Live performance at Hermitage Community Moorings, continuing beyond the night itself." },
      { heading: "Sun 6 September — The Waterfront Journals", text: "A promenade performance of David Wojnarowicz's text at Thames Barrier Park, presented by ONE DAY THIS KID." },
      { heading: "Thu 17 – Sun 20 September — Turning the Tide", text: "Site-specific film installation on the columns of Blackfriars Railway Bridge." },
      { heading: "Fri 18 September — The Living Thames", text: "Dvořák, Handel, Smetana and Strauss with Thames field recordings at Crossness Pumping Station." },
      { heading: "Thu 24 September — Nadi", text: "Contemporary dance duet by Aishwarya Raut and Antonello Sangirardi in the Brunel Museum tunnel shaft." },
      { heading: "Fri 25 September — Kick the Door Down", text: "An hour of river-themed theatre from the scheme's alumni community." },
      { heading: "Sat 26 September — River Recital presents SS Robin", text: "The historic SS Robin at Trinity Buoy Wharf as an immersive environment of sound and moving image." },
      { heading: "Sun 27 – Mon 28 September — Where the River Holds Us", text: "A site-responsive multisensory opera on water, memory, climate and belonging." },
    ],
    expertise:
      "Check the tide before the timetable. Several of these sites — the moorings, the wharf, the foreshore walks — are on the river rather than beside it, and the Thames drops the height of a house twice a day. The festival schedules around that; a visitor who does not will arrive at a jetty and find water where the path was.",
  },
  {
    slug: "lord-mayors-show-2026",
    featured: 2,
    site: "ldn",
    image: "/covers/lord-mayors-show-2026.jpg",
    imageAlt: "A red paper ceremonial coach under a line of bunting",
    imageKind: "generated",
    imageWidth: 1536,
    imageHeight: 864,
    title: "Lord Mayor's Show 2026",
    summary:
      "Saturday 14 November, 11am, from Mansion House: an eight-century-old procession that closes almost the whole City of London and costs nothing to watch.",
    start: "2026-11-14",
    startTime: "11:00",
    utcOffset: "+00:00",
    city: "London",
    venue: "City of London, from Mansion House",
    category: "Procession",
    organizer: "The Lord Mayor's Show",
    source: {
      name: "The Lord Mayor's Show",
      url: "https://www.lordmayorsshow.london/",
      verifiedOn: "2026-08-30",
    },
    body: [
      "The organisers describe their own event as the oldest, longest, best loved and least-rehearsed civic procession in the world, and every part of that is defensible — the last part especially.",
      "The <strong>2026 Show sets off from Mansion House at 11am on Saturday 14 November</strong> and fills most of the City of London. It is <strong>free</strong> and there is no ticket.",
      "## Eight hundred years of it",
      "The Show dates to the early 13th century, when King John granted that the City of London could appoint its own mayor — on condition that the new mayor travel to Westminster each year to swear loyalty to the crown. The procession is that journey, still being made. It began as a mediaeval power play and it has never stopped being one.",
      "In two hundred years it has been cancelled <strong>twice</strong>. It ran through the wars.",
      "## What actually comes past",
      "The <strong>2025 Show had over 7,000 participants</strong> from all over the world, in a procession more than <strong>three miles long</strong> when lined up. It is not a parade of floats: it is military bands, livery companies, charities, ceremonial carriages, school groups and a good deal that defies category, moving at walking pace for well over an hour.",
      "Details of the 2026 Show — the processional order, the participants, the new Lord Mayor — are published around the beginning of October, once the next Lord Mayor is elected. They are not announced yet, so they do not appear here.",
      "## The City stops",
      "Almost the whole of the City is closed on Show day, with no traffic in or out. Every bus route that would normally run through the City either turns back or goes around, and TfL publishes the detail in the week beforehand. Parking bays across the area are suspended from the Friday afternoon — partly to make space, partly so nobody gets shut in for the day. Residents’ parking at the Barbican is unaffected.",
      "Cars and buses cannot get in, but tube, train and river bus all can, and the organisers point people at all three.",
      "## Watching it well",
      "The procession is naturally accessible and free to all, and the organisers publish specific suggestions for wheelchair users and for anyone worried about crowds — which is a more useful page than most events of this size manage.",
      "The practical note for everyone else: three miles of procession takes a long time to pass one spot, so the choice is not where the best view is but how much of the route you want to be near when it starts.",
    ],
    expertise:
      "The Show is a morning event with an afternoon attached, and the two are different. The procession goes out at 11am and returns in the early afternoon — the return leg is the same participants, the same route in reverse, and a fraction of the crowd. If 11am at the front is not realistic, the return is not a consolation prize.",
  },
  {
    slug: "tokio-hotel-ovo-arena-2026",
    image: "/covers/tokio-hotel-ovo-arena-2026.jpg",
    imageAlt: "Two cut-paper figures seen from behind on a stage, arms raised, one with a guitar, red and charcoal streamers arcing overhead",
    imageKind: "generated",
    imageWidth: 1536,
    imageHeight: 864,
    featured: 3,
    site: "ldn",
    title: "Tokio Hotel at OVO Arena Wembley",
    cardTitle: "Tokio Hotel at Wembley",
    summary:
      "Wednesday 28 October, 6pm: the German band open their 2026 arena tour in London, seventeen dates before Madrid closes it in November.",
    start: "2026-10-28",
    startTime: "18:00",
    // BST ends on 25 October 2026, so the show falls three days into GMT.
    utcOffset: "+00:00",
    city: "London",
    venue: "OVO Arena Wembley, Arena Square, Engineers Way, HA9 0AA",
    category: "Music",
    organizer: "OVO Arena Wembley",
    ticket: {
      url: "https://www.axs.com/uk/events/893660/tokio-hotel-tickets?skin=wembley",
      label: "Tickets on AXS",
    },
    source: {
      name: "OVO Arena Wembley",
      url: "https://www.ovoarena.co.uk/events",
      verifiedOn: "2026-09-04",
    },
    body: [
      "A tour has to start somewhere, and this one starts here. Of the seventeen dates Tokio Hotel have announced for their 2026 arena run, London is the first — two days before Paris, and nearly a month before Madrid closes it on 23 November.",
      "## When and where",
      "<strong>Wednesday 28 October 2026</strong> at <strong>OVO Arena Wembley</strong>, with the venue listing a <strong>6pm</strong> start. Tickets are sold through <strong>AXS</strong>.",
      "## Who they are",
      "Four musicians from Magdeburg who formed in 2001: <strong>Bill Kaulitz</strong> on vocals, his twin brother <strong>Tom Kaulitz</strong> on guitar, <strong>Georg Listing</strong> on bass and <strong>Gustav Schäfer</strong> on drums. Twenty-five years is an unusual length of time for a band that arrived as a teenage phenomenon, and unusual too for one that has kept the same four members throughout.",
      "## The run this belongs to",
      "The 2026 tour takes in London, Paris twice, Hamburg, Brussels, Amsterdam, Frankfurt, Berlin, Nuremberg, Zurich, Milan, Leipzig, Vienna, Munich, Esch-sur-Alzette, Düsseldorf and Madrid. It is a European run: no North American or Latin American dates have been announced alongside it.",
      "## Getting there",
      "Wembley Park is the closest station and the one the arena itself points people at, on the Jubilee and Metropolitan lines. Wembley Stadium station, on the Chiltern line out of Marylebone, is the other option. A weeknight show at this end of the Jubilee line means the last trains matter more than they would in the centre.",
    ],
    expertise:
      "An October Wednesday at Wembley Park is a different proposition from a Saturday one: the arena and the stadium share a station, and on a night when only the arena is in use the walk from Wembley Park is quick. The thing to check before travelling is not the venue but the line — Jubilee weekend and evening closures are frequent at this end, and Transport for London publish them the week before. The 6pm start printed by the arena is the door-to-curtain figure venues use for the whole evening, support included, so it is not the time the headline act appears.",
  },
  {
    slug: "notting-hill-carnival-2026",
    featured: 3,
    site: "ldn",
    image: "/covers/notting-hill-carnival-2026.jpg",
    imageAlt: "A tall red paper feather plume above scattered confetti",
    imageKind: "generated",
    imageWidth: 1536,
    imageHeight: 864,
    title: "Notting Hill Carnival 2026",
    summary:
      "Three days over the August bank holiday for Carnival's sixtieth year: Panorama on the Saturday, J'Ouvert and Children's Day on the Sunday, the main parade on the Monday. Free, and enormous.",
    start: "2026-08-29",
    end: "2026-08-31",
    city: "London",
    venue: "Notting Hill, W11",
    category: "Carnival",
    organizer: "Notting Hill Carnival Ltd",
    source: {
      name: "Notting Hill Carnival",
      url: "https://nhcarnival.org/updates/notting-hill-carnival-2026",
      verifiedOn: "2026-08-30",
    },
    body: [
      "Carnival runs across three days in 2026, and they are not interchangeable. Anyone who turns up on the wrong one for what they wanted has not seen a smaller version of the same event — they have seen a different event",
      "## The three days",
      "<strong>Saturday 29 August</strong> is the <strong>UK National Panorama</strong> steel band competition. It is the one that gets left off the summaries, and it is the day on which the music is the point rather than the soundtrack",
      "<strong>Sunday 30 August</strong> is <strong>J’Ouvert</strong> in the early morning, then the <strong>Children’s Day parade</strong>. This is the family day and the quieter of the two parade days — quieter being relative",
      "<strong>Monday 31 August</strong> is the <strong>main parade</strong>: the adults’ day, and the busiest thing that happens in London all year",
      "## Sixty years",
      "It is the sixtieth Carnival, counting from <strong>1966</strong>. Organisers have put a record number of stewards on the route for it, and a plaque naming <strong>70 people</strong> who built the event was unveiled at Westbourne Park station — the northern end of the parade route",
      "## Getting there",
      "More than <strong>two million journeys</strong> are made on the transport network for Carnival each year, which is why the standing advice is to travel to <strong>Paddington and walk</strong> the last twenty minutes",
      "The stations on the route are restricted rather than open: <strong>Ladbroke Grove is closed all day</strong>; <strong>Westbourne Park</strong> takes no entries after 11am; <strong>Notting Hill Gate</strong>, <strong>Queensway</strong> and <strong>Royal Oak</strong> take none between 11am and 6pm; <strong>Holland Park</strong> shuts at 3pm. Buses are diverted away from the whole area, with limited-stop specials such as the <strong>148X</strong> running instead",
      "## What it costs",
      "Nothing. Carnival is free and unticketed, which is a large part of why it is the size it is",
    ],
    expertise:
      "The one decision worth making in advance is which day. Sunday and Monday get described together often enough that people arrive on the Monday expecting the Sunday’s crowd, which is a different event at a different density. If it is a first Carnival, or there are children involved, Sunday is the day — and Saturday if what you actually came for is the music",
  },

  {
    slug: "andre-rieu-ovo-arena-2026",
    image: "/covers/andre-rieu-ovo-arena-2026.jpg",
    imageAlt: "André Rieu playing the violin at the right of the Johann Strauss Orchestra, the players in ball gowns and tails behind gilded music stands",
    imageKind: "photo",
    imageCaption: "André Rieu and the Johann Strauss Orchestra at the Vrijthof, Maastricht, July 2018",
    imageCredit: "bert knottenbeld via Wikimedia Commons, CC BY-SA 2.0",
    imageWidth: 1536,
    imageHeight: 864,
    site: "ldn",
    title: "André Rieu at OVO Arena Wembley",
    cardTitle: "André Rieu at Wembley",
    summary:
      "Two nights, 17 and 18 September, with the Johann Strauss Orchestra. The arena lists a 6pm start; AXS puts doors at 6.30pm and the stage at 7.30pm on the Friday.",
    start: "2026-09-17",
    end: "2026-09-18",
    startTime: "18:00",
    utcOffset: "+01:00",
    city: "London",
    venue: "OVO Arena Wembley, Arena Square, Engineers Way, HA9 0AA",
    category: "Music",
    organizer: "OVO Arena Wembley",
    ticket: {
      url: "https://www.axs.com/uk/series/31513/andre-rieu-at-ovo-arena-wembley-tickets?skin=wembley",
      label: "Both nights on AXS",
    },
    source: {
      name: "OVO Arena Wembley, with the Friday times confirmed on AXS",
      url: "https://www.ovoarena.co.uk/events",
      verifiedOn: "2026-09-04",
    },
    body: [
      "Most acts at this arena get one night. Rieu gets two, on the Thursday and the Friday, and sells them the way he has sold every UK visit for two decades — as an evening out rather than a concert.",
      "## When",
      "<strong>Thursday 17</strong> and <strong>Friday 18 September 2026</strong>. The arena publishes <strong>6pm</strong> for the run; for the Friday, AXS lists <strong>doors at 6.30pm</strong> and the show at <strong>7.30pm</strong>. The two nights are sold together as one AXS series.",
      "## What the evening is",
      "Rieu tours with the <strong>Johann Strauss Orchestra</strong>, which he founded, and the programme moves between waltzes, light classics, musicals and film scores rather than staying in one of them. The staging is part of the proposition: the orchestra plays in costume, on a set built for the room.",
      "## The scale of it",
      "The arena’s own listing puts it plainly — more than <strong>40 million albums</strong> sold, over <strong>700,000 people</strong> at his concerts in a year, and <strong>13 UK top-ten albums</strong>. He is billed as the King of Waltz, and in the UK the cinema broadcasts of these shows have outsold a good deal of what was in the cinemas with them.",
      "## Getting there",
      "Wembley Park, on the Jubilee and Metropolitan lines, is the station the arena points at. Wembley Stadium, on the Chiltern line from Marylebone, is the alternative.",
    ],
    expertise:
      "Two-night runs at Wembley behave differently from single nights, and the difference is worth a moment before booking. The Thursday is the quieter of the two to travel to and usually the easier to get a decent seat on late; the Friday absorbs everyone who could not take a weeknight, and Wembley Park at 10.30pm on a Friday is a different station from Wembley Park at 10.30pm on a Thursday. The other thing to know about this particular audience is that it arrives early. Rieu’s crowd is not a support-act crowd — the room is close to full when the orchestra walks on, which means the bars and the lifts are busiest well before the advertised start rather than during it.",
  },

  {
    slug: "anastacia-ovo-arena-2026",
    image: "/covers/anastacia-ovo-arena-2026.jpg",
    imageAlt: "Anastacia on stage in a black jacket with gold chain detail, pointing off to her right",
    imageKind: "photo",
    imageCaption: "Anastacia on the Resurrection Tour, Sydney, April 2015",
    imageCredit: "Eva Rinaldi via Wikimedia Commons, CC BY-SA 2.0",
    imageWidth: 1536,
    imageHeight: 864,
    site: "ldn",
    title: "Anastacia at OVO Arena Wembley",
    cardTitle: "Anastacia at Wembley",
    summary:
      "Saturday 26 September, doors 6pm and stage 7.30pm. The #NTK Tour 2026 reaches Wembley with Roachford and Acrobvt supporting.",
    start: "2026-09-26",
    startTime: "18:00",
    utcOffset: "+01:00",
    city: "London",
    venue: "OVO Arena Wembley, Arena Square, Engineers Way, HA9 0AA",
    category: "Music",
    organizer: "OVO Arena Wembley",
    ticket: {
      url: "https://www.axs.com/uk/events/1123850/anastacia-tickets?skin=wembley",
      label: "Tickets on AXS",
    },
    source: {
      name: "AXS, the venue's own ticket source, cross-checked against the arena listing",
      url: "https://www.axs.com/uk/events/1123850/anastacia-tickets?skin=wembley",
      verifiedOn: "2026-09-04",
    },
    programme: [
      { heading: "Anastacia", text: "Headlining the #NTK Tour 2026." },
      { heading: "Roachford", text: "Support." },
      { heading: "Acrobvt", text: "Support." },
    ],
    body: [
      "A Saturday night with two support acts on the bill is a full evening rather than a headline set with a warm-up, and this one is billed that way: Anastacia, plus Roachford and Acrobvt.",
      "## When",
      "<strong>Saturday 26 September 2026</strong>. <strong>Doors at 6pm</strong>, and AXS lists the show at <strong>7.30pm</strong> — an hour and a half of room between the two, which is what a three-act bill needs.",
      "## Where",
      "<strong>OVO Arena Wembley</strong>, Arena Square, HA9 0AA. Tickets are sold through <strong>AXS</strong>, which is the arena’s own ticket source rather than a resale site.",
      "## Getting there",
      "Wembley Park on the Jubilee and Metropolitan lines, or Wembley Stadium from Marylebone. On a Saturday it is worth checking whether the stadium next door is also in use, because the two share the walk.",
    ],
    expertise:
      "The gap between doors and stage time is the useful number on this listing. Six o’clock doors with a 7.30pm start means the first support is on well before the headline, and anyone arriving for 7.30 will have missed a chunk of the bill they paid for. It also means the reverse is true: if what you came for is Anastacia and not the evening, there is no reason to be at Wembley Park at six. The other Saturday-specific point is the stadium. Wembley Park serves both venues, and an arena night that coincides with a stadium event turns a four-minute walk into a queued one — the arena’s own what’s-on page is the place to check that before setting off.",
  },

  {
    slug: "simple-plan-ovo-arena-2026",
    image: "/covers/simple-plan-ovo-arena-2026.jpg",
    imageAlt: "Pierre Bouvier singing into a microphone with an acoustic guitar slung across him, a screen glowing behind",
    imageKind: "photo",
    imageCaption: "Simple Plan on stage in Hanoi, May 2012",
    imageCredit: "USAID Vietnam via Wikimedia Commons, public domain",
    imageWidth: 1536,
    imageHeight: 864,
    site: "ldn",
    title: "Simple Plan at OVO Arena Wembley",
    cardTitle: "Simple Plan at Wembley",
    summary:
      "Saturday 3 October, doors 6pm and stage 7.30pm: the Bigger Than You Think! Europe Tour 2026, with Stand Atlantic and Charlotte Sands.",
    start: "2026-10-03",
    startTime: "18:00",
    utcOffset: "+01:00",
    city: "London",
    venue: "OVO Arena Wembley, Arena Square, Engineers Way, HA9 0AA",
    category: "Music",
    organizer: "OVO Arena Wembley",
    ticket: {
      url: "https://www.axs.com/uk/events/1241818/simple-plan-tickets?skin=wembley",
      label: "Tickets on AXS",
    },
    source: {
      name: "AXS, the venue's own ticket source, cross-checked against the arena listing",
      url: "https://www.axs.com/uk/events/1241818/simple-plan-tickets?skin=wembley",
      verifiedOn: "2026-09-04",
    },
    programme: [
      { heading: "Simple Plan", text: "Headlining the Bigger Than You Think! Europe Tour 2026." },
      { heading: "Stand Atlantic", text: "Support." },
      { heading: "Charlotte Sands", text: "Support." },
    ],
    body: [
      "The tour is called Bigger Than You Think!, and the London date is the kind of booking that tests the claim: an arena on a Saturday, with two support acts, for a band whose audience largely met them somewhere other than an arena.",
      "## When",
      "<strong>Saturday 3 October 2026</strong>, <strong>doors 6pm</strong>, show at <strong>7.30pm</strong> according to AXS.",
      "## Who else is on it",
      "<strong>Stand Atlantic</strong> and <strong>Charlotte Sands</strong> both support. The arena’s own listing spells the first of them differently from AXS; AXS is the ticket source and is the spelling used here.",
      "## Where, and how to reach it",
      "<strong>OVO Arena Wembley</strong>, Arena Square, HA9 0AA — Wembley Park on the Jubilee and Metropolitan lines, or Wembley Stadium station on the Chiltern line out of Marylebone.",
    ],
    expertise:
      "Three bands and a 6pm door is a long evening, and the arena’s standing floor is where that gets felt: by the time the headline starts, anyone who came in at six has been on their feet for an hour and a half. Seated tickets are the better choice for a bill this length unless the floor is the point. Worth knowing too that this is the second Saturday arena show at Wembley inside eight days — Anastacia has the 26th — so if the Jubilee line has engineering work scheduled for one of those weekends, it is the sort of thing that gets announced once and catches people twice.",
  },
];
