import type { EventItem } from "../types.ts";

export const items: EventItem[] = [
  {
    slug: "bfi-london-film-festival-2026",
    site: "ldn",
    image: "/covers/bfi-london-film-festival-2026.jpg",
    imageAlt: "A fanned stack of red paper rectangles with a dark aperture ring resting over them",
    imageKind: "generated",
    imageWidth: 1536,
    imageHeight: 864,
    title: "BFI London Film Festival 2026",
    summary:
      "The 70th LFF runs 7–18 October. Ten films compete for Best Film, the full programme lands on 2 September and tickets open on 17 September.",
    start: "2026-10-07",
    end: "2026-10-18",
    city: "London",
    venue: "BFI Southbank and other cinemas",
    category: "Festival",
    organizer: "British Film Institute",
    source: {
      name: "British Film Institute",
      url: "https://www.bfi.org.uk/london-film-festival/news/official-competition-films-70th-bfi-london-film-festival",
      verifiedOn: "2026-09-01",
    },
    body: [
      "A film festival reaching its seventieth edition has outlived most of the distribution models it was built to serve, which is a reasonable thing to think about while queueing for a ticket.",
      "The <strong>70th BFI London Film Festival runs from Wednesday 7 to Sunday 18 October 2026</strong>.",
      "## Four competitions, not one",
      "The festival runs <strong>four competitive categories</strong>: <strong>Best Film</strong>, <strong>Best Documentary</strong> (the Grierson Award), <strong>Best First Feature</strong> (the Sutherland Award) and the <strong>Short Film Award</strong>. The <strong>Audience Awards</strong> return for 2026.",
      "<strong>Ten films</strong> are in Official Competition for Best Film, chosen from ten countries: the UK, Ireland, Brazil, Denmark, France, Germany, Hungary, Italy, Japan and Poland. The LFF Awards Jury announces the winner on <strong>Sunday 18 October</strong>.",
      "Festival director Kristy Matheson framed the selection around its returning names: &laquo;As we celebrate the 70th edition of the BFI London Film Festival, it&rsquo;s an honour to have a number of alumni filmmakers represented in the Official Competition...&raquo;",
      "The shortlists for the other competitive categories are announced in September.",
      "## The two dates to put in a calendar",
      "<strong>Wednesday 2 September</strong> &mdash; the full programme is revealed.",
      "<strong>Thursday 17 September</strong> &mdash; tickets go on sale, with BFI Members booking early.",
      "The gap between them is the useful fortnight. The programme is public for two weeks before anything can be bought, which means the festival hands everyone the same information and then makes them wait &mdash; and the people who spend that fortnight building a shortlist are the ones who get the screenings they wanted.",
      "## What a festival screening is for",
      "Most of what plays at LFF will reach a cinema or a streaming service eventually. What will not repeat is the room: a first UK audience, frequently with the director in it, watching something before any consensus about it exists. That is the part the ticket buys.",
    ],
    expertise:
      "Competition titles are the hardest tickets and rarely the best use of a first festival. The films with distribution deals already signed will be in cinemas within months; the ones worth a festival seat are the documentaries and first features, which are the categories where a London screening is sometimes the only one a film gets in this country.",
  },
  {
    slug: "london-design-festival-2026",
    featured: 1,
    site: "ldn",
    image: "/covers/london-design-festival-2026.jpg",
    imageAlt: "A grid of paper furniture silhouettes in red and charcoal",
    imageKind: "generated",
    imageWidth: 1536,
    imageHeight: 864,
    title: "London Design Festival 2026",
    summary:
      "Nine days, eleven design districts and a light installation inside St Paul's Cathedral. The 24th festival runs 12–20 September, and most of it is free to walk into.",
    start: "2026-09-12",
    end: "2026-09-20",
    city: "London",
    venue: "Across London",
    category: "Festival",
    organizer: "London Design Festival",
    source: {
      name: "London Design Festival",
      url: "https://www.londondesignfestival.com/",
      verifiedOn: "2026-08-30",
    },
    body: [
      "The London Design Festival is not a venue you buy a ticket to. It is a week in which several hundred separate things happen across the city and agree to call themselves one event &mdash; and the trick to it is knowing that the good parts are free and the paid parts are optional.",
      "The <strong>24th edition runs from Saturday 12 to Sunday 20 September 2026</strong>.",
      "## Start with the Landmark",
      "Every year the festival commissions a small number of large installations, and every year those are what people actually remember. In 2026 the headline commission is <strong>The Point of Unity and Soul</strong>: contemporary light and media art staged inside <strong>St Paul&rsquo;s Cathedral</strong>.",
      "A cathedral interior is an unusual thing to hand to a light artist, because it already does the job &mdash; Wren&rsquo;s dome was designed around where daylight falls. Putting a media installation into that space is an argument with the building, not a decoration of it, and that is the reason to go and look.",
      "Alongside it, <strong>The Art of Sound</strong> brings Max Cooper and Chris Watson together for L-Acoustics, and <strong>The Speaking Oasis</strong> takes palm weaving &mdash; a craft, not a material anyone expects to see in an architecture programme &mdash; into architecture and design.",
      "## Eleven districts, and why that matters",
      "The festival is organised into <strong>eleven design districts</strong> for 2026: Bankside, Brompton, Blackhorse Creates, Chelsea, Dalston to Stokey, EC1, Fleet Street Quarter, Mayfair, Park Royal, Shoreditch and Soho.",
      "The districts are the practical unit of the festival. Each is a walkable cluster of studios, showrooms and installations, which means a day spent inside one district sees more than a day spent crossing London between three headline commissions. Blackhorse Creates and Park Royal are the two that pull furthest out of the centre, and they are also the two where the work is being made rather than displayed.",
      "## The talks are free, and they book out",
      "The <strong>Global Design Forum</strong> is the festival&rsquo;s talks programme, and <strong>free tickets</strong> are available for 2026. The line-up announced so far includes a keynote from <strong>Es Devlin</strong>, a conversation between Sun Media Group&rsquo;s Yang Lan and the Crafts Council&rsquo;s Natalie Melton, and sessions on colour, shared ecologies and machine intelligence in design.",
      "Free and unlimited are different things. A free ticket to a named keynote is the kind that disappears in the first day of release.",
      "## The other festival happening the same week",
      "Open House Festival runs on <strong>exactly the same nine days</strong>, opening buildings across all 33 boroughs for free. The overlap is not a coincidence and it is not a clash: one lets you inside the buildings, the other fills them with what people are making now.",
    ],
    expertise:
      "Pick a district, not a shortlist. The festival map tempts everyone into a route of four famous installations spread across the city, which turns into a day of transport with four short stops in it. One district on foot &mdash; Bankside, Shoreditch or EC1 &mdash; is a better day and sees roughly ten times as much work.",
  },
  {
    slug: "open-house-festival-2026",
    site: "ldn",
    image: "/covers/open-house-festival-2026.jpg",
    imageAlt: "Layered paper building facades with one small red door standing open",
    imageKind: "generated",
    imageWidth: 1536,
    imageHeight: 864,
    title: "Open House Festival 2026",
    summary:
      "For nine days in September, buildings across all 33 boroughs open their doors for free. The 35th edition runs 12–20 September, and the ticketed places went on sale in August.",
    start: "2026-09-12",
    end: "2026-09-20",
    city: "London",
    venue: "All 33 London boroughs",
    category: "Architecture",
    organizer: "Open City",
    source: {
      name: "Open City",
      url: "https://open-city.org.uk/open-house-festival",
      verifiedOn: "2026-08-30",
    },
    body: [
      "Open House is the one week a year when the answer to &laquo;what is that building?&raquo; is &laquo;come in and see&raquo;. The <strong>35th edition runs from Saturday 12 to Sunday 20 September 2026</strong>, and everything in it is <strong>free</strong>.",
      "## What it actually is",
      "Buildings and sites across <strong>all 33 London boroughs</strong> open to the public: private houses, working offices, infrastructure, places of worship, studios, and the occasional thing that is not really a building at all. The organisers describe it as opening up and celebrating the city&rsquo;s built environment, which understates it &mdash; in practice it is the only legal way most people will ever stand inside a good deal of this city.",
      "The festival is run by Open City, and it exists because people volunteer to open their doors. The contributors are householders, architects, institutions and community groups, not a venue programme.",
      "## The part people get wrong",
      "Most of Open House is <strong>walk-up</strong>: turn up during the open hours, queue if there is a queue, go in. A smaller set of sites is <strong>ticketed</strong>, and those are the famous ones &mdash; the tall towers, the private houses, the buildings with a lift and a capacity limit.",
      "Ticketed bookings for 2026 went live at <strong>midday on Wednesday 19 August</strong>, and they require a free account registered in advance. If that date has passed by the time you read this, it does not mean the festival is closed: it means the ballot-like scramble is over and the several hundred walk-up sites are all still there.",
      "The programme itself was published on <strong>15 July</strong>, on the festival&rsquo;s own website.",
      "## How to spend it",
      "The instinct is to chase one famous building. The better use of the week is to pick a borough &mdash; ideally one you do not live in &mdash; and treat its open sites as a walking route. The festival&rsquo;s reach across all 33 boroughs is the point of it; the towers are simply the part that photographs.",
      "Access requirements can be discussed with the festival team in advance, and the organisers ask people to get in touch rather than turn up hoping.",
    ],
    expertise:
      "The queue is the honest signal. A site with no queue at 10am on the Saturday is not a lesser building &mdash; it is usually a building that did not make a list, and the volunteer standing in it will have half an hour to talk to you. That is the version of Open House people remember, and it is the opposite of the one they plan.",
  },
  {
    slug: "totally-thames-2026",
    site: "ldn",
    image: "/covers/totally-thames-2026.jpg",
    imageAlt: "A paper river winding under a bridge span",
    imageKind: "generated",
    imageWidth: 1536,
    imageHeight: 864,
    title: "Totally Thames 2026",
    summary:
      "A month of art, performance and river adventures along the Thames through September — a film installation on Blackfriars Bridge, a dance duet in the Brunel tunnel shaft, an opera about water.",
    start: "2026-09-01",
    end: "2026-09-30",
    city: "London",
    venue: "Along the Thames",
    category: "Festival",
    organizer: "Thames Festival Trust",
    source: {
      name: "Thames Festival Trust",
      url: "https://totallythames.org/",
      verifiedOn: "2026-08-30",
    },
    body: [
      "London spent centuries with its back to the river, and Totally Thames is a month-long argument for turning round. It runs the <strong>whole of September</strong>, from the 1st to the 30th, and it is spread the length of the tidal Thames rather than gathered on the South Bank.",
      "## The shape of it",
      "The festival is programmed by the Thames Festival Trust and mixes arts events, active adventures on the water, environmental projects and heritage and education programmes. What that means in practice is that a single September weekend might offer a film installation, a rowing trip and a talk about eels.",
      "The venues are the interesting part. Not theatres &mdash; a railway bridge, a lightship, a tunnel shaft, a Victorian pumping station, a community mooring. Each performance below is site-specific in the strict sense: it could not be moved somewhere else without ceasing to be itself.",
      "## What to look at first",
      "<strong>Turning the Tide</strong> is the one that needs no ticket and no plan: a site-specific film installation projected onto the columns of <strong>Blackfriars Railway Bridge</strong>, running Thursday 17 to Sunday 20 September. Bridge columns are an unusual screen &mdash; the image is broken by the structure rather than framed by it, and the river moves underneath the whole time.",
      "<strong>The Living Thames</strong>, on Friday 18 September, is the one to book: Dvo&#345;&aacute;k&rsquo;s American Quartet, Handel&rsquo;s Water Music, Smetana&rsquo;s Moldau and Strauss&rsquo;s Blue Danube played with Thames field recordings, at <strong>Crossness Pumping Station</strong> &mdash; a piece of Victorian sewage infrastructure that happens to be one of the most extravagant interiors in London.",
      "## The river as a stage",
      "Several of the September pieces come through the Trust&rsquo;s Seed Funder scheme, which backs work made for the river specifically. <strong>Where the River Holds Us</strong> is a site-responsive multisensory opera about water, memory, climate and belonging. <strong>River Recital presents SS Robin</strong> turns the historic <strong>SS Robin</strong> at Trinity Buoy Wharf into an immersive environment of sound and moving image. <strong>Nadi</strong> is a contemporary dance duet performed by former Rambert dancers in the shaft of the <strong>Brunel Museum</strong> tunnel &mdash; the first tunnel ever dug under a navigable river.",
      "That last one is worth the detour on its own. The shaft is a brick cylinder that was, briefly in the 1840s, an underground concert hall. Putting dancers back into it is less an intervention than a restoration.",
    ],
    programme: [
      { heading: "Sat 5 September &mdash; Aftertide", text: "Live performance at Hermitage Community Moorings, continuing beyond the night itself." },
      { heading: "Sun 6 September &mdash; The Waterfront Journals", text: "A promenade performance of David Wojnarowicz's text at Thames Barrier Park, presented by ONE DAY THIS KID." },
      { heading: "Thu 17 &ndash; Sun 20 September &mdash; Turning the Tide", text: "Site-specific film installation on the columns of Blackfriars Railway Bridge." },
      { heading: "Fri 18 September &mdash; The Living Thames", text: "Dvo&#345;&aacute;k, Handel, Smetana and Strauss with Thames field recordings at Crossness Pumping Station." },
      { heading: "Thu 24 September &mdash; Nadi", text: "Contemporary dance duet by Aishwarya Raut and Antonello Sangirardi in the Brunel Museum tunnel shaft." },
      { heading: "Fri 25 September &mdash; Kick the Door Down", text: "An hour of river-themed theatre from the scheme's alumni community." },
      { heading: "Sat 26 September &mdash; River Recital presents SS Robin", text: "The historic SS Robin at Trinity Buoy Wharf as an immersive environment of sound and moving image." },
      { heading: "Sun 27 &ndash; Mon 28 September &mdash; Where the River Holds Us", text: "A site-responsive multisensory opera on water, memory, climate and belonging." },
    ],
    expertise:
      "Check the tide before the timetable. Several of these sites &mdash; the moorings, the wharf, the foreshore walks &mdash; are on the river rather than beside it, and the Thames drops the height of a house twice a day. The festival schedules around that; a visitor who does not will arrive at a jetty and find water where the path was.",
  },
  {
    slug: "lord-mayors-show-2026",
    featured: 2,
    site: "ldn",
    image: "/covers/lord-mayors-show-2026.jpg",
    imageAlt: "A red paper ceremonial coach under a line of bunting",
    imageKind: "generated",
    imageWidth: 1536,
    imageHeight: 864,
    title: "Lord Mayor's Show 2026",
    summary:
      "Saturday 14 November, 11am, from Mansion House: an eight-century-old procession that closes almost the whole City of London and costs nothing to watch.",
    start: "2026-11-14",
    startTime: "11:00",
    utcOffset: "+00:00",
    city: "London",
    venue: "City of London, from Mansion House",
    category: "Procession",
    organizer: "The Lord Mayor's Show",
    source: {
      name: "The Lord Mayor's Show",
      url: "https://www.lordmayorsshow.london/",
      verifiedOn: "2026-08-30",
    },
    body: [
      "The organisers describe their own event as the oldest, longest, best loved and least-rehearsed civic procession in the world, and every part of that is defensible &mdash; the last part especially.",
      "The <strong>2026 Show sets off from Mansion House at 11am on Saturday 14 November</strong> and fills most of the City of London. It is <strong>free</strong> and there is no ticket.",
      "## Eight hundred years of it",
      "The Show dates to the early 13th century, when King John granted that the City of London could appoint its own mayor &mdash; on condition that the new mayor travel to Westminster each year to swear loyalty to the crown. The procession is that journey, still being made. It began as a mediaeval power play and it has never stopped being one.",
      "In two hundred years it has been cancelled <strong>twice</strong>. It ran through the wars.",
      "## What actually comes past",
      "The <strong>2025 Show had over 7,000 participants</strong> from all over the world, in a procession more than <strong>three miles long</strong> when lined up. It is not a parade of floats: it is military bands, livery companies, charities, ceremonial carriages, school groups and a good deal that defies category, moving at walking pace for well over an hour.",
      "Details of the 2026 Show &mdash; the processional order, the participants, the new Lord Mayor &mdash; are published around the beginning of October, once the next Lord Mayor is elected. They are not announced yet, so they do not appear here.",
      "## The City stops",
      "Almost the whole of the City is closed on Show day, with no traffic in or out. Every bus route that would normally run through the City either turns back or goes around, and TfL publishes the detail in the week beforehand. Parking bays across the area are suspended from the Friday afternoon &mdash; partly to make space, partly so nobody gets shut in for the day. Residents&rsquo; parking at the Barbican is unaffected.",
      "Cars and buses cannot get in, but tube, train and river bus all can, and the organisers point people at all three.",
      "## Watching it well",
      "The procession is naturally accessible and free to all, and the organisers publish specific suggestions for wheelchair users and for anyone worried about crowds &mdash; which is a more useful page than most events of this size manage.",
      "The practical note for everyone else: three miles of procession takes a long time to pass one spot, so the choice is not where the best view is but how much of the route you want to be near when it starts.",
    ],
    expertise:
      "The Show is a morning event with an afternoon attached, and the two are different. The procession goes out at 11am and returns in the early afternoon &mdash; the return leg is the same participants, the same route in reverse, and a fraction of the crowd. If 11am at the front is not realistic, the return is not a consolation prize.",
  },
  {
    slug: "notting-hill-carnival-2026",
    featured: 3,
    site: "ldn",
    image: "/covers/notting-hill-carnival-2026.jpg",
    imageAlt: "A tall red paper feather plume above scattered confetti",
    imageKind: "generated",
    imageWidth: 1536,
    imageHeight: 864,
    title: "Notting Hill Carnival 2026",
    summary:
      "Three days over the August bank holiday for Carnival's sixtieth year: Panorama on the Saturday, J'Ouvert and Children's Day on the Sunday, the main parade on the Monday. Free, and enormous.",
    start: "2026-08-29",
    end: "2026-08-31",
    city: "London",
    venue: "Notting Hill, W11",
    category: "Carnival",
    organizer: "Notting Hill Carnival Ltd",
    source: {
      name: "Notting Hill Carnival",
      url: "https://nhcarnival.org/updates/notting-hill-carnival-2026",
      verifiedOn: "2026-08-30",
    },
    body: [
      "Carnival runs across three days in 2026, and they are not interchangeable. Anyone who turns up on the wrong one for what they wanted has not seen a smaller version of the same event &mdash; they have seen a different event",
      "## The three days",
      "<strong>Saturday 29 August</strong> is the <strong>UK National Panorama</strong> steel band competition. It is the one that gets left off the summaries, and it is the day on which the music is the point rather than the soundtrack",
      "<strong>Sunday 30 August</strong> is <strong>J&rsquo;Ouvert</strong> in the early morning, then the <strong>Children&rsquo;s Day parade</strong>. This is the family day and the quieter of the two parade days &mdash; quieter being relative",
      "<strong>Monday 31 August</strong> is the <strong>main parade</strong>: the adults&rsquo; day, and the busiest thing that happens in London all year",
      "## Sixty years",
      "It is the sixtieth Carnival, counting from <strong>1966</strong>. Organisers have put a record number of stewards on the route for it, and a plaque naming <strong>70 people</strong> who built the event was unveiled at Westbourne Park station &mdash; the northern end of the parade route",
      "## Getting there",
      "More than <strong>two million journeys</strong> are made on the transport network for Carnival each year, which is why the standing advice is to travel to <strong>Paddington and walk</strong> the last twenty minutes",
      "The stations on the route are restricted rather than open: <strong>Ladbroke Grove is closed all day</strong>; <strong>Westbourne Park</strong> takes no entries after 11am; <strong>Notting Hill Gate</strong>, <strong>Queensway</strong> and <strong>Royal Oak</strong> take none between 11am and 6pm; <strong>Holland Park</strong> shuts at 3pm. Buses are diverted away from the whole area, with limited-stop specials such as the <strong>148X</strong> running instead",
      "## What it costs",
      "Nothing. Carnival is free and unticketed, which is a large part of why it is the size it is",
    ],
    expertise:
      "The one decision worth making in advance is which day. Sunday and Monday get described together often enough that people arrive on the Monday expecting the Sunday&rsquo;s crowd, which is a different event at a different density. If it is a first Carnival, or there are children involved, Sunday is the day &mdash; and Saturday if what you actually came for is the music",
  },
];
