import type { EventItem } from "../types.ts";

export const items: EventItem[] = [
  {
    slug: "lambeth-fringe-2026",
    site: "lnd",
    image: "/covers/lambeth-fringe-2026.jpg",
    imageAlt: "A cluster of small pale blue paper doorways of different heights on a deep navy ground, one lit chalk white",
    imageKind: "generated",
    imageWidth: 1536,
    imageHeight: 864,
    title: "Lambeth Fringe 2026",
    summary:
      "Five weeks of theatre, comedy, cabaret and music in pubs, chapels and small theatres across the borough, from 24 September to 25 October.",
    start: "2026-09-24",
    end: "2026-10-25",
    utcOffset: "+01:00",
    venue: "Venues across the London Borough of Lambeth",
    city: "London",
    organizer: "The Bread & Roses Theatre",
    category: "Festivals",
    source: {
      name: "Lambeth Fringe",
      url: "https://lambethfringe.com/",
      verifiedOn: "2026-09-03",
    },
    body: [
      "Edinburgh in August costs a fortune and requires a train. Lambeth in autumn requires the Northern line.",
      "## The dates",
      "<strong>24 September to 25 October 2026</strong> — five weeks, across venues in the <strong>London Borough of Lambeth</strong>.",
      "## Who is behind it",
      "The team at <strong>The Bread &amp; Roses Theatre</strong> in Clapham, who have run it yearly since <strong>2015</strong> and expanded it across multiple venues in 2024.",
      "## The shape of it",
      "Theatre, comedy, cabaret, music and family work, staged in small rooms rather than in one festival site — theatres, pubs and chapels around the borough. Named supporters and associated venues include the <strong>Bread &amp; Roses Pub</strong>, <strong>St John's Waterloo</strong>, <strong>The Bridge at Waterloo</strong>, <strong>This is Clapham</strong>, <strong>Brixton BID</strong> and <strong>We Are Waterloo</strong>.",
      "## Its stated remit",
      "The festival is open to all, with an explicit remit to platform the work of women, LGBTQ+, global-majority and working-class artists.",
    ],
    expertise:
      "A fringe spread across a borough rather than gathered on one site rewards a different sort of planning: two shows in an evening is comfortable if they share a venue and rather ambitious if one is in Waterloo and the other in Clapham, since the connection is a bus more often than a tube. The rooms are small — Bread & Roses seats around fifty — so a well-reviewed show can sell out inside a week, which is not something Edinburgh-hardened audiences expect from a fringe. And do look at the church venues. St John's Waterloo is an unusually fine room for music, and a chapel acoustic flatters a small ensemble in a way a pub back room does not.",
  },

  {
    slug: "giant-summer-flea-olympic-park",
    featured: 1,
    site: "lnd",
    image: "/covers/giant-summer-flea-olympic-park.jpg",
    imageAlt: "Paper market stalls with awnings and crates on a navy ground",
    imageKind: "generated",
    imageWidth: 1536,
    imageHeight: 864,
    title: "The Giant Summer Flea",
    summary:
      "A one-day flea market at Queen Elizabeth Olympic Park, Sunday 6 September 2026.",
    start: "2026-09-06",
    city: "London",
    venue: "Queen Elizabeth Olympic Park, E20",
    geo: { name: "Queen Elizabeth Olympic Park", lat: 51.544960, lng: -0.017177 },
    category: "Markets",
    source: {
      name: "Londonist",
      url: "https://londonist.com/london/things-to-do/things-to-do-in-london-in-september",
      verifiedOn: "2026-08-30",
    },
    body: [
      "The Giant Summer Flea takes over Queen Elizabeth Olympic Park for a single Sunday, <strong>6 September 2026</strong>.",
      "One day only, which is the thing to note — a flea market that runs for a weekend forgives arriving late on the Saturday, and this one does not.",
    ],
  },
  {
    slug: "the-big-brine-hackney-bridge",
    site: "lnd",
    image: "/covers/the-big-brine-hackney-bridge.jpg",
    imageAlt: "Rows of paper preserving jars on shelves with cut citrus discs",
    imageKind: "generated",
    imageWidth: 1536,
    imageHeight: 864,
    title: "The Big Brine",
    summary:
      "Two days at Hackney Bridge given over to everything fermented, pickled and brined, with chef demos and live music. 12–13 September 2026.",
    start: "2026-09-12",
    end: "2026-09-13",
    city: "London",
    venue: "Hackney Bridge, E15",
    geo: { name: "Hackney Bridge", lat: 51.544300, lng: -0.021258 },
    category: "Food",
    source: {
      name: "Londonist",
      url: "https://londonist.com/london/things-to-do/things-to-do-in-london-in-september",
      verifiedOn: "2026-08-30",
    },
    body: [
      "The Big Brine runs at Hackney Bridge over <strong>12 and 13 September 2026</strong>, built entirely around fermented, pickled and brined food, with chef demonstrations and live music alongside it.",
      "Hackney Bridge is a five-minute walk from Hackney Wick station and sits on the canal, which makes it one of the easier east London venues to get to without a car.",
    ],
  },

  {
    slug: "blackheath-fireworks-2026",
    site: "lnd",
    image: "/covers/blackheath-fireworks-2026.jpg",
    imageAlt: "A single white and yellow firework bursting over a deep navy sky",
    imageKind: "generated",
    imageWidth: 1536,
    imageHeight: 864,
    title: "Blackheath Fireworks 2026",
    summary:
      "South-east London's biggest firework display returns to Blackheath Common on Saturday 7 November, ticketed, with adult entry at £17.60 and a capacity of forty thousand.",
    start: "2026-11-07",
    utcOffset: "+00:00",
    venue: "Blackheath Common",
    city: "London",
    country: "United Kingdom",
    organizer: "Slammin Events, in partnership with Lewisham Council",
    category: "Fireworks",
    tickets: { priceFrom: 5.5, priceTo: 17.6, currency: "GBP" },
    source: {
      name: "Time Out London",
      url: "https://www.timeout.com/london/news/blackheath-fireworks-tickets-have-been-released-for-bonfire-night-2026-090826",
      verifiedOn: "2026-09-08",
    },
    body: [
      "For years this was the great free spectacle of south-east London: you wandered up onto the heath and the sky did the rest. It is ticketed now, which is a change worth knowing about before you wander anywhere.",
      "## The details",
      "<strong>Saturday 7 November 2026</strong> on <strong>Blackheath Common</strong>, run by <strong>Slammin Events</strong> in partnership with <strong>Lewisham Council</strong>. Capacity is <strong>40,000</strong>.",
      "## Tickets",
      "<strong>Adult (16+) £17.60. Youth (11–15) £11. Child (0–10) £5.50.</strong> Family packages run from <strong>£28.08 to £51.36</strong>. Tickets are sold through See Tickets and have been released; the organisers expect them to go quickly.",
    ],
    expertise:
      "One kindly word of warning and one of encouragement. The warning: forty thousand tickets sounds like a great many until you remember that the heath is enormous and quite dark, and the walk back down towards the station afterwards is where an evening is either pleasant or ruined — Blackheath and Greenwich stations both queue, and the buses along the A2 do rather better than either. The encouragement: a display of this size, seen from open common land rather than between buildings, is genuinely a different thing from a municipal fifteen minutes in a park, and it is the one November evening in this corner of London that is worth the cold.",
  },
];
