import type { EventItem } from "../types.ts";

export const items: EventItem[] = [
  {
    slug: "lambeth-fringe-2026",
    createdAt: "2026-08-30T11:52:01+04:00",
    updatedAt: "2026-09-12T20:15:40+04:00",
    site: "lnd",
    image: "/covers/lambeth-fringe-2026.jpg",
    imageAlt: "A cluster of small pale blue paper doorways of different heights on a deep navy ground, one lit chalk white",
    imageKind: "generated",
    imageWidth: 1536,
    imageHeight: 864,
    title: "Lambeth Fringe 2026",
    summary:
      "Five weeks of theatre, comedy, cabaret and music in the pubs, chapels and small theatres of one south London borough, from 24 September to 25 October.",
    start: "2026-09-24",
    end: "2026-10-25",
    utcOffset: "+01:00",
    venue: "Venues across the London Borough of Lambeth",
    city: "London",
    organizer: "The Bread & Roses Theatre",
    category: "Festivals",
    source: {
      name: "Lambeth Fringe",
      url: "https://lambethfringe.com/",
      verifiedOn: "2026-09-03",
    },
    body: [
      "Edinburgh in August costs a fortune and requires a train. Lambeth in autumn requires the Northern line.",
      "## The dates",
      "<strong>24 September to 25 October 2026</strong> — five weeks, across venues in the <strong>London Borough of Lambeth</strong>.",
      "## Who is behind it",
      "The team at <strong>The Bread &amp; Roses Theatre</strong> in Clapham, who have run it yearly since <strong>2015</strong> and expanded it across multiple venues in 2024.",
      "## The shape of it",
      "Theatre, comedy, cabaret, music and family work, staged in small rooms rather than in one festival site — theatres, pubs and chapels around the borough. Named supporters and associated venues include the <strong>Bread &amp; Roses Pub</strong>, <strong>St John's Waterloo</strong>, <strong>The Bridge at Waterloo</strong>, <strong>This is Clapham</strong>, <strong>Brixton BID</strong> and <strong>We Are Waterloo</strong>.",
      "## Its stated remit",
      "The festival is open to all, with an explicit remit to platform the work of women, LGBTQ+, global-majority and working-class artists.",
    ],
    expertise:
      "A fringe spread across a borough rather than gathered on one site rewards a different sort of planning: two shows in an evening is comfortable if they share a venue and rather ambitious if one is in Waterloo and the other in Clapham, since the connection is a bus more often than a tube. The rooms are small — Bread & Roses seats around fifty — so a well-reviewed show can sell out inside a week, which is not something Edinburgh-hardened audiences expect from a fringe. And do look at the church venues. St John's Waterloo is an unusually fine room for music, and a chapel acoustic flatters a small ensemble in a way a pub back room does not.",
  },

  {
    slug: "giant-summer-flea-olympic-park",
    createdAt: "2026-08-30T11:52:01+04:00",
    updatedAt: "2026-09-12T20:15:40+04:00",
    featured: 1,
    site: "lnd",
    image: "/covers/giant-summer-flea-olympic-park.jpg",
    imageAlt: "Paper market stalls with awnings and crates on a navy ground",
    imageKind: "generated",
    imageWidth: 1536,
    imageHeight: 864,
    title: "The Giant Summer Flea",
    summary:
      "A one-day flea market at Queen Elizabeth Olympic Park in east London, Sunday 6 September 2026.",
    start: "2026-09-06",
    city: "London",
    venue: "Queen Elizabeth Olympic Park, E20",
    geo: { name: "Queen Elizabeth Olympic Park", lat: 51.544960, lng: -0.017177 },
    category: "Markets",
    source: {
      name: "Londonist",
      url: "https://londonist.com/london/things-to-do/things-to-do-in-london-in-september",
      verifiedOn: "2026-08-30",
    },
    body: [
      "The Giant Summer Flea takes over Queen Elizabeth Olympic Park for a single Sunday, <strong>6 September 2026</strong>.",
      "One day only, which is the thing to note — a flea market that runs for a weekend forgives arriving late on the Saturday, and this one does not.",
    ],
  },
  {
    slug: "the-big-brine-hackney-bridge",
    createdAt: "2026-08-30T11:52:01+04:00",
    updatedAt: "2026-09-12T20:15:40+04:00",
    site: "lnd",
    image: "/covers/the-big-brine-hackney-bridge.jpg",
    imageAlt: "Rows of paper preserving jars on shelves with cut citrus discs",
    imageKind: "generated",
    imageWidth: 1536,
    imageHeight: 864,
    title: "The Big Brine",
    summary:
      "Two days at Hackney Bridge in east London given over to everything fermented, pickled and brined, with chef demos and live music. 12–13 September 2026.",
    start: "2026-09-12",
    end: "2026-09-13",
    city: "London",
    venue: "Hackney Bridge, E15",
    geo: { name: "Hackney Bridge", lat: 51.544300, lng: -0.021258 },
    category: "Food",
    source: {
      name: "Londonist",
      url: "https://londonist.com/london/things-to-do/things-to-do-in-london-in-september",
      verifiedOn: "2026-08-30",
    },
    body: [
      "The Big Brine runs at Hackney Bridge over <strong>12 and 13 September 2026</strong>, built entirely around fermented, pickled and brined food, with chef demonstrations and live music alongside it.",
      "Hackney Bridge is a five-minute walk from Hackney Wick station and sits on the canal, which makes it one of the easier east London venues to get to without a car.",
    ],
  },

  {
    slug: "blackheath-fireworks-2026",
    createdAt: "2026-09-08T16:29:32+04:00",
    updatedAt: "2026-09-12T17:35:10+04:00",
    site: "lnd",
    image: "/covers/blackheath-fireworks-2026.jpg",
    imageAlt: "A single white and yellow firework bursting over a deep navy sky",
    imageKind: "generated",
    imageWidth: 1536,
    imageHeight: 864,
    title: "Blackheath Fireworks 2026",
    summary:
      "South-east London's biggest firework display returns to Blackheath Common on Saturday 7 November, ticketed, with adult entry at £17.60 and a capacity of forty thousand.",
    start: "2026-11-07",
    utcOffset: "+00:00",
    venue: "Blackheath Common",
    city: "London",
    country: "United Kingdom",
    organizer: "Slammin Events, in partnership with Lewisham Council",
    category: "Fireworks",
    tickets: { priceFrom: 5.5, priceTo: 17.6, currency: "GBP" },
    // The organiser's own site sells from this page; the basket on it is a
    // See Tickets embed for the 2026 event, which is the seller the body
    // names. Linking the organiser's page rather than the embed keeps the
    // destination one we can see working — See Tickets refuses us outright.
    ticket: {
      url: "https://www.blackheathfireworks.com/book-tickets",
      label: "Book tickets",
    },
    source: {
      name: "Time Out London",
      url: "https://www.timeout.com/london/news/blackheath-fireworks-tickets-have-been-released-for-bonfire-night-2026-090826",
      verifiedOn: "2026-09-08",
    },
    body: [
      "For years this was the great free spectacle of south-east London: you wandered up onto the heath and the sky did the rest. It is ticketed now, which is a change worth knowing about before you wander anywhere.",
      "## The details",
      "<strong>Saturday 7 November 2026</strong> on <strong>Blackheath Common</strong>, run by <strong>Slammin Events</strong> in partnership with <strong>Lewisham Council</strong>. Capacity is <strong>40,000</strong>.",
      "## Tickets",
      "<strong>Adult (16+) £17.60. Youth (11–15) £11. Child (0–10) £5.50.</strong> Family packages run from <strong>£28.08 to £51.36</strong>. Tickets are sold through See Tickets and have been released; the organisers expect them to go quickly.",
    ],
    expertise:
      "One kindly word of warning and one of encouragement. The warning: forty thousand tickets sounds like a great many until you remember that the heath is enormous and quite dark, and the walk back down towards the station afterwards is where an evening is either pleasant or ruined — Blackheath and Greenwich stations both queue, and the buses along the A2 do rather better than either. The encouragement: a display of this size, seen from open common land rather than between buildings, is genuinely a different thing from a municipal fifteen minutes in a park, and it is the one November evening in this corner of London that is worth the cold.",
  },
  {
    slug: "halloween-hampton-court-palace-2026",
    createdAt: "2026-09-08T22:51:25+04:00",
    updatedAt: "2026-09-12T20:15:40+04:00",
    site: "lnd",
    image: "/covers/halloween-hampton-court-palace-2026.jpg",
    imageAlt: "A dark blue crenellated roofline with three towers of different heights rising from it, the tallest carrying a small red flag",
    imageKind: "generated",
    imageWidth: 1536,
    imageHeight: 864,
    title: "Halloween at Hampton Court Palace 2026",
    summary:
      "Henry VIII's haunted palace does half term from 24 October to 1 November, included with admission — the largest Halloween in the London borough of Richmond upon Thames by some distance.",
    start: "2026-10-24",
    end: "2026-11-01",
    utcOffset: "+00:00",
    venue: "Hampton Court Palace",
    city: "London",
    country: "United Kingdom",
    organizer: "Historic Royal Palaces",
    category: "Halloween",
    source: {
      name: "Historic Royal Palaces",
      url: "https://www.hrp.org.uk/tower-of-london/whats-on/halloween-at-the-tower-of-london/",
      verifiedOn: "2026-09-08",
    },
    body: [
      "The palace bills it as a spell-binding adventure at Henry VIII's haunted palace, and for once the marketing has the easier job: this is a building with a resident ghost story older than most of the borough.",
      "## The details",
      "<strong>24 October to 1 November 2026</strong> at <strong>Hampton Court Palace</strong>, in the London Borough of Richmond upon Thames. <strong>Included in palace admission</strong>; members go free and no pre-booking is required.",
      "## What it is",
      "Historic Royal Palaces run the same half-term week at both of their London palaces, and the Tower's version — ghosts in theatrical costume, gathered at set times, designed to delight rather than to fright — is the shape of this one too. At Hampton Court the setting does much of the work: the Tudor kitchens and the Base Court after four o'clock in late October need very little help.",
      "## Getting there",
      "Hampton Court station is opposite the gates, twice an hour from Waterloo, and the palace car park fills early in half term.",
    ],
    faq: [
      {
        q: "When is Halloween at Hampton Court Palace in 2026?",
        a: "24 October to 1 November 2026 — the same dates as the Tower of London's Halloween.",
      },
      {
        q: "Does it cost extra?",
        a: "No. Historic Royal Palaces say it is included in palace admission, members go free, and pre-booking is not required.",
      },
      {
        q: "Which borough is Hampton Court Palace in?",
        a: "The London Borough of Richmond upon Thames, on the north bank of the Thames at East Molesey.",
      },
    ],
    expertise:
      "One might, with respect, suggest going late rather than early. The palace is at its most obliging in the last two hours of the afternoon, when the coach parties have gone and the light in the courtyards has turned; the gardens are included and are half the reason to come, and they are emptiest then. The train from Waterloo takes a little over half an hour and puts you at the gate — which is a kinder arrangement than the car park, that being full by eleven throughout half term.",
  },

  {
    slug: "halloween-eltham-palace-2026",
    createdAt: "2026-09-08T22:51:25+04:00",
    updatedAt: "2026-09-12T20:15:40+04:00",
    site: "lnd",
    image: "/covers/halloween-eltham-palace-2026.jpg",
    imageAlt: "A large circular window divided into panes, lit pale, above a stepped pale block on a deep blue ground",
    imageKind: "generated",
    imageWidth: 1536,
    imageHeight: 864,
    title: "Halloween half-term at Eltham Palace 2026",
    summary:
      "The Great Pumpkin Party runs 24 October to 1 November, 10am to 4pm, at the art deco palace in south-east London — storytelling, a themed trail and a fancy dress contest every day.",
    start: "2026-10-24",
    end: "2026-11-01",
    startTime: "10:00",
    endTime: "16:00",
    utcOffset: "+00:00",
    venue: "Eltham Palace and Gardens",
    city: "London",
    country: "United Kingdom",
    organizer: "English Heritage",
    category: "Halloween",
    source: {
      name: "English Heritage",
      url: "https://www.english-heritage.org.uk/visit/places/eltham-palace-and-gardens/",
      verifiedOn: "2026-09-08",
    },
    body: [
      "A medieval great hall with a 1930s art deco house grafted onto it, in Greenwich, throwing a pumpkin party for nine days.",
      "## The details",
      "<strong>Saturday 24 October to Sunday 1 November 2026</strong>, <strong>10am to 4pm daily</strong>, at <strong>Eltham Palace and Gardens</strong>, Court Yard, Eltham SE9 5NP. Included in the standard entry price; English Heritage members go free, and booking in advance saves 15 per cent.",
      "## What is on",
      "The Great Pumpkin Party: interactive storytelling and spooky games, a themed trail around the site and a seasonal spot to be photographed in. There is a fancy dress competition every day with prizes, and English Heritage recommend coming dressed for it — the opposite of the rule at the Tower.",
      "## The house itself",
      "Eltham is worth the ticket without a pumpkin in sight. Stephen and Virginia Courtauld built the art deco wing onto Edward IV's great hall in the 1930s, and the entrance hall and the gardens are the reason people come back in months without half term in them.",
    ],
    faq: [
      {
        q: "When is Halloween at Eltham Palace in 2026?",
        a: "Saturday 24 October to Sunday 1 November 2026, 10am to 4pm every day.",
      },
      {
        q: "Is the Great Pumpkin Party included in admission?",
        a: "Yes — it is included in the standard entry price, members go free, and advance booking gets 15 per cent off.",
      },
      {
        q: "Can children wear costumes?",
        a: "English Heritage encourage it: there is a fancy dress competition each day, with prizes for the winners.",
      },
    ],
    expertise:
      "Eltham is the quiet one of the London half-term palaces, which is its whole advantage — the same nine days that put a queue around Hampton Court leave this one comfortable, and it is twenty minutes from London Bridge to Mottingham. Ten in the morning is the hour to arrive if the trail is the point; the house and gardens then have the rest of the day, and they are the part children remember, art deco entrance hall and all.",
  },

  {
    slug: "day-of-the-dead-horniman-2026",
    createdAt: "2026-09-08T22:51:25+04:00",
    updatedAt: "2026-09-12T20:15:40+04:00",
    site: "lnd",
    image: "/covers/day-of-the-dead-horniman-2026.jpg",
    imageAlt: "Two strings of pale bunting crossing a deep blue ground, with layered paper flowers gathered at the left end",
    imageKind: "generated",
    imageWidth: 1536,
    imageHeight: 864,
    title: "Day of the Dead at the Horniman 2026",
    summary:
      "Aztec dancers open the Horniman's Day of the Dead in south-east London on Saturday 31 October, 11am to 4pm, with mariachi, a community ofrenda and a MexiBrit market — and an adults' fiesta at 7pm.",
    start: "2026-10-31",
    startTime: "11:00",
    endTime: "16:00",
    utcOffset: "+00:00",
    venue: "Horniman Museum and Gardens",
    city: "London",
    country: "United Kingdom",
    organizer: "Horniman Museum and Gardens",
    category: "Day of the Dead",
    tickets: { priceFrom: 6, priceTo: 8, currency: "GBP" },
    // The museum books this itself. Its own "Book tickets" button points at
    // the booking block further down the event page, not at my.horniman,
    // which is a login wall and no use as a destination.
    ticket: {
      url: "https://www.horniman.ac.uk/event/day-of-the-dead-family-festival/#tickets",
      label: "Book tickets",
    },
    source: {
      name: "Horniman Museum and Gardens",
      url: "https://www.horniman.ac.uk/event/day-of-the-dead-family-festival/",
      verifiedOn: "2026-09-08",
    },
    body: [
      "It opens with a ceremonial procession led by Aztec dancers and musicians, in a garden in Forest Hill, on Halloween.",
      "## The details",
      "<strong>Saturday 31 October 2026</strong>, <strong>11am to 4pm</strong>, in the Conservatory and gardens of the <strong>Horniman Museum</strong>, Forest Hill, in the London Borough of Lewisham. <strong>£8</strong> adults, <strong>£6</strong> children under 16, free for under-2s and access companions.",
      "## What is on",
      "Live mariachi, folkloric and contemporary dance in the Sunken Gardens, stilt performers, mask-making, face painting, children's performances and games. There is a community ofrenda where visitors can honour their own dead, and the MexiBrit marketplace of Mexican and Latin American crafts, goods and food.",
      "## The evening",
      "A separate <strong>Day of the Dead Evening Fiesta</strong> runs the same night, <strong>7pm to 10.30pm</strong>, for adults — welcome cocktail included.",
      "## One thing to know",
      "It goes ahead whatever the weather, and the museum says refunds are not offered if the weather turns.",
    ],
    faq: [
      {
        q: "When is the Horniman's Day of the Dead festival in 2026?",
        a: "Saturday 31 October 2026, 11am to 4pm for the family festival, and 7pm to 10.30pm for the adults' evening fiesta.",
      },
      {
        q: "How much are tickets?",
        a: "£8 for adults and £6 for children under 16 for the family festival. Under-2s and access companions go free.",
      },
      {
        q: "Is Day of the Dead the same as Halloween?",
        a: "No. Día de Muertos is the Mexican observance of 1 and 2 November, when families welcome their dead back; the Horniman holds its festival on 31 October because that is the Saturday, not because it is Halloween.",
      },
    ],
    expertise:
      "The opening ceremony is the thing to be on time for — it is at the start of the day and it is the part that is genuinely unlike anything else on offer in south London that weekend. The gardens are on a hill with one of the better views in the city, which is worth knowing when the Conservatory is full. And if you are bringing an ofrenda photograph, bring a copy rather than the original: the community altar stays up for the day and is handled by everyone.",
  },

  {
    slug: "dark-arts-warner-bros-studio-tour-2026",
    createdAt: "2026-09-08T22:51:25+04:00",
    updatedAt: "2026-09-12T20:15:40+04:00",
    site: "lnd",
    image: "/covers/dark-arts-warner-bros-studio-tour-2026.jpg",
    imageAlt: "Dozens of pale pumpkins hanging on threads at different heights over an empty hall floor, on a deep blue ground",
    imageKind: "generated",
    imageWidth: 1536,
    imageHeight: 864,
    title: "Dark Arts at Warner Bros. Studio Tour London 2026",
    summary:
      "The studio tour's Halloween season runs 16 September to 8 November, with more than a hundred floating pumpkins over the Great Hall — an hour out of London, included in the standard ticket, and the ticket must be booked in advance.",
    start: "2026-09-16",
    end: "2026-11-08",
    utcOffset: "+01:00",
    venue: "Warner Bros. Studio Tour London, Leavesden",
    city: "Watford",
    country: "United Kingdom",
    organizer: "Warner Bros. Studio Tour London",
    category: "Halloween",
    source: {
      name: "Warner Bros. Studio Tour London",
      url: "https://www.wbstudiotour.co.uk/explore-the-tour/dark-arts/",
      verifiedOn: "2026-09-08",
    },
    body: [
      "The longest Halloween season anywhere near London is not in London at all, and it lasts fifty-four days. From <strong>16 September to 8 November 2026</strong> the studio tour at Leavesden runs its Dark Arts feature, and the single image that carries it is the Great Hall with <strong>more than a hundred floating pumpkins</strong> hanging over the tables.",
      "## The details",
      "<strong>Wednesday 16 September to Sunday 8 November 2026</strong>, at <strong>Warner Bros. Studio Tour London</strong> in Leavesden. Everything in the feature is <strong>included in the standard ticket</strong>, and tickets <strong>must be booked in advance</strong> — there is no gate to turn up at.",
      "## What is added to the tour",
      "Death Eater performances staged at several points along the route, Dementors in the Forbidden Forest, a Defence Against the Dark Arts classroom with spell-casting, the Nagini creature on display in the workshop, and, new for 2026, a Secrets of Sound Effects demonstration. Themed food and drink are on offer alongside.",
      "## Where the performances happen",
      "Hagrid's hut, the Hogwarts Express, Diagon Alley, the Hogwarts bridge and the Forbidden Forest. Pyrotechnics and smoke are used in some areas, and the tour publishes an accessibility guide for anyone who would rather go around a particular installation than through it.",
      "## Getting there",
      "Leavesden is in Hertfordshire, not London, though the tour carries London's name: the nearest station is Watford Junction, twenty minutes from Euston, with a shuttle bus from there.",
    ],
    faq: [
      {
        q: "When does Dark Arts run in 2026?",
        a: "From <strong>16 September to 8 November 2026</strong>.",
      },
      {
        q: "Does it cost extra?",
        a: "No. All of the Dark Arts features are <strong>included with a standard tour ticket</strong>, which must be booked in advance.",
      },
      {
        q: "How many pumpkins are there in the Great Hall?",
        a: "<strong>Over a hundred</strong>, floating above the tables.",
      },
      {
        q: "Is the studio tour in London?",
        a: "It is in <strong>Leavesden</strong>, Hertfordshire. The nearest station is Watford Junction, about twenty minutes from Euston, with a shuttle bus to the studios.",
      },
      {
        q: "Are there effects that might be too much for younger children?",
        a: "Pyrotechnics and smoke are used in some areas and there are Dementor and Death Eater performances. The tour publishes an accessibility guide covering how to bypass particular installations.",
      },
    ],
    expertise:
      "Two things follow from the length of the season. The first is that the last week of October is the worst time to go and the whole of late September is the best: the feature is identical, and the difference is how many people are standing between you and the Great Hall. The second is the booking — a studio tour ticket is timed and sold in advance, so the usual Halloween habit of deciding on the Saturday morning does not work here at all. And it is worth being clear-eyed about what the day is: this is the standard three-hour tour with a season laid over it, so anyone who has already done the tour is paying for the overlay, not for a new visit.",
  },
  {
    slug: "super-natural-wwt-london-2026",
    createdAt: "2026-09-12T20:16:15+04:00",
    updatedAt: "2026-09-12T20:16:15+04:00",
    site: "lnd",
    image: "/covers/super-natural-wwt-london-2026.jpg",
    imageAlt: "A slender willow wand with a pale folded star at its tip, standing on a curved gold line beside two cream mushroom caps, on deep blue",
    imageKind: "generated",
    imageWidth: 1536,
    imageHeight: 864,
    title: "SUPER Natural at WWT London 2026",
    summary:
      "The Wetland Centre at Barnes, in south-west London, answers Halloween with willow wands, a marshland potion and a fungi hunt from 24 October to 1 November — scare-free, and included with admission.",
    start: "2026-10-24",
    end: "2026-11-01",
    utcOffset: "+00:00",
    venue: "WWT London Wetland Centre",
    city: "London",
    country: "United Kingdom",
    geo: {
      name: "WWT London Wetland Centre",
      lat: 51.478899,
      lng: -0.231822,
    },
    organizer: "WWT",
    category: "Halloween",
    ticket: {
      url: "https://wwt.digitickets.co.uk/event-tickets/28293/?catID=27780&branches.branchID=332",
      label: "Book online",
    },
    source: {
      name: "WWT",
      url: "https://www.wwt.org.uk/wetland-centres/london/whats-on/events/super-natural-october-half-term-2026",
      verifiedOn: "2026-09-12",
    },
    body: [
      "Forty acres of reedbed and lagoon between Barnes and the river, and the one week of the year when a wetland is asked to be frightening. WWT has declined: the centre calls its half term SUPER Natural and says, in as many words, that there are no jump scares in it.",
      "## The details",
      "<strong>24 October to 1 November 2026</strong> at the <strong>WWT London Wetland Centre</strong>, Queen Elizabeth's Walk, in the London Borough of Richmond upon Thames. Every SUPER Natural activity is <strong>included with standard entry</strong>, entry is free for WWT members, and booking online saves ten per cent.",
      "## What it is",
      "A week of wetland folklore rather than a haunting: a handmade willow wand, a marshland potion mixed and wished over, a self-led hunt for spotted tops and giant domes among the fungi, and a fairy mushroom ring the visitors build between them. Children collect a SUPER Natural log book at the start and work through it. WWT lists three things as extras on top — carving a pumpkin to give to the otters, modelling a wetland creature in clay, and a cryptid hunt that goes looking for mermaids and settles for the real powers of the wildlife.",
      "## Who it suits",
      "The centre says it is aimed at younger children and designed to be scare-free, which is a narrower promise than most half-term listings make and the reason to read it. Costumes are welcome. The paths are step-free, and there are indoor activities as well as outdoor ones, so the weather decides less here than it looks like it should.",
      "## Getting there",
      "Barnes station is ten to fifteen minutes on foot, and the 283 runs to the gate.",
    ],
    faq: [
      {
        q: "When is SUPER Natural at WWT London in 2026?",
        a: "24 October to 1 November 2026 — one week, over the October half term.",
      },
      {
        q: "Is it scary?",
        a: "No. WWT says the week is about wonder and discovery in nature and that there are no jump scares.",
      },
      {
        q: "Does it cost extra on top of admission?",
        a: "No. WWT says all SUPER Natural activities are included with standard entry, and that members go free. Pumpkin carving, clay modelling and the cryptid hunt are listed as additional extras.",
      },
      {
        q: "Which borough is the London Wetland Centre in?",
        a: "The London Borough of Richmond upon Thames, at Barnes, on a bend of the Thames.",
      },
    ],
    expertise:
      "One would go in the morning, and one would go on a weekday. The wildlife is the point of the place and it is at its most obliging early; by two in the afternoon in half term the wand-weaving table has a queue and the hides have small children in them, which the birds notice before you do. Wellingtons rather than trainers — the paths are made up but the interesting parts are the edges. And it is worth saying plainly that the promise of no scares is the selling point here: a four-year-old who was upset by a scare zone somewhere else in this list will be perfectly happy in Barnes.",
  },
  {
    slug: "howl-o-ween-chessington-2026",
    createdAt: "2026-09-12T20:16:15+04:00",
    updatedAt: "2026-09-12T20:16:15+04:00",
    site: "lnd",
    image: "/covers/howl-o-ween-chessington-2026.jpg",
    imageAlt: "A white paper fairground wheel with a red hub, a crouching gargoyle on a plinth to its left and a row of small orange and cream pumpkins along the foot of the frame",
    imageKind: "generated",
    imageWidth: 1536,
    imageHeight: 864,
    title: "Howl'o'ween at Chessington 2026",
    summary:
      "A theme park Halloween inside the London boundary: selected dates from 3 October to 1 November in Kingston upon Thames, with new shows, a vampire's lair and rides at dusk, from £34 online.",
    start: "2026-10-03",
    end: "2026-11-01",
    utcOffset: "+00:00",
    venue: "Chessington World of Adventures Resort",
    city: "London",
    country: "United Kingdom",
    geo: {
      name: "Chessington World of Adventures Resort",
      lat: 51.349515,
      lng: -0.317273,
    },
    organizer: "Chessington World of Adventures Resort",
    category: "Halloween",
    ticket: {
      url: "https://www.chessington.com/tickets-passes/day-tickets/",
      label: "Day tickets",
    },
    tickets: { priceFrom: 34, currency: "GBP" },
    source: {
      name: "Chessington World of Adventures Resort",
      url: "https://www.chessington.com/explore/events/halloween/",
      verifiedOn: "2026-09-12",
    },
    body: [
      "Everything else on this list is a palace, a garden or a museum doing Halloween for a week. This is a theme park doing it for a month, and it is in a London borough — the KT postcode misleads, but Chessington sits inside Kingston upon Thames.",
      "## The details",
      "<strong>Selected dates from 3 October to 1 November 2026</strong>: the weekends of <strong>3–4</strong> and <strong>10–11 October</strong>, then <strong>every day from 17 October to 1 November</strong>. <strong>Day tickets from £34</strong> booked online against <strong>£66</strong> at the gate, which is the largest gap between advance and walk-up on this site. Under 90cm goes free. One ticket covers the theme park, the zoo, the SEA LIFE aquarium and the Howl'o'ween programme.",
      "## What is in it",
      "Four shows and a scare zone, as the resort lists them. Dr Frankenfun's Haunted House Party and Barnyard Boogie are the pitched-at-children end; Rising Flame: Shadows of the Tomb is the set-piece, with fire and a summoned mummy; Stone Watchers: Vampire's Lair is the scare zone, where the gargoyles wake if you are heard. Rides run at dusk, which is the part regular visitors come back for — Mandrill Mayhem, Vampire and Room on the Broom in the dark are a different ride from the same ride in July.",
      "## One thing to watch",
      "Enchanted Hollow: Trick or Treat, the underground trick-or-treat village, is an <strong>optional extra</strong> rather than part of the ticket, and at the time of writing the resort says its tickets are still to come. Anyone buying a day ticket on the strength of that particular attraction should check it is on sale for their date first.",
      "## Getting there",
      "Chessington South is a ten-minute walk from the gate and runs twice an hour from Waterloo; the resort is off the A243 at Malden Rushett, and parking is charged separately.",
    ],
    faq: [
      {
        q: "When is Howl'o'ween at Chessington in 2026?",
        a: "Selected dates from 3 October to 1 November 2026: the weekends of 3–4 and 10–11 October, then every day from 17 October to 1 November.",
      },
      {
        q: "How much is a ticket?",
        a: "The resort lists day tickets from £34 online and £66 as the walk-up price. Under 90cm goes free, and the ticket includes the theme park, the zoo, SEA LIFE and the Howl'o'ween programme.",
      },
      {
        q: "Is Chessington in London?",
        a: "Yes — the resort is in the Royal Borough of Kingston upon Thames, at the far south-western edge of Greater London.",
      },
      {
        q: "Is Enchanted Hollow included?",
        a: "No. The resort lists Enchanted Hollow: Trick or Treat as an optional extra bought alongside a Howl'o'ween ticket or an annual pass, and says tickets will be available later.",
      },
    ],
    expertise:
      "The two October weekends are the ones to take if you can. From 17 October the park is open every day and every day is half term, and a theme park at capacity spends its afternoon in queues no seasonal show improves. Book the first entry slot, do the rides that matter before eleven, and keep the shows for the afternoon when standing still is welcome. And the £32 between the online price and the gate price is the plainest saving anywhere on this site: nobody should be paying £66 at a window in October.",
  },
];
