import type { EventItem } from "../types.ts";

export const items: EventItem[] = [
  {
    slug: "festival-internacional-cervantino-2026",
    createdAt: "2026-08-30T11:52:01+04:00",
    updatedAt: "2026-09-06T08:48:11+04:00",
    site: "mxo",
    image: "/covers/festival-internacional-cervantino-2026.jpg",
    imageAlt: "Tres arcos de papel de distinto tamaño anidados uno dentro de otro, en terracota y crema sobre un fondo verde",
    imageKind: "generated",
    imageWidth: 1536,
    imageHeight: 864,
    title: "Festival Internacional Cervantino 2026",
    summary:
      "La 54ª edición va del 3 al 18 de octubre en Guanajuato, con Francia como país invitado de honor y programación en seis ciudades del estado.",
    start: "2026-10-03",
    end: "2026-10-18",
    utcOffset: "-06:00",
    city: "Guanajuato",
    venue: "Teatro Juárez, Teatro Principal, Teatro Cervantes y otras sedes de Guanajuato",
    category: "Festivales",
    organizer: "Secretaría de Cultura",
    source: {
      name: "Festival Internacional Cervantino",
      url: "https://festivalcervantino.gob.mx/",
      verifiedOn: "2026-09-03",
    },
    body: [
      "Una ciudad de callejones y escalinatas, construida sobre un cauce de río, se convierte durante quince días de octubre en el escenario más incómodo y más bello del país.",
      "## Fechas del Festival Internacional Cervantino 2026",
      "La <strong>54ª edición</strong> del Festival Internacional Cervantino va del <strong>3 al 18 de octubre de 2026</strong>, organizada por la <strong>Secretaría de Cultura</strong>.",
      "## El país invitado",
      "<strong>Francia</strong> es el país invitado de honor de esta edición.",
      "## Dónde ocurre",
      "En la ciudad de Guanajuato, las sedes incluyen el <strong>Teatro Juárez</strong>, el <strong>Teatro Principal</strong>, el <strong>Teatro Cervantes</strong>, la <strong>Explanada de la Alhóndiga de Granaditas</strong>, la <strong>Plaza San Fernando</strong>, la <strong>Plaza Allende</strong>, <strong>Los Pastitos</strong> y la <strong>Universidad de Guanajuato</strong>. La programación se extiende además a <strong>León</strong>, <strong>San Miguel de Allende</strong>, <strong>Salamanca</strong>, <strong>Silao</strong> y <strong>Purísima del Rincón</strong>.",
      "## Algunos nombres del programa",
      "<strong>Mondo Cane</strong>, el proyecto de Mike Patton; <strong>«FuturesPast»</strong> del <strong>Bangarra Dance Theatre</strong>; <strong>«Carmen»</strong> de la <strong>Compañía Antonio Gades</strong>; y <strong>«Tosca»</strong> de Puccini a cargo de la <strong>Compañía Nacional de Ópera</strong>.",
      "## Boletos del Cervantino 2026",
      "La venta es a través de <strong>Ticketmaster</strong>.",
    ],
    expertise:
      "El Cervantino tiene dos festivales dentro: el de sala, con boleto y horario, y el de calle, que ocurre en plazas y explanadas sin costo. Quien viaja por el primero suele descubrir que el segundo le ocupó más horas. La restricción real es el hospedaje — Guanajuato es una ciudad pequeña y las dos semanas de octubre son las de mayor ocupación del año, así que la reserva se hace antes que la compra de boletos, no después. Sobre el traslado: la traza de callejones y escaleras hace que las distancias en el mapa engañen; entre dos sedes que parecen contiguas puede haber una subida considerable, y encadenar dos funciones con media hora de margen rara vez sale bien. Las sedes fuera de la capital — León, San Miguel, Salamanca — piden coche o autobús foráneo y prácticamente un día entero.",
  },

  {
    slug: "fil-guadalajara-2026",
    createdAt: "2026-08-30T23:36:45+04:00",
    updatedAt: "2026-09-06T08:48:11+04:00",
    featured: 1,
    site: "mxo",
    image: "/covers/fil-guadalajara-2026.jpg",
    imageAlt: "Un arco de papel verde con una puerta iluminada debajo",
    imageKind: "generated",
    imageWidth: 1536,
    imageHeight: 864,
    title: "FIL Guadalajara 2026: 40 años, Italia invitada",
    summary:
      "La Feria Internacional del Libro de Guadalajara cumple 40 ediciones del 28 de noviembre al 6 de diciembre, con Italia como país Invitado de Honor y 61 autores italianos en Expo Guadalajara.",
    start: "2026-11-28",
    end: "2026-12-06",
    utcOffset: "-06:00",
    city: "Guadalajara",
    // City and state trimmed off the end: the card prints "venue · city" and
    // this one came out "…Verde Valle, Guadalajara, Jalisco · Guadalajara".
    venue: "Expo Guadalajara, Avenida Mariano Otero 1499, Colonia Verde Valle",
    geo: { name: "Expo Guadalajara", lat: 20.654251, lng: -103.391867 },
    category: "Ferias",
    organizer: "Universidad de Guadalajara",
    source: {
      name: "FIL Guadalajara",
      url: "https://www.fil.com.mx/",
      verifiedOn: "2026-08-30",
    },
    programme: [
      {
        heading: "Pabellón de Italia",
        text: "El corazón del programa del país Invitado de Honor: más de treinta editoriales italianas exponen ahí, y hay una librería con venta de libros de autores italianos en su lengua original y en traducción al español.",
      },
      {
        heading: "61 autoras y autores italianos",
        text: "De la narrativa, el ensayo, la ilustración, el cómic y la literatura infantil y juvenil. Entre ellos Alessandro Baricco, Viola Ardone, Stefania Auci, Claudia Durastanti, Milo Manara, Francesca Melandri, Veronica Raimo y Emanuele Coccia.",
      },
      {
        heading: "Diez exposiciones por toda la ciudad",
        text: "La participación italiana no se queda en el recinto: exposiciones, conciertos, cine, gastronomía e intercambios académicos se extienden por Guadalajara durante los nueve días.",
      },
      {
        heading: "Premio de Literaturas Indígenas de América",
        text: "Se entrega el 4 de diciembre a las 16:00 al poeta guatemalteco garífuna Wingston González por Un poquito más allá: 300 mil pesos y una escultura del artista jalisciense Camilo Ramírez.",
      },
      {
        heading: "Venta nocturna del viernes 4",
        text: "Ese viernes la Feria extiende su horario hasta las 23:00 horas; el cierre de ventas es a esa hora y el recinto cierra a las 23:30.",
      },
    ],
    body: [
      "La <strong>Feria Internacional del Libro de Guadalajara</strong> llega a su <strong>edición 40</strong> del <strong>28 de noviembre al 6 de diciembre de 2026</strong> en <strong>Expo Guadalajara</strong>. El país Invitado de Honor es <strong>Italia</strong>, que vuelve a ocupar ese lugar <strong>dieciocho años</strong> después de su última participación",
      "## Una feria de negocios a la que el público entra",
      "Es el rasgo que la distingue de Fráncfort, de Bolonia y de casi cualquier otra feria grande del mundo: la FIL fue fundada por la <strong>Universidad de Guadalajara</strong> como una feria para profesionales <em>donde el público es bienvenido</em>. Los agentes literarios negocian derechos de traducción en los mismos pasillos por los que camina alguien que vino a comprar una novela",
      "Las cifras de un año normal explican para qué sirve esa mezcla: más de <strong>900 escritores</strong>, <strong>18 mil profesionales</strong> del sector editorial, <strong>2 800 casas editoriales</strong> de más de <strong>60 países</strong> y un público cercano al <strong>millón de visitantes</strong>. En más de <strong>43 mil metros cuadrados</strong> se desarrollan más de <strong>tres mil actividades</strong> a lo largo de nueve días",
      "## Por qué importa que el invitado sea Italia",
      "El español es el <strong>principal mercado de exportación de derechos de traducción</strong> de la industria editorial italiana, y concentró el <strong>15 por ciento</strong> de sus ventas en 2024. No es un gesto diplomático: es la feria donde ese negocio se hace",
      "> Mostraremos en México la Italia de hoy y la vitalidad de su propuesta editorial mediante un programa que reunirá a más de 60 autoras y autores, jóvenes y consagrados, de la narrativa, el ensayo, la ilustración, el cómic y la literatura infantil y juvenil.\n— Innocenzo Cipolletta, presidente de la Asociación Italiana de Editores",
      "El programa italiano se articula alrededor de una frase de <strong>Umberto Eco</strong> — «el mundo nos habla como un gran libro» — a diez años de su muerte. Se presentó en julio en el Palacio de la Farnesina, en Roma, con el ministro de Asuntos Exteriores Antonio Tajani, el presidente de la FIL José Trinidad Padilla López y la directora general Marisol Schulz Manaut",
      "## Cuándo ir, si se puede elegir",
      "Los dos fines de semana son los días llenos. Entre semana el recinto respira, y es cuando conviene ir si el plan es mirar mesas y no sólo llegar a una presentación concreta. El <strong>viernes 4 de diciembre</strong> hay <strong>venta nocturna</strong>: la Feria abre hasta las <strong>23:00</strong> horas, con cierre del recinto a las 23:30",
      "## Cómo llegar a Expo Guadalajara",
      "Expo Guadalajara está en <strong>Avenida Mariano Otero 1499</strong>, colonia Verde Valle. Es el recinto ferial de la ciudad, al sur del centro, sobre una avenida por la que pasan varias rutas del transporte urbano; en los días de FIL el tránsito alrededor es el peor del año y conviene llegar sin coche",
    ],
    expertise:
      "Nueve días y tres mil actividades no se recorren improvisando. Lo que funciona es elegir dos o tres presentaciones del programa oficial, anotarlas con hora y salón, y dejar el resto del día para caminar los pasillos: el hallazgo en la FIL casi siempre es una editorial pequeña que uno no buscaba, no el autor famoso al que no se alcanzó a entrar",
  },
  {
    slug: "filij-2026",
    createdAt: "2026-08-30T11:52:01+04:00",
    updatedAt: "2026-09-06T14:02:45+04:00",
    featured: 2,
    site: "mxo",
    image: "/covers/filij-2026.jpg",
    imageAlt: "Barcos de papel y confeti sobre fondo verde",
    imageKind: "generated",
    imageWidth: 1536,
    imageHeight: 864,
    title: "FILIJ 2026: el libro infantil y juvenil",
    summary:
      "La 44 Feria Internacional del Libro Infantil y Juvenil ocupa el CENART del 13 al 22 de noviembre. Entrada gratuita, diez días, y convocatoria abierta para visitas escolares.",
    start: "2026-11-13",
    end: "2026-11-22",
    startTime: "09:00",
    endTime: "19:00",
    utcOffset: "-06:00",
    city: "Ciudad de México",
    venue: "Centro Nacional de las Artes, Río Churubusco 79, Country Club Churubusco, Coyoacán",
    geo: { name: "Centro Nacional de las Artes", lat: 19.355607, lng: -99.137182 },
    category: "Ferias",
    organizer: "Secretaría de Cultura",
    tickets: { priceFrom: 0 },
    source: {
      name: "Excélsior",
      url: "https://www.excelsior.com.mx/cultura/filij-2026-regresa-cenart-con-entrada-gratuita-fechas",
      verifiedOn: "2026-08-30",
    },
    body: [
      "La <strong>44 edición</strong> de la Feria Internacional del Libro Infantil y Juvenil se realiza del <strong>13 al 22 de noviembre de 2026</strong> en el <strong>Centro Nacional de las Artes</strong>, según el Fondo de Cultura Económica. La <strong>entrada es gratuita</strong>",
      "## Diez días, no un fin de semana",
      "La duración es el rasgo que distingue a la FILIJ de casi cualquier otra feria del libro infantil: dos fines de semana completos y la semana entre ellos. Eso permite dos tipos de visita muy distintos — la familiar de sábado, ruidosa y llena, y la de un martes por la tarde, en la que un niño puede quedarse veinte minutos en una mesa sin que nadie lo apure",
      "## Qué hay adentro",
      "Editoriales, escritores e ilustradores, con oferta para todas las edades: del cuento ilustrado a la novela juvenil y el libro informativo",
      "Alrededor de los libros hay programación cultural: cuentacuentos, talleres creativos, presentaciones, teatro, música y danza. Es gratuita como el resto de la feria, y es la parte por la que conviene consultar el programa antes de ir en lugar de improvisar",
      "## Escuelas",
      "El FCE abrió <strong>convocatoria para visitas escolares</strong>; los detalles se publican en sus canales oficiales. Es el mecanismo que lleva a la feria a los niños que no vendrían en fin de semana con su familia, y es la razón de que la sede se llene entre semana por la mañana",
      "## Cómo llegar al CENART",
      "El CENART está en <strong>Avenida Río Churubusco 79</strong>, colonia Country Club Churubusco, alcaldía Coyoacán. Las estaciones de Metro más cercanas son <strong>General Anaya</strong> (Línea 2) y <strong>Ermita</strong> (Línea 12), a <strong>8 o 10 minutos caminando</strong> desde cualquiera de las dos",
    ],
    expertise:
      "Diez días de feria gratuita se sienten como una invitación a ir cuando se pueda, y así es como no se va. Vale más elegir una fecha entre semana por la tarde y anotarla: es cuando la feria está abierta, tiene programa y no tiene ni grupos escolares ni multitud de fin de semana",
  },

  {
    slug: "fiestas-de-octubre-2026",
    createdAt: "2026-09-08T16:29:32+04:00",
    updatedAt: "2026-09-08T16:34:13+04:00",
    site: "mxo",
    image: "/covers/fiestas-de-octubre-2026.jpg",
    imageAlt: "Una rueda de la fortuna naranja y crema, de líneas planas, sobre un fondo verde oscuro",
    imageKind: "generated",
    imageWidth: 1536,
    imageHeight: 864,
    title: "Fiestas de Octubre 2026",
    summary:
      "Un mes completo de feria en Zapopan, en el occidente de México, del 2 de octubre al 1 de noviembre: Foro Principal con conciertos incluidos en la entrada general y Palenque con boleto aparte.",
    start: "2026-10-02",
    end: "2026-11-01",
    utcOffset: "-06:00",
    venue: "Auditorio Benito Juárez, Zapopan",
    city: "Guadalajara",
    country: "México",
    organizer: "Patronato de las Fiestas de Octubre",
    category: "Feria",
    source: {
      name: "El Informador",
      url: "https://www.informador.mx/jalisco/fiestas-de-octubre-2026-cuando-empiezan-cuando-terminan-y-que-artistas-se-presentaran-20260723-0108.html",
      verifiedOn: "2026-09-08",
    },
    body: [
      "Treinta y un días seguidos. Ninguna otra feria del país se sostiene tanto tiempo en un mismo recinto, y esa duración es la que explica su programación.",
      "## Fechas de las Fiestas de Octubre 2026",
      "Las actividades <strong>comienzan el 2 de octubre y concluyen el 1 de noviembre de 2026</strong>, en las instalaciones del <strong>Auditorio Benito Juárez</strong>, en el municipio de <strong>Zapopan</strong>, Jalisco.",
      "## Los dos escenarios",
      "El <strong>Foro Principal</strong> presenta conciertos <strong>incluidos en la entrada general</strong>. El <strong>Palenque</strong> se vende por separado; entre los nombres confirmados están <strong>Alejandro Fernández</strong>, <strong>Grupo Firme</strong>, <strong>Banda MS</strong>, <strong>María José</strong>, <strong>Kany García</strong>, <strong>Jorge Medina</strong> y <strong>Josi Cuen</strong>.",
      "## Lo demás",
      "Juegos mecánicos, áreas gastronómicas y entretenimiento familiar. La venta de boletos <strong>inició el 27 de julio</strong> a través de mipase.net y de puntos físicos autorizados en la ciudad.",
    ],
    expertise:
      "La diferencia entre los dos escenarios es la que decide el presupuesto de la visita y casi nadie la explica al comprar: el Foro Principal entra con el boleto general, así que un cartel de nombres grandes puede salir por el precio de la entrada, mientras que el Palenque es un boleto aparte por función. Para quien viaja desde fuera de Jalisco, la lectura práctica es que un mes de feria significa que casi cualquier fin de semana de octubre sirve, y que los caros son los dos primeros y el último: entre semana, a mitad de mes, el mismo recinto se recorre sin fila.",
  },
  {
    slug: "festival-de-vida-y-muerte-2026",
    createdAt: "2026-09-08T21:23:08+04:00",
    updatedAt: "2026-09-08T21:59:53+04:00",
    site: "mxo",
    image: "/covers/festival-de-vida-y-muerte-2026.jpg",
    imageAlt: "Una flor de cempas\u00fachil de papel, de p\u00e9talos naranjas y centro oscuro, sola sobre un fondo azul verdoso",
    imageKind: "generated",
    imageWidth: 1536,
    imageHeight: 864,
    title: "Festival de Vida y Muerte 2026",
    summary:
      "La edici\u00f3n n\u00famero 20 del festival de Xcaret, del 30 de octubre al 2 de noviembre, con Guanajuato como estado invitado: cuatro d\u00edas de altares, m\u00fasica y representaciones en la Riviera Maya.",
    start: "2026-10-30",
    end: "2026-11-02",
    utcOffset: "-05:00",
    venue: "Parque Xcaret",
    city: "Riviera Maya",
    country: "M\u00e9xico",
    organizer: "Xcaret",
    category: "Día de Muertos",
    source: {
      name: "Festival de Vida y Muerte",
      url: "https://festivaldevidaymuerte.com/",
      verifiedOn: "2026-09-08",
    },
    ticket: { url: "https://festivaldevidaymuerte.com/", label: "Boletos" },
    body: [
      "El D\u00eda de Muertos se celebra el 1 y el 2 de noviembre. Este festival dura el doble y empieza dos d\u00edas antes.",
      "## Fechas del Festival de Vida y Muerte 2026",
      "<strong>Del 30 de octubre al 2 de noviembre de 2026</strong>, en el <strong>Parque Xcaret</strong>, en la Riviera Maya, Quintana Roo. Es la <strong>edici\u00f3n n\u00famero 20</strong>.",
      "## El estado invitado",
      "Cada a\u00f1o el festival invita a un estado a llevar su propia forma de celebrar. En 2026 es <strong>Guanajuato</strong>.",
      "## Qu\u00e9 hay dentro",
      "M\u00fasica del D\u00eda de Muertos \u2014 mariachi, estudiantina, sones, huapango arribe\u00f1o y m\u00fasica tradicional de la Pen\u00ednsula de Yucat\u00e1n \u2014 adem\u00e1s de representaciones y un <strong>Concierto de Gala</strong> el <strong>31 de octubre</strong>, que se compra aparte del acceso al parque.",
    ],
    faq: [
      {
        q: "\u00bfCu\u00e1ndo es el Festival de Vida y Muerte 2026?",
        a: "<strong>Del 30 de octubre al 2 de noviembre de 2026</strong>, en el Parque Xcaret.",
      },
      {
        q: "\u00bfCu\u00e1l es el estado invitado este a\u00f1o?",
        a: "<strong>Guanajuato</strong>. El festival invita cada edici\u00f3n a un estado distinto.",
      },
      {
        q: "\u00bfEl Concierto de Gala entra con el boleto del parque?",
        a: "No. El organizador lo vende como acceso aparte, para la noche del <strong>31 de octubre</strong>.",
      },
    ],
    expertise:
      "La confusi\u00f3n m\u00e1s cara aqu\u00ed es tratarlo como una fiesta de una noche. Son cuatro d\u00edas dentro de un parque que ya de por s\u00ed toma una jornada completa, y el festival ocupa la tarde y la noche; quien llega el 1 de noviembre por la ma\u00f1ana ve el parque, no el festival. La otra decisi\u00f3n que conviene tomar antes de viajar es la del concierto: se vende por separado y cae en la v\u00edspera, as\u00ed que define en qu\u00e9 noche conviene estar ah\u00ed.",
  },
  {
    slug: "noche-de-muertos-michoacan-2026",
    createdAt: "2026-09-08T21:39:47+04:00",
    updatedAt: "2026-09-08T21:59:53+04:00",
    site: "mxo",
    image: "/covers/noche-de-muertos-michoacan-2026.jpg",
    imageAlt: "Seis velas de papel color crema, con llamas naranjas, alineadas sobre un fondo azul verdoso y separadas de manera desigual",
    imageKind: "generated",
    imageWidth: 1536,
    imageHeight: 864,
    title: "Noche de Muertos en Michoacán 2026",
    summary:
      "La noche del 1 de noviembre, en Janitzio, Tzintzuntzan y Jarácuaro: velas, cempasúchil y una procesión al panteón. Patrimonio de la Humanidad por la UNESCO desde 2008.",
    start: "2026-11-01",
    end: "2026-11-02",
    utcOffset: "-06:00",
    city: "Janitzio",
    country: "México",
    organizer: "Secretaría de Turismo de Michoacán",
    category: "Día de Muertos",
    source: {
      name: "Secretaría de Turismo de Michoacán",
      url: "https://visitmichoacan.com.mx/experiences/noche-de-muertos/",
      verifiedOn: "2026-09-08",
    },
    body: [
      "No es un espectáculo con horario de inicio. Es una noche entera en la que un pueblo entero está despierto en el panteón.",
      "## Fechas de la Noche de Muertos en Michoacán 2026",
      "La noche principal es la del <strong>1 de noviembre</strong>, y los días de la fiesta son el <strong>1 y el 2</strong>. Los altares se colocaban tradicionalmente el <strong>30 o el 31 de octubre</strong> y se retiraban el <strong>3 de noviembre</strong>; hoy muchas familias los montan antes y los quitan después, porque el trabajo que llevan lo pide.",
      "## Tres lugares, tres formas",
      "En la <strong>Isla de Janitzio</strong>, mujeres y niños caminan en procesión hacia el panteón y colocan junto a las tumbas los platillos favoritos de sus difuntos, en silencio y a la luz de las velas. En <strong>Tzintzuntzan</strong>, la ofrenda se expresa en artesanía: loza negra, loza blanca, ángeles de paja y tallados en madera. En <strong>Jarácuaro</strong>, los arcos de flores adornan cada barrio y la plaza principal, y la danza guía a las almas.",
      "## Por qué es Patrimonio de la Humanidad",
      "La UNESCO la nombró <strong>Patrimonio de la Humanidad el 4 de noviembre de 2008</strong>. El altar tiene raíz prehispánica: la ofrenda dedicada a Mictlantecuhtli, señor de los muertos, coincidía con lo que hoy es noviembre, y durante la Colonia esa coincidencia se fundió con la celebración cristiana.",
    ],
    faq: [
      {
        q: "¿Cuándo es la Noche de Muertos en Michoacán 2026?",
        a: "La noche del <strong>1 de noviembre</strong>. Los días de la fiesta son el <strong>1 y el 2 de noviembre</strong>.",
      },
      {
        q: "¿Dónde se celebra?",
        a: "En comunidades de la región: la <strong>Isla de Janitzio</strong>, <strong>Tzintzuntzan</strong> y <strong>Jarácuaro</strong>, cada una con su propia forma del rito.",
      },
      {
        q: "¿Cuándo se ponen las ofrendas?",
        a: "Tradicionalmente el <strong>30 o el 31 de octubre</strong>, y permanecían hasta el <strong>3 de noviembre</strong>. Hoy muchas familias las montan antes.",
      },
      {
        q: "¿Es Patrimonio de la Humanidad?",
        a: "Sí, declarada por la <strong>UNESCO el 4 de noviembre de 2008</strong>.",
      },
    ],
    expertise:
      "Conviene decidir antes de viajar qué se va a ver, porque no es lo mismo la isla que los pueblos de la ribera: Janitzio es la imagen que todo el mundo conoce y es también la que concentra a los visitantes, mientras que en Tzintzuntzan y Jarácuaro la noche se parece más a lo que la fecha es en una casa. Y hay una cortesía que ninguna guía imprime en la portada: el panteón esa noche no es un escenario, es la sala de una familia. Se entra como se entra a una casa ajena.",
  },
  {
    slug: "festival-de-calaveras-2026",
    createdAt: "2026-09-08T21:59:53+04:00",
    updatedAt: "2026-09-08T21:59:53+04:00",
    site: "mxo",
    image: "/covers/festival-de-calaveras-2026.jpg",
    imageAlt: "Una calavera de papel color crema con sombrero naranja de ala ancha, recortada en formas planas, a la derecha de un fondo verde oscuro",
    imageKind: "generated",
    imageWidth: 1536,
    imageHeight: 864,
    title: "Festival de Calaveras 2026",
    summary:
      "Diecisiete días en Aguascalientes, del 30 de octubre al 15 de noviembre: desfiles, altares monumentales y exposiciones en la tierra de José Guadalupe Posada, el grabador que inventó a la Catrina.",
    start: "2026-10-30",
    end: "2026-11-15",
    utcOffset: "-06:00",
    city: "Aguascalientes",
    country: "México",
    organizer: "Gobierno de Aguascalientes",
    category: "Día de Muertos",
    source: {
      name: "Agenda difundida por medios de Aguascalientes; el sitio del festival no está en línea",
      verifiedOn: "2026-09-08",
    },
    body: [
      "La Catrina no es folclor anónimo: tiene autor, y el autor era de aquí. Aguascalientes celebra a sus muertos celebrando al hombre que los dibujó.",
      "## Fechas del Festival de Calaveras 2026",
      "<strong>Del 30 de octubre al 15 de noviembre de 2026</strong>. Es decir, más de dos semanas: el festival empieza antes de la fiesta y sigue mucho después del 2 de noviembre.",
      "## Dónde es el Festival de Calaveras",
      "Las actividades se reparten por la ciudad, sobre todo en la <strong>Isla San Marcos</strong>, el <strong>Centro Histórico</strong> y varios recintos culturales.",
      "## Qué hay dentro",
      "Desfiles, altares monumentales, exposiciones, danza, teatro, conciertos, actividades infantiles, recorridos, muestras gastronómicas y eventos deportivos.",
      "## Posada",
      "El festival está inspirado en el legado de <strong>José Guadalupe Posada</strong>, grabador aguascalentense y creador de la Catrina.",
      "## De dónde salen estas fechas",
      "Del calendario que difunden los medios locales. El sitio propio del festival no responde en este momento, así que aquí no hay programa por día: cuando el organizador publique el suyo, se anota.",
    ],
    faq: [
      {
        q: "¿Cuándo es el Festival de Calaveras 2026?",
        a: "<strong>Del 30 de octubre al 15 de noviembre de 2026</strong>, en la ciudad de Aguascalientes.",
      },
      {
        q: "¿Dónde son las actividades?",
        a: "Principalmente en la <strong>Isla San Marcos</strong> y el <strong>Centro Histórico</strong>, además de otros recintos culturales.",
      },
      {
        q: "¿Qué tiene que ver Posada?",
        a: "El festival honra a <strong>José Guadalupe Posada</strong>, grabador nacido en el estado y autor de la Catrina.",
      },
      {
        q: "¿Hay programa día por día?",
        a: "Todavía no publicado por el organizador. Estas fechas provienen del calendario que difunden los medios de Aguascalientes.",
      },
    ],
    expertise:
      "Diecisiete días cambian la manera de planear el viaje: quien va por el ambiente de la fecha quiere el tramo del 31 de octubre al 2 de noviembre, y quien va por el festival — exposiciones, teatro, conciertos — encuentra la segunda semana más barata y más tranquila, con la ciudad ya vacía de visitantes. Son dos viajes distintos con el mismo nombre.",
  },
  {
    slug: "xantolo-huasteca-potosina-2026",
    createdAt: "2026-09-08T21:59:53+04:00",
    updatedAt: "2026-09-08T21:59:53+04:00",
    site: "mxo",
    image: "/covers/xantolo-huasteca-potosina-2026.jpg",
    imageAlt: "Tres máscaras ovaladas de papel — naranja, roja y crema — superpuestas en fila sobre un fondo verde oscuro",
    imageKind: "generated",
    imageWidth: 1536,
    imageHeight: 864,
    title: "Xantolo 2026 en la Huasteca Potosina",
    summary:
      "Del 30 de octubre al 2 de noviembre, en Ciudad Valles, Tamazunchale y Aquismón: comparsas enmascaradas, arcos de cempasúchil y danzas tének y nahuas.",
    start: "2026-10-30",
    end: "2026-11-02",
    utcOffset: "-06:00",
    city: "Ciudad Valles",
    country: "México",
    category: "Día de Muertos",
    source: {
      name: "Prensa y guías de viaje de San Luis Potosí; la fiesta no tiene sitio propio",
      verifiedOn: "2026-09-08",
    },
    body: [
      "La palabra viene del latín. <em>Xantolo</em> es <em>sanctorum</em>, «de todos los santos», dicho durante siglos en boca nahua y tének hasta quedar así.",
      "## Fechas del Xantolo 2026 en la Huasteca Potosina",
      "<strong>Del 30 de octubre al 2 de noviembre de 2026</strong>. En muchas comunidades los preparativos empiezan semanas antes.",
      "## Dónde es el Xantolo",
      "<strong>Ciudad Valles</strong>, <strong>Tamazunchale</strong> y <strong>Aquismón</strong> concentran los principales festejos y desfiles.",
      "## Qué se ve",
      "Altares, arcos de cempasúchil, comparsas enmascaradas y danzas tradicionales tének y nahuas. La máscara es lo que distingue al Xantolo de casi cualquier otra celebración de la fecha en el país.",
      "## De dónde salen estas fechas",
      "De la prensa y las guías de San Luis Potosí. El Xantolo no es un evento con organizador ni sitio propio: es una fiesta comunitaria, y el calendario que se publica describe lo que hacen los pueblos, no un programa oficial.",
    ],
    faq: [
      {
        q: "¿Cuándo es el Xantolo 2026?",
        a: "<strong>Del 30 de octubre al 2 de noviembre de 2026</strong> en la Huasteca Potosina.",
      },
      {
        q: "¿Qué significa Xantolo?",
        a: "Viene del latín <em>sanctorum</em>, «de todos los santos», y en la Huasteca quedó como sinónimo de Fiesta de Muertos.",
      },
      {
        q: "¿A qué municipios ir?",
        a: "<strong>Ciudad Valles</strong>, <strong>Tamazunchale</strong> y <strong>Aquismón</strong> son los que concentran desfiles y festejos.",
      },
      {
        q: "¿Hay un programa oficial?",
        a: "No. Es una celebración comunitaria sin organizador único, y los horarios los fija cada pueblo.",
      },
    ],
    expertise:
      "La diferencia práctica con las celebraciones que se anuncian con cartel es que aquí no hay hora de inicio ni recinto: las comparsas salen cuando salen y recorren las calles del pueblo, así que el plan razonable es quedarse en un municipio y no intentar tres en una noche. La Huasteca es grande y las carreteras entre esos tres puntos no son cortas.",
  },

  {
    slug: "fil-monterrey-2026",
    createdAt: "2026-09-12T17:21:29+04:00",
    updatedAt: "2026-09-12T17:21:29+04:00",
    site: "mxo",
    title: "FIL Monterrey 2026: El Colegio Nacional",
    summary:
      "La feria del libro del norte de México va del 10 al 18 de octubre en Cintermex, Monterrey: entrada gratuita y El Colegio Nacional como Invitado de Honor.",
    start: "2026-10-10",
    end: "2026-10-18",
    utcOffset: "-06:00",
    city: "Monterrey",
    venue: "Cintermex",
    geo: { name: "Cintermex", lat: 25.678298, lng: -100.288060 },
    category: "Ferias",
    organizer: "Feria Internacional del Libro Monterrey",
    tickets: { priceFrom: 0 },
    source: {
      name: "ABC Noticias",
      url: "https://abcnoticias.mx/local/2026/8/18/confirman-fecha-para-la-feria-del-libro-monterrey-2026-en-cintermex-290570.html",
      verifiedOn: "2026-09-12",
    },
    body: [
      "Un premio Nobel, un Pulitzer y dos Princesa de Asturias en la misma feria, y la entrada no cuesta nada. Esa es la aritmética rara de Monterrey en octubre.",
      "## Fechas de la FIL Monterrey 2026",
      "La <strong>Feria Internacional del Libro Monterrey</strong> se realiza del <strong>10 al 18 de octubre de 2026</strong> en <strong>Cintermex</strong>, con <strong>acceso gratuito</strong>. Son nueve días.",
      "## El invitado de honor",
      "<strong>El Colegio Nacional</strong> es el Invitado de Honor de esta edición y lleva a Monterrey un programa con escritores, científicos, artistas y humanistas: <strong>Cristina Rivera Garza</strong>, <strong>Juan Villoro</strong>, <strong>Enrique Krauze</strong>, <strong>Leonardo López Luján</strong>, <strong>Gabriela Ortiz</strong>, <strong>Eduardo Matos Moctezuma</strong> y <strong>José Ramón Cossío</strong>, en conferencias, diálogos y presentaciones.",
      "## Quién viene de fuera",
      "<strong>Jean-Marie Gustave Le Clézio</strong>, Premio Nobel de Literatura; <strong>Emmanuel Carrère</strong> y <strong>Leonardo Padura</strong>, ambos Premio Princesa de Asturias; <strong>Rita Dove</strong>, Pulitzer de Poesía; <strong>Alberto Manguel</strong>, Premio Formentor; y la escritora nicaragüense <strong>Gioconda Belli</strong>. Manguel ofrece el discurso inaugural.",
      "## Lo nuevo de esta edición",
      "<strong>Sentir y pensar nuestro tiempo</strong> es un encuentro dedicado a la filosofía contemporánea, con <strong>Darío Sztajnszrajber</strong>, <strong>Hugo Mujica</strong>, <strong>Laura Quintana</strong> y <strong>Valeria Campos Salvaterra</strong>, sobre el amor, el cuerpo, la violencia, la espiritualidad y los retos éticos actuales.",
      "## Para niñas, niños y jóvenes",
      "Talleres y experiencias interactivas sobre lectura, salud mental, pensamiento crítico y medio ambiente, además del <strong>Congreso de Literatura Infantil y Juvenil</strong>, encuentros de promotores de lectura y bibliotecarios, y <strong>Lucha Libro</strong>, una competencia de improvisación literaria.",
      "## Quién organiza",
      "La dirige <strong>Henoc de Santiago</strong> y la preside <strong>Carmen Junco</strong>. El <strong>Tecnológico de Monterrey</strong> desarrolla por su cuenta más de cien actividades académicas y culturales dentro de la feria.",
    ],
    expertise:
      "La entrada libre cambia cómo se planea la visita: no hay boleto que obligue a un día concreto, así que conviene elegir por programa y no por fecha. Las presentaciones con nombres internacionales son las que llenan sala, y en una feria sin control de aforo por boleto el lugar se gana llegando antes, no comprando antes. Cintermex está dentro del Parque Fundidora, lo que significa que la caminata desde el estacionamiento es parte del plan y que se puede combinar la feria con el parque en la misma salida — dos cosas que rara vez coinciden en un recinto ferial.",
  },

  {
    slug: "futur-festival-mexico-2026",
    createdAt: "2026-09-12T17:21:29+04:00",
    updatedAt: "2026-09-12T17:21:29+04:00",
    site: "mxo",
    title: "Futur Festival México 2026, el primero fuera de Europa",
    summary:
      "El festival de techno de Turín abre su primera edición americana en México el 13 y 14 de noviembre, en el Parque Fundidora de Monterrey, con un escenario distinto cada día.",
    start: "2026-11-13",
    end: "2026-11-14",
    utcOffset: "-06:00",
    city: "Monterrey",
    venue: "Parque Fundidora",
    geo: { name: "Parque Fundidora", lat: 25.678225, lng: -100.289574 },
    category: "Festivales",
    organizer: "Movement Entertainment",
    ticket: {
      url: "https://cart.ingresse.com/a541874a-33c6-44fa-b9cf-df3fc9d2a1cf/tickets",
      label: "Boletos en Ingresse",
    },
    tickets: { priceFrom: 1610, currency: "MXN" },
    source: {
      name: "Futur Festival México",
      url: "https://futurfestival.mx/",
      verifiedOn: "2026-09-12",
    },
    body: [
      "Un festival que lleva quince años ocupando una acería reconvertida en Turín eligió, para su primera salida del continente, otra acería reconvertida. La coincidencia no es coincidencia.",
      "## Las fechas y el lugar",
      "<strong>Futur Festival México</strong> se realiza el <strong>viernes 13</strong> y el <strong>sábado 14 de noviembre de 2026</strong> en el <strong>Parque Fundidora</strong> de Monterrey. Es la primera edición del festival fuera de Europa.",
      "## Un escenario distinto cada día",
      "El <strong>primer día</strong> ocurre en la <strong>Nave Lewis</strong>; el <strong>segundo</strong>, en la <strong>Grúa y el Horno 3</strong>. Son tres piezas del patrimonio industrial de la antigua Fundidora de Fierro y Acero, y cada una impone su propia acústica y su propia escala.",
      "## Boletos del Futur Festival México",
      "Hay <strong>abono de dos días</strong> y boletos por día. Para el viernes, el General va de <strong>$1,610</strong> en Fase 1 a <strong>$2,300</strong> en la última fase; el Early Bird está agotado. Para el sábado hay además un boleto <strong>Sunset</strong> de <strong>$1,725</strong> con una condición: el ingreso es antes de las 5 de la tarde, y entrar después genera una penalización de <strong>$1,000</strong>. Las categorías VIP Premium y Backstage existen para ambos días. La venta es a través de <strong>Ingresse</strong>.",
      "## De dónde viene",
      "El festival es un proyecto de <strong>Movement Entertainment</strong>, la misma casa detrás del <strong>Kappa FuturFestival</strong> de Turín, que ocupa el Parco Dora y que en 2025 quedó en el <strong>sexto lugar</strong> de la lista Top 100 Festivals de la revista DJ Mag.",
      "## Lo que va con el boleto",
      "El festival destina <strong>5 dólares de cada entrada</strong> a la restauración de ecosistemas en la <strong>Sierra Madre Oriental</strong>.",
    ],
    expertise:
      "Los dos días no son intercambiables y el boleto tampoco: al cambiar de nave cambia el tipo de espacio, y quien compre un solo día está eligiendo un escenario, no solo una fecha. El boleto Sunset del sábado se ve barato hasta que se lee la letra chica — la penalización por entrar tarde cuesta más que la diferencia con el General, así que sale a cuenta únicamente para quien de verdad piensa llegar de día. Sobre noviembre en Monterrey: las noches ya enfrían y estas naves son de acero y concreto sin calefacción, de modo que la ropa que sobra a las siete de la tarde hace falta a la una de la mañana.",
  },

  {
    slug: "ficm-morelia-2026",
    createdAt: "2026-09-12T22:20:00+04:00",
    updatedAt: "2026-09-12T22:20:00+04:00",
    site: "mxo",
    image: "/covers/ficm-morelia-2026.jpg",
    imageAlt:
      "Una fila de arcos de papel en terracota que sostiene una larga tira oscura de fotogramas, sobre fondo verde bosque",
    imageKind: "generated",
    imageWidth: 1536,
    imageHeight: 864,
    title: "24° Festival Internacional de Cine de Morelia 2026",
    summary:
      "El festival de cine más importante de México va del 16 al 25 de octubre en Morelia, con 96 películas en competencia y una acreditación de $600 o $1,000 pesos que canjea 6 u 11 boletos.",
    start: "2026-10-16",
    end: "2026-10-25",
    utcOffset: "-06:00",
    venue: "Morelia",
    city: "Morelia",
    country: "México",
    geo: {
      name: "Teatro Mariano Matamoros, Morelia",
      lat: 19.70256,
      lng: -101.194426,
    },
    organizer: "Festival Internacional de Cine en Morelia A.C.",
    category: "Cine",
    tickets: { priceFrom: 600, priceTo: 1000, currency: "MXN" },
    ticket: {
      url: "https://moreliafilmfest.com/guia-acreditacion-ficm2026",
      label: "Guía de la acreditación",
    },
    source: {
      name: "Festival Internacional de Cine de Morelia",
      url: "https://moreliafilmfest.com/guia-acreditacion-ficm2026",
      verifiedOn: "2026-09-12",
    },
    body: [
      "Noventa y seis películas en competencia y diez días para verlas: el <strong>24° Festival Internacional de Cine de Morelia</strong> se realiza del <strong>16 al 25 de octubre de 2026</strong>, y la manera de entrar no es comprando boletos sueltos sino una credencial.",
      "## Qué es la acreditación",
      "La <strong>Acreditación #FICM2026</strong> es una credencial con fotografía que identifica a quien asiste y permite canjear boletos para funciones del festival. Está abierta tanto a la industria cinematográfica y sus acompañantes como al público cinéfilo: no hay que demostrar nada para adquirirla.",
      "## Los dos precios y lo que dan",
      "<strong>$600 pesos</strong>: <strong>6 boletos</strong> y <strong>3 descuentos</strong> del 40% en el combo de palomitas y refresco. <strong>$1,000 pesos</strong>: <strong>11 boletos</strong> y <strong>5 descuentos</strong> del mismo tipo. Las dos incluyen el <strong>programa de mano</strong> del 24° FICM y el acceso a la <strong>Fila de último minuto</strong>, que permite entrar <strong>gratis</strong> a funciones que todavía tengan cupo.",
      "## Cómo se canjean los boletos",
      "Los boletos se liberan <strong>48 horas antes de cada función</strong>, en línea o en taquilla, y el canje está sujeto a disponibilidad. Las taquillas son las de <strong>Cinépolis Morelia Centro</strong> y el <strong>Teatro Mariano Matamoros</strong>, de <strong>10:00 a 20:00</strong>; en línea, la página y la app de Cinépolis. Las sedes donde se pueden ver las funciones son <strong>Cinépolis Morelia Centro</strong>, <strong>Cinépolis VIP Las Américas</strong> y el <strong>Teatro Mariano Matamoros</strong>.",
      "## Lo que la acreditación no incluye",
      "El festival lo dice con todas sus letras: <strong>no</strong> da acceso a los espacios reservados para invitados oficiales, <strong>no</strong> da acceso al Hospitality Suite y <strong>no</strong> da acceso a las alfombras rojas ni a las ceremonias de inauguración y clausura.",
      "## Lo demás del programa",
      "A través de <strong>Morelia Pro</strong>, y con apoyo de <strong>Cinépolis</strong> y el <strong>Instituto Sundance</strong>, el festival presenta el <strong>Morelia:Sundance Laboratorio de Historias</strong>. La <strong>65ª Semana de la Crítica del Festival de Cannes</strong> tendrá presencia en esta edición, y corre además el <strong>IV Laboratorio de Desarrollo de Proyectos para Cineastas Indígenas y Afrodescendientes de México</strong>.",
    ],
    faq: [
      {
        q: "¿Cuándo es el FICM 2026?",
        a: "Del 16 al 25 de octubre de 2026, en Morelia, Michoacán. Es la 24ª edición.",
      },
      {
        q: "¿Cuánto cuesta la acreditación y qué incluye?",
        a: "Hay dos: la de $600 pesos da 6 boletos y 3 descuentos del 40% en el combo de palomitas y refresco; la de $1,000 pesos da 11 boletos y 5 descuentos. Ambas incluyen el programa de mano y el acceso a la Fila de último minuto, que permite entrar gratis a funciones con cupo disponible.",
      },
      {
        q: "¿Cómo se canjean los boletos?",
        a: "Se liberan 48 horas antes de cada función, sujetos a disponibilidad, en las taquillas de Cinépolis Morelia Centro y del Teatro Mariano Matamoros de 10:00 a 20:00, o en la página y la app de Cinépolis.",
      },
      {
        q: "¿En qué sedes son las funciones?",
        a: "Cinépolis Morelia Centro, Cinépolis VIP Las Américas y el Teatro Mariano Matamoros.",
      },
      {
        q: "¿La acreditación da acceso a las alfombras rojas?",
        a: "No. Tampoco a los espacios destinados únicamente a invitados oficiales, al Hospitality Suite ni a las ceremonias de inauguración y clausura.",
      },
      {
        q: "¿Cuántas películas hay en competencia?",
        a: "96 películas conforman la Selección Oficial de la 24ª edición.",
      },
    ],
    expertise:
      "La cuenta por boleto es obvia y engañosa a la vez: $100 por función con la acreditación de $600, contra unos $91 con la de $1,000. La diferencia real no está ahí, sino en la <strong>Fila de último minuto</strong>, que ambas incluyen y que no cuesta boleto — quien se organiza para llegar temprano a funciones con cupo puede ver bastante más de lo que compró. De modo que la acreditación barata no limita cuántas películas ves, sino cuántas puedes <em>reservar</em> con 48 horas de anticipación. Para diez días, la de $1,000 tiene sentido si piensas ver más de una función diaria en fin de semana, que es cuando la fila de último minuto deja de funcionar.",
  },

  {
    slug: "festival-internacional-del-globo-2026",
    createdAt: "2026-09-12T22:20:00+04:00",
    updatedAt: "2026-09-12T22:20:00+04:00",
    site: "mxo",
    image: "/covers/festival-internacional-del-globo-2026.jpg",
    imageAlt:
      "Globos aerostáticos de papel recortado en naranja y crema que descienden en diagonal por el cuadro, con una franja verde más clara al pie, sobre fondo verde bosque",
    imageKind: "generated",
    imageWidth: 1536,
    imageHeight: 864,
    title: "Festival Internacional del Globo 2026",
    summary:
      "Cuatro días en León, Guanajuato, del 13 al 16 de noviembre: más de 200 globos de más de 25 países despegan juntos al amanecer, y Los Ángeles Azules abren el escenario principal.",
    start: "2026-11-13",
    end: "2026-11-16",
    utcOffset: "-06:00",
    venue: "Parque Metropolitano de León",
    city: "León",
    country: "México",
    geo: {
      name: "Parque Metropolitano de León",
      lat: 21.179888,
      lng: -101.687421,
    },
    organizer: "Festival Internacional del Globo",
    category: "Festivales",
    ticket: {
      url: "https://vivefig.mx/",
      label: "Programa y boletos",
    },
    source: {
      name: "Festival Internacional del Globo",
      url: "https://vivefig.mx/",
      verifiedOn: "2026-09-12",
    },
    body: [
      "El momento que define al FIG ocurre a las <strong>6:30 de la mañana</strong> y dura pocos minutos: el <strong>despegue simultáneo de más de 200 globos aerostáticos provenientes de más de 25 países</strong>. Es lo primero del programa del <strong>viernes 13 de noviembre</strong>, y es la razón por la que este festival se ve a una hora a la que casi ningún otro empieza.",
      "## Fechas del Festival Internacional del Globo 2026",
      "<strong>Del 13 al 16 de noviembre de 2026</strong> —viernes, sábado, domingo y lunes— en el <strong>Parque Metropolitano de León</strong>, Guanajuato. Es la <strong>edición 23</strong>, y el festival se presenta a sí mismo como el Festival de Festivales.",
      "## El primer día, hora por hora",
      "<strong>6:30</strong>, Aeródromo FIG: despegue inaugural con más de 200 globos de más de 25 países. A la misma hora, la <strong>SEDENA</strong> presenta un despliegue de bandera monumental y un sobrevuelo de aeronaves. <strong>19:00</strong>: <strong>Noche Mágica</strong>, un espectáculo de luz y música con los globos anclados a tierra. <strong>20:00</strong>, escenario principal: <strong>Los Ángeles Azules</strong>, que llegan tras haber participado en la inauguración de la Copa Mundial de Futbol 2026.",
      "## Lo demás del cartel",
      "El festival anuncia además a <strong>Christian Nodal</strong> y <strong>Xavi</strong> en lo que llama la noche más grande del regional mexicano, y a <strong>Carin León</strong>, ganador del Grammy Latino al Mejor Álbum Regional. <strong>The Dream Nite</strong> vuelve tras una primera edición que, según el propio festival, alcanzó un récord de asistencia de <strong>58,000</strong> personas.",
      "## Lo que el clima decide",
      "El aviso del organizador es explícito y vale para el momento más importante del programa: <strong>toda la actividad aerostática está sujeta a las condiciones climatológicas</strong>. Los conciertos no dependen del viento; los despegues sí.",
      "## Dónde es el Festival del Globo",
      "El <strong>Parque Metropolitano de León</strong>, en León, Guanajuato. El despegue sale del <strong>Aeródromo FIG</strong>, dentro del mismo recinto.",
    ],
    faq: [
      {
        q: "¿Cuándo es el Festival Internacional del Globo 2026?",
        a: "Del 13 al 16 de noviembre de 2026, en el Parque Metropolitano de León, Guanajuato. Es la edición 23.",
      },
      {
        q: "¿A qué hora despegan los globos?",
        a: "El despegue inaugural es a las 6:30 de la mañana del viernes 13 de noviembre, con más de 200 globos de más de 25 países saliendo al mismo tiempo desde el Aeródromo FIG.",
      },
      {
        q: "¿Qué es la Noche Mágica?",
        a: "Un espectáculo de luz y música con los globos anclados a tierra, a las 19:00 horas.",
      },
      {
        q: "¿Quién toca en el escenario principal?",
        a: "El viernes 13 abren Los Ángeles Azules a las 20:00. El festival anuncia además a Christian Nodal y Xavi, y a Carin León.",
      },
      {
        q: "¿Qué pasa si hace mal tiempo?",
        a: "El festival advierte que toda la actividad aerostática está sujeta a las condiciones climatológicas. El programa de escenario no depende de ello.",
      },
    ],
    expertise:
      "Quien va al FIG por los globos y no por los conciertos está yendo a un evento de madrugada, y esa es la decisión logística de todo el viaje: el despegue es a las 6:30 y hay que estar en el parque antes de esa hora, de modo que el alojamiento en León y la salida de madrugada se planean primero y el resto del programa después. La segunda advertencia es de calendario: el lunes 16 es día festivo en México, lo que convierte el fin de semana en uno largo y explica por qué el sábado y el domingo son los días llenos. El viernes tiene el despegue inaugural, la Noche Mágica y el primer concierto, y es el día con menos gente de los cuatro.",
  },
];
