import type { EventItem } from "../types.ts";

export const items: EventItem[] = [
  {
    slug: "festival-internacional-cervantino-2026",
    site: "mxo",
    image: "/covers/festival-internacional-cervantino-2026.jpg",
    imageAlt: "Tres arcos de papel de distinto tamaño anidados uno dentro de otro, en terracota y crema sobre un fondo verde",
    imageKind: "generated",
    imageWidth: 1536,
    imageHeight: 864,
    title: "Festival Internacional Cervantino 2026",
    summary:
      "La 54ª edición va del 3 al 18 de octubre en Guanajuato, con Francia como país invitado de honor y programación en seis ciudades del estado.",
    start: "2026-10-03",
    end: "2026-10-18",
    utcOffset: "-06:00",
    city: "Guanajuato",
    venue: "Teatro Juárez, Teatro Principal, Teatro Cervantes y otras sedes de Guanajuato",
    category: "Festivales",
    organizer: "Secretaría de Cultura",
    source: {
      name: "Festival Internacional Cervantino",
      url: "https://festivalcervantino.gob.mx/",
      verifiedOn: "2026-09-03",
    },
    body: [
      "Una ciudad de callejones y escalinatas, construida sobre un cauce de río, se convierte durante quince días de octubre en el escenario más incómodo y más bello del país.",
      "## Las fechas",
      "La <strong>54ª edición</strong> del Festival Internacional Cervantino va del <strong>3 al 18 de octubre de 2026</strong>, organizada por la <strong>Secretaría de Cultura</strong>.",
      "## El país invitado",
      "<strong>Francia</strong> es el país invitado de honor de esta edición.",
      "## Dónde ocurre",
      "En la ciudad de Guanajuato, las sedes incluyen el <strong>Teatro Juárez</strong>, el <strong>Teatro Principal</strong>, el <strong>Teatro Cervantes</strong>, la <strong>Explanada de la Alhóndiga de Granaditas</strong>, la <strong>Plaza San Fernando</strong>, la <strong>Plaza Allende</strong>, <strong>Los Pastitos</strong> y la <strong>Universidad de Guanajuato</strong>. La programación se extiende además a <strong>León</strong>, <strong>San Miguel de Allende</strong>, <strong>Salamanca</strong>, <strong>Silao</strong> y <strong>Purísima del Rincón</strong>.",
      "## Algunos nombres del programa",
      "<strong>Mondo Cane</strong>, el proyecto de Mike Patton; <strong>«FuturesPast»</strong> del <strong>Bangarra Dance Theatre</strong>; <strong>«Carmen»</strong> de la <strong>Compañía Antonio Gades</strong>; y <strong>«Tosca»</strong> de Puccini a cargo de la <strong>Compañía Nacional de Ópera</strong>.",
      "## Boletos",
      "La venta es a través de <strong>Ticketmaster</strong>.",
    ],
    expertise:
      "El Cervantino tiene dos festivales dentro: el de sala, con boleto y horario, y el de calle, que ocurre en plazas y explanadas sin costo. Quien viaja por el primero suele descubrir que el segundo le ocupó más horas. La restricción real es el hospedaje — Guanajuato es una ciudad pequeña y las dos semanas de octubre son las de mayor ocupación del año, así que la reserva se hace antes que la compra de boletos, no después. Sobre el traslado: la traza de callejones y escaleras hace que las distancias en el mapa engañen; entre dos sedes que parecen contiguas puede haber una subida considerable, y encadenar dos funciones con media hora de margen rara vez sale bien. Las sedes fuera de la capital — León, San Miguel, Salamanca — piden coche o autobús foráneo y prácticamente un día entero.",
  },

  {
    slug: "fil-guadalajara-2026",
    featured: 1,
    site: "mxo",
    image: "/covers/fil-guadalajara-2026.jpg",
    imageAlt: "Un arco de papel verde con una puerta iluminada debajo",
    imageKind: "generated",
    imageWidth: 1536,
    imageHeight: 864,
    title: "FIL Guadalajara 2026: 40 años, Italia invitada",
    summary:
      "La Feria Internacional del Libro de Guadalajara cumple 40 ediciones del 28 de noviembre al 6 de diciembre, con Italia como país Invitado de Honor y 61 autores italianos en Expo Guadalajara.",
    start: "2026-11-28",
    end: "2026-12-06",
    utcOffset: "-06:00",
    city: "Guadalajara",
    // City and state trimmed off the end: the card prints "venue · city" and
    // this one came out "…Verde Valle, Guadalajara, Jalisco · Guadalajara".
    venue: "Expo Guadalajara, Avenida Mariano Otero 1499, Colonia Verde Valle",
    geo: { name: "Expo Guadalajara", lat: 20.654251, lng: -103.391867 },
    category: "Ferias",
    organizer: "Universidad de Guadalajara",
    source: {
      name: "FIL Guadalajara",
      url: "https://www.fil.com.mx/",
      verifiedOn: "2026-08-30",
    },
    programme: [
      {
        heading: "Pabellón de Italia",
        text: "El corazón del programa del país Invitado de Honor: más de treinta editoriales italianas exponen ahí, y hay una librería con venta de libros de autores italianos en su lengua original y en traducción al español.",
      },
      {
        heading: "61 autoras y autores italianos",
        text: "De la narrativa, el ensayo, la ilustración, el cómic y la literatura infantil y juvenil. Entre ellos Alessandro Baricco, Viola Ardone, Stefania Auci, Claudia Durastanti, Milo Manara, Francesca Melandri, Veronica Raimo y Emanuele Coccia.",
      },
      {
        heading: "Diez exposiciones por toda la ciudad",
        text: "La participación italiana no se queda en el recinto: exposiciones, conciertos, cine, gastronomía e intercambios académicos se extienden por Guadalajara durante los nueve días.",
      },
      {
        heading: "Premio de Literaturas Indígenas de América",
        text: "Se entrega el 4 de diciembre a las 16:00 al poeta guatemalteco garífuna Wingston González por Un poquito más allá: 300 mil pesos y una escultura del artista jalisciense Camilo Ramírez.",
      },
      {
        heading: "Venta nocturna del viernes 4",
        text: "Ese viernes la Feria extiende su horario hasta las 23:00 horas; el cierre de ventas es a esa hora y el recinto cierra a las 23:30.",
      },
    ],
    body: [
      "La <strong>Feria Internacional del Libro de Guadalajara</strong> llega a su <strong>edición 40</strong> del <strong>28 de noviembre al 6 de diciembre de 2026</strong> en <strong>Expo Guadalajara</strong>. El país Invitado de Honor es <strong>Italia</strong>, que vuelve a ocupar ese lugar <strong>dieciocho años</strong> después de su última participación",
      "## Una feria de negocios a la que el público entra",
      "Es el rasgo que la distingue de Fráncfort, de Bolonia y de casi cualquier otra feria grande del mundo: la FIL fue fundada por la <strong>Universidad de Guadalajara</strong> como una feria para profesionales <em>donde el público es bienvenido</em>. Los agentes literarios negocian derechos de traducción en los mismos pasillos por los que camina alguien que vino a comprar una novela",
      "Las cifras de un año normal explican para qué sirve esa mezcla: más de <strong>900 escritores</strong>, <strong>18 mil profesionales</strong> del sector editorial, <strong>2 800 casas editoriales</strong> de más de <strong>60 países</strong> y un público cercano al <strong>millón de visitantes</strong>. En más de <strong>43 mil metros cuadrados</strong> se desarrollan más de <strong>tres mil actividades</strong> a lo largo de nueve días",
      "## Por qué importa que el invitado sea Italia",
      "El español es el <strong>principal mercado de exportación de derechos de traducción</strong> de la industria editorial italiana, y concentró el <strong>15 por ciento</strong> de sus ventas en 2024. No es un gesto diplomático: es la feria donde ese negocio se hace",
      "> Mostraremos en México la Italia de hoy y la vitalidad de su propuesta editorial mediante un programa que reunirá a más de 60 autoras y autores, jóvenes y consagrados, de la narrativa, el ensayo, la ilustración, el cómic y la literatura infantil y juvenil.\n— Innocenzo Cipolletta, presidente de la Asociación Italiana de Editores",
      "El programa italiano se articula alrededor de una frase de <strong>Umberto Eco</strong> — «el mundo nos habla como un gran libro» — a diez años de su muerte. Se presentó en julio en el Palacio de la Farnesina, en Roma, con el ministro de Asuntos Exteriores Antonio Tajani, el presidente de la FIL José Trinidad Padilla López y la directora general Marisol Schulz Manaut",
      "## Cuándo ir, si se puede elegir",
      "Los dos fines de semana son los días llenos. Entre semana el recinto respira, y es cuando conviene ir si el plan es mirar mesas y no sólo llegar a una presentación concreta. El <strong>viernes 4 de diciembre</strong> hay <strong>venta nocturna</strong>: la Feria abre hasta las <strong>23:00</strong> horas, con cierre del recinto a las 23:30",
      "## Cómo llegar",
      "Expo Guadalajara está en <strong>Avenida Mariano Otero 1499</strong>, colonia Verde Valle. Es el recinto ferial de la ciudad, al sur del centro, sobre una avenida por la que pasan varias rutas del transporte urbano; en los días de FIL el tránsito alrededor es el peor del año y conviene llegar sin coche",
    ],
    expertise:
      "Nueve días y tres mil actividades no se recorren improvisando. Lo que funciona es elegir dos o tres presentaciones del programa oficial, anotarlas con hora y salón, y dejar el resto del día para caminar los pasillos: el hallazgo en la FIL casi siempre es una editorial pequeña que uno no buscaba, no el autor famoso al que no se alcanzó a entrar",
  },
  {
    slug: "filij-2026",
    featured: 2,
    site: "mxo",
    image: "/covers/filij-2026.jpg",
    imageAlt: "Barcos de papel y confeti sobre fondo verde",
    imageKind: "generated",
    imageWidth: 1536,
    imageHeight: 864,
    title: "FILIJ 2026: el libro infantil y juvenil",
    summary:
      "La 44 Feria Internacional del Libro Infantil y Juvenil ocupa el CENART del 13 al 22 de noviembre. Entrada gratuita, diez días, y convocatoria abierta para visitas escolares.",
    start: "2026-11-13",
    end: "2026-11-22",
    startTime: "09:00",
    endTime: "19:00",
    utcOffset: "-06:00",
    city: "Ciudad de México",
    venue: "Centro Nacional de las Artes, Río Churubusco 79, Country Club Churubusco, Coyoacán",
    geo: { name: "Centro Nacional de las Artes", lat: 19.355607, lng: -99.137182 },
    category: "Ferias",
    organizer: "Secretaría de Cultura",
    tickets: { priceFrom: 0 },
    source: {
      name: "Excélsior",
      url: "https://www.excelsior.com.mx/cultura/filij-2026-regresa-cenart-con-entrada-gratuita-fechas",
      verifiedOn: "2026-08-30",
    },
    body: [
      "La <strong>44 edición</strong> de la Feria Internacional del Libro Infantil y Juvenil se realiza del <strong>13 al 22 de noviembre de 2026</strong> en el <strong>Centro Nacional de las Artes</strong>, según el Fondo de Cultura Económica. La <strong>entrada es gratuita</strong>",
      "## Diez días, no un fin de semana",
      "La duración es el rasgo que distingue a la FILIJ de casi cualquier otra feria del libro infantil: dos fines de semana completos y la semana entre ellos. Eso permite dos tipos de visita muy distintos — la familiar de sábado, ruidosa y llena, y la de un martes por la tarde, en la que un niño puede quedarse veinte minutos en una mesa sin que nadie lo apure",
      "## Qué hay adentro",
      "Editoriales, escritores e ilustradores, con oferta para todas las edades: del cuento ilustrado a la novela juvenil y el libro informativo",
      "Alrededor de los libros hay programación cultural: cuentacuentos, talleres creativos, presentaciones, teatro, música y danza. Es gratuita como el resto de la feria, y es la parte por la que conviene consultar el programa antes de ir en lugar de improvisar",
      "## Escuelas",
      "El FCE abrió <strong>convocatoria para visitas escolares</strong>; los detalles se publican en sus canales oficiales. Es el mecanismo que lleva a la feria a los niños que no vendrían en fin de semana con su familia, y es la razón de que la sede se llene entre semana por la mañana",
      "## Cómo llegar",
      "El CENART está en <strong>Avenida Río Churubusco 79</strong>, colonia Country Club Churubusco, alcaldía Coyoacán. Las estaciones de Metro más cercanas son <strong>General Anaya</strong> (Línea 2) y <strong>Ermita</strong> (Línea 12), a <strong>8 o 10 minutos caminando</strong> desde cualquiera de las dos",
    ],
    expertise:
      "Diez días de feria gratuita se sienten como una invitación a ir cuando se pueda, y así es como no se va. Vale más elegir una fecha entre semana por la tarde y anotarla: es cuando la feria está abierta, tiene programa y no tiene ni grupos escolares ni multitud de fin de semana",
  },

  {
    slug: "fiestas-de-octubre-2026",
    site: "mxo",
    image: "/covers/fiestas-de-octubre-2026.jpg",
    imageAlt: "Una rueda de la fortuna naranja y crema, de líneas planas, sobre un fondo verde oscuro",
    imageKind: "generated",
    imageWidth: 1536,
    imageHeight: 864,
    title: "Fiestas de Octubre 2026",
    summary:
      "Un mes completo de feria en Zapopan, en el occidente de México, del 2 de octubre al 1 de noviembre: Foro Principal con conciertos incluidos en la entrada general y Palenque con boleto aparte.",
    start: "2026-10-02",
    end: "2026-11-01",
    utcOffset: "-06:00",
    venue: "Auditorio Benito Juárez, Zapopan",
    city: "Guadalajara",
    country: "México",
    organizer: "Patronato de las Fiestas de Octubre",
    category: "Feria",
    source: {
      name: "El Informador",
      url: "https://www.informador.mx/jalisco/fiestas-de-octubre-2026-cuando-empiezan-cuando-terminan-y-que-artistas-se-presentaran-20260723-0108.html",
      verifiedOn: "2026-09-08",
    },
    body: [
      "Treinta y un días seguidos. Ninguna otra feria del país se sostiene tanto tiempo en un mismo recinto, y esa duración es la que explica su programación.",
      "## Las fechas",
      "Las actividades <strong>comienzan el 2 de octubre y concluyen el 1 de noviembre de 2026</strong>, en las instalaciones del <strong>Auditorio Benito Juárez</strong>, en el municipio de <strong>Zapopan</strong>, Jalisco.",
      "## Los dos escenarios",
      "El <strong>Foro Principal</strong> presenta conciertos <strong>incluidos en la entrada general</strong>. El <strong>Palenque</strong> se vende por separado; entre los nombres confirmados están <strong>Alejandro Fernández</strong>, <strong>Grupo Firme</strong>, <strong>Banda MS</strong>, <strong>María José</strong>, <strong>Kany García</strong>, <strong>Jorge Medina</strong> y <strong>Josi Cuen</strong>.",
      "## Lo demás",
      "Juegos mecánicos, áreas gastronómicas y entretenimiento familiar. La venta de boletos <strong>inició el 27 de julio</strong> a través de mipase.net y de puntos físicos autorizados en la ciudad.",
    ],
    expertise:
      "La diferencia entre los dos escenarios es la que decide el presupuesto de la visita y casi nadie la explica al comprar: el Foro Principal entra con el boleto general, así que un cartel de nombres grandes puede salir por el precio de la entrada, mientras que el Palenque es un boleto aparte por función. Para quien viaja desde fuera de Jalisco, la lectura práctica es que un mes de feria significa que casi cualquier fin de semana de octubre sirve, y que los caros son los dos primeros y el último: entre semana, a mitad de mes, el mismo recinto se recorre sin fila.",
  },
  {
    slug: "festival-de-vida-y-muerte-2026",
    site: "mxo",
    image: "/covers/festival-de-vida-y-muerte-2026.jpg",
    imageAlt: "Una flor de cempas\u00fachil de papel, de p\u00e9talos naranjas y centro oscuro, sola sobre un fondo azul verdoso",
    imageKind: "generated",
    imageWidth: 1536,
    imageHeight: 864,
    title: "Festival de Vida y Muerte 2026",
    summary:
      "La edici\u00f3n n\u00famero 20 del festival de Xcaret, del 30 de octubre al 2 de noviembre, con Guanajuato como estado invitado: cuatro d\u00edas de altares, m\u00fasica y representaciones en la Riviera Maya.",
    start: "2026-10-30",
    end: "2026-11-02",
    utcOffset: "-05:00",
    venue: "Parque Xcaret",
    city: "Riviera Maya",
    country: "M\u00e9xico",
    organizer: "Xcaret",
    category: "Festival",
    source: {
      name: "Festival de Vida y Muerte",
      url: "https://festivaldevidaymuerte.com/",
      verifiedOn: "2026-09-08",
    },
    ticket: { url: "https://festivaldevidaymuerte.com/", label: "Boletos" },
    body: [
      "El D\u00eda de Muertos se celebra el 1 y el 2 de noviembre. Este festival dura el doble y empieza dos d\u00edas antes.",
      "## Las fechas",
      "<strong>Del 30 de octubre al 2 de noviembre de 2026</strong>, en el <strong>Parque Xcaret</strong>, en la Riviera Maya, Quintana Roo. Es la <strong>edici\u00f3n n\u00famero 20</strong>.",
      "## El estado invitado",
      "Cada a\u00f1o el festival invita a un estado a llevar su propia forma de celebrar. En 2026 es <strong>Guanajuato</strong>.",
      "## Qu\u00e9 hay dentro",
      "M\u00fasica del D\u00eda de Muertos \u2014 mariachi, estudiantina, sones, huapango arribe\u00f1o y m\u00fasica tradicional de la Pen\u00ednsula de Yucat\u00e1n \u2014 adem\u00e1s de representaciones y un <strong>Concierto de Gala</strong> el <strong>31 de octubre</strong>, que se compra aparte del acceso al parque.",
    ],
    faq: [
      {
        q: "\u00bfCu\u00e1ndo es el Festival de Vida y Muerte 2026?",
        a: "<strong>Del 30 de octubre al 2 de noviembre de 2026</strong>, en el Parque Xcaret.",
      },
      {
        q: "\u00bfCu\u00e1l es el estado invitado este a\u00f1o?",
        a: "<strong>Guanajuato</strong>. El festival invita cada edici\u00f3n a un estado distinto.",
      },
      {
        q: "\u00bfEl Concierto de Gala entra con el boleto del parque?",
        a: "No. El organizador lo vende como acceso aparte, para la noche del <strong>31 de octubre</strong>.",
      },
    ],
    expertise:
      "La confusi\u00f3n m\u00e1s cara aqu\u00ed es tratarlo como una fiesta de una noche. Son cuatro d\u00edas dentro de un parque que ya de por s\u00ed toma una jornada completa, y el festival ocupa la tarde y la noche; quien llega el 1 de noviembre por la ma\u00f1ana ve el parque, no el festival. La otra decisi\u00f3n que conviene tomar antes de viajar es la del concierto: se vende por separado y cae en la v\u00edspera, as\u00ed que define en qu\u00e9 noche conviene estar ah\u00ed.",
  },
  {
    slug: "noche-de-muertos-michoacan-2026",
    site: "mxo",
    image: "/covers/noche-de-muertos-michoacan-2026.jpg",
    imageAlt: "Seis velas de papel color crema, con llamas naranjas, alineadas sobre un fondo azul verdoso y separadas de manera desigual",
    imageKind: "generated",
    imageWidth: 1536,
    imageHeight: 864,
    title: "Noche de Muertos en Michoacán 2026",
    summary:
      "La noche del 1 de noviembre, en Janitzio, Tzintzuntzan y Jarácuaro: velas, cempasúchil y una procesión al panteón. Patrimonio de la Humanidad por la UNESCO desde 2008.",
    start: "2026-11-01",
    end: "2026-11-02",
    utcOffset: "-06:00",
    city: "Janitzio",
    country: "México",
    organizer: "Secretaría de Turismo de Michoacán",
    category: "Festival",
    source: {
      name: "Secretaría de Turismo de Michoacán",
      url: "https://visitmichoacan.com.mx/experiences/noche-de-muertos/",
      verifiedOn: "2026-09-08",
    },
    body: [
      "No es un espectáculo con horario de inicio. Es una noche entera en la que un pueblo entero está despierto en el panteón.",
      "## Las fechas",
      "La noche principal es la del <strong>1 de noviembre</strong>, y los días de la fiesta son el <strong>1 y el 2</strong>. Los altares se colocaban tradicionalmente el <strong>30 o el 31 de octubre</strong> y se retiraban el <strong>3 de noviembre</strong>; hoy muchas familias los montan antes y los quitan después, porque el trabajo que llevan lo pide.",
      "## Tres lugares, tres formas",
      "En la <strong>Isla de Janitzio</strong>, mujeres y niños caminan en procesión hacia el panteón y colocan junto a las tumbas los platillos favoritos de sus difuntos, en silencio y a la luz de las velas. En <strong>Tzintzuntzan</strong>, la ofrenda se expresa en artesanía: loza negra, loza blanca, ángeles de paja y tallados en madera. En <strong>Jarácuaro</strong>, los arcos de flores adornan cada barrio y la plaza principal, y la danza guía a las almas.",
      "## Por qué es Patrimonio de la Humanidad",
      "La UNESCO la nombró <strong>Patrimonio de la Humanidad el 4 de noviembre de 2008</strong>. El altar tiene raíz prehispánica: la ofrenda dedicada a Mictlantecuhtli, señor de los muertos, coincidía con lo que hoy es noviembre, y durante la Colonia esa coincidencia se fundió con la celebración cristiana.",
    ],
    faq: [
      {
        q: "¿Cuándo es la Noche de Muertos en Michoacán 2026?",
        a: "La noche del <strong>1 de noviembre</strong>. Los días de la fiesta son el <strong>1 y el 2 de noviembre</strong>.",
      },
      {
        q: "¿Dónde se celebra?",
        a: "En comunidades de la región: la <strong>Isla de Janitzio</strong>, <strong>Tzintzuntzan</strong> y <strong>Jarácuaro</strong>, cada una con su propia forma del rito.",
      },
      {
        q: "¿Cuándo se ponen las ofrendas?",
        a: "Tradicionalmente el <strong>30 o el 31 de octubre</strong>, y permanecían hasta el <strong>3 de noviembre</strong>. Hoy muchas familias las montan antes.",
      },
      {
        q: "¿Es Patrimonio de la Humanidad?",
        a: "Sí, declarada por la <strong>UNESCO el 4 de noviembre de 2008</strong>.",
      },
    ],
    expertise:
      "Conviene decidir antes de viajar qué se va a ver, porque no es lo mismo la isla que los pueblos de la ribera: Janitzio es la imagen que todo el mundo conoce y es también la que concentra a los visitantes, mientras que en Tzintzuntzan y Jarácuaro la noche se parece más a lo que la fecha es en una casa. Y hay una cortesía que ninguna guía imprime en la portada: el panteón esa noche no es un escenario, es la sala de una familia. Se entra como se entra a una casa ajena.",
  },
];
