import type { EventItem } from "../types.ts";

export const items: EventItem[] = [
  {
    slug: "new-york-comic-con-2026",
    site: "nyc42",
    title: "New York Comic Con 2026",
    summary:
      "Four days at the Javits Center, 8–11 October, for NYCC's twentieth anniversary — with a Coney Island theme and the panel schedule already published.",
    start: "2026-10-08",
    end: "2026-10-11",
    city: "New York",
    venue: "Jacob K. Javits Convention Center, 429 11th Avenue",
    category: "Convention",
    organizer: "ReedPop",
    geo: {
      name: "Jacob K. Javits Convention Center",
      lat: 40.758359,
      lng: -74.002121,
    },
    source: {
      name: "New York Comic Con",
      url: "https://www.newyorkcomiccon.com/",
      verifiedOn: "2026-08-30",
    },
    body: [
      "NYCC runs <strong>8 to 11 October 2026</strong> at the Javits Center: four days of comics, film and TV, anime and manga, gaming, cosplay, literary programming and horror.",
      "This one is the <strong>twentieth anniversary</strong>, and the organisers have picked a theme to match.",
      "## Coney Island",
      "The 20th-anniversary theme is <strong>Coney Island</strong> &mdash; sideshow energy, roaring coasters, ocean air, in the convention&rsquo;s own description, and the merchandise follows it.",
      "It is a better choice than it first sounds. Coney Island is where New York invented the idea that spectacle should be cheap and public: the freak show, the roller coaster and the boardwalk crowd are the direct ancestors of a convention hall where a hundred thousand people queue to see something loud. Twenty years in, the con is claiming a lineage rather than a birthday.",
      "## The schedule is already up",
      "The panels and programming schedule is <strong>live</strong>, which is unusual this far out and is the single most useful fact for planning. Announced so far: <strong>Marvel TV</strong>, a <strong>Crystal Lake</strong> screening, <strong>Yaga</strong>, a preview of Blumhouse&rsquo;s <strong>BlumFest</strong>, and <strong>Dexter: Resurrection</strong> Season 2.",
      "Guests are added continuously up to and during the show, so a schedule read in August is a floor, not a ceiling.",
      "## Tickets and the practical part",
      "Tickets are on sale. The convention runs a <strong>Fan Verification</strong> process for first-timers, and there is an app carrying the map of the Javits and the full panel schedule &mdash; the building is large enough that this is a genuine recommendation rather than a promotion.",
      "One thing worth knowing if you bought for a group: tickets have to be <strong>transferred</strong> to each person, not handed over, or your friend cannot access reservations on the day.",
      "## Getting to the Javits",
      "The Javits Center sits at <strong>429 11th Avenue</strong>, on the far west side at Hudson Yards. That is a longer walk from the subway than most New York venues, and the walk is on a stretch with very little on it &mdash; the 7 train to Hudson Yards is the shortest version of it.",
    ],
    expertise:
      "The twentieth-anniversary framing means the popular panels will be busier than the schedule suggests, and NYCC queues form for the room, not the panel &mdash; once you are inside a hall you can usually stay for the next session. Picking a room for a block of the afternoon beats picking four panels in four buildings.",
  },
  {
    slug: "village-halloween-parade-2026",
    site: "nyc42",
    title: "Village Halloween Parade 2026",
    summary:
      "The 53rd parade goes up Sixth Avenue at 7pm on Saturday 31 October. Watching is free, joining in is free if you are in costume, and it happens rain or shine.",
    start: "2026-10-31",
    startTime: "19:00",
    utcOffset: "-04:00",
    city: "New York",
    venue: "Sixth Avenue, Greenwich Village",
    category: "Parade",
    organizer: "Village Halloween Parade, Inc.",
    source: {
      name: "NYC Village Halloween Parade",
      url: "https://www.halloween-nyc.com/",
      verifiedOn: "2026-08-30",
    },
    body: [
      "New York&rsquo;s <strong>53rd annual Village Halloween Parade</strong> steps off at <strong>7:00pm on Saturday 31 October 2026</strong>, up Sixth Avenue.",
      "The organisers put the important part in capitals on their own front page: <strong>rain or shine</strong>. Or wind.",
      "## The rule that makes it different",
      "<strong>Everyone is invited to watch. Anyone in costume is welcome to join in.</strong>",
      "That second sentence is the whole event. Almost every other parade in America is a procession of organisations that the public watches from a barrier; this one has no audition, no application and no float requirement. Turn up in costume and you are in it. It is the largest participatory parade in the country for exactly that reason, and it is why the thing has never looked corporate.",
      "## Halloween lands on a Saturday",
      "The parade is always on 31 October, whatever day that is &mdash; and in 2026 it falls on a <strong>Saturday</strong>. A Saturday-night Halloween in Manhattan is the maximum-density version of this: nobody has work the next morning, and the parade is a whole evening rather than a weeknight detour.",
      "Plan the getting-home part before the getting-there part.",
      "## What tickets are for",
      "Watching costs nothing and marching costs nothing. Tickets exist for <strong>special access</strong> &mdash; skipping the line to enter the parade, and grandstand-style viewing &mdash; and the parade is a <strong>501(c)(3) not-for-profit arts organisation</strong>, so buying one is closer to a donation than a fee.",
      "The parade is supported in part by public funds from the <strong>NYC Department of Cultural Affairs</strong> in partnership with the City Council.",
      "## What is not announced",
      "The <strong>2026 theme and Grand Marshal have not been published</strong>, so they do not appear here. For reference, 2025 ran under &laquo;It&rsquo;s a Potluck!&raquo; with <strong>City Harvest</strong> as Grand Marshal &mdash; the organisation that rescues fresh produce and delivers it free across the five boroughs.",
      "There is also an official after party at <strong>House of Yes</strong> in Industry City, Brooklyn, from <strong>9:00pm</strong>, which is ticketed separately.",
    ],
    expertise:
      "The costume rule cuts both ways: if you are in costume you can join, and if you are in costume in the Village that night you will be swept into it whether you meant to be or not. For watching rather than marching, the north end of the route thins out considerably &mdash; the parade takes hours to pass, and the last third of it is the same parade with room to stand.",
  },
  {
    slug: "open-house-new-york-weekend-2026",
    site: "nyc42",
    title: "Open House New York Weekend 2026",
    summary:
      "Three hundred buildings across the five boroughs open for one weekend, 16–18 October. The full lineup is revealed on 25 September and tickets go on 2 October.",
    start: "2026-10-16",
    end: "2026-10-18",
    city: "New York",
    venue: "All five boroughs",
    category: "Architecture",
    organizer: "Open House New York",
    source: {
      name: "Open House New York",
      url: "https://ohny.org/festival",
      verifiedOn: "2026-08-30",
    },
    body: [
      "For one weekend in October the answer to &laquo;can you go in there?&raquo; is yes, about three hundred times over.",
      "<strong>OHNY Weekend runs 16 to 18 October 2026</strong> and unlocks <strong>300+ destinations</strong> across all five boroughs for behind-the-scenes tours and special activities.",
      "## What actually opens",
      "New buildings changing the skyline, and also: <strong>infrastructure facilities</strong> that keep the city running, parks, performance spaces, manufacturing workshops and private collections.",
      "The infrastructure is the part worth queuing for. Among the 2026 destinations already previewed is the <strong>Department of Sanitation&rsquo;s Brooklyn District 3 Garage</strong> and the <strong>DOT Sign Shop</strong> in Maspeth, Queens &mdash; the place where the city&rsquo;s street signs are actually made. Those are buildings no amount of money gets you into on an ordinary Tuesday, and they explain more about how New York works than any tower does.",
      "Also previewed: the <strong>Flatiron Building</strong>, <strong>Rockefeller Center Gardens</strong> and the <strong>Brooklyn Army Terminal</strong>.",
      "## The calendar before the calendar",
      "OHNY is unusual in that the month before the festival has its own schedule, and missing a date on it costs you access rather than information.",
      "Most sites you can simply show up to. A minority require <strong>tickets</strong>, because of space or security &mdash; and those are the ones that go in minutes on release day.",
      "## Five boroughs, and that is the instruction",
      "The festival is designed as a citywide event, not a Manhattan one, and the way to use it is to stay in one borough for a day rather than crossing three. A Sanitation garage in Brooklyn and a sign shop in Queens are not consolation prizes for missing the Flatiron; they are the festival.",
    ],
    programme: [
      { heading: "18 September &mdash; Members preview", text: "Members get early access to the Weekend lineup, and more time to plan." },
      { heading: "25 September &mdash; Public reveal", text: "The full lineup is published with all locations, activities, dates and times." },
      { heading: "2 October &mdash; Ticket release", text: "Most sites need no ticket; the ones limited by space or security release theirs now." },
      { heading: "15 October &mdash; Launch party", text: "The festival's fundraiser and official kick-off, with food, drinks and entertainment." },
      { heading: "16&ndash;18 October &mdash; The festival", text: "Three days of tours and visits across the five boroughs." },
    ],
    expertise:
      "Put 2 October in the diary rather than 16 October. The weekend itself is walk-up for most of the three hundred sites, so the only thing that can actually be missed by being slow is the ticketed handful &mdash; which is, reliably, the list of places everybody wanted to see.",
  },
  {
    slug: "broadway-week-fall-2026",
    site: "nyc42",
    title: "NYC Broadway Week: two-for-one at 25 shows",
    summary:
      "Two weeks of 2-for-1 Broadway tickets across 25 productions, from 8 to 20 September 2026. Tickets have been on sale since 18 August.",
    start: "2026-09-08",
    end: "2026-09-20",
    city: "New York City",
    category: "Theatre",
    organizer: "New York City Tourism + Conventions",
    source: {
      name: "NYC Tourism + Conventions",
      url: "https://www.nyctourism.com/broadway-week/",
      verifiedOn: "2026-08-30",
    },
    body: [
      "NYC Broadway Week runs from <strong>8 to 20 September 2026</strong>. Twenty-five productions take part, and the offer is the one it has always been: buy two tickets, pay for one. Sales opened on 18 August.",
      "## What is in it",
      "&amp; Juliet, Aladdin, The Book of Mormon, Buena Vista Social Club, Chicago, The Great Gatsby, Hadestown, Harry Potter and the Cursed Child, Just in Time, The Lion King, The Lost Boys, Maybe Happy Ending, MJ, Oh Mary!, Operation Mincemeat, The Outsiders, Paranormal Activity, The Rocky Horror Show, Schmigadoon!, School Girls; Or, the African Mean Girls Play, Six, Stranger Things: The First Shadow, Titaníque, Two Strangers (Carry a Cake Across New York) and Wicked.",
      "It is a wide list on purpose: long-runners that will still be there next year sit beside productions in their first season, and at half price those are worth very different things.",
      "## The catch is the calendar, not the price",
      "Each show sets its own <strong>blackout dates</strong> and releases its own allocation. The offer existing on a given day and the offer existing for the show you want on that day are two separate questions, and only the second decides your evening.",
      "Check the individual listing before committing, and before booking anything around it. The usual way this goes wrong is a dinner reservation made for a night the show had blacked out.",
      "## Seats, not shows",
      "A two-for-one discounts a seat rather than a production, so it is worth most where the seat was expensive to begin with. In a big house built on stagecraft the gap between a good seat and a bad one is wide, and the allocation decides which you get. In a small house the same offer buys proximity &mdash; which is most of what the ticket was for.",
    ],
    expertise:
      "Broadway Week runs twice a year, in January and September, and the September edition lands in the quiet stretch after the summer tourists and before the holiday run-up — which is why the discounted seats tend to be better ones than the winter edition offers.",
  },
];
