import type { EventItem } from "../types.ts";

export const items: EventItem[] = [
  {
    slug: "snoopy-in-style-nyc",
    site: "nyc42",
    image: "/covers/snoopy-in-style-nyc.jpg",
    imageAlt: "A cream paper dog-house silhouette on a deep brown ground with amber fabric swatches pinned in a row beside it",
    imageKind: "generated",
    imageWidth: 1536,
    imageHeight: 864,
    title: "Snoopy in Style NYC",
    summary:
      "A free 16,000-square-foot Peanuts exhibition in the Meatpacking District, open daily 10am–6pm through September 26. Ten zones, designer plush and Schulz Museum archives.",
    start: "2026-09-02",
    end: "2026-09-26",
    startTime: "10:00",
    endTime: "18:00",
    utcOffset: "-04:00",
    venue: "25 Little West 12th Street",
    city: "New York City",
    organizer: "Peanuts",
    category: "Exhibitions",
    source: {
      name: "Peanuts",
      url: "https://www.peanuts.com/snoopy-in-style-nyc",
      verifiedOn: "2026-09-03",
    },
    body: [
      "A beagle who has never worn clothes has somehow become a fashion exhibition. He opened on September 2, which is not an accident: Fashion Week and the US Open are both in town.",
      "## The practical details",
      "<strong>25 Little West 12th Street</strong>, in the Meatpacking District. <strong>September 2 to 26</strong>, <strong>10am to 6pm daily</strong>, and <strong>admission is free</strong>. Hours can vary for special events.",
      "## What is in it",
      "About <strong>16,000 square feet</strong> across <strong>ten immersive zones</strong>, looking at Charles M. Schulz's strip through fashion, creativity and culture. Installations are curated by the <strong>Charles M. Schulz Museum and Research Center</strong>, and the archives on show include material about Schulz's own connections to New York, to tennis, and to his friendship with <strong>Billie Jean King</strong>.",
      "## The clothes",
      "Custom Snoopy and Woodstock plush dolls dressed by named designers — among them <strong>Christopher John Rogers</strong>, <strong>Sandy Liang</strong>, <strong>LUAR</strong>, <strong>BODE</strong>, <strong>Coach</strong>, <strong>Levi's</strong>, <strong>Michael Kors Collection</strong>, <strong>Madhappy</strong> and <strong>New York or Nowhere</strong>.",
      "## The rest of it",
      "A gift shop curated by <strong>Sarah Andelman</strong>, and <strong>Joe Cool's Listening Lounge</strong>, given over to Vince Guaraldi's music.",
    ],
    expertise:
      "Free and three and a half weeks long is a combination that produces its own crowd problem, and this one has a specific shape: the exhibition sits between Fashion Week and the US Open, so the middle weekends are the worst of it. A 10am opening on a weekday is the quiet hour. The zone most people underrate is the Schulz Museum's archive material rather than the designer plush — the plush is what photographs, but the archives are the part with the Billie Jean King material in them, and it is genuinely difficult to see outside Santa Rosa. Note also that this is a pop-up rather than a museum: there is no reason to expect an extension past September 26.",
  },

  {
    slug: "new-york-film-festival-2026",
    site: "nyc42",
    image: "/covers/new-york-film-festival-2026.jpg",
    imageAlt: "A paper film strip crossing the frame, five frames in brighter tones, a projector beam at the edge",
    imageKind: "generated",
    imageWidth: 1536,
    imageHeight: 864,
    title: "New York Film Festival 2026",
    summary:
      "The 64th NYFF runs 25 September to 12 October: 32 films in the Main Slate, opening with James Gray's Paper Tiger and closing with Ava DuVernay's 14th, screening in all five boroughs.",
    start: "2026-09-25",
    end: "2026-10-12",
    city: "New York City",
    venue: "Lincoln Center and venues in all five boroughs",
    category: "Festival",
    organizer: "Film at Lincoln Center",
    source: {
      name: "Film at Lincoln Center",
      url: "https://www.filmlinc.org/nyff/",
      verifiedOn: "2026-09-01",
    },
    body: [
      "The New York Film Festival does not hand out a top prize. It has no competition, no jury and no winner — which is unusual enough among major festivals to be the first thing worth knowing about it. What it has instead is a <strong>Main Slate</strong>: a selection, argued over by programmers, that is the whole statement.",
      "The <strong>64th edition runs from 25 September to 12 October 2026</strong>.",
      "## The Main Slate",
      "<strong>32 films</strong>, including <strong>17 directors making their Main Slate debut</strong>. The selection brings together new work by returning NYFF filmmakers and titles from festivals earlier in the year.",
      "Dennis Lim, the festival’s artistic director, said it is «hard to recall a prior Main Slate program in which the state of the world has been as urgently reflected in so many creative ways».",
      "Among the names in the slate: <strong>Pedro Almodóvar</strong>, <strong>Mike Leigh</strong>, <strong>Lee Chang-dong</strong>, <strong>Paweł Pawlikowski</strong> and <strong>Ryûsuke Hamaguchi</strong>.",
      "## The three tentpole slots",
      "<strong>Opening Night — Paper Tiger</strong>, directed by James Gray.",
      "<strong>Centerpiece — Behemoth!</strong>, directed by Tony Gilroy.",
      "<strong>Closing Night — 14th</strong>, a documentary directed by Ava DuVernay.",
      "## It is not only a Lincoln Center festival any more",
      "Screenings take place across <strong>all five boroughs</strong>: at <strong>Lincoln Center</strong>, <strong>BAM</strong> in Brooklyn, the <strong>Museum of the Moving Image</strong> in Queens, <strong>Alamo Drafthouse Cinema</strong>, and <strong>AMC Bay Plaza Cinema</strong> in the Bronx.",
      "That spread changes the practical shape of the festival. A Main Slate title screening at Bay Plaza is the same film with the same print as the one at Alice Tully Hall, usually with a fraction of the queue.",
      "## Tickets",
      "Passes went on sale first. <strong>Single tickets go on sale 15 September at noon.</strong>",
    ],
    expertise:
      "The rush line is the part regulars use and visitors miss. Sold-out NYFF screenings routinely release returned seats at the venue shortly before the show, and the outer-borough venues almost never reach the point of needing one. If a title is gone at Lincoln Center, check the same film’s second screening in Queens or the Bronx before assuming it is unavailable.",
  },
  {
    slug: "new-york-comic-con-2026",
    featured: 1,
    site: "nyc42",
    image: "/covers/new-york-comic-con-2026.jpg",
    imageAlt: "A cut-paper starburst in amber bursting out of a dark ground",
    imageKind: "generated",
    imageWidth: 1536,
    imageHeight: 864,
    title: "New York Comic Con 2026",
    summary:
      "Four days at the Javits Center, 8–11 October, for NYCC's twentieth anniversary — with a Coney Island theme and the panel schedule already published.",
    start: "2026-10-08",
    end: "2026-10-11",
    city: "New York City",
    venue: "Jacob K. Javits Convention Center, 429 11th Avenue",
    category: "Convention",
    organizer: "ReedPop",
    geo: {
      name: "Jacob K. Javits Convention Center",
      lat: 40.758359,
      lng: -74.002121,
    },
    source: {
      name: "New York Comic Con",
      url: "https://www.newyorkcomiccon.com/",
      verifiedOn: "2026-08-30",
    },
    body: [
      "NYCC runs <strong>8 to 11 October 2026</strong> at the Javits Center: four days of comics, film and TV, anime and manga, gaming, cosplay, literary programming and horror.",
      "This one is the <strong>twentieth anniversary</strong>, and the organisers have picked a theme to match.",
      "## Coney Island",
      "The 20th-anniversary theme is <strong>Coney Island</strong> — sideshow energy, roaring coasters, ocean air, in the convention’s own description, and the merchandise follows it.",
      "It is a better choice than it first sounds. Coney Island is where New York invented the idea that spectacle should be cheap and public: the freak show, the roller coaster and the boardwalk crowd are the direct ancestors of a convention hall where a hundred thousand people queue to see something loud. Twenty years in, the con is claiming a lineage rather than a birthday.",
      "## The schedule is already up",
      "The panels and programming schedule is <strong>live</strong>, which is unusual this far out and is the single most useful fact for planning. Announced so far: <strong>Marvel TV</strong>, a <strong>Crystal Lake</strong> screening, <strong>Yaga</strong>, a preview of Blumhouse’s <strong>BlumFest</strong>, and <strong>Dexter: Resurrection</strong> Season 2.",
      "Guests are added continuously up to and during the show, so a schedule read in August is a floor, not a ceiling.",
      "## Tickets and the practical part",
      "Tickets are on sale. The convention runs a <strong>Fan Verification</strong> process for first-timers, and there is an app carrying the map of the Javits and the full panel schedule — the building is large enough that this is a genuine recommendation rather than a promotion.",
      "One thing worth knowing if you bought for a group: tickets have to be <strong>transferred</strong> to each person, not handed over, or your friend cannot access reservations on the day.",
      "## Getting to the Javits",
      "The Javits Center sits at <strong>429 11th Avenue</strong>, on the far west side at Hudson Yards. That is a longer walk from the subway than most New York venues, and the walk is on a stretch with very little on it — the 7 train to Hudson Yards is the shortest version of it.",
    ],
    expertise:
      "The twentieth-anniversary framing means the popular panels will be busier than the schedule suggests, and NYCC queues form for the room, not the panel — once you are inside a hall you can usually stay for the next session. Picking a room for a block of the afternoon beats picking four panels in four buildings.",
  },
  {
    slug: "village-halloween-parade-2026",
    featured: 3,
    site: "nyc42",
    image: "/covers/village-halloween-parade-2026.jpg",
    imageAlt: "Paper lanterns strung along a curve under a crescent moon",
    imageKind: "generated",
    imageWidth: 1536,
    imageHeight: 864,
    title: "Village Halloween Parade 2026",
    summary:
      "The 53rd parade goes up Sixth Avenue at 7pm on Saturday 31 October. Watching is free, joining in is free if you are in costume, and it happens rain or shine.",
    start: "2026-10-31",
    startTime: "19:00",
    utcOffset: "-04:00",
    city: "New York City",
    venue: "Sixth Avenue, Greenwich Village",
    category: "Parade",
    organizer: "Village Halloween Parade, Inc.",
    source: {
      name: "NYC Village Halloween Parade",
      url: "https://www.halloween-nyc.com/",
      verifiedOn: "2026-08-30",
    },
    body: [
      "New York’s <strong>53rd annual Village Halloween Parade</strong> steps off at <strong>7:00pm on Saturday 31 October 2026</strong>, up Sixth Avenue.",
      "The organisers put the important part in capitals on their own front page: <strong>rain or shine</strong>. Or wind.",
      "## The rule that makes it different",
      "<strong>Everyone is invited to watch. Anyone in costume is welcome to join in.</strong>",
      "That second sentence is the whole event. Almost every other parade in America is a procession of organisations that the public watches from a barrier; this one has no audition, no application and no float requirement. Turn up in costume and you are in it. It is the largest participatory parade in the country for exactly that reason, and it is why the thing has never looked corporate.",
      "## Halloween lands on a Saturday",
      "The parade is always on 31 October, whatever day that is — and in 2026 it falls on a <strong>Saturday</strong>. A Saturday-night Halloween in Manhattan is the maximum-density version of this: nobody has work the next morning, and the parade is a whole evening rather than a weeknight detour.",
      "Plan the getting-home part before the getting-there part.",
      "## What tickets are for",
      "Watching costs nothing and marching costs nothing. Tickets exist for <strong>special access</strong> — skipping the line to enter the parade, and grandstand-style viewing — and the parade is a <strong>501(c)(3) not-for-profit arts organisation</strong>, so buying one is closer to a donation than a fee.",
      "The parade is supported in part by public funds from the <strong>NYC Department of Cultural Affairs</strong> in partnership with the City Council.",
      "## What is not announced",
      "The <strong>2026 theme and Grand Marshal have not been published</strong>, so they do not appear here. For reference, 2025 ran under «It’s a Potluck!» with <strong>City Harvest</strong> as Grand Marshal — the organisation that rescues fresh produce and delivers it free across the five boroughs.",
      "There is also an official after party at <strong>House of Yes</strong> in Industry City, Brooklyn, from <strong>9:00pm</strong>, which is ticketed separately.",
    ],
    expertise:
      "The costume rule cuts both ways: if you are in costume you can join, and if you are in costume in the Village that night you will be swept into it whether you meant to be or not. For watching rather than marching, the north end of the route thins out considerably — the parade takes hours to pass, and the last third of it is the same parade with room to stand.",
  },
  {
    slug: "open-house-new-york-weekend-2026",
    site: "nyc42",
    image: "/covers/open-house-new-york-weekend-2026.jpg",
    imageAlt: "A paper cutaway of stacked building floors with a rooftop water tower",
    imageKind: "generated",
    imageWidth: 1536,
    imageHeight: 864,
    title: "Open House New York Weekend 2026",
    summary:
      "Three hundred buildings across the five boroughs open for one weekend, 16–18 October. OHNY has the lineup down for 25 September and tickets for 2 October.",
    start: "2026-10-16",
    end: "2026-10-18",
    city: "New York City",
    venue: "All five boroughs",
    category: "Architecture",
    organizer: "Open House New York",
    source: {
      name: "Open House New York",
      url: "https://ohny.org/festival",
      verifiedOn: "2026-08-30",
    },
    body: [
      "For one weekend in October the answer to «can you go in there?» is yes, about three hundred times over.",
      "<strong>OHNY Weekend runs 16 to 18 October 2026</strong> and unlocks <strong>300+ destinations</strong> across all five boroughs for behind-the-scenes tours and special activities.",
      "## What actually opens",
      "New buildings changing the skyline, and also: <strong>infrastructure facilities</strong> that keep the city running, parks, performance spaces, manufacturing workshops and private collections.",
      "The infrastructure is the part worth queuing for. Among the 2026 destinations already previewed is the <strong>Department of Sanitation’s Brooklyn District 3 Garage</strong> and the <strong>DOT Sign Shop</strong> in Maspeth, Queens — the place where the city’s street signs are actually made. Those are buildings no amount of money gets you into on an ordinary Tuesday, and they explain more about how New York works than any tower does.",
      "Also previewed: the <strong>Flatiron Building</strong>, <strong>Rockefeller Center Gardens</strong> and the <strong>Brooklyn Army Terminal</strong>.",
      "## The calendar before the calendar",
      "OHNY is unusual in that the month before the festival has its own schedule, and missing a date on it costs you access rather than information.",
      "Most sites you can simply show up to. A minority require <strong>tickets</strong>, because of space or security — and those are the ones that go in minutes on release day.",
      "## Five boroughs, and that is the instruction",
      "The festival is designed as a citywide event, not a Manhattan one, and the way to use it is to stay in one borough for a day rather than crossing three. A Sanitation garage in Brooklyn and a sign shop in Queens are not consolation prizes for missing the Flatiron; they are the festival.",
    ],
    programme: [
      { heading: "18 September — Members preview", text: "Members get early access to the Weekend lineup, and more time to plan." },
      { heading: "25 September — Public reveal", text: "The full lineup is published with all locations, activities, dates and times." },
      { heading: "2 October — Ticket release", text: "Most sites need no ticket; the ones limited by space or security release theirs now." },
      { heading: "15 October — Launch party", text: "The festival's fundraiser and official kick-off, with food, drinks and entertainment." },
      { heading: "16–18 October — The festival", text: "Three days of tours and visits across the five boroughs." },
    ],
    expertise:
      "Put 2 October in the diary rather than 16 October. The weekend itself is walk-up for most of the three hundred sites, so the only thing that can actually be missed by being slow is the ticketed handful — which is, reliably, the list of places everybody wanted to see.",
  },
  {
    slug: "broadway-week-harry-potter",
    site: "nyc42",
    image: "/covers/broadway-week-harry-potter.jpg",
    imageAlt: "A paper proscenium arch with curtains and a single shaft of light",
    imageKind: "generated",
    imageWidth: 1536,
    imageHeight: 864,
    title: "Harry Potter at Broadway Week",
    summary:
      "The two-for-one runs 8 to 20 September at the Lyric. It is the largest saving on the Broadway Week list, and the reason is the house rather than the play.",
    start: "2026-09-08",
    end: "2026-09-20",
    city: "New York City",
    venue: "Lyric Theatre, 213 West 42nd Street, Manhattan",
    geo: { name: "Lyric Theatre", lat: 40.756820, lng: -73.987484 },
    category: "Theatre",
    organizer: "New York City Tourism + Conventions",
    source: {
      name: "NYC Tourism + Conventions",
      url: "https://www.nyctourism.com/broadway-week/",
      verifiedOn: "2026-08-30",
    },
    body: [
      "Of the twenty-five productions in NYC Broadway Week, this is the one where the offer is worth the most — and it is worth reading why, because the reason is not that it is the best show on the list.",
      "## Why the saving is biggest here",
      "A two-for-one discounts a <em>seat</em>, not a production. It is worth most where the seat was expensive to begin with and where it is rarely cheap by any other route. <strong>Harry Potter and the Cursed Child</strong> is the longest and most technically elaborate thing on Broadway, it plays a big house, and it does not turn up week after week in the discount channels the way the long-running musicals do.",
      "Two-for-one on a rarely discounted ticket is a different purchase from two-for-one on a ticket that was going to be discounted anyway. This is the clearest case of the first kind on the list.",
      "## Where",
      "The <strong>Lyric Theatre</strong>, on West 43rd Street between Seventh and Eighth — its street address is 213 West 42nd. It is one of the largest houses on Broadway, which is both why the ticket is expensive and why the gap between a good seat and a poor one is wide.",
      "## The catch",
      "The offer exists for the fortnight, not for every performance in it. Each production sets its own <strong>blackout dates</strong> and releases its own allocation of eligible seats. Check this listing for the night you actually want before you book anything around it — a dinner reservation on a blacked-out night is the usual way this goes wrong.",
    ],
    expertise:
      "Because this is a long evening in a big house, the seat you are allocated matters more here than almost anywhere else on the list. If the offer comes back with only the back of the balcony, it is worth checking what a mid-house seat costs at full price before accepting: on a show built this heavily on stagecraft, the cheap pair can cost you the thing you came for.",
  },
  {
    slug: "broadway-week-hadestown",
    site: "nyc42",
    image: "/covers/broadway-week-hadestown.jpg",
    imageAlt: "A paper staircase descending into darkness",
    imageKind: "generated",
    imageWidth: 1536,
    imageHeight: 864,
    title: "Hadestown at Broadway Week",
    summary:
      "Anaïs Mitchell's Orpheus and Eurydice takes the two-for-one from 8 to 20 September at the Walter Kerr. The one on the list most likely to be the best evening rather than the best deal.",
    start: "2026-09-08",
    end: "2026-09-20",
    city: "New York City",
    venue: "Walter Kerr Theatre, 219 West 48th Street, Manhattan",
    geo: { name: "Walter Kerr Theatre", lat: 40.760681, lng: -73.985585 },
    category: "Theatre",
    organizer: "New York City Tourism + Conventions",
    source: {
      name: "NYC Tourism + Conventions",
      url: "https://www.nyctourism.com/broadway-week/",
      verifiedOn: "2026-08-30",
    },
    body: [
      "Every Broadway Week list mixes two different things: shows where the offer is worth the most, and shows you should see. <strong>Hadestown</strong> is on this list for the second reason.",
      "## The show",
      "Anaïs Mitchell’s retelling of Orpheus and Eurydice, staged as a smoky, jazz-inflected underworld with the band on stage. It began life as a folk album and was built outward from the songs, which is audible: the score carries the storytelling rather than decorating it.",
      "## Why it is not first on the list",
      "Only because it is easier to reach cheaply by other means than the biggest, newest productions are. If you are optimising purely for money saved, there are better uses of the offer. If you are optimising for the evening, this is the one to spend it on — Broadway Week is the excuse to stop putting it off.",
      "## Where",
      "The <strong>Walter Kerr Theatre</strong>, 219 West 48th Street. It is a mid-sized house, which suits a show that works on intimacy and a live band far better than a barn would.",
      "## The catch",
      "Each production sets its own <strong>blackout dates</strong> and releases its own allocation. The offer running from 8 to 20 September and the offer running on the night you can go are two different questions; only the second one decides anything.",
    ],
    expertise:
      "In a house this size the difference between the orchestra and the front mezzanine is smaller than the price difference suggests, and the band is on stage rather than in a pit. If the allocation offers a mezzanine pair, take it rather than holding out — sightlines here are forgiving in a way they are not at the larger houses on the list.",
  },
  {
    slug: "broadway-week-stranger-things",
    site: "nyc42",
    image: "/covers/broadway-week-stranger-things.jpg",
    imageAlt: "Bare paper trees mirrored above and below a horizon",
    imageKind: "generated",
    imageWidth: 1536,
    imageHeight: 864,
    title: "Stranger Things at Broadway Week",
    summary:
      "The First Shadow takes the two-for-one from 8 to 20 September at the Marquis. Recent, effects-heavy and in a big house — which is what makes the offer valuable and the seat allocation risky.",
    start: "2026-09-08",
    end: "2026-09-20",
    city: "New York City",
    venue: "Marquis Theatre, 210 West 46th Street, Manhattan",
    geo: { name: "Marquis Theatre", lat: 40.758904, lng: -73.986185 },
    category: "Theatre",
    organizer: "New York City Tourism + Conventions",
    source: {
      name: "NYC Tourism + Conventions",
      url: "https://www.nyctourism.com/broadway-week/",
      verifiedOn: "2026-08-30",
    },
    body: [
      "<strong>Stranger Things: The First Shadow</strong> follows the same logic as the Potter play, and carries the same warning.",
      "## Why the offer is worth a lot here",
      "It is recent, it is effects-heavy, and it plays a large house. All three push the full-price ticket up and keep it out of the routine discount channels, which is exactly the combination that makes a two-for-one worth more than the arithmetic suggests.",
      "## And why it is the riskiest on the list",
      "The difference between a good seat and a bad one is unusually wide in a show built on stagecraft, and it is the allocation, not you, that decides which one you get. This is the one production here where the saving can cost you the point of the evening: the effects are the argument, and from the back of the balcony the argument is quieter.",
      "## Where",
      "The <strong>Marquis Theatre</strong>, 210 West 46th Street, inside the Marriott Marquis. It is one of the few Broadway houses that is not at street level — the auditorium is several floors up, which is worth knowing if you are arriving close to curtain.",
      "## The catch",
      "<strong>Blackout dates</strong> are set per production, and the eligible seats are a limited allocation at each theatre’s discretion. Check this listing for your night before booking anything around it.",
    ],
    expertise:
      "Ask what section the two-for-one pair is in before you accept it. On a spectacle show the honest comparison is not “free ticket versus paid ticket” but “two poor seats versus one good one”, and for this production that comparison genuinely goes either way.",
  },
  {
    slug: "broadway-week-six",
    site: "nyc42",
    image: "/covers/broadway-week-six.jpg",
    imageAlt: "Six paper microphones in a row with a small crown above the middle one",
    imageKind: "generated",
    imageWidth: 1536,
    imageHeight: 864,
    title: "Six at Broadway Week",
    summary:
      "Eighty minutes, no interval, Tudor England as a pop concert. On the two-for-one from 8 to 20 September at the Lena Horne — the cheapest way this fortnight to put two people in a Broadway theatre.",
    start: "2026-09-08",
    end: "2026-09-20",
    city: "New York City",
    venue: "Lena Horne Theatre, 256 West 47th Street, Manhattan",
    geo: { name: "Lena Horne Theatre", lat: 40.759975, lng: -73.986966 },
    category: "Theatre",
    organizer: "New York City Tourism + Conventions",
    source: {
      name: "NYC Tourism + Conventions",
      url: "https://www.nyctourism.com/broadway-week/",
      verifiedOn: "2026-08-30",
    },
    body: [
      "<strong>Six</strong> is the shortest thing on the Broadway Week list, and that turns out to be its whole practical argument.",
      "## The show",
      "The six wives of Henry VIII, staged as a pop concert in which each queen takes the microphone to argue that she had the worst of it. <strong>Eighty minutes, no interval</strong>, no set changes to wait through.",
      "## Why the length matters",
      "Two reasons, both logistical. It is the easiest show on the list to pair with something else in the same day — a matinee here leaves the evening intact. And it is the easiest to take a teenager to, because eighty minutes is inside the attention span that a three-hour book musical is not.",
      "On a two-for-one it is also, simply, the cheapest way this fortnight to get two people inside a Broadway theatre at all.",
      "## Where",
      "The <strong>Lena Horne Theatre</strong>, 256 West 47th Street — a smaller house, renamed in 2022. In a room this size the concert staging works the way it is meant to.",
      "## The catch",
      "Each production sets its own <strong>blackout dates</strong> and its own allocation of eligible seats. Confirm the night before you build a day around it.",
    ],
    expertise:
      "Because there is no interval, latecomers are held longer here than at a show with a natural break to seat them at. Eighty minutes also means the theatre empties early — a matinee finishes well before the pre-theatre dinner rush, which is the one evening this fortnight where restaurants around Times Square are easy at 6pm.",
  },
  {
    slug: "broadway-week-oh-mary",
    site: "nyc42",
    image: "/covers/broadway-week-oh-mary.jpg",
    imageAlt: "A tied-back paper drape and a single lit spot on an empty stage",
    imageKind: "generated",
    imageWidth: 1536,
    imageHeight: 864,
    title: "Oh Mary! at Broadway Week",
    summary:
      "The comedy on the Broadway Week list, at the Lyceum from 8 to 20 September. In a house this small the offer buys proximity rather than merely a seat.",
    start: "2026-09-08",
    end: "2026-09-20",
    city: "New York City",
    venue: "Lyceum Theatre, 149 West 45th Street, Manhattan",
    geo: { name: "Lyceum Theatre", lat: 40.757869, lng: -73.984501 },
    category: "Theatre",
    organizer: "New York City Tourism + Conventions",
    source: {
      name: "NYC Tourism + Conventions",
      url: "https://www.nyctourism.com/broadway-week/",
      verifiedOn: "2026-08-30",
    },
    body: [
      "<strong>Oh, Mary!</strong> is the comedy on the Broadway Week list, and the one production here whose ticket price has least to do with spectacle.",
      "## Why that changes the maths",
      "Most of the list is big houses where you are paying for stagecraft and the seat determines how much of it reaches you. This is the opposite case. The <strong>Lyceum</strong> is one of the smallest Broadway houses, so the offer buys <em>proximity</em> rather than merely a seat — and in a small room built for a comic performance, proximity is most of what you were paying for in the first place.",
      "A two-for-one on a comedy in a 900-seat house is a materially different purchase from a two-for-one in a 1,600-seat musical barn. It is also the case on this list where the worst available seat is least likely to ruin the evening.",
      "## Where",
      "The <strong>Lyceum Theatre</strong>, 149 West 45th Street — the oldest continuously operating Broadway theatre, opened in 1903, and a landmarked building inside and out.",
      "## The catch",
      "<strong>Blackout dates</strong> are set per production and the discounted seats are a limited allocation. A small house means a small allocation: this is one to check early rather than late in the fortnight.",
    ],
    expertise:
      "Small house, small allocation. The two-for-one inventory at the Lyceum is a fraction of what the Gershwin or the Lyric can release, so the practical advice differs from the rest of the list: for this one, treat the on-sale date as the deadline rather than the offer's closing date.",
  },
  {
    slug: "broadway-week-the-lion-king",
    site: "nyc42",
    image: "/covers/broadway-week-the-lion-king.jpg",
    imageAlt: "A paper sun rising behind a lone tree over layered savannah bands",
    imageKind: "generated",
    imageWidth: 1536,
    imageHeight: 864,
    title: "The Lion King at Broadway Week",
    summary:
      "On the two-for-one from 8 to 20 September at the Minskoff. One of the safest evenings in New York — and one of the three shows on the list where the offer is doing the least work.",
    start: "2026-09-08",
    end: "2026-09-20",
    city: "New York City",
    venue: "Minskoff Theatre, 1515 Broadway, Manhattan",
    geo: { name: "Minskoff Theatre", lat: 40.758063, lng: -73.986205 },
    category: "Theatre",
    organizer: "New York City Tourism + Conventions",
    source: {
      name: "NYC Tourism + Conventions",
      url: "https://www.nyctourism.com/broadway-week/",
      verifiedOn: "2026-08-30",
    },
    body: [
      "<strong>The Lion King</strong> is on the Broadway Week list, and it is worth being straightforward about what that is worth.",
      "## The honest position",
      "This is one of the longest-running productions on the list and one of the safest evenings in New York. It is also one of the most reliably available at <em>some</em> reduced price in any given month. Using a Broadway Week ticket on it is not a mistake — it is simply the purchase where the offer is doing the least work, because the alternative to the offer was not full price.",
      "That is a statement about the discount market, not about the show. Julie Taymor’s staging has been the reason people book it since 1997, and it is the reason it still fills a 1,600-seat house.",
      "## When it is the right call anyway",
      "If you are booking for children, the calculation changes completely. The offer is fully transferable to a family plan, the running time and the matinee schedule suit it, and the reliability that makes it a weak <em>deal</em> is exactly what you want when the evening has to work.",
      "## Where",
      "The <strong>Minskoff Theatre</strong>, 1515 Broadway at West 45th Street. Like the Marquis, the auditorium is above street level.",
      "## The catch",
      "Each production sets its own <strong>blackout dates</strong> and allocation. Weekend matinees are the first to go on a family show.",
    ],
    expertise:
      "Compare the two-for-one against the discount you could get anyway before deciding. For the long-runners this is the question that decides whether Broadway Week saved you anything, and it is the one question the offer's own marketing never asks.",
  },
  {
    slug: "broadway-week-wicked",
    site: "nyc42",
    image: "/covers/broadway-week-wicked.jpg",
    imageAlt: "A green paper hat curled on an amber disc",
    imageKind: "generated",
    imageWidth: 1536,
    imageHeight: 864,
    title: "Wicked at Broadway Week",
    summary:
      "Two-for-one at the Gershwin from 8 to 20 September. A long-runner in Broadway's largest house — reliable, and reliably discounted the rest of the year too.",
    start: "2026-09-08",
    end: "2026-09-20",
    city: "New York City",
    venue: "Gershwin Theatre, 222 West 51st Street, Manhattan",
    geo: { name: "Gershwin Theatre", lat: 40.762362, lng: -73.985204 },
    category: "Theatre",
    organizer: "New York City Tourism + Conventions",
    source: {
      name: "NYC Tourism + Conventions",
      url: "https://www.nyctourism.com/broadway-week/",
      verifiedOn: "2026-08-30",
    },
    body: [
      "<strong>Wicked</strong> takes the Broadway Week offer, and sits in the same category as the other long-runners on the list.",
      "## What the offer is really worth here",
      "It is among the three most reliably available at some reduced price in any given month, which means the two-for-one is competing against a discount you could probably have found anyway. The saving is real; it is just smaller than the headline implies once you compare it to the right baseline rather than to the full price.",
      "## The house is the argument for going anyway",
      "The <strong>Gershwin Theatre</strong>, 222 West 51st Street, is the largest theatre on Broadway. That cuts both ways: there is more inventory to release into an offer like this one, so the odds of getting a decent pair of seats are better here than at the small houses — and the range between the best and worst seat is correspondingly enormous.",
      "For a show with this much scenery, a large allocation in a large house is genuinely useful. It is one of the few places on the list where being flexible about the night is likely to be rewarded.",
      "## The catch",
      "<strong>Blackout dates</strong> are set per production and the eligible seats are limited and at the theatre’s discretion. Check this listing for the specific night rather than assuming the fortnight.",
    ],
    expertise:
      "The Gershwin's size is the reason to check back more than once. Large houses release eligible seats in waves rather than all at the on-sale date, so an allocation that looks poor on day one is often better a week in — which is the opposite of the advice for the small houses on this list.",
  },
  {
    slug: "broadway-week-chicago",
    site: "nyc42",
    image: "/covers/broadway-week-chicago.jpg",
    imageAlt: "A bentwood chair silhouette against a paper sunburst",
    imageKind: "generated",
    imageWidth: 1536,
    imageHeight: 864,
    title: "Chicago at Broadway Week",
    summary:
      "The longest-running American musical on Broadway takes the two-for-one from 8 to 20 September at the Ambassador. A safe evening, and the offer's least necessary use.",
    start: "2026-09-08",
    end: "2026-09-20",
    city: "New York City",
    venue: "Ambassador Theatre, 219 West 49th Street, Manhattan",
    geo: { name: "Ambassador Theatre", lat: 40.761235, lng: -73.984990 },
    category: "Theatre",
    organizer: "New York City Tourism + Conventions",
    source: {
      name: "NYC Tourism + Conventions",
      url: "https://www.nyctourism.com/broadway-week/",
      verifiedOn: "2026-08-30",
    },
    body: [
      "<strong>Chicago</strong> is on the Broadway Week list, and like the other long-runners it is a strong evening and a weak deal.",
      "## Why the deal is weak",
      "It is one of the three productions here most reliably available at a reduced price in any given month. A two-for-one that competes with a discount you could find anyway is saving you the difference between two discounts, not half the price.",
      "## Why the evening is strong",
      "The staging is the concert version that came out of the 1996 Encores! revival and never left: the orchestra on stage, black costumes, almost no scenery. That look reads today as a deliberate minimalist choice, and it was originally the constraint of a concert staging that worked too well to undo.",
      "It also means the seat matters less than at any other big-house show on this list. There is no scenery to be blocked by and nothing happening upstage that you need a sightline for.",
      "## Where",
      "The <strong>Ambassador Theatre</strong>, 219 West 49th Street, where the revival has played since January 2003.",
      "## The catch",
      "<strong>Blackout dates</strong> and the size of the eligible allocation are set by the production, not by the offer. Check the night you want.",
    ],
    expertise:
      "This is the one show on the list where accepting a cheap seat costs you almost nothing. With the band on stage and no set to speak of, the rear mezzanine sees the same production as the orchestra — so if the allocation comes back high and far, take it here rather than at the spectacle shows.",
  },
  {
    slug: "broadway-week-fall-2026",
    featured: 2,
    site: "nyc42",
    image: "/covers/broadway-week-fall-2026.jpg",
    imageAlt: "A row of paper theatre marquee canopies",
    imageKind: "generated",
    imageWidth: 1536,
    imageHeight: 864,
    title: "NYC Broadway Week: two-for-one at 25 shows",
    summary:
      "Two weeks of 2-for-1 Broadway tickets across 25 productions, from 8 to 20 September 2026. Tickets have been on sale since 18 August.",
    start: "2026-09-08",
    end: "2026-09-20",
    city: "New York City",
    category: "Theatre",
    organizer: "New York City Tourism + Conventions",
    source: {
      name: "NYC Tourism + Conventions",
      url: "https://www.nyctourism.com/broadway-week/",
      verifiedOn: "2026-08-30",
    },
    body: [
      "NYC Broadway Week runs from <strong>8 to 20 September 2026</strong>. Twenty-five productions take part, and the offer is the one it has always been: buy two tickets, pay for one. Sales opened on 18 August.",
      "## What is in it",
      "&amp; Juliet, Aladdin, The Book of Mormon, Buena Vista Social Club, Chicago, The Great Gatsby, Hadestown, Harry Potter and the Cursed Child, Just in Time, The Lion King, The Lost Boys, Maybe Happy Ending, MJ, Oh Mary!, Operation Mincemeat, The Outsiders, Paranormal Activity, The Rocky Horror Show, Schmigadoon!, School Girls; Or, the African Mean Girls Play, Six, Stranger Things: The First Shadow, Titaníque, Two Strangers (Carry a Cake Across New York) and Wicked.",
      "It is a wide list on purpose: long-runners that will still be there next year sit beside productions in their first season, and at half price those are worth very different things.",
      "## The catch is the calendar, not the price",
      "Each show sets its own <strong>blackout dates</strong> and releases its own allocation. The offer existing on a given day and the offer existing for the show you want on that day are two separate questions, and only the second decides your evening.",
      "Check the individual listing before committing, and before booking anything around it. The usual way this goes wrong is a dinner reservation made for a night the show had blacked out.",
      "## Seats, not shows",
      "A two-for-one discounts a seat rather than a production, so it is worth most where the seat was expensive to begin with. In a big house built on stagecraft the gap between a good seat and a bad one is wide, and the allocation decides which you get. In a small house the same offer buys proximity — which is most of what the ticket was for.",
    ],
    expertise:
      "Broadway Week runs twice a year, in January and September, and the September edition lands in the quiet stretch after the summer tourists and before the holiday run-up — which is why the discounted seats tend to be better ones than the winter edition offers.",
  },

  {
    slug: "brooklyn-book-festival-2026",
    site: "nyc42",
    image: "/covers/brooklyn-book-festival-2026.jpg",
    imageAlt: "A close row of book blocks in orange, red, cream and grey on charcoal brown, their tops uneven",
    imageKind: "generated",
    imageWidth: 1536,
    imageHeight: 864,
    title: "Brooklyn Book Festival 2026",
    summary:
      "Nine days of Bookend events across Brooklyn from September 20, Children's Day on the 26th, and Festival Day on Sunday the 27th — eight stages around Borough Hall in New York, free.",
    start: "2026-09-20",
    end: "2026-09-28",
    utcOffset: "-04:00",
    venue: "Brooklyn Borough Hall and surrounding venues",
    city: "Brooklyn",
    country: "United States",
    organizer: "Brooklyn Book Festival, Inc. and the Brooklyn Book Festival Literary Council",
    category: "Books",
    tickets: { priceFrom: 0, currency: "USD" },
    source: {
      name: "Brooklyn Book Festival",
      url: "https://www.brooklynbookfestival.org/",
      verifiedOn: "2026-09-08",
    },
    body: [
      "Most literary festivals put a few hundred people in a tent. This one takes over a civic centre, opens eight stages at once, and charges nothing.",
      "## The three parts",
      "<strong>Bookend events</strong> run across Brooklyn from <strong>September 20 to September 28, 2026</strong>. <strong>Children's Day</strong> is <strong>Saturday, September 26</strong> at Brooklyn Borough Hall, 209 Joralemon St. <strong>Festival Day and the Literary Marketplace</strong> is <strong>Sunday, September 27</strong>.",
      "## Festival Day",
      "Eight indoor and outdoor stages at <strong>Brooklyn Borough Hall</strong>, <strong>Brooklyn Law School</strong>, the <strong>Center for Brooklyn History</strong>, <strong>St. Ann &amp; the Holy Trinity Church</strong>, <strong>Columbus Park</strong> and <strong>Korean War Veterans Park</strong>, with the Literary Marketplace running alongside.",
      "## Who is reading",
      "Announced authors include <strong>Marlon James</strong>, <strong>Joyce Carol Oates</strong>, <strong>Namwali Serpell</strong> and <strong>Douglas Stuart</strong>. The festival is overwhelmingly free to the public.",
    ],
    expertise:
      "Festival Day is the famous one and the Bookend events are the better ones. The week before is when individual bookshops, bars and libraries across the borough host single readings — smaller rooms, one author, and no need to choose between eight stages running at the same hour. Plan Sunday backwards from the two panels you actually want and accept that you will miss the rest; the Literary Marketplace is worth an hour on its own, and it is quietest before noon. Borough Hall is on the 2/3, 4/5 and R at Borough Hall and Court Street, which is as easy as arriving anywhere in Brooklyn gets.",
  },

  {
    slug: "feast-of-san-gennaro-2026",
    site: "nyc42",
    image: "/covers/feast-of-san-gennaro-2026.jpg",
    imageAlt: "A string of small amber lamps hung in a line across a dark brown ground",
    imageKind: "generated",
    imageWidth: 1536,
    imageHeight: 864,
    title: "Feast of San Gennaro 2026",
    summary:
      "Eleven days of New York's Little Italy given over to the feast, September 17 to 27, free to walk into, with the Grand Procession on Saturday the 26th from 2pm.",
    start: "2026-09-17",
    end: "2026-09-27",
    utcOffset: "-04:00",
    venue: "Mulberry Street, Little Italy",
    city: "New York",
    country: "United States",
    organizer: "Figli di San Gennaro",
    category: "Festival",
    tickets: { priceFrom: 0, currency: "USD" },
    source: {
      name: "Feast of San Gennaro",
      url: "https://sangennaronyc.org/",
      verifiedOn: "2026-09-08",
    },
    ticket: { url: "https://sangennaronyc.org/", label: "More details" },
    body: [
      "For eleven days a working stretch of downtown stops being a street. The Feast of San Gennaro is the oldest and largest of New York's Italian-American street feasts, and the thing to understand before going is that it is a religious procession with a fair around it, not a fair with a saint's name on it.",
      "## The dates",
      "<strong>September 17 to September 27, 2026</strong>, in Little Italy.",
      "## Where it runs",
      "<strong>Mulberry Street</strong> between Canal and Houston, <strong>Hester Street</strong> between Baxter and Centre, and <strong>Grand Street</strong> between Baxter and Centre Market Place.",
      "## The Grand Procession",
      "<strong>Saturday, September 26, 2pm to 4pm</strong>: the statue is carried through the streets, with live music. The <strong>Solemn High Mass</strong> is on <strong>September 19</strong>.",
      "## What it costs",
      "Nothing to walk in. The daily opening and closing times are not published on the feast's own site, so no hours appear here.",
    ],
    faq: [
      {
        q: "Is the Feast of San Gennaro free?",
        a: "Yes. The streets are open and there is <strong>no admission charge</strong>; you pay only for what you eat and for the games.",
      },
      {
        q: "When is the Feast of San Gennaro 2026?",
        a: "<strong>September 17 to September 27, 2026</strong>, eleven days in Little Italy.",
      },
      {
        q: "When is the Grand Procession?",
        a: "<strong>Saturday, September 26, from 2pm to 4pm</strong>, with the statue carried through the streets and live music.",
      },
      {
        q: "Which streets does the feast cover?",
        a: "Mulberry Street from Canal to Houston, Hester Street from Baxter to Centre, and Grand Street from Baxter to Centre Market Place.",
      },
    ],
    expertise:
      "Two weekends and nine weekdays, and they are not the same event. The weekend nights on Mulberry are shoulder-to-shoulder, which is the picture everyone has of the feast and also the reason people leave after twenty minutes; a Tuesday evening is the same food and the same stalls with room to stand still. If the point of going is the procession, that is Saturday the 26th and it is the one date that cannot be moved. And the side streets matter: Hester and Grand carry the same feast with a fraction of the crowd, and the queues on Mulberry are for the stands nearest the entrance, not for the best of them.",
  },

  {
    slug: "climate-week-nyc-2026",
    site: "nyc42",
    image: "/covers/climate-week-nyc-2026.jpg",
    imageAlt: "A row of tall dark towers of falling height across a pale amber ground, one orange circle low behind them",
    imageKind: "generated",
    imageWidth: 1536,
    imageHeight: 864,
    title: "Climate Week NYC 2026",
    summary:
      "Eight days of climate business and policy events across New York, September 20 to 27, run by the Climate Group alongside the UN General Assembly, drawing over a hundred thousand people a year.",
    start: "2026-09-20",
    end: "2026-09-27",
    utcOffset: "-04:00",
    city: "New York",
    country: "United States",
    organizer: "Climate Group",
    category: "Summit",
    source: {
      name: "Climate Week NYC",
      url: "https://www.climateweeknyc.org/",
      verifiedOn: "2026-09-08",
    },
    ticket: { url: "https://www.climateweeknyc.org/", label: "The calendar" },
    body: [
      "For one week in September the city carries a second conference on top of itself, and most of it is not in one building. Climate Week NYC is a calendar rather than a venue: hundreds of separately run events across Manhattan and Brooklyn, held under one name and one set of dates.",
      "## The dates",
      "<strong>September 20 to September 27, 2026</strong>, across New York City.",
      "## Who runs it",
      "The <strong>Climate Group</strong>, an international non-profit. It sets the dates and the main programme; the rest of the calendar is filled by organisations registering their own events under it.",
      "## The scale",
      "The organisers put attendance at <strong>over 100,000 people a year</strong>, which makes it the largest annual gathering of its kind in the city.",
      "## What is on the 2026 calendar",
      "Among the featured events: investor and family-office summits, clean energy trade and the grid, methane reduction, the circular economy and aluminium recycling, and the electricity demand of AI.",
      "## Getting in",
      "There is no single ticket. Each event on the calendar sets its own terms — some open, some by registration, some invitation only — so the calendar entry is the thing to read, not the week.",
    ],
    faq: [
      {
        q: "When is Climate Week NYC 2026?",
        a: "<strong>September 20 to September 27, 2026</strong>, across New York City.",
      },
      {
        q: "Is there one ticket for Climate Week NYC?",
        a: "No. Climate Week is a calendar of separately run events, and <strong>each one sets its own admission</strong> — some open to anyone, some by registration, some invitation only.",
      },
      {
        q: "Who organises Climate Week NYC?",
        a: "The Climate Group, an international non-profit, which sets the dates and the main programme while other organisations register their own events under it.",
      },
      {
        q: "How big is Climate Week NYC?",
        a: "The organisers put attendance at over 100,000 people a year.",
      },
    ],
    expertise:
      "The mistake is treating it as a conference you attend. There is no badge that opens the week: the main programme is a small share of it, and the hundreds of events around it are run by whoever registered them, each with its own door policy. What that means in practice is that the useful planning happens on the calendar page a fortnight out, when the open events are still taking registrations — by the week itself the ones worth going to are full. The second thing worth knowing is what it does to the city: it runs alongside the UN General Assembly, and midtown east of Fifth is slower all week.",
  },

  {
    slug: "burning-man-2026",
    site: "nyc42",
    image: "/covers/burning-man-2026.jpg",
    imageAlt: "Two amber paper rings around a pale disc, with one small upright amber rectangle standing at the centre, on a dark brown ground",
    imageKind: "generated",
    imageWidth: 1536,
    imageHeight: 864,
    title: "Burning Man 2026",
    summary:
      "A city of tens of thousands went up in the Nevada desert from August 30 to September 7 under the theme Axis Mundi, and then came down. The 2027 dates are already set.",
    start: "2026-08-30",
    end: "2026-09-07",
    utcOffset: "-07:00",
    venue: "Black Rock City, Black Rock Desert",
    city: "Black Rock City",
    country: "United States",
    organizer: "Burning Man Project",
    category: "Festival",
    source: {
      name: "Burning Man Project",
      url: "https://burningman.org/black-rock-city/black-rock-city-2026/",
      verifiedOn: "2026-09-08",
    },
    ticket: { url: "https://burningman.org/event/", label: "Official site" },
    body: [
      "It ended the day before yesterday. Black Rock City exists for eight days a year and is dismantled to nothing afterwards \u2014 which is the part that makes it worth reading about after it is over rather than before, because what there is to plan for is the next one.",
      "## The dates",
      "<strong>August 30 to September 7, 2026</strong>, in the <strong>Black Rock Desert</strong> in Nevada. The next edition is <strong>August 29 to September 6, 2027</strong>.",
      "## The theme",
      "<strong>Axis Mundi</strong> \u2014 the world axis \u2014 which the organisers describe as being about interconnectedness, shared social realities and our ties to the natural world. The theme names the concentric streets of the city and shapes the two structures everything else is arranged around: the Man Pavilion, called <strong>Cryptomeria</strong>, and the <strong>Temple of the Moon</strong>, whose form came from the queen of the night, a desert cactus flower that opens for one night.",
      "## What it is not",
      "It is not a music festival with a ticket and a line-up. The event runs on the <strong>10 Principles</strong>, of which the two that surprise people are <strong>decommodification</strong> \u2014 no vending, no sponsorship, no logos, nothing bought or sold on the playa beyond ice and coffee \u2014 and <strong>participation</strong>, which is the reason there is no audience. Everything present was brought and built by someone who came.",
      "## Getting in",
      "Attendance is by ticket and the sales are staged through the year rather than opened once, so the useful thing to know in September is that the process for the following August has already started. Volunteer crews, theme camps and art projects all place months ahead.",
    ],
    faq: [
      {
        q: "When is Burning Man 2027?",
        a: "<strong>August 29 to September 6, 2027</strong>, in the Black Rock Desert. The 2026 event ran August 30 to September 7.",
      },
      {
        q: "What was the 2026 theme?",
        a: "<strong>Axis Mundi</strong>, the world axis \u2014 about interconnectedness and our ties to the natural world. It named the city's streets, the Man Pavilion (<em>Cryptomeria</em>) and the Temple of the Moon.",
      },
      {
        q: "Can you buy things at Burning Man?",
        a: "No. <strong>Decommodification</strong> is one of the 10 Principles: there is no vending and no sponsorship on the playa, and ice and coffee are the stated exceptions. Everything else has to be carried in.",
      },
      {
        q: "Is it a music festival?",
        a: "No, and the difference is the principle of <strong>participation</strong>: there is no audience. What is there was built by the people who came, and it is taken away again when the city is dismantled.",
      },
    ],
    expertise:
      "The mistake a New Yorker makes with this one is treating it as a trip to book. It is not a destination with a season \u2014 it is a city that has to be provisioned, and the useful comparison is not to a festival weekend but to camping in a desert with no water and no shops for nine days, in a place that reaches the high thirties by day and drops sharply at night. That is also why the ticket is the small problem and the logistics are the large one: the tickets are staged through the year and there are several routes to one, but nothing sold in Reno on the Friday will make up for what was not packed. If the year is a maybe, the thing to do in September is not to look at tickets, it is to read the Survival Guide the organisers publish and decide honestly whether that is a holiday.",
  },

  {
    slug: "sxsw-2027",
    site: "nyc42",
    image: "/covers/sxsw-2027.jpg",
    imageAlt: "A long row of narrow paper bars in amber, ochre and cream, standing together on one level line, on a dark brown ground",
    imageKind: "generated",
    imageWidth: 1536,
    imageHeight: 864,
    title: "SXSW 2027",
    summary:
      "Austin's conference, film, music and comedy festivals run together March 15 to 21, 2027. Badges start at $550 and the early-bird prices end on September 17.",
    start: "2027-03-15",
    end: "2027-03-21",
    utcOffset: "-05:00",
    venue: "Austin Convention Center and venues across the city",
    city: "Austin",
    country: "United States",
    organizer: "SXSW",
    category: "Convention",
    tickets: { priceFrom: 550, priceTo: 1395, currency: "USD" },
    source: {
      name: "SXSW",
      url: "https://www.sxsw.com/",
      verifiedOn: "2026-09-08",
    },
    ticket: { url: "https://www.sxsw.com/", label: "Badges" },
    body: [
      "Four festivals share one week and one city, and the badge you buy decides which of them you are actually at. That is the whole decision, and it is cheaper if it is made this month.",
      "## The dates",
      "<strong>March 15 to 21, 2027</strong>, in <strong>Austin, Texas</strong>. The event has run since <strong>1987</strong>.",
      "## The four halves of it",
      "The <strong>Innovation Conference</strong>, the <strong>Film &amp; TV Festival</strong>, the <strong>Music Festival</strong> and the <strong>Comedy Festival</strong>, with <strong>13 content tracks</strong> across them \u2014 among them tech and AI, startups, the creator economy, design, health, gaming, sport and climate.",
      "## The badges",
      "<strong>Platinum, $1,395</strong> \u2014 all four. <strong>Innovation, $895.</strong> <strong>Film &amp; TV, $775.</strong> <strong>Music, $550.</strong> Group rates exist.",
      "## The deadline that matters now",
      "Early-bird pricing runs to <strong>September 17</strong>, and the organisers put the gap between it and the walk-up rate at <strong>up to $900</strong>. That is the largest single number on this page and it expires six months before the event.",
    ],
    faq: [
      {
        q: "When is SXSW 2027?",
        a: "<strong>March 15 to 21, 2027</strong>, in Austin, Texas.",
      },
      {
        q: "How much is an SXSW badge?",
        a: "<strong>$550</strong> for Music, <strong>$775</strong> for Film &amp; TV, <strong>$895</strong> for Innovation and <strong>$1,395</strong> for Platinum, which covers all four festivals.",
      },
      {
        q: "When does early-bird pricing end?",
        a: "<strong>September 17.</strong> The organisers put the saving against the walk-up rate at up to <strong>$900</strong>.",
      },
      {
        q: "Do I need the Platinum badge?",
        a: "Only if you intend to move between the four festivals. A single-festival badge is a third of the price, and the four run at once rather than in sequence \u2014 so the question is how much of the week you would really spend outside your own track.",
      },
    ],
    expertise:
      "The badge tiers are not a quality ladder, they are a map of the week, and the $845 between Music and Platinum buys optionality rather than access to anything better. Most people who buy Platinum spend the week in one or two tracks anyway, because the four festivals run concurrently in venues spread across a city and the walking is real. The other thing worth knowing from New York is that March in Austin is the week the whole industry is there, which means flights and rooms are priced accordingly and are booked long before the badge deadline \u2014 the $900 saved on the early bird is easy to lose twice over on a hotel booked in January.",
  },

  {
    slug: "ces-2027",
    site: "nyc42",
    image: "/covers/ces-2027.jpg",
    imageAlt: "A dense grid of small textured paper squares filling the frame, with one larger bright amber square alone in a clear space at the centre",
    imageKind: "generated",
    imageWidth: 1536,
    imageHeight: 864,
    title: "CES 2027",
    summary:
      "The Consumer Technology Association's show returns to Las Vegas from January 6 to 9, 2027, with registration already open and no public price published.",
    start: "2027-01-06",
    end: "2027-01-09",
    utcOffset: "-08:00",
    venue: "Las Vegas Convention Center and venues across the city",
    city: "Las Vegas",
    country: "United States",
    organizer: "Consumer Technology Association",
    category: "Convention",
    source: {
      name: "CES",
      url: "https://www.ces.tech/",
      verifiedOn: "2026-09-08",
    },
    ticket: { url: "https://www.ces.tech/", label: "Registration" },
    body: [
      "The first big week of the year, and the one that sets what the rest of it will be arguing about.",
      "## The dates",
      "<strong>January 6 to 9, 2027</strong>, in <strong>Las Vegas</strong>, organised by the <strong>Consumer Technology Association</strong>.",
      "## Who it is for",
      "The organisers describe the audience as global brands, industry professionals, decision makers, media and influencers. <strong>Registration is open.</strong> No admission price is published on the show's own front page, and no attendance or exhibitor figure is given there either \u2014 so neither appears here.",
    ],
    faq: [
      {
        q: "When is CES 2027?",
        a: "<strong>January 6 to 9, 2027</strong>, in Las Vegas.",
      },
      {
        q: "How much does CES cost to attend?",
        a: "The show does not publish a price on its own front page. Registration is open and the fee is shown during registration.",
      },
      {
        q: "Is CES open to the public?",
        a: "The organisers describe it as an event for industry professionals, media and decision makers rather than a consumer show, but do not state a trade-only rule on the front page.",
      },
    ],
    expertise:
      "Two things about CES are worth knowing before deciding it is a trip. The first is that it is not one venue: the show occupies the convention center and a string of hotels along the strip, and the distance between two appointments is measured in half-hours, not minutes. The second is that January in Las Vegas is the single hardest week of the year for rooms, and the price of a bed moves more than the price of a badge \u2014 which is the reverse of how most shows work, and the reason the decision is really about accommodation.",
  },

  {
    slug: "art-basel-miami-beach-2026",
    site: "nyc42",
    image: "/covers/art-basel-miami-beach-2026.jpg",
    imageAlt: "Three square sheets of paper hung in a row on a dark brown ground, one amber, one russet, one yellow",
    imageKind: "generated",
    imageWidth: 1536,
    imageHeight: 864,
    title: "Art Basel Miami Beach 2026",
    summary:
      "The American edition of Art Basel runs December 4 to 6 in Miami Beach — three public days, and the week the rest of the city builds its own fairs around.",
    start: "2026-12-04",
    end: "2026-12-06",
    utcOffset: "-05:00",
    venue: "Miami Beach",
    city: "Miami Beach",
    country: "United States",
    organizer: "Art Basel",
    category: "Exhibitions",
    source: {
      name: "Art Basel",
      url: "https://www.artbasel.com/miami-beach",
      verifiedOn: "2026-09-08",
    },
    ticket: { url: "https://www.artbasel.com/miami-beach", label: "Tickets" },
    body: [
      "Three days in December do something to Miami Beach that no other three days do, and most of what happens that week is not the fair.",
      "## The dates",
      "<strong>December 4 to 6, 2026</strong>, in <strong>Miami Beach</strong>. UBS is the global lead partner.",
      "## What is published and what is not",
      "The dates are confirmed on Art Basel's own page. The gallery list, the ticket prices and the split between preview and public days are not on it yet, so they are not here \u2014 the ticket link goes to the source rather than to a number invented for a listing.",
    ],
    faq: [
      {
        q: "When is Art Basel Miami Beach 2026?",
        a: "<strong>December 4 to 6, 2026</strong>, in Miami Beach.",
      },
      {
        q: "How much are tickets?",
        a: "Not yet published. Art Basel's own page carries a tickets link but no prices for this edition, so any figure quoted elsewhere is from a previous year.",
      },
    ],
    expertise:
      "The thing a first-time visitor gets wrong is booking the three days of the fair and nothing else. Art Basel is the anchor, but the week around it is when a dozen satellite fairs, gallery openings and institutional shows run across Miami Beach and the mainland \u2014 and a good deal of what is worth seeing costs nothing and is not inside the convention center at all. If the trip is being planned from New York, the flight is the cheap part and the room is not: December is high season on the beach before the fair is factored in.",
  },
  {
    slug: "rose-parade-2027",
    site: "nyc42",
    image: "/covers/rose-parade-2027.jpg",
    imageAlt: "A long single band of small paper petals in red, orange, cream and pink laid edge to edge across a dark brown ground, empty above and below",
    imageKind: "generated",
    imageWidth: 1536,
    imageHeight: 864,
    title: "Rose Parade 2027",
    summary:
      "The 138th Rose Parade runs down Colorado Boulevard in Pasadena on New Year's Day 2027 \u2014 floats covered entirely in flowers and other natural material, and the one American parade that has run since 1890.",
    start: "2027-01-01",
    venue: "Colorado Boulevard",
    city: "Pasadena",
    country: "United States",
    organizer: "Pasadena Tournament of Roses",
    category: "Parade",
    source: {
      name: "Pasadena Tournament of Roses",
      url: "https://tournamentofroses.com/rose-parade/",
      verifiedOn: "2026-09-08",
    },
    body: [
      "It is the oldest fixture on the American new year, and it is free to stand and watch.",
      "## The date",
      "<strong>January 1, 2027</strong>, in <strong>Pasadena, California</strong>. This is the <strong>138th</strong> Rose Parade, presented by Honda.",
      "## What it is",
      "The Tournament of Roses has produced what it calls America's New Year Celebration since <strong>1890</strong> \u2014 the parade and the Rose Bowl Game on the same day, in the same city.",
    ],
    faq: [
      {
        q: "When is the Rose Parade 2027?",
        a: "<strong>January 1, 2027</strong>, in Pasadena, California \u2014 the 138th edition.",
      },
      {
        q: "Does it cost anything to watch?",
        a: "Standing on the route is free; grandstand seating is sold separately by the Tournament of Roses and its partners. Prices for 2027 are not published on the organiser's parade page.",
      },
    ],
    expertise:
      "A New Year's Day parade means a New Year's Eve on the route, which is the part nobody plans for: the kerbside is claimed the night before, and Pasadena's own rules govern when you may put a chair down. Anyone flying in for it is really booking two nights, not one.",
  },
  {
    slug: "coachella-2027",
    site: "nyc42",
    image: "/covers/coachella-2027.jpg",
    imageAlt: "Two matching pale yellow paper palm trees standing on small orange sand mounds, one on each side of a wide brown frame",
    imageKind: "generated",
    imageWidth: 1536,
    imageHeight: 864,
    title: "Coachella 2027",
    summary:
      "Coachella returns to the Empire Polo Club in Indio for two identical weekends in April 2027. The dates are published; the line-up is not.",
    start: "2027-04-09",
    end: "2027-04-18",
    venue: "Empire Polo Club",
    city: "Indio",
    country: "United States",
    organizer: "Coachella",
    category: "Festival",
    source: {
      name: "Coachella",
      url: "https://www.coachella.com/",
      verifiedOn: "2026-09-08",
    },
    ticket: { url: "https://www.coachella.com/", label: "Tickets" },
    body: [
      "Two weekends, the same bill twice, and a line-up that will not be announced for months.",
      "## The dates",
      "<strong>April 9\u201311 and April 16\u201318, 2027</strong>, at the <strong>Empire Polo Club</strong> in <strong>Indio, California</strong>. The festival's own words for it: see you in the desert.",
      "## What is not published",
      "No line-up and no 2027 prices at the time of writing. Passes are sold in advance of both, which is the arrangement to understand before deciding.",
    ],
    faq: [
      {
        q: "When is Coachella 2027?",
        a: "Two weekends: <strong>April 9 to 11</strong> and <strong>April 16 to 18, 2027</strong>.",
      },
      {
        q: "Where is it held?",
        a: "The <strong>Empire Polo Club</strong>, Indio, California \u2014 the same site every year.",
      },
      {
        q: "Is the line-up announced?",
        a: "No. Coachella has published the dates only; anything circulating as a 2027 line-up is not from the festival.",
      },
    ],
    expertise:
      "The two weekends are sold as identical and are not quite: the second tends to be the easier one to get into and the hotter one to stand in. From New York it is a five-hour flight to a desert with no city attached \u2014 the accommodation decision is made in the autumn, not in March.",
  },
  {
    slug: "edc-las-vegas-2027",
    site: "nyc42",
    image: "/covers/edc-las-vegas-2027.jpg",
    imageAlt: "A flat orange paper ring with a red disc inside it, centred on a near-black ground",
    imageKind: "generated",
    imageWidth: 1536,
    imageHeight: 864,
    title: "EDC Las Vegas 2027",
    summary:
      "Three nights at the Las Vegas Motor Speedway in May 2027. Electric Daisy Carnival runs after dark and ends at sunrise, which is the whole design of it.",
    start: "2027-05-14",
    end: "2027-05-16",
    venue: "Las Vegas Motor Speedway",
    city: "Las Vegas",
    country: "United States",
    organizer: "Insomniac",
    category: "Festival",
    source: {
      name: "EDC Las Vegas",
      url: "https://lasvegas.electricdaisycarnival.com/faq/",
      verifiedOn: "2026-09-08",
    },
    ticket: { url: "https://lasvegas.electricdaisycarnival.com/", label: "Tickets" },
    body: [
      "It is a festival that opens when the sun goes down and closes when it comes back up.",
      "## The dates",
      "<strong>May 14, 15 and 16, 2027</strong>, at the <strong>Las Vegas Motor Speedway</strong> \u2014 not on the Strip, some fifteen miles north-east of it.",
      "## What that means in practice",
      "Three consecutive nights rather than three days: the schedule runs overnight, and the trip home happens in daylight. Camping is sold as part of the festival.",
    ],
    faq: [
      {
        q: "When is EDC Las Vegas 2027?",
        a: "<strong>May 14 to 16, 2027</strong> \u2014 three nights, each running from evening until sunrise.",
      },
      {
        q: "Where is it?",
        a: "The <strong>Las Vegas Motor Speedway</strong>, well outside the Strip. Shuttles and camping are both offered by the festival.",
      },
    ],
    expertise:
      "The sunrise finish is not a detail, it is the thing to plan the whole trip around: a hotel room booked for the nights of the festival is a room slept in during the day, and a flight out on the Sunday morning is a flight missed. Anyone treating it like a Vegas weekend with a festival attached has the schedule backwards.",
  },
  {
    slug: "lollapalooza-2026",
    site: "nyc42",
    image: "/covers/lollapalooza-2026.jpg",
    imageAlt: "A cut-paper panel: orange skyscraper silhouettes along a deep navy sky, with a broad green lawn curving across the lower half",
    imageKind: "generated",
    imageWidth: 1536,
    imageHeight: 864,
    title: "Lollapalooza 2026",
    summary:
      "Four days in Grant Park at the end of July 2026 \u2014 the festival that stopped touring and stayed in one city, in the middle of it rather than in a field outside.",
    start: "2026-07-30",
    end: "2026-08-02",
    venue: "Grant Park",
    city: "Chicago",
    country: "United States",
    organizer: "Lollapalooza",
    category: "Festival",
    source: {
      name: "Lollapalooza",
      url: "https://www.lollapalooza.com/",
      verifiedOn: "2026-09-08",
    },
    body: [
      "Most big American festivals happen somewhere you have to drive to. This one happens in a park with a skyline behind it.",
      "## The dates",
      "<strong>July 30 to August 2, 2026</strong>, in <strong>Grant Park, Chicago, Illinois</strong> \u2014 four days, now past.",
      "## Next year",
      "Dates for 2027 are not published yet. When the festival announces them, they go here.",
    ],
    faq: [
      {
        q: "When was Lollapalooza 2026?",
        a: "<strong>July 30 to August 2, 2026</strong>, in Grant Park, Chicago.",
      },
      {
        q: "When is Lollapalooza 2027?",
        a: "Not announced. The festival has kept to late summer in Grant Park for years, but no 2027 dates are published, so none are stated here.",
      },
    ],
    expertise:
      "A city-centre festival is a different proposition from a desert or a farm: you sleep in a hotel, you eat in restaurants, and the day ends by a curfew the neighbours negotiated. That makes it the easiest of the big American festivals to attend badly \u2014 people underestimate how far Grant Park is end to end, and how much of the line-up runs at the same time.",
  },
  {
    slug: "kentucky-derby-2027",
    site: "nyc42",
    image: "/covers/kentucky-derby-2027.jpg",
    imageAlt: "Two tall paper crescents facing each other across a brown ground, one yellow and one orange",
    imageKind: "generated",
    imageWidth: 1536,
    imageHeight: 864,
    title: "Kentucky Derby 2027",
    summary:
      "The 153rd running at Churchill Downs on Saturday, May 1, 2027. Gates open at 9am for a race that goes off in the early evening \u2014 the day is the event, not the two minutes.",
    start: "2027-05-01",
    venue: "Churchill Downs",
    city: "Louisville",
    country: "United States",
    organizer: "Churchill Downs",
    category: "Racing",
    source: {
      name: "Kentucky Derby",
      url: "https://www.kentuckyderby.com/",
      verifiedOn: "2026-09-08",
    },
    ticket: { url: "https://www.kentuckyderby.com/", label: "Tickets" },
    body: [
      "The race lasts about two minutes. The gates open nine hours before it.",
      "## The dates",
      "<strong>Saturday, May 1, 2027</strong> at <strong>Churchill Downs</strong>, Louisville, Kentucky \u2014 the <strong>153rd</strong> Derby, and as always the first Saturday in May. The Kentucky Oaks runs the day before, on <strong>April 30</strong>.",
      "## The day itself",
      "<strong>Gates open at 9am.</strong> Post time for the Derby is scheduled for approximately <strong>6:57pm ET</strong>. Everything between those two numbers \u2014 a full card of racing, the infield, the hats \u2014 is what the ticket is actually for.",
    ],
    faq: [
      {
        q: "When is the Kentucky Derby 2027?",
        a: "<strong>Saturday, May 1, 2027</strong> \u2014 the first Saturday in May, as always, and the 153rd running.",
      },
      {
        q: "What time is the race?",
        a: "Post time is scheduled for approximately <strong>6:57pm ET</strong>. Gates open at <strong>9am</strong>.",
      },
      {
        q: "What is the Kentucky Oaks?",
        a: "The Friday card at the same track, <strong>April 30, 2027</strong>. Many people who travel for the Derby go to both.",
      },
    ],
    expertise:
      "Two things decide whether the day is a good one and neither is the horse: where you stand, and when you arrive. Louisville prices its hotel rooms for Derby week a year ahead, and the infield and the grandstand are different events at the same address \u2014 one is a nine-hour party where you may never see a horse, the other is a seat. Buying the cheaper ticket without knowing which one it is, is the classic first Derby.",
  },
  {
    slug: "austin-city-limits-2026",
    site: "nyc42",
    image: "/covers/austin-city-limits-2026.jpg",
    imageAlt: "Six flat green paper trees on short orange trunks standing in a row across a dark brown ground, one of them much smaller than the rest",
    imageKind: "generated",
    imageWidth: 1536,
    imageHeight: 864,
    title: "Austin City Limits 2026",
    summary:
      "Two weekends in Zilker Park at the start of October \u2014 the same bill played twice, in a park inside Austin rather than a field outside it.",
    start: "2026-10-02",
    end: "2026-10-11",
    venue: "Zilker Park",
    city: "Austin",
    country: "United States",
    organizer: "Austin City Limits Music Festival",
    category: "Festival",
    source: {
      name: "Austin City Limits Music Festival",
      url: "https://www.aclfestival.com/",
      verifiedOn: "2026-09-08",
    },
    ticket: { url: "https://www.aclfestival.com/", label: "Tickets" },
    body: [
      "The nearest of these to happening: three weeks from now, and in a city that is easy to fly into.",
      "## The dates",
      "<strong>October 2\u20134 and October 9\u201311, 2026</strong>, at <strong>Zilker Park</strong> in <strong>Austin, Texas</strong>. Two weekends, the same festival twice.",
      "## Why the park matters",
      "Zilker is inside Austin, which makes this one of the few American festivals of its size where the accommodation is a hotel room and the journey home is a short one.",
    ],
    faq: [
      {
        q: "When is Austin City Limits 2026?",
        a: "<strong>October 2 to 4</strong> and <strong>October 9 to 11, 2026</strong>, at Zilker Park in Austin.",
      },
      {
        q: "Are the two weekends the same?",
        a: "They are sold as the same festival twice. The line-up, schedule and FAQs are published by the festival itself.",
      },
    ],
    expertise:
      "Early October in Austin is still summer by most standards, and Zilker has very little shade \u2014 which is what separates people who enjoy the second weekend from people who leave at four. The other thing worth knowing from New York: the flight is three and a half hours and the city is busy that fortnight, so the room is the booking that decides the price of the trip.",
  },
  {
    slug: "ultra-miami-2027",
    site: "nyc42",
    image: "/covers/ultra-miami-2027.jpg",
    imageAlt: "A long flat teal paper band running the width of a dark brown ground, with two narrow magenta paper spires standing on it near the left",
    imageKind: "generated",
    imageWidth: 1536,
    imageHeight: 864,
    title: "Ultra Miami 2027",
    summary:
      "Three days at Bayfront Park in downtown Miami at the end of March 2027 \u2014 an electronic festival held in the middle of a city, with the bay behind the stage.",
    start: "2027-03-26",
    end: "2027-03-28",
    venue: "Bayfront Park",
    city: "Miami",
    country: "United States",
    organizer: "Ultra Music Festival",
    category: "Festival",
    source: {
      name: "Ultra Music Festival",
      url: "https://ultramusicfestival.com/",
      verifiedOn: "2026-09-08",
    },
    ticket: { url: "https://ultramusicfestival.com/", label: "Tickets" },
    body: [
      "Most festivals of this size are held somewhere with room to build them. This one is held on the waterfront of a downtown.",
      "## The dates",
      "<strong>March 26 to 28, 2027</strong>, at <strong>Bayfront Park</strong>, Miami, Florida.",
      "## What is not published yet",
      "No 2027 line-up at the time of writing. Tickets are sold before it is announced, which is the same arrangement Coachella runs.",
    ],
    faq: [
      {
        q: "When is Ultra Miami 2027?",
        a: "<strong>March 26 to 28, 2027</strong>, at Bayfront Park in downtown Miami.",
      },
      {
        q: "Is the line-up out?",
        a: "Not yet. The festival has published the dates and the venue; anything else circulating for 2027 is not from Ultra.",
      },
    ],
    expertise:
      "Ultra falls inside Miami Music Week, and that is the part that changes the trip: the festival is three days, the week around it is a city full of parties in clubs and hotels, most of them ticketed separately. Booking only the festival is booking the smaller half.",
  },
  {
    slug: "stagecoach-2027",
    site: "nyc42",
    image: "/covers/stagecoach-2027.jpg",
    imageAlt: "A wheel of straight yellow and red paper spokes radiating from a small red disc, on a rust-orange ground",
    imageKind: "generated",
    imageWidth: 1536,
    imageHeight: 864,
    title: "Stagecoach 2027",
    summary:
      "The country festival that follows Coachella into the same desert, a week later: April 23 to 25, 2027.",
    start: "2027-04-23",
    end: "2027-04-25",
    country: "United States",
    organizer: "Stagecoach",
    category: "Festival",
    source: {
      name: "Stagecoach",
      url: "https://www.stagecoachfestival.com/",
      verifiedOn: "2026-09-08",
    },
    ticket: { url: "https://www.stagecoachfestival.com/", label: "Tickets" },
    body: [
      "Country music's biggest party, in the festival's own words, and it happens in the same corner of California as Coachella a fortnight earlier.",
      "## The dates",
      "<strong>April 23 to 25, 2027</strong>. The festival's own page says only that it returns to the desert; it does not name the site or the town, so neither does this page.",
      "## What is not published",
      "No line-up and no 2027 prices yet.",
    ],
    faq: [
      {
        q: "When is Stagecoach 2027?",
        a: "<strong>April 23 to 25, 2027</strong>.",
      },
      {
        q: "Where is it held?",
        a: "The festival's own announcement says the desert and no more than that. Rather than repeat an address from a previous year, this page waits for the organiser to publish one.",
      },
    ],
    expertise:
      "Two festivals a fortnight apart in the same desert means the same hotels and the same flights are wanted twice in April, and the second wave is the one people book late. Anyone considering both weekends should be aware they are priced as two separate trips, not one long one.",
  },
  {
    slug: "iowa-state-fair-2027",
    site: "nyc42",
    image: "/covers/iowa-state-fair-2027.jpg",
    imageAlt: "A row of six paper corn cobs in yellow with pale green husk leaves, lying overlapping across a rust-brown ground",
    imageKind: "generated",
    imageWidth: 1536,
    imageHeight: 864,
    title: "Iowa State Fair 2027",
    summary:
      "Eleven days in Des Moines in August \u2014 one of the oldest and largest agricultural expositions in the country, and the largest event in Iowa.",
    start: "2027-08-12",
    end: "2027-08-22",
    city: "Des Moines",
    country: "United States",
    organizer: "Iowa State Fair",
    category: "Festival",
    source: {
      name: "Iowa State Fair",
      url: "https://www.iowastatefair.org/",
      verifiedOn: "2026-09-08",
    },
    body: [
      "It is the sort of event the coasts forget exists, and it is bigger than most of the festivals they do not.",
      "## The dates",
      "<strong>August 12 to 22, 2027</strong>, in <strong>Des Moines, Iowa</strong> \u2014 eleven days.",
      "## What it is",
      "The fair describes itself as the largest event in Iowa and one of the oldest and largest agricultural and industrial expositions in the country.",
    ],
    faq: [
      {
        q: "When is the Iowa State Fair 2027?",
        a: "<strong>August 12 to 22, 2027</strong>, in Des Moines.",
      },
      {
        q: "How long does it run?",
        a: "Eleven days, which is longer than any music festival on this page \u2014 it is built to be visited for a day, not camped at for a weekend.",
      },
    ],
    expertise:
      "A state fair is the one American event on this list that is genuinely about the place it happens in rather than about who is playing, and that is the reason to go: livestock barns, competitions and food on sticks are the programme, not the sideshow. It is also the cheapest day out here by a distance.",
  },
  {
    slug: "bonnaroo-2026",
    site: "nyc42",
    image: "/covers/bonnaroo-2026.jpg",
    imageAlt: "A thick orange paper arch standing behind layered green paper hills against a near-black sky",
    imageKind: "generated",
    imageWidth: 1536,
    imageHeight: 864,
    title: "Bonnaroo 2026",
    summary:
      "Four days on a farm in Manchester, Tennessee in June 2026, now past \u2014 the American festival that still means camping rather than commuting.",
    start: "2026-06-11",
    end: "2026-06-14",
    city: "Manchester",
    country: "United States",
    organizer: "Bonnaroo Music & Arts Festival",
    category: "Festival",
    source: {
      name: "Bonnaroo Music & Arts Festival",
      url: "https://www.bonnaroo.com/",
      verifiedOn: "2026-09-08",
    },
    body: [
      "Four days of adventure, as the festival puts it, on 700 acres of farmland an hour from Nashville.",
      "## The dates",
      "<strong>June 11 to 14, 2026</strong>, in <strong>Manchester, Tennessee</strong> \u2014 four days, now past.",
      "## Next year",
      "No 2027 dates are published yet. When Bonnaroo announces them, they go here.",
    ],
    faq: [
      {
        q: "When was Bonnaroo 2026?",
        a: "<strong>June 11 to 14, 2026</strong>, in Manchester, Tennessee.",
      },
      {
        q: "When is Bonnaroo 2027?",
        a: "Not announced. The festival has kept to June for years, but no dates are published, so none are stated here.",
      },
    ],
    expertise:
      "Bonnaroo is the one on this page you cannot do from a hotel: the festival is a campsite with stages attached, an hour from the nearest city, and the experience people describe is as much about the field as the line-up. Flying in from New York means renting a car in Nashville, which is a plan to make before the ticket, not after.",
  },
];
