import type { EventItem } from "../types.ts";

export const items: EventItem[] = [
  {
    slug: "new-york-comic-con-2026",
    site: "nyc42",
    title: "New York Comic Con 2026",
    summary:
      "Four days at the Javits Center, 8–11 October, for NYCC's twentieth anniversary — with a Coney Island theme and the panel schedule already published.",
    start: "2026-10-08",
    end: "2026-10-11",
    city: "New York",
    venue: "Jacob K. Javits Convention Center, 429 11th Avenue",
    category: "Convention",
    organizer: "ReedPop",
    geo: {
      name: "Jacob K. Javits Convention Center",
      lat: 40.758359,
      lng: -74.002121,
    },
    source: {
      name: "New York Comic Con",
      url: "https://www.newyorkcomiccon.com/",
      verifiedOn: "2026-08-30",
    },
    body: [
      "NYCC runs <strong>8 to 11 October 2026</strong> at the Javits Center: four days of comics, film and TV, anime and manga, gaming, cosplay, literary programming and horror.",
      "This one is the <strong>twentieth anniversary</strong>, and the organisers have picked a theme to match.",
      "## Coney Island",
      "The 20th-anniversary theme is <strong>Coney Island</strong> &mdash; sideshow energy, roaring coasters, ocean air, in the convention&rsquo;s own description, and the merchandise follows it.",
      "It is a better choice than it first sounds. Coney Island is where New York invented the idea that spectacle should be cheap and public: the freak show, the roller coaster and the boardwalk crowd are the direct ancestors of a convention hall where a hundred thousand people queue to see something loud. Twenty years in, the con is claiming a lineage rather than a birthday.",
      "## The schedule is already up",
      "The panels and programming schedule is <strong>live</strong>, which is unusual this far out and is the single most useful fact for planning. Announced so far: <strong>Marvel TV</strong>, a <strong>Crystal Lake</strong> screening, <strong>Yaga</strong>, a preview of Blumhouse&rsquo;s <strong>BlumFest</strong>, and <strong>Dexter: Resurrection</strong> Season 2.",
      "Guests are added continuously up to and during the show, so a schedule read in August is a floor, not a ceiling.",
      "## Tickets and the practical part",
      "Tickets are on sale. The convention runs a <strong>Fan Verification</strong> process for first-timers, and there is an app carrying the map of the Javits and the full panel schedule &mdash; the building is large enough that this is a genuine recommendation rather than a promotion.",
      "One thing worth knowing if you bought for a group: tickets have to be <strong>transferred</strong> to each person, not handed over, or your friend cannot access reservations on the day.",
      "## Getting to the Javits",
      "The Javits Center sits at <strong>429 11th Avenue</strong>, on the far west side at Hudson Yards. That is a longer walk from the subway than most New York venues, and the walk is on a stretch with very little on it &mdash; the 7 train to Hudson Yards is the shortest version of it.",
    ],
    expertise:
      "The twentieth-anniversary framing means the popular panels will be busier than the schedule suggests, and NYCC queues form for the room, not the panel &mdash; once you are inside a hall you can usually stay for the next session. Picking a room for a block of the afternoon beats picking four panels in four buildings.",
  },
  {
    slug: "village-halloween-parade-2026",
    site: "nyc42",
    title: "Village Halloween Parade 2026",
    summary:
      "The 53rd parade goes up Sixth Avenue at 7pm on Saturday 31 October. Watching is free, joining in is free if you are in costume, and it happens rain or shine.",
    start: "2026-10-31",
    startTime: "19:00",
    utcOffset: "-04:00",
    city: "New York",
    venue: "Sixth Avenue, Greenwich Village",
    category: "Parade",
    organizer: "Village Halloween Parade, Inc.",
    source: {
      name: "NYC Village Halloween Parade",
      url: "https://www.halloween-nyc.com/",
      verifiedOn: "2026-08-30",
    },
    body: [
      "New York&rsquo;s <strong>53rd annual Village Halloween Parade</strong> steps off at <strong>7:00pm on Saturday 31 October 2026</strong>, up Sixth Avenue.",
      "The organisers put the important part in capitals on their own front page: <strong>rain or shine</strong>. Or wind.",
      "## The rule that makes it different",
      "<strong>Everyone is invited to watch. Anyone in costume is welcome to join in.</strong>",
      "That second sentence is the whole event. Almost every other parade in America is a procession of organisations that the public watches from a barrier; this one has no audition, no application and no float requirement. Turn up in costume and you are in it. It is the largest participatory parade in the country for exactly that reason, and it is why the thing has never looked corporate.",
      "## Halloween lands on a Saturday",
      "The parade is always on 31 October, whatever day that is &mdash; and in 2026 it falls on a <strong>Saturday</strong>. A Saturday-night Halloween in Manhattan is the maximum-density version of this: nobody has work the next morning, and the parade is a whole evening rather than a weeknight detour.",
      "Plan the getting-home part before the getting-there part.",
      "## What tickets are for",
      "Watching costs nothing and marching costs nothing. Tickets exist for <strong>special access</strong> &mdash; skipping the line to enter the parade, and grandstand-style viewing &mdash; and the parade is a <strong>501(c)(3) not-for-profit arts organisation</strong>, so buying one is closer to a donation than a fee.",
      "The parade is supported in part by public funds from the <strong>NYC Department of Cultural Affairs</strong> in partnership with the City Council.",
      "## What is not announced",
      "The <strong>2026 theme and Grand Marshal have not been published</strong>, so they do not appear here. For reference, 2025 ran under &laquo;It&rsquo;s a Potluck!&raquo; with <strong>City Harvest</strong> as Grand Marshal &mdash; the organisation that rescues fresh produce and delivers it free across the five boroughs.",
      "There is also an official after party at <strong>House of Yes</strong> in Industry City, Brooklyn, from <strong>9:00pm</strong>, which is ticketed separately.",
    ],
    expertise:
      "The costume rule cuts both ways: if you are in costume you can join, and if you are in costume in the Village that night you will be swept into it whether you meant to be or not. For watching rather than marching, the north end of the route thins out considerably &mdash; the parade takes hours to pass, and the last third of it is the same parade with room to stand.",
  },
  {
    slug: "open-house-new-york-weekend-2026",
    site: "nyc42",
    title: "Open House New York Weekend 2026",
    summary:
      "Three hundred buildings across the five boroughs open for one weekend, 16–18 October. The full lineup is revealed on 25 September and tickets go on 2 October.",
    start: "2026-10-16",
    end: "2026-10-18",
    city: "New York",
    venue: "All five boroughs",
    category: "Architecture",
    organizer: "Open House New York",
    source: {
      name: "Open House New York",
      url: "https://ohny.org/festival",
      verifiedOn: "2026-08-30",
    },
    body: [
      "For one weekend in October the answer to &laquo;can you go in there?&raquo; is yes, about three hundred times over.",
      "<strong>OHNY Weekend runs 16 to 18 October 2026</strong> and unlocks <strong>300+ destinations</strong> across all five boroughs for behind-the-scenes tours and special activities.",
      "## What actually opens",
      "New buildings changing the skyline, and also: <strong>infrastructure facilities</strong> that keep the city running, parks, performance spaces, manufacturing workshops and private collections.",
      "The infrastructure is the part worth queuing for. Among the 2026 destinations already previewed is the <strong>Department of Sanitation&rsquo;s Brooklyn District 3 Garage</strong> and the <strong>DOT Sign Shop</strong> in Maspeth, Queens &mdash; the place where the city&rsquo;s street signs are actually made. Those are buildings no amount of money gets you into on an ordinary Tuesday, and they explain more about how New York works than any tower does.",
      "Also previewed: the <strong>Flatiron Building</strong>, <strong>Rockefeller Center Gardens</strong> and the <strong>Brooklyn Army Terminal</strong>.",
      "## The calendar before the calendar",
      "OHNY is unusual in that the month before the festival has its own schedule, and missing a date on it costs you access rather than information.",
      "Most sites you can simply show up to. A minority require <strong>tickets</strong>, because of space or security &mdash; and those are the ones that go in minutes on release day.",
      "## Five boroughs, and that is the instruction",
      "The festival is designed as a citywide event, not a Manhattan one, and the way to use it is to stay in one borough for a day rather than crossing three. A Sanitation garage in Brooklyn and a sign shop in Queens are not consolation prizes for missing the Flatiron; they are the festival.",
    ],
    programme: [
      { heading: "18 September &mdash; Members preview", text: "Members get early access to the Weekend lineup, and more time to plan." },
      { heading: "25 September &mdash; Public reveal", text: "The full lineup is published with all locations, activities, dates and times." },
      { heading: "2 October &mdash; Ticket release", text: "Most sites need no ticket; the ones limited by space or security release theirs now." },
      { heading: "15 October &mdash; Launch party", text: "The festival's fundraiser and official kick-off, with food, drinks and entertainment." },
      { heading: "16&ndash;18 October &mdash; The festival", text: "Three days of tours and visits across the five boroughs." },
    ],
    expertise:
      "Put 2 October in the diary rather than 16 October. The weekend itself is walk-up for most of the three hundred sites, so the only thing that can actually be missed by being slow is the ticketed handful &mdash; which is, reliably, the list of places everybody wanted to see.",
  },
  {
    slug: "broadway-week-harry-potter",
    site: "nyc42",
    title: "Harry Potter at Broadway Week",
    summary:
      "The two-for-one runs 8 to 20 September at the Lyric. It is the largest saving on the Broadway Week list, and the reason is the house rather than the play.",
    start: "2026-09-08",
    end: "2026-09-20",
    city: "New York City",
    venue: "Lyric Theatre, 213 West 42nd Street, Manhattan",
    geo: { lat: 40.756820, lon: -73.987484 },
    category: "Theatre",
    organizer: "New York City Tourism + Conventions",
    source: {
      name: "NYC Tourism + Conventions",
      url: "https://www.nyctourism.com/broadway-week/",
      verifiedOn: "2026-08-30",
    },
    body: [
      "Of the twenty-five productions in NYC Broadway Week, this is the one where the offer is worth the most &mdash; and it is worth reading why, because the reason is not that it is the best show on the list.",
      "## Why the saving is biggest here",
      "A two-for-one discounts a <em>seat</em>, not a production. It is worth most where the seat was expensive to begin with and where it is rarely cheap by any other route. <strong>Harry Potter and the Cursed Child</strong> is the longest and most technically elaborate thing on Broadway, it plays a big house, and it does not turn up week after week in the discount channels the way the long-running musicals do.",
      "Two-for-one on a rarely discounted ticket is a different purchase from two-for-one on a ticket that was going to be discounted anyway. This is the clearest case of the first kind on the list.",
      "## Where",
      "The <strong>Lyric Theatre</strong>, on West 43rd Street between Seventh and Eighth &mdash; its street address is 213 West 42nd. It is one of the largest houses on Broadway, which is both why the ticket is expensive and why the gap between a good seat and a poor one is wide.",
      "## The catch",
      "The offer exists for the fortnight, not for every performance in it. Each production sets its own <strong>blackout dates</strong> and releases its own allocation of eligible seats. Check this listing for the night you actually want before you book anything around it &mdash; a dinner reservation on a blacked-out night is the usual way this goes wrong.",
    ],
    expertise:
      "Because this is a long evening in a big house, the seat you are allocated matters more here than almost anywhere else on the list. If the offer comes back with only the back of the balcony, it is worth checking what a mid-house seat costs at full price before accepting: on a show built this heavily on stagecraft, the cheap pair can cost you the thing you came for.",
  },
  {
    slug: "broadway-week-hadestown",
    site: "nyc42",
    title: "Hadestown at Broadway Week",
    summary:
      "Anaïs Mitchell's Orpheus and Eurydice takes the two-for-one from 8 to 20 September at the Walter Kerr. The one on the list most likely to be the best evening rather than the best deal.",
    start: "2026-09-08",
    end: "2026-09-20",
    city: "New York City",
    venue: "Walter Kerr Theatre, 219 West 48th Street, Manhattan",
    geo: { lat: 40.760681, lon: -73.985585 },
    category: "Theatre",
    organizer: "New York City Tourism + Conventions",
    source: {
      name: "NYC Tourism + Conventions",
      url: "https://www.nyctourism.com/broadway-week/",
      verifiedOn: "2026-08-30",
    },
    body: [
      "Every Broadway Week list mixes two different things: shows where the offer is worth the most, and shows you should see. <strong>Hadestown</strong> is on this list for the second reason.",
      "## The show",
      "Ana&iuml;s Mitchell&rsquo;s retelling of Orpheus and Eurydice, staged as a smoky, jazz-inflected underworld with the band on stage. It began life as a folk album and was built outward from the songs, which is audible: the score carries the storytelling rather than decorating it.",
      "## Why it is not first on the list",
      "Only because it is easier to reach cheaply by other means than the biggest, newest productions are. If you are optimising purely for money saved, there are better uses of the offer. If you are optimising for the evening, this is the one to spend it on &mdash; Broadway Week is the excuse to stop putting it off.",
      "## Where",
      "The <strong>Walter Kerr Theatre</strong>, 219 West 48th Street. It is a mid-sized house, which suits a show that works on intimacy and a live band far better than a barn would.",
      "## The catch",
      "Each production sets its own <strong>blackout dates</strong> and releases its own allocation. The offer running from 8 to 20 September and the offer running on the night you can go are two different questions; only the second one decides anything.",
    ],
    expertise:
      "In a house this size the difference between the orchestra and the front mezzanine is smaller than the price difference suggests, and the band is on stage rather than in a pit. If the allocation offers a mezzanine pair, take it rather than holding out &mdash; sightlines here are forgiving in a way they are not at the larger houses on the list.",
  },
  {
    slug: "broadway-week-stranger-things",
    site: "nyc42",
    title: "Stranger Things at Broadway Week",
    summary:
      "The First Shadow takes the two-for-one from 8 to 20 September at the Marquis. Recent, effects-heavy and in a big house — which is what makes the offer valuable and the seat allocation risky.",
    start: "2026-09-08",
    end: "2026-09-20",
    city: "New York City",
    venue: "Marquis Theatre, 210 West 46th Street, Manhattan",
    geo: { lat: 40.758904, lon: -73.986185 },
    category: "Theatre",
    organizer: "New York City Tourism + Conventions",
    source: {
      name: "NYC Tourism + Conventions",
      url: "https://www.nyctourism.com/broadway-week/",
      verifiedOn: "2026-08-30",
    },
    body: [
      "<strong>Stranger Things: The First Shadow</strong> follows the same logic as the Potter play, and carries the same warning.",
      "## Why the offer is worth a lot here",
      "It is recent, it is effects-heavy, and it plays a large house. All three push the full-price ticket up and keep it out of the routine discount channels, which is exactly the combination that makes a two-for-one worth more than the arithmetic suggests.",
      "## And why it is the riskiest on the list",
      "The difference between a good seat and a bad one is unusually wide in a show built on stagecraft, and it is the allocation, not you, that decides which one you get. This is the one production here where the saving can cost you the point of the evening: the effects are the argument, and from the back of the balcony the argument is quieter.",
      "## Where",
      "The <strong>Marquis Theatre</strong>, 210 West 46th Street, inside the Marriott Marquis. It is one of the few Broadway houses that is not at street level &mdash; the auditorium is several floors up, which is worth knowing if you are arriving close to curtain.",
      "## The catch",
      "<strong>Blackout dates</strong> are set per production, and the eligible seats are a limited allocation at each theatre&rsquo;s discretion. Check this listing for your night before booking anything around it.",
    ],
    expertise:
      "Ask what section the two-for-one pair is in before you accept it. On a spectacle show the honest comparison is not “free ticket versus paid ticket” but “two poor seats versus one good one”, and for this production that comparison genuinely goes either way.",
  },
  {
    slug: "broadway-week-six",
    site: "nyc42",
    title: "Six at Broadway Week",
    summary:
      "Eighty minutes, no interval, Tudor England as a pop concert. On the two-for-one from 8 to 20 September at the Lena Horne — the cheapest way this fortnight to put two people in a Broadway theatre.",
    start: "2026-09-08",
    end: "2026-09-20",
    city: "New York City",
    venue: "Lena Horne Theatre, 256 West 47th Street, Manhattan",
    geo: { lat: 40.759975, lon: -73.986966 },
    category: "Theatre",
    organizer: "New York City Tourism + Conventions",
    source: {
      name: "NYC Tourism + Conventions",
      url: "https://www.nyctourism.com/broadway-week/",
      verifiedOn: "2026-08-30",
    },
    body: [
      "<strong>Six</strong> is the shortest thing on the Broadway Week list, and that turns out to be its whole practical argument.",
      "## The show",
      "The six wives of Henry VIII, staged as a pop concert in which each queen takes the microphone to argue that she had the worst of it. <strong>Eighty minutes, no interval</strong>, no set changes to wait through.",
      "## Why the length matters",
      "Two reasons, both logistical. It is the easiest show on the list to pair with something else in the same day &mdash; a matinee here leaves the evening intact. And it is the easiest to take a teenager to, because eighty minutes is inside the attention span that a three-hour book musical is not.",
      "On a two-for-one it is also, simply, the cheapest way this fortnight to get two people inside a Broadway theatre at all.",
      "## Where",
      "The <strong>Lena Horne Theatre</strong>, 256 West 47th Street &mdash; a smaller house, renamed in 2022. In a room this size the concert staging works the way it is meant to.",
      "## The catch",
      "Each production sets its own <strong>blackout dates</strong> and its own allocation of eligible seats. Confirm the night before you build a day around it.",
    ],
    expertise:
      "Because there is no interval, latecomers are held longer here than at a show with a natural break to seat them at. Eighty minutes also means the theatre empties early &mdash; a matinee finishes well before the pre-theatre dinner rush, which is the one evening this fortnight where restaurants around Times Square are easy at 6pm.",
  },
  {
    slug: "broadway-week-oh-mary",
    site: "nyc42",
    title: "Oh Mary! at Broadway Week",
    summary:
      "The comedy on the Broadway Week list, at the Lyceum from 8 to 20 September. In a house this small the offer buys proximity rather than merely a seat.",
    start: "2026-09-08",
    end: "2026-09-20",
    city: "New York City",
    venue: "Lyceum Theatre, 149 West 45th Street, Manhattan",
    geo: { lat: 40.757869, lon: -73.984501 },
    category: "Theatre",
    organizer: "New York City Tourism + Conventions",
    source: {
      name: "NYC Tourism + Conventions",
      url: "https://www.nyctourism.com/broadway-week/",
      verifiedOn: "2026-08-30",
    },
    body: [
      "<strong>Oh, Mary!</strong> is the comedy on the Broadway Week list, and the one production here whose ticket price has least to do with spectacle.",
      "## Why that changes the maths",
      "Most of the list is big houses where you are paying for stagecraft and the seat determines how much of it reaches you. This is the opposite case. The <strong>Lyceum</strong> is one of the smallest Broadway houses, so the offer buys <em>proximity</em> rather than merely a seat &mdash; and in a small room built for a comic performance, proximity is most of what you were paying for in the first place.",
      "A two-for-one on a comedy in a 900-seat house is a materially different purchase from a two-for-one in a 1,600-seat musical barn. It is also the case on this list where the worst available seat is least likely to ruin the evening.",
      "## Where",
      "The <strong>Lyceum Theatre</strong>, 149 West 45th Street &mdash; the oldest continuously operating Broadway theatre, opened in 1903, and a landmarked building inside and out.",
      "## The catch",
      "<strong>Blackout dates</strong> are set per production and the discounted seats are a limited allocation. A small house means a small allocation: this is one to check early rather than late in the fortnight.",
    ],
    expertise:
      "Small house, small allocation. The two-for-one inventory at the Lyceum is a fraction of what the Gershwin or the Lyric can release, so the practical advice differs from the rest of the list: for this one, treat the on-sale date as the deadline rather than the offer's closing date.",
  },
  {
    slug: "broadway-week-the-lion-king",
    site: "nyc42",
    title: "The Lion King at Broadway Week",
    summary:
      "On the two-for-one from 8 to 20 September at the Minskoff. One of the safest evenings in New York — and one of the three shows on the list where the offer is doing the least work.",
    start: "2026-09-08",
    end: "2026-09-20",
    city: "New York City",
    venue: "Minskoff Theatre, 1515 Broadway, Manhattan",
    geo: { lat: 40.758063, lon: -73.986205 },
    category: "Theatre",
    organizer: "New York City Tourism + Conventions",
    source: {
      name: "NYC Tourism + Conventions",
      url: "https://www.nyctourism.com/broadway-week/",
      verifiedOn: "2026-08-30",
    },
    body: [
      "<strong>The Lion King</strong> is on the Broadway Week list, and it is worth being straightforward about what that is worth.",
      "## The honest position",
      "This is one of the longest-running productions on the list and one of the safest evenings in New York. It is also one of the most reliably available at <em>some</em> reduced price in any given month. Using a Broadway Week ticket on it is not a mistake &mdash; it is simply the purchase where the offer is doing the least work, because the alternative to the offer was not full price.",
      "That is a statement about the discount market, not about the show. Julie Taymor&rsquo;s staging has been the reason people book it since 1997, and it is the reason it still fills a 1,600-seat house.",
      "## When it is the right call anyway",
      "If you are booking for children, the calculation changes completely. The offer is fully transferable to a family plan, the running time and the matinee schedule suit it, and the reliability that makes it a weak <em>deal</em> is exactly what you want when the evening has to work.",
      "## Where",
      "The <strong>Minskoff Theatre</strong>, 1515 Broadway at West 45th Street. Like the Marquis, the auditorium is above street level.",
      "## The catch",
      "Each production sets its own <strong>blackout dates</strong> and allocation. Weekend matinees are the first to go on a family show.",
    ],
    expertise:
      "Compare the two-for-one against the discount you could get anyway before deciding. For the long-runners this is the question that decides whether Broadway Week saved you anything, and it is the one question the offer's own marketing never asks.",
  },
  {
    slug: "broadway-week-wicked",
    site: "nyc42",
    title: "Wicked at Broadway Week",
    summary:
      "Two-for-one at the Gershwin from 8 to 20 September. A long-runner in Broadway's largest house — reliable, and reliably discounted the rest of the year too.",
    start: "2026-09-08",
    end: "2026-09-20",
    city: "New York City",
    venue: "Gershwin Theatre, 222 West 51st Street, Manhattan",
    geo: { lat: 40.762362, lon: -73.985204 },
    category: "Theatre",
    organizer: "New York City Tourism + Conventions",
    source: {
      name: "NYC Tourism + Conventions",
      url: "https://www.nyctourism.com/broadway-week/",
      verifiedOn: "2026-08-30",
    },
    body: [
      "<strong>Wicked</strong> takes the Broadway Week offer, and sits in the same category as the other long-runners on the list.",
      "## What the offer is really worth here",
      "It is among the three most reliably available at some reduced price in any given month, which means the two-for-one is competing against a discount you could probably have found anyway. The saving is real; it is just smaller than the headline implies once you compare it to the right baseline rather than to the full price.",
      "## The house is the argument for going anyway",
      "The <strong>Gershwin Theatre</strong>, 222 West 51st Street, is the largest theatre on Broadway. That cuts both ways: there is more inventory to release into an offer like this one, so the odds of getting a decent pair of seats are better here than at the small houses &mdash; and the range between the best and worst seat is correspondingly enormous.",
      "For a show with this much scenery, a large allocation in a large house is genuinely useful. It is one of the few places on the list where being flexible about the night is likely to be rewarded.",
      "## The catch",
      "<strong>Blackout dates</strong> are set per production and the eligible seats are limited and at the theatre&rsquo;s discretion. Check this listing for the specific night rather than assuming the fortnight.",
    ],
    expertise:
      "The Gershwin's size is the reason to check back more than once. Large houses release eligible seats in waves rather than all at the on-sale date, so an allocation that looks poor on day one is often better a week in — which is the opposite of the advice for the small houses on this list.",
  },
  {
    slug: "broadway-week-chicago",
    site: "nyc42",
    title: "Chicago at Broadway Week",
    summary:
      "The longest-running American musical on Broadway takes the two-for-one from 8 to 20 September at the Ambassador. A safe evening, and the offer's least necessary use.",
    start: "2026-09-08",
    end: "2026-09-20",
    city: "New York City",
    venue: "Ambassador Theatre, 219 West 49th Street, Manhattan",
    geo: { lat: 40.761235, lon: -73.984990 },
    category: "Theatre",
    organizer: "New York City Tourism + Conventions",
    source: {
      name: "NYC Tourism + Conventions",
      url: "https://www.nyctourism.com/broadway-week/",
      verifiedOn: "2026-08-30",
    },
    body: [
      "<strong>Chicago</strong> is on the Broadway Week list, and like the other long-runners it is a strong evening and a weak deal.",
      "## Why the deal is weak",
      "It is one of the three productions here most reliably available at a reduced price in any given month. A two-for-one that competes with a discount you could find anyway is saving you the difference between two discounts, not half the price.",
      "## Why the evening is strong",
      "The staging is the concert version that came out of the 1996 Encores! revival and never left: the orchestra on stage, black costumes, almost no scenery. That look reads today as a deliberate minimalist choice, and it was originally the constraint of a concert staging that worked too well to undo.",
      "It also means the seat matters less than at any other big-house show on this list. There is no scenery to be blocked by and nothing happening upstage that you need a sightline for.",
      "## Where",
      "The <strong>Ambassador Theatre</strong>, 219 West 49th Street, where the revival has played since January 2003.",
      "## The catch",
      "<strong>Blackout dates</strong> and the size of the eligible allocation are set by the production, not by the offer. Check the night you want.",
    ],
    expertise:
      "This is the one show on the list where accepting a cheap seat costs you almost nothing. With the band on stage and no set to speak of, the rear mezzanine sees the same production as the orchestra — so if the allocation comes back high and far, take it here rather than at the spectacle shows.",
  },
  {
    slug: "broadway-week-fall-2026",
    site: "nyc42",
    title: "NYC Broadway Week: two-for-one at 25 shows",
    summary:
      "Two weeks of 2-for-1 Broadway tickets across 25 productions, from 8 to 20 September 2026. Tickets have been on sale since 18 August.",
    start: "2026-09-08",
    end: "2026-09-20",
    city: "New York City",
    category: "Theatre",
    organizer: "New York City Tourism + Conventions",
    source: {
      name: "NYC Tourism + Conventions",
      url: "https://www.nyctourism.com/broadway-week/",
      verifiedOn: "2026-08-30",
    },
    body: [
      "NYC Broadway Week runs from <strong>8 to 20 September 2026</strong>. Twenty-five productions take part, and the offer is the one it has always been: buy two tickets, pay for one. Sales opened on 18 August.",
      "## What is in it",
      "&amp; Juliet, Aladdin, The Book of Mormon, Buena Vista Social Club, Chicago, The Great Gatsby, Hadestown, Harry Potter and the Cursed Child, Just in Time, The Lion King, The Lost Boys, Maybe Happy Ending, MJ, Oh Mary!, Operation Mincemeat, The Outsiders, Paranormal Activity, The Rocky Horror Show, Schmigadoon!, School Girls; Or, the African Mean Girls Play, Six, Stranger Things: The First Shadow, Titaníque, Two Strangers (Carry a Cake Across New York) and Wicked.",
      "It is a wide list on purpose: long-runners that will still be there next year sit beside productions in their first season, and at half price those are worth very different things.",
      "## The catch is the calendar, not the price",
      "Each show sets its own <strong>blackout dates</strong> and releases its own allocation. The offer existing on a given day and the offer existing for the show you want on that day are two separate questions, and only the second decides your evening.",
      "Check the individual listing before committing, and before booking anything around it. The usual way this goes wrong is a dinner reservation made for a night the show had blacked out.",
      "## Seats, not shows",
      "A two-for-one discounts a seat rather than a production, so it is worth most where the seat was expensive to begin with. In a big house built on stagecraft the gap between a good seat and a bad one is wide, and the allocation decides which you get. In a small house the same offer buys proximity &mdash; which is most of what the ticket was for.",
    ],
    expertise:
      "Broadway Week runs twice a year, in January and September, and the September edition lands in the quiet stretch after the summer tourists and before the holiday run-up — which is why the discounted seats tend to be better ones than the winter edition offers.",
  },
];
