import type { EventItem } from "../types.ts";

export const items: EventItem[] = [
  {
    slug: "meydan-racing-season-2026-27",
    createdAt: "2026-08-25T18:18:34+04:00",
    updatedAt: "2026-09-06T08:48:11+04:00",
    site: "riviera",
    image: "/covers/meydan-racing-season-2026-27.jpg",
    imageAlt: "A pale oval racetrack with white rails set on a broad white band against a clear blue ground",
    imageKind: "generated",
    imageWidth: 1536,
    imageHeight: 864,
    title: "Meydan racing season 2026–27",
    summary:
      "Seventeen race nights at Meydan from 6 November to 27 March, ending with the $12 million Dubai World Cup — all of it about a kilometre and a half from Riviera.",
    start: "2026-11-06",
    end: "2027-03-27",
    venue: "Meydan Racecourse",
    city: "Dubai",
    organizer: "Dubai Racing Club",
    category: "Sport",
    source: {
      name: "Emirates Racing Authority",
      url: "https://emiratesracing.com/news/the-emirates-racing-authority-era-has-announced-the-official-schedule-for-the-2026-2027-uae-horse-racing-season",
      verifiedOn: "2026-09-02",
    },
    body: [
      "The nearest large public venue to Riviera is not a mall. It is a racecourse, and for five months of the year it is open on Friday evenings.",
      "The <strong>2026–27 UAE racing season</strong> opens on <strong>22 October</strong> at Abu Dhabi Turf Club. <strong>Meydan</strong>'s own season begins on <strong>6 November 2026</strong> and runs to <strong>27 March 2027</strong>, when the <strong>$12 million Dubai World Cup</strong> closes it.",
      "Meydan holds <strong>17 race meetings</strong> across those five months — the largest share of the <strong>64 meetings</strong> the Emirates Racing Authority has scheduled across five UAE racecourses. Two fall in November, three in December, five in January, four in February and three in March.",
      "The meetings that carry the international field are known collectively as the <strong>Dubai Racing Carnival</strong>, which runs from the November opening through to March and exists to bring overseas horses into form for World Cup night.",
    ],
    expertise:
      "The practical point for Riviera is the day of the week. Meydan races mostly on Friday evenings, with the biggest nights — World Cup night on 27 March among them — falling on a Saturday. Friday is the same evening the Al Khail and Meydan Road approaches carry weekend traffic into MBR City. The racecourse is roughly a kilometre and a half away in a straight line, so the arrival and departure peaks are audible and visible from the district rather than something happening across town. Individual fixture dates and race times are published by the Dubai Racing Club as each programme is confirmed; the season shape above is the Emirates Racing Authority's own schedule.",
  },

  {
    slug: "dubai-design-week-2026",
    createdAt: "2026-09-02T14:56:31+04:00",
    updatedAt: "2026-09-06T08:48:11+04:00",
    site: "riviera",
    image: "/covers/dubai-design-week-2026.jpg",
    imageAlt: "Overlapping flat paper shapes — two circles, two rectangles and a sand triangle — on a clear blue ground",
    imageKind: "generated",
    imageWidth: 1536,
    imageHeight: 864,
    title: "Dubai Design Week 2026",
    summary:
      "Six days at d3, roughly two kilometres from Riviera: installations, commissions, workshops, an outdoor marketplace and the Downtown Design fair.",
    start: "2026-11-03",
    end: "2026-11-08",
    venue: "Dubai Design District (d3)",
    city: "Dubai",
    organizer: "Dubai Design Week",
    category: "Design",
    source: {
      name: "Dubai Design Week",
      url: "https://www.dubaidesignweek.ae/",
      verifiedOn: "2026-09-02",
    },
    body: [
      "<strong>Dubai Design Week</strong> runs <strong>3–8 November 2026</strong> at the <strong>Dubai Design District (d3)</strong>.",
      "## The programme as the organisers frame it",
      "<strong>Abwab</strong> is this year's themed strand, examining the ways language is communicated, interpreted and remembered. <strong>Urban Commissions</strong> asks how spatial design shapes collective life in the public realm. Around them sit installations and exhibitions, workshops, activations and talks, a weekend-long outdoor <strong>Marketplace</strong>, and <strong>Downtown Design</strong>, described by the organisers as the leading fair in the Middle East for contemporary design.",
      "## Why the public realm strand is the one to read from here",
      "MBR City is a district being built at speed, largely as private developments with public space left over between them. A programme strand asking how spatial design shapes collective life is, for anyone living in that, less an abstract theme than a description of the argument going on outside the window.",
      "## What is not stated",
      "The organisers have not published admission terms for the 2026 edition on their own site. Design Week has historically been free to walk into with the fair ticketed separately, but that is a pattern rather than an announcement, and it is not repeated here as fact.",
    ],
    expertise:
      "d3 is about two kilometres from Riviera in a straight line and sits on the other side of Al Khail Road, which makes it one of the few genuinely walkable-adjacent cultural venues to the district — not walkable in November heat with a pushchair, but a short enough drive that an evening visit does not consume the evening. The Marketplace weekend is the part with the least queueing and the most that can be done without a booking.",
  },

  {
    slug: "dubai-fitness-challenge-2026",
    createdAt: "2026-08-25T18:18:34+04:00",
    updatedAt: "2026-09-08T19:46:47+04:00",
    site: "riviera",
    image: "/covers/dubai-fitness-challenge-2026.jpg",
    imageAlt: "A running track looping through a field of low city blocks, seen from above",
    imageKind: "generated",
    imageWidth: 1536,
    imageHeight: 864,
    title: "Dubai Fitness Challenge 2026",
    summary:
      "The city-wide 30x30 challenge runs October 31 to November 29 — 30 minutes of activity a day for 30 days, with Dubai Run, Dubai Ride and free classes across the city.",
    start: "2026-10-31",
    end: "2026-11-29",
    city: "Dubai",
    organizer: "Dubai Fitness Challenge",
    category: "City-wide",
    source: {
      name: "Gulf News",
      url: "https://gulfnews.com/uae/dubai-fitness-challenge-2026-dates-announced-1.500639620",
      verifiedOn: "2026-08-25",
    },
    body: [
      "Dubai Fitness Challenge returns for its tenth edition from October 31 to November 29, 2026, asking residents to commit to 30 minutes of activity a day for 30 days — the format the city knows as 30x30.",
      "The month carries the usual flagship events: <a href=\"/events/dubai-run-2026/\" title=\"Dubai Run 2026\">Dubai Run</a> on 22 November, <a href=\"/events/dubai-ride-2026/\" title=\"Dubai Ride 2026\">Dubai Ride</a> on 1 November, Dubai Stand Up Paddle on 7 and 8 November and Dubai Yoga on 29 November, plus Fitness Villages, Fitness Hubs and free community classes across the city. Registration for the individual events runs through the challenge's own official channels.",
    ],
    expertise:
      "This is a city-wide programme rather than a Riviera one, but it lands here more usefully than most: the promenade is a continuous canal-front walking route, which is exactly what a 30-minutes-a-day commitment needs and what most Dubai communities have to drive to find. Expect the promenade to be noticeably busier in the evenings through November.",
  },

  {
    slug: "ripe-market-2026-27",
    createdAt: "2026-09-08T16:29:32+04:00",
    updatedAt: "2026-09-08T16:29:32+04:00",
    site: "riviera",
    image: "/covers/ripe-market-2026-27.jpg",
    imageAlt: "A row of blue and yellow market canopies with a low table under each, on pale blue",
    imageKind: "generated",
    imageWidth: 1536,
    imageHeight: 864,
    title: "Ripe Market, 15th season",
    summary:
      "The weekend market at Police Academy Park reopens on 10 October and runs to 2 May, Saturdays and Sundays from 9am to 9pm — the nearest thing Dubai has to a standing weekend habit.",
    start: "2026-10-10",
    end: "2027-05-02",
    startTime: "09:00",
    endTime: "21:00",
    utcOffset: "+04:00",
    venue: "Dubai Police Academy Park, Umm Suqeim",
    city: "Dubai",
    country: "United Arab Emirates",
    organizer: "Ripe",
    category: "Market",
    source: {
      name: "Khaleej Times",
      url: "https://www.khaleejtimes.com/lifestyle/dubai-ripe-market-2026-opening-date-timings-location",
      verifiedOn: "2026-09-08",
    },
    body: [
      "Dubai does not have many things that happen every weekend for seven months. This is one of them, and it has been running long enough that the season opening is a date people diarise.",
      "## Ripe Market dates, 15th season",
      "The <strong>15th season</strong> opens on <strong>10 October 2026</strong> and runs until <strong>2 May 2027</strong>, every <strong>Saturday and Sunday from 9am to 9pm</strong>, at <strong>Dubai Police Academy Park</strong> in Umm Suqeim, off Sheikh Zayed Road.",
      "## What is there",
      "Independent stalls selling fashion, home decor, art and locally made goods, produce from UAE farmers, food vendors, creative workshops, activities for children and live entertainment.",
    ],
    expertise:
      "From Riviera this is a drive rather than a walk — Umm Suqeim is on the other side of Sheikh Zayed Road from MBR City — and the twelve-hour opening is what makes that worth planning around. The market is at its emptiest in the first two hours and at its hottest, in both senses, in the middle of the afternoon; October and early November are the two months when the late-evening end of the window is the pleasant one. Note also what the season dates tell you about Dubai's outdoor calendar generally: 10 October to 2 May is roughly the whole of it, and most open-air weekend events in the city sit inside those two bookends.",
  },

  {
    slug: "dubai-ride-2026",
    createdAt: "2026-09-08T19:46:47+04:00",
    updatedAt: "2026-09-12T17:35:10+04:00",
    site: "riviera",
    image: "/covers/dubai-ride-2026.jpg",
    imageAlt: "A pale road band crossing the frame between two textured edges, a dense field of small cream blocks below it, on pale blue",
    imageKind: "generated",
    imageWidth: 1536,
    imageHeight: 864,
    title: "Dubai Ride 2026",
    summary:
      "Sheikh Zayed Road closes to cars for the morning of Sunday November 1 and becomes a cycling route, free to join, with a 12km ride and a 4km family loop through Downtown Dubai.",
    start: "2026-11-01",
    startTime: "06:00",
    utcOffset: "+04:00",
    venue: "Sheikh Zayed Road and Downtown Dubai",
    city: "Dubai",
    country: "United Arab Emirates",
    organizer: "Dubai Department of Economy and Tourism and Dubai Sports Council",
    category: "Sport",
    tickets: { priceFrom: 0, currency: "AED" },
    source: {
      name: "Dubai Fitness Challenge",
      url: "https://dubaifitnesschallenge.com/en/dubai-ride",
      verifiedOn: "2026-09-08",
    },
    ticket: { url: "https://dubaifitnesschallenge.com/en/dubai-ride", label: "Official page" },
    body: [
      "Once a year the twelve-lane road that defines Dubai is emptied of cars and handed to people on bicycles. That is the whole event, and it is free.",
      "## Dubai Ride 2026: the date",
      "<strong>Sunday 1 November 2026</strong>, starting at <strong>6:00am</strong>. It is the <strong>sixth edition</strong>, the opening weekend of the month-long Dubai Fitness Challenge.",
      "## The two routes",
      "The <strong>12km Sheikh Zayed Road route</strong>, which the organisers recommend for more experienced riders, and the <strong>4km Downtown family route</strong>, a flat loop around Dubai Mall, Dubai Opera and Burj Khalifa. Both pass the Museum of the Future, and the longer one takes in the Dubai Water Canal.",
      "## What it costs and what it needs",
      "<strong>Nothing to enter, but registration is compulsory.</strong> At the time of writing the organisers say only that details of how to register will be announced; there is no open form yet. It is <strong>not a timed race</strong> — the official line is to ride at a comfortable pace and keep to the posted speed limits.",
      "## Who can ride",
      "Open to everyone. Adults over 21 can add <strong>children under 13</strong> to their own registration; <strong>13- to 21-year-olds</strong> register individually with parental or guardian consent. There are dedicated support entry points for <strong>adapted bikes, handcycles and tandem bikes</strong>.",
    ],
    faq: [
      {
        q: "Is Dubai Ride free?",
        a: "Yes. There is <strong>no entry fee</strong>, but every rider has to register, and registration is required for safety reasons rather than payment.",
      },
      {
        q: "When does Dubai Ride 2026 start?",
        a: "<strong>6:00am on Sunday 1 November 2026.</strong> Sheikh Zayed Road is closed to traffic for it.",
      },
      {
        q: "How long are the Dubai Ride routes?",
        a: "<strong>12km</strong> along Sheikh Zayed Road for confident riders, and a flat <strong>4km loop</strong> through Downtown Dubai for families and anyone riding at an easy pace.",
      },
      {
        q: "Is Dubai Ride a race?",
        a: "No. It is not timed and there are no results \u2014 the organisers ask riders to keep a comfortable pace and observe the speed limits on the route.",
      },
      {
        q: "Can children take part in Dubai Ride?",
        a: "Yes. An adult over 21 adds children under 13 to their own registration, and riders aged 13 to 21 register themselves with a parent or guardian's consent.",
      },
    ],
    expertise:
      "The 4km Downtown loop is the one to pick if you have not ridden in traffic recently, and not because of the distance \u2014 it is flat and it is a loop, so you can stop whenever you like and still be at the start. The 12km route is an out-and-back on a road with long gentle inclines you never notice in a car. The real constraint is neither: it is that the road reopens, so the last riders are moved along. Getting there is the part to plan, because the metro runs above the closed road and the stations nearest the start fill first \u2014 arriving a station early and riding in is the standard move. The <a href=\"/events/dubai-fitness-challenge-2026/\" title=\"Dubai Fitness Challenge, 30x30\">Fitness Challenge</a> the ride opens runs for another four weeks, and <a href=\"/events/dubai-run-2026/\" title=\"Dubai Run 2026\">Dubai Run</a> closes the same road on foot three weeks later.",
  },

  {
    slug: "dubai-run-2026",
    createdAt: "2026-09-08T19:46:47+04:00",
    updatedAt: "2026-09-12T17:35:10+04:00",
    site: "riviera",
    image: "/covers/dubai-run-2026.jpg",
    imageAlt: "A pale road band curving across the top of the frame and a separate ring of small cream blocks below it, on pale blue",
    imageKind: "generated",
    imageWidth: 1536,
    imageHeight: 864,
    title: "Dubai Run 2026",
    summary:
      "Sheikh Zayed Road closes again on Sunday November 22 for the seventh Dubai Run, free to enter with a 10km and a 5km route, starting at 6:30am and finishing by nine.",
    start: "2026-11-22",
    startTime: "06:30",
    endTime: "09:00",
    utcOffset: "+04:00",
    venue: "Sheikh Zayed Road and Downtown Dubai",
    city: "Dubai",
    country: "United Arab Emirates",
    organizer: "Dubai Department of Economy and Tourism and Dubai Sports Council",
    category: "Sport",
    tickets: { priceFrom: 0, currency: "AED" },
    source: {
      name: "Dubai Fitness Challenge",
      url: "https://dubaifitnesschallenge.com/en/dubai-run",
      verifiedOn: "2026-09-08",
    },
    ticket: { url: "https://dubaifitnesschallenge.com/en/dubai-run", label: "Official page" },
    body: [
      "Three weeks after the bicycles, the same road closes for people on foot. The organisers call it the world's largest fun run, and the format is the same one that makes it work: free, untimed, and on a road you cannot otherwise walk on.",
      "## The date and the clock",
      "<strong>Sunday 22 November 2026.</strong> The start is <strong>6:30am</strong>, the <strong>start line closes at 8:00am</strong>, and the finish is <strong>9:00am</strong>. It is the <strong>seventh edition</strong>.",
      "## The two routes",
      "<strong>10km</strong>, starting and finishing on Sheikh Zayed Road, and <strong>5km</strong> through Downtown Dubai along Sheikh Mohammed bin Zayed Boulevard. Both pass the Museum of the Future, Emirates Towers, Dubai Opera and Burj Khalifa.",
      "## What it costs and what it needs",
      "<strong>Free to enter, and registration is compulsory.</strong> The organisers say details of how to register will be announced. A <strong>bib is mandatory</strong>: anyone without one will not be allowed to run, which is the rule that makes the registration deadline matter more than the entry fee that does not exist.",
    ],
    faq: [
      {
        q: "Is Dubai Run free?",
        a: "Yes. There is <strong>no entry fee</strong>. Registration is still required, and the organisers give safety and security as the reason.",
      },
      {
        q: "What time does Dubai Run 2026 start and finish?",
        a: "It starts at <strong>6:30am</strong> on 22 November 2026. The <strong>start line closes at 8:00am</strong> and the event finishes at <strong>9:00am</strong>.",
      },
      {
        q: "How long are the Dubai Run routes?",
        a: "<strong>10km</strong>, out and back on Sheikh Zayed Road, and <strong>5km</strong> through Downtown Dubai on Sheikh Mohammed bin Zayed Boulevard.",
      },
      {
        q: "Can I run Dubai Run without a bib?",
        a: "No. Bibs are required for safety, and anyone without one will not be allowed to take part \u2014 so registering is the thing that has to happen in advance, not paying.",
      },
    ],
    expertise:
      "The 8:00am cut-off is the number that actually shapes the morning. It is not a pace requirement, it is a start-line closure: a 10km walk at an easy pace still finishes inside the window if you are through the line early, and does not if you arrive at half past seven. The other thing worth knowing is that the two routes have different characters despite the shared branding \u2014 the 5km through Downtown is enclosed and shaded in patches by the towers, and the 10km on Sheikh Zayed Road is wide, open and completely exposed, which at that hour in November is pleasant and at any other hour would not be.",
  },
];
