import type { EventItem } from "../types.ts";

export const items: EventItem[] = [
  {
    slug: "breakpoint-2026-london",
    site: "sol2go",
    image: "/covers/breakpoint-2026-london.jpg",
    imageAlt: "A tall paper hall with a barrel-vaulted glass roof cut as flat violet and lilac sheets, a wide crowd band of pale mint below it",
    imageKind: "generated",
    imageWidth: 1536,
    imageHeight: 864,
    title: "Solana Breakpoint 2026",
    summary:
      "Solana's flagship conference lands at Olympia London on 15–17 November, its theme the Token Supercycle. Developer tickets are $250, general admission $550, students $100.",
    start: "2026-11-15",
    end: "2026-11-17",
    startTime: "16:00",
    utcOffset: "+00:00",
    venue: "Olympia Convention Centre",
    city: "London",
    organizer: "Solana Foundation",
    category: "Conference",
    featured: 1,
    source: {
      name: "Solana Foundation",
      url: "https://solana.com/breakpoint",
      verifiedOn: "2026-09-06",
    },
    ticket: { url: "https://luma.com/breakpoint2026", label: "Tickets" },
    tickets: { priceFrom: 100, priceTo: 800, currency: "USD" },
    body: [
      "Breakpoint has been in Lisbon, Amsterdam, Singapore and Abu Dhabi. In 2026 it is in west London, in a Victorian exhibition hall with a barrel-vaulted glass roof, and the framing has moved with it: this is the year the conference stops addressing the room as developers first.",
      "## The dates and the room",
      "<strong>15 to 17 November 2026</strong> at the <strong>Olympia Convention Centre</strong> in London. The Foundation puts attendance at <strong>8,000+</strong>.",
      "## What the theme actually says",
      "The Foundation's own words: Breakpoint 2026 “centers on the Token Supercycle: a new era in which stablecoins, tokenized assets, payments, and AI-driven economic activity increasingly move onchain.” The audience it names is “financial institutions, technology companies, investors, and policymakers” — which is a different guest list from the one Breakpoint had when it was a builders' reunion.",
      "## What a ticket costs",
      "<strong>Developers $250</strong>. <strong>Students $100</strong>. <strong>General admission $550</strong>, rising to <strong>$800</strong> late. The developer and student tiers are the interesting part of that table: a conference that prices its builders at less than half of general admission is telling you who it still wants in the room.",
      "## The week around it",
      "Breakpoint is the middle of a fortnight, not a standalone. The <strong>Solana Hacker House</strong> runs 1–12 November, <strong>Scale or Die</strong> takes the day before on 14 November, and side events fill the evenings of the 16th. If you are flying in, the calendar to plan against is the fortnight, not the three days.",
    ],
    expertise:
      "Two things are worth knowing before you buy. First, the price ladder is real: the late-bird tier at $800 is a $250 penalty for deciding in October, and the developer tier at $250 has historically sold out well before the general one. Second, a London Breakpoint is the cheapest one this conference has been to reach for anyone in Europe since Lisbon in 2023 — which is also why the room will be fuller than the ticket count suggests, because the side events do not require a badge. If the reason you are going is the hallway rather than the stage, the Hacker House fortnight and the free evening events may be the better half of the trip.",
  },

  {
    slug: "crypto-worlds-fair-2026",
    site: "sol2go",
    image: "/covers/crypto-worlds-fair-2026.jpg",
    imageAlt: "A ring of flat pavilion shapes in violet, lilac and mint paper arranged around a small cream disc",
    imageKind: "generated",
    imageWidth: 1536,
    imageHeight: 864,
    title: "Crypto World's Fair",
    cardTitle: "Crypto World's Fair hackathon",
    summary:
      "Colosseum's online hackathon runs four weeks from 14 September to 12 October, across eight ecosystems at once. Winners can take $250,000 from its accelerator.",
    start: "2026-09-14",
    end: "2026-10-12",
    city: "Online",
    organizer: "Colosseum",
    category: "Hackathon",
    featured: 2,
    audience: ["Founders", "Developers", "Designers", "First-time teams"],
    source: {
      name: "Colosseum",
      url: "https://www.colosseum.com/worldsfair",
      verifiedOn: "2026-09-06",
    },
    ticket: { url: "https://www.colosseum.com/worldsfair", label: "Register" },
    body: [
      "Colosseum runs the hackathons that Solana used to run itself, and it has spent three years being a Solana competition. This one is not. The Crypto World's Fair puts eight ecosystems on the same page and asks builders to pick one.",
      "## The dates",
      "<strong>14 September to 12 October 2026</strong> — four weeks, entirely online. Colosseum describes it as “a global, online competition where founders sprint over 4 weeks to build impactful products”, and as “an online hackathon bringing together builders and founders across blockchain ecosystems to launch breakout startups.”",
      "## Who is on the page",
      "The ecosystem logos shown are <strong>Solana</strong>, <strong>Ethereum</strong>, <strong>Hyperliquid</strong>, <strong>Base</strong>, <strong>Tempo</strong>, <strong>Arbitrum</strong>, <strong>Zcash</strong> and <strong>Robinhood Chain</strong>.",
      "## What is actually on offer",
      "Non-dilutive prizes and, for the teams that get through, a place in Colosseum's full-time accelerator with <strong>$250,000 in capital from its venture fund</strong>. The prize table itself had not been published as of 6 September.",
      "## The signal to read",
      "The registration counter stood at <strong>778 builders</strong> when we checked. That is early — the last Colosseum competition finished with a registration figure an order of magnitude higher, and most teams sign up in the final week.",
    ],
    expertise:
      "A cross-ecosystem hackathon changes what a good submission looks like. In a single-chain competition the judges know the ecosystem's gaps and you can win by filling one; here the field is eight ecosystems wide, so a project whose whole argument is a chain-specific optimisation has to explain itself to a judge who does not share the premise. The teams that tend to do well in that format are the ones whose product makes sense to somebody who does not care which chain it is on, and which then have a specific, defensible reason for the chain they chose. The four-week length also matters: it is a business sprint as much as an engineering one, and Colosseum has been explicit for two years that it funds founders rather than repositories.",
  },

  {
    slug: "solana-hacker-house-london-2026",
    site: "sol2go",
    image: "/covers/solana-hacker-house-london-2026.jpg",
    imageAlt: "Rows of flat desk shapes in lilac and mint paper receding under a long violet ceiling band",
    imageKind: "generated",
    imageWidth: 1536,
    imageHeight: 864,
    title: "Solana Hacker House — London",
    cardTitle: "Solana Hacker House London",
    summary:
      "Thirteen days of free workspace and workshops in London, 1–12 November, running straight into Breakpoint. Approval required, and capacity is limited.",
    start: "2026-11-01",
    end: "2026-11-12",
    startTime: "10:00",
    endTime: "20:00",
    utcOffset: "+00:00",
    city: "London",
    organizer: "Solana Foundation",
    category: "Hacker House",
    featured: 3,
    audience: ["Developers", "Founders", "Designers"],
    source: {
      name: "Solana Foundation",
      url: "https://luma.com/london-hh-26",
      verifiedOn: "2026-09-06",
    },
    ticket: { url: "https://luma.com/london-hh-26", label: "Request to join" },
    body: [
      "The Hacker House is the part of the Breakpoint fortnight that costs nothing and takes the most out of you. Thirteen days of desks, and the expectation that you leave with something built.",
      "## The dates and the day",
      "<strong>1 to 12 November 2026</strong> in London, open <strong>10:00 to 20:00</strong> daily. Registration is handled on the day, <strong>10:00 to 17:00</strong>.",
      "## What is in the building",
      "Workspace with wifi and power, food, lounges and dedicated build zones. The programme is described as “Workshops and deep dives across DeFi, security, infrastructure, and applications”, with Ecosystem Experts and Solana Foundation teams on hand.",
      "## Getting in",
      "<strong>Approval is required</strong> and capacity is limited: you request to join through the event page, and the organisers ask that you keep your RSVP current rather than holding a place you will not use. Anyone wanting to lead a session applies through a typeform; sponsorship goes to events@solana.org.",
      "## Where the address is",
      "Not published. The venue is released to approved guests through the event page rather than announced, which is normal for a Hacker House and worth knowing before you book a hotel.",
    ],
    expertise:
      "Thirteen days is unusually long — most Hacker Houses run five. The length is deliberate: this one exists to fill the run-up to Breakpoint, so the first week is the quiet, useful one and the second is when the conference crowd arrives and the desks stop being available. If you are coming to build rather than to network, the first week is the whole value of the trip, and it is also the week the Ecosystem Experts have time for a real conversation rather than a queue.",
  },

  {
    slug: "scale-or-die-2026",
    site: "sol2go",
    image: "/covers/scale-or-die-2026.jpg",
    imageAlt: "A steep ascending stack of narrow paper bars in violet and mint against a pale ground",
    imageKind: "generated",
    imageWidth: 1536,
    imageHeight: 864,
    title: "Scale or Die",
    summary:
      "A one-day engineering conference in London on 14 November, 09:30 to 18:30, the day before Breakpoint opens.",
    start: "2026-11-14",
    startTime: "09:30",
    endTime: "18:30",
    utcOffset: "+00:00",
    city: "London",
    organizer: "Solana Foundation",
    category: "Conference",
    source: {
      name: "Solana Foundation",
      url: "https://luma.com/scale-or-die-26",
      verifiedOn: "2026-09-06",
    },
    ticket: { url: "https://luma.com/scale-or-die-26", label: "Register" },
    body: [
      "Scale or Die is the technical day that Breakpoint's main stage no longer has room for. One day, one track, London, and it happens the day before the conference opens.",
      "## The details",
      "<strong>14 November 2026</strong>, <strong>09:30 to 18:30</strong>, in London. The address is released to registered guests rather than published.",
      "## Why the day before",
      "Because the people it is for are already flying in. Putting the engineering day on the 14th means it costs a Saturday rather than a Breakpoint session, and it is the reason a developer ticket for the fortnight is worth more than the three conference days on its own.",
      "The full speaker list had not been published as of 6 September.",
    ],
    expertise:
      "The pattern to watch is that Breakpoint's own programme has moved toward institutions and policy, and Scale or Die is where the material that used to be on the main stage went. If the reason you were considering Breakpoint is the protocol engineering, this single day may be the better ticket — and it is a Saturday, so it costs nothing in working time.",
  },

  {
    slug: "solana-summit-canada-2026",
    site: "sol2go",
    image: "/covers/solana-summit-canada-2026.jpg",
    imageAlt: "A flat gabled market-hall silhouette in violet paper with a row of mint arches beneath it",
    imageKind: "generated",
    imageWidth: 1536,
    imageHeight: 864,
    title: "Solana Summit Canada",
    summary:
      "Two days in Toronto on 23–24 September at St. Lawrence Market North, the Canadian stop on the Solana Summit circuit.",
    start: "2026-09-23",
    end: "2026-09-24",
    startTime: "09:30",
    utcOffset: "-04:00",
    venue: "St. Lawrence Market North",
    city: "Toronto",
    organizer: "Superteam Canada",
    category: "Summit",
    source: {
      name: "Solana Foundation events calendar",
      url: "https://lu.ma/Solana-Summit-Canada",
      verifiedOn: "2026-09-06",
    },
    ticket: { url: "https://lu.ma/Solana-Summit-Canada", label: "Register" },
    body: [
      "The Solana Summit series is the Foundation's regional format: one or two days, a local host community, and a room sized for the country rather than the continent. Canada's runs in Toronto at the end of September.",
      "## The details",
      "<strong>23 and 24 September 2026</strong> at <strong>St. Lawrence Market North</strong>, Toronto. The building is the newer half of the St. Lawrence Market complex, which is a market hall rather than a conference centre — expect an open floor rather than breakout rooms.",
      "The programme had not been published in full as of 6 September.",
    ],
  },

  {
    slug: "ethglobal-tokyo-2026",
    site: "sol2go",
    image: "/covers/ethglobal-tokyo-2026.jpg",
    imageAlt: "A tall paper gate form in violet over a dense grid of small mint and lilac squares",
    imageKind: "generated",
    imageWidth: 1536,
    imageHeight: 864,
    title: "ETHGlobal Tokyo 2026",
    summary:
      "A three-day in-person hackathon in Tokyo, 25–27 September, with the Pragma Tokyo conference alongside it on the 26th.",
    start: "2026-09-25",
    end: "2026-09-27",
    utcOffset: "+09:00",
    city: "Tokyo",
    organizer: "ETHGlobal",
    category: "Hackathon",
    source: {
      name: "ETHGlobal",
      url: "https://ethglobal.com/events",
      verifiedOn: "2026-09-06",
    },
    ticket: { url: "https://ethglobal.com/events", label: "Apply to attend" },
    body: [
      "Not a Solana event, and here for the same reason the rest of the wider calendar is: the people who build across chains keep both dates in one diary.",
      "## The details",
      "<strong>25 to 27 September 2026</strong>, Tokyo, listed by ETHGlobal as an in-person hackathon. Attendance is by application rather than by ticket.",
      "## The day beside it",
      "<strong>Pragma Tokyo 2026</strong> runs on <strong>26 September</strong> in the same city — ETHGlobal's conference format, which travels with the hackathons rather than separately from them.",
      "Two other dates from the same calendar are worth noting for the autumn: <strong>ETHOnline 2026</strong>, an async online hackathon running <strong>4 to 16 September</strong>, and <strong>ETHGlobal Mumbai</strong> on <strong>6 to 8 November</strong>, with <strong>Pragma Mumbai</strong> the day before it.",
    ],
  },

  {
    slug: "solana-summit-korea-2026",
    site: "sol2go",
    image: "/covers/solana-summit-korea-2026.jpg",
    imageAlt: "A stepped skyline of flat violet towers with a wide mint river band across the lower frame",
    imageKind: "generated",
    imageWidth: 1536,
    imageHeight: 864,
    title: "Solana Summit Korea",
    summary:
      "A single day in Seoul on 30 September, 10:00 to 17:00, on Yeoui-daero in the Yeouido financial district.",
    start: "2026-09-30",
    startTime: "10:00",
    endTime: "17:00",
    utcOffset: "+09:00",
    city: "Seoul",
    organizer: "Solana Foundation",
    category: "Summit",
    source: {
      name: "Solana Foundation events calendar",
      url: "https://lu.ma/solana-summit-korea-2026",
      verifiedOn: "2026-09-06",
    },
    ticket: { url: "https://lu.ma/solana-summit-korea-2026", label: "Register" },
    body: [
      "## The details",
      "<strong>30 September 2026</strong>, <strong>10:00 to 17:00</strong>, Seoul. The listing places it on <strong>Yeoui-daero</strong> — Yeouido, which is the financial district rather than the startup one, and that is a choice worth reading.",
      "The exact address is released to registered guests. The programme had not been published in full as of 6 September.",
    ],
  },

  {
    slug: "solana-summit-singapore-2026",
    site: "sol2go",
    image: "/covers/solana-summit-singapore-2026.jpg",
    imageAlt: "Three tall paper columns joined by a long flat deck in violet, a mint bay band below",
    imageKind: "generated",
    imageWidth: 1536,
    imageHeight: 864,
    title: "Solana Summit Singapore",
    summary:
      "6 October at the Ritz-Carlton Millenia, 09:00 to 18:00 — and the Solana Capital Forum runs in the same city on the same day.",
    start: "2026-10-06",
    startTime: "09:00",
    endTime: "18:00",
    utcOffset: "+08:00",
    venue: "The Ritz-Carlton, Millenia Singapore",
    city: "Singapore",
    organizer: "Solana Foundation",
    category: "Summit",
    source: {
      name: "Solana Foundation events calendar",
      url: "https://lu.ma/solana-summit-singapore-2026",
      verifiedOn: "2026-09-06",
    },
    ticket: { url: "https://lu.ma/solana-summit-singapore-2026", label: "Register" },
    body: [
      "## The details",
      "<strong>6 October 2026</strong>, <strong>09:00 to 18:00</strong>, at <strong>The Ritz-Carlton, Millenia Singapore</strong>.",
      "## The clash worth knowing about",
      "The <strong>Solana Capital Forum Singapore</strong> runs the same day, <strong>12:00 to 20:00</strong>, in the Orchard area. Two Solana events, one city, one date, overlapping by six hours — they are aimed at different rooms, but if you were planning to do both, the afternoon is the part you have to choose between.",
    ],
  },

  {
    slug: "solana-summit-india-2026",
    site: "sol2go",
    image: "/covers/solana-summit-india-2026.jpg",
    imageAlt: "A row of flat arched openings in violet paper with mint sea shapes behind them",
    imageKind: "generated",
    imageWidth: 1536,
    imageHeight: 864,
    title: "Solana Summit India",
    summary:
      "Mumbai on 2 November, 10:00 to 19:00, in Navpada — four days before ETHGlobal fills the same city.",
    start: "2026-11-02",
    startTime: "10:00",
    endTime: "19:00",
    utcOffset: "+05:30",
    city: "Mumbai",
    organizer: "Solana Foundation",
    category: "Summit",
    source: {
      name: "Solana Foundation events calendar",
      url: "https://lu.ma/solana-summit-india",
      verifiedOn: "2026-09-06",
    },
    ticket: { url: "https://lu.ma/solana-summit-india", label: "Register" },
    body: [
      "## The details",
      "<strong>2 November 2026</strong>, <strong>10:00 to 19:00</strong>, Mumbai, in <strong>Navpada</strong>. The exact address is released to registered guests.",
      "## The week it sits in",
      "Mumbai has a crowded first week of November: <strong>Pragma Mumbai</strong> on the <strong>5th</strong> and <strong>ETHGlobal Mumbai</strong> from the <strong>6th to the 8th</strong>. If you are travelling to India for one of them, the Summit is three days of overlap away from the other.",
    ],
  },

  {
    slug: "solana-startup-connect-ghana-2026",
    site: "sol2go",
    image: "/covers/solana-startup-connect-ghana-2026.jpg",
    imageAlt: "Interlocking flat chevrons in violet, mint and cream paper forming a broad woven band",
    imageKind: "generated",
    imageWidth: 1536,
    imageHeight: 864,
    title: "solanaStartupConnect Ghana",
    summary:
      "Two days at the Accra Digital Centre on 15–16 October, the Solana calendar's West African stop this autumn.",
    start: "2026-10-15",
    end: "2026-10-16",
    utcOffset: "+00:00",
    venue: "Accra Digital Centre",
    city: "Accra",
    category: "Summit",
    source: {
      name: "Solana Foundation events calendar",
      url: "https://lu.ma/nx9ps6ud",
      verifiedOn: "2026-09-06",
    },
    ticket: { url: "https://lu.ma/nx9ps6ud", label: "Register" },
    body: [
      "## The details",
      "<strong>15 and 16 October 2026</strong> at the <strong>Accra Digital Centre</strong>, Ghana. The listing gives a start time in a timezone that does not match the venue, so we are printing the dates and leaving the clock to the organiser's page rather than publishing an hour we cannot stand behind.",
      "The programme had not been published in full as of 6 September.",
    ],
  },

  {
    slug: "co-working-fridays-london-september-2026",
    site: "sol2go",
    title: "Co-Working Fridays: London Chapter",
    summary:
      "A free Friday desk at Somerset House, 11 September, 10:00 to 20:00. The London chapter runs it most weeks.",
    start: "2026-09-11",
    startTime: "10:00",
    endTime: "20:00",
    utcOffset: "+01:00",
    venue: "Somerset House",
    city: "London",
    category: "Co-working",
    source: {
      name: "Solana Foundation events calendar",
      url: "https://lu.ma/london-sep-11",
      verifiedOn: "2026-09-06",
    },
  },

  {
    slug: "the-future-of-finance-thessaloniki-2026",
    site: "sol2go",
    title: "The Future of Finance — Thessaloniki",
    cardTitle: "The Future of Finance, Thessaloniki",
    summary:
      "An evening meetup in the Ladadika quarter on 13 September, 19:30 to 22:00.",
    start: "2026-09-13",
    startTime: "19:30",
    endTime: "22:00",
    utcOffset: "+03:00",
    city: "Thessaloniki",
    category: "Meetup",
    source: {
      name: "Solana Foundation events calendar",
      url: "https://lu.ma/q242rqc4",
      verifiedOn: "2026-09-06",
    },
  },

  {
    slug: "solana-ecosystem-call-september-2026",
    site: "sol2go",
    title: "The Solana Ecosystem Call — September",
    cardTitle: "Solana Ecosystem Call, September",
    summary: "The monthly ecosystem call, online, 24 September, 14:00 to 15:00 UTC.",
    start: "2026-09-24",
    startTime: "14:00",
    endTime: "15:00",
    utcOffset: "+00:00",
    city: "Online",
    category: "Online",
    source: {
      name: "Solana Foundation events calendar",
      url: "https://lu.ma/0j8gx7i1",
      verifiedOn: "2026-09-06",
    },
  },

  {
    slug: "superteam-canada-community-call-october-2026",
    site: "sol2go",
    title: "Superteam Canada Community Call",
    summary: "Half an hour online on 1 October, 16:00 to 16:30 UTC.",
    start: "2026-10-01",
    startTime: "16:00",
    endTime: "16:30",
    utcOffset: "+00:00",
    city: "Online",
    category: "Online",
    source: {
      name: "Solana Foundation events calendar",
      url: "https://lu.ma/aq7rqqmn",
      verifiedOn: "2026-09-06",
    },
  },

  {
    slug: "solana-capital-forum-singapore-2026",
    site: "sol2go",
    title: "Solana Capital Forum Singapore",
    summary:
      "6 October in Orchard, 12:00 to 20:00 — the institutional half of Solana's Singapore day.",
    start: "2026-10-06",
    startTime: "12:00",
    endTime: "20:00",
    utcOffset: "+08:00",
    city: "Singapore",
    organizer: "Solana Foundation",
    category: "Forum",
    source: {
      name: "Solana Foundation",
      url: "https://lu.ma/sol-cap-sg",
      verifiedOn: "2026-09-06",
    },
  },

  {
    slug: "islanddao-v5-2026",
    site: "sol2go",
    title: "IslandDAO v5",
    summary:
      "A three-and-a-half-week builder residency in Florianópolis, Brazil, 19 October to 11 November.",
    start: "2026-10-19",
    end: "2026-11-11",
    utcOffset: "-03:00",
    city: "Florianópolis",
    category: "Residency",
    source: {
      name: "Solana Foundation events calendar",
      url: "https://lu.ma/6laijuyn",
      verifiedOn: "2026-09-06",
    },
  },

  {
    slug: "money-layer-breakpoint-week-2026",
    site: "sol2go",
    title: "Money Layer — Breakpoint Week",
    cardTitle: "Money Layer, Breakpoint week",
    summary: "A London side event on the evening of 16 November, 18:30 to 22:00.",
    start: "2026-11-16",
    startTime: "18:30",
    endTime: "22:00",
    utcOffset: "+00:00",
    city: "London",
    category: "Side event",
    source: {
      name: "Solana Foundation events calendar",
      url: "https://lu.ma/xykfcf1a",
      verifiedOn: "2026-09-06",
    },
  },

  {
    slug: "pr1me-london-dinner-2026",
    site: "sol2go",
    title: "Pr1me London — dinner for web3 finance",
    cardTitle: "Pr1me London dinner",
    summary:
      "An invitation-shaped dinner during Breakpoint week, London, 16 November, 19:00 to 22:00.",
    start: "2026-11-16",
    startTime: "19:00",
    endTime: "22:00",
    utcOffset: "+00:00",
    city: "London",
    category: "Side event",
    source: {
      name: "Solana Foundation events calendar",
      url: "https://lu.ma/aqntywn2",
      verifiedOn: "2026-09-06",
    },
  },

  {
    slug: "solana-community-call-november-2026",
    site: "sol2go",
    title: "Solana Community Call — November",
    cardTitle: "Community Call, November",
    summary: "Half an hour online on 5 November, 17:00 to 17:30 UTC.",
    start: "2026-11-05",
    startTime: "17:00",
    endTime: "17:30",
    utcOffset: "+00:00",
    city: "Online",
    category: "Online",
    source: {
      name: "Solana Foundation events calendar",
      url: "https://lu.ma/8uhc300o",
      verifiedOn: "2026-09-06",
    },
  },

  {
    slug: "solana-community-call-december-2026",
    site: "sol2go",
    title: "Solana Community Call — December",
    cardTitle: "Community Call, December",
    summary: "Half an hour online on 3 December, 17:00 to 17:30 UTC.",
    start: "2026-12-03",
    startTime: "17:00",
    endTime: "17:30",
    utcOffset: "+00:00",
    city: "Online",
    category: "Online",
    source: {
      name: "Solana Foundation events calendar",
      url: "https://lu.ma/sejn139p",
      verifiedOn: "2026-09-06",
    },
  },

  {
    slug: "solana-frontier-hackathon-2026",
    site: "sol2go",
    image: "/covers/solana-frontier-hackathon-2026.jpg",
    imageAlt: "A wide horizon band of layered violet and mint paper with one small cream flag shape near the edge",
    imageKind: "generated",
    imageWidth: 1536,
    imageHeight: 864,
    title: "Solana Frontier Hackathon",
    summary:
      "Colosseum's spring competition ran 6 April to 11 May and paid out $250,000 in prizes, with another $250,000 per accelerator place — and no tracks and no bounties at all.",
    start: "2026-04-06",
    end: "2026-05-11",
    city: "Online",
    organizer: "Colosseum",
    category: "Hackathon",
    source: {
      name: "Colosseum",
      url: "https://blog.colosseum.com/announcing-the-solana-frontier-hackathon/",
      verifiedOn: "2026-09-06",
    },
    body: [
      "The Frontier hackathon is the most useful thing to read before entering the current one, because it is where Colosseum wrote down what it actually rewards.",
      "## The dates",
      "<strong>6 April to 11 May 2026</strong>, online. Announced on 6 April.",
      "## What it paid",
      "<strong>$30,000</strong> to the grand champion. <strong>$10,000</strong> each to the next twenty startups. <strong>$10,000</strong> for the best university team and <strong>$10,000</strong> for the best public goods project. Up to <strong>ten</strong> winners took a place in the accelerator, each carrying <strong>$250,000 in pre-seed funding</strong>, mentorship, AI credits, in-person support at Colosseum's San Francisco office and a private demo day. Colosseum put the total venture deployment at <strong>over $2.5 million</strong>.",
      "## The part people miss",
      "There were <strong>no tracks and no bounties</strong>. Colosseum framed the competition as “intensive engineering <em>and</em> business sprints where elite developers vie for prizes and pre-seed funding” — which is a polite way of saying that a technically excellent project with no business behind it does not place.",
    ],
    outcome: [
      "The format carried straight into the autumn: the Crypto World's Fair, which opened on 14 September, uses the same accelerator terms — $250,000 per team from the venture fund — and the same absence of tracks.",
    ],
  },

  {
    slug: "ethglobal-lisbon-2026",
    site: "sol2go",
    title: "ETHGlobal Lisbon 2026",
    summary:
      "A three-day hackathon in Lisbon on 24–26 July, with Pragma Lisbon the day after and a co-working day before it.",
    start: "2026-07-24",
    end: "2026-07-26",
    utcOffset: "+01:00",
    city: "Lisbon",
    organizer: "ETHGlobal",
    category: "Hackathon",
    source: {
      name: "ETHGlobal",
      url: "https://ethglobal.com/events",
      verifiedOn: "2026-09-06",
    },
    outcome: [
      "ETHGlobal wrapped the weekend in two more dates in the same city: Onchain Builders Day on 23 July and the Pragma Lisbon conference on 25 July. The next in-person one on its calendar is Tokyo, 25 to 27 September.",
    ],
  },
];
