import type { EventItem } from "../types.ts";

export const items: EventItem[] = [
  {
    slug: "crypto-expo-dubai-2026",
    site: "sol2go",
    image: "/covers/crypto-expo-dubai-2026.jpg",
    imageAlt: "A wide flat hall in violet paper with two rows of small stand shapes and one tall mint tower rising behind it",
    imageKind: "generated",
    imageWidth: 1536,
    imageHeight: 864,
    title: "Crypto Expo Dubai 2026",
    summary:
      "The eighth edition takes the Dubai World Trade Centre on 9 and 10 September, pitched at institutions rather than builders: 7,000+ attendees, 100+ exhibitors, 140+ speakers from 40+ countries.",
    start: "2026-09-09",
    end: "2026-09-10",
    startTime: "10:00",
    endTime: "18:00",
    utcOffset: "+04:00",
    venue: "Dubai World Trade Centre",
    city: "Dubai",
    country: "United Arab Emirates",
    organizer: "Crypto Expo Dubai",
    category: "Conference",
    audience: [
      "Institutional investors",
      "Asset managers and family offices",
      "Licensed digital asset companies",
      "Exchanges and brokers",
      "Custody and infrastructure providers",
      "Compliance and licensing",
      "Web3 founders",
      "Regulators",
    ],
    source: {
      name: "Crypto Expo Dubai",
      url: "https://cryptoexpodubai.com",
      verifiedOn: "2026-09-06",
    },
    ticket: { url: "https://cryptoexpodubai.com/dubai#tickets", label: "Tickets" },
    // Two of the 140 the organiser advertises, and the two that say what
    // kind of room this is. Both are listed by name on the event's own site,
    // checked on the date in `source`.
    speakers: [
      {
        name: "Simon O’Brien",
        role: "Executive Director of Markets",
        org: "Financial Services Regulatory Authority, Abu Dhabi Global Market",
        note: "Led the development of ADGM’s virtual asset regulatory framework.",
      },
      {
        name: "Sohaib Memon",
        role: "Virtual Assets Supervisory Officer",
        org: "Capital Market Authority",
      },
    ],
    body: [
      "The one least like the rest of this calendar. Where Solana Breakpoint and the Hacker House are addressed to people who write code, Crypto Expo Dubai is addressed to the people who license, custody and allocate — and it says so in its own strapline: “Where Digital Assets Meet Institutional Capital.”",
      "## The dates and the hall",
      "<strong>9 and 10 September 2026</strong>, <strong>10:00 to 18:00</strong>, at the <strong>Dubai World Trade Centre</strong>. It is the <strong>eighth edition</strong>.",
      "## The numbers the organiser publishes",
      "<strong>7,000+ attendees</strong>, <strong>100+ exhibitors</strong>, <strong>140+ speakers</strong>, <strong>40+ countries</strong>. Those are the organiser’s own figures for the edition, not an audited count.",
      "## Who it is built for",
      "The organiser lists six layers by name: institutional investors, asset managers and family offices; licensed digital asset companies and regulated platforms; exchanges, brokers and trading platforms; custody, wallet, blockchain and infrastructure providers; fintech, payments, compliance and licensing services; and Web3 founders, enterprises, regulators and strategic investors.",
      "## The regulators are on the programme, not in the audience",
      "Among the speakers listed on the site are <strong>Simon O’Brien</strong>, Executive Director of Markets at the <strong>Financial Services Regulatory Authority of Abu Dhabi Global Market</strong>, who led the development of ADGM’s virtual asset regulatory framework, and <strong>Sohaib Memon</strong>, a Virtual Assets Supervisory Officer at the <strong>Capital Market Authority</strong>. That is the difference between this event and the rest of the autumn in one line.",
      "## What the site does not publish",
      "Ticket prices. The organiser sends you to a booking page rather than printing a table, so we are not quoting a figure. The full agenda, the exhibitor list and the floor plan each have a page on the site; the side event, the awards and the HashMining &amp; AI Summit are named in the navigation without dates of their own.",
    ],
    expertise:
      "Read the audience list before you buy, because it is the whole review. Six segments are named and not one of them is a developer: this is a licensing, custody and allocation room, and two of the people on the programme supervise virtual assets for a living. If you are raising, selling infrastructure or trying to get a straight answer out of a regulator, two days at the World Trade Centre is a cheaper way to do it than two months of email. If you came to talk about consensus, this is the wrong hall, and the London fortnight in November is the one to save the flight for.",
  },

  {
    slug: "breakpoint-2026-london",
    site: "sol2go",
    image: "/covers/breakpoint-2026-london.jpg",
    imageAlt: "A tall paper hall with a barrel-vaulted glass roof cut as flat violet and lilac sheets, a wide crowd band of pale mint below it",
    imageKind: "generated",
    imageWidth: 1536,
    imageHeight: 864,
    title: "Solana Breakpoint 2026",
    summary:
      "Solana's flagship conference lands at Olympia London on 15–17 November, its theme the Token Supercycle. Developer tickets are $250, general admission $550, students $100.",
    start: "2026-11-15",
    end: "2026-11-17",
    startTime: "16:00",
    utcOffset: "+00:00",
    venue: "Olympia Convention Centre",
    city: "London",
    country: "United Kingdom",
    organizer: "Solana Foundation",
    category: "Conference",
    featured: 1,
    source: {
      name: "Solana Foundation",
      url: "https://solana.com/breakpoint",
      verifiedOn: "2026-09-06",
    },
    ticket: { url: "https://luma.com/breakpoint2026", label: "Tickets" },
    tickets: { priceFrom: 100, priceTo: 800, currency: "USD" },
    body: [
      "Breakpoint has been in Lisbon, Amsterdam, Singapore and Abu Dhabi. In 2026 it is in west London, in a Victorian exhibition hall with a barrel-vaulted glass roof, and the framing has moved with it: this is the year the conference stops addressing the room as developers first.",
      "## The dates and the room",
      "<strong>15 to 17 November 2026</strong> at the <strong>Olympia Convention Centre</strong> in London. The Foundation puts attendance at <strong>8,000+</strong>.",
      "## What the theme actually says",
      "The Foundation's own words: Breakpoint 2026 “centers on the Token Supercycle: a new era in which stablecoins, tokenized assets, payments, and AI-driven economic activity increasingly move onchain.” The audience it names is “financial institutions, technology companies, investors, and policymakers” — which is a different guest list from the one Breakpoint had when it was a builders' reunion.",
      "## What a ticket costs",
      "<strong>Developers $250</strong>. <strong>Students $100</strong>. <strong>General admission $550</strong>, rising to <strong>$800</strong> late. The developer and student tiers are the interesting part of that table: a conference that prices its builders at less than half of general admission is telling you who it still wants in the room.",
      "## The week around it",
      "Breakpoint is the middle of a fortnight, not a standalone. The <strong>Solana Hacker House</strong> runs 1–12 November, <strong>Scale or Die</strong> takes the day before on 14 November, and side events fill the evenings of the 16th. If you are flying in, the calendar to plan against is the fortnight, not the three days.",
    ],
    expertise:
      "Two things are worth knowing before you buy. First, the price ladder is real: the late-bird tier at $800 is a $250 penalty for deciding in October, and the developer tier at $250 has historically sold out well before the general one. Second, a London Breakpoint is the cheapest one this conference has been to reach for anyone in Europe since Lisbon in 2023 — which is also why the room will be fuller than the ticket count suggests, because the side events do not require a badge. If the reason you are going is the hallway rather than the stage, the Hacker House fortnight and the free evening events may be the better half of the trip.",
  },

  {
    slug: "crypto-worlds-fair-2026",
    site: "sol2go",
    image: "/covers/crypto-worlds-fair-2026.jpg",
    imageAlt: "A ring of flat pavilion shapes in violet, lilac and mint paper arranged around a small cream disc",
    imageKind: "generated",
    imageWidth: 1536,
    imageHeight: 864,
    title: "Crypto World's Fair",
    cardTitle: "Crypto World's Fair hackathon",
    summary:
      "Colosseum's online hackathon runs four weeks from 14 September to 12 October, across eight ecosystems at once, Solana among them. Winners can take $250,000 from its accelerator.",
    start: "2026-09-14",
    end: "2026-10-12",
    city: "Online",
    online: true,
    organizer: "Colosseum",
    category: "Hackathon",
    featured: 2,
    audience: ["Founders", "Developers", "Designers", "First-time teams"],
    source: {
      name: "Colosseum",
      url: "https://www.colosseum.com/worldsfair",
      verifiedOn: "2026-09-06",
    },
    ticket: { url: "https://www.colosseum.com/worldsfair", label: "Register" },
    body: [
      "Colosseum runs the hackathons that Solana used to run itself, and it has spent three years being a Solana competition. This one is not. The Crypto World's Fair puts eight ecosystems on the same page and asks builders to pick one.",
      "## The dates",
      "<strong>14 September to 12 October 2026</strong> — four weeks, entirely online. Colosseum describes it as “a global, online competition where founders sprint over 4 weeks to build impactful products”, and as “an online hackathon bringing together builders and founders across blockchain ecosystems to launch breakout startups.”",
      "## Who is on the page",
      "The ecosystem logos shown are <strong>Solana</strong>, <strong>Ethereum</strong>, <strong>Hyperliquid</strong>, <strong>Base</strong>, <strong>Tempo</strong>, <strong>Arbitrum</strong>, <strong>Zcash</strong> and <strong>Robinhood Chain</strong>.",
      "## What is actually on offer",
      "Non-dilutive prizes and, for the teams that get through, a place in Colosseum's full-time accelerator with <strong>$250,000 in capital from its venture fund</strong>. The prize table itself had not been published as of 6 September.",
      "## The signal to read",
      "The registration counter stood at <strong>778 builders</strong> when we checked. That is early — the last Colosseum competition finished with a registration figure an order of magnitude higher, and most teams sign up in the final week.",
    ],
    expertise:
      "A cross-ecosystem hackathon changes what a good submission looks like. In a single-chain competition the judges know the ecosystem's gaps and you can win by filling one; here the field is eight ecosystems wide, so a project whose whole argument is a chain-specific optimisation has to explain itself to a judge who does not share the premise. The teams that tend to do well in that format are the ones whose product makes sense to somebody who does not care which chain it is on, and which then have a specific, defensible reason for the chain they chose. The four-week length also matters: it is a business sprint as much as an engineering one, and Colosseum has been explicit for two years that it funds founders rather than repositories.",
  },

  {
    slug: "solana-hacker-house-london-2026",
    site: "sol2go",
    image: "/covers/solana-hacker-house-london-2026.jpg",
    imageAlt: "Rows of flat desk shapes in lilac and mint paper receding under a long violet ceiling band",
    imageKind: "generated",
    imageWidth: 1536,
    imageHeight: 864,
    title: "Solana Hacker House — London",
    cardTitle: "Solana Hacker House London",
    summary:
      "Thirteen days of free workspace and Solana workshops in London, 1–12 November, running straight into Breakpoint. Approval required, and capacity is limited.",
    start: "2026-11-01",
    end: "2026-11-12",
    startTime: "10:00",
    endTime: "20:00",
    utcOffset: "+00:00",
    city: "London",
    country: "United Kingdom",
    organizer: "Solana Foundation",
    category: "Hacker House",
    featured: 3,
    audience: ["Developers", "Founders", "Designers"],
    source: {
      name: "Solana Foundation",
      url: "https://luma.com/london-hh-26",
      verifiedOn: "2026-09-06",
    },
    ticket: { url: "https://luma.com/london-hh-26", label: "Request to join" },
    body: [
      "The Hacker House is the part of the Breakpoint fortnight that costs nothing and takes the most out of you. Thirteen days of desks, and the expectation that you leave with something built.",
      "## The dates and the day",
      "<strong>1 to 12 November 2026</strong> in London, open <strong>10:00 to 20:00</strong> daily. Registration is handled on the day, <strong>10:00 to 17:00</strong>.",
      "## What is in the building",
      "Workspace with wifi and power, food, lounges and dedicated build zones. The programme is described as “Workshops and deep dives across DeFi, security, infrastructure, and applications”, with Ecosystem Experts and Solana Foundation teams on hand.",
      "## Getting in",
      "<strong>Approval is required</strong> and capacity is limited: you request to join through the event page, and the organisers ask that you keep your RSVP current rather than holding a place you will not use. Anyone wanting to lead a session applies through a typeform; sponsorship goes to events@solana.org.",
      "## Where the address is",
      "Not published. The venue is released to approved guests through the event page rather than announced, which is normal for a Hacker House and worth knowing before you book a hotel.",
    ],
    expertise:
      "Thirteen days is unusually long — most Hacker Houses run five. The length is deliberate: this one exists to fill the run-up to Breakpoint, so the first week is the quiet, useful one and the second is when the conference crowd arrives and the desks stop being available. If you are coming to build rather than to network, the first week is the whole value of the trip, and it is also the week the Ecosystem Experts have time for a real conversation rather than a queue.",
  },

  {
    slug: "scale-or-die-2026",
    site: "sol2go",
    image: "/covers/scale-or-die-2026.jpg",
    imageAlt: "A steep ascending stack of narrow paper bars in violet and mint against a pale ground",
    imageKind: "generated",
    imageWidth: 1536,
    imageHeight: 864,
    title: "Scale or Die",
    summary:
      "A one-day Solana engineering conference in London on 14 November, 09:30 to 18:30, the day before Breakpoint opens.",
    start: "2026-11-14",
    startTime: "09:30",
    endTime: "18:30",
    utcOffset: "+00:00",
    city: "London",
    country: "United Kingdom",
    organizer: "Solana Foundation",
    category: "Conference",
    source: {
      name: "Solana Foundation",
      url: "https://luma.com/scale-or-die-26",
      verifiedOn: "2026-09-06",
    },
    ticket: { url: "https://luma.com/scale-or-die-26", label: "Register" },
    body: [
      "Scale or Die is the technical day that Solana Breakpoint's main stage no longer has room for. One day, one track, London, and it happens the day before the conference opens.",
      "## The details",
      "<strong>14 November 2026</strong>, <strong>09:30 to 18:30</strong>, in London. The address is released to registered guests rather than published.",
      "## Why the day before",
      "Because the people it is for are already flying in. Putting the engineering day on the 14th means it costs a Saturday rather than a Breakpoint session, and it is the reason a developer ticket for the fortnight is worth more than the three conference days on its own.",
      "The full speaker list had not been published as of 6 September.",
    ],
    expertise:
      "The pattern to watch is that Breakpoint's own programme has moved toward institutions and policy, and Scale or Die is where the material that used to be on the main stage went. If the reason you were considering Breakpoint is the protocol engineering, this single day may be the better ticket — and it is a Saturday, so it costs nothing in working time.",
  },

  {
    slug: "solana-summit-canada-2026",
    site: "sol2go",
    image: "/covers/solana-summit-canada-2026.jpg",
    imageAlt: "A flat gabled market-hall silhouette in violet paper with a row of mint arches beneath it",
    imageKind: "generated",
    imageWidth: 1536,
    imageHeight: 864,
    title: "Solana Summit Canada",
    summary:
      "Two days in Toronto on 23–24 September at St. Lawrence Market North, the Canadian stop on the Solana Summit circuit.",
    start: "2026-09-23",
    end: "2026-09-24",
    startTime: "09:30",
    utcOffset: "-04:00",
    venue: "St. Lawrence Market North",
    city: "Toronto",
    country: "Canada",
    organizer: "Superteam Canada",
    category: "Summit",
    source: {
      name: "Solana Foundation events calendar",
      url: "https://lu.ma/Solana-Summit-Canada",
      verifiedOn: "2026-09-06",
    },
    ticket: { url: "https://lu.ma/Solana-Summit-Canada", label: "Register" },
    body: [
      "The Solana Summit series is the Foundation's regional format: one or two days, a local host community, and a room sized for the country rather than the continent. Canada's runs in Toronto at the end of September.",
      "## The details",
      "<strong>23 and 24 September 2026</strong> at <strong>St. Lawrence Market North</strong>, Toronto. The building is the newer half of the St. Lawrence Market complex, which is a market hall rather than a conference centre — expect an open floor rather than breakout rooms.",
      "The programme had not been published in full as of 6 September.",
    ],
  },

  {
    slug: "ethglobal-tokyo-2026",
    site: "sol2go",
    image: "/covers/ethglobal-tokyo-2026.jpg",
    imageAlt: "A tall paper gate form in violet over a dense grid of small mint and lilac squares",
    imageKind: "generated",
    imageWidth: 1536,
    imageHeight: 864,
    title: "ETHGlobal Tokyo 2026",
    summary:
      "A three-day in-person hackathon in Tokyo, 25–27 September, with the Pragma Tokyo conference alongside it on the 26th.",
    start: "2026-09-25",
    end: "2026-09-27",
    utcOffset: "+09:00",
    city: "Tokyo",
    country: "Japan",
    organizer: "ETHGlobal",
    category: "Hackathon",
    source: {
      name: "ETHGlobal",
      url: "https://ethglobal.com/events",
      verifiedOn: "2026-09-06",
    },
    ticket: { url: "https://ethglobal.com/events", label: "Apply to attend" },
    body: [
      "Here for the same reason the rest of the wider calendar is: the people who build across chains keep an Ethereum hackathon and a Solana one in the same diary.",
      "## The details",
      "<strong>25 to 27 September 2026</strong>, Tokyo, listed by ETHGlobal as an in-person hackathon. Attendance is by application rather than by ticket.",
      "## The day beside it",
      "<strong>Pragma Tokyo 2026</strong> runs on <strong>26 September</strong> in the same city — ETHGlobal's conference format, which travels with the hackathons rather than separately from them.",
      "Two other dates from the same calendar are worth noting for the autumn: <strong>ETHOnline 2026</strong>, an async online hackathon running <strong>4 to 16 September</strong>, and <strong>ETHGlobal Mumbai</strong> on <strong>6 to 8 November</strong>, with <strong>Pragma Mumbai</strong> the day before it.",
    ],
  },

  {
    slug: "solana-summit-korea-2026",
    site: "sol2go",
    image: "/covers/solana-summit-korea-2026.jpg",
    imageAlt: "A stepped skyline of flat violet towers with a wide mint river band across the lower frame",
    imageKind: "generated",
    imageWidth: 1536,
    imageHeight: 864,
    title: "Solana Summit Korea",
    summary:
      "A single Solana day in Seoul on 30 September, 10:00 to 17:00, on Yeoui-daero in the Yeouido financial district.",
    start: "2026-09-30",
    startTime: "10:00",
    endTime: "17:00",
    utcOffset: "+09:00",
    city: "Seoul",
    country: "South Korea",
    organizer: "Solana Foundation",
    category: "Summit",
    source: {
      name: "Solana Foundation events calendar",
      url: "https://lu.ma/solana-summit-korea-2026",
      verifiedOn: "2026-09-06",
    },
    ticket: { url: "https://lu.ma/solana-summit-korea-2026", label: "Register" },
    body: [
      "## The details",
      "<strong>30 September 2026</strong>, <strong>10:00 to 17:00</strong>, Seoul. The listing places it on <strong>Yeoui-daero</strong> — Yeouido, which is the financial district rather than the startup one, and that is a choice worth reading.",
      "The exact address is released to registered guests. The programme had not been published in full as of 6 September.",
    ],
  },

  {
    slug: "solana-summit-singapore-2026",
    site: "sol2go",
    image: "/covers/solana-summit-singapore-2026.jpg",
    imageAlt: "Three tall paper columns joined by a long flat deck in violet, a mint bay band below",
    imageKind: "generated",
    imageWidth: 1536,
    imageHeight: 864,
    title: "Solana Summit Singapore",
    summary:
      "6 October at the Ritz-Carlton Millenia, 09:00 to 18:00 — and the Solana Capital Forum runs in the same city on the same day.",
    start: "2026-10-06",
    startTime: "09:00",
    endTime: "18:00",
    utcOffset: "+08:00",
    venue: "The Ritz-Carlton, Millenia Singapore",
    city: "Singapore",
    country: "Singapore",
    organizer: "Solana Foundation",
    category: "Summit",
    source: {
      name: "Solana Foundation events calendar",
      url: "https://lu.ma/solana-summit-singapore-2026",
      verifiedOn: "2026-09-06",
    },
    ticket: { url: "https://lu.ma/solana-summit-singapore-2026", label: "Register" },
    body: [
      "## The details",
      "<strong>6 October 2026</strong>, <strong>09:00 to 18:00</strong>, at <strong>The Ritz-Carlton, Millenia Singapore</strong>.",
      "## The clash worth knowing about",
      "The <strong>Solana Capital Forum Singapore</strong> runs the same day, <strong>12:00 to 20:00</strong>, in the Orchard area. Two Solana events, one city, one date, overlapping by six hours — they are aimed at different rooms, but if you were planning to do both, the afternoon is the part you have to choose between.",
    ],
  },

  {
    slug: "solana-summit-india-2026",
    site: "sol2go",
    image: "/covers/solana-summit-india-2026.jpg",
    imageAlt: "A row of flat arched openings in violet paper with mint sea shapes behind them",
    imageKind: "generated",
    imageWidth: 1536,
    imageHeight: 864,
    title: "Solana Summit India",
    summary:
      "Solana in Mumbai on 2 November, 10:00 to 19:00, in Navpada — four days before ETHGlobal fills the same city.",
    start: "2026-11-02",
    startTime: "10:00",
    endTime: "19:00",
    utcOffset: "+05:30",
    city: "Mumbai",
    country: "India",
    organizer: "Solana Foundation",
    category: "Summit",
    source: {
      name: "Solana Foundation events calendar",
      url: "https://lu.ma/solana-summit-india",
      verifiedOn: "2026-09-06",
    },
    ticket: { url: "https://lu.ma/solana-summit-india", label: "Register" },
    body: [
      "## The details",
      "<strong>2 November 2026</strong>, <strong>10:00 to 19:00</strong>, Mumbai, in <strong>Navpada</strong>. The exact address is released to registered guests.",
      "## The week it sits in",
      "Mumbai has a crowded first week of November: <strong>Pragma Mumbai</strong> on the <strong>5th</strong> and <strong>ETHGlobal Mumbai</strong> from the <strong>6th to the 8th</strong>. If you are travelling to India for one of them, the Summit is three days of overlap away from the other.",
    ],
  },

  {
    slug: "solana-startup-connect-ghana-2026",
    site: "sol2go",
    image: "/covers/solana-startup-connect-ghana-2026.jpg",
    imageAlt: "Interlocking flat chevrons in violet, mint and cream paper forming a broad woven band",
    imageKind: "generated",
    imageWidth: 1536,
    imageHeight: 864,
    title: "solanaStartupConnect Ghana",
    summary:
      "Two days at the Accra Digital Centre on 15–16 October, the Solana calendar's West African stop this autumn.",
    start: "2026-10-15",
    end: "2026-10-16",
    utcOffset: "+00:00",
    venue: "Accra Digital Centre",
    city: "Accra",
    country: "Ghana",
    category: "Summit",
    source: {
      name: "Solana Foundation events calendar",
      url: "https://lu.ma/nx9ps6ud",
      verifiedOn: "2026-09-06",
    },
    ticket: { url: "https://lu.ma/nx9ps6ud", label: "Register" },
    body: [
      "## The details",
      "<strong>15 and 16 October 2026</strong> at the <strong>Accra Digital Centre</strong>, Ghana. The listing gives a start time in a timezone that does not match the venue, so we are printing the dates and leaving the clock to the organiser's page rather than publishing an hour we cannot stand behind.",
      "The programme had not been published in full as of 6 September.",
    ],
  },

  {
    slug: "co-working-fridays-london-september-2026",
    site: "sol2go",
    image: "/covers/co-working-fridays-london-september-2026.jpg",
    imageAlt:
      "A square courtyard in violet paper enclosed by a run of pale column slabs, a grid of short cream jets rising from the paving inside it",
    imageKind: "generated",
    imageWidth: 1536,
    imageHeight: 864,
    title: "Co-Working Fridays: London Chapter",
    summary:
      "A free Friday desk at Somerset House, 11 September, 10:00 to 20:00, for anyone building on Solana. The London chapter runs it most weeks.",
    start: "2026-09-11",
    startTime: "10:00",
    endTime: "20:00",
    utcOffset: "+01:00",
    venue: "Somerset House",
    city: "London",
    country: "United Kingdom",
    organizer: "Superteam UK",
    category: "Co-working",
    tickets: { priceFrom: 0 },
    source: {
      name: "Superteam UK, via the Solana Foundation events calendar",
      url: "https://lu.ma/london-sep-11",
      verifiedOn: "2026-09-06",
    },
    body: [
      "Somerset House is a strange address for a co-working day, and that is most of the appeal. Superteam UK runs one every Friday for “builders, leaders and creatives at the frontier of tech in London”, and 11 September is simply the next one.",
      "## What it costs, and what that does not mean",
      "Attendance is <strong>free</strong>. It is not open: entry is <strong>by approval only</strong>, so registering is not the same as being on the guestlist, and the organiser says so in as many words. You are asked to show the confirmation QR code or email on arrival, and you are given a wristband to wear for the day.",
      "The listing adds two warnings worth reading before you plan a train around it: places are <strong>limited even after confirmation</strong>, and arriving early is the organiser's own advice.",
      "## The hours do not agree with themselves",
      "The calendar entry runs <strong>10:00 to 20:00</strong>. The description on the same page says <strong>10:00 to 20:30</strong>. We print the first, because it is the field the calendar actually schedules from, and we mention the second because a half-hour is exactly the kind of difference that strands somebody at a door.",
      "## Who runs it",
      "Superteam describes itself as a global co-operative of regional non-profits across <strong>20+ countries</strong>, supporting founders and talent. The UK chapter takes questions through the Solana UK Telegram group, and membership applications through superteamuk.org.",
      "## What the page does not publish",
      "No agenda, no speakers, no room number. This is a desk and the people at the other desks, which is the entire proposition — the value is who else got approved that week, and nobody publishes that in advance.",
    ],
    expertise:
      "Register early rather than on the Thursday. Approval-only plus “limited spaces even after confirmation” means the guestlist is a queue, and a weekly event with a fixed room fills from the regulars outward.",
  },

  {
    slug: "the-future-of-finance-thessaloniki-2026",
    site: "sol2go",
    image: "/covers/the-future-of-finance-thessaloniki-2026.jpg",
    imageAlt:
      "A long low boat hull cut from pale paper on a band of violet water, with a tall cylindrical tower standing beside it on the quay",
    imageKind: "generated",
    imageWidth: 1536,
    imageHeight: 864,
    title: "The Future of Finance — Thessaloniki",
    cardTitle: "The Future of Finance, Thessaloniki",
    summary:
      "Anodos Labs and Superteam Balkan, the Solana chapter for the region, take over a cruise boat moored by the White Tower on 13 September, 19:30 to 22:00 — the closing party of Thessaloniki International Fair week.",
    start: "2026-09-13",
    startTime: "19:30",
    endTime: "22:00",
    utcOffset: "+03:00",
    venue: "Klió Cruise boat, by the White Tower",
    city: "Thessaloniki",
    country: "Greece",
    organizer: "Anodos Labs and Superteam Balkan",
    category: "Meetup",
    tickets: { priceFrom: 0 },
    source: {
      name: "Anodos Labs and Superteam Balkan, via the Solana Foundation events calendar",
      url: "https://lu.ma/q242rqc4",
      verifiedOn: "2026-09-06",
    },
    body: [
      "The venue is the point: a cruise boat, the <strong>Klió</strong>, docked on the waterfront beside the White Tower. Anodos Labs and Superteam Balkan have taken it for an evening, and the meetup happens on the water.",
      "## Why that evening",
      "13 September is the <strong>last day of the Thessaloniki International Fair</strong>, and this is a side event to it — the organisers pitch it as the after-party that closes TIF week rather than as a standalone meetup. If you are in the city for the fair, the calendar has arranged itself for you.",
      "## Who it is for",
      "The listing casts wide on purpose: founders, builders, creators, students, marketers, developers, engineers, “and anyone curious about the future of finance and new emerging technologies such as blockchain and AI”. Read that as an evening for meeting people rather than for learning something specific.",
      "## What is actually promised",
      "<strong>One free cocktail or drink</strong> for everyone on board, live DJ sets, and conversations about finance, startups and the Solana ecosystem. Superteam Balkan uses the evening to explain what it offers a builder in the region — jobs, mentorship, education, grants, ecosystem support.",
      "## The two hosts",
      "<strong>Anodos Labs</strong> is a fintech building what it calls a global financial super app, with a stated mission to make financial services reachable “anywhere, anytime, anyhow”. <strong>Superteam Balkan</strong> is the regional chapter that connects founders and developers to capital, talent and mentorship in the Solana ecosystem.",
      "## What the page does not publish",
      "No speaker list, no schedule for the three hours, and no capacity. The boat is a boat, so the last of those is the one that matters.",
    ],
    expertise:
      "Treat the mooring as the deadline rather than the start time. A boat with a fixed dock and a three-hour window is not a room you can slip into at 21:00, and the listing sets no capacity — which on a vessel means the capacity is set by the vessel.",
  },

  {
    slug: "solana-ecosystem-call-september-2026",
    site: "sol2go",
    image: "/covers/solana-ecosystem-call-september-2026.jpg",
    imageAlt:
      "Many small pale paper squares arranged in a wide ring on a violet ground, one larger cream square alone at the centre of it",
    imageKind: "generated",
    imageWidth: 1536,
    imageHeight: 864,
    title: "The Solana Ecosystem Call — September",
    cardTitle: "Solana Ecosystem Call, September",
    summary:
      "The monthly Solana ecosystem call returns on 24 September, 14:00 to 15:00 UTC — a live show hosted by SOL BROTHERS that would rather be late-night television than a community update.",
    start: "2026-09-24",
    startTime: "14:00",
    endTime: "15:00",
    utcOffset: "+00:00",
    city: "Online",
    online: true,
    organizer: "SOL BROTHERS Studio",
    category: "Online",
    tickets: { priceFrom: 0 },
    source: {
      name: "SOL BROTHERS Studio, via the Solana Foundation events calendar",
      url: "https://lu.ma/0j8gx7i1",
      verifiedOn: "2026-09-06",
    },
    body: [
      "Most ecosystem calls are a slide deck and a queue of speakers. This one is produced as a show, and describes itself that way: it “brings the production quality and energy of late-night television to the fastest-moving ecosystem in crypto”.",
      "## The format",
      "An hour, monthly, live. Each episode is built out of <strong>sketches, interviews, data-driven segments and unfiltered commentary</strong> rather than a run of announcements. The organisers' own line for it is “no fluff, yet cringe-intolerant”, which is a claim you can hold them to.",
      "## Who makes it",
      "<strong>SOL BROTHERS Studio</strong>, a podcast producer that hosts interviews and is credited as the creator of the official Solana Ecosystem Call. The show keeps its own site at ecosystemcall.com.",
      "## The part that is worth knowing",
      "Segments are <strong>open to submission</strong>. The listing invites product announcements, timeline moments, event plans and company giveaways through a submission form — so an hour of television is also a distribution channel for anyone building on Solana, and one that costs nothing to try.",
      "## What the page does not publish",
      "No guest list and no running order for September. The show is “back” with what the listing calls fresh energy, and what that means is decided closer to the day.",
    ],
    expertise:
      "If you have something to announce, the submission form is the reason to open this listing at all — the hour itself will be on the timeline afterwards, and the one thing you cannot get later is a slot in it.",
  },

  {
    slug: "superteam-canada-community-call-october-2026",
    site: "sol2go",
    image: "/covers/superteam-canada-community-call-october-2026.jpg",
    imageAlt:
      "A dense wall of small violet paper squares in even rows, with the three-bar Solana mark hanging at its centre in the red and white of the Canadian flag",
    imageKind: "generated",
    imageWidth: 1536,
    imageHeight: 864,
    title: "Superteam Canada Community Call — October",
    titleSeo: "Superteam Canada Community Call, October",
    cardTitle: "Superteam Canada call, October",
    summary:
      "Thirty minutes on Discord on 1 October, 16:00 to 16:30 UTC, hosted by Simon, from the chapter building the Solana ecosystem in Canada. The first of three, a month apart.",
    start: "2026-10-01",
    startTime: "16:00",
    endTime: "16:30",
    utcOffset: "+00:00",
    city: "Online",
    online: true,
    organizer: "Superteam Canada",
    category: "Online",
    tickets: { priceFrom: 0 },
    source: {
      name: "Superteam Canada, via the Solana Foundation events calendar",
      url: "https://lu.ma/aq7rqqmn",
      verifiedOn: "2026-09-06",
    },
    body: [
      "Half an hour on Discord, hosted by Simon, and pitched at both ends of the room: “whether you're a seasoned pro or just starting out”. The chapter uses it to answer questions and to find people who want to do more than attend.",
      "## The three dates",
      "Superteam Canada has <strong>three of these on the calendar</strong> — 1 October, 5 November and 3 December 2026 — each on the first Thursday of the month.",
      "## Monthly or quarterly?",
      "The listing says the call happens “first Thursday on the every Quarter”. The calendar says three Thursdays a month apart. <strong>The dates are the reliable half</strong>: they are what the invitation actually schedules, and they are what a reminder is set from.",
      "## What half an hour buys",
      "Insights, advice, questions taken live, and a route into the chapter for anyone who wants one. Thirty minutes is not a conference — it is the shortest way to find out whether a regional chapter is worth your time before committing an evening to one of its events.",
      "## What the page does not publish",
      "No agenda per call and no guest names. A recurring listing that reuses one description does not tell you what October differs on, and this one does not pretend to.",
    ],
    expertise:
      "Join the Discord before the day rather than at 16:00. A thirty-minute call on a server you have not been admitted to is a call you will spend ten minutes joining.",
  },

  {
    slug: "solana-capital-forum-singapore-2026",
    site: "sol2go",
    image: "/covers/solana-capital-forum-singapore-2026.jpg",
    imageAlt:
      "A close row of tall narrow tower slabs in violet paper standing on a pale cream band, an even skyline broken by a few shorter blocks",
    imageKind: "generated",
    imageWidth: 1536,
    imageHeight: 864,
    title: "Solana Capital Forum Singapore",
    summary:
      "6 October in Orchard, 12:00 to 20:00 — a private Solana forum capped at 150 allocators, investors, policymakers and infrastructure providers.",
    start: "2026-10-06",
    startTime: "12:00",
    endTime: "20:00",
    utcOffset: "+08:00",
    city: "Singapore",
    country: "Singapore",
    organizer: "Solana Foundation",
    category: "Forum",
    source: {
      name: "Solana Foundation",
      url: "https://lu.ma/sol-cap-sg",
      verifiedOn: "2026-09-06",
    },
    ticket: { url: "https://capitalforum.solana.com/", label: "Official site" },
    body: [
      "The number to read first is <strong>150</strong>. That is the cap the Solana Foundation has put on the room, and it is the design of the day rather than a detail of it — a curated executive gathering that is limited on purpose so the conversations are with people who can act on them.",
      "## Who is in the room",
      "Allocators, investors, operators, policymakers and infrastructure providers, drawn from traditional finance and digital assets both. The Foundation's own framing puts the forum “at the intersection of institutional capital, private capital, and financial innovation”.",
      "## What is discussed",
      "How <strong>tokenized assets, stablecoins and internet-native financial infrastructure</strong> are reshaping global capital markets. That is the whole published brief: no track list, no session titles, no speakers as of 6 September.",
      "## The eight hours",
      "<strong>12:00 to 20:00</strong> in Orchard. Luma gives the district and withholds the street — the address goes to registered guests, which is the usual shape for an invitation-controlled room.",
      "## The clash worth knowing about",
      "The <a href=\"/events/solana-summit-singapore-2026/\" title=\"Solana Summit Singapore\">Solana Summit</a> runs in the same city on the same day. One is the builders' day and this is the institutional one, and they overlap by six hours — so Singapore on 6 October is a choice, not a schedule.",
      "## What the page does not publish",
      "No price, no application criteria, and no indication of how the 150 are selected. Sponsorship goes through events@solana.org; attendance goes through the official site.",
    ],
    expertise:
      "A 150-seat cap in a week that also carries a summit means the guestlist closes on relevance rather than on date. If the forum is the reason you are flying, apply before you book — the summit will still be there if this one says no.",
  },

  {
    slug: "islanddao-v5-2026",
    site: "sol2go",
    image: "/covers/islanddao-v5-2026.jpg",
    imageAlt:
      "A map seen from overhead: a small mint island at the centre of a violet sea, ringed by one wide pale band, tiny cream boat shapes scattered around it",
    imageKind: "generated",
    imageWidth: 1536,
    imageHeight: 864,
    title: "IslandDAO v5",
    summary:
      "IslandDAO's month-long residency for the Solana ecosystem goes to Latin America for the first time: Florianópolis, 19 October to 11 November, with a hackathon, investor days and a demo day inside it.",
    start: "2026-10-19",
    end: "2026-11-11",
    utcOffset: "-03:00",
    city: "Florianópolis",
    country: "Brazil",
    organizer: "IslandDAO",
    category: "Residency",
    source: {
      name: "IslandDAO, via the Solana Foundation events calendar",
      url: "https://lu.ma/6laijuyn",
      verifiedOn: "2026-09-06",
    },
    ticket: { url: "https://islanddao.org/", label: "Apply" },
    body: [
      "Twenty-four days is not an event, it is a move. IslandDAO's fifth residency runs from <strong>19 October to 11 November</strong> and asks developers, founders and investors in the Solana ecosystem to co-work in one place for most of a month.",
      "## The new part",
      "<strong>For the first time the residency goes to LATAM</strong>: Florianópolis — Floripa — in Santa Catarina, Brazil. The four previous editions did not, and the organisers lead with the change rather than burying it.",
      "## What is inside the month",
      "The published programme is a list rather than a schedule: <strong>building, feedback sessions, investor days, a hackathon, a demo day, work opportunities, fitness and wellness</strong>. The shape that implies is an accelerator with no cohort agreement — the demo day at the end is the deadline everything else runs toward.",
      "## How you get in",
      "Registration on Luma is not registration. The listing is explicit about it: <strong>apply at islanddao.org</strong>, and only there. A residency that houses people for three and a half weeks is selecting, not ticketing.",
      "## What the page does not publish",
      "No cost, no accommodation terms, no cohort size, no application deadline. For a month away from home those are the four questions, and all four are behind the application form.",
    ],
    expertise:
      "Ask what is covered before you ask whether you qualify. Three and a half weeks in Brazil has a floor price in flights and rent whatever the residency provides, and the listing settles none of it — a demo day is worth planning around, but not on an assumption about who pays for the bed.",
  },

  {
    slug: "money-layer-breakpoint-week-2026",
    site: "sol2go",
    image: "/covers/money-layer-breakpoint-week-2026.jpg",
    imageAlt:
      "Broad flat horizontal layers of violet paper stacked edge to edge across the frame, one pale pink and one mint band lying among them",
    imageKind: "generated",
    imageWidth: 1536,
    imageHeight: 864,
    title: "Money Layer — Breakpoint Week",
    cardTitle: "Money Layer, Breakpoint week",
    summary:
      "Capvise brings its founder-and-fund format to Solana's Breakpoint week: London, 16 November, 18:30 to 22:00, under the heading “Money. Markets. Machines.”",
    start: "2026-11-16",
    startTime: "18:30",
    endTime: "22:00",
    utcOffset: "+00:00",
    city: "London",
    country: "United Kingdom",
    organizer: "Capvise Global",
    category: "Side event",
    tickets: { priceFrom: 0 },
    source: {
      name: "Capvise Global, via the Solana Foundation events calendar",
      url: "https://lu.ma/xykfcf1a",
      verifiedOn: "2026-09-06",
    },
    body: [
      "Three and a half hours on the Monday evening of <a href=\"/events/breakpoint-2026-london/\" title=\"Solana Breakpoint 2026, London\">Breakpoint</a> week, under a three-word banner — <strong>Money. Markets. Machines.</strong> — that is also the room's segment list.",
      "## What the room is meant to contain",
      "The organiser's description of it is unusually precise about function: “the companies building the financial stack, the companies buying it, and the capital funding it”. In practice that means founders, funds, market makers, exchanges, asset managers, fintechs, protocols and senior operators who are already in town for the conference.",
      "## The track record they cite",
      "Capvise Global says previous editions have run in <strong>Singapore, Dubai, Bali and Buenos Aires</strong> and drew <strong>6,400+ applications</strong> across them. Applications, note, not attendees — the number describes demand for the format rather than the size of any room.",
      "## The commercial half",
      "A good part of the listing is a partnership pitch: presenting, Money, Markets, Machines, Exchange and After Dark are named as partner slots, with series and city partnerships available and a deck on request. Worth knowing what you are reading, and worth knowing the evening is programmed around those segments.",
      "## What the page does not publish",
      "No venue, no speakers, no capacity, no admission terms. The address follows registration, as it does for most of Breakpoint week's evenings.",
    ],
    expertise:
      "Breakpoint week's evenings compete with each other, and this one starts at 18:30 while <a href=\"/events/pr1me-london-dinner-2026/\" title=\"Pr1me London dinner\">the Pr1me dinner</a> starts at 19:00 across town. One is a room you work; the other is a table you sit at for three hours. Pick by which you actually want, not by which confirms first.",
  },

  {
    slug: "pr1me-london-dinner-2026",
    site: "sol2go",
    image: "/covers/pr1me-london-dinner-2026.jpg",
    imageAlt:
      "One long pale table slab running the full width of the frame seen from above, an even row of small cream discs down its length",
    imageKind: "generated",
    imageWidth: 1536,
    imageHeight: 864,
    title: "Pr1me London — dinner for web3 finance",
    cardTitle: "Pr1me London dinner",
    summary:
      "A Solana Breakpoint-week dinner for web3 accounting and finance, London, 16 November, 19:00 to 22:00 — and the guest list is restricted by job title, in writing.",
    start: "2026-11-16",
    startTime: "19:00",
    endTime: "22:00",
    utcOffset: "+00:00",
    city: "London",
    country: "United Kingdom",
    organizer: "Onchain Finance Institute",
    category: "Side event",
    tickets: { priceFrom: 0 },
    source: {
      name: "Onchain Finance Institute, via the Solana Foundation events calendar",
      url: "https://lu.ma/aqntywn2",
      verifiedOn: "2026-09-06",
    },
    body: [
      "Most invite-only listings hint. This one states the rule: the dinner is <strong>for finance professionals — CFOs, COOs, Controllers, Heads of Finance, or equivalent</strong> — and “we're unable to accept applications outside these roles”. Read it before you apply, because it is the clearest admission criterion on this calendar.",
      "## What it is",
      "The London edition of the PR1ME series, run during <a href=\"/events/breakpoint-2026-london/\" title=\"Solana Breakpoint 2026, London\">Breakpoint</a> and described as community-driven rather than commercial: an evening for the people doing web3 accounting and finance, at a table rather than in a room.",
      "## Who is behind it",
      "Four names. The <strong>Onchain Finance Institute</strong>, an education and community platform for finance professionals moving into onchain work, which says it has 150+ alumni and 400+ community members. The <strong>Solana Foundation</strong>. <strong>Lukka</strong>, which builds institutional digital-asset data for pricing, valuation, compliance and reporting. And <strong>Breezing</strong>, a crypto subledger for accountants that connects to Xero and QuickBooks, SOC 2 certified, used by 200+ businesses.",
      "## Entry is by QR code",
      "The listing is blunt about it: only confirmed guests with a QR code get in, and <strong>walk-ins and unapproved registrations will not be possible</strong>. A dinner has covers, and covers are counted in advance.",
      "## What the page does not publish",
      "No venue, no menu, no cost, and no number of seats. The address goes to confirmed guests, which for a dinner during Breakpoint week is the norm rather than a slight.",
    ],
    expertise:
      "This is the one evening in Breakpoint week where the job title on your application does the deciding, so put the real one on it. If you are a founder rather than a finance lead, <a href=\"/events/money-layer-breakpoint-week-2026/\" title=\"Money Layer, Breakpoint week\">Money Layer</a> starts half an hour earlier and is the room that wants you.",
  },

  {
    slug: "superteam-canada-community-call-november-2026",
    site: "sol2go",
    image: "/covers/superteam-canada-community-call-november-2026.jpg",
    imageAlt:
      "A dense wall of small violet paper squares in even rows, with the three-bar Solana mark hanging at its centre in the red and white of the Canadian flag",
    imageKind: "generated",
    imageWidth: 1536,
    imageHeight: 864,
    title: "Superteam Canada Community Call — November",
    titleSeo: "Superteam Canada Community Call, November",
    cardTitle: "Superteam Canada call, November",
    summary:
      "The second of the three Solana calls from Superteam Canada, 5 November, 17:00 to 17:30 UTC on Discord. The clock moves an hour in UTC and the listing does not say why.",
    start: "2026-11-05",
    startTime: "17:00",
    endTime: "17:30",
    utcOffset: "+00:00",
    city: "Online",
    online: true,
    organizer: "Superteam Canada",
    category: "Online",
    tickets: { priceFrom: 0 },
    source: {
      name: "Superteam Canada, via the Solana Foundation events calendar",
      url: "https://lu.ma/8uhc300o",
      verifiedOn: "2026-09-06",
    },
    body: [
      "The same thirty minutes on Discord as October's, hosted by Simon, on the first Thursday of the month.",
      "## The hour that moved",
      "October's call is 16:00 UTC; this one is <strong>17:00 UTC</strong>. Nothing in the listing explains it, but the reason is the clock rather than the organiser: the call is scheduled in Toronto time, and North America puts its clocks back on 1 November. <strong>The local hour is unchanged — the UTC one is not.</strong> If you are joining from Europe, this is the month the reminder in your calendar quietly stops matching the one in your head.",
      "## The description is out of date",
      "The listing still opens by announcing a call “Thursday, Jul 3rd, 12:00 PM to 12:30 PM EDT”. The scheduled fields say 5 November. We follow the fields, because they are what the invitation runs on, and we say so here rather than tidying it away.",
      "## What it is",
      "A chapter call: questions taken live, advice, and a route in for anyone who wants to do more than listen. Superteam Canada is one of the regional chapters of a co-operative that runs in more than twenty countries.",
      "## What the page does not publish",
      "No agenda for November. See <a href=\"/events/superteam-canada-community-call-october-2026/\" title=\"Superteam Canada Community Call, October\">October's call</a> for what the series looks like when it runs.",
    ],
    expertise:
      "Check what your calendar app did with this one. A recurring series whose UTC hour shifts in November catches people who set a reminder in October, and the half-hour is short enough that arriving late is arriving after.",
  },

  {
    slug: "superteam-canada-community-call-december-2026",
    site: "sol2go",
    image: "/covers/superteam-canada-community-call-december-2026.jpg",
    imageAlt:
      "A dense wall of small violet paper squares in even rows, with the three-bar Solana mark hanging at its centre in the red and white of the Canadian flag",
    imageKind: "generated",
    imageWidth: 1536,
    imageHeight: 864,
    title: "Superteam Canada Community Call — December",
    titleSeo: "Superteam Canada Community Call, December",
    cardTitle: "Superteam Canada call, December",
    summary:
      "The last Solana call Superteam Canada has scheduled: 3 December, 17:00 to 17:30 UTC on Discord. Nothing is published beyond it.",
    start: "2026-12-03",
    startTime: "17:00",
    endTime: "17:30",
    utcOffset: "+00:00",
    city: "Online",
    online: true,
    organizer: "Superteam Canada",
    category: "Online",
    tickets: { priceFrom: 0 },
    source: {
      name: "Superteam Canada, via the Solana Foundation events calendar",
      url: "https://lu.ma/sejn139p",
      verifiedOn: "2026-09-06",
    },
    body: [
      "First Thursday of the month, thirty minutes on Discord, hosted by Simon — the third and last of the calls Superteam Canada has scheduled in 2026.",
      "## The end of the published series",
      "October, November, December, and then nothing. <strong>No January date has been announced</strong> as of 6 September. That is worth knowing before you treat the series as a standing fixture: three dates is what the chapter has committed to in public, and the fourth is a question.",
      "## Same clock as November",
      "<strong>17:00 UTC</strong>, which is midday in Toronto — the hour the series has run at locally all along. See <a href=\"/events/superteam-canada-community-call-november-2026/\" title=\"Superteam Canada Community Call, November\">November's call</a> for why the UTC time changed and the local one did not.",
      "## The description is out of date",
      "As on the other two listings, the text still announces a call on “Thursday, Jul 3rd”. The scheduled fields carry 3 December, and those are what the invitation runs on.",
      "## What the page does not publish",
      "No agenda, no guests, no indication of whether a December call before the holidays runs shorter or longer than the half-hour it is booked for.",
    ],
    expertise:
      "This is the one to attend if you want to know whether the series continues. A chapter with no January date published in September will either announce one on this call or not have one — and the question costs nothing to ask in a room built for questions.",
  },

  {
    slug: "solana-frontier-hackathon-2026",
    site: "sol2go",
    image: "/covers/solana-frontier-hackathon-2026.jpg",
    imageAlt: "A wide horizon band of layered violet and mint paper with one small cream flag shape near the edge",
    imageKind: "generated",
    imageWidth: 1536,
    imageHeight: 864,
    title: "Solana Frontier Hackathon",
    summary:
      "Colosseum's spring Solana competition ran 6 April to 11 May and paid out $250,000 in prizes, with another $250,000 per accelerator place — and no tracks and no bounties at all.",
    start: "2026-04-06",
    end: "2026-05-11",
    city: "Online",
    online: true,
    organizer: "Colosseum",
    category: "Hackathon",
    source: {
      name: "Colosseum",
      url: "https://blog.colosseum.com/announcing-the-solana-frontier-hackathon/",
      verifiedOn: "2026-09-06",
    },
    body: [
      "The Frontier hackathon is the most useful thing to read before entering the current one, because it is where Colosseum wrote down what it actually rewards.",
      "## The dates",
      "<strong>6 April to 11 May 2026</strong>, online. Announced on 6 April.",
      "## What it paid",
      "<strong>$30,000</strong> to the grand champion. <strong>$10,000</strong> each to the next twenty startups. <strong>$10,000</strong> for the best university team and <strong>$10,000</strong> for the best public goods project. Up to <strong>ten</strong> winners took a place in the accelerator, each carrying <strong>$250,000 in pre-seed funding</strong>, mentorship, AI credits, in-person support at Colosseum's San Francisco office and a private demo day. Colosseum put the total venture deployment at <strong>over $2.5 million</strong>.",
      "## The part people miss",
      "There were <strong>no tracks and no bounties</strong>. Colosseum framed the competition as “intensive engineering <em>and</em> business sprints where elite developers vie for prizes and pre-seed funding” — which is a polite way of saying that a technically excellent project with no business behind it does not place.",
    ],
    outcome: [
      "The format carried straight into the autumn: the Crypto World's Fair, which opened on 14 September, uses the same accelerator terms — $250,000 per team from the venture fund — and the same absence of tracks.",
    ],
  },

  {
    slug: "solana-armenia-meetup-yerevan-july-2026",
    site: "sol2go",
    image: "/covers/solana-armenia-meetup-yerevan-july-2026.jpg",
    imageAlt: "A low wide room in violet paper with the three-bar Solana mark hanging on the back wall in the red, blue and apricot of the Armenian flag, a small raised platform at one end and flat cream and mint rectangles scattered across the floor",
    imageKind: "generated",
    imageWidth: 1536,
    imageHeight: 864,
    title: "Solana Armenia Meetup, Yerevan",
    cardTitle: "Solana Armenia Meetup",
    summary:
      "108 people came to the ISTC Foundation on 25 July for two short talks, a CTF prize ceremony and four hours of Armenia's Solana builders in one room.",
    start: "2026-07-25",
    startTime: "16:00",
    endTime: "20:00",
    utcOffset: "+04:00",
    venue: "ISTC Foundation",
    city: "Yerevan",
    country: "Armenia",
    geo: { name: "ISTC Foundation", lat: 40.1831239, lng: 44.5262954 },
    organizer: "Solana Armenia",
    category: "Meetup",
    tickets: { priceFrom: 0 },
    source: {
      name: "Solana Armenia",
      url: "https://luma.com/404vst65",
      verifiedOn: "2026-09-06",
    },
    body: [
      "Four hours on a Saturday afternoon and evening in Kentron, and the organisers were explicit about how they divide them: “We like keeping the talks concise so there's enough time for the conversations that happen afterwards.” Two talks, a prize ceremony, and then the part the evening is actually for.",
      "## The room",
      "<strong>ISTC Foundation</strong>, 1 and 7 Alek Manukyan Street, in the Kentron district of Yerevan. <strong>108 people registered.</strong> The listing calls it &ldquo;another evening with the local Solana community&rdquo;, so the room is a habit rather than a one-off.",
      "## The programme",
      "<strong>Levon Bilbulyan — “Understanding Solana PDAs Through a CTF Challenge.”</strong> Program-derived addresses taught from the attacker's side, which is the way they stop being an abstraction: a PDA you have had to break is a PDA you understand.",
      "Then the <strong>CTF challenge recap and prize ceremony</strong> — the meetup ran a capture-the-flag and handed out the prizes in the room.",
      "<strong>Ernest Mkrtchyan — “The Status Code That Waited 28 Years.”</strong> The title names no code and the listing does not expand on it, which is either very good billing or an accident. Whoever was there knows.",
      "Then networking, for as long as the rest of it left.",
      "## Who it was for",
      "The invitation lists the room it wanted: people writing Rust, people building a startup, people working in fintech, computer science students, and anyone who had merely started to look at Solana. That is a wider door than most technical meetups open, and it is deliberate — the organisers describe the evening as relaxed, and the value proposition as seeing what other people in Armenia are working on.",
      "## Written twice, on purpose",
      "The listing runs in full in <strong>English and Armenian</strong>, not as a summary and a translation. A community that writes its invitation twice is telling you who it expects to come.",
      "## Who runs it",
      "<strong>Solana Armenia</strong>, hosted by <strong>Ernest Mkrtchyan</strong> and <strong>Hrach Avagyan</strong>. It is a local calendar rather than a Foundation programme — this evening does not appear on the Solana Foundation's own events calendar at all, which is worth knowing if that calendar is where you look for what is happening near you.",
    ],
    outcome: [
      "The format is the takeaway, and it is portable: two short talks, a competition with its prizes handed over in person, and the rest of the evening left empty on purpose. A meetup that schedules its own conversations is rarer than it should be.",
      "Nothing is published yet for the next one. The calendar it was announced on is the place it will appear.",
    ],
  },

  {
    slug: "ethglobal-lisbon-2026",
    site: "sol2go",
    image: "/covers/ethglobal-lisbon-2026.jpg",
    imageAlt:
      "A broad rise paved with dense rows of small violet diamonds, one small mint block standing alone at its crest",
    imageKind: "generated",
    imageWidth: 1536,
    imageHeight: 864,
    title: "ETHGlobal Lisbon 2026",
    summary:
      "800+ hackers, $100,000 in prizes and one rule change: for the first time at an ETHGlobal event, you did not have to start from an empty repository.",
    start: "2026-07-24",
    end: "2026-07-26",
    utcOffset: "+01:00",
    city: "Lisbon",
    country: "Portugal",
    organizer: "ETHGlobal",
    category: "Hackathon",
    source: {
      name: "ETHGlobal",
      url: "https://ethglobal.com/events/lisbon2026",
      verifiedOn: "2026-09-06",
    },
    body: [
      "Lisbon is on this calendar for one reason and it is not the prize pool: it is where ETHGlobal changed the oldest rule in hackathons. A rule change at one hackathon is read by everyone who runs one, Solana's among them.",
      "## The rule that changed",
      "Until Lisbon, the terms were: empty repository only, existing code not allowed. In July they became <strong>“any repo you bring”</strong>, with existing code <strong>welcomed</strong>. Team size stayed 1–5 and sponsor SDKs stayed capped at three — ETHGlobal's own summary is “two items, the rest unchanged”, which undersells it.",
      "## The three ways to enter",
      "<strong>From Scratch</strong> — show up, type <code>git init</code>, ship by Sunday, the hackathon everyone already knew. <strong>Extend Open Source</strong> — bring a repository you already maintain and ship the feature you have been putting off all year. <strong>Ship a Feature</strong> — build one new feature on top of something existing and release it as open source.",
      "## The weekend by the numbers",
      "<strong>24–26 July 2026</strong>, Lisbon. <strong>800+ attendees</strong>, <strong>10+ protocols</strong>, <strong>29+ workshops</strong>. <strong>$100,000 in prizes</strong>, the largest pots being The Graph, World, Hedera and 0G at <strong>$15,000</strong> each, then Uniswap Foundation at $10,000, 1inch at $7,000, Sui at $6,000 and ENS at $5,000.",
      "## Themes",
      "Zero-knowledge proofs, AI × crypto, DeFi, consumer crypto, layer 2s, interoperability, public goods, privacy, security, TEEs, data availability, identity and dev tools.",
      "## It started two weeks early",
      "The schedule opened on <strong>8 July</strong> with virtual team-formation and brainstorming sessions, a beginners' workshop on 15 July on what to expect, and more sessions on the 17th and 22nd. The application deadline was <strong>17 July</strong> — a week before the doors.",
    ],
    outcome: [
      "The rule change is the part that travels. A hackathon that accepts existing repositories is judging the feature rather than the weekend, and it turns the format from a sprint into a release — which is a different competition from the one that has run for a decade.",
      "ETHGlobal wrapped the weekend in two more dates in the same city: Onchain Builders Day on 23 July and the Pragma Lisbon conference on 25 July. The next in-person one on its calendar is Tokyo, 25 to 27 September.",
    ],
  },
  {
    slug: "coworking-fridays-belgrade-september-2026",
    site: "sol2go",
    image: "/covers/coworking-fridays-belgrade-september-2026.jpg",
    imageAlt:
      "A tall violet room with a pale mint aisle running away down the middle, a long desk along each side wall carrying open laptops, and bright windows above them",
    imageKind: "generated",
    imageWidth: 1536,
    imageHeight: 864,
    title: "Coworking Fridays Belgrade",
    summary:
      "A free Friday desk at the AI Hub on Savska, run by Superteam Balkan for anyone building on Solana. 11 September is the next one; there is one most weeks.",
    start: "2026-09-11",
    startTime: "10:00",
    endTime: "17:00",
    utcOffset: "+02:00",
    venue: "AI Hub Belgrade by Startit, Savska 5",
    city: "Belgrade",
    country: "Serbia",
    organizer: "Superteam Balkan",
    category: "Co-working",
    tickets: { priceFrom: 0 },
    source: {
      name: "Superteam Balkan",
      url: "https://luma.com/coworking-fridays-belgrade",
      verifiedOn: "2026-09-06",
    },
    body: [
      "Every Friday, a room on Savska with desks in it. Superteam Balkan opens the <strong>AI Hub Belgrade by Startit</strong> to “founders, builders, and frens from the Solana and Balkan Web3 community”, and 11 September is simply the next Friday on the list.",
      "## What is promised, in full",
      "The listing does not oversell it, which is a point in its favour: <strong>friendly vibes</strong>, <strong>in-person help from the Superteam Balkan crew</strong>, and <strong>networking, free coffee and a cosy space</strong>. That is the whole offer. There is no agenda and no speaker, because a co-working day is neither.",
      "## Who it is for",
      "Founders, developers, designers and students — the organisers write “basically everyone”, and add anyone curious about Solana and about building startups. Unlike the London chapter's Friday, this one is not approval-only: attendance is free and registering is the whole of it.",
      "## Who runs it",
      "<strong>Superteam Balkan</strong> is the regional Solana chapter and a non-profit. It says plainly on its own page that it sells nothing and gives no investment advice; what it does is incubate and fund Balkan builders, and help them ship startups with Solana underneath. The same crew put on Solana Summit Serbia in August and runs Buildstation in October, so a Friday here is the cheapest way to meet the people behind both.",
      "## What the page does not publish",
      "No room number, no headcount, no list of who is coming. On a co-working day the value is exactly who else turned up, and nobody can publish that in advance.",
    ],
    expertise:
      "This is the low-stakes door into the Belgrade scene. The Summit is over and Buildstation wants a project; a Friday desk wants nothing, and the same people are behind all three.",
  },
  {
    slug: "buildstation-belgrade-2026",
    site: "sol2go",
    image: "/covers/buildstation-belgrade-2026.jpg",
    imageAlt:
      "A grid of pale mint scaffolding bars covering the whole frame on a violet ground, with one small cream platform resting on a bar at the centre",
    imageKind: "generated",
    imageWidth: 1536,
    imageHeight: 864,
    title: "Buildstation Belgrade",
    summary:
      "Twelve days of free co-working in Belgrade, 1 to 12 October, where Superteam Balkan gathers Solana builders to work on projects for the next hackathon.",
    start: "2026-10-01",
    end: "2026-10-12",
    startTime: "09:00",
    endTime: "21:00",
    utcOffset: "+02:00",
    city: "Belgrade",
    country: "Serbia",
    organizer: "Superteam Balkan",
    category: "Residency",
    tickets: { priceFrom: 0 },
    source: {
      name: "Superteam Balkan",
      url: "https://luma.com/lr0tvzai",
      verifiedOn: "2026-09-06",
    },
    body: [
      "A Buildstation is Superteam Balkan's name for a fortnight of shared desks with a deadline attached. In the chapter's own words it is “the free coworking space in Belgrade” where “Solana builders, community members and friends of Superteam Balkan will gather to network and build their projects for the upcoming Solana hackathon”.",
      "## Twelve days, not two",
      "<strong>1 to 12 October</strong>. That length is the thing that makes it different from the Friday sessions the same chapter runs: a fortnight is long enough that people arrange the rest of their month around it, and long enough to finish something. It is also why the entry sits under Residency here rather than Co-working.",
      "## Who it is open to",
      "The programme page is explicit that it is open to everyone regardless of background — founders, developers, builders, designers and artists — and names students and people wanting to learn blockchain among those it is aimed at. Attendance is <strong>free</strong>.",
      "## What we are not printing",
      "The organiser's standing Buildstation page still carries the prize pool, travel budget and hackathon name from the previous edition, and the October listing confirms none of them. So this page gives the dates, the city, the host and the price, and leaves the numbers to the organiser to reconfirm. If a figure matters to your decision, ask before you book a flight.",
      "## Where exactly",
      "Belgrade; the listing names no address. The chapter's Friday sessions run at the AI Hub on Savska 5, which is the reasonable guess and not a published fact.",
    ],
    expertise:
      "Read the length as the entry requirement. Nobody blocks twelve days for the coffee, and a room where everyone else arrived with a project is a hard room to walk into with none.",
  },
  {
    slug: "solana-summit-serbia-2026",
    site: "sol2go",
    image: "/covers/solana-summit-serbia-2026.jpg",
    imageAlt:
      "A wide auditorium in violet paper seen from the back, a broad pale mint stage band across the lower third and dense rows of small lilac seat shapes filling the rest of the frame",
    imageKind: "generated",
    imageWidth: 1536,
    imageHeight: 864,
    title: "Solana Summit Serbia 2026",
    summary:
      "Eastern Europe's largest Solana event took the Sava Congress Center in Belgrade on 26 and 27 August: 1,000+ attendees, 50+ speakers, seven tracks, and free to attend.",
    start: "2026-08-26",
    end: "2026-08-27",
    startTime: "08:00",
    endTime: "18:00",
    utcOffset: "+02:00",
    venue: "Sava Congress Center",
    city: "Belgrade",
    country: "Serbia",
    organizer: "Superteam Balkan",
    category: "Summit",
    tickets: { priceFrom: 0 },
    audience: [
      "Founders",
      "Developers",
      "Investors and grant allocators",
      "Payments and stablecoin teams",
      "Infrastructure operators",
      "Regulators",
    ],
    source: {
      name: "Superteam Balkan",
      url: "https://solanasummit.rs/",
      verifiedOn: "2026-09-06",
    },
    programme: [
      { heading: "DeFi", text: "Lending, DEXs, derivatives and MEV — “what's shipping in production, not whitepapers”." },
      { heading: "Infra", text: "Validators, RPC and indexers: the plumbing that lets Solana scale." },
      { heading: "RWA", text: "Tokenised real estate, credit and commodities, and the compliance work behind them." },
      { heading: "Payments", text: "Stablecoin rails and merchant integrations, framed around volume rather than pilots." },
      { heading: "AI & Agents", text: "Autonomous agents transacting on-chain." },
      { heading: "Demo Day", text: "Startups pitching live with capital allocators in the room." },
    ],
    body: [
      "The claim on the door was “Eastern Europe's biggest Solana event”, and the numbers behind it were 1,000+ attendees and 50+ speakers across two days at the <strong>Sava Congress Center</strong>. It was the fourth year of Belgrade Blockchain Week, and it was free to attend.",
      "## The line that explains the room",
      "“No spectators — over half the room are founders and developers actively building.” Whether or not the half is exact, it is the organisers' own framing of what they were selling: not a conference stop, but a working room. Their other line is blunter — “Belgrade isn't a conference circuit stop. People who come here came specifically for this.”",
      "## Who was on stage",
      "Four people from the <strong>Solana Foundation</strong>, among them its head of events and its head of DeFi; <strong>Mert Mumtaz</strong> of Helius; <strong>Vidor Gencel</strong> of Solflare; <strong>Malisha Stanojevic</strong> of Streamflow; core contributors from Kamino, Jito, Marinade and MetaDAO. JetBrains sent the head of its Rust ecosystem.",
      "## The part that does not happen at most Solana events",
      "The programme put an <strong>Assistant Minister from Serbia's Ministry of Finance</strong> on stage for a fireside chat titled “Serbian Financial System on Solana”, and an adviser from the Croatian National Bank on the Internet Capital Markets panel beside the Solana Foundation's CFO. Regulators appearing on a chain's own stage is rare enough to be the reason to read the agenda.",
      "## Two ecosystems, one building",
      "ETH Belgrade ran on the same two dates in the same venue, the twin anchors of Belgrade Blockchain Week. A Solana summit and an Ethereum one sharing a roof is not the usual arrangement, and it is the clearest thing this calendar can say about how the Belgrade scene works.",
      "## If you missed it",
      "The chapter behind it runs a free co-working Friday in Belgrade most weeks and a twelve-day Buildstation in October, both on this calendar. The Summit is annual; the rest of it is not.",
    ],
    expertise:
      "The interesting fact is not the headcount, it is who agreed to sit on the stage. A finance ministry and a central bank taking part in an ecosystem summit is a signal about the country, and it is worth more than the attendance figure.",
  },
  {
    slug: "blockchain-life-2026-dubai",
    site: "sol2go",
    image: "/covers/blockchain-life-2026-dubai.jpg",
    imageAlt:
      "A broad cream wall on a violet ground with a single tall arch cut through the middle of it, and three small pale mint booth shapes standing in the opening",
    imageKind: "generated",
    imageWidth: 1536,
    imageHeight: 864,
    title: "Blockchain Life 2026",
    cardTitle: "Blockchain Life 2026, Dubai",
    summary:
      "The seventeenth Blockchain Life takes Dubai's Festival Arena on 1 and 2 December: a claimed 15,000 attendees, a new AI Future forum inside it, and the week the region's Solana builders plan around.",
    start: "2026-12-01",
    end: "2026-12-02",
    utcOffset: "+04:00",
    venue: "Festival Arena, Dubai Festival City",
    city: "Dubai",
    country: "United Arab Emirates",
    organizer: "Blockchain Life",
    category: "Forum",
    tickets: { priceFrom: 189, currency: "USD" },
    audience: [
      "Miners",
      "Exchanges and trading desks",
      "Web3 founders",
      "Funds and investors",
      "Infrastructure providers",
      "AI and robotics teams",
    ],
    source: {
      name: "Blockchain Life",
      // The edition's own page rather than the site root: the root is
      // whatever forum comes next, and this entry is about this December.
      url: "https://blockchain-life.com/autumn2026/",
      verifiedOn: "2026-09-07",
    },
    // Six of the 200 the organiser lists, chosen for this site's reader:
    // protocol and market-infrastructure people rather than exchange chief
    // executives. The full list is on the edition's own page, which is the
    // source above.
    speakers: [
      { name: "Sergey Nazarov", role: "Co-Founder", org: "Chainlink" },
      { name: "Sandeep Nailwal", role: "Co-Founder", org: "Polygon" },
      { name: "Arthur Breitman", role: "Co-Founder", org: "Tezos" },
      {
        name: "Kostas Chalkias",
        role: "Co-Founder and Chief Cryptographer",
        org: "Mysten Labs",
      },
      { name: "Yoann Turpin", role: "Co-Founder", org: "Wintermute" },
      { name: "Paolo Ardoino", role: "CEO", org: "Tether" },
    ],
    ticket: { url: "https://blockchain-life.com/", label: "Tickets" },
    body: [
      "Blockchain Life is the biggest general crypto forum in the Gulf's calendar, and it is on this one for the ordinary reason: everything else that week is downstream of it. The organisers describe it as the <strong>17th international forum on Web3, mining, cryptocurrencies and AI</strong>, and put the numbers at 15,000+ attendees from 130+ countries, 200+ speakers, 200+ booths and three stages.",
      "## The new half",
      "This edition adds <strong>AI Future</strong>, a forum inside the forum, on “the future of AI, emerging trends, breakthrough robotics” and where those meet blockchain and business. One ticket covers both, which is the organisers' way of saying it is a track rather than a separate event.",
      "## Why it is on a Solana calendar",
      "Because the region's Solana builders come to Dubai for this week, and the side events fill the gaps around it. The forum's own centre of gravity is miners, exchanges and funds rather than any one chain — it earns its place here the way Crypto Expo does, by setting the dates everyone else works around.",
      "## The week around it",
      "The organisers count <strong>100+ side events</strong> between <strong>27 November and 6 December</strong> under the Blockchain Life Week banner. If you are travelling for the forum, the two days in the arena are the smaller part of the trip.",
      "## What a seat costs",
      "Early-bird pricing runs <strong>Standard $189, Business $329, VIP $999</strong>, and the published later prices are $399, $729 and $2,099 — so the gap between booking now and booking at the door is larger than most conferences'. Prices are quoted in dollars and charged in dirhams.",
    ],
    expertise:
      "Buy the ticket well before December or don't buy it at all: standard more than doubles, and VIP goes up by $1,100. The forum is also the excuse for the week rather than the week itself — check the side-event calendar before you decide which nights to be in town.",
  },

  {
    slug: "digitec-2026-yerevan",
    site: "sol2go",
    image: "/covers/digitec-2026-yerevan.jpg",
    imageAlt: "A violet exhibition hall with a row of pale lilac booth counters down each side wall, mint banners and track lights hanging between the columns, a large blank cream board on the far wall and an empty floor down the middle",
    imageKind: "generated",
    imageWidth: 1536,
    imageHeight: 864,
    title: "DigiTec 2026, Yerevan",
    cardTitle: "DigiTec 2026",
    summary:
      "Armenia's largest tech event fills the Meridian Expo Center on 20 to 22 November, and with nothing on the Solana Armenia calendar since July it is the next time the country's Web3 community is all in one building.",
    start: "2026-11-20",
    end: "2026-11-22",
    utcOffset: "+04:00",
    venue: "Meridian Expo, 1 Voskerichneri Street",
    city: "Yerevan",
    country: "Armenia",
    geo: { name: "Meridian Expo", lat: 40.1663961, lng: 44.4999562 },
    organizer: "Union of Advanced Technology Enterprises (UATE)",
    category: "Expo",
    tickets: { priceFrom: 0 },
    ticket: { url: "https://digitec.am/", label: "Register" },
    source: {
      name: "DigiTec",
      url: "https://digitec.am/",
      verifiedOn: "2026-09-06",
    },
    body: [
      "## Why it is on a Solana calendar",
      "Solana Armenia has run four meetups in three years — October 2023, July 2024, February 2025, July 2026 — and its calendar has nothing on it for the rest of this year. DigiTec is the one date the Armenian technology year is organised around, and the Web3 people who fill those meetups spend three days of it in the same building: the <strong>Web3 Armenia Foundation</strong> exhibited in 2023 and again in 2024, and in October 2025 <strong>Gavin Wood</strong> came to a DigiTec Ecosystem Talk on his first visit to the country. If you want to find the Armenian ecosystem in one room this year, this is the room.",
      "## What is confirmed",
      "<strong>20 to 22 November 2026</strong> at the <strong>Meridian Expo</strong>, 1 Voskerichneri Street, in the Kentron district of Yerevan. It is run by <strong>UATE</strong>, Armenia's technology association, with the support of the Government of Armenia and the Yerevan Municipality, and it has run since <strong>2005</strong> — twenty-one years, begun by the late Karen Vardanyan, who described it as a celebration for the global Armenian tech community.",
      "<strong>Admission to the exhibition floor is free</strong>, and registration is required to attend anything at all.",
      "The 2025 edition, by the organiser's own count, drew <strong>more than 30,000 visitors</strong>, <strong>over 200 exhibiting companies</strong>, <strong>more than 100 international speakers</strong> and participants from <strong>over 30 countries</strong>. For 2026 the published targets are <strong>250+ exhibitors</strong> from seven or more countries, <strong>40,000+ visitors</strong> and <strong>80 startups</strong> in Startup Alley, across three named pillars: global tech companies, STEM education and fintech.",
      "## What is not confirmed yet",
      "The thematic tracks and the speaker line-up have not been published — UATE says both will be announced separately — so there is no blockchain track on paper and nothing here promises one. The framing that has been published for 2026 is artificial intelligence: Armenia is being positioned as a regional hub for AI infrastructure, and the organiser says the programme will be anchored in that.",
      "So the reason to put this in a diary now is the date and the building, not a session list. The session list is worth checking again in October.",
    ],
  },

  {
    slug: "200ms-breakpoint-week-2026",
    site: "sol2go",
    image: "/covers/200ms-breakpoint-week-2026.jpg",
    imageAlt: "A stack of flat violet and mint slabs, each offset from the one below it, on deep violet",
    imageKind: "generated",
    imageWidth: 1536,
    imageHeight: 864,
    title: "200ms — Jito's MEV and DeFi day",
    summary:
      "Jito takes 13 November at Olympia for a day on Solana's market microstructure. Free, but selective: priority goes to builders, core developers and onchain traders.",
    start: "2026-11-13",
    utcOffset: "+00:00",
    venue: "Olympia, Hammersmith Rd, London W14 8UX",
    city: "London",
    country: "United Kingdom",
    organizer: "Jito Events",
    category: "Conference",
    tickets: { priceFrom: 0, currency: "GBP" },
    source: {
      name: "200ms on Luma",
      url: "https://luma.com/6xip72je",
      verifiedOn: "2026-09-08",
    },
    ticket: { url: "https://luma.com/6xip72je", label: "Register" },
    body: [
      "The name is the whole argument: 200 milliseconds is roughly how long a Solana slot lasts, and everything this day is about happens inside one.",
      "## The date",
      "<strong>13 November 2026</strong> at <strong>Olympia</strong>, Hammersmith Road, London W14 8UX — the same building Breakpoint opens in two days later. Hosted by <strong>Jito Events</strong>.",
      "## What it covers",
      "The organisers describe it as a day on <strong>Solana's microstructure and DeFi landscape</strong>: what is happening, how it affects DeFi projects, and what traders should know.",
      "## Getting in",
      "Attendance is <strong>free but selective</strong>. Priority is given to <strong>Solana builders</strong>, <strong>core developers</strong> and <strong>onchain traders</strong>.",
    ],
    expertise:
      "This is the first of the three technical days that now open Breakpoint week — 200ms on the 13th, Scale or Die on the 14th, then the conference from the 15th — and it is the one aimed at the trading side rather than the protocol side. Free but selective means the registration is a filter, not a formality: apply early and say what you run onchain, because the room is picked from what people write there. Being in the same building as the main conference also makes it the cheapest way to test whether the Breakpoint week is worth the flight, since nothing about this day depends on holding a conference ticket.",
  },
];
