import type { EventItem } from "../types.ts";

export const items: EventItem[] = [
  {
    slug: "crypto-expo-dubai-2026",
    site: "sol2go",
    image: "/covers/crypto-expo-dubai-2026.jpg",
    imageAlt: "A wide flat hall in violet paper with two rows of small stand shapes and one tall mint tower rising behind it",
    imageKind: "generated",
    imageWidth: 1536,
    imageHeight: 864,
    title: "Crypto Expo Dubai 2026",
    summary:
      "The eighth edition takes the Dubai World Trade Centre on 9 and 10 September, pitched at institutions rather than builders: 7,000+ attendees, 100+ exhibitors, 140+ speakers from 40+ countries.",
    start: "2026-09-09",
    end: "2026-09-10",
    startTime: "10:00",
    endTime: "18:00",
    utcOffset: "+04:00",
    venue: "Dubai World Trade Centre",
    city: "Dubai",
    organizer: "Crypto Expo Dubai",
    category: "Conference",
    audience: [
      "Institutional investors",
      "Asset managers and family offices",
      "Licensed digital asset companies",
      "Exchanges and brokers",
      "Custody and infrastructure providers",
      "Compliance and licensing",
      "Web3 founders",
      "Regulators",
    ],
    source: {
      name: "Crypto Expo Dubai",
      url: "https://cryptoexpodubai.com",
      verifiedOn: "2026-09-06",
    },
    ticket: { url: "https://cryptoexpodubai.com/dubai#tickets", label: "Tickets" },
    body: [
      "The nearest thing on this calendar, and the one least like the rest of it. Where Breakpoint and the Hacker House are addressed to people who write code, Crypto Expo Dubai is addressed to the people who license, custody and allocate — and it says so in its own strapline: “Where Digital Assets Meet Institutional Capital.”",
      "## The dates and the hall",
      "<strong>9 and 10 September 2026</strong>, <strong>10:00 to 18:00</strong>, at the <strong>Dubai World Trade Centre</strong>. It is the <strong>eighth edition</strong>.",
      "## The numbers the organiser publishes",
      "<strong>7,000+ attendees</strong>, <strong>100+ exhibitors</strong>, <strong>140+ speakers</strong>, <strong>40+ countries</strong>. Those are the organiser’s own figures for the edition, not an audited count.",
      "## Who it is built for",
      "The organiser lists six layers by name: institutional investors, asset managers and family offices; licensed digital asset companies and regulated platforms; exchanges, brokers and trading platforms; custody, wallet, blockchain and infrastructure providers; fintech, payments, compliance and licensing services; and Web3 founders, enterprises, regulators and strategic investors.",
      "## The regulators are on the programme, not in the audience",
      "Among the speakers listed on the site are <strong>Simon O’Brien</strong>, Executive Director of Markets at the <strong>Financial Services Regulatory Authority of Abu Dhabi Global Market</strong>, who led the development of ADGM’s virtual asset regulatory framework, and <strong>Sohaib Memon</strong>, a Virtual Assets Supervisory Officer at the <strong>Capital Market Authority</strong>. That is the difference between this event and the rest of the autumn in one line.",
      "## What the site does not publish",
      "Ticket prices. The organiser sends you to a booking page rather than printing a table, so we are not quoting a figure. The full agenda, the exhibitor list and the floor plan each have a page on the site; the side event, the awards and the HashMining &amp; AI Summit are named in the navigation without dates of their own.",
    ],
    expertise:
      "Read the audience list before you buy, because it is the whole review. Six segments are named and not one of them is a developer: this is a licensing, custody and allocation room, in the city that has spent five years building a licensing regime worth flying to. If you are raising, selling infrastructure or trying to get a straight answer out of a regulator, two days at the World Trade Centre is a cheaper way to do it than two months of email. If you came to talk about consensus, this is the wrong hall in the right city, and the London fortnight in November is the one to save the flight for.",
  },

  {
    slug: "breakpoint-2026-london",
    site: "sol2go",
    image: "/covers/breakpoint-2026-london.jpg",
    imageAlt: "A tall paper hall with a barrel-vaulted glass roof cut as flat violet and lilac sheets, a wide crowd band of pale mint below it",
    imageKind: "generated",
    imageWidth: 1536,
    imageHeight: 864,
    title: "Solana Breakpoint 2026",
    summary:
      "Solana's flagship conference lands at Olympia London on 15–17 November, its theme the Token Supercycle. Developer tickets are $250, general admission $550, students $100.",
    start: "2026-11-15",
    end: "2026-11-17",
    startTime: "16:00",
    utcOffset: "+00:00",
    venue: "Olympia Convention Centre",
    city: "London",
    organizer: "Solana Foundation",
    category: "Conference",
    featured: 1,
    source: {
      name: "Solana Foundation",
      url: "https://solana.com/breakpoint",
      verifiedOn: "2026-09-06",
    },
    ticket: { url: "https://luma.com/breakpoint2026", label: "Tickets" },
    tickets: { priceFrom: 100, priceTo: 800, currency: "USD" },
    body: [
      "Breakpoint has been in Lisbon, Amsterdam, Singapore and Abu Dhabi. In 2026 it is in west London, in a Victorian exhibition hall with a barrel-vaulted glass roof, and the framing has moved with it: this is the year the conference stops addressing the room as developers first.",
      "## The dates and the room",
      "<strong>15 to 17 November 2026</strong> at the <strong>Olympia Convention Centre</strong> in London. The Foundation puts attendance at <strong>8,000+</strong>.",
      "## What the theme actually says",
      "The Foundation's own words: Breakpoint 2026 “centers on the Token Supercycle: a new era in which stablecoins, tokenized assets, payments, and AI-driven economic activity increasingly move onchain.” The audience it names is “financial institutions, technology companies, investors, and policymakers” — which is a different guest list from the one Breakpoint had when it was a builders' reunion.",
      "## What a ticket costs",
      "<strong>Developers $250</strong>. <strong>Students $100</strong>. <strong>General admission $550</strong>, rising to <strong>$800</strong> late. The developer and student tiers are the interesting part of that table: a conference that prices its builders at less than half of general admission is telling you who it still wants in the room.",
      "## The week around it",
      "Breakpoint is the middle of a fortnight, not a standalone. The <strong>Solana Hacker House</strong> runs 1–12 November, <strong>Scale or Die</strong> takes the day before on 14 November, and side events fill the evenings of the 16th. If you are flying in, the calendar to plan against is the fortnight, not the three days.",
    ],
    expertise:
      "Two things are worth knowing before you buy. First, the price ladder is real: the late-bird tier at $800 is a $250 penalty for deciding in October, and the developer tier at $250 has historically sold out well before the general one. Second, a London Breakpoint is the cheapest one this conference has been to reach for anyone in Europe since Lisbon in 2023 — which is also why the room will be fuller than the ticket count suggests, because the side events do not require a badge. If the reason you are going is the hallway rather than the stage, the Hacker House fortnight and the free evening events may be the better half of the trip.",
  },

  {
    slug: "crypto-worlds-fair-2026",
    site: "sol2go",
    image: "/covers/crypto-worlds-fair-2026.jpg",
    imageAlt: "A ring of flat pavilion shapes in violet, lilac and mint paper arranged around a small cream disc",
    imageKind: "generated",
    imageWidth: 1536,
    imageHeight: 864,
    title: "Crypto World's Fair",
    cardTitle: "Crypto World's Fair hackathon",
    summary:
      "Colosseum's online hackathon runs four weeks from 14 September to 12 October, across eight ecosystems at once. Winners can take $250,000 from its accelerator.",
    start: "2026-09-14",
    end: "2026-10-12",
    city: "Online",
    online: true,
    organizer: "Colosseum",
    category: "Hackathon",
    featured: 2,
    audience: ["Founders", "Developers", "Designers", "First-time teams"],
    source: {
      name: "Colosseum",
      url: "https://www.colosseum.com/worldsfair",
      verifiedOn: "2026-09-06",
    },
    ticket: { url: "https://www.colosseum.com/worldsfair", label: "Register" },
    body: [
      "Colosseum runs the hackathons that Solana used to run itself, and it has spent three years being a Solana competition. This one is not. The Crypto World's Fair puts eight ecosystems on the same page and asks builders to pick one.",
      "## The dates",
      "<strong>14 September to 12 October 2026</strong> — four weeks, entirely online. Colosseum describes it as “a global, online competition where founders sprint over 4 weeks to build impactful products”, and as “an online hackathon bringing together builders and founders across blockchain ecosystems to launch breakout startups.”",
      "## Who is on the page",
      "The ecosystem logos shown are <strong>Solana</strong>, <strong>Ethereum</strong>, <strong>Hyperliquid</strong>, <strong>Base</strong>, <strong>Tempo</strong>, <strong>Arbitrum</strong>, <strong>Zcash</strong> and <strong>Robinhood Chain</strong>.",
      "## What is actually on offer",
      "Non-dilutive prizes and, for the teams that get through, a place in Colosseum's full-time accelerator with <strong>$250,000 in capital from its venture fund</strong>. The prize table itself had not been published as of 6 September.",
      "## The signal to read",
      "The registration counter stood at <strong>778 builders</strong> when we checked. That is early — the last Colosseum competition finished with a registration figure an order of magnitude higher, and most teams sign up in the final week.",
    ],
    expertise:
      "A cross-ecosystem hackathon changes what a good submission looks like. In a single-chain competition the judges know the ecosystem's gaps and you can win by filling one; here the field is eight ecosystems wide, so a project whose whole argument is a chain-specific optimisation has to explain itself to a judge who does not share the premise. The teams that tend to do well in that format are the ones whose product makes sense to somebody who does not care which chain it is on, and which then have a specific, defensible reason for the chain they chose. The four-week length also matters: it is a business sprint as much as an engineering one, and Colosseum has been explicit for two years that it funds founders rather than repositories.",
  },

  {
    slug: "solana-hacker-house-london-2026",
    site: "sol2go",
    image: "/covers/solana-hacker-house-london-2026.jpg",
    imageAlt: "Rows of flat desk shapes in lilac and mint paper receding under a long violet ceiling band",
    imageKind: "generated",
    imageWidth: 1536,
    imageHeight: 864,
    title: "Solana Hacker House — London",
    cardTitle: "Solana Hacker House London",
    summary:
      "Thirteen days of free workspace and workshops in London, 1–12 November, running straight into Breakpoint. Approval required, and capacity is limited.",
    start: "2026-11-01",
    end: "2026-11-12",
    startTime: "10:00",
    endTime: "20:00",
    utcOffset: "+00:00",
    city: "London",
    organizer: "Solana Foundation",
    category: "Hacker House",
    featured: 3,
    audience: ["Developers", "Founders", "Designers"],
    source: {
      name: "Solana Foundation",
      url: "https://luma.com/london-hh-26",
      verifiedOn: "2026-09-06",
    },
    ticket: { url: "https://luma.com/london-hh-26", label: "Request to join" },
    body: [
      "The Hacker House is the part of the Breakpoint fortnight that costs nothing and takes the most out of you. Thirteen days of desks, and the expectation that you leave with something built.",
      "## The dates and the day",
      "<strong>1 to 12 November 2026</strong> in London, open <strong>10:00 to 20:00</strong> daily. Registration is handled on the day, <strong>10:00 to 17:00</strong>.",
      "## What is in the building",
      "Workspace with wifi and power, food, lounges and dedicated build zones. The programme is described as “Workshops and deep dives across DeFi, security, infrastructure, and applications”, with Ecosystem Experts and Solana Foundation teams on hand.",
      "## Getting in",
      "<strong>Approval is required</strong> and capacity is limited: you request to join through the event page, and the organisers ask that you keep your RSVP current rather than holding a place you will not use. Anyone wanting to lead a session applies through a typeform; sponsorship goes to events@solana.org.",
      "## Where the address is",
      "Not published. The venue is released to approved guests through the event page rather than announced, which is normal for a Hacker House and worth knowing before you book a hotel.",
    ],
    expertise:
      "Thirteen days is unusually long — most Hacker Houses run five. The length is deliberate: this one exists to fill the run-up to Breakpoint, so the first week is the quiet, useful one and the second is when the conference crowd arrives and the desks stop being available. If you are coming to build rather than to network, the first week is the whole value of the trip, and it is also the week the Ecosystem Experts have time for a real conversation rather than a queue.",
  },

  {
    slug: "scale-or-die-2026",
    site: "sol2go",
    image: "/covers/scale-or-die-2026.jpg",
    imageAlt: "A steep ascending stack of narrow paper bars in violet and mint against a pale ground",
    imageKind: "generated",
    imageWidth: 1536,
    imageHeight: 864,
    title: "Scale or Die",
    summary:
      "A one-day engineering conference in London on 14 November, 09:30 to 18:30, the day before Breakpoint opens.",
    start: "2026-11-14",
    startTime: "09:30",
    endTime: "18:30",
    utcOffset: "+00:00",
    city: "London",
    organizer: "Solana Foundation",
    category: "Conference",
    source: {
      name: "Solana Foundation",
      url: "https://luma.com/scale-or-die-26",
      verifiedOn: "2026-09-06",
    },
    ticket: { url: "https://luma.com/scale-or-die-26", label: "Register" },
    body: [
      "Scale or Die is the technical day that Breakpoint's main stage no longer has room for. One day, one track, London, and it happens the day before the conference opens.",
      "## The details",
      "<strong>14 November 2026</strong>, <strong>09:30 to 18:30</strong>, in London. The address is released to registered guests rather than published.",
      "## Why the day before",
      "Because the people it is for are already flying in. Putting the engineering day on the 14th means it costs a Saturday rather than a Breakpoint session, and it is the reason a developer ticket for the fortnight is worth more than the three conference days on its own.",
      "The full speaker list had not been published as of 6 September.",
    ],
    expertise:
      "The pattern to watch is that Breakpoint's own programme has moved toward institutions and policy, and Scale or Die is where the material that used to be on the main stage went. If the reason you were considering Breakpoint is the protocol engineering, this single day may be the better ticket — and it is a Saturday, so it costs nothing in working time.",
  },

  {
    slug: "solana-summit-canada-2026",
    site: "sol2go",
    image: "/covers/solana-summit-canada-2026.jpg",
    imageAlt: "A flat gabled market-hall silhouette in violet paper with a row of mint arches beneath it",
    imageKind: "generated",
    imageWidth: 1536,
    imageHeight: 864,
    title: "Solana Summit Canada",
    summary:
      "Two days in Toronto on 23–24 September at St. Lawrence Market North, the Canadian stop on the Solana Summit circuit.",
    start: "2026-09-23",
    end: "2026-09-24",
    startTime: "09:30",
    utcOffset: "-04:00",
    venue: "St. Lawrence Market North",
    city: "Toronto",
    organizer: "Superteam Canada",
    category: "Summit",
    source: {
      name: "Solana Foundation events calendar",
      url: "https://lu.ma/Solana-Summit-Canada",
      verifiedOn: "2026-09-06",
    },
    ticket: { url: "https://lu.ma/Solana-Summit-Canada", label: "Register" },
    body: [
      "The Solana Summit series is the Foundation's regional format: one or two days, a local host community, and a room sized for the country rather than the continent. Canada's runs in Toronto at the end of September.",
      "## The details",
      "<strong>23 and 24 September 2026</strong> at <strong>St. Lawrence Market North</strong>, Toronto. The building is the newer half of the St. Lawrence Market complex, which is a market hall rather than a conference centre — expect an open floor rather than breakout rooms.",
      "The programme had not been published in full as of 6 September.",
    ],
  },

  {
    slug: "ethglobal-tokyo-2026",
    site: "sol2go",
    image: "/covers/ethglobal-tokyo-2026.jpg",
    imageAlt: "A tall paper gate form in violet over a dense grid of small mint and lilac squares",
    imageKind: "generated",
    imageWidth: 1536,
    imageHeight: 864,
    title: "ETHGlobal Tokyo 2026",
    summary:
      "A three-day in-person hackathon in Tokyo, 25–27 September, with the Pragma Tokyo conference alongside it on the 26th.",
    start: "2026-09-25",
    end: "2026-09-27",
    utcOffset: "+09:00",
    city: "Tokyo",
    organizer: "ETHGlobal",
    category: "Hackathon",
    source: {
      name: "ETHGlobal",
      url: "https://ethglobal.com/events",
      verifiedOn: "2026-09-06",
    },
    ticket: { url: "https://ethglobal.com/events", label: "Apply to attend" },
    body: [
      "Not a Solana event, and here for the same reason the rest of the wider calendar is: the people who build across chains keep both dates in one diary.",
      "## The details",
      "<strong>25 to 27 September 2026</strong>, Tokyo, listed by ETHGlobal as an in-person hackathon. Attendance is by application rather than by ticket.",
      "## The day beside it",
      "<strong>Pragma Tokyo 2026</strong> runs on <strong>26 September</strong> in the same city — ETHGlobal's conference format, which travels with the hackathons rather than separately from them.",
      "Two other dates from the same calendar are worth noting for the autumn: <strong>ETHOnline 2026</strong>, an async online hackathon running <strong>4 to 16 September</strong>, and <strong>ETHGlobal Mumbai</strong> on <strong>6 to 8 November</strong>, with <strong>Pragma Mumbai</strong> the day before it.",
    ],
  },

  {
    slug: "solana-summit-korea-2026",
    site: "sol2go",
    image: "/covers/solana-summit-korea-2026.jpg",
    imageAlt: "A stepped skyline of flat violet towers with a wide mint river band across the lower frame",
    imageKind: "generated",
    imageWidth: 1536,
    imageHeight: 864,
    title: "Solana Summit Korea",
    summary:
      "A single day in Seoul on 30 September, 10:00 to 17:00, on Yeoui-daero in the Yeouido financial district.",
    start: "2026-09-30",
    startTime: "10:00",
    endTime: "17:00",
    utcOffset: "+09:00",
    city: "Seoul",
    organizer: "Solana Foundation",
    category: "Summit",
    source: {
      name: "Solana Foundation events calendar",
      url: "https://lu.ma/solana-summit-korea-2026",
      verifiedOn: "2026-09-06",
    },
    ticket: { url: "https://lu.ma/solana-summit-korea-2026", label: "Register" },
    body: [
      "## The details",
      "<strong>30 September 2026</strong>, <strong>10:00 to 17:00</strong>, Seoul. The listing places it on <strong>Yeoui-daero</strong> — Yeouido, which is the financial district rather than the startup one, and that is a choice worth reading.",
      "The exact address is released to registered guests. The programme had not been published in full as of 6 September.",
    ],
  },

  {
    slug: "solana-summit-singapore-2026",
    site: "sol2go",
    image: "/covers/solana-summit-singapore-2026.jpg",
    imageAlt: "Three tall paper columns joined by a long flat deck in violet, a mint bay band below",
    imageKind: "generated",
    imageWidth: 1536,
    imageHeight: 864,
    title: "Solana Summit Singapore",
    summary:
      "6 October at the Ritz-Carlton Millenia, 09:00 to 18:00 — and the Solana Capital Forum runs in the same city on the same day.",
    start: "2026-10-06",
    startTime: "09:00",
    endTime: "18:00",
    utcOffset: "+08:00",
    venue: "The Ritz-Carlton, Millenia Singapore",
    city: "Singapore",
    organizer: "Solana Foundation",
    category: "Summit",
    source: {
      name: "Solana Foundation events calendar",
      url: "https://lu.ma/solana-summit-singapore-2026",
      verifiedOn: "2026-09-06",
    },
    ticket: { url: "https://lu.ma/solana-summit-singapore-2026", label: "Register" },
    body: [
      "## The details",
      "<strong>6 October 2026</strong>, <strong>09:00 to 18:00</strong>, at <strong>The Ritz-Carlton, Millenia Singapore</strong>.",
      "## The clash worth knowing about",
      "The <strong>Solana Capital Forum Singapore</strong> runs the same day, <strong>12:00 to 20:00</strong>, in the Orchard area. Two Solana events, one city, one date, overlapping by six hours — they are aimed at different rooms, but if you were planning to do both, the afternoon is the part you have to choose between.",
    ],
  },

  {
    slug: "solana-summit-india-2026",
    site: "sol2go",
    image: "/covers/solana-summit-india-2026.jpg",
    imageAlt: "A row of flat arched openings in violet paper with mint sea shapes behind them",
    imageKind: "generated",
    imageWidth: 1536,
    imageHeight: 864,
    title: "Solana Summit India",
    summary:
      "Mumbai on 2 November, 10:00 to 19:00, in Navpada — four days before ETHGlobal fills the same city.",
    start: "2026-11-02",
    startTime: "10:00",
    endTime: "19:00",
    utcOffset: "+05:30",
    city: "Mumbai",
    organizer: "Solana Foundation",
    category: "Summit",
    source: {
      name: "Solana Foundation events calendar",
      url: "https://lu.ma/solana-summit-india",
      verifiedOn: "2026-09-06",
    },
    ticket: { url: "https://lu.ma/solana-summit-india", label: "Register" },
    body: [
      "## The details",
      "<strong>2 November 2026</strong>, <strong>10:00 to 19:00</strong>, Mumbai, in <strong>Navpada</strong>. The exact address is released to registered guests.",
      "## The week it sits in",
      "Mumbai has a crowded first week of November: <strong>Pragma Mumbai</strong> on the <strong>5th</strong> and <strong>ETHGlobal Mumbai</strong> from the <strong>6th to the 8th</strong>. If you are travelling to India for one of them, the Summit is three days of overlap away from the other.",
    ],
  },

  {
    slug: "solana-startup-connect-ghana-2026",
    site: "sol2go",
    image: "/covers/solana-startup-connect-ghana-2026.jpg",
    imageAlt: "Interlocking flat chevrons in violet, mint and cream paper forming a broad woven band",
    imageKind: "generated",
    imageWidth: 1536,
    imageHeight: 864,
    title: "solanaStartupConnect Ghana",
    summary:
      "Two days at the Accra Digital Centre on 15–16 October, the Solana calendar's West African stop this autumn.",
    start: "2026-10-15",
    end: "2026-10-16",
    utcOffset: "+00:00",
    venue: "Accra Digital Centre",
    city: "Accra",
    category: "Summit",
    source: {
      name: "Solana Foundation events calendar",
      url: "https://lu.ma/nx9ps6ud",
      verifiedOn: "2026-09-06",
    },
    ticket: { url: "https://lu.ma/nx9ps6ud", label: "Register" },
    body: [
      "## The details",
      "<strong>15 and 16 October 2026</strong> at the <strong>Accra Digital Centre</strong>, Ghana. The listing gives a start time in a timezone that does not match the venue, so we are printing the dates and leaving the clock to the organiser's page rather than publishing an hour we cannot stand behind.",
      "The programme had not been published in full as of 6 September.",
    ],
  },

  {
    slug: "co-working-fridays-london-september-2026",
    site: "sol2go",
    title: "Co-Working Fridays: London Chapter",
    summary:
      "A free Friday desk at Somerset House, 11 September, 10:00 to 20:00. The London chapter runs it most weeks.",
    start: "2026-09-11",
    startTime: "10:00",
    endTime: "20:00",
    utcOffset: "+01:00",
    venue: "Somerset House",
    city: "London",
    organizer: "Superteam UK",
    category: "Co-working",
    tickets: { priceFrom: 0 },
    source: {
      name: "Superteam UK, via the Solana Foundation events calendar",
      url: "https://lu.ma/london-sep-11",
      verifiedOn: "2026-09-06",
    },
    body: [
      "Somerset House is a strange address for a co-working day, and that is most of the appeal. Superteam UK runs one every Friday for “builders, leaders and creatives at the frontier of tech in London”, and 11 September is simply the next one.",
      "## What it costs, and what that does not mean",
      "Attendance is <strong>free</strong>. It is not open: entry is <strong>by approval only</strong>, so registering is not the same as being on the guestlist, and the organiser says so in as many words. You are asked to show the confirmation QR code or email on arrival, and you are given a wristband to wear for the day.",
      "The listing adds two warnings worth reading before you plan a train around it: places are <strong>limited even after confirmation</strong>, and arriving early is the organiser's own advice.",
      "## The hours do not agree with themselves",
      "The calendar entry runs <strong>10:00 to 20:00</strong>. The description on the same page says <strong>10:00 to 20:30</strong>. We print the first, because it is the field the calendar actually schedules from, and we mention the second because a half-hour is exactly the kind of difference that strands somebody at a door.",
      "## Who runs it",
      "Superteam describes itself as a global co-operative of regional non-profits across <strong>20+ countries</strong>, supporting founders and talent. The UK chapter takes questions through the Solana UK Telegram group, and membership applications through superteamuk.org.",
      "## What the page does not publish",
      "No agenda, no speakers, no room number. This is a desk and the people at the other desks, which is the entire proposition — the value is who else got approved that week, and nobody publishes that in advance.",
    ],
    expertise:
      "Register early rather than on the Thursday. Approval-only plus “limited spaces even after confirmation” means the guestlist is a queue, and a weekly event with a fixed room fills from the regulars outward.",
  },

  {
    slug: "the-future-of-finance-thessaloniki-2026",
    site: "sol2go",
    title: "The Future of Finance — Thessaloniki",
    cardTitle: "The Future of Finance, Thessaloniki",
    summary:
      "Anodos Labs and Superteam Balkan take over a cruise boat moored by the White Tower on 13 September, 19:30 to 22:00 — the closing party of Thessaloniki International Fair week.",
    start: "2026-09-13",
    startTime: "19:30",
    endTime: "22:00",
    utcOffset: "+03:00",
    venue: "Klió Cruise boat, by the White Tower",
    city: "Thessaloniki",
    organizer: "Anodos Labs and Superteam Balkan",
    category: "Meetup",
    tickets: { priceFrom: 0 },
    source: {
      name: "Anodos Labs and Superteam Balkan, via the Solana Foundation events calendar",
      url: "https://lu.ma/q242rqc4",
      verifiedOn: "2026-09-06",
    },
    body: [
      "The venue is the point: a cruise boat, the <strong>Klió</strong>, docked on the waterfront beside the White Tower. Anodos Labs and Superteam Balkan have taken it for an evening, and the meetup happens on the water.",
      "## Why that evening",
      "13 September is the <strong>last day of the Thessaloniki International Fair</strong>, and this is a side event to it — the organisers pitch it as the after-party that closes TIF week rather than as a standalone meetup. If you are in the city for the fair, the calendar has arranged itself for you.",
      "## Who it is for",
      "The listing casts wide on purpose: founders, builders, creators, students, marketers, developers, engineers, “and anyone curious about the future of finance and new emerging technologies such as blockchain and AI”. Read that as an evening for meeting people rather than for learning something specific.",
      "## What is actually promised",
      "<strong>One free cocktail or drink</strong> for everyone on board, live DJ sets, and conversations about finance, startups and the Solana ecosystem. Superteam Balkan uses the evening to explain what it offers a builder in the region — jobs, mentorship, education, grants, ecosystem support.",
      "## The two hosts",
      "<strong>Anodos Labs</strong> is a fintech building what it calls a global financial super app, with a stated mission to make financial services reachable “anywhere, anytime, anyhow”. <strong>Superteam Balkan</strong> is the regional chapter that connects founders and developers to capital, talent and mentorship in the Solana ecosystem.",
      "## What the page does not publish",
      "No speaker list, no schedule for the three hours, and no capacity. The boat is a boat, so the last of those is the one that matters.",
    ],
    expertise:
      "Treat the mooring as the deadline rather than the start time. A boat with a fixed dock and a three-hour window is not a room you can slip into at 21:00, and the listing sets no capacity — which on a vessel means the capacity is set by the vessel.",
  },

  {
    slug: "solana-ecosystem-call-september-2026",
    site: "sol2go",
    title: "The Solana Ecosystem Call — September",
    cardTitle: "Solana Ecosystem Call, September",
    summary:
      "The monthly ecosystem call returns on 24 September, 14:00 to 15:00 UTC — a live show hosted by SOL BROTHERS that would rather be late-night television than a community update.",
    start: "2026-09-24",
    startTime: "14:00",
    endTime: "15:00",
    utcOffset: "+00:00",
    city: "Online",
    online: true,
    organizer: "SOL BROTHERS Studio",
    category: "Online",
    tickets: { priceFrom: 0 },
    source: {
      name: "SOL BROTHERS Studio, via the Solana Foundation events calendar",
      url: "https://lu.ma/0j8gx7i1",
      verifiedOn: "2026-09-06",
    },
    body: [
      "Most ecosystem calls are a slide deck and a queue of speakers. This one is produced as a show, and describes itself that way: it “brings the production quality and energy of late-night television to the fastest-moving ecosystem in crypto”.",
      "## The format",
      "An hour, monthly, live. Each episode is built out of <strong>sketches, interviews, data-driven segments and unfiltered commentary</strong> rather than a run of announcements. The organisers' own line for it is “no fluff, yet cringe-intolerant”, which is a claim you can hold them to.",
      "## Who makes it",
      "<strong>SOL BROTHERS Studio</strong>, a podcast producer that hosts interviews and is credited as the creator of the official Solana Ecosystem Call. The show keeps its own site at ecosystemcall.com.",
      "## The part that is worth knowing",
      "Segments are <strong>open to submission</strong>. The listing invites product announcements, timeline moments, event plans and company giveaways through a submission form — so an hour of television is also a distribution channel for anyone building on Solana, and one that costs nothing to try.",
      "## What the page does not publish",
      "No guest list and no running order for September. The show is “back” with what the listing calls fresh energy, and what that means is decided closer to the day.",
    ],
    expertise:
      "If you have something to announce, the submission form is the reason to open this listing at all — the hour itself will be on the timeline afterwards, and the one thing you cannot get later is a slot in it.",
  },

  {
    slug: "superteam-canada-community-call-october-2026",
    site: "sol2go",
    title: "Superteam Canada Community Call — October",
    cardTitle: "Superteam Canada call, October",
    summary:
      "Thirty minutes on Discord on 1 October, 16:00 to 16:30 UTC, hosted by Simon. The first of three on the calendar, a month apart.",
    start: "2026-10-01",
    startTime: "16:00",
    endTime: "16:30",
    utcOffset: "+00:00",
    city: "Online",
    online: true,
    organizer: "Superteam Canada",
    category: "Online",
    tickets: { priceFrom: 0 },
    source: {
      name: "Superteam Canada, via the Solana Foundation events calendar",
      url: "https://lu.ma/aq7rqqmn",
      verifiedOn: "2026-09-06",
    },
    body: [
      "Half an hour on Discord, hosted by Simon, and pitched at both ends of the room: “whether you're a seasoned pro or just starting out”. The chapter uses it to answer questions and to find people who want to do more than attend.",
      "## The three dates",
      "Superteam Canada has <strong>three of these on the calendar</strong> — 1 October, 5 November and 3 December 2026 — each on the first Thursday of the month.",
      "## Monthly or quarterly?",
      "The listing says the call happens “first Thursday on the every Quarter”. The calendar says three Thursdays a month apart. <strong>The dates are the reliable half</strong>: they are what the invitation actually schedules, and they are what a reminder is set from.",
      "## What half an hour buys",
      "Insights, advice, questions taken live, and a route into the chapter for anyone who wants one. Thirty minutes is not a conference — it is the shortest way to find out whether a regional chapter is worth your time before committing an evening to one of its events.",
      "## What the page does not publish",
      "No agenda per call and no guest names. A recurring listing that reuses one description does not tell you what October differs on, and this one does not pretend to.",
    ],
    expertise:
      "Join the Discord before the day rather than at 16:00. A thirty-minute call on a server you have not been admitted to is a call you will spend ten minutes joining.",
  },

  {
    slug: "solana-capital-forum-singapore-2026",
    site: "sol2go",
    title: "Solana Capital Forum Singapore",
    summary:
      "6 October in Orchard, 12:00 to 20:00 — a private forum capped at 150 allocators, investors, policymakers and infrastructure providers.",
    start: "2026-10-06",
    startTime: "12:00",
    endTime: "20:00",
    utcOffset: "+08:00",
    city: "Singapore",
    organizer: "Solana Foundation",
    category: "Forum",
    source: {
      name: "Solana Foundation",
      url: "https://lu.ma/sol-cap-sg",
      verifiedOn: "2026-09-06",
    },
    ticket: { url: "https://capitalforum.solana.com/", label: "Official site" },
    body: [
      "The number to read first is <strong>150</strong>. That is the cap the Solana Foundation has put on the room, and it is the design of the day rather than a detail of it — a curated executive gathering that is limited on purpose so the conversations are with people who can act on them.",
      "## Who is in the room",
      "Allocators, investors, operators, policymakers and infrastructure providers, drawn from traditional finance and digital assets both. The Foundation's own framing puts the forum “at the intersection of institutional capital, private capital, and financial innovation”.",
      "## What is discussed",
      "How <strong>tokenized assets, stablecoins and internet-native financial infrastructure</strong> are reshaping global capital markets. That is the whole published brief: no track list, no session titles, no speakers as of 6 September.",
      "## The eight hours",
      "<strong>12:00 to 20:00</strong> in Orchard. Luma gives the district and withholds the street — the address goes to registered guests, which is the usual shape for an invitation-controlled room.",
      "## The clash worth knowing about",
      "The <a href=\"/events/solana-summit-singapore-2026/\" title=\"Solana Summit Singapore\">Solana Summit</a> runs in the same city on the same day. One is the builders' day and this is the institutional one, and they overlap by six hours — so Singapore on 6 October is a choice, not a schedule.",
      "## What the page does not publish",
      "No price, no application criteria, and no indication of how the 150 are selected. Sponsorship goes through events@solana.org; attendance goes through the official site.",
    ],
    expertise:
      "A 150-seat cap in a week that also carries a summit means the guestlist closes on relevance rather than on date. If the forum is the reason you are flying, apply before you book — the summit will still be there if this one says no.",
  },

  {
    slug: "islanddao-v5-2026",
    site: "sol2go",
    title: "IslandDAO v5",
    summary:
      "IslandDAO's month-long residency goes to Latin America for the first time: Florianópolis, 19 October to 11 November, with a hackathon, investor days and a demo day inside it.",
    start: "2026-10-19",
    end: "2026-11-11",
    utcOffset: "-03:00",
    city: "Florianópolis",
    organizer: "IslandDAO",
    category: "Residency",
    source: {
      name: "IslandDAO, via the Solana Foundation events calendar",
      url: "https://lu.ma/6laijuyn",
      verifiedOn: "2026-09-06",
    },
    ticket: { url: "https://islanddao.org/", label: "Apply" },
    body: [
      "Twenty-four days is not an event, it is a move. IslandDAO's fifth residency runs from <strong>19 October to 11 November</strong> and asks developers, founders and investors in the Solana ecosystem to co-work in one place for most of a month.",
      "## The new part",
      "<strong>For the first time the residency goes to LATAM</strong>: Florianópolis — Floripa — in Santa Catarina, Brazil. The four previous editions did not, and the organisers lead with the change rather than burying it.",
      "## What is inside the month",
      "The published programme is a list rather than a schedule: <strong>building, feedback sessions, investor days, a hackathon, a demo day, work opportunities, fitness and wellness</strong>. The shape that implies is an accelerator with no cohort agreement — the demo day at the end is the deadline everything else runs toward.",
      "## How you get in",
      "Registration on Luma is not registration. The listing is explicit about it: <strong>apply at islanddao.org</strong>, and only there. A residency that houses people for three and a half weeks is selecting, not ticketing.",
      "## What the page does not publish",
      "No cost, no accommodation terms, no cohort size, no application deadline. For a month away from home those are the four questions, and all four are behind the application form.",
    ],
    expertise:
      "Ask what is covered before you ask whether you qualify. Three and a half weeks in Brazil has a floor price in flights and rent whatever the residency provides, and the listing settles none of it — a demo day is worth planning around, but not on an assumption about who pays for the bed.",
  },

  {
    slug: "money-layer-breakpoint-week-2026",
    site: "sol2go",
    title: "Money Layer — Breakpoint Week",
    cardTitle: "Money Layer, Breakpoint week",
    summary:
      "Capvise brings its founder-and-fund format to Breakpoint week: London, 16 November, 18:30 to 22:00, under the heading “Money. Markets. Machines.”",
    start: "2026-11-16",
    startTime: "18:30",
    endTime: "22:00",
    utcOffset: "+00:00",
    city: "London",
    organizer: "Capvise Global",
    category: "Side event",
    tickets: { priceFrom: 0 },
    source: {
      name: "Capvise Global, via the Solana Foundation events calendar",
      url: "https://lu.ma/xykfcf1a",
      verifiedOn: "2026-09-06",
    },
    body: [
      "Three and a half hours on the Monday evening of <a href=\"/events/breakpoint-2026-london/\" title=\"Solana Breakpoint 2026, London\">Breakpoint</a> week, under a three-word banner — <strong>Money. Markets. Machines.</strong> — that is also the room's segment list.",
      "## What the room is meant to contain",
      "The organiser's description of it is unusually precise about function: “the companies building the financial stack, the companies buying it, and the capital funding it”. In practice that means founders, funds, market makers, exchanges, asset managers, fintechs, protocols and senior operators who are already in town for the conference.",
      "## The track record they cite",
      "Capvise Global says previous editions have run in <strong>Singapore, Dubai, Bali and Buenos Aires</strong> and drew <strong>6,400+ applications</strong> across them. Applications, note, not attendees — the number describes demand for the format rather than the size of any room.",
      "## The commercial half",
      "A good part of the listing is a partnership pitch: presenting, Money, Markets, Machines, Exchange and After Dark are named as partner slots, with series and city partnerships available and a deck on request. Worth knowing what you are reading, and worth knowing the evening is programmed around those segments.",
      "## What the page does not publish",
      "No venue, no speakers, no capacity, no admission terms. The address follows registration, as it does for most of Breakpoint week's evenings.",
    ],
    expertise:
      "Breakpoint week's evenings compete with each other, and this one starts at 18:30 while <a href=\"/events/pr1me-london-dinner-2026/\" title=\"Pr1me London dinner\">the Pr1me dinner</a> starts at 19:00 across town. One is a room you work; the other is a table you sit at for three hours. Pick by which you actually want, not by which confirms first.",
  },

  {
    slug: "pr1me-london-dinner-2026",
    site: "sol2go",
    title: "Pr1me London — dinner for web3 finance",
    cardTitle: "Pr1me London dinner",
    summary:
      "A Breakpoint-week dinner for web3 accounting and finance, London, 16 November, 19:00 to 22:00 — and the guest list is restricted by job title, in writing.",
    start: "2026-11-16",
    startTime: "19:00",
    endTime: "22:00",
    utcOffset: "+00:00",
    city: "London",
    organizer: "Onchain Finance Institute",
    category: "Side event",
    tickets: { priceFrom: 0 },
    source: {
      name: "Onchain Finance Institute, via the Solana Foundation events calendar",
      url: "https://lu.ma/aqntywn2",
      verifiedOn: "2026-09-06",
    },
    body: [
      "Most invite-only listings hint. This one states the rule: the dinner is <strong>for finance professionals — CFOs, COOs, Controllers, Heads of Finance, or equivalent</strong> — and “we're unable to accept applications outside these roles”. Read it before you apply, because it is the clearest admission criterion on this calendar.",
      "## What it is",
      "The London edition of the PR1ME series, run during <a href=\"/events/breakpoint-2026-london/\" title=\"Solana Breakpoint 2026, London\">Breakpoint</a> and described as community-driven rather than commercial: an evening for the people doing web3 accounting and finance, at a table rather than in a room.",
      "## Who is behind it",
      "Four names. The <strong>Onchain Finance Institute</strong>, an education and community platform for finance professionals moving into onchain work, which says it has 150+ alumni and 400+ community members. The <strong>Solana Foundation</strong>. <strong>Lukka</strong>, which builds institutional digital-asset data for pricing, valuation, compliance and reporting. And <strong>Breezing</strong>, a crypto subledger for accountants that connects to Xero and QuickBooks, SOC 2 certified, used by 200+ businesses.",
      "## Entry is by QR code",
      "The listing is blunt about it: only confirmed guests with a QR code get in, and <strong>walk-ins and unapproved registrations will not be possible</strong>. A dinner has covers, and covers are counted in advance.",
      "## What the page does not publish",
      "No venue, no menu, no cost, and no number of seats. The address goes to confirmed guests, which for a dinner during Breakpoint week is the norm rather than a slight.",
    ],
    expertise:
      "This is the one evening in Breakpoint week where the job title on your application does the deciding, so put the real one on it. If you are a founder rather than a finance lead, <a href=\"/events/money-layer-breakpoint-week-2026/\" title=\"Money Layer, Breakpoint week\">Money Layer</a> starts half an hour earlier and is the room that wants you.",
  },

  {
    slug: "superteam-canada-community-call-november-2026",
    site: "sol2go",
    title: "Superteam Canada Community Call — November",
    cardTitle: "Superteam Canada call, November",
    summary:
      "The second of the three, 5 November, 17:00 to 17:30 UTC on Discord. The clock moves an hour in UTC and the listing does not say why.",
    start: "2026-11-05",
    startTime: "17:00",
    endTime: "17:30",
    utcOffset: "+00:00",
    city: "Online",
    online: true,
    organizer: "Superteam Canada",
    category: "Online",
    tickets: { priceFrom: 0 },
    source: {
      name: "Superteam Canada, via the Solana Foundation events calendar",
      url: "https://lu.ma/8uhc300o",
      verifiedOn: "2026-09-06",
    },
    body: [
      "The same thirty minutes on Discord as October's, hosted by Simon, on the first Thursday of the month.",
      "## The hour that moved",
      "October's call is 16:00 UTC; this one is <strong>17:00 UTC</strong>. Nothing in the listing explains it, but the reason is the clock rather than the organiser: the call is scheduled in Toronto time, and North America puts its clocks back on 1 November. <strong>The local hour is unchanged — the UTC one is not.</strong> If you are joining from Europe, this is the month the reminder in your calendar quietly stops matching the one in your head.",
      "## The description is out of date",
      "The listing still opens by announcing a call “Thursday, Jul 3rd, 12:00 PM to 12:30 PM EDT”. The scheduled fields say 5 November. We follow the fields, because they are what the invitation runs on, and we say so here rather than tidying it away.",
      "## What it is",
      "A chapter call: questions taken live, advice, and a route in for anyone who wants to do more than listen. Superteam Canada is one of the regional chapters of a co-operative that runs in more than twenty countries.",
      "## What the page does not publish",
      "No agenda for November. See <a href=\"/events/superteam-canada-community-call-october-2026/\" title=\"Superteam Canada Community Call, October\">October's call</a> for what the series looks like when it runs.",
    ],
    expertise:
      "Check what your calendar app did with this one. A recurring series whose UTC hour shifts in November catches people who set a reminder in October, and the half-hour is short enough that arriving late is arriving after.",
  },

  {
    slug: "superteam-canada-community-call-december-2026",
    site: "sol2go",
    title: "Superteam Canada Community Call — December",
    cardTitle: "Superteam Canada call, December",
    summary:
      "The last one on the calendar: 3 December, 17:00 to 17:30 UTC on Discord. Nothing is published beyond it.",
    start: "2026-12-03",
    startTime: "17:00",
    endTime: "17:30",
    utcOffset: "+00:00",
    city: "Online",
    online: true,
    organizer: "Superteam Canada",
    category: "Online",
    tickets: { priceFrom: 0 },
    source: {
      name: "Superteam Canada, via the Solana Foundation events calendar",
      url: "https://lu.ma/sejn139p",
      verifiedOn: "2026-09-06",
    },
    body: [
      "First Thursday of the month, thirty minutes on Discord, hosted by Simon — the third and last of the calls Superteam Canada has scheduled in 2026.",
      "## The end of the published series",
      "October, November, December, and then nothing. <strong>No January date has been announced</strong> as of 6 September. That is worth knowing before you treat the series as a standing fixture: three dates is what the chapter has committed to in public, and the fourth is a question.",
      "## Same clock as November",
      "<strong>17:00 UTC</strong>, which is midday in Toronto — the hour the series has run at locally all along. See <a href=\"/events/superteam-canada-community-call-november-2026/\" title=\"Superteam Canada Community Call, November\">November's call</a> for why the UTC time changed and the local one did not.",
      "## The description is out of date",
      "As on the other two listings, the text still announces a call on “Thursday, Jul 3rd”. The scheduled fields carry 3 December, and those are what the invitation runs on.",
      "## What the page does not publish",
      "No agenda, no guests, no indication of whether a December call before the holidays runs shorter or longer than the half-hour it is booked for.",
    ],
    expertise:
      "This is the one to attend if you want to know whether the series continues. A chapter with no January date published in September will either announce one on this call or not have one — and the question costs nothing to ask in a room built for questions.",
  },

  {
    slug: "solana-frontier-hackathon-2026",
    site: "sol2go",
    image: "/covers/solana-frontier-hackathon-2026.jpg",
    imageAlt: "A wide horizon band of layered violet and mint paper with one small cream flag shape near the edge",
    imageKind: "generated",
    imageWidth: 1536,
    imageHeight: 864,
    title: "Solana Frontier Hackathon",
    summary:
      "Colosseum's spring competition ran 6 April to 11 May and paid out $250,000 in prizes, with another $250,000 per accelerator place — and no tracks and no bounties at all.",
    start: "2026-04-06",
    end: "2026-05-11",
    city: "Online",
    online: true,
    organizer: "Colosseum",
    category: "Hackathon",
    source: {
      name: "Colosseum",
      url: "https://blog.colosseum.com/announcing-the-solana-frontier-hackathon/",
      verifiedOn: "2026-09-06",
    },
    body: [
      "The Frontier hackathon is the most useful thing to read before entering the current one, because it is where Colosseum wrote down what it actually rewards.",
      "## The dates",
      "<strong>6 April to 11 May 2026</strong>, online. Announced on 6 April.",
      "## What it paid",
      "<strong>$30,000</strong> to the grand champion. <strong>$10,000</strong> each to the next twenty startups. <strong>$10,000</strong> for the best university team and <strong>$10,000</strong> for the best public goods project. Up to <strong>ten</strong> winners took a place in the accelerator, each carrying <strong>$250,000 in pre-seed funding</strong>, mentorship, AI credits, in-person support at Colosseum's San Francisco office and a private demo day. Colosseum put the total venture deployment at <strong>over $2.5 million</strong>.",
      "## The part people miss",
      "There were <strong>no tracks and no bounties</strong>. Colosseum framed the competition as “intensive engineering <em>and</em> business sprints where elite developers vie for prizes and pre-seed funding” — which is a polite way of saying that a technically excellent project with no business behind it does not place.",
    ],
    outcome: [
      "The format carried straight into the autumn: the Crypto World's Fair, which opened on 14 September, uses the same accelerator terms — $250,000 per team from the venture fund — and the same absence of tracks.",
    ],
  },

  {
    slug: "solana-armenia-meetup-yerevan-july-2026",
    site: "sol2go",
    image: "/covers/solana-armenia-meetup-yerevan-july-2026.jpg",
    imageAlt: "A low wide room in violet paper with the three-bar Solana mark hanging on the back wall in the red, blue and apricot of the Armenian flag, a small raised platform at one end and flat cream and mint rectangles scattered across the floor",
    imageKind: "generated",
    imageWidth: 1536,
    imageHeight: 864,
    title: "Solana Armenia Meetup, Yerevan",
    cardTitle: "Solana Armenia Meetup",
    summary:
      "108 people came to the ISTC Foundation on 25 July for two short talks, a CTF prize ceremony and four hours of Armenian builders in one room.",
    start: "2026-07-25",
    startTime: "16:00",
    endTime: "20:00",
    utcOffset: "+04:00",
    venue: "ISTC Foundation",
    city: "Yerevan",
    geo: { lat: 40.1831239, lng: 44.5262954 },
    organizer: "Solana Armenia",
    category: "Meetup",
    tickets: { priceFrom: 0 },
    source: {
      name: "Solana Armenia",
      url: "https://luma.com/404vst65",
      verifiedOn: "2026-09-06",
    },
    body: [
      "Four hours on a Saturday afternoon and evening in Kentron, and the organisers were explicit about how they divide them: “We like keeping the talks concise so there's enough time for the conversations that happen afterwards.” Two talks, a prize ceremony, and then the part the evening is actually for.",
      "## The room",
      "<strong>ISTC Foundation</strong>, 1 and 7 Alek Manukyan Street, in the Kentron district of Yerevan. <strong>108 people registered.</strong> The listing calls it &ldquo;another evening with the local Solana community&rdquo;, so the room is a habit rather than a one-off.",
      "## The programme",
      "<strong>Levon Bilbulyan — “Understanding Solana PDAs Through a CTF Challenge.”</strong> Program-derived addresses taught from the attacker's side, which is the way they stop being an abstraction: a PDA you have had to break is a PDA you understand.",
      "Then the <strong>CTF challenge recap and prize ceremony</strong> — the meetup ran a capture-the-flag and handed out the prizes in the room.",
      "<strong>Ernest Mkrtchyan — “The Status Code That Waited 28 Years.”</strong> The title names no code and the listing does not expand on it, which is either very good billing or an accident. Whoever was there knows.",
      "Then networking, for as long as the rest of it left.",
      "## Who it was for",
      "The invitation lists the room it wanted: people writing Rust, people building a startup, people working in fintech, computer science students, and anyone who had merely started to look at Solana. That is a wider door than most technical meetups open, and it is deliberate — the organisers describe the evening as relaxed, and the value proposition as seeing what other people in Armenia are working on.",
      "## Written twice, on purpose",
      "The listing runs in full in <strong>English and Armenian</strong>, not as a summary and a translation. A community that writes its invitation twice is telling you who it expects to come.",
      "## Who runs it",
      "<strong>Solana Armenia</strong>, hosted by <strong>Ernest Mkrtchyan</strong> and <strong>Hrach Avagyan</strong>. It is a local calendar rather than a Foundation programme — this evening does not appear on the Solana Foundation's own events calendar at all, which is worth knowing if that calendar is where you look for what is happening near you.",
    ],
    outcome: [
      "The format is the takeaway, and it is portable: two short talks, a competition with its prizes handed over in person, and the rest of the evening left empty on purpose. A meetup that schedules its own conversations is rarer than it should be.",
      "Nothing is published yet for the next one. The calendar it was announced on is the place it will appear.",
    ],
  },

  {
    slug: "ethglobal-lisbon-2026",
    site: "sol2go",
    title: "ETHGlobal Lisbon 2026",
    summary:
      "800+ hackers, $100,000 in prizes and one rule change: for the first time at an ETHGlobal event, you did not have to start from an empty repository.",
    start: "2026-07-24",
    end: "2026-07-26",
    utcOffset: "+01:00",
    city: "Lisbon",
    organizer: "ETHGlobal",
    category: "Hackathon",
    source: {
      name: "ETHGlobal",
      url: "https://ethglobal.com/events/lisbon2026",
      verifiedOn: "2026-09-06",
    },
    body: [
      "Lisbon is on this calendar for one reason, and it is not the prize pool. It is where ETHGlobal changed the oldest rule in hackathons.",
      "## The rule that changed",
      "Until Lisbon, the terms were: empty repository only, existing code not allowed. In July they became <strong>“any repo you bring”</strong>, with existing code <strong>welcomed</strong>. Team size stayed 1–5 and sponsor SDKs stayed capped at three — ETHGlobal's own summary is “two items, the rest unchanged”, which undersells it.",
      "## The three ways to enter",
      "<strong>From Scratch</strong> — show up, type <code>git init</code>, ship by Sunday, the hackathon everyone already knew. <strong>Extend Open Source</strong> — bring a repository you already maintain and ship the feature you have been putting off all year. <strong>Ship a Feature</strong> — build one new feature on top of something existing and release it as open source.",
      "## The weekend by the numbers",
      "<strong>24–26 July 2026</strong>, Lisbon. <strong>800+ attendees</strong>, <strong>10+ protocols</strong>, <strong>29+ workshops</strong>. <strong>$100,000 in prizes</strong>, the largest pots being The Graph, World, Hedera and 0G at <strong>$15,000</strong> each, then Uniswap Foundation at $10,000, 1inch at $7,000, Sui at $6,000 and ENS at $5,000.",
      "## Themes",
      "Zero-knowledge proofs, AI × crypto, DeFi, consumer crypto, layer 2s, interoperability, public goods, privacy, security, TEEs, data availability, identity and dev tools.",
      "## It started two weeks early",
      "The schedule opened on <strong>8 July</strong> with virtual team-formation and brainstorming sessions, a beginners' workshop on 15 July on what to expect, and more sessions on the 17th and 22nd. The application deadline was <strong>17 July</strong> — a week before the doors.",
    ],
    outcome: [
      "The rule change is the part that travels. A hackathon that accepts existing repositories is judging the feature rather than the weekend, and it turns the format from a sprint into a release — which is a different competition from the one that has run for a decade.",
      "ETHGlobal wrapped the weekend in two more dates in the same city: Onchain Builders Day on 23 July and the Pragma Lisbon conference on 25 July. The next in-person one on its calendar is Tokyo, 25 to 27 September.",
    ],
  },
];
