import type { EventItem } from "../types.ts";

const source = {
  name: "Visit Yerevan",
  url: "https://visityerevan.am/blog/details/156/am/",
  verifiedOn: "2026-10-09",
};

// Separate, image-led event pages for the stages listed in the City Day guide.
export const items: EventItem[] = [
  {
    slug: "yerevan-city-day-diana-arbenina-2026",
    createdAt: "2026-10-09T12:00:00+04:00",
    updatedAt: "2026-10-09T12:00:00+04:00",
    site: "tick",
    title: "Դիանա Արբենինա և «Նոչնիե սնայպերի». Երևանի օրվա համերգը",
    cardTitle: "Դիանա Արբենինան՝ Երևանի օրը",
    titleSeo: "Երևանի օր․ Դիանա Արբենինայի համերգը՝ հոկտեմբերի 9-ին",
    summary: "Երևանի օրվա բացման համերգը Դիանա Աբգարի անվան զբոսայգում է. Դիանա Արբենինան և «Նոչնիե սնայպերի»-ն ելույթ կունենան հոկտեմբերի 9-ին՝ ժամը 21:00-ին։",
    start: "2026-10-09",
    startTime: "21:00",
    utcOffset: "+04:00",
    city: "Երևան",
    country: "Հայաստան",
    venue: "Դիանա Աբգարի անվան զբոսայգի, Երևան",
    geo: { name: "Դիանա Աբգարի անվան զբոսայգի", lat: 40.1832252, lng: 44.5077975 },
    organizer: "Երևանի քաղաքապետարան",
    tags: ["yerevan-city-day"],
    category: "Համերգներ",
    image: "/covers/yerevan-2808th-anniversary-2026.jpg",
    imageAlt: "Երևանի 2808-ամյակի պաշտոնական նարնջագույն պաստառը՝ հոկտեմբերի 9–10-ի տոնական գրությամբ",
    imageKind: "illustration",
    imageCredit: "Երևանի քաղաքապետարան",
    imageWidth: 523,
    imageHeight: 349,
    source,
    body: [
      "Երևանի օրվա երկօրյա տոնակատարությունների մեկնարկը կտրվի հոկտեմբերի 9-ին՝ Դիանա Աբգարի անվան զբոսայգում։ Գլխավոր համերգին Դիանա Արբենինան հանդես կգա «Նոչնիե սնայպերի» խմբի հետ։",
      "## Ժամը և վայրը",
      "Համերգը նախատեսված է ժամը 21:00-ին։ Զբոսայգում նույն օրերին անցկացվում է նաև գարեջրի փառատոն։",
    ],
    faq: [
      { q: "Ե՞րբ է Դիանա Արբենինայի համերգը Երևանում", a: "Հոկտեմբերի 9-ին՝ ժամը 21:00-ին, Դիանա Աբգարի անվան զբոսայգում։" },
      { q: "Որտե՞ղ է համերգը", a: "Դիանա Աբգարի անվան զբոսայգում՝ Երևանի կենտրոնում։" },
    ],
    i18n: {
      en: {
        title: "Diana Arbenina and Night Snipers: Yerevan City Day concert",
        cardTitle: "Diana Arbenina on Yerevan City Day",
        titleSeo: "Yerevan City Day: Diana Arbenina concert on 9 October",
        summary: "Yerevan City Day opens at Diana Abgar Park: Diana Arbenina and Night Snipers perform on 9 October at 21:00.",
        city: "Yerevan",
        country: "Armenia",
        venue: "Diana Abgar Park, Yerevan",
        organizer: "Yerevan Municipality",
        category: "Concerts",
        imageAlt: "Official orange poster for Yerevan's 2,808th anniversary, dated 9–10 October",
        imageCredit: "Yerevan Municipality",
        body: [
          "Yerevan's two-day City Day celebration opens on 9 October at Diana Abgar Park. Diana Arbenina performs with the Night Snipers band.",
          "## Time and place",
          "The concert is scheduled for 21:00. A beer festival also takes place in the park on 9 and 10 October.",
        ],
        faq: [
          { q: "When is Diana Arbenina's Yerevan concert?", a: "At 21:00 on 9 October at Diana Abgar Park." },
          { q: "Where is the concert?", a: "At Diana Abgar Park in central Yerevan." },
        ],
      },
    },
  },
  {
    slug: "yerevan-city-day-beer-festival-2026",
    createdAt: "2026-10-09T12:00:00+04:00",
    updatedAt: "2026-10-09T12:00:00+04:00",
    site: "tick",
    title: "Երևանի օրվա գարեջրի փառատոնը՝ Դիանա Աբգարի այգում",
    cardTitle: "Գարեջրի փառատոն՝ Երևանի օրը",
    titleSeo: "Երևանի օր․ գարեջրի փառատոն Դիանա Աբգարի այգում",
    summary: "Երևանի օրվա գարեջրի փառատոնը Դիանա Աբգարի անվան զբոսայգում է՝ հոկտեմբերի 9-ից 10-ը։ Առաջին օրը ծրագիրը սկսվում է ժամը 16:00-ին։",
    start: "2026-10-09",
    startTime: "16:00",
    end: "2026-10-10",
    utcOffset: "+04:00",
    city: "Երևան",
    country: "Հայաստան",
    venue: "Դիանա Աբգարի անվան զբոսայգի, Երևան",
    geo: { name: "Դիանա Աբգարի անվան զբոսայգի", lat: 40.1832252, lng: 44.5077975 },
    organizer: "Երևանի քաղաքապետարան",
    tags: ["yerevan-city-day"],
    category: "Փառատոներ",
    image: "/covers/yerevan-2808th-anniversary-2026.jpg",
    imageAlt: "Երևանի 2808-ամյակի պաշտոնական տոնական պաստառը՝ քաղաքային միջոցառումների համար",
    imageKind: "illustration",
    imageCredit: "Երևանի քաղաքապետարան",
    imageWidth: 523,
    imageHeight: 349,
    source,
    body: [
      "Երևանի օրվա գարեջրի փառատոնը անցկացվում է Դիանա Աբգարի անվան զբոսայգում՝ հոկտեմբերի 9-ին և 10-ին։ Քաղաքային ուղեցույցում նշվում է, որ առաջին օրը փառատոնը մեկնարկում է ժամը 16:00-ին, իսկ հոկտեմբերի 10-ին կշարունակվի ռոք բեմի համերգների հետ զուգահեռ։",
      "Հոկտեմբերի 9-ի երեկոյան այգու գլխավոր համերգին ելույթ կունենան Դիանա Արբենինան և «Նոչնիե սնայպերի»-ն։",
    ],
    faq: [
      { q: "Ե՞րբ է գարեջրի փառատոնը", a: "Հոկտեմբերի 9–10-ին։ Հոկտեմբերի 9-ին մեկնարկը ժամը 16:00-ին է։" },
      { q: "Որտե՞ղ է անցկացվում փառատոնը", a: "Դիանա Աբգարի անվան զբոսայգում՝ Երևանում։" },
    ],
    i18n: {
      en: {
        title: "Yerevan City Day beer festival at Diana Abgar Park",
        cardTitle: "Beer festival on Yerevan City Day",
        titleSeo: "Yerevan City Day: beer festival at Diana Abgar Park",
        summary: "The Yerevan City Day beer festival runs at Diana Abgar Park on 9–10 October. On the first day, it opens at 16:00.",
        city: "Yerevan",
        country: "Armenia",
        venue: "Diana Abgar Park, Yerevan",
        organizer: "Yerevan Municipality",
        category: "Festivals",
        imageAlt: "Official celebration poster for Yerevan's 2,808th anniversary and its city events",
        imageCredit: "Yerevan Municipality",
        body: [
          "The Yerevan City Day beer festival takes place at Diana Abgar Park on 9 and 10 October. The city guide says it opens at 16:00 on the first day and continues alongside the rock stage on 10 October.",
          "Diana Arbenina and Night Snipers headline the park's concert on the evening of 9 October.",
        ],
        faq: [
          { q: "When is the beer festival?", a: "On 9–10 October; it opens at 16:00 on 9 October." },
          { q: "Where is the festival?", a: "At Diana Abgar Park in Yerevan." },
        ],
      },
    },
  },
  {
    slug: "yerevan-city-day-pop-stage-2026",
    createdAt: "2026-10-09T12:00:00+04:00",
    updatedAt: "2026-10-09T12:00:00+04:00",
    site: "tick",
    title: "Երևանի օրվա փոփ բեմը՝ Շառլ Ազնավուրի հրապարակում",
    cardTitle: "Փոփ բեմ՝ Շառլ Ազնավուրի հրապարակում",
    titleSeo: "Երևանի օր․ փոփ համերգը՝ Շառլ Ազնավուրի հրապարակում",
    summary: "Երևանի օրվա փոփ բեմը հոկտեմբերի 10-ին է՝ Շառլ Ազնավուրի հրապարակում, ժամը 12:00–18:00։ Ծրագրում են Արամ MP3-ը և հայկական խմբեր։",
    start: "2026-10-10",
    startTime: "12:00",
    end: "2026-10-10",
    endTime: "18:00",
    utcOffset: "+04:00",
    city: "Երևան",
    country: "Հայաստան",
    venue: "Շառլ Ազնավուրի հրապարակ, Երևան",
    geo: { name: "Շառլ Ազնավուրի հրապարակ", lat: 40.1816935, lng: 44.5169406 },
    organizer: "Երևանի քաղաքապետարան",
    tags: ["yerevan-city-day"],
    category: "Համերգներ",
    image: "/covers/yerevan-2808th-anniversary-2026.jpg",
    imageAlt: "Երևանի 2808-ամյակի պաշտոնական պաստառը՝ հոկտեմբերի 9–10-ի տոնակատարությունների համար",
    imageKind: "illustration",
    imageCredit: "Երևանի քաղաքապետարան",
    imageWidth: 523,
    imageHeight: 349,
    source,
    speakersHeading: "Կատարողներ",
    speakers: [{ name: "Aram MP3" }, { name: "Mohana Band" }, { name: "D'Litte" }, { name: "Project 12" }, { name: "Yellow Heart" }, { name: "Kami Friends" }],
    body: [
      "Երևանի օրվա փոփ համերգը հոկտեմբերի 10-ին Շառլ Ազնավուրի հրապարակում է։ Քաղաքային ուղեցույցը բեմի ծրագիրը նշում է ժամը 12:00–18:00-ը։",
      "Կատարողների թվում են Արամ MP3-ը, Mohana Band-ը, D'Litte-ը, Project 12-ը, Yellow Heart-ը և Kami Friends-ը։",
    ],
    faq: [{ q: "Ո՞ր ժամին է փոփ համերգը", a: "Հոկտեմբերի 10-ին՝ ժամը 12:00–18:00։" }, { q: "Որտե՞ղ է փոփ բեմը", a: "Շառլ Ազնավուրի հրապարակում՝ Երևանի կենտրոնում։" }],
    i18n: {
      en: {
        title: "Yerevan City Day pop stage at Charles Aznavour Square",
        cardTitle: "Pop at Charles Aznavour Square",
        titleSeo: "Yerevan City Day: pop concert at Charles Aznavour Square",
        summary: "The Yerevan City Day pop stage runs on 10 October at Charles Aznavour Square, 12:00–18:00, with Aram MP3 and Armenian acts.",
        city: "Yerevan",
        country: "Armenia",
        venue: "Charles Aznavour Square, Yerevan",
        organizer: "Yerevan Municipality",
        category: "Concerts",
        imageAlt: "Official poster for Yerevan's 2,808th anniversary celebrations on 9–10 October",
        imageCredit: "Yerevan Municipality",
        speakersHeading: "Performers",
        body: [
          "The Yerevan City Day pop concert is at Charles Aznavour Square on 10 October. The city's guide lists the stage from 12:00 to 18:00.",
          "Performers include Aram MP3, Mohana Band, D'Litte, Project 12, Yellow Heart and Kami Friends.",
        ],
        faq: [{ q: "What time is the pop concert?", a: "On 10 October, from 12:00 to 18:00." }, { q: "Where is the pop stage?", a: "At Charles Aznavour Square in central Yerevan." }],
      },
    },
  },
  {
    slug: "yerevan-city-day-jazz-fkj-2026",
    createdAt: "2026-10-09T12:00:00+04:00",
    updatedAt: "2026-10-09T12:00:00+04:00",
    site: "tick",
    title: "Երևանի օրվա ջազ բեմը՝ Կասկադում և FKJ-ի մասնակցությամբ",
    cardTitle: "Ջազ Կասկադում․ FKJ՝ ժամը 20:00-ին",
    titleSeo: "Երևանի օր․ ջազ համերգ Կասկադում, FKJ՝ 20:00-ին",
    summary: "Երևանի օրվա ջազ բեմը Կասկադի Գաֆէսճեան քանդակների պարտեզում է՝ հոկտեմբերի 10-ին, ժամը 13:00–22:00։ Հատուկ հյուր FKJ-ն ելույթ կունենա 20:00-ին։",
    start: "2026-10-10",
    startTime: "13:00",
    end: "2026-10-10",
    endTime: "22:00",
    utcOffset: "+04:00",
    city: "Երևան",
    country: "Հայաստան",
    venue: "Գաֆէսճեան քանդակների պարտեզ, Կասկադ, Երևան",
    geo: { name: "Գաֆէսճեան քանդակների պարտեզ", lat: 40.1893845, lng: 44.5154178 },
    organizer: "Երևանի քաղաքապետարան",
    tags: ["yerevan-city-day"],
    category: "Համերգներ",
    image: "/covers/yerevan-city-day-fkj-2026.jpg",
    imageAlt: "Visit Yerevan-ի ջազի պաստառը՝ FKJ-ի դիմանկարով և հոկտեմբերի 10-ի 20:00 ելույթի նշումով",
    imageKind: "illustration",
    imageCredit: "Visit Yerevan",
    imageWidth: 1280,
    imageHeight: 720,
    source,
    speakersHeading: "Կատարողներ",
    speakers: [{ name: "FKJ" }, { name: "Հայաստանի պետական ջազ նվագախումբ" }, { name: "Karen Manukyan Trio" }, { name: "The Armenian Colors Quartet" }, { name: "Artyom Manukyan Trio" }, { name: "Malkhas Jazz Trio" }],
    body: [
      "Երևանի օրվա ջազային ծրագիրը հոկտեմբերի 10-ին Կասկադի Գաֆէսճեան քանդակների պարտեզում է՝ ժամը 13:00–22:00։",
      "Օրվա ընթացքում ելույթ կունենան Հայաստանի պետական ջազ նվագախումբը, Karen Manukyan Trio-ն, Վահագն Հայրապետյանի The Armenian Colors Quartet-ը, Artyom Manukyan Trio-ն, Malkhas Jazz Trio-ն և այլ երաժիշտներ։",
      "## Հատուկ հյուր՝ FKJ",
      "Ֆրանսիացի բազմագործիքահար FKJ-ի ելույթը նախատեսված է ժամը 20:00-ին։",
    ],
    faq: [{ q: "Ե՞րբ է FKJ-ի համերգը Երևանում", a: "Հոկտեմբերի 10-ին՝ ժամը 20:00-ին, Կասկադի ջազ բեմում։" }, { q: "Որքա՞ն է տևում ջազային ծրագիրը", a: "Քաղաքային ուղեցույցում նշված ժամերն են 13:00–22:00։" }],
    i18n: {
      en: {
        title: "Yerevan City Day jazz at the Cascade, with FKJ",
        cardTitle: "Jazz at the Cascade: FKJ at 20:00",
        titleSeo: "Yerevan City Day: Cascade jazz concert, FKJ at 20:00",
        summary: "The Yerevan City Day jazz stage runs at the Cafesjian Sculpture Garden on 10 October, 13:00–22:00. Special guest FKJ plays at 20:00.",
        city: "Yerevan",
        country: "Armenia",
        venue: "Cafesjian Sculpture Garden, Cascade, Yerevan",
        organizer: "Yerevan Municipality",
        category: "Concerts",
        imageAlt: "Visit Yerevan jazz poster with FKJ and his 20:00 performance time on 10 October",
        imageCredit: "Visit Yerevan",
        speakersHeading: "Performers",
        body: [
          "Yerevan City Day's jazz programme takes place at the Cafesjian Sculpture Garden at the Cascade on 10 October, from 13:00 to 22:00.",
          "Performers include the Armenian State Jazz Orchestra, Karen Manukyan Trio, Vahagn Hayrapetyan's The Armenian Colors Quartet, Artyom Manukyan Trio, Malkhas Jazz Trio and others.",
          "## Special guest: FKJ",
          "French multi-instrumentalist FKJ is scheduled to perform at 20:00.",
        ],
        faq: [{ q: "When is FKJ performing in Yerevan?", a: "At 20:00 on 10 October on the Cascade jazz stage." }, { q: "What are the jazz stage hours?", a: "The city guide lists 13:00–22:00." }],
      },
    },
  },
  {
    slug: "yerevan-city-day-rock-stage-2026",
    createdAt: "2026-10-09T12:00:00+04:00",
    updatedAt: "2026-10-09T12:00:00+04:00",
    site: "tick",
    title: "Երևանի օրվա ռոք բեմը՝ Դիանա Աբգարի անվան զբոսայգում",
    cardTitle: "Ռոք՝ Դիանա Աբգարի զբոսայգում",
    titleSeo: "Երևանի օր․ ռոք համերգ Դիանա Աբգարի զբոսայգում",
    summary: "Երևանի օրվա ռոք բեմը Դիանա Աբգարի անվան զբոսայգում է՝ հոկտեմբերի 10-ին, ժամը 13:00–23:00։ Ծրագրում են Nemra-ն, Bambir-ը, FairWind-ը և այլ խմբեր։",
    start: "2026-10-10",
    startTime: "13:00",
    end: "2026-10-10",
    endTime: "23:00",
    utcOffset: "+04:00",
    city: "Երևան",
    country: "Հայաստան",
    venue: "Դիանա Աբգարի անվան զբոսայգի, Երևան",
    geo: { name: "Դիանա Աբգարի անվան զբոսայգի", lat: 40.1832252, lng: 44.5077975 },
    organizer: "Երևանի քաղաքապետարան",
    tags: ["yerevan-city-day"],
    category: "Համերգներ",
    image: "/covers/yerevan-city-day-nemra-2026.jpg",
    imageAlt: "Visit Yerevan-ի Երևանի օրվա պաստառը՝ Nemra խմբի և հոկտեմբերի 10-ի համերգի համար",
    imageKind: "illustration",
    imageCredit: "Visit Yerevan",
    imageWidth: 1280,
    imageHeight: 720,
    source,
    speakersHeading: "Կատարողներ",
    speakers: [{ name: "Nemra" }, { name: "Bambir" }, { name: "FairWind" }, { name: "Another Story" }, { name: "The Beautified Project" }, { name: "Lav Eli" }],
    body: [
      "Երևանի օրվա ռոք բեմը հոկտեմբերի 10-ին գործում է Դիանա Աբգարի անվան զբոսայգում՝ ժամը 13:00–23:00։",
      "Համերգների ծրագրում են FairWind-ը, Another Story-ն, The Beautified Project-ը, «Լավ էլի»-ն, «Նեմրան», «Բամբիռը» և այլ հայկական կատարողներ։ Զբոսայգում կշարունակվի նաև գարեջրի փառատոնը։",
    ],
    faq: [{ q: "Ե՞րբ է Երևանի օրվա ռոք համերգը", a: "Հոկտեմբերի 10-ին՝ ժամը 13:00–23:00։" }, { q: "Որտե՞ղ է ռոք բեմը", a: "Դիանա Աբգարի անվան զբոսայգում։" }],
    i18n: {
      en: {
        title: "Yerevan City Day rock stage at Diana Abgar Park",
        cardTitle: "Rock at Diana Abgar Park",
        titleSeo: "Yerevan City Day: rock concert at Diana Abgar Park",
        summary: "The Yerevan City Day rock stage runs at Diana Abgar Park on 10 October, 13:00–23:00, with Nemra, Bambir, FairWind and other bands.",
        city: "Yerevan",
        country: "Armenia",
        venue: "Diana Abgar Park, Yerevan",
        organizer: "Yerevan Municipality",
        category: "Concerts",
        imageAlt: "Visit Yerevan poster for the Nemra concert on Yerevan City Day, 10 October",
        imageCredit: "Visit Yerevan",
        speakersHeading: "Performers",
        body: [
          "The Yerevan City Day rock stage runs at Diana Abgar Park on 10 October, from 13:00 to 23:00.",
          "The line-up includes FairWind, Another Story, The Beautified Project, Lav Eli, Nemra, Bambir and other Armenian acts. The beer festival continues in the park too.",
        ],
        faq: [{ q: "When is the Yerevan City Day rock concert?", a: "On 10 October, from 13:00 to 23:00." }, { q: "Where is the rock stage?", a: "At Diana Abgar Park in Yerevan." }],
      },
    },
  },
  {
    slug: "yerevan-city-day-armenian-music-wine-2026",
    createdAt: "2026-10-09T12:00:00+04:00",
    updatedAt: "2026-10-09T12:00:00+04:00",
    site: "tick",
    title: "Երևանի օրվա ազգային երաժշտությունն ու գինու փառատոնը",
    cardTitle: "Ազգային երաժշտություն և գինի",
    titleSeo: "Երևանի օր․ հայկական երաժշտություն և գինու փառատոն",
    summary: "Երևանի օրվա ազգային երաժշտության ծրագիրը Հյուսիսային պողոտայում է՝ հոկտեմբերի 10-ին, 13:00–18:00։ Գինու փառատոնը կշարունակվի մինչև 23:00։",
    start: "2026-10-10",
    startTime: "12:00",
    end: "2026-10-10",
    endTime: "23:00",
    utcOffset: "+04:00",
    city: "Երևան",
    country: "Հայաստան",
    venue: "Հյուսիսային պողոտա, Երևան",
    geo: { name: "Հյուսիսային պողոտա", lat: 40.1836176, lng: 44.5148388 },
    organizer: "Երևանի քաղաքապետարան",
    tags: ["yerevan-city-day"],
    category: "Փառատոներ",
    image: "/covers/yerevan-city-day-akunk-2026.jpg",
    imageAlt: "Visit Yerevan-ի Երևանի օրվա պաստառը՝ «Ակունք» պետական ազգագրական համույթի պատկերով",
    imageKind: "illustration",
    imageCredit: "Visit Yerevan",
    imageWidth: 1280,
    imageHeight: 720,
    source,
    speakersHeading: "Կատարողներ",
    speakers: [{ name: "Սոնա Ռուբենյան" }, { name: "Arpi & Highway Band" }, { name: "Թմբաթա" }, { name: "Ethno Colors" }, { name: "Ակունք" }, { name: "Զվարթնոց" }],
    body: [
      "Երևանի օրվա ազգային երաժշտության բեմն ու գինու փառատոնը հոկտեմբերի 10-ին Հյուսիսային պողոտայում են։ Երաժշտական ելույթները նախատեսված են 13:00–18:00-ին, իսկ գինու փառատոնը՝ 12:00–23:00-ին։",
      "Ելույթ կունենան Սոնա Ռուբենյանը, Arpi & Highway Band-ը, «Թմբաթան», Ethno Colors-ը, «Ակունք» պետական ազգագրական համույթը և «Զվարթնոց» քանոնահարների անսամբլը։ Ծրագրում կլինեն նաև ազգային երգի ու պարի խմբեր։",
    ],
    faq: [{ q: "Որտե՞ղ և ե՞րբ է ազգային երաժշտության ծրագիրը", a: "Հոկտեմբերի 10-ին՝ Հյուսիսային պողոտայում, ժամը 13:00–18:00։" }, { q: "Մինչև ե՞րբ է գինու փառատոնը", a: "Հոկտեմբերի 10-ին՝ մինչև ժամը 23:00։" }],
    i18n: {
      en: {
        title: "Yerevan City Day Armenian music and wine festival",
        cardTitle: "Armenian music and wine",
        titleSeo: "Yerevan City Day: Armenian music and wine festival",
        summary: "Yerevan City Day's Armenian music programme is on Northern Avenue on 10 October, 13:00–18:00. The wine festival runs until 23:00.",
        city: "Yerevan",
        country: "Armenia",
        venue: "Northern Avenue, Yerevan",
        organizer: "Yerevan Municipality",
        category: "Festivals",
        imageAlt: "Visit Yerevan poster featuring the Akunk State Ethnographic Ensemble for City Day",
        imageCredit: "Visit Yerevan",
        speakersHeading: "Performers",
        body: [
          "Yerevan City Day's Armenian music stage and wine festival take place on Northern Avenue on 10 October. Music runs from 13:00 to 18:00; the wine festival is open from 12:00 to 23:00.",
          "Performers include Sona Rubenyan, Arpi & Highway Band, Tmbata, Ethno Colors, Akunk State Ethnographic Ensemble and Zvartnots Qanun Ensemble, alongside folk song and dance groups.",
        ],
        faq: [{ q: "When and where is the Armenian music programme?", a: "On 10 October on Northern Avenue, from 13:00 to 18:00." }, { q: "When does the wine festival close?", a: "At 23:00 on 10 October." }],
      },
    },
  },
  {
    slug: "yerevan-city-day-rap-stage-2026",
    createdAt: "2026-10-09T12:00:00+04:00",
    updatedAt: "2026-10-09T12:00:00+04:00",
    site: "tick",
    title: "Երևանի օրվա ռեփ բեմը՝ Անգլիական այգում",
    cardTitle: "Ռեփ՝ Անգլիական այգում",
    titleSeo: "Երևանի օր․ ռեփ համերգ Անգլիական այգում",
    summary: "Երևանի օրվա ռեփ համերգը հոկտեմբերի 10-ին Անգլիական այգում է՝ ժամը 17:00–22:00։ Բեմում կլինեն A Chilla-ն, VNAS-ը, Dav-ը, GALIFE-ը և այլ կատարողներ։",
    start: "2026-10-10",
    startTime: "17:00",
    end: "2026-10-10",
    endTime: "22:00",
    utcOffset: "+04:00",
    city: "Երևան",
    country: "Հայաստան",
    venue: "Անգլիական այգի, Երևան",
    geo: { name: "Անգլիական այգի", lat: 40.1739565, lng: 44.5081189 },
    organizer: "Երևանի քաղաքապետարան",
    tags: ["yerevan-city-day"],
    category: "Համերգներ",
    image: "/covers/yerevan-2808th-anniversary-2026.jpg",
    imageAlt: "Երևանի 2808-ամյակի պաշտոնական պաստառը՝ քաղաքի համերգային ծրագրի համար",
    imageKind: "illustration",
    imageCredit: "Երևանի քաղաքապետարան",
    imageWidth: 523,
    imageHeight: 349,
    source,
    speakersHeading: "Կատարողներ",
    speakers: [{ name: "A Chilla" }, { name: "VNAS" }, { name: "Dav" }, { name: "GALIFE" }, { name: "Narek Mets Hayk" }, { name: "Misht Hasarak" }, { name: "47" }, { name: "Felo" }, { name: "Serjo" }],
    body: [
      "Երևանի օրվա ռեփ բեմը հոկտեմբերի 10-ին Անգլիական այգում է՝ ժամը 17:00–22:00։",
      "Քաղաքային ուղեցույցում նշված կատարողներն են A Chilla-ն, ՎՆԱՍ-ը, ԴԱՎ-ը, GALIFE-ը, Նարեկ Մեծ Հայքը, «Միշտ Հասարակ»-ը, 47-ը, Ֆելոն և Սերժոն։",
    ],
    faq: [{ q: "Ե՞րբ է ռեփ համերգը", a: "Հոկտեմբերի 10-ին՝ ժամը 17:00–22:00։" }, { q: "Որտե՞ղ է ռեփ բեմը", a: "Անգլիական այգում՝ Երևանում։" }],
    i18n: {
      en: {
        title: "Yerevan City Day rap stage at English Park",
        cardTitle: "Rap at English Park",
        titleSeo: "Yerevan City Day: rap concert at English Park",
        summary: "Yerevan City Day's rap concert is at English Park on 10 October, 17:00–22:00, with A Chilla, VNAS, Dav, GALIFE and others.",
        city: "Yerevan",
        country: "Armenia",
        venue: "English Park, Yerevan",
        organizer: "Yerevan Municipality",
        category: "Concerts",
        imageAlt: "Official poster for Yerevan's 2,808th anniversary city programme",
        imageCredit: "Yerevan Municipality",
        speakersHeading: "Performers",
        body: [
          "Yerevan City Day's rap stage is at English Park on 10 October, from 17:00 to 22:00.",
          "The city guide lists A Chilla, VNAS, Dav, GALIFE, Narek Mets Hayk, Misht Hasarak, 47, Felo and Serjo.",
        ],
        faq: [{ q: "When is the rap concert?", a: "On 10 October, from 17:00 to 22:00." }, { q: "Where is the rap stage?", a: "At English Park in Yerevan." }],
      },
    },
  },
  {
    slug: "yerevan-city-day-symphonic-folk-2026",
    createdAt: "2026-10-09T12:00:00+04:00",
    updatedAt: "2026-10-09T12:00:00+04:00",
    site: "tick",
    title: "«Սիմֆոնիկ ֆոլք». Երևանի օրվա դասական համերգը Ազատության հրապարակում",
    cardTitle: "Սիմֆոնիկ ֆոլք՝ Ազատության հրապարակում",
    titleSeo: "Երևանի օր․ Սիմֆոնիկ ֆոլք՝ Ազատության հրապարակում",
    summary: "Երևանի օրվա «Սիմֆոնիկ ֆոլք» համերգը Ազատության հրապարակում է՝ հոկտեմբերի 10-ին, ժամը 17:00–20:30։ Մասնակցում են երկու նվագախումբ և երգչախմբեր։",
    start: "2026-10-10",
    startTime: "17:00",
    end: "2026-10-10",
    endTime: "20:30",
    utcOffset: "+04:00",
    city: "Երևան",
    country: "Հայաստան",
    venue: "Ազատության հրապարակ, Երևան",
    geo: { name: "Ազատության հրապարակ", lat: 40.1853614, lng: 44.5150485 },
    organizer: "Երևանի քաղաքապետարան",
    tags: ["yerevan-city-day"],
    category: "Համերգներ",
    image: "/covers/yerevan-city-day-symphonic-folk-2026.jpg",
    imageAlt: "Visit Yerevan-ի «Սիմֆոնիկ ֆոլք» համերգի պաստառը՝ հոկտեմբերի 10-ի ամսաթվով",
    imageKind: "illustration",
    imageCredit: "Visit Yerevan",
    imageWidth: 1280,
    imageHeight: 720,
    source,
    speakersHeading: "Մասնակիցներ",
    speakers: [{ name: "Երևան երիտասարդական նվագախումբ" }, { name: "Հայաստանի պետական սիմֆոնիկ նվագախումբ" }, { name: "Երևանի պետական կամերային երգչախումբ" }, { name: "Կամերտոն վոկալ ստուդիա" }],
    body: [
      "Երևանի օրվա դասական երաժշտության ծրագիրը հոկտեմբերի 10-ին Ազատության հրապարակում է՝ ժամը 17:00–20:30։",
      "«Սիմֆոնիկ ֆոլք» ծրագրում ելույթ կունենան «Երևան» երիտասարդական նվագախումբը, Հայաստանի պետական սիմֆոնիկ նվագախումբը, Երևանի պետական կամերային երգչախումբը և «Կամերտոն» վոկալ ստուդիան։",
    ],
    faq: [{ q: "Ե՞րբ է «Սիմֆոնիկ ֆոլք» համերգը", a: "Հոկտեմբերի 10-ին՝ ժամը 17:00–20:30։" }, { q: "Որտե՞ղ է համերգը", a: "Ազատության հրապարակում՝ Երևանի օպերայի հարևանությամբ։" }],
    i18n: {
      en: {
        title: "Symphonic Folk: Yerevan City Day concert at Freedom Square",
        cardTitle: "Symphonic Folk at Freedom Square",
        titleSeo: "Yerevan City Day: Symphonic Folk at Freedom Square",
        summary: "The Yerevan City Day Symphonic Folk concert is at Freedom Square on 10 October, 17:00–20:30, with two orchestras and choirs.",
        city: "Yerevan",
        country: "Armenia",
        venue: "Freedom Square, Yerevan",
        organizer: "Yerevan Municipality",
        category: "Concerts",
        imageAlt: "Visit Yerevan poster for the Symphonic Folk concert on 10 October",
        imageCredit: "Visit Yerevan",
        speakersHeading: "Performers",
        body: [
          "Yerevan City Day's classical programme is at Freedom Square on 10 October, from 17:00 to 20:30.",
          "The Symphonic Folk programme features the Yerevan Youth Orchestra, Armenian State Symphony Orchestra, Yerevan State Chamber Choir and Kamerton Vocal Studio.",
        ],
        faq: [{ q: "When is the Symphonic Folk concert?", a: "On 10 October, from 17:00 to 20:30." }, { q: "Where is the concert?", a: "At Freedom Square beside the Yerevan Opera." }],
      },
    },
  },
  {
    slug: "yerevan-city-day-electronic-vanco-2026",
    createdAt: "2026-10-09T12:00:00+04:00",
    updatedAt: "2026-10-09T12:00:00+04:00",
    site: "tick",
    title: "Երևանի օրվա էլեկտրոնային բեմը՝ Vanco-ի մասնակցությամբ",
    cardTitle: "Էլեկտրոնային երաժշտություն․ Vanco՝ 21:30-ին",
    titleSeo: "Երևանի օր․ էլեկտրոնային բեմը Հանրապետության հրապարակում",
    summary: "Երևանի օրվա էլեկտրոնային համերգը Հանրապետության հրապարակում է՝ հոկտեմբերի 10-ին, 17:00–23:00։ Հատուկ հյուր Vanco-ն ելույթ կունենա 21:30-ին։",
    start: "2026-10-10",
    startTime: "17:00",
    end: "2026-10-10",
    endTime: "23:00",
    utcOffset: "+04:00",
    city: "Երևան",
    country: "Հայաստան",
    venue: "Հանրապետության հրապարակ, Երգող շատրվանների մոտ, Երևան",
    geo: { name: "Հանրապետության հրապարակ", lat: 40.1780258, lng: 44.512877 },
    organizer: "Երևանի քաղաքապետարան",
    tags: ["yerevan-city-day"],
    category: "Համերգներ",
    image: "/covers/yerevan-city-day-vanco-2026.jpg",
    imageAlt: "Visit Yerevan-ի էլեկտրոնային բեմի պաստառը՝ Vanco-ի դիմանկարով և 21:30 ելույթի ժամով",
    imageKind: "illustration",
    imageCredit: "Visit Yerevan",
    imageWidth: 1280,
    imageHeight: 720,
    source,
    speakersHeading: "Կատարողներ",
    speakers: [{ name: "Vanco" }, { name: "Guevo Aka Kai" }, { name: "Roob" }, { name: "Socko" }, { name: "Alber Ensso" }],
    body: [
      "Երևանի օրվա էլեկտրոնային բեմը հոկտեմբերի 10-ին Հանրապետության հրապարակում է՝ Երգող շատրվանների հարևանությամբ։ Ծրագիրը սկսվում է ժամը 17:00-ին և շարունակվում մինչև 23:00։",
      "Ելույթ կունենան Guevo Aka Kai-ը, Roob-ը, Socko-ն և Alber Ensso-ն։ Հատուկ հյուր Vanco-ն նվագելու է ժամը 21:30-ին։",
    ],
    faq: [{ q: "Ե՞րբ է Vanco-ի ելույթը Երևանում", a: "Հոկտեմբերի 10-ին՝ ժամը 21:30-ին, Հանրապետության հրապարակի էլեկտրոնային բեմում։" }, { q: "Որտե՞ղ է էլեկտրոնային համերգը", a: "Հանրապետության հրապարակում՝ Երգող շատրվանների մոտ։" }],
    i18n: {
      en: {
        title: "Yerevan City Day electronic stage, with Vanco",
        cardTitle: "Electronic music: Vanco at 21:30",
        titleSeo: "Yerevan City Day: electronic stage at Republic Square",
        summary: "The Yerevan City Day electronic concert is at Republic Square on 10 October, 17:00–23:00. Special guest Vanco performs at 21:30.",
        city: "Yerevan",
        country: "Armenia",
        venue: "Republic Square, by the Singing Fountains, Yerevan",
        organizer: "Yerevan Municipality",
        category: "Concerts",
        imageAlt: "Visit Yerevan poster for the electronic stage, featuring Vanco and his 21:30 set time",
        imageCredit: "Visit Yerevan",
        speakersHeading: "Performers",
        body: [
          "Yerevan City Day's electronic stage is at Republic Square, beside the Singing Fountains, on 10 October. The programme runs from 17:00 to 23:00.",
          "Guevo Aka Kai, Roob, Socko and Alber Ensso are on the line-up. Special guest Vanco is scheduled to play at 21:30.",
        ],
        faq: [{ q: "When does Vanco perform in Yerevan?", a: "At 21:30 on 10 October on the Republic Square electronic stage." }, { q: "Where is the electronic concert?", a: "At Republic Square, beside the Singing Fountains." }],
      },
    },
  },
];
