import type { EventItem } from "../types.ts";

const caf: EventItem["source"] = {
  name: "Cafesjian Center for the Arts",
  url: "https://www.cmf.am/en/exhibitions",
  verifiedOn: "2026-10-09",
};
const gallery: EventItem["source"] = {
  name: "National Gallery of Armenia",
  url: "https://www.gallery.am/en/exhibitions",
  verifiedOn: "2026-10-09",
};

export const items: EventItem[] = [
  {
    slug: "qarpet-cafesjian-yerevan-2026",
    createdAt: "2026-10-09T13:00:00+04:00",
    updatedAt: "2026-10-10T06:20:00+04:00",
    site: "tick",
    title: "«Քարպետ»՝ Ալեքսանդր Նիկիտինի և Դմիտրի Բեկետովի ցուցահանդեսը",
    cardTitle: "«Քարպետ»՝ Կասկադում",
    titleSeo: "Երևանում՝ «Քարպետ» ցուցահանդեսը Գաֆէսճեան կենտրոնում",
    summary:
      "Երևանի Գաֆէսճեան արվեստի կենտրոնում՝ Սասունցի Դավիթ սրահում, ցուցադրվում են խաչքարի և հայկական գորգանախշի ձևերը վերաիմաստավորող չորս քանդակներ՝ մինչև դեկտեմբերի 12-ը։",
    start: "2026-05-16",
    end: "2026-12-12",
    utcOffset: "+04:00",
    city: "Երևան",
    country: "Հայաստան",
    venue: "Գաֆէսճեան արվեստի կենտրոն, Սասունցի Դավիթ սրահ, Թամանյան 10",
    geo: { name: "Գաֆէսճեան արվեստի կենտրոն", lat: 40.1893845, lng: 44.5154178 },
    organizer: "Գաֆէսճեան արվեստի կենտրոն",
    category: "Ցուցահանդեսներ",
    image: "/covers/qarpet-cafesjian-yerevan-2026.jpg",
    imageAlt: "Չորս գունավոր երկրաչափական քանդակ՝ գորգանախշերից ու խաչքարային ձևերից ներշնչված",
    imageKind: "illustration",
    imageCredit: "Tick.am",
    imageWidth: 3072,
    imageHeight: 1728,
    tickets: { priceFrom: 0, currency: "AMD" },
    source: {
      name: "Cafesjian Center for the Arts",
      url: "https://www.cmf.am/en/exhibitions/qarpet",
      verifiedOn: "2026-10-09",
    },
    ticket: { url: "https://www.cmf.am/index.php/en/visit-cca", label: "Այցելության տեղեկություններ" },
    body: [
      "Գաֆէսճեան արվեստի կենտրոնում Ալեքսանդր Նիկիտինն ու Դմիտրի Բեկետովը հայկական գորգի զարդանախշն ու խաչքարի ձևը տեղափոխում են քանդակի նոր լեզու։ «Քարպետ» ցուցադրության չորս մոնումենտալ գործերը Սասունցի Դավիթ սրահում են մինչև <strong>2026 թվականի դեկտեմբերի 12-ը</strong>։",
      "## Ինչ է ցուցադրվում",
      "Նախագիծը չի կրկնօրինակում մեկ որոշակի շրջանի կամ վայրի ավանդական ձևերը։ Հեղինակները միավորում են Արցախի ու Սևանի գորգագործական մոտիվները Սանահինի և Ջուղայի խաչքարային ժառանգության հետ։ Կենտրոնի նկարագրությամբ՝ յուրաքանչյուր քանդակ ունի իր պատմությունը՝ ծիրանենու ծաղկումից մինչև ավելի անձնական ու ինքնամփոփ ճանապարհորդություններ։",
      "## Որտեղ և երբ",
      "Ցուցահանդեսը Գաֆէսճեան կենտրոնի <strong>Սասունցի Դավիթ սրահում</strong> է՝ Թամանյան 10 հասցեում։ Մուտքն անվճար է։ Ցուցասրահների աշխատանքային ժամերը տարբեր են Կասկադի մյուս բաց տարածքների ժամերից․ այցից առաջ ստուգիր կենտրոնի այցելուների էջը։",
    ],
    faq: [
      { q: "Մինչև ե՞րբ է բաց «Քարպետ» ցուցահանդեսը Երևանում։", a: "Մինչև <strong>2026 թվականի դեկտեմբերի 12-ը</strong>՝ Գաֆէսճեան արվեստի կենտրոնի Սասունցի Դավիթ սրահում։" },
      { q: "Ովքե՞ր են «Քարպետ»-ի հեղինակները։", a: "Ալեքսանդր Նիկիտինն ու Դմիտրի Բեկետովը։" },
      { q: "Մուտքն անվճա՞ր է։", a: "Այո։ Գաֆէսճեան արվեստի կենտրոնը հայտնում է, որ մուտքն անվճար է։" },
    ],
    i18n: {
      en: {
        title: "Qarpet: Alexander Nikitin and Dmitry Beketov at Cafesjian",
        cardTitle: "Qarpet at the Cascade",
        titleSeo: "Qarpet in Yerevan: Cafesjian exhibition through 12 December",
        summary:
          "Four sculptural works recast Armenian carpet ornament and khachkar forms at Cafesjian Center for the Arts in Yerevan, through 12 December.",
        venue: "Cafesjian Center for the Arts, Sasuntsi Davit Gallery, 10 Tamanyan Street",
        city: "Yerevan",
        country: "Armenia",
        organizer: "Cafesjian Center for the Arts",
        category: "Exhibitions",
        imageAlt: "Four colourful geometric sculptures reinterpreting Armenian carpet patterns and khachkar forms",
        ticket: { url: "https://www.cmf.am/index.php/en/visit-cca", label: "Visitor information" },
        body: [
          "At the Cafesjian Center for the Arts, Alexander Nikitin and Dmitry Beketov bring Armenian carpet ornament and the form of the khachkar into a new sculptural language. Four monumental works from <em>Qarpet</em> are on view in the Sasuntsi Davit Gallery through <strong>12 December 2026</strong>.",
          "## What is on view",
          "The project reinterprets rather than copies a single local tradition. The artists combine carpet motifs from Artsakh and Lake Sevan with the khachkar heritage of Sanahin and Julfa. The Center says each of the four sculptures has its own narrative, from an apricot tree in blossom to more personal, inward journeys.",
          "## Where and when",
          "The exhibition is in the <strong>Sasuntsi Davit Gallery</strong> at the Cafesjian Center for the Arts, 10 Tamanyan Street. Admission is free. Gallery opening hours differ from the Cascade's outdoor spaces, so check the visitor page before going.",
        ],
        faq: [
          { q: "How long is Qarpet on in Yerevan?", a: "Through <strong>12 December 2026</strong> at the Cafesjian Center for the Arts' Sasuntsi Davit Gallery." },
          { q: "Who made Qarpet?", a: "Artists Alexander Nikitin and Dmitry Beketov." },
          { q: "Is admission free?", a: "Yes. The Cafesjian Center for the Arts lists free admission." },
        ],
      },
    },
  },
  {
    slug: "unfamiliar-city-gagik-ghazanchyan-yerevan-2026",
    createdAt: "2026-10-09T13:00:00+04:00",
    updatedAt: "2026-10-10T06:20:00+04:00",
    site: "tick",
    title: "Գագիկ Ղազանչյանի «Անծանոթ քաղաքը»՝ Կասկադում",
    cardTitle: "«Անծանոթ քաղաքը»",
    titleSeo: "Գագիկ Ղազանչյանի ցուցահանդեսը Երևանում՝ մինչև փետրվարի 28-ը",
    summary:
      "Գագիկ Ղազանչյանի 2024–2026 թվականների նկարներում Երևանի քաղաքային պատկերները երևում են վերացական գունային շերտերի միջից․ ցուցահանդեսը Կասկադի Գաֆէսճեան կենտրոնում է մինչև փետրվարի 28-ը։",
    start: "2026-10-01",
    end: "2027-02-28",
    utcOffset: "+04:00",
    city: "Երևան",
    country: "Հայաստան",
    venue: "Գաֆէսճեան արվեստի կենտրոն, Gallery One, Թամանյան 10",
    geo: { name: "Գաֆէսճեան արվեստի կենտրոն", lat: 40.1893845, lng: 44.5154178 },
    organizer: "Գաֆէսճեան արվեստի կենտրոն",
    category: "Ցուցահանդեսներ",
    image: "/covers/unfamiliar-city-gagik-ghazanchyan-yerevan-2026.jpg",
    imageAlt: "Վերացական նկար՝ բազմագույն շերտերի միջից բացվող Երևանի քաղաքային ուրվագծով",
    imageKind: "illustration",
    imageCredit: "Tick.am",
    imageWidth: 3072,
    imageHeight: 1728,
    tickets: { priceFrom: 0, currency: "AMD" },
    source: {
      name: "Cafesjian Center for the Arts",
      url: "https://www.cmf.am/en/exhibitions/gagik-ghazanchyan-unfamiliar-city",
      verifiedOn: "2026-10-09",
    },
    ticket: { url: "https://www.cmf.am/index.php/en/visit-cca", label: "Այցելության տեղեկություններ" },
    body: [
      "Գագիկ Ղազանչյանի նոր նկարներում ծանոթ քաղաքային միջավայրը միաժամանակ ճանաչելի է ու օտար։ «Անծանոթ քաղաքը» ներառում է <strong>2024–2026 թվականների</strong> գործեր և ցուցադրվում է Կասկադի Գաֆէսճեան արվեստի կենտրոնի Gallery One սրահում մինչև <strong>2027 թվականի փետրվարի 28-ը</strong>։",
      "## Ինչ փնտրել ցուցասրահում",
      "Նկարները սկզբում կարող են թվալ գծերի ու գունային բծերի խիտ դաշտեր։ Դրանց մեջ աստիճանաբար երևում են բարձրահարկ շենքեր ու ամբողջ թաղամասեր՝ տարբեր բարձրություններից ու հեռանկարներից։ Նկարչական մակերեսով անցնող անվադողի հետքերը ֆիզիկական շարժումը դարձնում են պատկեր։",
      "## Ցուցահանդեսի միտքը",
      "Կենտրոնի ներկայացմամբ՝ գործերը հարցնում են, թե ինչ է տեղի ունենում քաղաքի զգացողության հետ, երբ ծանոթ շենքերն ու տարածքները կորցնում են իրենց կայուն իմաստը։ Ցուցահանդեսը նաև մտնում է CYFEST 17-ի <em>Natura Naturans</em> նախագծի շրջանակ՝ քաղաքը դիտարկելով որպես մարդու ստեղծած բնապատկեր։ Մուտքն անվճար է։",
    ],
    faq: [
      { q: "Ե՞րբ է ցուցադրվում «Անծանոթ քաղաքը»։", a: "Մինչև <strong>2027 թվականի փետրվարի 28-ը</strong>՝ Գաֆէսճեան արվեստի կենտրոնի Gallery One սրահում։" },
      { q: "Ի՞նչ է ներկայացնում Գագիկ Ղազանչյանը։", a: "2024–2026 թվականների գործեր, որտեղ բազմագույն շերտերի միջից երևում են քաղաքային պատկերներ ու բարձրահարկ թաղամասեր։" },
      { q: "Որտե՞ղ է ցուցահանդեսը։", a: "Կասկադում՝ Գաֆէսճեան արվեստի կենտրոնի Gallery One-ում, Թամանյան 10 հասցեում։" },
    ],
    i18n: {
      en: {
        title: "Gagik Ghazanchyan: unFamiliar City at the Cafesjian Center",
        cardTitle: "unFamiliar City",
        titleSeo: "Ghazanchyan's unFamiliar City in Yerevan, until February",
        summary:
          "City fragments emerge from abstract, layered paintings in Gagik Ghazanchyan's 2024–26 work, at Cafesjian Center for the Arts in Yerevan through 28 February.",
        venue: "Cafesjian Center for the Arts, Gallery One, 10 Tamanyan Street",
        city: "Yerevan",
        country: "Armenia",
        organizer: "Cafesjian Center for the Arts",
        category: "Exhibitions",
        imageAlt: "An abstract painting with a city outline emerging through layers of colour",
        ticket: { url: "https://www.cmf.am/index.php/en/visit-cca", label: "Visitor information" },
        body: [
          "In Gagik Ghazanchyan's new paintings, a city can look familiar and strange at once. <em>unFamiliar City</em> brings together works from <strong>2024–2026</strong> at Gallery One in Yerevan's Cafesjian Center for the Arts through <strong>28 February 2027</strong>.",
          "## What to look for in the gallery",
          "The paintings can first read as dense fields of lines and colour. Then fragments of buildings and whole high-rise districts emerge, seen from shifting heights and angles. Tire marks across the painted surface turn physical movement into another kind of image.",
          "## The exhibition's idea",
          "The Center frames the work around what happens to a city's felt identity when familiar buildings and places lose stable meaning. The exhibition is also part of CYFEST 17's <em>Natura Naturans</em>, which considers the city as a human-made landscape. Admission is free.",
        ],
        faq: [
          { q: "When is unFamiliar City on?", a: "Through <strong>28 February 2027</strong> at Gallery One, Cafesjian Center for the Arts." },
          { q: "What does Gagik Ghazanchyan show?", a: "Works from 2024–2026 in which city imagery and high-rise districts emerge through layered abstract painting." },
          { q: "Where is the exhibition in Yerevan?", a: "Gallery One at the Cafesjian Center for the Arts, 10 Tamanyan Street, in the Cascade." },
        ],
      },
    },
  },
  {
    slug: "cyfest-17-yerevan-2026",
    createdAt: "2026-10-09T13:00:00+04:00",
    updatedAt: "2026-10-10T06:20:00+04:00",
    site: "tick",
    title: "CYFEST 17 Երևանում․ «Բնություն արարող բնությունը»",
    cardTitle: "CYFEST 17՝ Կասկադում",
    titleSeo: "CYFEST 17 Երևանում․ մեդիաարվեստի ցուցահանդեսը Կասկադում",
    summary:
      "Երևանի Կասկադում մեդիաարվեստի միջազգային փառատոնը միավորում է ավելի քան 35 արվեստագետի․ CYFEST 17-ը Գաֆէսճեան կենտրոնում է հոկտեմբերի 15-ից մինչև հունվարի 17-ը։",
    start: "2026-10-15",
    end: "2027-01-17",
    utcOffset: "+04:00",
    city: "Երևան",
    country: "Հայաստան",
    venue: "Գաֆէսճեան արվեստի կենտրոն, Թամանյան 10",
    geo: { name: "Գաֆէսճեան արվեստի կենտրոն", lat: 40.1893845, lng: 44.5154178 },
    organizer: "CYLAND Foundation և Գաֆէսճեան արվեստի կենտրոն",
    category: "Ցուցահանդեսներ",
    image: "/covers/cyfest-17-yerevan-2026.jpg",
    imageAlt: "Լուսային ալիքներ ու թվային բնապատկեր Կասկադի աստիճանների վրա",
    imageKind: "illustration",
    imageCredit: "Tick.am",
    imageWidth: 3072,
    imageHeight: 1728,
    tickets: { priceFrom: 0, currency: "AMD" },
    source: {
      name: "CYFEST",
      url: "https://www.cyfest.art/cyfest-17-yerevan",
      verifiedOn: "2026-10-09",
    },
    ticket: { url: "https://www.cyfest.art/cyfest-17-yerevan", label: "Փառատոնի ծրագիր" },
    body: [
      "CYFEST 17-ը <strong>հոկտեմբերի 15-ից մինչև 2027 թվականի հունվարի 17-ը</strong> Կասկադում ներկայացնում է մեդիաարվեստի միջազգային ցուցահանդես։ <em>Natura Naturans․ Մարդիկ, բնություն, բնապատկեր</em> խորագրով ծրագիրը համախմբում է ավելի քան <strong>35 միջազգային արվեստագետի</strong>։",
      "## Ինչ է ուսումնասիրում ցուցահանդեսը",
      "Աշխատանքները անդրադառնում են բնական ու տեխնոլոգիական ուժերին, որոնք ազդում են մեր ընկալման վրա՝ արևի լույսից և երկրաբանական նյութերից մինչև մագնիսական դաշտեր ու էլեկտրամագնիսական ազդանշաններ։ Ցուցադրությունը կապում է մեդիաարվեստը Օրգանական դպրոցի ժառանգության և Կասկադի ճարտարապետության հետ։",
      "## Բացումը և ծրագիրը",
      "Բացման արարողությունը հոկտեմբերի <strong>15-ին, ժամը 18:00-ին</strong> է՝ Գաֆէսճեան արվեստի կենտրոնում։ Փառատոնի բացման շաբաթը ներառում է կատարումներ, վիդեոցուցադրություններ, քննարկումներ և հնչյունային ծրագիր։ Տոմսերի կամ առանձին միջոցառումների ամրագրման պահանջը ստուգիր պաշտոնական ծրագրում։ Կենտրոնի ցուցասրահների մուտքն անվճար է, աշխատանքային ժամերը՝ ուրբաթից կիրակի 10:00–20:00։",
    ],
    faq: [
      { q: "Ե՞րբ է CYFEST 17-ը Երևանում։", a: "2026 թվականի հոկտեմբերի 15-ից մինչև 2027 թվականի հունվարի 17-ը։ Բացումը հոկտեմբերի 15-ին՝ 18:00-ին։" },
      { q: "Որտե՞ղ է անցկացվում փառատոնը։", a: "Գաֆէսճեան արվեստի կենտրոնում՝ Կասկադում, Թամանյան 10 հասցեում։" },
      { q: "Ի՞նչ միջոցառումներ կան ցուցահանդեսից բացի։", a: "Կատարումներ, վիդեոցուցադրություններ, քննարկումներ ու հնչյունային ծրագիր․ որոշ միջոցառումների համար կարող են լինել առանձին ամրագրման պայմաններ։" },
    ],
    i18n: {
      en: {
        title: "CYFEST 17 Yerevan: Natura Naturans at the Cascade",
        cardTitle: "CYFEST 17 at the Cascade",
        titleSeo: "CYFEST 17 in Yerevan: media art at the Cascade",
        summary:
          "More than 35 artists bring international media art to the Cascade: CYFEST 17 runs at Cafesjian Center for the Arts in Yerevan from 15 October to 17 January.",
        venue: "Cafesjian Center for the Arts, 10 Tamanyan Street",
        city: "Yerevan",
        country: "Armenia",
        organizer: "CYLAND Foundation and Cafesjian Center for the Arts",
        category: "Exhibitions",
        imageAlt: "Light waves and a digital landscape across the Cascade steps",
        ticket: { url: "https://www.cyfest.art/cyfest-17-yerevan", label: "Festival programme" },
        body: [
          "CYFEST 17 brings an international media-art exhibition to the Cascade from <strong>15 October 2026 to 17 January 2027</strong>. <em>Natura Naturans: Human Beings, Nature, Landscape</em> brings together more than <strong>35 international artists</strong> at the Cafesjian Center for the Arts.",
          "## What the exhibition explores",
          "The works consider the natural and technological forces that shape perception, from sunlight and geological matter to magnetic fields and electromagnetic signals. The programme puts media art in conversation with the legacy of the Organic School and the architecture of the Cascade.",
          "## Opening and public programme",
          "The opening reception is on <strong>15 October at 6pm</strong> at the Cafesjian Center for the Arts. Opening week includes performances, video screenings, discussions and a sound programme. Check CYFEST's official programme for booking requirements for individual events. The Center's exhibition galleries are free to enter and open Friday to Sunday, 10am–8pm.",
        ],
        faq: [
          { q: "When is CYFEST 17 in Yerevan?", a: "From 15 October 2026 to 17 January 2027. The opening reception is on 15 October at 6pm." },
          { q: "Where is the festival?", a: "At the Cafesjian Center for the Arts in the Cascade, 10 Tamanyan Street, Yerevan." },
          { q: "What else is on besides the exhibition?", a: "Performances, video screenings, discussions and a sound programme. Individual events may have separate booking requirements." },
        ],
      },
    },
  },
  {
    slug: "face-of-humanity-surenyants-national-gallery-2026",
    createdAt: "2026-10-09T13:00:00+04:00",
    updatedAt: "2026-10-10T06:20:00+04:00",
    site: "tick",
    title: "«Մարդկային դեմքը»․ Վարդգես Սուրենյանցը ազգային պատկերասրահում",
    cardTitle: "Վարդգես Սուրենյանց՝ պատկերասրահում",
    titleSeo: "Սուրենյանցի «Մարդկային դեմքը»՝ Երևանում մինչև փետրվարի 17-ը",
    summary:
      "Երևանի Հայաստանի ազգային պատկերասրահում առաջին անգամ հայրենիքում ցուցադրվում է Սուրենյանցի «Լքյալը» կտավը՝ երեք մեծածավալ գործերի հետ․ ցուցահանդեսը բաց է մինչև փետրվարի 17-ը։",
    start: "2026-09-17",
    end: "2027-02-17",
    utcOffset: "+04:00",
    city: "Երևան",
    country: "Հայաստան",
    venue: "Հայաստանի ազգային պատկերասրահ, Արամի 1",
    geo: { name: "Հայաստանի ազգային պատկերասրահ", lat: 40.1780258, lng: 44.512877 },
    organizer: "Հայաստանի ազգային պատկերասրահ",
    category: "Ցուցահանդեսներ",
    image: "/covers/face-of-humanity-surenyants-yerevan-2026.jpg",
    imageAlt: "Երեք թանգարանային շրջանակ՝ մարդկային կերպարների ուրվագծերով, ոսկեգույն պատի վրա",
    imageKind: "illustration",
    imageCredit: "Tick.am",
    imageWidth: 3072,
    imageHeight: 1728,
    source: {
      name: "National Gallery of Armenia",
      url: "https://www.gallery.am/en/the-face-of-humanity-2026-09-17-2027-02-17",
      verifiedOn: "2026-10-09",
    },
    ticket: { url: "https://www.gallery.am/en/the-face-of-humanity-2026-09-17-2027-02-17", label: "Ցուցահանդեսի տեղեկություններ" },
    body: [
      "Վարդգես Սուրենյանցի «Լքյալը» կտավը 1894 թվականից ի վեր առաջին անգամ ցուցադրվում է Հայաստանում՝ Ղազախստանի Աբիլխան Կաստեևի անվան արվեստի ազգային թանգարանից բացառիկ փոխառությամբ։ Այն Հայաստանի ազգային պատկերասրահի «Մարդկային դեմքը․ Սուրենյանցի «Լքյալը» և հումանիստական արվեստը» ցուցահանդեսի կենտրոնական գործն է, որը բաց է մինչև <strong>2027 թվականի փետրվարի 17-ը</strong>։",
      "## Երեք մեծ կտավ՝ մեկ սրահում",
      "«Լքյալը» միավորվում է Սուրենյանցի երկու այլ մոնումենտալ գործերի՝ «Պղծված սրբարանի» (1895) և «Կոտորածից հետո»-ի (1898) հետ։ Ցուցահանդեսում ներառված են նաև Փանոս Թերլեմեզյանի, Սարգիս Խաչատուրյանի, Մարիամ Ասլամազյանի և այլ արվեստագետների աշխատանքներ։",
      "## Այցի տեղեկություններ",
      "Ցուցահանդեսը Հայաստանի ազգային պատկերասրահում է՝ Արամի 1 հասցեում։ Պատկերասրահը երկուշաբթի փակ է, իսկ տոմսարկղը փակվում է աշխատանքային օրվա ավարտից 45 րոպե առաջ։ Մուտքի գործող գինը ստուգիր պատկերասրահի տոմսերի հղումով։",
    ],
    faq: [
      { q: "Մինչև ե՞րբ է բաց Սուրենյանցի ցուցահանդեսը։", a: "Մինչև <strong>2027 թվականի փետրվարի 17-ը</strong>՝ Հայաստանի ազգային պատկերասրահում։" },
      { q: "Ո՞ր գործն է ցուցադրվում առաջին անգամ Հայաստանում։", a: "Վարդգես Սուրենյանցի <em>Լքյալը</em> (1894) կտավը՝ Ղազախստանի Աբիլխան Կաստեևի անվան արվեստի ազգային թանգարանից փոխառությամբ։" },
      { q: "Որտե՞ղ է Հայաստանի ազգային պատկերասրահը։", a: "Արամի 1 հասցեում՝ Երևանի Հանրապետության հրապարակի հարևանությամբ։" },
    ],
    i18n: {
      en: {
        title: "The Face of Humanity: Vardges Sureniants at the National Gallery",
        cardTitle: "Sureniants at the National Gallery",
        titleSeo: "Sureniants in Yerevan: The Face of Humanity to 17 Feb",
        summary:
          "The Abandoned returns to Armenia for the first time in over 130 years, alongside two monumental Sureniants paintings at Yerevan's National Gallery through 17 February.",
        venue: "National Gallery of Armenia, 1 Aram Street",
        city: "Yerevan",
        country: "Armenia",
        organizer: "National Gallery of Armenia",
        category: "Exhibitions",
        imageAlt: "Three museum frames with human figures outlined on a gold-coloured wall",
        ticket: { url: "https://www.gallery.am/en/the-face-of-humanity-2026-09-17-2027-02-17", label: "Exhibition information" },
        body: [
          "Vardges Sureniants' <em>The Abandoned</em> (1894) is on view in Armenia for the first time, on loan from Kazakhstan's Abylkhan Kasteyev National Museum of Arts. It anchors <em>The Face of Humanity: Sureniants' Abandoned and Humanist Art</em> at the National Gallery of Armenia through <strong>17 February 2027</strong>.",
          "## Three monumental paintings together",
          "<em>The Abandoned</em> is shown alongside two other large Sureniants works: <em>Desecrated Sanctity</em> (1895) and <em>After the Massacre</em> (1898). The exhibition also includes works by Panos Terlemezian, Sarkis Katchadourian, Mariam Aslamazyan and other artists.",
          "## Visiting information",
          "The exhibition is at the National Gallery of Armenia, 1 Aram Street. The Gallery is closed on Mondays; its ticket office closes 45 minutes before the end of the working day. Check the Gallery's ticket link for current admission prices.",
        ],
        faq: [
          { q: "How long is The Face of Humanity on?", a: "Through <strong>17 February 2027</strong> at the National Gallery of Armenia in Yerevan." },
          { q: "Which Sureniants painting is being shown in Armenia for the first time?", a: "<em>The Abandoned</em> (1894), on loan from Kazakhstan's Abylkhan Kasteyev National Museum of Arts." },
          { q: "Where is the National Gallery of Armenia?", a: "At 1 Aram Street, beside Republic Square in central Yerevan." },
        ],
      },
    },
  },
];
