import type { EventItem } from "../types.ts";

// tick publishes in Armenian first and English second: each entry is
// written in Armenian and carries its English in `i18n.en` — see
// `localize` in ../i18n.ts. One entry, one slug, one set of facts; the
// English page is the same page in another language, and both are dated by
// the same `updatedAt`.
//
// Prices are in drams as the box office publishes them. Every date here was
// read off Tomsarkgh, Yerevan's main box office, on the day in `verifiedOn`.

export const items: EventItem[] = [

  {
    slug: "elgar-enigma-variations-yerevan-2026",
    createdAt: "2026-10-04T15:00:00+04:00",
    updatedAt: "2026-10-04T15:00:00+04:00",
    site: "tick",
    title: "Էլգար. Թավջութակի կոնցերտ և «Էնիգմա» վարիացիաներ",
    cardTitle: "Էլգար՝ «Էնիգմա» վարիացիաներ",
    summary:
      "Հոկտեմբերի 5-ին Երևանում՝ Արամ Խաչատրյան համերգասրահում, Հայաստանի պետական սիմֆոնիկ նվագախումբը նվագում է Էլգար. մենակատարը թավջութակահար Գայ Ջոնսթոնն է։",
    start: "2026-10-05",
    startTime: "19:30",
    utcOffset: "+04:00",
    city: "Երևան",
    country: "Հայաստան",
    venue: "Արամ Խաչատրյան համերգասրահ, Մաշտոցի պող. 46",
    geo: { lat: 40.1862685, lng: 44.5151091 },
    organizer: "Հայաստանի պետական սիմֆոնիկ նվագախումբ",
    image: "/covers/elgar-enigma-variations-yerevan-2026.jpg",
    imageAlt: "Կարմիր թավջութակ՝ կանգնած նոտակալի կողքին, ծիրանագույն ֆոնի վրա",
    imageKind: "generated",
    imageWidth: 1536,
    imageHeight: 864,
    category: "Դասական երաժշտություն",
    tickets: { priceFrom: 3000, priceTo: 15000, currency: "AMD" },
    ticket: { url: "https://www.tomsarkgh.am/en/event/51330/", label: "Տոմսեր" },
    source: { name: "Tomsarkgh", url: "https://www.tomsarkgh.am/en/event/51330/", verifiedOn: "2026-10-04" },
    body: [
      "Հոկտեմբերի 5-ի երեկոն ամբողջությամբ Էդվարդ Էլգարինն է։ Հայաստանի պետական սիմֆոնիկ նվագախումբը նվագում է նրա երկու ամենասիրված ստեղծագործությունները՝ Թավջութակի կոնցերտը մի մինոր և «Էնիգմա» վարիացիաները։",
      "Մենակատարը բրիտանացի թավջութակահար Գայ Ջոնսթոնն է, դիրիժորը՝ Մարիոս Պապադոպուլոսը։ Համերգը «Հայաստան–Միացյալ Թագավորություն բիզնես համաժողով 2026»-ի մշակութային մասն է, բայց տոմսերը բաց վաճառքում են։",
      "## Ծրագիրը",
      "Առաջին բաժնում՝ Թավջութակի կոնցերտը, երկ 85 (մոտ 35 րոպե)։ Ընդմիջումից հետո՝ «Էնիգմա» վարիացիաները, երկ 36 (մոտ 38 րոպե)։",
      "Երեխաների մուտքը՝ 6 տարեկանից։",
    ],
    faq: [
      { q: "Որքա՞ն արժե տոմսը", a: "Տոմսերը 3000-ից 15000 դրամ են՝ կախված նստատեղից, և վաճառվում են Tomsarkgh-ում։" },
      { q: "Կարելի՞ է գալ երեխաների հետ", a: "Այո, 6 տարեկանից։" },
      { q: "Որքա՞ն է տևում համերգը", a: "Երաժշտությունը մոտ 73 րոպե է՝ երկու մասով, որոնց միջև ընդմիջում կա։" },
    ],
    i18n: {
      en: {
        imageAlt: "A red cello standing beside a music stand on an apricot ground",
        ticket: { url: "https://www.tomsarkgh.am/en/event/51330/", label: "Tickets" },
        title: "Elgar: Cello Concerto and Enigma Variations",
        cardTitle: "Elgar: the Enigma Variations",
        summary:
          "Elgar in Yerevan on 5 October: the Armenian State Symphony Orchestra at the Aram Khachaturian Concert Hall, with Guy Johnston as soloist in the Cello Concerto.",
        city: "Yerevan",
        country: "Armenia",
        venue: "Aram Khachaturian Concert Hall, 46 Mashtots Avenue",
        organizer: "Armenian State Symphony Orchestra",
        category: "Classical",
        body: [
          "An evening given over entirely to Edward Elgar. The Armenian State Symphony Orchestra plays the composer's two best-loved works: the Cello Concerto in E minor and the Enigma Variations.",
          "The British cellist Guy Johnston is the soloist and Marios Papadopoulos conducts. The concert is the cultural half of the Armenia–UK Business Forum 2026, but the tickets are on general sale, and one needn't have a lanyard to attend.",
          "## The programme",
          "First half: the Cello Concerto, Op. 85 (about 35 minutes). After the interval: the Enigma Variations, Op. 36 (about 38 minutes).",
          "Children are admitted from the age of six.",
        ],
        faq: [
          { q: "How much are tickets?", a: "From 3,000 to 15,000 drams depending on the seat, on sale at Tomsarkgh." },
          { q: "Can children come?", a: "Yes, from the age of six." },
          { q: "How long is the concert?", a: "About 73 minutes of music, in two halves with an interval between them." },
        ],
      },
    },
  },

  {
    slug: "macbeth-chamber-theatre-yerevan-2026",
    createdAt: "2026-10-04T20:00:00+04:00",
    updatedAt: "2026-10-04T20:00:00+04:00",
    site: "tick",
    title: "«Մակբեթ»՝ Երևանի պետական կամերային թատրոնում",
    cardTitle: "«Մակբեթ»՝ Կամերային թատրոնում",
    summary:
      "Շեքսպիրի «Մակբեթը» Երևանում՝ հոկտեմբերի 7-ին Կամերային թատրոնում, անգլիացի ռեժիսոր Էլիոթ Հաքսթբլի բեմադրությամբ. Մակբեթ՝ Վահե Զիրոյան, Լեդի Մակբեթ՝ Սոնա Մաթևոսյան։",
    start: "2026-10-07",
    startTime: "19:00",
    utcOffset: "+04:00",
    city: "Երևան",
    country: "Հայաստան",
    venue: "Երևանի պետական կամերային թատրոն, Մաշտոցի պող. 58",
    organizer: "Երևանի պետական կամերային թատրոն",
    image: "/covers/macbeth-chamber-theatre-yerevan-2026.jpg",
    imageAlt: "Մուգ թագ դատարկ բեմի վրա՝ երկու մերկ ծառի միջև, մարջանագույն ֆոնի վրա",
    imageKind: "generated",
    imageWidth: 1536,
    imageHeight: 864,
    category: "Թատրոն",
    tickets: { priceFrom: 3000, priceTo: 8000, currency: "AMD" },
    ticket: { url: "https://www.tomsarkgh.am/en/event/50927/", label: "Տոմսեր" },
    source: { name: "Tomsarkgh", url: "https://www.tomsarkgh.am/en/event/50927/", verifiedOn: "2026-10-04" },
    body: [
      "Երևանի պետական կամերային թատրոնը ներկայացնում է Շեքսպիրի «Մակբեթը» անգլիացի ռեժիսոր Էլիոթ Հաքսթբլի բեմադրությամբ. նա Մեծ Բրիտանիայի Քենթերբերիի շեքսպիրյան փառատոնի գեղարվեստական ղեկավարն է։",
      "Ադապտացիան Շարլոթ Գրումբրիջինն է, թարգմանությունը՝ Հասմիկ Հարությունյանի (Հասմիկ Սեյմոր), երաժշտությունը՝ Վահե Գրիգորյանի, կոստյումները՝ Գայանե Բայաթյանի։",
      "## Դերերում",
      "Մակբեթ՝ Վահե Զիրոյան, Լեդի Մակբեթ՝ Սոնա Մաթևոսյան, Դանքըն և Մալքոմ՝ Ավետ Զոհրաբյան, Բանքո և Սիվըրդ Կրտսեր՝ Մհեր Ալաբեգյան, Մաքդաֆ՝ Սուրեն Պողոսյան։ Վհուկներին խաղում են Մոհանան, Էվա Խաչատրյանը և Վիկտորյա Սահակյանը։",
      "## Ինչպիսի բեմադրություն է",
      "Թատրոնի խոսքով՝ սա ողբերգության ժամանակակից ընթերցում է՝ մինիմալիստական բեմանկարչությամբ, որտեղ առանձնահատուկ տեղ ունեն վհուկները։ Հոկտեմբերի 7-ին, ժամը 19:00-ին. տոմսերը 3000-ից 8000 դրամ են։",
    ],
    faq: [
      { q: "Որքա՞ն արժե տոմսը", a: "3000-ից 8000 դրամ՝ կախված նստատեղից։" },
      { q: "Ո՞վ է բեմադրել", a: "Անգլիացի ռեժիսոր Էլիոթ Հաքսթբլը՝ Քենթերբերիի շեքսպիրյան փառատոնի գեղարվեստական ղեկավարը։" },
      { q: "Ի՞նչ լեզվով է ներկայացումը", a: "Հայերեն՝ Հասմիկ Հարությունյանի (Հասմիկ Սեյմոր) թարգմանությամբ։" },
    ],
    i18n: {
      en: {
        imageAlt: "A dark crown on a bare stage between two leafless trees, on a coral ground",
        ticket: { url: "https://www.tomsarkgh.am/en/event/50927/", label: "Tickets" },
        title: "Macbeth at the Yerevan State Chamber Theatre",
        cardTitle: "Macbeth at the Chamber Theatre",
        summary:
          "Shakespeare's Macbeth in Yerevan on 7 October, staged at the Chamber Theatre by the English director Elliot Huxtable, with Vahe Ziroyan and Sona Matevosyan as the Macbeths.",
        city: "Yerevan",
        country: "Armenia",
        venue: "Yerevan State Chamber Theatre, 58 Mashtots Avenue",
        organizer: "Yerevan State Chamber Theatre",
        category: "Theatre",
        body: [
          "The Yerevan State Chamber Theatre plays Shakespeare's Macbeth in a staging by the English director Elliot Huxtable, artistic director of the Canterbury Shakespeare Festival.",
          "The adaptation is by Charlotte Groombridge and the translation by Hasmik Harutyunyan (Hasmik Seymour); the music is Vahe Grigoryan's and the costumes Gayane Bayatyan's.",
          "## The cast",
          "Vahe Ziroyan is Macbeth and Sona Matevosyan Lady Macbeth; Avet Zohrabyan doubles Duncan and Malcolm, Mher Alabegyan Banquo and Young Siward, and Suren Poghosyan plays Macduff. The witches are Mohana, Eva Khachatryan and Viktorya Sahakyan.",
          "## The production",
          "The theatre calls it a modern reading of the tragedy, minimal in its design, with the witches steering events — one rather suspects they always were. 7 October at 19:00, with tickets from 3,000 to 8,000 drams.",
        ],
        faq: [
          { q: "How much are tickets?", a: "From 3,000 to 8,000 drams depending on the seat." },
          { q: "Who directs it?", a: "The English director Elliot Huxtable, artistic director of the Canterbury Shakespeare Festival." },
          { q: "What language is it in?", a: "Armenian, in Hasmik Harutyunyan's (Hasmik Seymour's) translation." },
        ],
      },
    },
  },

  {
    slug: "harry-potter-film-music-yerevan-2026",
    createdAt: "2026-10-04T15:00:00+04:00",
    updatedAt: "2026-10-04T15:00:00+04:00",
    site: "tick",
    title: "Հարի Փոթեր ֆիլմի երաժշտությունը՝ Mystery Ensemble",
    cardTitle: "Հարի Փոթերի երաժշտությունը",
    summary:
      "Հարի Փոթերի ֆիլմերի երաժշտությունը Երևանում՝ Կոմիտասի անվան կամերային երաժշտության տանը, հոկտեմբերի 9-ին և դեկտեմբերի 4-ին. նվագում է Mystery Ensemble-ը։",
    start: "2026-10-09",
    startTime: "19:00",
    utcOffset: "+04:00",
    city: "Երևան",
    country: "Հայաստան",
    venue: "Կոմիտասի անվան կամերային երաժշտության տուն, Իսահակյան 1",
    geo: { lat: 40.1854319, lng: 44.5232134 },
    organizer: "Red Events",
    image: "/covers/harry-potter-film-music-yerevan-2026.jpg",
    imageAlt: "Դիրիժորական փայտիկ՝ անկյունագծով, փոքրիկ մոմերի շարքի վերևում",
    imageKind: "generated",
    imageWidth: 1536,
    imageHeight: 864,
    category: "Համերգներ",
    tickets: { priceFrom: 8300, priceTo: 13700, currency: "AMD" },
    ticket: { url: "https://www.tomsarkgh.am/en/event/47386/", label: "Տոմսեր" },
    source: { name: "Tomsarkgh", url: "https://www.tomsarkgh.am/en/event/47386/", verifiedOn: "2026-10-04" },
    body: [
      "Ջոն Ուիլյամսի «Հեդվիգի թեման» և Հարի Փոթերի ֆիլմաշարի մյուս թեմաները կհնչեն ոչ թե կինոդահլիճում, այլ Կոմիտասի անվան կամերային երաժշտության տանը։ Նվագում է Mystery Ensemble-ը՝ ակուստիկ լարայիններ, ստեղնաշարային գործիքներ և հարվածայիններ։",
      "Երկու երեկո կա՝ հոկտեմբերի 9-ին և դեկտեմբերի 4-ին, երկուսն էլ ժամը 19:00-ին։ Կազմակերպիչը Red Events-ն է, որը նման համերգներ անցկացնում է առանձնատներում, տանիքներում և ջերմոցներում։",
      "## Ի՞նչ կհնչի",
      "Ծրագրում՝ Hedwig’s Theme, Hogwarts March, Lily’s Theme, Harry in Winter, Dumbledore’s Army, Double Trouble և Flight of the Order of the Phoenix՝ ընդհանուր քսան թեմա։ Կազմակերպիչը նախազգուշացնում է, որ ծրագրում հնարավոր են փոփոխություններ։",
    ],
    faq: [
      { q: "Որքա՞ն արժե տոմսը", a: "Տոմսերը երեք գնով են՝ 8300, 9700 և 13700 դրամ։" },
      { q: "Ե՞րբ է համերգը", a: "Հոկտեմբերի 9-ին և դեկտեմբերի 4-ին, ժամը 19:00-ին։" },
    ],
    i18n: {
      en: {
        imageAlt: "A conductor's baton laid on a diagonal above a long row of small candles",
        ticket: { url: "https://www.tomsarkgh.am/en/event/47386/", label: "Tickets" },
        title: "Harry Potter film music by the Mystery Ensemble",
        cardTitle: "Harry Potter film music",
        summary:
          "The Harry Potter scores in Yerevan, played by the Mystery Ensemble at the Komitas Chamber Music House on 9 October and again on 4 December.",
        city: "Yerevan",
        country: "Armenia",
        venue: "Komitas Chamber Music House, 1 Isahakyan Street",
        organizer: "Red Events",
        category: "Concerts",
        body: [
          "John Williams's Hedwig's Theme and the rest of the Harry Potter scores, in a chamber music hall rather than a cinema — a rather more civilised way to hear them. The Mystery Ensemble plays them on acoustic strings, keyboards and percussion.",
          "There are two evenings, 9 October and 4 December, both at 19:00. The organiser is Red Events, who stage concerts of this sort in old mansions, on rooftops and in glasshouses.",
          "## What is played",
          "Hedwig's Theme, Hogwarts March, Lily's Theme, Harry in Winter, Dumbledore's Army, Double Trouble and Flight of the Order of the Phoenix, among twenty themes in all. The organiser notes that the programme may change.",
        ],
        faq: [
          { q: "How much are tickets?", a: "There are three prices: 8,300, 9,700 and 13,700 drams." },
          { q: "When is it?", a: "On 9 October and on 4 December, at 19:00 both evenings." },
        ],
      },
    },
  },

  {
    slug: "equinox-fest-autumn-chapter-2026",
    createdAt: "2026-10-04T15:00:00+04:00",
    updatedAt: "2026-10-04T15:00:00+04:00",
    site: "tick",
    title: "EQUINOX Fest. աշնանային էպիզոդ Altezza-ում",
    cardTitle: "EQUINOX Fest. աշնանային էպիզոդ",
    summary:
      "Հոկտեմբերի 17-ին Երևանի մոտ՝ Altezza ուղղաթիռային հրապարակում, էլեկտրոնային և կենդանի երաժշտության փառատոն է՝ Արմեն Միրան, Վիկեն Արման, Արտո Թունչբոյաջյան։",
    start: "2026-10-17",
    startTime: "18:00",
    endTime: "23:00",
    utcOffset: "+04:00",
    city: "Ջրվեժ",
    country: "Հայաստան",
    venue: "Altezza by Armenian Helicopters, Երևան–Գառնի մայրուղի 6/14",
    geo: { lat: 40.1841367, lng: 44.6168316 },
    image: "/covers/equinox-fest-autumn-chapter-2026.jpg",
    imageAlt: "Կլոր հարթակ բլուրների մեջ, երկինքը կիսված է ցերեկվա և գիշերվա կեսերի՝ լուսնով",
    imageKind: "generated",
    imageWidth: 1536,
    imageHeight: 864,
    category: "Փառատոներ",
    tickets: { priceFrom: 15000, priceTo: 18000, currency: "AMD", salesEnd: "2026-10-17" },
    ticket: { url: "https://www.tomsarkgh.am/en/event/51317/", label: "Տոմսեր" },
    source: { name: "Tomsarkgh", url: "https://www.tomsarkgh.am/en/event/51317/", verifiedOn: "2026-10-04" },
    speakersHeading: "Կատարողներ",
    speakers: [
      { name: "Արմեն Միրան" },
      { name: "Hraach" },
      { name: "Վիկեն Արման" },
      { name: "Արտո Թունչբոյաջյան" },
      { name: "Արտյոմ Մանուկյան" },
      { name: "Շահեն Խանդկարյան" },
      { name: "Արամ Չախոյան", note: "Հատուկ հյուր" },
    ],
    body: [
      "EQUINOX-ը էլեկտրոնային բեմի և կենդանի կատարման համադրության փառատոն է, և աշնանային էպիզոդն այս անգամ տեղափոխվում է ուղղաթիռային հրապարակ՝ Altezza, Ջրվեժում, Երևան–Գառնի մայրուղու վրա։",
      "Մուտքը բացվում է ժամը 16:00-ին, երաժշտությունը՝ 18:00-ից 23:00։",
      "## Տոմսերը",
      "Մինչև հոկտեմբերի 10-ը տոմսն արժե 15000 դրամ, հոկտեմբերի 11-ից 17-ը՝ 18000 դրամ։ Վաղ վաճառքի 10000 դրամանոց տոմսերն ավարտվել են սեպտեմբերի 5-ին։",
    ],
    faq: [
      { q: "Որքա՞ն արժե տոմսը", a: "15000 դրամ մինչև հոկտեմբերի 10-ը, 18000 դրամ՝ հոկտեմբերի 11-ից 17-ը։" },
      { q: "Ե՞րբ է բացվում մուտքը", a: "Ժամը 16:00-ին. երաժշտությունը սկսվում է 18:00-ին և ավարտվում 23:00-ին։" },
      { q: "Որտե՞ղ է Altezza-ն", a: "Ջրվեժում՝ Armenian Helicopters ուղղաթիռային հրապարակում, Երևան–Գառնի մայրուղի 6/14։" },
    ],
    i18n: {
      en: {
        imageAlt: "A round platform among the hills under a sky split into a day half and a night half with a moon",
        ticket: { url: "https://www.tomsarkgh.am/en/event/51317/", label: "Tickets" },
        title: "EQUINOX Fest: Autumn Chapter at Altezza",
        cardTitle: "EQUINOX Fest: Autumn Chapter",
        summary:
          "An electronic and live-music festival on a helipad just outside Yerevan on 17 October, with Armen Miran, Viken Arman and Arto Tunçboyacıyan.",
        city: "Jrvezh",
        country: "Armenia",
        venue: "Altezza by Armenian Helicopters, 6/14 Yerevan–Garni Highway",
        category: "Festivals",
        speakersHeading: "Line-up",
        speakers: [
          { name: "Armen Miran" },
          { name: "Hraach" },
          { name: "Viken Arman" },
          { name: "Arto Tunçboyacıyan" },
          { name: "Artyom Manukyan" },
          { name: "Shahen Khandkaryan" },
          { name: "Aram Chakhoyan", note: "Special guest" },
        ],
        body: [
          "EQUINOX pairs the electronic stage with live musicians, and for its autumn chapter it has moved somewhere altogether different: Altezza, the helipad of Armenian Helicopters at Jrvezh, on the Yerevan–Garni highway.",
          "Gates open at 16:00; the music runs from 18:00 to 23:00.",
          "## Tickets",
          "A ticket is 15,000 drams until 10 October and 18,000 drams from 11 to 17 October. The 10,000-dram early-bird tickets went on 5 September.",
        ],
        faq: [
          { q: "How much are tickets?", a: "15,000 drams until 10 October, then 18,000 drams from 11 to 17 October." },
          { q: "What time do the gates open?", a: "At 16:00; the music starts at 18:00 and ends at 23:00." },
          { q: "Where is Altezza?", a: "At Jrvezh, on the Armenian Helicopters helipad at 6/14 Yerevan–Garni Highway." },
        ],
      },
    },
  },

  {
    slug: "romeo-juliet-deja-vu-2026",
    createdAt: "2026-10-04T15:00:00+04:00",
    updatedAt: "2026-10-04T15:00:00+04:00",
    site: "tick",
    title: "«Ռոմեո Ջուլիետ. Դեժավյու»",
    titleSeo: "«Ռոմեո Ջուլիետ. Դեժավյու»՝ Ղափլանյանի թատրոնում",
    summary:
      "Նոր սիրո դրամա Երևանում՝ հոկտեմբերի 19-ին Հրաչյա Ղափլանյանի անվան դրամատիկական թատրոնում. դերերում՝ Իննա Խոջամիրյան, Ռուբեն Մուրադյան, Արամ Կարախանյան։",
    start: "2026-10-19",
    startTime: "19:00",
    utcOffset: "+04:00",
    city: "Երևան",
    country: "Հայաստան",
    venue: "Հրաչյա Ղափլանյանի անվան դրամատիկական թատրոն",
    image: "/covers/romeo-juliet-deja-vu-2026.jpg",
    imageAlt: "Երկու բարձր կամարավոր պատուհան՝ իրար դեմ, մեկում փոքրիկ մահիկ",
    imageKind: "generated",
    imageWidth: 1536,
    imageHeight: 864,
    category: "Թատրոն",
    tickets: { priceFrom: 3000, priceTo: 12000, currency: "AMD" },
    ticket: { url: "https://www.tomsarkgh.am/en/event/51478/", label: "Տոմսեր" },
    source: { name: "Tomsarkgh", url: "https://www.tomsarkgh.am/en/event/51478/", verifiedOn: "2026-10-04" },
    body: [
      "«Ռոմեո Ջուլիետ. Դեժավյու»-ն Լյուդվիգ Հարությունյանի նոր սիրո դրաման է՝ Անահիտ Աղասարյանի պիեսով։ Դերերում՝ Իննա Խոջամիրյանը, Ռուբեն Մուրադյանը և Արամ Կարախանյանը։",
      "Նկարչական ձևավորումը Հրաչ Քեշիշյանինն է, պրոդյուսերը՝ Արման Միտոյանը։ Ներկայացումն իրականացվում է Երևանի քաղաքապետարանի աջակցությամբ։",
      "Հոկտեմբերի 19-ին, ժամը 19:00-ին։ Տոմսերը 3000-ից 12000 դրամ են։",
    ],
    faq: [
      { q: "Որքա՞ն արժե տոմսը", a: "3000-ից 12000 դրամ՝ կախված նստատեղից։" },
      { q: "Ո՞վ է խաղում", a: "Իննա Խոջամիրյանը, Ռուբեն Մուրադյանը և Արամ Կարախանյանը։" },
    ],
    i18n: {
      en: {
        imageAlt: "Two tall arched windows facing each other, a small crescent moon in one of them",
        ticket: { url: "https://www.tomsarkgh.am/en/event/51478/", label: "Tickets" },
        title: "Romeo Juliet. Déjà Vu",
        titleSeo: "Romeo Juliet. Déjà Vu at the Ghaplanyan Theatre",
        summary:
          "A new love drama in Yerevan on 19 October at the Hrachya Ghaplanyan Drama Theatre, with Inna Khojamiryan, Ruben Muradyan and Aram Karakhanyan.",
        city: "Yerevan",
        country: "Armenia",
        venue: "Hrachya Ghaplanyan Drama Theatre",
        category: "Theatre",
        body: [
          "Romeo Juliet. Déjà Vu is Ludwig Harutyunyan's new love drama, written by Anahit Aghasaryan. Inna Khojamiryan, Ruben Muradyan and Aram Karakhanyan take the leads.",
          "The design is by Hrach Keshishyan and the producer is Arman Mitoyan; the production has the support of Yerevan's city hall.",
          "One night only as listed: 19 October at 19:00, with tickets from 3,000 to 12,000 drams. The listing is in Armenian alone, which is a fair guide to the language on stage.",
        ],
        faq: [
          { q: "How much are tickets?", a: "From 3,000 to 12,000 drams depending on the seat." },
          { q: "Who is in it?", a: "Inna Khojamiryan, Ruben Muradyan and Aram Karakhanyan." },
        ],
      },
    },
  },

  {
    slug: "tata-simonyan-yerevan-2026",
    createdAt: "2026-10-04T15:00:00+04:00",
    updatedAt: "2026-10-04T15:00:00+04:00",
    site: "tick",
    title: "Թաթա Սիմոնյան. մենահամերգ Երևանում",
    summary:
      "Թաթա Սիմոնյանի մեծ մենահամերգը Երևանում՝ նոյեմբերի 7-ին Կարեն Դեմիրճյանի անվան մարզահամերգային համալիրում, Կարեն Սևակ բենդի կենդանի նվագակցությամբ։",
    start: "2026-11-07",
    startTime: "19:00",
    utcOffset: "+04:00",
    city: "Երևան",
    country: "Հայաստան",
    venue: "Կարեն Դեմիրճյանի անվան մարզահամերգային համալիր, մեծ դահլիճ",
    geo: { lat: 40.1881503, lng: 44.4833297 },
    image: "/covers/tata-simonyan-yerevan-2026.jpg",
    imageAlt: "Միկրոֆոն դատարկ բեմի կենտրոնում՝ կարմիր ֆոնի և լուսարձակների շողերի տակ",
    imageKind: "generated",
    imageWidth: 1536,
    imageHeight: 864,
    category: "Համերգներ",
    tickets: { priceFrom: 6000, priceTo: 45000, currency: "AMD" },
    ticket: { url: "https://www.tomsarkgh.am/en/event/50900/", label: "Տոմսեր" },
    source: { name: "Tomsarkgh", url: "https://www.tomsarkgh.am/en/event/50900/", verifiedOn: "2026-10-04" },
    body: [
      "Թաթա Սիմոնյանը նոյեմբերի 7-ին հանդես է գալիս Կարեն Դեմիրճյանի անվան մարզահամերգային համալիրի մեծ դահլիճում։ Միայն կենդանի հնչողություն՝ Կարեն Սևակ բենդի նվագակցությամբ։",
      "Ծրագրում՝ հին ու նոր երգեր և համերգային պրեմիերաներ, ժամանակակից լուսային, տեսա- և ձայնային էֆեկտներով։",
      "Համերգը սկսվում է ժամը 19:00-ին։ Տոմսերը 6000-ից 45000 դրամ են։",
    ],
    faq: [
      { q: "Որքա՞ն արժե տոմսը", a: "6000-ից 45000 դրամ՝ կախված նստատեղից։" },
      { q: "Ե՞րբ է սկսվում համերգը", a: "Նոյեմբերի 7-ին, ժամը 19:00-ին։" },
    ],
    i18n: {
      en: {
        imageAlt: "A microphone at the centre of an empty stage under a red backdrop and spotlight beams",
        ticket: { url: "https://www.tomsarkgh.am/en/event/50900/", label: "Tickets" },
        title: "Tata Simonyan in concert in Yerevan",
        summary:
          "Tata Simonyan plays the main hall of the Karen Demirchyan Complex in Yerevan on 7 November, with the Karen Sevak band and nothing pre-recorded.",
        city: "Yerevan",
        country: "Armenia",
        venue: "Karen Demirchyan Sports and Concert Complex, main hall",
        category: "Concerts",
        body: [
          "Tata Simonyan takes the main hall of the Karen Demirchyan Sports and Concert Complex on 7 November. Everything is played live, backed by the Karen Sevak band.",
          "The programme mixes old songs and new, with a few concert premieres, under a full production of lights, video and sound.",
          "The concert starts at 19:00, with tickets from 6,000 to 45,000 drams.",
        ],
        faq: [
          { q: "How much are tickets?", a: "From 6,000 to 45,000 drams depending on the seat." },
          { q: "What time does it start?", a: "At 19:00 on 7 November." },
        ],
      },
    },
  },

  {
    slug: "grigory-sokolov-yerevan-2026",
    createdAt: "2026-10-04T20:00:00+04:00",
    updatedAt: "2026-10-04T20:00:00+04:00",
    site: "tick",
    title: "Գրիգորի Սոկոլով. դաշնամուրային մենահամերգ Երևանում",
    cardTitle: "Գրիգորի Սոկոլով. մենահամերգ",
    summary:
      "Դաշնակահար Գրիգորի Սոկոլովը նոյեմբերի 14-ին Երևանում է՝ Արամ Խաչատրյան համերգասրահում, Երևանյան 18-րդ միջազգային երաժշտական փառատոնի փակման համերգով։",
    start: "2026-11-14",
    startTime: "19:00",
    utcOffset: "+04:00",
    city: "Երևան",
    country: "Հայաստան",
    venue: "Արամ Խաչատրյան համերգասրահ, Մաշտոցի պող. 46",
    geo: { lat: 40.1862685, lng: 44.5151091 },
    image: "/covers/grigory-sokolov-yerevan-2026.jpg",
    imageAlt: "Կարմիր ռոյալ՝ բաց կափարիչով, և դատարկ աթոռ՝ վերևից ընկնող լույսի շերտի տակ, ծիրանագույն ֆոնի վրա",
    imageKind: "generated",
    imageWidth: 1536,
    imageHeight: 864,
    category: "Դասական երաժշտություն",
    tickets: { priceFrom: 10000, priceTo: 70000, currency: "AMD" },
    ticket: { url: "https://www.tomsarkgh.am/en/event/51312/", label: "Տոմսեր" },
    source: { name: "Tomsarkgh", url: "https://www.tomsarkgh.am/en/event/51312/", verifiedOn: "2026-10-04" },
    body: [
      "Գրիգորի Սոկոլովը՝ համաշխարհային կատարողական արվեստի լեգենդը, ինչպես նրան անվանում են կազմակերպիչները, նոյեմբերի 14-ին մենահամերգով հանդես կգա Երևանում։",
      "Համերգը Երևանյան 18-րդ միջազգային երաժշտական փառատոնի փակումն է և տեղի կունենա Արամ Խաչատրյան համերգասրահում՝ ժամը 19:00-ին։",
      "## Ծրագիրը և տոմսերը",
      "Համերգի ծրագիրը Tomsarkgh-ում դեռ հրապարակված չէ։ Տոմսերը 10000-ից 70000 դրամ են։",
    ],
    faq: [
      { q: "Որքա՞ն արժե տոմսը", a: "10000-ից 70000 դրամ՝ կախված նստատեղից։" },
      { q: "Ե՞րբ է համերգը", a: "Նոյեմբերի 14-ին, ժամը 19:00-ին, Արամ Խաչատրյան համերգասրահում։" },
      { q: "Ի՞նչ կնվագի Սոկոլովը", a: "Ծրագիրը դեռ հրապարակված չէ։" },
    ],
    i18n: {
      en: {
        imageAlt: "A red grand piano with its lid raised beside an empty stool, under a shaft of light on an apricot ground",
        ticket: { url: "https://www.tomsarkgh.am/en/event/51312/", label: "Tickets" },
        title: "Grigory Sokolov: piano recital in Yerevan",
        cardTitle: "Grigory Sokolov in recital",
        summary:
          "Grigory Sokolov gives a solo piano recital in Yerevan on 14 November at the Aram Khachaturian Concert Hall, closing the 18th Yerevan International Music Festival.",
        city: "Yerevan",
        country: "Armenia",
        venue: "Aram Khachaturian Concert Hall, 46 Mashtots Avenue",
        category: "Classical",
        body: [
          "Grigory Sokolov — billed by the organisers, without much fear of contradiction, as a legend of the world's performing arts — gives a solo recital in Yerevan on 14 November.",
          "It is the closing concert of the 18th Yerevan International Music Festival, at the Aram Khachaturian Concert Hall, starting at 19:00.",
          "## Programme and tickets",
          "The programme has not yet been published on Tomsarkgh. Tickets run from 10,000 to 70,000 drams.",
        ],
        faq: [
          { q: "How much are tickets?", a: "From 10,000 to 70,000 drams depending on the seat." },
          { q: "When is it?", a: "On 14 November at 19:00, at the Aram Khachaturian Concert Hall." },
          { q: "What will Sokolov play?", a: "The programme has not been published yet." },
        ],
      },
    },
  },

  {
    slug: "andru-donalds-enigma-yerevan-2026",
    createdAt: "2026-10-04T15:00:00+04:00",
    updatedAt: "2026-10-04T15:00:00+04:00",
    site: "tick",
    title: "Էնդրյու Դոնալդս. ENIGMA-ի ոսկե ձայնը Երևանում",
    cardTitle: "Էնդրյու Դոնալդս. ENIGMA-ի ձայնը",
    summary:
      "Էնդրյու Դոնալդսը՝ ENIGMA-ի ձայնը, նոյեմբերի 21-ին Երևանում է՝ Արամ Խաչատրյան համերգասրահում, լարային նվագախմբի և մանկական երգչախմբի հետ։",
    start: "2026-11-21",
    startTime: "19:00",
    utcOffset: "+04:00",
    city: "Երևան",
    country: "Հայաստան",
    venue: "Արամ Խաչատրյան համերգասրահ, Մաշտոցի պող. 46",
    geo: { lat: 40.1862685, lng: 44.5151091 },
    image: "/covers/andru-donalds-enigma-yerevan-2026.jpg",
    imageAlt: "Սև վինիլե ձայնասկավառակ, որի կենտրոնից ոլորվում է թղթե ժապավեն",
    imageKind: "generated",
    imageWidth: 1536,
    imageHeight: 864,
    category: "Համերգներ",
    tickets: { priceFrom: 10000, priceTo: 50000, currency: "AMD" },
    ticket: { url: "https://www.tomsarkgh.am/en/event/51067/", label: "Տոմսեր" },
    source: { name: "Tomsarkgh", url: "https://www.tomsarkgh.am/en/event/51067/", verifiedOn: "2026-10-04" },
    body: [
      "Ճամայկացի երգիչ և երգահան Էնդրյու Դոնալդսը հայտնի դարձավ 1995 թվականին «Mishale» երգով, իսկ 1998-ին Միշել Կրետուն նրան հրավիրեց ENIGMA նախագիծ։ Մինչև 2008 թվականը նա աշխատել է ENIGMA-ի չորրորդից յոթերորդ ալբոմների վրա՝ «Seven Lives», «Boum-Boum», «Modern Crusaders» և այլ երգեր։",
      "Երևանում կհնչեն ENIGMA-ի հայտնի երգերը և Դոնալդսի մենահիթերը՝ լարային նվագախմբի և մանկական երգչախմբի ուղեկցությամբ։ Կազմակերպիչների խոսքով՝ այցն արտիստի համար անձնական է. նրա որդին հայկական արմատներ ունի։",
      "Նոյեմբերի 21-ին, ժամը 19:00-ին, Արամ Խաչատրյան համերգասրահում։ Տոմսերը 10000-ից 50000 դրամ են։",
    ],
    faq: [
      { q: "Որքա՞ն արժե տոմսը", a: "10000-ից 50000 դրամ՝ կախված նստատեղից։" },
      { q: "Ի՞նչ կհնչի", a: "ENIGMA-ի երգերը և Էնդրյու Դոնալդսի մենահիթերը՝ լարային նվագախմբի և մանկական երգչախմբի հետ։" },
    ],
    i18n: {
      en: {
        imageAlt: "A black vinyl record with a paper ribbon curling up from its red centre",
        ticket: { url: "https://www.tomsarkgh.am/en/event/51067/", label: "Tickets" },
        title: "Andru Donalds: the voice of Enigma in Yerevan",
        cardTitle: "Andru Donalds: the voice of Enigma",
        summary:
          "Andru Donalds, the voice on Enigma's records from 1998 to 2008, sings at the Aram Khachaturian Concert Hall in Yerevan on 21 November, with strings and a children's choir.",
        city: "Yerevan",
        country: "Armenia",
        venue: "Aram Khachaturian Concert Hall, 46 Mashtots Avenue",
        category: "Concerts",
        body: [
          "The Jamaican singer-songwriter Andru Donalds broke through with Mishale in 1995, and in 1998 Michael Cretu brought Donalds into Enigma. Donalds sang on the project's fourth to seventh albums, until 2008 — Seven Lives, Boum-Boum and Modern Crusaders among them.",
          "In Yerevan the programme is Enigma's best-known songs and Donalds's own hits, with a string orchestra and a children's choir. The organisers say the visit is a personal one: the singer's son has Armenian roots.",
          "21 November at 19:00, at the Aram Khachaturian Concert Hall, with tickets from 10,000 to 50,000 drams.",
        ],
        faq: [
          { q: "How much are tickets?", a: "From 10,000 to 50,000 drams depending on the seat." },
          { q: "What is on the programme?", a: "Enigma's songs and Andru Donalds's own hits, with a string orchestra and a children's choir." },
        ],
      },
    },
  },

  {
    slug: "rachmaninov-piano-concertos-1-3-yerevan-2026",
    createdAt: "2026-10-04T20:00:00+04:00",
    updatedAt: "2026-10-04T20:00:00+04:00",
    site: "tick",
    title: "Ռախմանինով. Դաշնամուրի կոնցերտներ թիվ 1 և 3",
    cardTitle: "Ռախմանինով՝ կոնցերտներ 1 և 3",
    summary:
      "Նոյեմբերի 26-ին Երևանում՝ Արամ Խաչատրյան համերգասրահում, Եվա Գևորգյանը նվագում է Ռախմանինովի առաջին և երրորդ կոնցերտները. բացվում է Խաչատրյանի 14-րդ միջազգային փառատոնը։",
    start: "2026-11-26",
    startTime: "19:30",
    utcOffset: "+04:00",
    city: "Երևան",
    country: "Հայաստան",
    venue: "Արամ Խաչատրյան համերգասրահ, Մաշտոցի պող. 46",
    geo: { lat: 40.1862685, lng: 44.5151091 },
    organizer: "«Արամ Խաչատրյան» մշակութային հիմնադրամ",
    image: "/covers/rachmaninov-piano-concertos-1-3-yerevan-2026.jpg",
    imageAlt: "Դաշնամուրի ստեղնաշարի երկար շերտ, որը բարձրանում և իջնում է ալիքի պես՝ ծիրանագույն ֆոնի վրա",
    imageKind: "generated",
    imageWidth: 1536,
    imageHeight: 864,
    category: "Դասական երաժշտություն",
    tickets: { priceFrom: 3000, priceTo: 15000, currency: "AMD" },
    ticket: { url: "https://www.tomsarkgh.am/en/event/51418/", label: "Տոմսեր" },
    source: { name: "Tomsarkgh", url: "https://www.tomsarkgh.am/en/event/51418/", verifiedOn: "2026-10-04" },
    body: [
      "Խաչատրյանի անվան 14-րդ միջազգային փառատոնը բացվում է Ռախմանինովով։ Նոյեմբերի 26-ին դաշնակահարուհի Եվա Գևորգյանը Հայաստանի պետական սիմֆոնիկ նվագախմբի հետ նվագում է նրա Դաշնամուրի առաջին և երրորդ կոնցերտները, դիրիժորը՝ Սերգեյ Սմբատյանը։",
      "## Ծրագիրը",
      "Առաջին բաժնում՝ Դաշնամուրի կոնցերտ թիվ 1 ֆա դիեզ մինոր, երկ 1 (մոտ 27 րոպե)։ Ընդմիջումից հետո՝ Դաշնամուրի կոնցերտ թիվ 3 ռե մինոր, երկ 30 (մոտ 40 րոպե)։",
      "## Տոմսերը",
      "Համերգը սկսվում է ժամը 19:30-ին։ Տոմսերը 3000-ից 15000 դրամ են, երեխաների մուտքը՝ 6 տարեկանից։ Փառատոնը կազմակերպում է «Արամ Խաչատրյան» մշակութային հիմնադրամը՝ ԿԳՄՍ նախարարության աջակցությամբ։",
    ],
    faq: [
      { q: "Որքա՞ն արժե տոմսը", a: "3000-ից 15000 դրամ՝ կախված նստատեղից։" },
      { q: "Կարելի՞ է գալ երեխաների հետ", a: "Այո, 6 տարեկանից։" },
      { q: "Որքա՞ն է տևում համերգը", a: "Երաժշտությունը մոտ 67 րոպե է՝ երկու մասով, որոնց միջև ընդմիջում կա։" },
    ],
    i18n: {
      en: {
        imageAlt: "A long band of piano keys rising and falling like a wave across an apricot ground",
        ticket: { url: "https://www.tomsarkgh.am/en/event/51418/", label: "Tickets" },
        title: "Rachmaninov: Piano Concertos Nos. 1 and 3",
        cardTitle: "Rachmaninov: Concertos 1 and 3",
        summary:
          "Eva Gevorgyan plays Rachmaninov's First and Third Piano Concertos in Yerevan on 26 November at the Aram Khachaturian Concert Hall, opening the 14th Khachaturian International Festival.",
        city: "Yerevan",
        country: "Armenia",
        venue: "Aram Khachaturian Concert Hall, 46 Mashtots Avenue",
        organizer: "Aram Khachaturian Cultural Foundation",
        category: "Classical",
        body: [
          "The 14th Khachaturian International Festival opens with Rachmaninov. On 26 November the pianist Eva Gevorgyan plays his First and Third Piano Concertos with the Armenian State Symphony Orchestra, conducted by Sergey Smbatyan.",
          "## The programme",
          "First half: Piano Concerto No. 1 in F-sharp minor, Op. 1 (about 27 minutes). After the interval: Piano Concerto No. 3 in D minor, Op. 30 (about 40 minutes) — the one pianists speak of with a certain respect.",
          "## Tickets",
          "The concert starts at 19:30, with tickets from 3,000 to 15,000 drams; children are admitted from the age of six. The festival is run by the Aram Khachaturian Cultural Foundation with the support of Armenia's Ministry of Education, Science, Culture and Sports.",
        ],
        faq: [
          { q: "How much are tickets?", a: "From 3,000 to 15,000 drams depending on the seat." },
          { q: "Can children come?", a: "Yes, from the age of six." },
          { q: "How long is the concert?", a: "About 67 minutes of music, in two halves with an interval between them." },
        ],
      },
    },
  },

  {
    slug: "lyubov-uspenskaya-yerevan-2027",
    createdAt: "2026-10-04T15:00:00+04:00",
    updatedAt: "2026-10-04T15:00:00+04:00",
    site: "tick",
    title: "Լյուբով Ուսպենսկայա. մեծ համերգ Երևանում",
    summary:
      "Ռուսական շանսոնի աստղ Լյուբով Ուսպենսկայան 2027 թվականի հունվարի 30-ին Երևանում է՝ Կարեն Դեմիրճյանի անվան մարզահամերգային համալիրում։",
    start: "2027-01-30",
    startTime: "19:00",
    utcOffset: "+04:00",
    city: "Երևան",
    country: "Հայաստան",
    venue: "Կարեն Դեմիրճյանի անվան մարզահամերգային համալիր",
    geo: { lat: 40.1881503, lng: 44.4833297 },
    image: "/covers/lyubov-uspenskaya-yerevan-2027.jpg",
    imageAlt: "Ռոյալի ուրվագիծ՝ բաց կափարիչով, ոտքերի մոտ ընկած վարդով",
    imageKind: "generated",
    imageWidth: 1536,
    imageHeight: 864,
    category: "Համերգներ",
    tickets: { priceFrom: 7000, priceTo: 50000, currency: "AMD" },
    ticket: { url: "https://www.tomsarkgh.am/en/event/46842/", label: "Տոմսեր" },
    source: { name: "Tomsarkgh", url: "https://www.tomsarkgh.am/en/event/46842/", verifiedOn: "2026-10-04" },
    body: [
      "Լյուբով Ուսպենսկայան՝ ռուսական շանսոնի թագուհին, Երևանում ներկայացնում է մեծ համերգային ծրագիր՝ միլիոնավոր ունկնդիրներին ծանոթ երգերով։",
      "2027 թվականի հունվարի 30-ին, ժամը 19:00-ին, Կարեն Դեմիրճյանի անվան մարզահամերգային համալիրում։ Տոմսերը 7000-ից 50000 դրամ են։",
    ],
    faq: [
      { q: "Որքա՞ն արժե տոմսը", a: "7000-ից 50000 դրամ՝ կախված նստատեղից։" },
      { q: "Ե՞րբ է համերգը", a: "2027 թվականի հունվարի 30-ին, ժամը 19:00-ին։" },
    ],
    i18n: {
      en: {
        imageAlt: "The silhouette of a grand piano with its lid raised and a single rose lying at its feet",
        ticket: { url: "https://www.tomsarkgh.am/en/event/46842/", label: "Tickets" },
        title: "Lyubov Uspenskaya in concert in Yerevan",
        summary:
          "Lyubov Uspenskaya, the queen of Russian chanson, brings a full concert programme to the Karen Demirchyan Complex in Yerevan on 30 January 2027.",
        city: "Yerevan",
        country: "Armenia",
        venue: "Karen Demirchyan Sports and Concert Complex",
        category: "Concerts",
        body: [
          "Lyubov Uspenskaya, long billed as the queen of Russian chanson, brings a full concert programme to Yerevan: the songs millions know, sung live.",
          "30 January 2027 at 19:00, at the Karen Demirchyan Sports and Concert Complex, with tickets from 7,000 to 50,000 drams.",
        ],
        faq: [
          { q: "How much are tickets?", a: "From 7,000 to 50,000 drams depending on the seat." },
          { q: "When is it?", a: "On 30 January 2027 at 19:00." },
        ],
      },
    },
  },

  {
    slug: "swan-lake-yerevan-opera-2026",
    createdAt: "2026-10-06T01:00:00+04:00",
    updatedAt: "2026-10-06T20:15:00+04:00",
    site: "tick",
    title: "«Կարապի լիճ»՝ Երևանի օպերային թատրոնում",
    cardTitle: "Չայկովսկի. «Կարապի լիճ»",
    summary:
      "Չայկովսկու «Կարապի լիճը» Երևանում՝ Սպենդիարյանի անվան օպերայի և բալետի թատրոնում, հոկտեմբերի 9-ին և 30-ին, նաև նոյեմբերին և հունվարին. տոմսերը՝ 5000-ից 28000 դրամ։",
    start: "2026-10-09",
    startTime: "19:00",
    utcOffset: "+04:00",
    city: "Երևան",
    country: "Հայաստան",
    venue: "Ալ. Սպենդիարյանի անվան օպերայի և բալետի ազգային ակադեմիական թատրոն, Թումանյան 54",
    geo: { lat: 40.1862685, lng: 44.5151091 },
    organizer: "Ալ. Սպենդիարյանի անվան օպերայի և բալետի ազգային ակադեմիական թատրոն",
    image: "/covers/swan-lake-yerevan-opera-2026.jpg",
    imageAlt: "Սպիտակ կարապ՝ մութ լճի վրա, վերևում՝ մահիկ, ջրում՝ կարապի արտացոլանքը",
    imageKind: "generated",
    imageWidth: 1536,
    imageHeight: 864,
    category: "Օպերա և բալետ",
    tickets: { priceFrom: 5000, priceTo: 28000, currency: "AMD" },
    ticket: { url: "https://www.tomsarkgh.am/en/event/47038/", label: "Տոմսեր" },
    source: { name: "Tomsarkgh", url: "https://www.tomsarkgh.am/en/event/47038/", verifiedOn: "2026-10-06" },
    body: [
      "Չայկովսկու «Կարապի լիճը» Երևանի օպերային թատրոնում պարում են Մարիուս Պետիպայի և Լև Իվանովի պարուսույցով՝ Ալեքսեյ Ֆադեեչևի խմբագրմամբ։ Բեմադրության գեղարվեստական ղեկավարը Նինա Անանիաշվիլին է, բեմանկարչությունն ու զգեստները՝ Վյաչեսլավ Օկունևի։",
      "Երաժշտական ղեկավարն ու դիրիժորը Կարեն Դուրգարյանն է, դիրիժոր՝ Հարություն Արզումանյան։ Բալետը երկու գործողությամբ է և մեկ ընդմիջումով. ընդհանուր տևողությունը՝ 2 ժամ 10 րոպե։",
      "## Երբ",
      "Հոկտեմբերի 9-ին և 30-ին՝ ժամը 19:00-ին, նոյեմբերի 15-ին՝ 18:00-ին, նոյեմբերի 26-ին՝ 19:00-ին, հունվարի 9-ին և 30-ին՝ 18:00-ին։ Տոմսերը 5000-ից 28000 դրամ են։",
    ],
    faq: [
      { q: "Որքա՞ն արժե տոմսը", a: "5000-ից 28000 դրամ՝ կախված նստատեղից։" },
      { q: "Ե՞րբ են ներկայացումները", a: "Հոկտեմբերի 9-ին և 30-ին, նոյեմբերի 15-ին և 26-ին, հունվարի 9-ին և 30-ին։" },
      { q: "Որքա՞ն է տևում բալետը", a: "2 ժամ 10 րոպե՝ մեկ ընդմիջումով։" },
    ],
    i18n: {
      en: {
        imageAlt: "A white swan on a dark lake beneath a crescent moon, its reflection in the water",
        ticket: { url: "https://www.tomsarkgh.am/en/event/47038/", label: "Tickets" },
        title: "Swan Lake at the Yerevan Opera",
        cardTitle: "Tchaikovsky: Swan Lake",
        summary:
          "Tchaikovsky's Swan Lake in Yerevan at the Spendiaryan Opera and Ballet Theatre on 9 and 30 October, with more nights in November and January; tickets from 5,000 drams.",
        city: "Yerevan",
        country: "Armenia",
        venue: "Spendiaryan Opera and Ballet Theatre, 54 Tumanyan Street",
        organizer: "Spendiaryan National Academic Opera and Ballet Theatre",
        category: "Opera and ballet",
        body: [
          "Tchaikovsky's Swan Lake as the Yerevan Opera dances it: Marius Petipa and Lev Ivanov's choreography in Alexei Fadeyechev's revision, with Nina Ananiashvili as the production's artistic director and sets and costumes by Vyacheslav Okunev.",
          "Karen Durgaryan is music director and conductor, with Harutyun Arzumanyan also conducting. Two acts and one interval, 2 hours 10 minutes in all.",
          "## Dates",
          "9 and 30 October at 19:00, 15 November at 18:00, 26 November at 19:00, and 9 and 30 January at 18:00. Tickets cost 5,000 to 28,000 drams.",
        ],
        faq: [
          { q: "How much are tickets?", a: "From 5,000 to 28,000 drams depending on the seat." },
          { q: "When is it on?", a: "On 9 and 30 October, 15 and 26 November, and 9 and 30 January." },
          { q: "How long is the ballet?", a: "2 hours 10 minutes, with one interval." },
        ],
      },
    },
  },

  {
    slug: "carmen-yerevan-opera-2026",
    createdAt: "2026-10-06T01:00:00+04:00",
    updatedAt: "2026-10-06T01:00:00+04:00",
    site: "tick",
    title: "«Կարմեն»՝ Երևանի օպերային թատրոնում",
    cardTitle: "Բիզե. «Կարմեն»",
    summary:
      "Բիզեի «Կարմեն» օպերան Երևանում՝ Սպենդիարյանի անվան օպերայի և բալետի թատրոնում, հոկտեմբերի 10-ին և նոյեմբերի 14-ին, ժամը 18:00-ին. տոմսերը՝ 5000-ից 18000 դրամ։",
    start: "2026-10-10",
    startTime: "18:00",
    utcOffset: "+04:00",
    city: "Երևան",
    country: "Հայաստան",
    venue: "Ալ. Սպենդիարյանի անվան օպերայի և բալետի ազգային ակադեմիական թատրոն, Թումանյան 54",
    geo: { lat: 40.1862685, lng: 44.5151091 },
    organizer: "Ալ. Սպենդիարյանի անվան օպերայի և բալետի ազգային ակադեմիական թատրոն",
    image: "/covers/carmen-yerevan-opera-2026.jpg",
    imageAlt: "Կարմիր վարդ՝ բացված թղթե հովհարի վրա, նարնջագույն ֆոնի վրա",
    imageKind: "generated",
    imageWidth: 1536,
    imageHeight: 864,
    category: "Օպերա և բալետ",
    tickets: { priceFrom: 5000, priceTo: 18000, currency: "AMD" },
    ticket: { url: "https://www.tomsarkgh.am/en/event/44954/", label: "Տոմսեր" },
    source: { name: "Tomsarkgh", url: "https://www.tomsarkgh.am/en/event/44954/", verifiedOn: "2026-10-06" },
    body: [
      "Ժորժ Բիզեի «Կարմենը» Երևանի օպերային թատրոնի խաղացանկում է Արմեն Մելիքսեթյանի բեմադրությամբ և Դավիթ Մինասյանի բեմանկարչությամբ։ Երաժշտական ղեկավարն ու դիրիժորը Կարեն Դուրգարյանն է։",
      "Օպերան չորս գործողությամբ է և մեկ ընդմիջումով. ընդհանուր տևողությունը 3 ժամ 10 րոպե է։",
      "## Երբ",
      "Հոկտեմբերի 10-ին և նոյեմբերի 14-ին, երկու օրն էլ ժամը 18:00-ին։ Տոմսերը 5000-ից 18000 դրամ են։",
    ],
    faq: [
      { q: "Որքա՞ն արժե տոմսը", a: "5000-ից 18000 դրամ՝ կախված նստատեղից։" },
      { q: "Ե՞րբ է ներկայացումը", a: "Հոկտեմբերի 10-ին և նոյեմբերի 14-ին, ժամը 18:00-ին։" },
      { q: "Որքա՞ն է տևում օպերան", a: "3 ժամ 10 րոպե՝ մեկ ընդմիջումով։" },
    ],
    i18n: {
      en: {
        imageAlt: "A red rose on an open paper fan, on an orange ground",
        ticket: { url: "https://www.tomsarkgh.am/en/event/44954/", label: "Tickets" },
        title: "Carmen at the Yerevan Opera",
        cardTitle: "Bizet: Carmen",
        summary:
          "Bizet's Carmen in Yerevan at the Spendiaryan Opera and Ballet Theatre on 10 October and 14 November, both at 18:00, with tickets from 5,000 to 18,000 drams.",
        city: "Yerevan",
        country: "Armenia",
        venue: "Spendiaryan Opera and Ballet Theatre, 54 Tumanyan Street",
        organizer: "Spendiaryan National Academic Opera and Ballet Theatre",
        category: "Opera and ballet",
        body: [
          "Bizet's Carmen is in the Yerevan Opera's repertoire in Armen Meliksetyan's staging, designed by Davit Minasyan, with Karen Durgaryan as music director and conductor.",
          "Four acts and a single interval, 3 hours 10 minutes in all — one is advised to dine beforehand.",
          "## Dates",
          "10 October and 14 November, both at 18:00. Tickets cost 5,000 to 18,000 drams.",
        ],
        faq: [
          { q: "How much are tickets?", a: "From 5,000 to 18,000 drams depending on the seat." },
          { q: "When is it on?", a: "On 10 October and 14 November, at 18:00." },
          { q: "How long is the opera?", a: "3 hours 10 minutes, with one interval." },
        ],
      },
    },
  },

  {
    slug: "gayane-ballet-yerevan-2026",
    createdAt: "2026-10-06T01:00:00+04:00",
    updatedAt: "2026-10-06T01:00:00+04:00",
    site: "tick",
    title: "Խաչատրյանի «Գայանե» բալետը Երևանում",
    cardTitle: "Խաչատրյան. «Գայանե»",
    summary:
      "Արամ Խաչատրյանի «Գայանե» բալետը Երևանում՝ Սպենդիարյանի անվան օպերայի և բալետի թատրոնում, հոկտեմբերի 11-ին և 21-ին, նոյեմբերի 5-ին և 19-ին. տոմսերը՝ 5000-ից 28000 դրամ։",
    start: "2026-10-11",
    startTime: "18:00",
    utcOffset: "+04:00",
    city: "Երևան",
    country: "Հայաստան",
    venue: "Ալ. Սպենդիարյանի անվան օպերայի և բալետի ազգային ակադեմիական թատրոն, Թումանյան 54",
    geo: { lat: 40.1862685, lng: 44.5151091 },
    organizer: "Ալ. Սպենդիարյանի անվան օպերայի և բալետի ազգային ակադեմիական թատրոն",
    image: "/covers/gayane-ballet-yerevan-2026.jpg",
    imageAlt: "Երկու խաչված սուր՝ բամբակով լի հյուսած զամբյուղի վերևում",
    imageKind: "generated",
    imageWidth: 1536,
    imageHeight: 864,
    category: "Օպերա և բալետ",
    tickets: { priceFrom: 5000, priceTo: 28000, currency: "AMD" },
    ticket: { url: "https://www.tomsarkgh.am/en/event/1963/", label: "Տոմսեր" },
    source: { name: "Tomsarkgh", url: "https://www.tomsarkgh.am/en/event/1963/", verifiedOn: "2026-10-06" },
    body: [
      "«Գայանեն» Արամ Խաչատրյանի բալետն է՝ այն նույնը, որից աշխարհը ճանաչում է «Սրերով պարը»։ Երևանի օպերային թատրոնում այն բեմադրել է թատրոնի գլխավոր բալետմայստեր Վիլեն Գալստյանը, նկարիչը Մինաս Ավետիսյանն է, զգեստների նկարիչը՝ Ռուբինա Հովհաննիսյանը։",
      "Դիրիժորը Կարեն Դուրգարյանն է, փորձավարները՝ Էլվիրա Մնացականյանը և Արթուր Գրիգորյանը։ Բալետը երեք գործողությամբ է և երկու ընդմիջումով, ընդհանուր տևողությունը՝ 2 ժամ 20 րոպե։",
      "## Երբ",
      "Հոկտեմբերի 11-ին՝ ժամը 18:00-ին, հոկտեմբերի 21-ին, նոյեմբերի 5-ին և 19-ին՝ 19:00-ին։ Տոմսերը 5000-ից 28000 դրամ են։",
    ],
    faq: [
      { q: "Որքա՞ն արժե տոմսը", a: "5000-ից 28000 դրամ՝ կախված նստատեղից։" },
      { q: "Ե՞րբ են ներկայացումները", a: "Հոկտեմբերի 11-ին և 21-ին, նոյեմբերի 5-ին և 19-ին։" },
      { q: "Որքա՞ն է տևում բալետը", a: "2 ժամ 20 րոպե՝ երկու ընդմիջումով։" },
    ],
    i18n: {
      en: {
        imageAlt: "Two crossed sabres above a woven basket full of cotton bolls",
        ticket: { url: "https://www.tomsarkgh.am/en/event/1963/", label: "Tickets" },
        title: "Khachaturian's Gayane at the Yerevan Opera",
        cardTitle: "Khachaturian: Gayane",
        summary:
          "Aram Khachaturian's ballet Gayane in Yerevan at the Spendiaryan Opera and Ballet Theatre on 11 and 21 October and 5 and 19 November, with tickets from 5,000 drams.",
        city: "Yerevan",
        country: "Armenia",
        venue: "Spendiaryan Opera and Ballet Theatre, 54 Tumanyan Street",
        organizer: "Spendiaryan National Academic Opera and Ballet Theatre",
        category: "Opera and ballet",
        body: [
          "Gayane is Aram Khachaturian's ballet — the one the Sabre Dance comes from — and in Yerevan it is danced in a staging by Vilen Galstyan, the theatre's chief choreographer, with designs by Minas Avetisyan and costumes by Rubina Hovhannisyan.",
          "Karen Durgaryan conducts, and the répétiteurs are Elvira Mnatsakanyan and Artur Grigoryan. Three acts and two intervals, 2 hours 20 minutes in all.",
          "## Dates",
          "11 October at 18:00, then 21 October, 5 November and 19 November at 19:00. Tickets cost 5,000 to 28,000 drams.",
        ],
        faq: [
          { q: "How much are tickets?", a: "From 5,000 to 28,000 drams depending on the seat." },
          { q: "When is it on?", a: "On 11 and 21 October and on 5 and 19 November." },
          { q: "How long is the ballet?", a: "2 hours 20 minutes, with two intervals." },
        ],
      },
    },
  },

  {
    slug: "turandot-yerevan-opera-2026",
    createdAt: "2026-10-06T01:00:00+04:00",
    updatedAt: "2026-10-06T01:00:00+04:00",
    site: "tick",
    title: "Պուչչինի. «Տուրանդոտ»՝ Երևանի օպերային թատրոնում",
    titleSeo: "«Տուրանդոտ»՝ Երևանի օպերային թատրոնում",
    cardTitle: "Պուչչինի. «Տուրանդոտ»",
    summary:
      "Պուչչինիի «Տուրանդոտը» Երևանում՝ հոկտեմբերի 22-ին Սպենդիարյանի անվան օպերայի և բալետի թատրոնում, Վյաչեսլավ Ստարոդուբցևի բեմադրությամբ. տոմսերը՝ 5000-ից 15000 դրամ։",
    start: "2026-10-22",
    startTime: "19:00",
    utcOffset: "+04:00",
    city: "Երևան",
    country: "Հայաստան",
    venue: "Ալ. Սպենդիարյանի անվան օպերայի և բալետի ազգային ակադեմիական թատրոն, Թումանյան 54",
    geo: { lat: 40.1862685, lng: 44.5151091 },
    organizer: "Ալ. Սպենդիարյանի անվան օպերայի և բալետի ազգային ակադեմիական թատրոն",
    image: "/covers/turandot-yerevan-opera-2026.jpg",
    imageAlt: "Մեծ գունատ լուսին՝ կամարի վերևում, որից կախված են երեք լապտեր",
    imageKind: "generated",
    imageWidth: 1536,
    imageHeight: 864,
    category: "Օպերա և բալետ",
    tickets: { priceFrom: 5000, priceTo: 15000, currency: "AMD" },
    ticket: { url: "https://www.tomsarkgh.am/en/event/46863/", label: "Տոմսեր" },
    source: { name: "Tomsarkgh", url: "https://www.tomsarkgh.am/en/event/46863/", verifiedOn: "2026-10-06" },
    body: [
      "Ջակոմո Պուչչինիի վերջին օպերան՝ «Տուրանդոտը», Երևանում բեմադրել է ռեժիսոր Վյաչեսլավ Ստարոդուբցևը։ Բեմանկարչությունն ու զգեստները Պյոտր Օկունևինն են, լուսային ձևավորումը՝ Սերգեյ Սկորնեցկու, տեսաձևավորումը՝ Վադիմ Դուլենկոյի։",
      "Երաժշտական ղեկավարն ու դիրիժորը Կարեն Դուրգարյանն է, դիրիժորներ՝ Հարություն Արզումանյան և Վարդան Գրիգորյան, գլխավոր խմբավար՝ Հրաչ Բորյան։",
      "## Երբ",
      "Հոկտեմբերի 22-ին, ժամը 19:00-ին։ Օպերան երեք գործողությամբ է և երկու ընդմիջումով, ընդհանուր տևողությունը՝ 2 ժամ 50 րոպե։ Տոմսերը 5000-ից 15000 դրամ են։",
    ],
    faq: [
      { q: "Որքա՞ն արժե տոմսը", a: "5000-ից 15000 դրամ՝ կախված նստատեղից։" },
      { q: "Ե՞րբ է ներկայացումը", a: "Հոկտեմբերի 22-ին, ժամը 19:00-ին։" },
      { q: "Որքա՞ն է տևում օպերան", a: "2 ժամ 50 րոպե՝ երկու ընդմիջումով։" },
    ],
    i18n: {
      en: {
        imageAlt: "A large pale moon above an arch hung with three lanterns",
        ticket: { url: "https://www.tomsarkgh.am/en/event/46863/", label: "Tickets" },
        title: "Puccini's Turandot at the Yerevan Opera",
        titleSeo: "Turandot at the Yerevan Opera",
        cardTitle: "Puccini: Turandot",
        summary:
          "Puccini's Turandot in Yerevan on 22 October at the Spendiaryan Opera and Ballet Theatre, staged by Vyacheslav Starodubtsev, with tickets from 5,000 to 15,000 drams.",
        city: "Yerevan",
        country: "Armenia",
        venue: "Spendiaryan Opera and Ballet Theatre, 54 Tumanyan Street",
        organizer: "Spendiaryan National Academic Opera and Ballet Theatre",
        category: "Opera and ballet",
        body: [
          "Turandot, the opera Puccini left unfinished at his death, in the Yerevan staging by Vyacheslav Starodubtsev. Sets and costumes are by Pyotr Okunev, lighting by Sergei Skornetsky and video by Vadim Dulenko.",
          "Karen Durgaryan is music director and conductor, with Harutyun Arzumanyan and Vardan Grigoryan also conducting; Hrach Boryan is chorus master.",
          "## Date",
          "22 October at 19:00. Three acts and two intervals, 2 hours 50 minutes in all. Tickets cost 5,000 to 15,000 drams.",
        ],
        faq: [
          { q: "How much are tickets?", a: "From 5,000 to 15,000 drams depending on the seat." },
          { q: "When is it on?", a: "On 22 October at 19:00." },
          { q: "How long is the opera?", a: "2 hours 50 minutes, with two intervals." },
        ],
      },
    },
  },

  {
    slug: "alice-sara-ott-symphonic-europe-yerevan-2026",
    createdAt: "2026-10-06T01:00:00+04:00",
    updatedAt: "2026-10-06T01:00:00+04:00",
    site: "tick",
    title: "«Սիմֆոնիկ Եվրոպա»՝ Ալիս Սառա Օտտ և Հայաստանի պետական սիմֆոնիկ նվագախումբ",
    titleSeo: "Ալիս Սառա Օտտ Երևանում՝ «Սիմֆոնիկ Եվրոպա»",
    cardTitle: "Ալիս Սառա Օտտ. Բեթհովեն",
    summary:
      "Դաշնակահար Ալիս Սառա Օտտը հոկտեմբերի 24-ին Երևանում է՝ Արամ Խաչատրյան համերգասրահում, Բեթհովենի Դաշնամուրի թիվ 4 կոնցերտով՝ Հայաստանի պետական սիմֆոնիկ նվագախմբի հետ։",
    start: "2026-10-24",
    startTime: "19:30",
    utcOffset: "+04:00",
    city: "Երևան",
    country: "Հայաստան",
    venue: "Արամ Խաչատրյան համերգասրահ, Մաշտոցի պող. 46",
    geo: { lat: 40.1862685, lng: 44.5151091 },
    organizer: "Հայաստանի պետական սիմֆոնիկ նվագախումբ",
    image: "/covers/alice-sara-ott-symphonic-europe-yerevan-2026.jpg",
    imageAlt: "Կարմիր ռոյալ՝ բաց կափարիչով, հետևում՝ բարձրացող ծովային ալիք",
    imageKind: "generated",
    imageWidth: 1536,
    imageHeight: 864,
    category: "Դասական երաժշտություն",
    tickets: { priceFrom: 3000, priceTo: 15000, currency: "AMD" },
    ticket: { url: "https://www.tomsarkgh.am/en/event/51579/", label: "Տոմսեր" },
    source: { name: "Tomsarkgh", url: "https://www.tomsarkgh.am/en/event/51579/", verifiedOn: "2026-10-06" },
    body: [
      "Հայաստանի պետական սիմֆոնիկ նվագախումբը և Հայաստանում Եվրոպական միության պատվիրակությունը «Սիմֆոնիկ Եվրոպա» երեկոն նվիրում են Հայաստանի և Եվրոպայի ժողովուրդների մշակութային կապերին։ Մենակատարը դաշնակահար Ալիս Սառա Օտտն է, դիրիժորը՝ Սերգեյ Սմբատյանը։",
      "## Ծրագիրը",
      "Բեթհովեն. «Կորիոլան» նախերգանք, երկ 62, և Դաշնամուրի կոնցերտ թիվ 4 սոլ մաժոր, երկ 58։ Ընդմիջումից հետո՝ Վերդիի «Սիցիլիական ժամերգություն» օպերայի նախերգանքը և Դեբյուսիի «Ծովը»՝ երեք սիմֆոնիկ էսքիզ նվագախմբի համար։",
      "Հոկտեմբերի 24-ին, ժամը 19:30-ին։ Տոմսերը 3000-ից 15000 դրամ են, երեխաների մուտքը՝ 6 տարեկանից։",
    ],
    faq: [
      { q: "Որքա՞ն արժե տոմսը", a: "3000-ից 15000 դրամ՝ կախված նստատեղից. վաճառվում են Tomsarkgh-ում և համերգասրահի տոմսարկղում։" },
      { q: "Ի՞նչ կնվագի Ալիս Սառա Օտտը", a: "Բեթհովենի Դաշնամուրի կոնցերտ թիվ 4 սոլ մաժոր։" },
      { q: "Կարելի՞ է գալ երեխաների հետ", a: "Այո, 6 տարեկանից. համերգը երկու բաժնով է՝ ընդմիջումով։" },
    ],
    i18n: {
      en: {
        imageAlt: "A red grand piano with its lid raised and a curling sea wave rising behind it",
        ticket: { url: "https://www.tomsarkgh.am/en/event/51579/", label: "Tickets" },
        title: "Symphonic Europe: Alice Sara Ott and the Armenian State Symphony Orchestra",
        titleSeo: "Alice Sara Ott in Yerevan: Symphonic Europe",
        cardTitle: "Alice Sara Ott plays Beethoven",
        summary:
          "Alice Sara Ott plays Beethoven's Fourth Piano Concerto in Yerevan on 24 October with the Armenian State Symphony Orchestra at the Aram Khachaturian Concert Hall.",
        city: "Yerevan",
        country: "Armenia",
        venue: "Aram Khachaturian Concert Hall, 46 Mashtots Avenue",
        organizer: "Armenian State Symphony Orchestra",
        category: "Classical",
        body: [
          "Symphonic Europe is the Armenian State Symphony Orchestra's evening with the Delegation of the European Union to Armenia, given over to the cultural ties between Armenia and Europe. The soloist is the pianist Alice Sara Ott, and Sergey Smbatyan conducts.",
          "## The programme",
          "Beethoven's Coriolan Overture, Op. 62, and his Piano Concerto No. 4 in G major, Op. 58. After the interval, Verdi's overture to The Sicilian Vespers and Debussy's La Mer, three symphonic sketches for orchestra.",
          "24 October at 19:30, with tickets from 3,000 to 15,000 drams. Children are admitted from the age of six.",
        ],
        faq: [
          { q: "How much are tickets?", a: "From 3,000 to 15,000 drams depending on the seat, on sale at Tomsarkgh and the concert hall's box office." },
          { q: "What does Alice Sara Ott play?", a: "Beethoven's Piano Concerto No. 4 in G major." },
          { q: "Can children come?", a: "Yes, from the age of six; the concert is in two halves with an interval." },
        ],
      },
    },
  },

  {
    slug: "yerevan-international-music-festival-iddo-bar-shai-2026",
    createdAt: "2026-10-06T01:00:00+04:00",
    updatedAt: "2026-10-06T01:00:00+04:00",
    site: "tick",
    title: "Երևանի 18-րդ միջազգային երաժշտական փառատոն. Իդդո Բար-Շայ",
    cardTitle: "Իդդո Բար-Շայ. փառատոնի երեկո",
    summary:
      "Երևանի 18-րդ միջազգային երաժշտական փառատոնի երեկոներից մեկը՝ հոկտեմբերի 16-ին Արամ Խաչատրյան համերգասրահում. դաշնակահար Իդդո Բար-Շայ, դիրիժոր Ջեք Գոնզալես-Հարդինգ։",
    start: "2026-10-16",
    startTime: "19:00",
    utcOffset: "+04:00",
    city: "Երևան",
    country: "Հայաստան",
    venue: "Արամ Խաչատրյան համերգասրահ, Մաշտոցի պող. 46",
    geo: { lat: 40.1862685, lng: 44.5151091 },
    organizer: "Հայաստանի ազգային ֆիլհարմոնիկ նվագախումբ",
    image: "/covers/yerevan-international-music-festival-iddo-bar-shai-2026.jpg",
    imageAlt: "Ռոյալ, որի վրայից հովհարի պես վեր են բարձրանում նոտաների թերթերը",
    imageKind: "generated",
    imageWidth: 1536,
    imageHeight: 864,
    category: "Դասական երաժշտություն",
    tickets: { priceFrom: 3000, priceTo: 15000, currency: "AMD" },
    ticket: { url: "https://www.tomsarkgh.am/en/event/51514/", label: "Տոմսեր" },
    source: { name: "Tomsarkgh", url: "https://www.tomsarkgh.am/en/event/51514/", verifiedOn: "2026-10-06" },
    body: [
      "Հոկտեմբերի 16-ին Երևանի 18-րդ միջազգային երաժշտական փառատոնի շրջանակում Հայաստանի ազգային ֆիլհարմոնիկ նվագախմբի հետ հանդես կգան դաշնակահար Իդդո Բար-Շայը և դիրիժոր Ջեք Գոնզալես-Հարդինգը։",
      "Այս տարի փառատոնը նվիրված է Հայաստանի Հանրապետության անկախության 35-ամյակին, հովանավորը VTB Armenia Bank-ն է։ Փառատոնը փակվում է նոյեմբերի 14-ին՝ Գրիգորի Սոկոլովի մենահամերգով։",
      "## Ծրագիրը և տոմսերը",
      "Համերգի ծրագիրը Tomsarkgh-ում դեռ հրապարակված չէ։ Սկիզբը ժամը 19:00-ին է, տոմսերը 3000-ից 15000 դրամ են։",
    ],
    faq: [
      { q: "Որքա՞ն արժե տոմսը", a: "Փառատոնի այս երեկոյի տոմսերը 3000-ից 15000 դրամ են։" },
      { q: "Ո՞վ է նվագում", a: "Դաշնակահար Իդդո Բար-Շայը՝ Հայաստանի ազգային ֆիլհարմոնիկ նվագախմբի հետ, դիրիժոր Ջեք Գոնզալես-Հարդինգ։" },
      { q: "Ե՞րբ է փակվում փառատոնը", a: "Նոյեմբերի 14-ին՝ Գրիգորի Սոկոլովի մենահամերգով։" },
    ],
    i18n: {
      en: {
        imageAlt: "A grand piano with sheets of music fanning up from it",
        ticket: { url: "https://www.tomsarkgh.am/en/event/51514/", label: "Tickets" },
        title: "18th Yerevan International Music Festival: Iddo Bar-Shai",
        cardTitle: "Iddo Bar-Shai at the festival",
        summary:
          "One evening of the 18th Yerevan International Music Festival: Iddo Bar-Shai plays with the Armenian National Philharmonic under Jack Gonzalez-Harding on 16 October.",
        city: "Yerevan",
        country: "Armenia",
        venue: "Aram Khachaturian Concert Hall, 46 Mashtots Avenue",
        organizer: "Armenian National Philharmonic Orchestra",
        category: "Classical",
        body: [
          "On 16 October, as part of the 18th Yerevan International Music Festival, the pianist Iddo Bar-Shai joins the Armenian National Philharmonic Orchestra under the conductor Jack Gonzalez-Harding.",
          "This year's festival is dedicated to the 35th anniversary of Armenia's independence, with VTB Armenia Bank as its sponsor. It closes on 14 November with a recital by Grigory Sokolov.",
          "## Programme and tickets",
          "The programme has not yet been published on Tomsarkgh. The concert starts at 19:00, and tickets cost 3,000 to 15,000 drams.",
        ],
        faq: [
          { q: "How much are tickets?", a: "Tickets for this festival evening cost 3,000 to 15,000 drams." },
          { q: "Who is playing?", a: "The pianist Iddo Bar-Shai, with the Armenian National Philharmonic Orchestra under Jack Gonzalez-Harding." },
          { q: "When does the festival close?", a: "On 14 November, with a recital by Grigory Sokolov." },
        ],
      },
    },
  },

  {
    slug: "star-wars-the-planets-yerevan-2026",
    createdAt: "2026-10-06T01:00:00+04:00",
    updatedAt: "2026-10-06T01:00:00+04:00",
    site: "tick",
    title: "«Աստղային պատերազմներ» և «Մոլորակները»՝ Արամ Խաչատրյան համերգասրահում",
    titleSeo: "«Աստղային պատերազմներ» և «Մոլորակները» Երևանում",
    cardTitle: "«Աստղային պատերազմներ» և «Մոլորակները»",
    summary:
      "Հոլստի «Մոլորակները» և Ջոն Ուիլյամսի «Աստղային պատերազմների» թեմաները Երևանում՝ հոկտեմբերի 28-ին Արամ Խաչատրյան համերգասրահում. նվագում է Հայաստանի պետական սիմֆոնիկ նվագախումբը։",
    start: "2026-10-28",
    startTime: "19:30",
    utcOffset: "+04:00",
    city: "Երևան",
    country: "Հայաստան",
    venue: "Արամ Խաչատրյան համերգասրահ, Մաշտոցի պող. 46",
    geo: { lat: 40.1862685, lng: 44.5151091 },
    organizer: "Հայաստանի պետական սիմֆոնիկ նվագախումբ",
    image: "/covers/star-wars-the-planets-yerevan-2026.jpg",
    imageAlt: "Տարբեր չափի մոլորակներ՝ աղեղով, գիշերային երկնքում, մեկը՝ օղակներով",
    imageKind: "generated",
    imageWidth: 1536,
    imageHeight: 864,
    category: "Դասական երաժշտություն",
    tickets: { priceFrom: 4000, priceTo: 25000, currency: "AMD" },
    ticket: { url: "https://www.tomsarkgh.am/en/event/51314/", label: "Տոմսեր" },
    source: { name: "Tomsarkgh", url: "https://www.tomsarkgh.am/en/event/51314/", verifiedOn: "2026-10-06" },
    body: [
      "Հայաստանի պետական սիմֆոնիկ նվագախումբը մեկ երեկոյում միավորում է Գուստավ Հոլստի «Մոլորակները» և Ջոն Ուիլյամսի ամենահայտնի կինոթեմաները։ Երաժշտությանը կուղեկցեն մոլորակների պատկերներ՝ համերգասրահի պատերին։ Դիրիժորը Սերգեյ Սմբատյանն է։",
      "## Ծրագիրը",
      "Առաջին բաժնում՝ Հոլստի «Մոլորակները» սյուիտը մեծ նվագախմբի համար, երկ 32 (56 րոպե)։ Ընդմիջումից հետո՝ Ուիլյամսի «Արկածները Երկրի վրա»՝ «Այլմոլորակայինը» ֆիլմից, ապա «Կայսերական երթը», «Աստղերի միջով», «Ճակատագրերի մենամարտը» և «Հիմնական թեման»՝ «Աստղային պատերազմներից»։",
      "Հոկտեմբերի 28-ին, ժամը 19:30-ին։ Տոմսերը 4000-ից 25000 դրամ են, երեխաների մուտքը՝ 6 տարեկանից։",
    ],
    faq: [
      { q: "Որքա՞ն արժե տոմսը", a: "4000-ից 25000 դրամ՝ կախված նստատեղից։" },
      { q: "Ի՞նչ կհնչի", a: "Հոլստի «Մոլորակները» և Ջոն Ուիլյամսի թեմաները «Աստղային պատերազմներից» և «Այլմոլորակայինից»։" },
      { q: "Կարելի՞ է գալ երեխաների հետ", a: "Այո, 6 տարեկանից. Հոլստը առաջին բաժնում է, «Աստղային պատերազմները»՝ ընդմիջումից հետո։" },
    ],
    i18n: {
      en: {
        imageAlt: "Planets of different sizes in an arc across a night sky, one of them ringed",
        ticket: { url: "https://www.tomsarkgh.am/en/event/51314/", label: "Tickets" },
        title: "Star Wars and The Planets at the Aram Khachaturian Concert Hall",
        titleSeo: "Star Wars and The Planets in Yerevan",
        cardTitle: "Star Wars and The Planets",
        summary:
          "Holst's The Planets and John Williams's Star Wars themes in Yerevan on 28 October, played by the Armenian State Symphony Orchestra at the Aram Khachaturian Concert Hall.",
        city: "Yerevan",
        country: "Armenia",
        venue: "Aram Khachaturian Concert Hall, 46 Mashtots Avenue",
        organizer: "Armenian State Symphony Orchestra",
        category: "Classical",
        body: [
          "The Armenian State Symphony Orchestra puts Gustav Holst's The Planets and John Williams's best-known film themes on one programme, with images of the planets projected onto the walls of the hall. Sergey Smbatyan conducts.",
          "## The programme",
          "First half: Holst's The Planets, Op. 32 (56 minutes). After the interval, Williams: Adventures on Earth from E.T., then the Imperial March, Across the Stars, Duel of the Fates and the Main Title from Star Wars.",
          "28 October at 19:30, with tickets from 4,000 to 25,000 drams. Children are admitted from six — which, for this programme, seems rather the point.",
        ],
        faq: [
          { q: "How much are tickets?", a: "From 4,000 to 25,000 drams depending on the seat." },
          { q: "What is played?", a: "Holst's The Planets, and John Williams's themes from Star Wars and E.T." },
          { q: "Can children come?", a: "Yes, from the age of six. Holst fills the first half; Star Wars comes after the interval." },
        ],
      },
    },
  },

  {
    slug: "nervy-yerevan-2026",
    createdAt: "2026-10-06T01:00:00+04:00",
    updatedAt: "2026-10-06T01:00:00+04:00",
    site: "tick",
    title: "Nervy ռոք խումբը Երևանում",
    cardTitle: "Nervy",
    summary:
      "Nervy (Нервы) ռոք խմբի համերգը Երևանում՝ նոյեմբերի 7-ին Eventhub Yerevan-ում. տոմսերը՝ 20000 դրամից, կան նաև ինքնագրերով աֆիշայով և Meet & Greet-ով տարբերակներ։",
    start: "2026-11-07",
    startTime: "20:00",
    utcOffset: "+04:00",
    city: "Երևան",
    country: "Հայաստան",
    venue: "Eventhub Yerevan, Ավետիս Ահարոնյան 3/8",
    organizer: "Դենիս Նեդորեզով ԱՁ",
    image: "/covers/nervy-yerevan-2026.jpg",
    imageAlt: "Կարմիր էլեկտրական կիթառ՝ դատարկ բեմի վրա, կամարավոր մուտքի առջև",
    imageKind: "generated",
    imageWidth: 1536,
    imageHeight: 864,
    category: "Համերգներ",
    tickets: { priceFrom: 20000, priceTo: 120000, currency: "AMD" },
    ticket: { url: "https://www.tomsarkgh.am/en/event/51482/", label: "Տոմսեր" },
    source: { name: "Tomsarkgh", url: "https://www.tomsarkgh.am/en/event/51482/", verifiedOn: "2026-10-06" },
    body: [
      "Nervy ռոք խումբը նոյեմբերի 7-ին համերգ է տալիս Երևանում՝ Eventhub Yerevan-ում, Ավետիս Ահարոնյան 3/8 հասցեում։ Սկիզբը ժամը 20:00-ին է։",
      "Կազմակերպիչներն այն ներկայացնում են որպես ռոք՝ առանց դիմակների. բարձր կիթառներ, անկեղծ խոսքեր և համերգ, որտեղ բեմի և դահլիճի միջև հեռավորություն չկա։",
      "## Տոմսերը",
      "Պարահրապարակ՝ 20000 դրամ, բալկոն՝ 28000 դրամ։ Ինքնագրերով աֆիշայով՝ 30000 և 38000 դրամ, Meet & Greet-ով՝ 110000 և 120000 դրամ։",
    ],
    faq: [
      { q: "Որքա՞ն արժե տոմսը", a: "Պարահրապարակը՝ 20000 դրամ, բալկոնը՝ 28000 դրամ. ինքնագրերով աֆիշայով և Meet & Greet-ով տոմսերն ավելի թանկ են՝ մինչև 120000 դրամ։" },
      { q: "Ե՞րբ է սկսվում համերգը", a: "Նոյեմբերի 7-ին, ժամը 20:00-ին։" },
      { q: "Կա՞ տարիքային սահմանափակում", a: "Tomsarkgh-ում համերգը նշված է 0+։" },
    ],
    i18n: {
      en: {
        imageAlt: "A red electric guitar standing on an empty stage before an arched doorway",
        ticket: { url: "https://www.tomsarkgh.am/en/event/51482/", label: "Tickets" },
        title: "Nervy in concert in Yerevan",
        cardTitle: "Nervy",
        summary:
          "The rock band Nervy (Нервы) plays Yerevan on 7 November at Eventhub Yerevan, with tickets from 20,000 drams and signed-poster and meet-and-greet options.",
        city: "Yerevan",
        country: "Armenia",
        venue: "Eventhub Yerevan, 3/8 Avetis Aharonyan Street",
        organizer: "Denis Nedorezov (sole proprietor)",
        category: "Concerts",
        body: [
          "The rock band Nervy plays Yerevan on 7 November, at Eventhub Yerevan on Avetis Aharonyan Street, from 20:00.",
          "The organisers bill it as rock without masks: loud guitars, plain-spoken lyrics and no distance between the stage and the crowd.",
          "## Tickets",
          "Dance floor 20,000 drams, balcony 28,000. With a signed poster, 30,000 and 38,000; with a meet-and-greet, 110,000 and 120,000.",
        ],
        faq: [
          { q: "How much are tickets?", a: "20,000 drams for the dance floor and 28,000 for the balcony; signed-poster and meet-and-greet tickets cost more, up to 120,000." },
          { q: "What time does it start?", a: "At 20:00 on 7 November." },
          { q: "Is there an age limit?", a: "The box office lists it as 0+." },
        ],
      },
    },
  },

  {
    slug: "harvest-fest-van-ardi-2026",
    createdAt: "2026-10-06T01:00:00+04:00",
    updatedAt: "2026-10-06T01:00:00+04:00",
    site: "tick",
    title: "Բերքի փառատոն Վան Արդիում",
    titleSeo: "Բերքի փառատոն Վան Արդի գինեգործարանում՝ Երևանի մոտ",
    cardTitle: "Բերքի փառատոն Վան Արդիում",
    summary:
      "Բերքի փառատոն Վան Արդի գինեգործարանում՝ Երևանից ոչ հեռու, Սասունիկում, հոկտեմբերի 17-ին. կենդանի երաժշտություն, դդմի փորագրություն, գինի և խարույկ, տոմսերը՝ 5000 դրամից։",
    start: "2026-10-17",
    startTime: "13:00",
    endTime: "18:00",
    utcOffset: "+04:00",
    city: "Սասունիկ",
    country: "Հայաստան",
    venue: "Վան Արդի գինեգործարան, Սասունիկ, Արագածոտնի մարզ",
    organizer: "Van Ardi",
    image: "/covers/harvest-fest-van-ardi-2026.jpg",
    imageAlt: "Աշնանային ոսկեգույն խաղողի այգու շարքեր, առջևում՝ գինու շիշ, բաժակ և խարույկ",
    imageKind: "generated",
    imageWidth: 1536,
    imageHeight: 864,
    category: "Փառատոներ",
    tickets: { priceFrom: 5000, priceTo: 7000, currency: "AMD" },
    ticket: { url: "https://www.tomsarkgh.am/en/event/51649/", label: "Տոմսեր" },
    source: { name: "Tomsarkgh", url: "https://www.tomsarkgh.am/en/event/51649/", verifiedOn: "2026-10-06" },
    body: [
      "Վան Արդի գինեգործարանը նշում է 2026 թվականի բերքահավաքի ավարտը՝ աշնանային մի ամբողջ օր իր այգիներում, Արագածոտնի մարզի Սասունիկ գյուղում։",
      "Ծրագրում՝ կենդանի երաժշտություն ամբողջ օրը, դդմի փորագրություն, մրցանակներով խաղեր, ստեղծագործական անկյուն, որտեղ կարելի է նկարազարդել սեփական գինու շիշը, սեզոնային ուտեստներ, Վան Արդիի գինիներ և խարույկ։ Փառատոնը բոլոր տարիքների համար է։",
      "## Ժամը և տոմսերը",
      "Հոկտեմբերի 17-ին, 13:00-ից 18:00։ Վաղ տոմսը 5000 դրամ է՝ առցանց, մինչև հոկտեմբերի 10-ը, սովորական մուտքը՝ 7000 դրամ։ Տոմսը ներառում է մուտքը և երաժշտությունը. ուտելիքը և որոշ վարպետաց դասեր ու խաղեր վճարովի են առանձին։",
    ],
    faq: [
      { q: "Որքա՞ն արժե տոմսը", a: "5000 դրամ՝ առցանց, մինչև հոկտեմբերի 10-ը, այնուհետև 7000 դրամ։" },
      { q: "Որտե՞ղ է Վան Արդին", a: "Արագածոտնի մարզի Սասունիկ գյուղում՝ Երևանից ոչ հեռու։" },
      { q: "Կարելի՞ է գալ երեխաների հետ", a: "Այո, փառատոնը բոլոր տարիքների համար է։" },
    ],
    i18n: {
      en: {
        imageAlt: "Rows of golden autumn vines, with a wine bottle, a glass and a bonfire in front",
        ticket: { url: "https://www.tomsarkgh.am/en/event/51649/", label: "Tickets" },
        title: "Harvest Fest at Van Ardi",
        titleSeo: "Harvest Fest at Van Ardi winery, near Yerevan",
        cardTitle: "Harvest Fest at Van Ardi",
        summary:
          "Van Ardi winery celebrates the 2026 harvest at Sasunik, a short drive from Yerevan, on 17 October: live music, pumpkin carving, wine and a bonfire, from 5,000 drams.",
        city: "Sasunik",
        country: "Armenia",
        venue: "Van Ardi Winery, Sasunik, Aragatsotn province",
        organizer: "Van Ardi",
        category: "Festivals",
        body: [
          "Van Ardi marks the end of the 2026 harvest with a day in its vineyards at Sasunik, in the Aragatsotn province.",
          "Live music all afternoon, pumpkin carving, games with prizes, an art station where one may paint one's own wine bottle, seasonal food, Van Ardi's wines and a bonfire. It is meant for all ages.",
          "## Times and tickets",
          "17 October, 13:00 to 18:00. An early-bird ticket is 5,000 drams online until 10 October; after that, 7,000. The pass covers entry and the music; food and some of the masterclasses and games are extra.",
        ],
        faq: [
          { q: "How much are tickets?", a: "5,000 drams online until 10 October, then 7,000 drams." },
          { q: "Where is Van Ardi?", a: "At Sasunik, in the Aragatsotn province, a short drive from Yerevan." },
          { q: "Can children come?", a: "Yes, it is meant for all ages." },
        ],
      },
    },
  },

  {
    slug: "halloween-oxygen-yerevan-2026",
    createdAt: "2026-10-06T01:00:00+04:00",
    updatedAt: "2026-10-06T01:00:00+04:00",
    site: "tick",
    title: "Հելոուին Oxygen-ում",
    titleSeo: "Հելոուին Երևանում՝ Oxygen-ում, հոկտեմբերի 31",
    cardTitle: "Հելոուին Oxygen-ում",
    summary:
      "Հելոուինի երեկույթ Երևանում՝ հոկտեմբերի 31-ին Oxygen-ում. KAI, T_GRAN, LIL. WAVE և DES1GNER, Հելոուինի դրես-կոդ, մուտքը՝ խստորեն 18 տարեկանից։",
    start: "2026-10-31",
    startTime: "18:00",
    utcOffset: "+04:00",
    city: "Երևան",
    country: "Հայաստան",
    venue: "Oxygen",
    organizer: "TRAP DOM × KAUFMAN × OXYGEN",
    image: "/covers/halloween-oxygen-yerevan-2026.jpg",
    imageAlt: "Փորագրված դդում՝ պարահրապարակի վրա, վերևում՝ հայելային գունդ և չղջիկներ",
    imageKind: "generated",
    imageWidth: 1536,
    imageHeight: 864,
    category: "Երեկույթներ",
    tickets: { priceFrom: 4000, priceTo: 6000, currency: "AMD" },
    ticket: { url: "https://www.tomsarkgh.am/en/event/51668/", label: "Տոմսեր" },
    source: { name: "Tomsarkgh", url: "https://www.tomsarkgh.am/en/event/51668/", verifiedOn: "2026-10-06" },
    speakersHeading: "Կատարողներ",
    speakers: [{ name: "KAI" }, { name: "T_GRAN" }, { name: "LIL. WAVE" }, { name: "DES1GNER" }],
    body: [
      "Հոկտեմբերի 31-ին Oxygen-ը նշում է Հելոուինը։ Line-up-ում են KAI-ը, T_GRAN-ը, LIL. WAVE-ը և DES1GNER-ը, սկիզբը՝ ժամը 18:00-ին։ Կազմակերպիչները TRAP DOM-ը, KAUFMAN-ը և OXYGEN-ն են։",
      "Դրես-կոդը Հելոուինն է. թեմատիկ կերպարներն ու կոստյումները ողջունվում են։",
      "## Մուտքը",
      "Մուտքը խստորեն 18 տարեկանից է, անձը հաստատող փաստաթղթով։ Տղամարդիկ մուտք են գործում միայն զույգով, աղջիկները՝ ցանկացած կազմով։ Տոմսը 4000 դրամ է մինչև հոկտեմբերի 31-ը, իսկ հոկտեմբերի 31-ին մուտքի մոտ՝ 6000 դրամ։",
    ],
    faq: [
      { q: "Որքա՞ն արժե տոմսը", a: "4000 դրամ՝ նախապես, 6000 դրամ՝ հոկտեմբերի 31-ին մուտքի մոտ։" },
      { q: "Կա՞ տարիքային սահմանափակում", a: "Այո, մուտքը խստորեն 18 տարեկանից է, անձը հաստատող փաստաթղթով։" },
      { q: "Կա՞ դրես-կոդ", a: "Այո, Հելոուին. կոստյումները ողջունվում են։" },
    ],
    i18n: {
      en: {
        imageAlt: "A carved pumpkin on a dance floor, with a mirror ball and bats above it",
        ticket: { url: "https://www.tomsarkgh.am/en/event/51668/", label: "Tickets" },
        title: "Halloween at Oxygen",
        titleSeo: "Halloween in Yerevan: Oxygen on 31 October",
        cardTitle: "Halloween at Oxygen",
        summary:
          "A Halloween party in Yerevan on 31 October at Oxygen, with KAI, T_GRAN, LIL. WAVE and DES1GNER, a Halloween dress code and entry strictly for over-18s.",
        city: "Yerevan",
        country: "Armenia",
        venue: "Oxygen",
        organizer: "TRAP DOM × KAUFMAN × OXYGEN",
        category: "Parties",
        speakersHeading: "Line-up",
        speakers: [{ name: "KAI" }, { name: "T_GRAN" }, { name: "LIL. WAVE" }, { name: "DES1GNER" }],
        body: [
          "Oxygen marks Halloween on 31 October with KAI, T_GRAN, LIL. WAVE and DES1GNER from 18:00, organised by TRAP DOM, KAUFMAN and Oxygen.",
          "The dress code is Halloween, and costumes are positively encouraged.",
          "## Getting in",
          "Strictly over-18s, with photo ID at the door. Men are admitted only as part of a couple; women in any number. A ticket is 4,000 drams until 31 October and 6,000 at the door on the night.",
        ],
        faq: [
          { q: "How much are tickets?", a: "4,000 drams in advance, 6,000 at the door on 31 October." },
          { q: "Is there an age limit?", a: "Yes, strictly over-18s, with photo ID." },
          { q: "Is there a dress code?", a: "Yes, Halloween; costumes are encouraged." },
        ],
      },
    },
  },

  {
    slug: "hamlet-ghaplanyan-theatre-2026",
    createdAt: "2026-10-06T01:00:00+04:00",
    updatedAt: "2026-10-06T01:00:00+04:00",
    site: "tick",
    title: "«Համլետ»՝ Ղափլանյանի թատրոնում",
    titleSeo: "«Համլետ»՝ Երևանի Ղափլանյանի թատրոնում",
    cardTitle: "«Համլետ»՝ Ղափլանյանի թատրոնում",
    summary:
      "Շեքսպիրի «Համլետը» Երևանում՝ հոկտեմբերի 24-ին և նոյեմբերի 4-ին Հրաչյա Ղափլանյանի անվան դրամատիկական թատրոնում, Գրիգոր Խաչատրյանի բեմադրությամբ. Համլետ՝ Լիդիա Գրիգորյան։",
    start: "2026-10-24",
    startTime: "19:30",
    utcOffset: "+04:00",
    city: "Երևան",
    country: "Հայաստան",
    venue: "Հրաչյա Ղափլանյանի անվան դրամատիկական թատրոն",
    organizer: "Հրաչյա Ղափլանյանի անվան դրամատիկական թատրոն",
    image: "/covers/hamlet-ghaplanyan-theatre-2026.jpg",
    imageAlt: "Գանգ՝ բաց գրքի վրա, դատարկ բեմի վրա ընկնող լույսի շերտի տակ",
    imageKind: "generated",
    imageWidth: 1536,
    imageHeight: 864,
    category: "Թատրոն",
    tickets: { priceFrom: 3000, priceTo: 6000, currency: "AMD" },
    ticket: { url: "https://www.tomsarkgh.am/en/event/47889/", label: "Տոմսեր" },
    source: { name: "Tomsarkgh", url: "https://www.tomsarkgh.am/en/event/47889/", verifiedOn: "2026-10-06" },
    body: [
      "Ղափլանյանի թատրոնի «Համլետի» բեմական տարբերակն ու բեմադրությունը Գրիգոր Խաչատրյանինն են։ Համլետին խաղում է դերասանուհի Լիդիա Գրիգորյանը։",
      "## Դերերում",
      "Թագավոր՝ Գագիկ Մկրտչյան, թագուհի՝ Լուիզա Ղամբարյան կամ Լիդա Լևոնյան, Պոլոնիուս՝ Վիլեն Սարգսյան, Լաերտ՝ Արմեն Մեսրոբյան, Օֆելիա՝ Դիանա Մալենկո։ Ռոզենկրանցին և Գիլդենշտերնին խաղում են Վլադիմիր Մսրյանը և Վահագն Սամվելյանը, գերեզմանափորին՝ Ռոբերտ Զախարյանը, ուրվականին՝ Նիկոլայ Ավետիսյանը։",
      "Հոկտեմբերի 24-ին և նոյեմբերի 4-ին, ժամը 19:30-ին։ Տոմսերը 3000-ից 6000 դրամ են։ Մինչև 14 տարեկանների մուտքն արգելված է։",
    ],
    faq: [
      { q: "Որքա՞ն արժե տոմսը", a: "3000-ից 6000 դրամ՝ կախված նստատեղից։" },
      { q: "Ո՞վ է խաղում Համլետին", a: "Դերասանուհի Լիդիա Գրիգորյանը։" },
      { q: "Կա՞ տարիքային սահմանափակում", a: "Այո, մինչև 14 տարեկանների մուտքն արգելված է։" },
    ],
    i18n: {
      en: {
        imageAlt: "A skull on an open book on a bare stage, under a shaft of light",
        ticket: { url: "https://www.tomsarkgh.am/en/event/47889/", label: "Tickets" },
        title: "Hamlet at the Ghaplanyan Theatre",
        titleSeo: "Hamlet at the Ghaplanyan Theatre, Yerevan",
        cardTitle: "Hamlet at the Ghaplanyan",
        summary:
          "Shakespeare's Hamlet in Yerevan on 24 October and 4 November at the Hrachya Ghaplanyan Drama Theatre, staged by Grigor Khachatryan, with Lidia Grigoryan as Hamlet.",
        city: "Yerevan",
        country: "Armenia",
        venue: "Hrachya Ghaplanyan Drama Theatre",
        organizer: "Hrachya Ghaplanyan Drama Theatre",
        category: "Theatre",
        body: [
          "The Ghaplanyan Theatre's Hamlet is Grigor Khachatryan's, both the stage version and the production, and the prince is played by an actress, Lidia Grigoryan.",
          "## The cast",
          "Gagik Mkrtchyan is the King and Luiza Ghambaryan or Lida Levonyan the Queen; Vilen Sargsyan plays Polonius, Armen Mesrobyan Laertes and Diana Malenko Ophelia. Vladimir Msryan and Vahagn Samvelyan are Rosencrantz and Guildenstern, Robert Zakharyan the Gravedigger and Nikolay Avetisyan the Ghost.",
          "24 October and 4 November at 19:30, with tickets from 3,000 to 6,000 drams. Nobody under 14 is admitted. The listing is in Armenian alone, which is a fair guide to the language on stage.",
        ],
        faq: [
          { q: "How much are tickets?", a: "From 3,000 to 6,000 drams depending on the seat." },
          { q: "Who plays Hamlet?", a: "The actress Lidia Grigoryan." },
          { q: "Is there an age limit?", a: "Yes, nobody under 14 is admitted." },
        ],
      },
    },
  },

  {
    slug: "shooting-la-la-land-paronyan-2026",
    createdAt: "2026-10-06T01:00:00+04:00",
    updatedAt: "2026-10-06T01:00:00+04:00",
    site: "tick",
    title: "«Նկարում ենք Լա Լա Լենդը»՝ Պարոնյանի թատրոնում",
    cardTitle: "«Նկարում ենք Լա Լա Լենդը»",
    summary:
      "«Լա Լա Լենդ»-ի մասին մյուզիքլ Երևանում՝ նոյեմբերի 14-ին Պարոնյանի անվան երաժշտական կոմեդիայի թատրոնում, Լիլի Էլբակյանի բեմադրությամբ. գլխավոր դերերում՝ Ներսես Ավետիսյան և Մարիամ Շահինյան։",
    start: "2026-11-14",
    startTime: "19:00",
    utcOffset: "+04:00",
    city: "Երևան",
    country: "Հայաստան",
    venue: "Հակոբ Պարոնյանի անվան երաժշտական կոմեդիայի պետական թատրոն",
    organizer: "Հակոբ Պարոնյանի անվան երաժշտական կոմեդիայի պետական թատրոն",
    image: "/covers/shooting-la-la-land-paronyan-2026.jpg",
    imageAlt: "Հին կինոխցիկ՝ եռոտանու վրա, կողքին՝ լապտերասյուն, հետևում՝ աստղազարդ երկինք",
    imageKind: "generated",
    imageWidth: 1536,
    imageHeight: 864,
    category: "Թատրոն",
    tickets: { priceFrom: 3000, priceTo: 12000, currency: "AMD" },
    ticket: { url: "https://www.tomsarkgh.am/en/event/51492/", label: "Տոմսեր" },
    source: { name: "Tomsarkgh", url: "https://www.tomsarkgh.am/en/event/51492/", verifiedOn: "2026-10-06" },
    body: [
      "«Նկարում ենք Լա Լա Լենդը» մյուզիքլ է «Լա Լա Լենդ» ֆիլմի ստեղծման մասին. ֆիլմի պրեմիերայից տասը տարի անց հանդիսատեսը հայտնվում է հենց նկարահանման կենտրոնում, և ֆիլմը ծնվում է բեմի վրա։",
      "Բեմադրող ռեժիսորը Լիլի Էլբակյանն է, գլխավոր դերերում՝ Ներսես Ավետիսյան և Մարիամ Շահինյան։ Նոր երգերի և ադապտացիայի հեղինակը Մարիամ Շահինյանն է, բեմանկարչությունն ու անիմացիան՝ Մարիամ Մուրադյանի, պարուսույցը՝ Քրիստինա Ավագիմյանի։ Մասնակցում է թատրոնի բալետային խումբը։",
      "## Տոմսերը",
      "Նոյեմբերի 14-ին, ժամը 19:00-ին։ Տոմսերը 3000-ից 12000 դրամ են։ Ներկայացումը 14+ է, իսկ ուշացողներին դահլիճ չեն թողնում։",
    ],
    faq: [
      { q: "Որքա՞ն արժե տոմսը", a: "3000-ից 12000 դրամ՝ կախված նստատեղից։" },
      { q: "Ո՞վ է խաղում գլխավոր դերերում", a: "Ներսես Ավետիսյանը և Մարիամ Շահինյանը։" },
      { q: "Կա՞ տարիքային սահմանափակում", a: "Այո, 14+։" },
    ],
    i18n: {
      en: {
        imageAlt: "An old film camera on a tripod beside a streetlamp, under a starry sky",
        ticket: { url: "https://www.tomsarkgh.am/en/event/51492/", label: "Tickets" },
        title: "Shooting La La Land at the Paronyan Theatre",
        cardTitle: "Shooting La La Land",
        summary:
          "A La La Land musical in Yerevan on 14 November at the Paronyan Musical Comedy Theatre, directed by Lili Elbakyan, with Nerses Avetisyan and Mariam Shahinyan in the leads.",
        city: "Yerevan",
        country: "Armenia",
        venue: "Hakob Paronyan State Musical Comedy Theatre",
        organizer: "Hakob Paronyan State Musical Comedy Theatre",
        category: "Theatre",
        body: [
          "Shooting La La Land is a musical about the making of the film: ten years after La La Land's premiere, the audience is put at the centre of the shoot, and the film comes together on stage in front of them.",
          "Lili Elbakyan directs, with Nerses Avetisyan and Mariam Shahinyan in the leads. Mariam Shahinyan also wrote the new songs and the adaptation; Mariam Muradyan did the set and the animation and Christina Avagimyan the choreography, and the theatre's ballet troupe takes part.",
          "## Tickets",
          "14 November at 19:00, with tickets from 3,000 to 12,000 drams. It is rated 14+, and latecomers are not admitted — so do be prompt.",
        ],
        faq: [
          { q: "How much are tickets?", a: "From 3,000 to 12,000 drams depending on the seat." },
          { q: "Who is in the leads?", a: "Nerses Avetisyan and Mariam Shahinyan." },
          { q: "Is there an age limit?", a: "Yes, it is rated 14+." },
        ],
      },
    },
  },

  {
    slug: "pagliacci-yerevan-opera-2026",
    createdAt: "2026-10-06T20:15:00+04:00",
    updatedAt: "2026-10-06T20:15:00+04:00",
    site: "tick",
    title: "Լեոնկավալո. «Պայացներ»՝ Երևանի օպերային թատրոնում",
    titleSeo: "«Պայացներ»՝ Երևանի օպերային թատրոնում",
    cardTitle: "Լեոնկավալո. «Պայացներ»",
    summary:
      "Լեոնկավալոյի «Պայացներ» օպերան Երևանում՝ հոկտեմբերի 8-ին և նոյեմբերի 17-ին Սպենդիարյանի անվան օպերայի և բալետի թատրոնում, իտալացի ռեժիսոր Մարիո Ակամպայի բեմադրությամբ։",
    start: "2026-10-08",
    startTime: "19:00",
    utcOffset: "+04:00",
    city: "Երևան",
    country: "Հայաստան",
    venue: "Ալ. Սպենդիարյանի անվան օպերայի և բալետի ազգային ակադեմիական թատրոն, Թումանյան 54",
    geo: { lat: 40.1862685, lng: 44.5151091 },
    organizer: "Ալ. Սպենդիարյանի անվան օպերայի և բալետի ազգային ակադեմիական թատրոն",
    category: "Օպերա և բալետ",
    tickets: { priceFrom: 4000, priceTo: 15000, currency: "AMD" },
    ticket: { url: "https://www.tomsarkgh.am/en/event/50346/", label: "Տոմսեր" },
    source: { name: "Tomsarkgh", url: "https://www.tomsarkgh.am/en/event/50346/", verifiedOn: "2026-10-06" },
    body: [
      "Ռուջերո Լեոնկավալոյի «Պայացները» օպերա է, որտեղ բեմն ու իրականությունը միաձուլվում են, իսկ ծիծաղը վերածվում է ողբերգության։ Երևանի օպերային թատրոնում այն բեմադրել է իտալացի ռեժիսոր Մարիո Ակամպան, որը նաև լուսային նկարիչն է։",
      "Բեմի նկարիչը Էլեոնորա Պերոնետին է, զգեստների նկարիչը՝ Քիարա Ամալտեա Չիարելին՝ երկուսն էլ Իտալիայից։ Երաժշտական ղեկավարն ու դիրիժորը Կարեն Դուրգարյանն է, երգչախմբի ղեկավարը՝ Նարինե Ոսկանյանը, մանկական երգչախմբի ղեկավարը՝ Էմմա Առաքելյանը։",
      "## Երբ",
      "Հոկտեմբերի 8-ին և նոյեմբերի 17-ին, ժամը 19:00-ին։ Օպերան երկու գործողությամբ է և մեկ ընդմիջումով, ընդհանուր տևողությունը՝ 1 ժամ 55 րոպե։ Տոմսերը 4000-ից 15000 դրամ են։",
    ],
    faq: [
      { q: "Որքա՞ն արժե տոմսը", a: "4000-ից 15000 դրամ՝ կախված նստատեղից։" },
      { q: "Ե՞րբ է ներկայացումը", a: "Հոկտեմբերի 8-ին և նոյեմբերի 17-ին, ժամը 19:00-ին։" },
      { q: "Որքա՞ն է տևում օպերան", a: "1 ժամ 55 րոպե՝ մեկ ընդմիջումով։" },
    ],
    i18n: {
      en: {
        ticket: { url: "https://www.tomsarkgh.am/en/event/50346/", label: "Tickets" },
        title: "Leoncavallo's Pagliacci at the Yerevan Opera",
        titleSeo: "Pagliacci at the Yerevan Opera",
        cardTitle: "Leoncavallo: Pagliacci",
        summary:
          "Leoncavallo's Pagliacci in Yerevan on 8 October and 17 November at the Spendiaryan Opera and Ballet Theatre, staged by the Italian director Mario Acampa.",
        city: "Yerevan",
        country: "Armenia",
        venue: "Spendiaryan Opera and Ballet Theatre, 54 Tumanyan Street",
        organizer: "Spendiaryan National Academic Opera and Ballet Theatre",
        category: "Opera and ballet",
        body: [
          "Ruggero Leoncavallo's Pagliacci is the opera in which the stage and real life run together and the laughter turns to tragedy. The Yerevan Opera's production is by the Italian director Mario Acampa, who lights it as well.",
          "The set is by Eleonora Peronetti and the costumes by Chiara Amaltea Ciarelli, both from Italy. Karen Durgaryan is music director and conductor; Narine Voskanyan leads the chorus and Emma Arakelyan the children's chorus.",
          "## Dates",
          "8 October and 17 November at 19:00. Two acts and one interval, 1 hour 55 minutes in all — rather a brisk evening by operatic standards. Tickets cost 4,000 to 15,000 drams.",
        ],
        faq: [
          { q: "How much are tickets?", a: "From 4,000 to 15,000 drams depending on the seat." },
          { q: "When is it on?", a: "On 8 October and 17 November, at 19:00." },
          { q: "How long is the opera?", a: "1 hour 55 minutes, with one interval." },
        ],
      },
    },
  },

  {
    slug: "bakian-sings-aznavour-yerevan-2026",
    createdAt: "2026-10-06T20:15:00+04:00",
    updatedAt: "2026-10-06T20:15:00+04:00",
    site: "tick",
    title: "Bakian sings Aznavour. Ազնավուրի երգերը Երևանում",
    cardTitle: "Bakian sings Aznavour",
    summary:
      "Ֆրանսահայ երգիչ Բաքիանը հոկտեմբերի 15-ին Երևանում է՝ Ֆիլհարմոնիայի Բաբաջանյան համերգասրահում, Շառլ Ազնավուրի երգերով, այդ թվում՝ Ազնավուրի կողմից իրեն վստահված երեքը։",
    start: "2026-10-15",
    startTime: "19:00",
    utcOffset: "+04:00",
    city: "Երևան",
    country: "Հայաստան",
    venue: "Հայաստանի պետական ֆիլհարմոնիա, Բաբաջանյան համերգասրահ",
    organizer: "Հայաստանի պետական ֆիլհարմոնիա",
    category: "Համերգներ",
    tickets: { priceFrom: 10000, priceTo: 10000, currency: "AMD" },
    ticket: { url: "https://www.tomsarkgh.am/en/event/51599/", label: "Տոմսեր" },
    source: { name: "Tomsarkgh", url: "https://www.tomsarkgh.am/en/event/51599/", verifiedOn: "2026-10-06" },
    speakersHeading: "Կատարողներ",
    speakers: [
      { name: "Բաքիան", note: "Վոկալ" },
      { name: "Միկաել Սերրա", note: "Կիթառ" },
      { name: "Անտուան Ժերեմիա", note: "Դաշնամուր" },
    ],
    body: [
      "Bakian sings Aznavour-ը Շառլ Ազնավուրին նվիրված համերգային նախագիծ է՝ ֆրանսահայ երգիչ Բաքիանի կատարմամբ։ Նրանց ստեղծագործական մտերմությունը սկսվել է Բաքիանի պատանեկության տարիներին և շարունակվել շուրջ երեք տարի. այդ ընթացքում Ազնավուրը նրան է վստահել իր երեք դեռևս չհրապարակված երգերը։",
      "## Ինչ կհնչի",
      "Ազնավուրի հանրահայտ երգերի հետ կհնչեն նաև Բաքիանին նվիրված այդ երեք երգերը, իսկ արտիստը կպատմի դրանց ստեղծման մասին և կկիսվի Ազնավուրի հետ կապված անձնական հուշերով։ Կիթառը՝ Միկաել Սերրա, դաշնամուրը՝ Անտուան Ժերեմիա։ Նախագիծն իրականացվում է Seiya Records-ի և Aznavour pour l’Amour-ի հետ համագործակցությամբ։",
      "## Երբ և որտեղ",
      "Հոկտեմբերի 15-ին, ժամը 19:00-ին, Հայաստանի պետական ֆիլհարմոնիայի Բաբաջանյան համերգասրահում։ Տոմսն արժե 10000 դրամ։",
    ],
    faq: [
      { q: "Որքա՞ն արժե տոմսը", a: "10000 դրամ։" },
      { q: "Ե՞րբ է համերգը", a: "Հոկտեմբերի 15-ին, ժամը 19:00-ին։" },
      { q: "Ի՞նչ կհնչի", a: "Ազնավուրի հայտնի երգերը և երեք երգ, որոնք Ազնավուրը վստահել է Բաքիանին։" },
    ],
    i18n: {
      en: {
        ticket: { url: "https://www.tomsarkgh.am/en/event/51599/", label: "Tickets" },
        title: "Bakian sings Aznavour in Yerevan",
        cardTitle: "Bakian sings Aznavour",
        summary:
          "The French-Armenian singer Bakian brings his Charles Aznavour tribute to Yerevan on 15 October, at the Philharmonia's Babajanyan Concert Hall, with three songs Aznavour gave him.",
        city: "Yerevan",
        country: "Armenia",
        venue: "Armenian State Philharmonia, Babajanyan Concert Hall",
        organizer: "Armenian State Philharmonia",
        category: "Concerts",
        speakersHeading: "Performers",
        speakers: [
          { name: "Bakian", note: "Vocals" },
          { name: "Mickael Serra", note: "Guitar" },
          { name: "Antoine Geremia", note: "Piano" },
        ],
        body: [
          "Bakian sings Aznavour is the French-Armenian singer Bakian's tribute to Charles Aznavour. Bakian met Aznavour as a young artist and the two worked together for nearly three years, in the course of which Aznavour entrusted him with three songs that had never been released.",
          "## What is sung",
          "Those three songs sit alongside Aznavour's best-known ones, and between them Bakian tells the stories behind the music and his own memories of the chansonnier. Mickael Serra plays guitar and Antoine Geremia piano. The project is presented with Seiya Records and Aznavour pour l'Amour.",
          "## When and where",
          "15 October at 19:00, in the Babajanyan Concert Hall of the Armenian State Philharmonia. A ticket is 10,000 drams — one price for the whole house.",
        ],
        faq: [
          { q: "How much are tickets?", a: "10,000 drams." },
          { q: "When is it?", a: "On 15 October at 19:00." },
          { q: "What is on the programme?", a: "Aznavour's best-known songs, and three songs Aznavour entrusted to Bakian." },
        ],
      },
    },
  },

  {
    slug: "tamar-ballet-yerevan-opera-2026",
    createdAt: "2026-10-06T20:15:00+04:00",
    updatedAt: "2026-10-06T20:15:00+04:00",
    site: "tick",
    title: "«Թամար» բալետը՝ Երևանի օպերային թատրոնում",
    cardTitle: "Տոլստով. «Թամար»",
    summary:
      "Վալերի Տոլստովի «Թամար» բալետը՝ Ախթամարի լեգենդը մեր օրերում, Երևանում՝ Սպենդիարյանի անվան օպերայի և բալետի թատրոնում, հոկտեմբերի 17-ից. տոմսերը՝ 5000-ից 25000 դրամ։",
    start: "2026-10-17",
    startTime: "18:00",
    utcOffset: "+04:00",
    city: "Երևան",
    country: "Հայաստան",
    venue: "Ալ. Սպենդիարյանի անվան օպերայի և բալետի ազգային ակադեմիական թատրոն, Թումանյան 54",
    geo: { lat: 40.1862685, lng: 44.5151091 },
    organizer: "Ալ. Սպենդիարյանի անվան օպերայի և բալետի ազգային ակադեմիական թատրոն",
    category: "Օպերա և բալետ",
    tickets: { priceFrom: 5000, priceTo: 25000, currency: "AMD" },
    ticket: { url: "https://www.tomsarkgh.am/en/event/51487/", label: "Տոմսեր" },
    source: { name: "Tomsarkgh", url: "https://www.tomsarkgh.am/en/event/51487/", verifiedOn: "2026-10-06" },
    body: [
      "«Թամարը» Ախթամարի լեգենդի ժամանակակից վերաիմաստավորումն է։ Գործողությունները ծավալվում են մեր օրերում. գլխավոր հերոսները ֆոտոլրագրող Արամն ու նկարչուհի Թամարն են, և նրանց հանդիպմամբ անցյալից եկող պատմությունը նոր ընթացք է ստանում՝ սիրո, ընտրության, հիշողության և անդառնալի կորստի մասին։",
      "Երաժշտությունը Վալերի Տոլստովինն է, բեմադրող բալետմայստերը Իլյա Ժիվոյն է, մտահղացման և լիբրետոյի հեղինակը՝ Գոշ Սարգսյանը։ Բեմանկարիչը Արթուր Դուրգարյանն է, զգեստների նկարիչը՝ Սոնյա Վարդանյանը։",
      "## Դերերում",
      "Հոկտեմբերի 17-ին և 24-ին Թամար՝ Անահիտ Վասիլյան, Արամ՝ Յուրա Մարտիրոսյան, Թամարի հայրը՝ Սևակ Ավետիսյան, ընկերության տնօրենը՝ Ռուբեն Մուրադյան։ Հոկտեմբերի 18-ին և 25-ին Թամար՝ Վալերիյա Բեսսոնովա, Արամ՝ Գոռ Սարգսյան, Թամարի հայրը՝ Արտաշես Հակոբյան, ընկերության տնօրենը՝ Համլետ Միրզոյան։",
      "## Երբ",
      "Հոկտեմբերի 17-ին, 18-ին, 24-ին և 25-ին, նոյեմբերի 21-ին և 22-ին, բոլորը՝ ժամը 18:00-ին։ Տոմսերը 5000-ից 25000 դրամ են։",
    ],
    faq: [
      { q: "Որքա՞ն արժե տոմսը", a: "5000-ից 25000 դրամ՝ կախված նստատեղից։" },
      { q: "Ե՞րբ են ներկայացումները", a: "Հոկտեմբերի 17-ին, 18-ին, 24-ին և 25-ին, նոյեմբերի 21-ին և 22-ին, ժամը 18:00-ին։" },
      { q: "Ինչի՞ մասին է բալետը", a: "Ախթամարի լեգենդի մասին՝ տեղափոխված մեր օրեր. հերոսները ֆոտոլրագրող Արամն ու նկարչուհի Թամարն են։" },
    ],
    i18n: {
      en: {
        ticket: { url: "https://www.tomsarkgh.am/en/event/51487/", label: "Tickets" },
        title: "Tamar, a ballet at the Yerevan Opera",
        cardTitle: "Tolstov: Tamar",
        summary:
          "Valery Tolstov's ballet Tamar, the Akhtamar legend set in the present day, in Yerevan at the Spendiaryan Opera and Ballet Theatre from 17 October; tickets from 5,000 drams.",
        city: "Yerevan",
        country: "Armenia",
        venue: "Spendiaryan Opera and Ballet Theatre, 54 Tumanyan Street",
        organizer: "Spendiaryan National Academic Opera and Ballet Theatre",
        category: "Opera and ballet",
        body: [
          "Tamar retells the legend of Akhtamar for the present day. Its leads are Aram, a photojournalist, and Tamar, a painter, and when they meet, a story handed down from the past takes a new turn — one about love, choice, memory and a loss that cannot be undone.",
          "The music is by Valery Tolstov and the choreography by Ilya Zhivoy, from a concept and libretto by Gosh Sargsyan. Artur Durgaryan designed the set and Sonya Vardanyan the costumes.",
          "## The cast",
          "On 17 and 24 October, Anahit Vasilyan dances Tamar and Yura Martirosyan Aram, with Sevak Avetisyan as Tamar's father and Ruben Muradyan as the company director. On 18 and 25 October, Valeriya Bessonova and Gor Sargsyan take the leads, with Artashes Hakobyan and Hamlet Mirzoyan.",
          "## Dates",
          "17, 18, 24 and 25 October and 21 and 22 November, all at 18:00. Tickets cost 5,000 to 25,000 drams.",
        ],
        faq: [
          { q: "How much are tickets?", a: "From 5,000 to 25,000 drams depending on the seat." },
          { q: "When is it on?", a: "On 17, 18, 24 and 25 October and on 21 and 22 November, at 18:00." },
          { q: "What is the ballet about?", a: "The legend of Akhtamar, moved to the present day: its leads are Aram, a photojournalist, and Tamar, a painter." },
        ],
      },
    },
  },
];
