import type { EventItem } from "../types.ts";

export const items: EventItem[] = [
  {
    slug: "viennale-2026",
    createdAt: "2026-09-06T09:36:42+04:00",
    updatedAt: "2026-09-06T09:36:42+04:00",
    site: "vien",
    image: "/covers/viennale-2026.jpg",
    imageAlt: "Ein Papierstreifen aus Filmkadern quer durchs Bild, drei Kader in Zinnoberrot, ein moosgrüner Lichtkegel am Rand",
    imageKind: "generated",
    imageWidth: 1536,
    imageHeight: 864,
    title: "Viennale 2026",
    summary:
      "Österreichs größtes Filmfestival läuft vom 22. Oktober bis 3. November. Die 64. Ausgabe bringt eine Retrospektive zu Robert Aldrich und ein Ferien-Abo für Jugendliche um 20 Euro.",
    start: "2026-10-22",
    end: "2026-11-03",
    utcOffset: "+02:00",
    city: "Wien",
    organizer: "Viennale",
    category: "Filmfestival",
    featured: 1,
    source: {
      name: "Viennale",
      url: "https://www.viennale.at/de",
      verifiedOn: "2026-09-06",
    },
    ticket: { url: "https://www.viennale.at/de", label: "Zum Festival" },
    body: [
      "Zwölf Tage lang gehört das Kino in Wien wieder dem Festival. Die Viennale ist das größte Filmfestival Österreichs, und sie ist eines der wenigen großen, die keinen Wettbewerb haben: Es gibt keine Jury, die am Ende einen Sieger ausruft, sondern ein kuratiertes Programm und ein Publikum.",
      "## Die Daten",
      "<strong>22. Oktober bis 3. November 2026</strong>, in den Festivalkinos in Wien. Es ist die <strong>64. Ausgabe</strong>.",
      "## Was im Programm steht",
      "Die Viennale zeigt neue Filme aus aller Welt und aus Österreich, darunter internationale Premieren. Für 2026 angekündigt sind eine <strong>Retrospektive zu Robert Aldrich</strong> sowie Spezialprogramme zu <strong>Jocelyne Saab</strong>, <strong>Phil Solomon</strong>, <strong>Vasko Pregelj</strong> und dem <strong>österreichischen Film der Neunzigerjahre</strong>.",
      "## Tickets",
      "Das <strong>Ferien-Abo</strong> gibt Jugendlichen ab 14 Jahren vier Festivalfilme um <strong>20 Euro</strong>. Der Termin für den Vorverkaufsstart 2026 stand am 6. September noch nicht auf der Festivalseite; im Vorjahr begann er rund zwei Wochen vor Festivalbeginn an einem Samstagvormittag. Wir tragen hier kein Datum ein, das die Viennale nicht genannt hat.",
      "## Die vollständige Kinoliste",
      "Ebenfalls noch nicht veröffentlicht. Die Seite führt die Festivalkinos als Menüpunkt, nennt sie aber noch nicht einzeln.",
    ],
    expertise:
      "Zwei Dinge, die den Unterschied zwischen einem guten und einem frustrierenden Viennale-Besuch ausmachen. Erstens: Ein Festival ohne Wettbewerb hat auch keinen Preisträgerfilm, über den danach alle reden — die Auswahl trifft man selbst, und die Retrospektive ist erfahrungsgemäß der Teil, den man später am ehesten bereut verpasst zu haben, weil diese Kopien sonst nirgends laufen. Zweitens: Der Vorverkauf ist der eigentliche Engpass, nicht das Festival. Wer erst in der Festivalwoche schaut, bekommt die Abendvorstellungen der bekannten Titel nicht mehr; die Vormittage in der zweiten Woche sind dagegen fast immer offen.",
  },

  {
    slug: "wien-modern-39",
    createdAt: "2026-09-06T09:36:42+04:00",
    updatedAt: "2026-09-06T09:36:42+04:00",
    site: "vien",
    image: "/covers/wien-modern-39.jpg",
    imageAlt: "Ein breites moosgrünes Flussband aus Papier unter gestaffelten zinnoberroten Klangbalken",
    imageKind: "generated",
    imageWidth: 1536,
    imageHeight: 864,
    title: "Wien Modern 39",
    summary:
      "Das Festival für neue Musik eröffnet am 30. Oktober im Wiener Konzerthaus mit der Uraufführung von Pia Palmes „Mit der Donau“. Das ganze Programm kommt am 8. September, dann startet auch der Vorverkauf.",
    start: "2026-10-30",
    utcOffset: "+01:00",
    venue: "Wiener Konzerthaus",
    city: "Wien",
    organizer: "Wien Modern",
    category: "Musikfestival",
    featured: 2,
    source: {
      name: "Wien Modern",
      url: "https://www.wienmodern.at/",
      verifiedOn: "2026-09-06",
    },
    ticket: { url: "https://www.wienmodern.at/", label: "Zum Festival" },
    body: [
      "Wien Modern ist das Festival, das der Stadt jedes Jahr für ein paar Wochen zeigt, wie zeitgenössische Musik klingt, wenn sie nicht zwischen zwei Klassikprogrammen versteckt wird. Die 39. Ausgabe beginnt an der Donau — jedenfalls thematisch.",
      "## Der Eröffnungsabend",
      "<strong>30. Oktober 2026</strong>, <strong>Wiener Konzerthaus</strong>: die Uraufführung von <strong>„Mit der Donau“</strong> von <strong>Pia Palme</strong>, entstanden in Zusammenarbeit mit der Künstlerin <strong>Lisa Horvath</strong> im <strong>Nationalpark Donau-Auen</strong>.",
      "## Was am 8. September kommt",
      "Das Festival schreibt es selbst: „Das volle Programm der 39. Festivalausgabe präsentieren wir am 8. September, dann startet auch der Vorverkauf!“ Bis dahin steht der Eröffnungsabend, und sonst nichts.",
      "## Was noch nicht feststeht",
      "Das Enddatum, die Zahl der Veranstaltungen und die Liste der Spielstätten. Wien Modern läuft üblicherweise mehrere Wochen und an vielen Orten in der Stadt — aber „üblicherweise“ ist kein Datum, und wir tragen hier keines ein, das das Festival nicht genannt hat.",
    ],
    expertise:
      "Der 8. September ist bei diesem Festival der wichtigere Termin als der 30. Oktober. Programm und Vorverkauf starten am selben Tag, und das heißt: Wer am 8. September nachmittags schaut, hat die gesamte Auswahl vor sich; wer eine Woche wartet, hat die Uraufführungen in den kleinen Sälen nicht mehr. Bei einem Festival für neue Musik ist das keine Formalie — die kleinen Säle sind der Ort, an dem die Stücke stattfinden, die es danach nie wieder zu hören gibt.",
  },

  {
    slug: "vienna-coffee-festival-2026",
    createdAt: "2026-09-08T16:29:32+04:00",
    updatedAt: "2026-09-08T16:34:13+04:00",
    site: "vien",
    image: "/covers/vienna-coffee-festival-2026.jpg",
    imageAlt: "Ein goldener Ring mit einer roten Scheibe darin und drei kurzen roten Dampfstrichen darüber, auf cremefarbenem Grund",
    imageKind: "generated",
    imageWidth: 1536,
    imageHeight: 864,
    title: "Vienna Coffee Festival 2026",
    summary:
      "Über hundert Röstereien und Spezialitäten-Aussteller drei Tage lang in der Wiener Marx Halle, von 11. bis 13. September, mit Workshops, Cuppings und einem eigenen B2B-Tag.",
    start: "2026-09-11",
    end: "2026-09-13",
    utcOffset: "+02:00",
    venue: "Marx Halle, Karl-Farkas-Gasse 19",
    city: "Wien",
    country: "Österreich",
    organizer: "Lefor Oberbauer",
    category: "Festival",
    source: {
      name: "Vienna Coffee Festival",
      url: "https://www.viennacoffeefestival.cc/",
      verifiedOn: "2026-09-08",
    },
    body: [
      "In einer Stadt, deren Kaffeehauskultur zum Weltkulturerbe zählt, ist ein Festival für Spezialitätenkaffee eine kleine Provokation. Es findet trotzdem statt, und zwar in einer Industriehalle.",
      "## Die Daten",
      "<strong>11. bis 13. September 2026</strong> in der <strong>Marx Halle</strong>, Karl-Farkas-Gasse 19, 1030 Wien. Veranstalter ist <strong>Lefor Oberbauer</strong>, Gründer und Betreiber des Festivals. Karten laufen über wien-ticket.at.",
      "## Wer ausstellt",
      "Über <strong>100 Kaffeeröster und Spezialitäten-Aussteller</strong>, dazu Maschinenhersteller wie <strong>La Cimbali</strong>, <strong>Faema</strong> und <strong>La Marzocco</strong>.",
      "## Was im Programm steht",
      "<strong>Workshops</strong>, <strong>Cuppings</strong>, eine <strong>Open Stage</strong> und Führungen. Ein eigener <strong>B2B-Day</strong> richtet sich an Geschäftspartner.",
    ],
    expertise:
      "Das Cupping ist der Teil, für den man kommt, und der Teil, der zuerst ausgebucht ist — anders als bei den Ausstellerständen sitzt man dort in einer festen Runde, und die Plätze sind gezählt. Wer nur einen Tag hat, nimmt den Freitag: der B2B-Tag zieht das Fachpublikum, und an den Ständen wird an diesem Tag anders geredet als am Wochenende, wo dieselben Leute Schlangen abarbeiten. Und eine Anmerkung zur Halle: Die Marx Halle ist eine Gusseisenkonstruktion aus dem 19. Jahrhundert ohne Klimaanlage. Bei einem warmen Septemberwochenende ist der Vormittag die angenehmere Hälfte des Tages.",
  },

  {
    slug: "vienna-design-week-2026",
    createdAt: "2026-09-08T19:16:59+04:00",
    updatedAt: "2026-09-08T19:16:59+04:00",
    site: "vien",
    image: "/covers/vienna-design-week-2026.jpg",
    imageAlt: "Ein gestufter Turm aus roten und grünen Blöcken auf hellem Grund, als Linolschnitt",
    imageKind: "generated",
    imageWidth: 1536,
    imageHeight: 864,
    title: "Vienna Design Week 2026",
    summary:
      "Zehn Tage Design in ganz Wien, vom 25. September bis 4. Oktober, an rund 50 Orten und bei den meisten Programmpunkten bei freiem Eintritt. Die 20. Ausgabe hat ihre Festivalzentrale in einem Bürohochhaus von Harry Glück in Hietzing.",
    start: "2026-09-25",
    end: "2026-10-04",
    utcOffset: "+02:00",
    city: "Wien",
    organizer: "Vienna Design Week",
    category: "Designfestival",
    source: {
      name: "Vienna Design Week",
      url: "https://www.viennadesignweek.at/en/",
      verifiedOn: "2026-09-08",
    },
    ticket: { url: "https://www.viennadesignweek.at/en/", label: "Zum Festival" },
    body: [
      "Ein Designfestival, das keine Messehalle mietet, sondern die Stadt benutzt: Vienna Design Week findet in Werkstätten, Geschäften, Höfen und einem leerstehenden Bürohochhaus statt, und wer hingeht, geht dorthin, wo gearbeitet wird.",
      "## Die Daten",
      "<strong>25. September bis 4. Oktober 2026</strong>, an rund <strong>50 Orten</strong> in Wien. Es ist die <strong>20. Ausgabe</strong> — das Festival nennt sich selbst Österreichs wichtigstes kuratiertes Designfestival und zählt üblicherweise rund 200 Programmpunkte und 40.000 Besucherinnen und Besucher.",
      "## Was der Eintritt kostet",
      "Bei den <strong>meisten Programmpunkten nichts</strong>. Einzelne Formate sind kostenpflichtig oder brauchen eine Anmeldung; welche das 2026 sind, stand am 8. September noch nicht fest.",
      "## Die Festivalzentrale",
      "Ein Bürohochhaus am <strong>Hietzinger Kai 101</strong> im 13. Bezirk, in den Siebzigerjahren von <strong>Harry Glück</strong> gebaut. Dort ist auch das Gastland <strong>Luxemburg</strong> mit eigenen Ausstellungsprojekten untergebracht.",
      "## Die Formate",
      "Ausstellungen und Installationen, Führungen, Workshops, Studiobesuche und Produktionsstätten. Das bekannteste Format sind die <strong>Passionswege</strong>: internationale und österreichische Gestalterinnen und Gestalter arbeiten dafür mit Wiener Handwerksbetrieben zusammen. Neu 2026 sind <strong>Akustikdesign</strong> und <strong>Urban Food Design</strong>.",
    ],
    faq: [
      {
        q: "Kostet die Vienna Design Week Eintritt?",
        a: "Bei den meisten Programmpunkten ist der Eintritt frei. Einzelne Workshops und Führungen sind kostenpflichtig oder brauchen eine Anmeldung.",
      },
      {
        q: "Wann findet die Vienna Design Week 2026 statt?",
        a: "Von <strong>25. September bis 4. Oktober 2026</strong>, zehn Tage lang an rund 50 Orten in Wien.",
      },
      {
        q: "Wo ist die Festivalzentrale 2026?",
        a: "In einem Bürohochhaus am Hietzinger Kai 101 im 13. Bezirk, gebaut in den Siebzigerjahren von Harry Glück.",
      },
      {
        q: "Was sind die Passionswege?",
        a: "Das älteste Format des Festivals: Gestalterinnen und Gestalter arbeiten für eine Saison mit einem Wiener Handwerksbetrieb zusammen, und das Ergebnis wird in der Werkstatt gezeigt, nicht auf einem Messestand.",
      },
    ],
    expertise:
      "Die Passionswege sind der Grund, warum dieses Festival anders ist als eine Designmesse, und sie sind auch der Teil, der am meisten Weg kostet: Die Werkstätten liegen über die Stadt verteilt, und wer sie an einem Nachmittag abhaken will, verbringt den Nachmittag in der U-Bahn. Sinnvoller ist es, sich einen Bezirk vorzunehmen. Zweitens die Festivalzentrale: Ein leerstehendes Bürohochhaus ist als Ort selbst schon die halbe Ausstellung, und es ist der einzige Punkt im Programm, an dem man ohne Planung hingehen und trotzdem viel sehen kann.",
  },

  {
    slug: "wiener-kaiser-wiesn-2026",
    createdAt: "2026-09-08T19:16:59+04:00",
    updatedAt: "2026-09-12T17:35:10+04:00",
    site: "vien",
    image: "/covers/wiener-kaiser-wiesn-2026.jpg",
    imageAlt: "Drei Festzelte nebeneinander in Rot, Ocker und Grün auf cremefarbenem Grund, das mittlere höher und mit einer kleinen roten Fahne",
    imageKind: "generated",
    imageWidth: 1536,
    imageHeight: 864,
    title: "Wiener Kaiser Wiesn 2026",
    summary:
      "Achtzehn Tage Volksfest auf der Kaiserwiese im Wiener Prater, von 24. September bis 11. Oktober. Der Eintritt aufs Gelände ist frei, Karten braucht man nur für die Abendveranstaltungen in den drei Zelten.",
    start: "2026-09-24",
    end: "2026-10-11",
    utcOffset: "+02:00",
    venue: "Kaiserwiese, Prater",
    city: "Wien",
    organizer: "Wiener Kaiser Wiesn GmbH",
    category: "Volksfest",
    tickets: { priceFrom: 0, currency: "EUR" },
    source: {
      name: "Stadt Wien",
      url: "https://www.wien.gv.at/veranstaltungen/wiener-kaiser-wiesn-2026",
      verifiedOn: "2026-09-08",
    },
    ticket: { url: "https://kaiserwiesn.at/en/", label: "Zur Kaiser Wiesn" },
    body: [
      "Achtzehn Tage lang steht auf der Kaiserwiese im Prater das größte Volksfest Österreichs, und der Eintritt aufs Gelände kostet nichts. Das ist der Unterschied zu München, den man kennen sollte, bevor man ein Ticket sucht: Man braucht keines, um hinzugehen.",
      "## Die Daten",
      "<strong>24. September bis 11. Oktober 2026</strong>, <strong>Kaiserwiese</strong> im Prater, 2. Bezirk.",
      "## Was der Eintritt kostet",
      "<strong>Nichts.</strong> Karten braucht man nur für die <strong>Abendveranstaltungen in den drei Festzelten</strong> — Gösser Kaiserzelt, Wiesbauer Kaiserzelt und Nordic Spirit Kaiserzelt.",
      "## Die Zelte",
      "Drei an der Zahl, mit Live-Bands. Das Musikprogramm endet um Mitternacht.",
    ],
    faq: [
      {
        q: "Kostet die Wiener Kaiser Wiesn Eintritt?",
        a: "Das Gelände auf der Kaiserwiese ist <strong>frei zugänglich</strong>. Karten braucht man nur für die Abendveranstaltungen in den drei Festzelten.",
      },
      {
        q: "Wann ist die Wiener Kaiser Wiesn 2026?",
        a: "Von <strong>24. September bis 11. Oktober 2026</strong>, achtzehn Tage lang.",
      },
      {
        q: "Wo findet die Kaiser Wiesn statt?",
        a: "Auf der Kaiserwiese im Prater im 2. Bezirk, gleich beim Riesenrad.",
      },
      {
        q: "Wie viele Festzelte gibt es?",
        a: "Drei: das Gösser Kaiserzelt, das Wiesbauer Kaiserzelt und das Nordic Spirit Kaiserzelt.",
      },
    ],
    expertise:
      "Der freie Eintritt ist der Punkt, an dem die meisten falsch planen. Aufs Gelände kommt man ohne Karte, und tagsüber ist das auch die ganze Wahrheit — abends aber sind die Zelte der Ort, an dem das Fest stattfindet, und dafür braucht es eine Reservierung. Wer spontan am Samstagabend hinfährt, steht auf der Wiese und hört die Band durch die Zeltwand. Und die Lage ist der zweite Vorteil gegenüber München: Die Kaiserwiese liegt direkt beim Riesenrad an der U1, man kommt ohne Sonderfahrplan hin und wieder weg.",
  },

  {
    slug: "lange-nacht-der-museen-2026",
    createdAt: "2026-09-08T19:16:59+04:00",
    updatedAt: "2026-09-08T19:33:00+04:00",
    site: "vien",
    image: "/covers/lange-nacht-der-museen-2026.jpg",
    imageAlt: "Drei hell erleuchtete hohe Fenster in einer dunkelroten Fassade",
    imageKind: "generated",
    imageWidth: 1536,
    imageHeight: 864,
    title: "ORF Lange Nacht der Museen 2026",
    summary:
      "Eine Nacht, ein Ticket, rund 270 Museen in ganz Österreich, viele davon in Wien: am 3. Oktober von 18 bis 24 Uhr. Das Ticket kostet 19 Euro, ermäßigt 16, Kinder unter zwölf gehen frei.",
    start: "2026-10-03",
    startTime: "18:00",
    endTime: "24:00",
    utcOffset: "+02:00",
    city: "Wien",
    organizer: "ORF",
    category: "Museumsnacht",
    tickets: { priceFrom: 16, priceTo: 19, currency: "EUR" },
    source: {
      name: "ORF Lange Nacht der Museen",
      url: "https://langenacht.orf.at/",
      verifiedOn: "2026-09-08",
    },
    ticket: { url: "https://langenacht.orf.at/", label: "Zur Langen Nacht" },
    body: [
      "Ein Ticket, sechs Stunden, rund 270 Häuser: Die Lange Nacht der Museen ist der einzige Abend im Jahr, an dem man in Wien ein Museum verlässt, weil noch drei andere offen haben.",
      "## Die Daten",
      "<strong>Samstag, 3. Oktober 2026, 18 bis 24 Uhr</strong>, in ganz Österreich.",
      "## Was das Ticket kostet",
      "<strong>19 Euro</strong> regulär, <strong>16 Euro</strong> ermäßigt für Studierende, Seniorinnen und Senioren und Menschen mit Behinderung. Ein <strong>Regionalticket</strong> für ein einzelnes Bundesland kostet <strong>7 Euro</strong>. <strong>Kinder unter zwölf</strong> — geboren nach dem 2. Oktober 2014 — gehen <strong>gratis</strong>.",
      "## Wie viele Häuser mitmachen",
      "Rund <strong>270 Museen und Kultureinrichtungen</strong> in ganz Österreich, ein großer Teil davon in Wien.",
    ],
    faq: [
      {
        q: "Was kostet die Lange Nacht der Museen 2026?",
        a: "<strong>19 Euro</strong> regulär und <strong>16 Euro</strong> ermäßigt für ganz Österreich; ein Regionalticket für ein Bundesland kostet 7 Euro. Kinder unter zwölf zahlen nichts.",
      },
      {
        q: "Wann ist die Lange Nacht der Museen 2026?",
        a: "Am <strong>Samstag, 3. Oktober 2026, von 18 bis 24 Uhr</strong>.",
      },
      {
        q: "Wie viele Museen machen mit?",
        a: "Rund 270 Museen und Kultureinrichtungen in ganz Österreich.",
      },
      {
        q: "Gilt ein Ticket für alle Museen?",
        a: "Ja. Ein Ticket gilt für alle teilnehmenden Häuser in ganz Österreich; das günstigere Regionalticket gilt nur in einem Bundesland.",
      },
    ],
    expertise:
      "Sechs Stunden klingen nach viel und sind es nicht: Realistisch sind vier Häuser, wenn sie nahe beieinander liegen, und drei, wenn nicht. Der Fehler, den fast alle beim ersten Mal machen, ist das größte Haus zuerst — im Kunsthistorischen oder im Naturhistorischen ist der Abend vorbei, bevor er begonnen hat, und beide sind ohnehin ganzjährig offen. Die Nacht lohnt sich für die kleinen Sammlungen, die man sonst nie betritt, weil sie um 17 Uhr zusperren. Und das Regionalticket um 7 Euro ist für einen Wiener Abend die richtige Karte — die 19 Euro zahlt nur, wer wirklich Bundesländer wechselt.",
  },

  {
    slug: "vienna-halloween-run-2026",
    createdAt: "2026-09-08T22:51:25+04:00",
    updatedAt: "2026-09-12T17:35:10+04:00",
    site: "vien",
    image: "/covers/vienna-halloween-run-2026.jpg",
    imageAlt: "Eine helle Laufbahn, die in die Bildmitte führt, gesäumt von Bäumen mit rotem Herbstlaub",
    imageKind: "generated",
    imageWidth: 1536,
    imageHeight: 864,
    title: "Vienna Halloween Run 2026",
    summary:
      "Ein Laufabend in der Prater Hauptallee am 30. Oktober, ab 15:30 Uhr, in drei Distanzen von 600 Metern bis 5 Kilometern. Startgebühr 8 bis 40 Euro, verkleidet laufen ist ausdrücklich erwünscht.",
    start: "2026-10-30",
    startTime: "15:30",
    utcOffset: "+01:00",
    venue: "Prater Hauptallee, Antifaschismusplatz 1",
    city: "Wien",
    organizer: "Fairsport Events e.U.",
    category: "Halloween",
    tickets: { priceFrom: 8, priceTo: 40, currency: "EUR" },
    // Die Anmeldung läuft über Time Now Sports; die Veranstalterseite
    // verlinkt die Jahrgangsseite 2026 direkt.
    ticket: {
      url: "https://www.time-now-sports.at/vienna-halloween-run-2026",
      label: "Anmeldung bei Time Now Sports",
    },
    source: {
      name: "Vienna Halloween Run",
      url: "https://www.vienna-halloween-run.at/",
      verifiedOn: "2026-09-08",
    },
    body: [
      "Halloween in Wien findet zum größten Teil in Wohnungen und Lokalen statt. Der Vienna Halloween Run ist das seltene Gegenteil: eine Veranstaltung im Freien, mit Startnummer, Zeitnehmung und einem Zieleinlauf im Dunkeln. Die zweite Auflage läuft am <strong>30. Oktober 2026</strong> in der Prater Hauptallee.",
      "## Die Distanzen",
      "<strong>Mini Monster</strong> über 600 bis 800 Meter für die Kleinsten, <strong>Little Fear</strong> über 2,5 Kilometer und <strong>Big Scare</strong> über 5 Kilometer. Die beiden längeren Bewerbe starten in Blöcken um <strong>18:30</strong> und <strong>19:30 Uhr</strong>, das Gelände öffnet um <strong>15:30 Uhr</strong>.",
      "## Was es kostet",
      "Die Startgebühr liegt je nach Bewerb und Anmeldezeitpunkt zwischen <strong>8 und 40 Euro</strong>.",
      "## Der Ort",
      "Start und Ziel liegen am <strong>Antifaschismusplatz 1</strong> am Beginn der Hauptallee, wenige Minuten vom Praterstern.",
    ],
    faq: [
      {
        q: "Wann ist der Vienna Halloween Run 2026?",
        a: "Am <strong>30. Oktober 2026</strong>. Das Gelände öffnet um 15:30 Uhr, die längeren Bewerbe starten um 18:30 und 19:30 Uhr.",
      },
      {
        q: "Welche Distanzen gibt es?",
        a: "Drei: Mini Monster über 600 bis 800 Meter, Little Fear über 2,5 Kilometer und Big Scare über 5 Kilometer.",
      },
      {
        q: "Was kostet die Teilnahme?",
        a: "Zwischen <strong>8 und 40 Euro</strong>, abhängig vom Bewerb und davon, wie früh man sich anmeldet.",
      },
      {
        q: "Wo startet der Lauf?",
        a: "In der Prater Hauptallee, am Antifaschismusplatz 1 im 2. Bezirk.",
      },
    ],
    expertise:
      "Zwei Dinge unterscheiden diesen Abend von einem gewöhnlichen Volkslauf. Erstens die Uhrzeit: Ende Oktober ist es um halb sieben bereits dunkel, und die Hauptallee ist keine hell beleuchtete Straße — wer die 5 Kilometer läuft, läuft den größten Teil davon im Halbdunkel. Zweitens das Kostüm, das hier nicht Zierde, sondern Ausrüstung ist: Was beim Fotografieren gut aussieht, wird nach zwei Kilometern schwer und warm. Die praktikable Lösung sind Maske und Umhang, die man im Ziel wieder anzieht, nicht das vollständige Ganzkörperkostüm.",
  },

  {
    slug: "kuerbisfest-am-himmel-2026",
    createdAt: "2026-09-08T22:51:25+04:00",
    updatedAt: "2026-09-12T17:35:10+04:00",
    site: "vien",
    image: "/covers/kuerbisfest-am-himmel-2026.jpg",
    imageAlt: "Ein breiter Haufen runder Papierscheiben in Rot, Grün, Ocker und Creme, in vielen verschiedenen Größen",
    imageKind: "generated",
    imageWidth: 1536,
    imageHeight: 864,
    title: "Kürbisfest am Himmel 2026",
    summary:
      "Drei Tage Kürbis am Stadtrand von Wien, von 24. bis 26. Oktober jeweils 10 bis 18 Uhr, mit über 200 Sorten zum Anschauen. Der Eintritt ist frei.",
    start: "2026-10-24",
    end: "2026-10-26",
    startTime: "10:00",
    endTime: "18:00",
    utcOffset: "+02:00",
    venue: "Himmelstraße 125",
    city: "Wien",
    organizer: "Kuratorium Wald",
    category: "Halloween",
    tickets: { priceFrom: 0, currency: "EUR" },
    source: {
      name: "Himmel — Kuratorium Wald",
      url: "https://www.himmel.at/kuerbisfest",
      verifiedOn: "2026-09-08",
    },
    body: [
      "Der ausgehöhlte Kürbis ist das eine Bild, das jeder mit dem Ende des Oktobers verbindet, und am Himmel in Sievering steht er drei Tage lang in über zweihundert Sorten nebeneinander — die meisten davon sehen nicht im Entferntesten aus wie das orange Ding aus dem Supermarkt.",
      "## Die Daten",
      "<strong>24. bis 26. Oktober 2026</strong>, jeweils von <strong>10 bis 18 Uhr</strong>, Himmelstraße 125 im 19. Bezirk.",
      "## Was der Eintritt kostet",
      "<strong>Nichts.</strong> Das Fest ist frei zugänglich.",
      "## Was dort steht",
      "Über <strong>200 Kürbissorten</strong>, dazu das Gelände des Kuratoriums Wald am Stadtrand mit Blick über die Stadt.",
    ],
    faq: [
      {
        q: "Wann ist das Kürbisfest am Himmel 2026?",
        a: "Von <strong>24. bis 26. Oktober 2026</strong>, täglich von 10 bis 18 Uhr.",
      },
      {
        q: "Kostet das Kürbisfest Eintritt?",
        a: "Nein, der <strong>Eintritt ist frei</strong>.",
      },
      {
        q: "Wo ist der Himmel?",
        a: "In der Himmelstraße 125 im 19. Bezirk, am Stadtrand oberhalb von Sievering.",
      },
      {
        q: "Wie viele Kürbissorten gibt es zu sehen?",
        a: "Über <strong>200</strong>.",
      },
    ],
    expertise:
      "Der Himmel liegt nicht an der U-Bahn, und das ist der Punkt, an dem die Anreise geplant gehört: Hinauf fährt der 39A, und an einem freien Nachmittag Ende Oktober ist er voll. Wer mit dem Auto kommt, findet in der Himmelstraße kaum Platz. Dafür bekommt man den Gegenwert, den ein Halloween-Programm im Innenstadtlokal nicht hat — Tageslicht, Aussicht über die Stadt und einen Grund, das Wochenende vor dem 31. Oktober im Freien zu verbringen.",
  },

  {
    slug: "wiener-christkindlmarkt-2026",
    createdAt: "2026-09-12T23:41:00+04:00",
    updatedAt: "2026-09-12T23:41:00+04:00",
    site: "vien",
    image: "/covers/wiener-christkindlmarkt-2026.jpg",
    imageAlt:
      "Drei kleine rote Papierhäuser mit grünen Dächern auf einer cremefarbenen Schneefläche, dahinter eine hohe grüne Tanne mit rotem Stern, auf warmem Cremegrund",
    imageKind: "generated",
    imageWidth: 1536,
    imageHeight: 864,
    title: "Wiener Christkindlmarkt am Rathausplatz 2026",
    summary:
      "Der größte Weihnachtsmarkt in Wien läuft vom 13. November bis 26. Dezember 2026, täglich 10 bis 22 Uhr, am 24. Dezember bis 18:30 Uhr. Die Eisfläche bleibt bis 6. Jänner 2027.",
    start: "2026-11-13",
    end: "2026-12-26",
    startTime: "10:00",
    endTime: "22:00",
    utcOffset: "+01:00",
    venue: "Rathausplatz",
    city: "Wien",
    country: "Österreich",
    geo: {
      name: "Rathausplatz, Wien",
      lat: 48.212293,
      lng: 16.359847,
    },
    organizer: "stadt wien marketing",
    category: "Weihnachtsmarkt",
    ticket: {
      url: "https://www.christkindlmarkt.at/",
      label: "Öffnungszeiten und Programm",
    },
    source: {
      name: "Wiener Christkindlmarkt",
      url: "https://www.christkindlmarkt.at/",
      verifiedOn: "2026-09-12",
    },
    body: [
      "Sechs Wochen, ein Platz, und zwei Termine, die nicht zusammenfallen: Der Markt endet am <strong>26. Dezember</strong>, die Eisfläche davor bleibt bis <strong>6. Jänner</strong>. Wer den Unterschied kennt, hat nach Weihnachten noch zwei Wochen Rathausplatz.",
      "## Die Öffnungszeiten",
      "<strong>13. November bis 26. Dezember 2026</strong>, <strong>täglich 10 bis 22 Uhr</strong>. Am <strong>24. Dezember</strong> sperrt der Markt früher zu: <strong>10 bis 18:30 Uhr</strong>.",
      "## Der Eistraum am Christkindlmarkt",
      "Die Eisfläche läuft länger als der Markt — <strong>13. November 2026 bis 6. Jänner 2027</strong>, ebenfalls <strong>täglich 10 bis 22 Uhr</strong>, am <strong>24. Dezember 10 bis 18:30 Uhr</strong>. Eine Ausnahme gibt es: <strong>am 31. Dezember geschlossen</strong>. Danach macht der Rathausplatz Pause und kommt am 22. Jänner als Wiener Eistraum zurück.",
      "## Wo das ist",
      "Am <strong>Rathausplatz</strong> zwischen Rathaus und Burgtheater, im ersten Bezirk. Der Markt gilt als einer der größten und meistbesuchten Weihnachtsmärkte Europas, und das Wiener Christkindl ist der Höhepunkt, den das Programm selbst voranstellt.",
      "## Anreise",
      "Öffentlich: die Linien <strong>1, 71 und D</strong> zur Station Rathausplatz/Burgtheater, die <strong>Linie 2</strong> zur Station Parlament, die <strong>U2</strong> zur Station Rathaus und die <strong>U3</strong> zum Volkstheater, Ausgang Ring. Mit dem Rad: Radwege verlaufen sowohl vor dem Rathaus am Universitätsring als auch dahinter am Friedrich-Schmidt-Platz, Abstellplätze gibt es vor Ort.",
    ],
    faq: [
      {
        q: "Wann ist der Wiener Christkindlmarkt 2026 geöffnet?",
        a: "Vom 13. November bis 26. Dezember 2026, täglich von 10 bis 22 Uhr. Am 24. Dezember ist von 10 bis 18:30 Uhr geöffnet.",
      },
      {
        q: "Wie lange bleibt die Eisfläche?",
        a: "Der Eistraum am Christkindlmarkt läuft vom 13. November 2026 bis 6. Jänner 2027, täglich 10 bis 22 Uhr, am 24. Dezember 10 bis 18:30 Uhr. Am 31. Dezember ist er geschlossen.",
      },
      {
        q: "Wo findet der Markt statt?",
        a: "Am Rathausplatz im ersten Wiener Gemeindebezirk, zwischen Rathaus und Burgtheater.",
      },
      {
        q: "Wie komme ich hin?",
        a: "Mit den Straßenbahnlinien 1, 71 und D zur Station Rathausplatz/Burgtheater, mit der Linie 2 zur Station Parlament, mit der U2 zur Station Rathaus oder mit der U3 zum Volkstheater, Ausgang Ring. Radwege und Abstellplätze gibt es am Universitätsring und am Friedrich-Schmidt-Platz.",
      },
      {
        q: "Was kommt nach dem 6. Jänner?",
        a: "Der Wiener Eistraum, vom 22. Jänner bis 7. März 2027 am selben Platz.",
      },
    ],
    expertise:
      "Zwei Daten entscheiden über den Besuch, und beide stehen nicht dort, wo man sie sucht. Das erste ist der 24. Dezember: Wer den Markt als Teil des Heiligen Abends plant, hat bis <strong>18:30 Uhr</strong> Zeit und nicht bis 22 Uhr. Das zweite ist der 26. Dezember — danach ist der Markt weg, die Eisfläche aber nicht, und die Tage zwischen Weihnachten und dem 6. Jänner sind der einzige Zeitraum, in dem man am Rathausplatz Platz hat. Wer den Markt selbst leer erleben will, kommt in der zweiten Novemberhälfte an einem Vormittag: geöffnet ist ab 10 Uhr, voll wird es ab dem späten Nachmittag.",
  },

  {
    slug: "wiener-eistraum-2027",
    createdAt: "2026-09-12T23:41:00+04:00",
    updatedAt: "2026-09-12T23:41:00+04:00",
    site: "vien",
    image: "/covers/wiener-eistraum-2027.jpg",
    imageAlt:
      "Ein langer flacher grüner Steg auf schmalen Stützen über einem breiten zinnoberroten Rücken, darunter zwei winzige Figuren, auf warmem Cremegrund",
    imageKind: "generated",
    imageWidth: 1536,
    imageHeight: 864,
    title: "Wiener Eistraum 2027",
    summary:
      "Über 10.000 Quadratmeter Eis am Rathausplatz in Wien, vom 22. Jänner bis 7. März 2027, mit Sky Rink, Eisstockbahnen ab 17 Uhr und Verleih vor Ort.",
    start: "2027-01-22",
    end: "2027-03-07",
    utcOffset: "+01:00",
    venue: "Rathausplatz",
    city: "Wien",
    country: "Österreich",
    geo: {
      name: "Rathausplatz, Wien",
      lat: 48.212293,
      lng: 16.359847,
    },
    organizer: "stadt wien marketing",
    category: "Eislaufen",
    ticket: {
      url: "https://www.wienereistraum.com/",
      label: "Öffnungszeiten und Tickets",
    },
    source: {
      name: "Wiener Eistraum",
      url: "https://www.wienereistraum.com/",
      verifiedOn: "2026-09-12",
    },
    body: [
      "Eine Eisfläche von <strong>über 10.000 Quadratmetern</strong> mitten in der Stadt, und sie liegt nicht nur am Boden: Der <strong>Sky Rink</strong> führt über Pfade im Rathauspark bis in den ersten Stock und hat heuer eine neue Aussichtsplattform. Der Wiener Eistraum läuft vom <strong>22. Jänner bis 7. März 2027</strong> am Rathausplatz.",
      "## Was am Platz steht",
      "Vier große Flächen, dazu die romantischen Pfade im Park und der erhöhte Sky Rink. <strong>Ab 17 Uhr</strong> wird die Anfänger:innenfläche zur <strong>Eisstockbahn</strong> — auf professionellen Bahnen, gedacht für Gruppen, die sich gegenseitig herausfordern wollen, statt Runden zu drehen.",
      "## Ausrüstung vor Ort",
      "Der Verleih hält mit <strong>Warmluft vorgewärmte Eislaufschuhe in den Größen 23 bis 52</strong> bereit. <strong>300 Schutzhelme</strong> und verstellbare <strong>Doppelkufen in den Größen 21 bis 25</strong> stehen <strong>kostenlos</strong> zur Verfügung, solange der Vorrat reicht. Eigene Schlittschuhe kann man vor Ort schleifen lassen, und <strong>900 Schließfächer</strong> gibt es dazu. Alle Services sind im Online-Shop um <strong>10 Prozent günstiger</strong>.",
      "## Zwei Wege, weniger zu zahlen",
      "Erstens die <strong>Schulaktion</strong>: Die Stadt Wien lädt Wiener Kindergärten, Schulen und Horte im Schulverband an Schultagen von <strong>Montag bis Freitag, 10 bis 16 Uhr</strong>, kostenlos aufs Eis; Eislaufschuhe gibt es dabei vergünstigt. Rund <strong>45.000 Kinder</strong> nützen das pro Jahr. Zweitens der <strong>Vorteilsclub der Stadt Wien</strong>: Mitglieder kommen an <strong>allen Montagen um 50 Prozent günstiger</strong> hinein, die Mitgliedschaft selbst ist kostenfrei.",
      "## Nachhaltigkeit",
      "Der Eistraum führt Maßnahmen zur Verringerung des Energieverbrauchs, ein Abfallsystem und <strong>75 Prozent Speisen und Getränke in biologischer Qualität</strong> an. Seit <strong>2023</strong> ist die Veranstaltung mit dem Zertifikat <strong>ÖkoEvent PLUS</strong> ausgezeichnet.",
      "## Davor",
      "Am selben Platz läuft von <strong>13. November 2026 bis 6. Jänner 2027</strong> der Eistraum am Christkindlmarkt. Zwischen 7. Jänner und 21. Jänner ist der Rathausplatz eisfrei.",
    ],
    faq: [
      {
        q: "Wann ist der Wiener Eistraum 2027 geöffnet?",
        a: "Vom 22. Jänner bis 7. März 2027 am Rathausplatz in Wien.",
      },
      {
        q: "Wie groß ist die Eisfläche?",
        a: "Über 10.000 Quadratmeter, verteilt auf vier große Flächen, Pfade im Rathauspark und den erhöhten Sky Rink, der heuer eine neue Aussichtsplattform hat.",
      },
      {
        q: "Kann man Schlittschuhe ausleihen?",
        a: "Ja. Der Verleih hat mit Warmluft vorgewärmte Eislaufschuhe in den Größen 23 bis 52. 300 Schutzhelme und verstellbare Doppelkufen in den Größen 21 bis 25 sind kostenlos, solange der Vorrat reicht. Eigene Schlittschuhe kann man vor Ort schleifen lassen.",
      },
      {
        q: "Gibt es Ermäßigungen?",
        a: "Mitglieder des Vorteilsclubs der Stadt Wien zahlen an allen Montagen 50 Prozent weniger. Wiener Kindergärten, Schulen und Horte im Schulverband laufen im Rahmen der Schulaktion an Schultagen von Montag bis Freitag zwischen 10 und 16 Uhr kostenlos. Alle Services sind im Online-Shop um 10 Prozent günstiger.",
      },
      {
        q: "Ab wann gibt es Eisstockschießen?",
        a: "Ab 17 Uhr wird die Anfänger:innenfläche zur Eisstockbahn.",
      },
    ],
    expertise:
      "Der Eistraum ist zwei Veranstaltungen in einer, und die Fläche, auf der man steht, entscheidet darüber, wie der Abend wird. Wer Runden drehen will, kommt unter der Woche und früh: Ab 17 Uhr verschwindet die Anfänger:innenfläche in die Eisstockbahnen, und genau dann füllt sich der Rest. Wer in der Gruppe kommt, dreht das um — der Eisstock ist der Teil, bei dem auch die mitkönnen, die nicht eislaufen. Und die zwei Rabatte sind kein Kleingeld: Montag mit dem kostenlosen Vorteilsclub sind minus 50 Prozent, dazu zehn Prozent auf Verleih und Services im Online-Shop, wenn man vorher bucht statt an der Kassa zu überlegen.",
  },
];
