import type { EventItem } from "../types.ts";

export const items: EventItem[] = [
  {
    slug: "viennale-2026",
    site: "vien",
    image: "/covers/viennale-2026.jpg",
    imageAlt: "Ein Papierstreifen aus Filmkadern quer durchs Bild, drei Kader in Zinnoberrot, ein moosgrüner Lichtkegel am Rand",
    imageKind: "generated",
    imageWidth: 1536,
    imageHeight: 864,
    title: "Viennale 2026",
    summary:
      "Österreichs größtes Filmfestival läuft vom 22. Oktober bis 3. November. Die 64. Ausgabe bringt eine Retrospektive zu Robert Aldrich und ein Ferien-Abo für Jugendliche um 20 Euro.",
    start: "2026-10-22",
    end: "2026-11-03",
    utcOffset: "+02:00",
    city: "Wien",
    organizer: "Viennale",
    category: "Filmfestival",
    featured: 1,
    source: {
      name: "Viennale",
      url: "https://www.viennale.at/de",
      verifiedOn: "2026-09-06",
    },
    ticket: { url: "https://www.viennale.at/de", label: "Zum Festival" },
    body: [
      "Zwölf Tage lang gehört das Kino in Wien wieder dem Festival. Die Viennale ist das größte Filmfestival Österreichs, und sie ist eines der wenigen großen, die keinen Wettbewerb haben: Es gibt keine Jury, die am Ende einen Sieger ausruft, sondern ein kuratiertes Programm und ein Publikum.",
      "## Die Daten",
      "<strong>22. Oktober bis 3. November 2026</strong>, in den Festivalkinos in Wien. Es ist die <strong>64. Ausgabe</strong>.",
      "## Was im Programm steht",
      "Die Viennale zeigt neue Filme aus aller Welt und aus Österreich, darunter internationale Premieren. Für 2026 angekündigt sind eine <strong>Retrospektive zu Robert Aldrich</strong> sowie Spezialprogramme zu <strong>Jocelyne Saab</strong>, <strong>Phil Solomon</strong>, <strong>Vasko Pregelj</strong> und dem <strong>österreichischen Film der Neunzigerjahre</strong>.",
      "## Tickets",
      "Das <strong>Ferien-Abo</strong> gibt Jugendlichen ab 14 Jahren vier Festivalfilme um <strong>20 Euro</strong>. Der Termin für den Vorverkaufsstart 2026 stand am 6. September noch nicht auf der Festivalseite; im Vorjahr begann er rund zwei Wochen vor Festivalbeginn an einem Samstagvormittag. Wir tragen hier kein Datum ein, das die Viennale nicht genannt hat.",
      "## Die vollständige Kinoliste",
      "Ebenfalls noch nicht veröffentlicht. Die Seite führt die Festivalkinos als Menüpunkt, nennt sie aber noch nicht einzeln.",
    ],
    expertise:
      "Zwei Dinge, die den Unterschied zwischen einem guten und einem frustrierenden Viennale-Besuch ausmachen. Erstens: Ein Festival ohne Wettbewerb hat auch keinen Preisträgerfilm, über den danach alle reden — die Auswahl trifft man selbst, und die Retrospektive ist erfahrungsgemäß der Teil, den man später am ehesten bereut verpasst zu haben, weil diese Kopien sonst nirgends laufen. Zweitens: Der Vorverkauf ist der eigentliche Engpass, nicht das Festival. Wer erst in der Festivalwoche schaut, bekommt die Abendvorstellungen der bekannten Titel nicht mehr; die Vormittage in der zweiten Woche sind dagegen fast immer offen.",
  },

  {
    slug: "wien-modern-39",
    site: "vien",
    image: "/covers/wien-modern-39.jpg",
    imageAlt: "Ein breites moosgrünes Flussband aus Papier unter gestaffelten zinnoberroten Klangbalken",
    imageKind: "generated",
    imageWidth: 1536,
    imageHeight: 864,
    title: "Wien Modern 39",
    summary:
      "Das Festival für neue Musik eröffnet am 30. Oktober im Wiener Konzerthaus mit der Uraufführung von Pia Palmes „Mit der Donau“. Das ganze Programm kommt am 8. September, dann startet auch der Vorverkauf.",
    start: "2026-10-30",
    utcOffset: "+01:00",
    venue: "Wiener Konzerthaus",
    city: "Wien",
    organizer: "Wien Modern",
    category: "Musikfestival",
    featured: 2,
    source: {
      name: "Wien Modern",
      url: "https://www.wienmodern.at/",
      verifiedOn: "2026-09-06",
    },
    ticket: { url: "https://www.wienmodern.at/", label: "Zum Festival" },
    body: [
      "Wien Modern ist das Festival, das der Stadt jedes Jahr für ein paar Wochen zeigt, wie zeitgenössische Musik klingt, wenn sie nicht zwischen zwei Klassikprogrammen versteckt wird. Die 39. Ausgabe beginnt an der Donau — jedenfalls thematisch.",
      "## Der Eröffnungsabend",
      "<strong>30. Oktober 2026</strong>, <strong>Wiener Konzerthaus</strong>: die Uraufführung von <strong>„Mit der Donau“</strong> von <strong>Pia Palme</strong>, entstanden in Zusammenarbeit mit der Künstlerin <strong>Lisa Horvath</strong> im <strong>Nationalpark Donau-Auen</strong>.",
      "## Was am 8. September kommt",
      "Das Festival schreibt es selbst: „Das volle Programm der 39. Festivalausgabe präsentieren wir am 8. September, dann startet auch der Vorverkauf!“ Bis dahin steht der Eröffnungsabend, und sonst nichts.",
      "## Was noch nicht feststeht",
      "Das Enddatum, die Zahl der Veranstaltungen und die Liste der Spielstätten. Wien Modern läuft üblicherweise mehrere Wochen und an vielen Orten in der Stadt — aber „üblicherweise“ ist kein Datum, und wir tragen hier keines ein, das das Festival nicht genannt hat.",
    ],
    expertise:
      "Der 8. September ist bei diesem Festival der wichtigere Termin als der 30. Oktober. Programm und Vorverkauf starten am selben Tag, und das heißt: Wer am 8. September nachmittags schaut, hat die gesamte Auswahl vor sich; wer eine Woche wartet, hat die Uraufführungen in den kleinen Sälen nicht mehr. Bei einem Festival für neue Musik ist das keine Formalie — die kleinen Säle sind der Ort, an dem die Stücke stattfinden, die es danach nie wieder zu hören gibt.",
  },

  {
    slug: "vienna-coffee-festival-2026",
    site: "vien",
    image: "/covers/vienna-coffee-festival-2026.jpg",
    imageAlt: "Ein goldener Ring mit einer roten Scheibe darin und drei kurzen roten Dampfstrichen darüber, auf cremefarbenem Grund",
    imageKind: "generated",
    imageWidth: 1536,
    imageHeight: 864,
    title: "Vienna Coffee Festival 2026",
    summary:
      "Über hundert Röstereien und Spezialitäten-Aussteller drei Tage lang in der Wiener Marx Halle, von 11. bis 13. September, mit Workshops, Cuppings und einem eigenen B2B-Tag.",
    start: "2026-09-11",
    end: "2026-09-13",
    utcOffset: "+02:00",
    venue: "Marx Halle, Karl-Farkas-Gasse 19",
    city: "Wien",
    country: "Österreich",
    organizer: "Lefor Oberbauer",
    category: "Festival",
    source: {
      name: "Vienna Coffee Festival",
      url: "https://www.viennacoffeefestival.cc/",
      verifiedOn: "2026-09-08",
    },
    body: [
      "In einer Stadt, deren Kaffeehauskultur zum Weltkulturerbe zählt, ist ein Festival für Spezialitätenkaffee eine kleine Provokation. Es findet trotzdem statt, und zwar in einer Industriehalle.",
      "## Die Daten",
      "<strong>11. bis 13. September 2026</strong> in der <strong>Marx Halle</strong>, Karl-Farkas-Gasse 19, 1030 Wien. Veranstalter ist <strong>Lefor Oberbauer</strong>, Gründer und Betreiber des Festivals. Karten laufen über wien-ticket.at.",
      "## Wer ausstellt",
      "Über <strong>100 Kaffeeröster und Spezialitäten-Aussteller</strong>, dazu Maschinenhersteller wie <strong>La Cimbali</strong>, <strong>Faema</strong> und <strong>La Marzocco</strong>.",
      "## Was im Programm steht",
      "<strong>Workshops</strong>, <strong>Cuppings</strong>, eine <strong>Open Stage</strong> und Führungen. Ein eigener <strong>B2B-Day</strong> richtet sich an Geschäftspartner.",
    ],
    expertise:
      "Das Cupping ist der Teil, für den man kommt, und der Teil, der zuerst ausgebucht ist — anders als bei den Ausstellerständen sitzt man dort in einer festen Runde, und die Plätze sind gezählt. Wer nur einen Tag hat, nimmt den Freitag: der B2B-Tag zieht das Fachpublikum, und an den Ständen wird an diesem Tag anders geredet als am Wochenende, wo dieselben Leute Schlangen abarbeiten. Und eine Anmerkung zur Halle: Die Marx Halle ist eine Gusseisenkonstruktion aus dem 19. Jahrhundert ohne Klimaanlage. Bei einem warmen Septemberwochenende ist der Vormittag die angenehmere Hälfte des Tages.",
  },
];
