import type { EventItem } from "../types.ts";

export const items: EventItem[] = [
  {
    slug: "viennale-2026",
    site: "vien",
    image: "/covers/viennale-2026.jpg",
    imageAlt: "Ein Papierstreifen aus Filmkadern quer durchs Bild, drei Kader in Zinnoberrot, ein moosgrüner Lichtkegel am Rand",
    imageKind: "generated",
    imageWidth: 1536,
    imageHeight: 864,
    title: "Viennale 2026",
    summary:
      "Österreichs größtes Filmfestival läuft vom 22. Oktober bis 3. November. Die 64. Ausgabe bringt eine Retrospektive zu Robert Aldrich und ein Ferien-Abo für Jugendliche um 20 Euro.",
    start: "2026-10-22",
    end: "2026-11-03",
    utcOffset: "+02:00",
    city: "Wien",
    organizer: "Viennale",
    category: "Filmfestival",
    featured: 1,
    source: {
      name: "Viennale",
      url: "https://www.viennale.at/de",
      verifiedOn: "2026-09-06",
    },
    ticket: { url: "https://www.viennale.at/de", label: "Zum Festival" },
    body: [
      "Zwölf Tage lang gehört das Kino in Wien wieder dem Festival. Die Viennale ist das größte Filmfestival Österreichs, und sie ist eines der wenigen großen, die keinen Wettbewerb haben: Es gibt keine Jury, die am Ende einen Sieger ausruft, sondern ein kuratiertes Programm und ein Publikum.",
      "## Die Daten",
      "<strong>22. Oktober bis 3. November 2026</strong>, in den Festivalkinos in Wien. Es ist die <strong>64. Ausgabe</strong>.",
      "## Was im Programm steht",
      "Die Viennale zeigt neue Filme aus aller Welt und aus Österreich, darunter internationale Premieren. Für 2026 angekündigt sind eine <strong>Retrospektive zu Robert Aldrich</strong> sowie Spezialprogramme zu <strong>Jocelyne Saab</strong>, <strong>Phil Solomon</strong>, <strong>Vasko Pregelj</strong> und dem <strong>österreichischen Film der Neunzigerjahre</strong>.",
      "## Tickets",
      "Das <strong>Ferien-Abo</strong> gibt Jugendlichen ab 14 Jahren vier Festivalfilme um <strong>20 Euro</strong>. Der Termin für den Vorverkaufsstart 2026 stand am 6. September noch nicht auf der Festivalseite; im Vorjahr begann er rund zwei Wochen vor Festivalbeginn an einem Samstagvormittag. Wir tragen hier kein Datum ein, das die Viennale nicht genannt hat.",
      "## Die vollständige Kinoliste",
      "Ebenfalls noch nicht veröffentlicht. Die Seite führt die Festivalkinos als Menüpunkt, nennt sie aber noch nicht einzeln.",
    ],
    expertise:
      "Zwei Dinge, die den Unterschied zwischen einem guten und einem frustrierenden Viennale-Besuch ausmachen. Erstens: Ein Festival ohne Wettbewerb hat auch keinen Preisträgerfilm, über den danach alle reden — die Auswahl trifft man selbst, und die Retrospektive ist erfahrungsgemäß der Teil, den man später am ehesten bereut verpasst zu haben, weil diese Kopien sonst nirgends laufen. Zweitens: Der Vorverkauf ist der eigentliche Engpass, nicht das Festival. Wer erst in der Festivalwoche schaut, bekommt die Abendvorstellungen der bekannten Titel nicht mehr; die Vormittage in der zweiten Woche sind dagegen fast immer offen.",
  },

  {
    slug: "wien-modern-39",
    site: "vien",
    image: "/covers/wien-modern-39.jpg",
    imageAlt: "Ein breites moosgrünes Flussband aus Papier unter gestaffelten zinnoberroten Klangbalken",
    imageKind: "generated",
    imageWidth: 1536,
    imageHeight: 864,
    title: "Wien Modern 39",
    summary:
      "Das Festival für neue Musik eröffnet am 30. Oktober im Wiener Konzerthaus mit der Uraufführung von Pia Palmes „Mit der Donau“. Das ganze Programm kommt am 8. September, dann startet auch der Vorverkauf.",
    start: "2026-10-30",
    utcOffset: "+01:00",
    venue: "Wiener Konzerthaus",
    city: "Wien",
    organizer: "Wien Modern",
    category: "Musikfestival",
    featured: 2,
    source: {
      name: "Wien Modern",
      url: "https://www.wienmodern.at/",
      verifiedOn: "2026-09-06",
    },
    ticket: { url: "https://www.wienmodern.at/", label: "Zum Festival" },
    body: [
      "Wien Modern ist das Festival, das der Stadt jedes Jahr für ein paar Wochen zeigt, wie zeitgenössische Musik klingt, wenn sie nicht zwischen zwei Klassikprogrammen versteckt wird. Die 39. Ausgabe beginnt an der Donau — jedenfalls thematisch.",
      "## Der Eröffnungsabend",
      "<strong>30. Oktober 2026</strong>, <strong>Wiener Konzerthaus</strong>: die Uraufführung von <strong>„Mit der Donau“</strong> von <strong>Pia Palme</strong>, entstanden in Zusammenarbeit mit der Künstlerin <strong>Lisa Horvath</strong> im <strong>Nationalpark Donau-Auen</strong>.",
      "## Was am 8. September kommt",
      "Das Festival schreibt es selbst: „Das volle Programm der 39. Festivalausgabe präsentieren wir am 8. September, dann startet auch der Vorverkauf!“ Bis dahin steht der Eröffnungsabend, und sonst nichts.",
      "## Was noch nicht feststeht",
      "Das Enddatum, die Zahl der Veranstaltungen und die Liste der Spielstätten. Wien Modern läuft üblicherweise mehrere Wochen und an vielen Orten in der Stadt — aber „üblicherweise“ ist kein Datum, und wir tragen hier keines ein, das das Festival nicht genannt hat.",
    ],
    expertise:
      "Der 8. September ist bei diesem Festival der wichtigere Termin als der 30. Oktober. Programm und Vorverkauf starten am selben Tag, und das heißt: Wer am 8. September nachmittags schaut, hat die gesamte Auswahl vor sich; wer eine Woche wartet, hat die Uraufführungen in den kleinen Sälen nicht mehr. Bei einem Festival für neue Musik ist das keine Formalie — die kleinen Säle sind der Ort, an dem die Stücke stattfinden, die es danach nie wieder zu hören gibt.",
  },

  {
    slug: "vienna-coffee-festival-2026",
    site: "vien",
    image: "/covers/vienna-coffee-festival-2026.jpg",
    imageAlt: "Ein goldener Ring mit einer roten Scheibe darin und drei kurzen roten Dampfstrichen darüber, auf cremefarbenem Grund",
    imageKind: "generated",
    imageWidth: 1536,
    imageHeight: 864,
    title: "Vienna Coffee Festival 2026",
    summary:
      "Über hundert Röstereien und Spezialitäten-Aussteller drei Tage lang in der Wiener Marx Halle, von 11. bis 13. September, mit Workshops, Cuppings und einem eigenen B2B-Tag.",
    start: "2026-09-11",
    end: "2026-09-13",
    utcOffset: "+02:00",
    venue: "Marx Halle, Karl-Farkas-Gasse 19",
    city: "Wien",
    country: "Österreich",
    organizer: "Lefor Oberbauer",
    category: "Festival",
    source: {
      name: "Vienna Coffee Festival",
      url: "https://www.viennacoffeefestival.cc/",
      verifiedOn: "2026-09-08",
    },
    body: [
      "In einer Stadt, deren Kaffeehauskultur zum Weltkulturerbe zählt, ist ein Festival für Spezialitätenkaffee eine kleine Provokation. Es findet trotzdem statt, und zwar in einer Industriehalle.",
      "## Die Daten",
      "<strong>11. bis 13. September 2026</strong> in der <strong>Marx Halle</strong>, Karl-Farkas-Gasse 19, 1030 Wien. Veranstalter ist <strong>Lefor Oberbauer</strong>, Gründer und Betreiber des Festivals. Karten laufen über wien-ticket.at.",
      "## Wer ausstellt",
      "Über <strong>100 Kaffeeröster und Spezialitäten-Aussteller</strong>, dazu Maschinenhersteller wie <strong>La Cimbali</strong>, <strong>Faema</strong> und <strong>La Marzocco</strong>.",
      "## Was im Programm steht",
      "<strong>Workshops</strong>, <strong>Cuppings</strong>, eine <strong>Open Stage</strong> und Führungen. Ein eigener <strong>B2B-Day</strong> richtet sich an Geschäftspartner.",
    ],
    expertise:
      "Das Cupping ist der Teil, für den man kommt, und der Teil, der zuerst ausgebucht ist — anders als bei den Ausstellerständen sitzt man dort in einer festen Runde, und die Plätze sind gezählt. Wer nur einen Tag hat, nimmt den Freitag: der B2B-Tag zieht das Fachpublikum, und an den Ständen wird an diesem Tag anders geredet als am Wochenende, wo dieselben Leute Schlangen abarbeiten. Und eine Anmerkung zur Halle: Die Marx Halle ist eine Gusseisenkonstruktion aus dem 19. Jahrhundert ohne Klimaanlage. Bei einem warmen Septemberwochenende ist der Vormittag die angenehmere Hälfte des Tages.",
  },

  {
    slug: "vienna-design-week-2026",
    site: "vien",
    image: "/covers/vienna-design-week-2026.jpg",
    imageAlt: "Ein gestufter Turm aus roten und grünen Blöcken auf hellem Grund, als Linolschnitt",
    imageKind: "generated",
    imageWidth: 1536,
    imageHeight: 864,
    title: "Vienna Design Week 2026",
    summary:
      "Zehn Tage Design in ganz Wien, vom 25. September bis 4. Oktober, an rund 50 Orten und bei den meisten Programmpunkten bei freiem Eintritt. Die 20. Ausgabe hat ihre Festivalzentrale in einem Bürohochhaus von Harry Glück in Hietzing.",
    start: "2026-09-25",
    end: "2026-10-04",
    utcOffset: "+02:00",
    city: "Wien",
    organizer: "Vienna Design Week",
    category: "Designfestival",
    source: {
      name: "Vienna Design Week",
      url: "https://www.viennadesignweek.at/en/",
      verifiedOn: "2026-09-08",
    },
    ticket: { url: "https://www.viennadesignweek.at/en/", label: "Zum Festival" },
    body: [
      "Ein Designfestival, das keine Messehalle mietet, sondern die Stadt benutzt: Vienna Design Week findet in Werkstätten, Geschäften, Höfen und einem leerstehenden Bürohochhaus statt, und wer hingeht, geht dorthin, wo gearbeitet wird.",
      "## Die Daten",
      "<strong>25. September bis 4. Oktober 2026</strong>, an rund <strong>50 Orten</strong> in Wien. Es ist die <strong>20. Ausgabe</strong> — das Festival nennt sich selbst Österreichs wichtigstes kuratiertes Designfestival und zählt üblicherweise rund 200 Programmpunkte und 40.000 Besucherinnen und Besucher.",
      "## Was der Eintritt kostet",
      "Bei den <strong>meisten Programmpunkten nichts</strong>. Einzelne Formate sind kostenpflichtig oder brauchen eine Anmeldung; welche das 2026 sind, stand am 8. September noch nicht fest.",
      "## Die Festivalzentrale",
      "Ein Bürohochhaus am <strong>Hietzinger Kai 101</strong> im 13. Bezirk, in den Siebzigerjahren von <strong>Harry Glück</strong> gebaut. Dort ist auch das Gastland <strong>Luxemburg</strong> mit eigenen Ausstellungsprojekten untergebracht.",
      "## Die Formate",
      "Ausstellungen und Installationen, Führungen, Workshops, Studiobesuche und Produktionsstätten. Das bekannteste Format sind die <strong>Passionswege</strong>: internationale und österreichische Gestalterinnen und Gestalter arbeiten dafür mit Wiener Handwerksbetrieben zusammen. Neu 2026 sind <strong>Akustikdesign</strong> und <strong>Urban Food Design</strong>.",
    ],
    faq: [
      {
        q: "Kostet die Vienna Design Week Eintritt?",
        a: "Bei den meisten Programmpunkten ist der Eintritt frei. Einzelne Workshops und Führungen sind kostenpflichtig oder brauchen eine Anmeldung.",
      },
      {
        q: "Wann findet die Vienna Design Week 2026 statt?",
        a: "Von <strong>25. September bis 4. Oktober 2026</strong>, zehn Tage lang an rund 50 Orten in Wien.",
      },
      {
        q: "Wo ist die Festivalzentrale 2026?",
        a: "In einem Bürohochhaus am Hietzinger Kai 101 im 13. Bezirk, gebaut in den Siebzigerjahren von Harry Glück.",
      },
      {
        q: "Was sind die Passionswege?",
        a: "Das älteste Format des Festivals: Gestalterinnen und Gestalter arbeiten für eine Saison mit einem Wiener Handwerksbetrieb zusammen, und das Ergebnis wird in der Werkstatt gezeigt, nicht auf einem Messestand.",
      },
    ],
    expertise:
      "Die Passionswege sind der Grund, warum dieses Festival anders ist als eine Designmesse, und sie sind auch der Teil, der am meisten Weg kostet: Die Werkstätten liegen über die Stadt verteilt, und wer sie an einem Nachmittag abhaken will, verbringt den Nachmittag in der U-Bahn. Sinnvoller ist es, sich einen Bezirk vorzunehmen. Zweitens die Festivalzentrale: Ein leerstehendes Bürohochhaus ist als Ort selbst schon die halbe Ausstellung, und es ist der einzige Punkt im Programm, an dem man ohne Planung hingehen und trotzdem viel sehen kann.",
  },

  {
    slug: "wiener-kaiser-wiesn-2026",
    site: "vien",
    image: "/covers/wiener-kaiser-wiesn-2026.jpg",
    imageAlt: "Drei Festzelte nebeneinander in Rot, Ocker und Grün auf cremefarbenem Grund, das mittlere höher und mit einer kleinen roten Fahne",
    imageKind: "generated",
    imageWidth: 1536,
    imageHeight: 864,
    title: "Wiener Kaiser Wiesn 2026",
    summary:
      "Achtzehn Tage Volksfest auf der Kaiserwiese im Prater, von 24. September bis 11. Oktober. Der Eintritt aufs Gelände ist frei, Karten braucht man nur für die Abendveranstaltungen in den drei Zelten.",
    start: "2026-09-24",
    end: "2026-10-11",
    utcOffset: "+02:00",
    venue: "Kaiserwiese, Prater",
    city: "Wien",
    organizer: "Wiener Kaiser Wiesn GmbH",
    category: "Volksfest",
    tickets: { priceFrom: 0, priceTo: 0, currency: "EUR" },
    source: {
      name: "Stadt Wien",
      url: "https://www.wien.gv.at/veranstaltungen/wiener-kaiser-wiesn-2026",
      verifiedOn: "2026-09-08",
    },
    ticket: { url: "https://kaiserwiesn.at/en/", label: "Zur Kaiser Wiesn" },
    body: [
      "Achtzehn Tage lang steht auf der Kaiserwiese im Prater das größte Volksfest Österreichs, und der Eintritt aufs Gelände kostet nichts. Das ist der Unterschied zu München, den man kennen sollte, bevor man ein Ticket sucht: Man braucht keines, um hinzugehen.",
      "## Die Daten",
      "<strong>24. September bis 11. Oktober 2026</strong>, <strong>Kaiserwiese</strong> im Prater, 2. Bezirk.",
      "## Was der Eintritt kostet",
      "<strong>Nichts.</strong> Karten braucht man nur für die <strong>Abendveranstaltungen in den drei Festzelten</strong> — Gösser Kaiserzelt, Wiesbauer Kaiserzelt und Nordic Spirit Kaiserzelt.",
      "## Die Zelte",
      "Drei an der Zahl, mit Live-Bands. Das Musikprogramm endet um Mitternacht.",
    ],
    faq: [
      {
        q: "Kostet die Wiener Kaiser Wiesn Eintritt?",
        a: "Das Gelände auf der Kaiserwiese ist <strong>frei zugänglich</strong>. Karten braucht man nur für die Abendveranstaltungen in den drei Festzelten.",
      },
      {
        q: "Wann ist die Wiener Kaiser Wiesn 2026?",
        a: "Von <strong>24. September bis 11. Oktober 2026</strong>, achtzehn Tage lang.",
      },
      {
        q: "Wo findet die Kaiser Wiesn statt?",
        a: "Auf der Kaiserwiese im Prater im 2. Bezirk, gleich beim Riesenrad.",
      },
      {
        q: "Wie viele Festzelte gibt es?",
        a: "Drei: das Gösser Kaiserzelt, das Wiesbauer Kaiserzelt und das Nordic Spirit Kaiserzelt.",
      },
    ],
    expertise:
      "Der freie Eintritt ist der Punkt, an dem die meisten falsch planen. Aufs Gelände kommt man ohne Karte, und tagsüber ist das auch die ganze Wahrheit — abends aber sind die Zelte der Ort, an dem das Fest stattfindet, und dafür braucht es eine Reservierung. Wer spontan am Samstagabend hinfährt, steht auf der Wiese und hört die Band durch die Zeltwand. Und die Lage ist der zweite Vorteil gegenüber München: Die Kaiserwiese liegt direkt beim Riesenrad an der U1, man kommt ohne Sonderfahrplan hin und wieder weg.",
  },

  {
    slug: "lange-nacht-der-museen-2026",
    site: "vien",
    image: "/covers/lange-nacht-der-museen-2026.jpg",
    imageAlt: "Drei hell erleuchtete hohe Fenster in einer dunkelroten Fassade",
    imageKind: "generated",
    imageWidth: 1536,
    imageHeight: 864,
    title: "ORF Lange Nacht der Museen 2026",
    summary:
      "Eine Nacht, ein Ticket, rund 270 Museen in ganz Österreich: am 3. Oktober von 18 bis 24 Uhr. Das Ticket kostet 19 Euro, ermäßigt 16, Kinder unter zwölf gehen frei.",
    start: "2026-10-03",
    startTime: "18:00",
    endTime: "24:00",
    utcOffset: "+02:00",
    city: "Wien",
    organizer: "ORF",
    category: "Museumsnacht",
    tickets: { priceFrom: 16, priceTo: 19, currency: "EUR" },
    source: {
      name: "ORF Lange Nacht der Museen",
      url: "https://langenacht.orf.at/",
      verifiedOn: "2026-09-08",
    },
    ticket: { url: "https://langenacht.orf.at/", label: "Zur Langen Nacht" },
    body: [
      "Ein Ticket, sechs Stunden, rund 270 Häuser: Die Lange Nacht der Museen ist der einzige Abend im Jahr, an dem man in Wien ein Museum verlässt, weil noch drei andere offen haben.",
      "## Die Daten",
      "<strong>Samstag, 3. Oktober 2026, 18 bis 24 Uhr</strong>, in ganz Österreich.",
      "## Was das Ticket kostet",
      "<strong>19 Euro</strong> regulär, <strong>16 Euro</strong> ermäßigt für Studierende, Seniorinnen und Senioren und Menschen mit Behinderung. Ein <strong>Regionalticket</strong> für ein einzelnes Bundesland kostet <strong>7 Euro</strong>. <strong>Kinder unter zwölf</strong> — geboren nach dem 2. Oktober 2014 — gehen <strong>gratis</strong>.",
      "## Wie viele Häuser mitmachen",
      "Rund <strong>270 Museen und Kultureinrichtungen</strong> in ganz Österreich, ein großer Teil davon in Wien.",
    ],
    faq: [
      {
        q: "Was kostet die Lange Nacht der Museen 2026?",
        a: "<strong>19 Euro</strong> regulär und <strong>16 Euro</strong> ermäßigt für ganz Österreich; ein Regionalticket für ein Bundesland kostet 7 Euro. Kinder unter zwölf zahlen nichts.",
      },
      {
        q: "Wann ist die Lange Nacht der Museen 2026?",
        a: "Am <strong>Samstag, 3. Oktober 2026, von 18 bis 24 Uhr</strong>.",
      },
      {
        q: "Wie viele Museen machen mit?",
        a: "Rund 270 Museen und Kultureinrichtungen in ganz Österreich.",
      },
      {
        q: "Gilt ein Ticket für alle Museen?",
        a: "Ja. Ein Ticket gilt für alle teilnehmenden Häuser in ganz Österreich; das günstigere Regionalticket gilt nur in einem Bundesland.",
      },
    ],
    expertise:
      "Sechs Stunden klingen nach viel und sind es nicht: Realistisch sind vier Häuser, wenn sie nahe beieinander liegen, und drei, wenn nicht. Der Fehler, den fast alle beim ersten Mal machen, ist das größte Haus zuerst — im Kunsthistorischen oder im Naturhistorischen ist der Abend vorbei, bevor er begonnen hat, und beide sind ohnehin ganzjährig offen. Die Nacht lohnt sich für die kleinen Sammlungen, die man sonst nie betritt, weil sie um 17 Uhr zusperren. Und das Regionalticket um 7 Euro ist für einen Wiener Abend die richtige Karte — die 19 Euro zahlt nur, wer wirklich Bundesländer wechselt.",
  },
];
