// Every third-party destination this site links to, keyed by the slug that
// /go/<slug>/ resolves to. Outbound links run through that hop so external
// domains collect no link equity from our pages, and /go/ is disallowed in
// robots.txt so the hops are never crawled or indexed themselves.
//
// Ticket links are the one place a visible outbound button is right: a
// reader deciding whether to go needs one click to the seller. It still goes
// through the hop. Two kinds of slug live here — tickets-<show>-<run> for a
// seller, venue-<venue> for a venue's own website. The show is in the ticket
// key because a run slug is only unique inside its show: Cats and Chicago
// both play Plymouth, and they are not sold by the same page.
export const outbound: Record<string, string> = {
  "chicago-official": "https://chicagothemusical.com/",
  "chicago-uk-tour": "https://chicagothemusical.com/uk-tour/",
  "chicago-international": "https://chicagothemusical.com/international/",
  "tickets-chicago-new-york":
    "https://www.telecharge.com/Chicago-tickets?AID=BWY0049300&utm_source=show_site&utm_campaign=chicagoSS&utm_medium=web&utm_id=BWY0049300",
  "tickets-chicago-tokyo": "https://www.kyodotokyo.com/chicago-en/",
  "tickets-chicago-osaka": "https://eplus.jp/sf/detail/0227890001?P6=001&P1=0402&P59=1",
  "tickets-chicago-dubai-ticketmaster":
    "https://www.ticketmaster.ae/artist/chicago-the-musical-tickets/1443524",
  "venue-coca-cola-arena": "https://coca-cola-arena.com/",
  "venue-ambassador-theatre": "https://www.shubert.nyc/theatres/ambassador",
  "tickets-chicago-aberdeen": "https://www.aberdeenperformingarts.com/whats-on/chicago-2027/",
  "tickets-chicago-belfast": "https://www.goh.co.uk/whats-on/chicago-2",
  "tickets-chicago-birmingham": "https://www.birminghamhippodrome.com/calendar/chicago/",
  "tickets-chicago-blackpool": "https://www.wintergardensblackpool.co.uk/events/chicago/",
  "tickets-chicago-bournemouth": "https://www.bournemouthpavilion.co.uk/events/chicago-2027",
  "tickets-chicago-bradford": "https://www.bradford-theatres.co.uk/whats-on/chicago",
  "tickets-chicago-brighton": "https://www.atgtickets.com/shows/chicago-the-musical/theatre-royal-brighton/",
  "tickets-chicago-bristol": "https://www.atgtickets.com/shows/chicago-the-musical/bristol-hippodrome/",
  "tickets-chicago-cardiff": "https://www.wmc.org.uk/en/whats-on/2027/chicago",
  "tickets-chicago-cheltenham": "https://www.everymantheatre.org.uk/shows/chicago/",
  "tickets-chicago-eastbourne": "https://trafalgartickets.com/eastbourne-theatres-eastbourne/en-GB/event/musical/chicago-tickets",
  "tickets-chicago-edinburgh": "https://www.atgtickets.com/shows/chicago-the-musical/edinburgh-playhouse/",
  "tickets-chicago-glasgow": "https://www.atgtickets.com/shows/chicago-the-musical/kings-theatre-glasgow/",
  "tickets-chicago-hull": "https://www.hulltheatres.co.uk/theatre-events/chicago",
  "tickets-chicago-liverpool": "https://www.atgtickets.com/shows/chicago-the-musical/liverpool-empire/",
  "tickets-chicago-manchester": "https://www.atgtickets.com/shows/chicago-the-musical/opera-house-manchester/",
  "tickets-chicago-milton-keynes": "https://www.atgtickets.com/shows/chicago-the-musical/milton-keynes-theatre/",
  "tickets-chicago-newcastle": "https://www.theatreroyal.co.uk/whats-on/chicago-3/",
  "tickets-chicago-norwich": "https://norwichtheatre.org/whats-on/chicago/",
  "tickets-chicago-nottingham": "https://www.trch.co.uk/whats-on/chicago-zcb4",
  "tickets-chicago-oxford": "https://www.atgtickets.com/shows/chicago-the-musical/new-theatre-oxford/",
  "tickets-chicago-plymouth": "https://theatreroyal.com/whats-on/chicago-2027/",
  "tickets-chicago-southend": "https://trafalgartickets.com/southend-theatres/en-GB/event/musical/chicago-tickets",
  "tickets-chicago-stoke": "https://www.atgtickets.com/shows/chicago-the-musical/regent-theatre/",
  "tickets-chicago-sunderland": "https://www.atgtickets.com/shows/chicago-the-musical/sunderland-empire/",
  "tickets-chicago-truro": "https://www.hallforcornwall.co.uk/whats-on/chicago/",
  "tickets-chicago-wimbledon": "https://www.atgtickets.com/shows/chicago-the-musical/new-wimbledon-theatre/",
  "tickets-chicago-woking": "https://www.atgtickets.com/shows/chicago-the-musical/woking-theatre/",
  "tickets-chicago-york": "https://www.atgtickets.com/shows/chicago-the-musical/grand-opera-house-york/",
  "venue-alhambra-theatre-bradford": "https://www.bradford-theatres.co.uk/",
  "venue-birmingham-hippodrome": "https://www.birminghamhippodrome.com/",
  "venue-blackpool-opera-house": "https://www.wintergardensblackpool.co.uk/",
  "venue-bournemouth-pavilion": "https://www.bournemouthpavilion.co.uk/",
  "venue-everyman-theatre-cheltenham": "https://www.everymantheatre.org.uk/",
  "venue-grand-opera-house-belfast": "https://www.goh.co.uk/",
  "venue-hall-for-cornwall": "https://www.hallforcornwall.co.uk/",
  "venue-his-majestys-theatre-aberdeen": "https://www.aberdeenperformingarts.com/",
  "venue-hull-new-theatre": "https://www.hulltheatres.co.uk/",
  "venue-newcastle-theatre-royal": "https://www.theatreroyal.co.uk/",
  "venue-norwich-theatre-royal": "https://norwichtheatre.org/",
  "venue-nottingham-royal-concert-hall": "https://www.trch.co.uk/",
  "venue-theatre-royal-plymouth": "https://theatreroyal.com/",
  "venue-venue-cymru": "https://www.venuecymru.co.uk/",
  "info-llandudno": "https://www.venuecymru.co.uk/chicago-3",
  "venue-wales-millennium-centre": "https://www.wmc.org.uk/",

  // The file page each venue photograph came from, and the licence it is
  // published under. Both are named in the caption under the picture
  // because the licence requires it — and both go through the hop, like
  // every other outbound address on this site.
  "photo-coca-cola-arena": "https://commons.wikimedia.org/wiki/File:Westlife_at_Coca-Cola_Arena_-_1.jpg",
  "photo-everyman-theatre-cheltenham": "https://commons.wikimedia.org/wiki/File:Everyman_Theatre,_Cheltenham-4077863023.jpg",
  "photo-grand-opera-house-york": "https://commons.wikimedia.org/wiki/File:Grand_Opera_House,_York_Feb_2022_02.jpg",
  "photo-hall-for-cornwall": "https://commons.wikimedia.org/wiki/File:Hall_for_Cornwall_on_Back_Quay,_Truro_-_geograph.org.uk_-_4429068.jpg",
  "photo-hull-new-theatre": "https://commons.wikimedia.org/wiki/File:Hull_New_Theatre,_Hull_-_geograph.org.uk_-_5233236.jpg",
  "photo-kings-theatre-glasgow": "https://commons.wikimedia.org/wiki/File:King%27s_Theatre,_Glasgow_02.jpg",
  "photo-liverpool-empire": "https://commons.wikimedia.org/wiki/File:Empire_Theatre,_Lime_Street,_Liverpool_-_geograph.org.uk_-_4767710.jpg",
  "photo-new-theatre-oxford": "https://commons.wikimedia.org/wiki/File:New_Theatre_Oxford_Geograph-4785233-by-Steve-Daniels.jpg",
  "photo-new-wimbledon-theatre": "https://commons.wikimedia.org/wiki/File:New_Wimbledon_Theatre_-_geograph.org.uk_-_3809753.jpg",
  "photo-norwich-theatre-royal": "https://commons.wikimedia.org/wiki/File:Norwich_Theatre_Royal_-_geograph.org.uk_-_7566091.jpg",
  "photo-nottingham-royal-concert-hall": "https://commons.wikimedia.org/wiki/File:Theatre_Royal-Royal_Concert_Hall,_South_Sherwood_Street_-_geograph.org.uk_-_7397361.jpg",
  "photo-opera-house-manchester": "https://commons.wikimedia.org/wiki/File:Opera_House,_Manchester_-_geograph.org.uk_-_5624967.jpg",
  "photo-orix-theater": "https://commons.wikimedia.org/wiki/File:ORIX_Theatre.jpg",
  "photo-sheffield-lyceum": "https://commons.wikimedia.org/wiki/File:Lyceum_Theatre,_Sheffield_(1).JPG",
  "photo-sunderland-empire": "https://commons.wikimedia.org/wiki/File:Sunderland_-_High_St_West_%5E_Empire_Theatre_-_geograph.org.uk_-_7939436.jpg",
  "photo-theatre-royal-brighton": "https://commons.wikimedia.org/wiki/File:Theatre_Royal,_New_Road,_Brighton_(NHLE_Code_1380103)_(May_2020)_(2).JPG",
  "photo-theatre-royal-plymouth": "https://commons.wikimedia.org/wiki/File:Theatre_Royal,_Plymouth.jpg",
  "photo-venue-cymru": "https://commons.wikimedia.org/wiki/File:Venue_Cymru_(geograph_5294767).jpg",
  "photo-woking-theatre": "https://commons.wikimedia.org/wiki/File:New_Victoria_Theatre,_Victoria_Way,_Woking_(June_2015)_(2).jpg",
  "photo-ambassador-theatre": "https://commons.wikimedia.org/wiki/File:W_49_St_Dec_2021_17.jpg",
  "photo-tokyu-theatre-orb": "https://commons.wikimedia.org/wiki/File:Shibuya_Hikarie_Tokyu_Theatre_Orb_(49333094033).jpg",
  "photo-alhambra-theatre-bradford": "https://commons.wikimedia.org/wiki/File:The_Alhambra_Theatre,_Bradford_-_geograph.org.uk_-_7153310.jpg",
  "photo-birmingham-hippodrome": "https://commons.wikimedia.org/wiki/File:Birmingham_Hippodrome.jpg",
  "photo-blackpool-opera-house": "https://commons.wikimedia.org/wiki/File:The_Winter_Gardens_-_geograph.org.uk_-_5551191.jpg",
  "photo-bournemouth-pavilion": "https://commons.wikimedia.org/wiki/File:Bournemouth_Pavilion_%5E2_-_geograph.org.uk_-_1923963.jpg",
  "photo-bristol-hippodrome": "https://commons.wikimedia.org/wiki/File:Hippodrome_Theatre,_Bristol._-_panoramio.jpg",
  "photo-cliffs-pavilion-southend": "https://commons.wikimedia.org/wiki/File:Cliffs_Pavilion_-_geograph.org.uk_-_4224824.jpg",
  "photo-congress-theatre-eastbourne": "https://commons.wikimedia.org/wiki/File:Congress_Theatre,_Eastbourne,_East_Sussex_-_geograph.org.uk_-_8173313.jpg",
  "photo-edinburgh-playhouse": "https://commons.wikimedia.org/wiki/File:Edinburgh_Townscape_,_The_Playhouse_Theatre_-_geograph.org.uk_-_2271383.jpg",
  "photo-grand-opera-house-belfast": "https://commons.wikimedia.org/wiki/File:Belfast_City_Centre_-_Grand_Opera_House_-_geograph.org.uk_-_3703186.jpg",
  "photo-his-majestys-theatre-aberdeen": "https://commons.wikimedia.org/wiki/File:Front_elevation_of_His_Majesty%27s_Theatre,_Aberdeen.jpg",
  "photo-newcastle-theatre-royal": "https://commons.wikimedia.org/wiki/File:Theatre_Royal_Newcastle_1145840.jpg",
  "photo-orchard-theatre-dartford": "https://commons.wikimedia.org/wiki/File:Orchard_Theatre,_Dartford_(Southeast_View).jpg",
  "photo-regent-theatre-stoke": "https://commons.wikimedia.org/wiki/File:Regent_Theatre,_Stoke-on-Trent.jpg",
  "photo-wales-millennium-centre": "https://commons.wikimedia.org/wiki/File:Wales_Millennium_Centre_Illuminated_Facade.jpg",

  // The file page each city cover came from, and its licence. A cover is
  // the view a reader recognises as the place, not the theatre — the
  // theatre has its own page and its own picture.
  "photo-city-aberdeen": "https://commons.wikimedia.org/wiki/File:Aberdeen-Harbour-Skyline.jpg",
  "photo-city-belfast": "https://commons.wikimedia.org/wiki/File:Belfast_City_Hall_007.jpg",
  "photo-city-birmingham": "https://commons.wikimedia.org/wiki/File:Victoria_Square_Birmingham_2014-03-15.jpg",
  "photo-city-blackpool": "https://commons.wikimedia.org/wiki/File:Blackpool_-_Blackpool_Tower_-_20170518114241.jpg",
  "photo-city-bournemouth": "https://commons.wikimedia.org/wiki/File:Bournemouth_Pier_-_geograph.org.uk_-_3852494.jpg",
  "photo-city-bradford": "https://commons.wikimedia.org/wiki/File:Bradfordskyline.jpeg",
  "photo-city-brighton": "https://commons.wikimedia.org/wiki/File:Palace_Pier_April_2018_02.jpg",
  "photo-city-bristol": "https://commons.wikimedia.org/wiki/File:Cabot_Tower_View_-_The_Centre,_Redcliffe_and_Bristol_Old_City_-_August_2025.jpg",
  "photo-city-cardiff": "https://commons.wikimedia.org/wiki/File:Cardiff%27s_skyline_2020.jpg",
  "photo-city-cheltenham": "https://commons.wikimedia.org/wiki/File:Cheltenham_town_centre_-_geograph.org.uk_-_6368018.jpg",
  "photo-city-dartford": "https://commons.wikimedia.org/wiki/File:Queen_Elizabeth_II_Bridge,_Dartford,_England_-_Feb_2009.jpg",
  "photo-city-dubai": "https://commons.wikimedia.org/wiki/File:Dubai_skyline_unsplash.jpg",
  "photo-city-dublin": "https://commons.wikimedia.org/wiki/File:Ha%27Penny_Bridge_in_Dublin,_Ireland.jpg",
  "photo-city-eastbourne": "https://commons.wikimedia.org/wiki/File:Eastbourne_Pier_April_2018_05.jpg",
  "photo-city-edinburgh": "https://commons.wikimedia.org/wiki/File:View_of_Edinburgh_Castle_from_Princes_Street.jpg",
  "photo-city-glasgow": "https://commons.wikimedia.org/wiki/File:River_Clyde_in_Glasgow_-_aerial_-_2025-04-17_01.jpg",
  "photo-city-hull": "https://commons.wikimedia.org/wiki/File:Queen_Victoria_Square,_Kingston_upon_Hull_-_geograph.org.uk_-_4736170.jpg",
  "photo-city-liverpool": "https://commons.wikimedia.org/wiki/File:Liverpool_Skyline_from_Birkenhead_-_geograph.org.uk_-_7770736.jpg",
  "photo-city-llandudno": "https://commons.wikimedia.org/wiki/File:LlandudnoPier-P6140188.JPG",
  "photo-city-manchester": "https://commons.wikimedia.org/wiki/File:Deansgate_Square_Manchester_Topped_Out.jpg",
  "photo-city-milton-keynes": "https://commons.wikimedia.org/wiki/File:The_CMK_Shopping_Mall_from_the_top_floor_hotel.jpg",
  "photo-city-new-york": "https://commons.wikimedia.org/wiki/File:Midtown_Manhattan_skyline_from_the_One_World_Observatory,_New_York_City.jpg",
  "photo-city-newcastle": "https://commons.wikimedia.org/wiki/File:Newcastle_Quayside_and_bridges_-_geograph.org.uk_-_5549745.jpg",
  "photo-city-norwich": "https://commons.wikimedia.org/wiki/File:View_of_Norwich_Guildhall_from_the_market_place_-_geograph.org.uk_-_6409489.jpg",
  "photo-city-nottingham": "https://commons.wikimedia.org/wiki/File:Nottingham_Council_House,_Old_Market_Square_-_geograph.org.uk_-_7417417.jpg",
  "photo-city-osaka": "https://commons.wikimedia.org/wiki/File:Osaka_Skyline_from_Abeno_Harukas_20260505_121829_UTC%2B9_23_mm.jpg",
  "photo-city-oxford": "https://commons.wikimedia.org/wiki/File:Oxford_-_Top_of_St_Mary%27s_Church_Tower,-_View_to_City_Centre_%5E_All_Saints_Church_-_geograph.org.uk_-_6400438.jpg",
  "photo-city-plymouth": "https://commons.wikimedia.org/wiki/File:Plymouth_Hoe_at_sunset.jpg",
  "photo-city-sheffield": "https://commons.wikimedia.org/wiki/File:View_over_Sheffield_city_centre_-_geograph.org.uk_-_7735484.jpg",
  "photo-city-southend": "https://commons.wikimedia.org/wiki/File:Southend_Pier_with_train.jpg",
  "photo-city-stoke": "https://commons.wikimedia.org/wiki/File:Hanley_skyline_in_Stoke-on-Trent_-_geograph.org.uk_-_6364167.jpg",
  "photo-city-sunderland": "https://commons.wikimedia.org/wiki/File:Wearmouth_Bridge_and_The_River_Wear.jpg",
  "photo-city-tokyo": "https://commons.wikimedia.org/wiki/File:Shibuya_skyline_from_Tokyu_Plaza_in_Omotesando,_Harajuku,_Tokyo,_2024_May_-_2.jpg",
  "photo-city-truro": "https://commons.wikimedia.org/wiki/File:Distant_view_of_Truro_Cathedral.jpg",
  "photo-city-wimbledon": "https://commons.wikimedia.org/wiki/File:Wimbledon_Village_Hall_and_Museum_-_geograph.org.uk_-_8249069.jpg",
  "photo-city-woking": "https://commons.wikimedia.org/wiki/File:Woking_town_centre_from_Fisher%27s_Farm_near_Send,_Surrey,_January_2024.jpg",
  "photo-city-york": "https://commons.wikimedia.org/wiki/File:York_Minster_from_the_city_wall_-_geograph.org.uk_-_4978609.jpg",
  "licence-cc-by-2-0": "https://creativecommons.org/licenses/by/2.0/",
  "licence-cc-by-4-0": "https://creativecommons.org/licenses/by/4.0/",
  "cats-official": "https://www.catsthemusical.com/",
  "cats-uk-tour": "https://uktour.catsthemusical.com/tickets",
  "tickets-cats-plymouth": "https://theatreroyal.com/whats-on/cats/",
  "tickets-cats-hull": "https://www.hulltheatres.co.uk/theatre-events/cats",
  "tickets-cats-birmingham": "https://www.birminghamhippodrome.com/calendar/cats-two/",
  "tickets-cats-manchester": "https://www.atgtickets.com/shows/cats/palace-theatre-manchester/",
  "tickets-cats-bristol": "https://www.atgtickets.com/shows/cats/bristol-hippodrome/",
  "tickets-cats-llandudno": "https://www.venuecymru.co.uk/cats",
  "tickets-cats-glasgow": "https://www.atgtickets.com/shows/cats/theatre-royal-glasgow/",
  "tickets-cats-nottingham": "https://trch.co.uk/whats-on/cats-14tr",
  "tickets-cats-canterbury": "https://marlowetheatre.com/shows/cats/",
  "tickets-cats-sunderland": "https://www.atgtickets.com/shows/cats/sunderland-empire/calendar/",
  "tickets-cats-aberdeen": "https://www.aberdeenperformingarts.com/whats-on/cats/",
  "tickets-cats-norwich": "https://norwichtheatre.org/whats-on/cats/",
  "tickets-cats-belfast": "https://www.goh.co.uk/whats-on/cats",
  "tickets-cats-dublin": "https://www.bordgaisenergytheatre.ie/show/cats/",
  "tickets-cats-oxford": "https://www.atgtickets.com/shows/cats/new-theatre-oxford/calendar/",
  "tickets-cats-southampton": "https://www.mayflower.org.uk/whats-on/cats-2027/",
  "tickets-cats-edinburgh": "https://www.atgtickets.com/shows/cats/edinburgh-playhouse/calendar/",
  "tickets-cats-bradford": "https://www.bradford-theatres.co.uk/whats-on/cats",
  "tickets-cats-liverpool": "https://www.atgtickets.com/shows/cats/liverpool-empire/calendar/",
  "tickets-cats-woking": "https://www.atgtickets.com/shows/cats/woking-theatre/calendar/",
  "tickets-cats-cardiff": "https://www.wmc.org.uk/en/whats-on/2027/cats",
  "tickets-cats-milton-keynes": "https://www.atgtickets.com/shows/cats/milton-keynes-theatre/calendar/",
  "tickets-cats-newcastle": "https://www.theatreroyal.co.uk/whats-on/cats/",
  "venue-palace-theatre-manchester": "https://www.atgtickets.com/venues/palace-theatre-manchester/",
  "venue-theatre-royal-glasgow": "https://www.atgtickets.com/venues/theatre-royal-glasgow/",
  "venue-marlowe-theatre-canterbury": "https://marlowetheatre.com/",
  "venue-bord-gais-energy-theatre": "https://www.bordgaisenergytheatre.ie/",
  "venue-mayflower-theatre-southampton": "https://www.mayflower.org.uk/",
  "licence-cc-by-sa-2-0": "https://creativecommons.org/licenses/by-sa/2.0/",
  "licence-cc-by-sa-3-0": "https://creativecommons.org/licenses/by-sa/3.0/",
  "licence-cc-by-sa-4-0": "https://creativecommons.org/licenses/by-sa/4.0/",
  "licence-cc0": "https://creativecommons.org/publicdomain/zero/1.0/",
};

/** Path for an outbound link, e.g. go("tickets-cats-plymouth") -> "/go/tickets-cats-plymouth/" */
export function go(slug: string): string {
  return `/go/${slug}/`;
}
