// Every third-party destination this site links to, keyed by the slug that
// /go/<slug>/ resolves to. Outbound links run through that hop so external
// domains collect no link equity from our pages, and /go/ is disallowed in
// robots.txt so the hops are never crawled or indexed themselves.
//
// Ticket links are the one place a visible outbound button is right: a
// reader deciding whether to go needs one click to the seller. It still goes
// through the hop. Two kinds of slug live here — tickets-<run> for a seller,
// venue-<venue> for a venue's own website.
export const outbound: Record<string, string> = {
  "chicago-official": "https://chicagothemusical.com/",
  "chicago-uk-tour": "https://chicagothemusical.com/uk-tour/",
  "chicago-international": "https://chicagothemusical.com/international/",
  "tickets-new-york":
    "https://www.telecharge.com/Chicago-tickets?AID=BWY0049300&utm_source=show_site&utm_campaign=chicagoSS&utm_medium=web&utm_id=BWY0049300",
  "tickets-tokyo": "https://www.kyodotokyo.com/chicago-en/",
  "tickets-osaka": "https://eplus.jp/sf/detail/0227890001?P6=001&P1=0402&P59=1",
  "tickets-dubai-ticketmaster":
    "https://www.ticketmaster.ae/artist/chicago-the-musical-tickets/1443524",
  "venue-coca-cola-arena": "https://coca-cola-arena.com/",
  "venue-ambassador-theatre": "https://www.shubert.nyc/theatres/ambassador",
  "tickets-aberdeen": "https://www.aberdeenperformingarts.com/whats-on/chicago-2027/",
  "tickets-belfast": "https://www.goh.co.uk/whats-on/chicago-2",
  "tickets-birmingham": "https://www.birminghamhippodrome.com/calendar/chicago/",
  "tickets-blackpool": "https://www.wintergardensblackpool.co.uk/events/chicago/",
  "tickets-bournemouth": "https://www.bournemouthpavilion.co.uk/events/chicago-2027",
  "tickets-bradford": "https://www.bradford-theatres.co.uk/whats-on/chicago",
  "tickets-brighton": "https://www.atgtickets.com/shows/chicago-the-musical/theatre-royal-brighton/",
  "tickets-bristol": "https://www.atgtickets.com/shows/chicago-the-musical/bristol-hippodrome/",
  "tickets-cardiff": "https://www.wmc.org.uk/en/whats-on/2027/chicago",
  "tickets-cheltenham": "https://www.everymantheatre.org.uk/shows/chicago/",
  "tickets-eastbourne": "https://trafalgartickets.com/eastbourne-theatres-eastbourne/en-GB/event/musical/chicago-tickets",
  "tickets-edinburgh": "https://www.atgtickets.com/shows/chicago-the-musical/edinburgh-playhouse/",
  "tickets-glasgow": "https://www.atgtickets.com/shows/chicago-the-musical/kings-theatre-glasgow/",
  "tickets-hull": "https://www.hulltheatres.co.uk/theatre-events/chicago",
  "tickets-liverpool": "https://www.atgtickets.com/shows/chicago-the-musical/liverpool-empire/",
  "tickets-manchester": "https://www.atgtickets.com/shows/chicago-the-musical/opera-house-manchester/",
  "tickets-milton-keynes": "https://www.atgtickets.com/shows/chicago-the-musical/milton-keynes-theatre/",
  "tickets-newcastle": "https://www.theatreroyal.co.uk/whats-on/chicago-3/",
  "tickets-norwich": "https://norwichtheatre.org/whats-on/chicago/",
  "tickets-nottingham": "https://www.trch.co.uk/whats-on/chicago-zcb4",
  "tickets-oxford": "https://www.atgtickets.com/shows/chicago-the-musical/new-theatre-oxford/",
  "tickets-plymouth": "https://theatreroyal.com/whats-on/chicago-2027/",
  "tickets-southend": "https://trafalgartickets.com/southend-theatres/en-GB/event/musical/chicago-tickets",
  "tickets-stoke": "https://www.atgtickets.com/shows/chicago-the-musical/regent-theatre/",
  "tickets-sunderland": "https://www.atgtickets.com/shows/chicago-the-musical/sunderland-empire/",
  "tickets-truro": "https://www.hallforcornwall.co.uk/whats-on/chicago/",
  "tickets-wimbledon": "https://www.atgtickets.com/shows/chicago-the-musical/new-wimbledon-theatre/",
  "tickets-woking": "https://www.atgtickets.com/shows/chicago-the-musical/woking-theatre/",
  "tickets-york": "https://www.atgtickets.com/shows/chicago-the-musical/grand-opera-house-york/",
  "venue-alhambra-theatre-bradford": "https://www.bradford-theatres.co.uk/",
  "venue-birmingham-hippodrome": "https://www.birminghamhippodrome.com/",
  "venue-blackpool-opera-house": "https://www.wintergardensblackpool.co.uk/",
  "venue-bournemouth-pavilion": "https://www.bournemouthpavilion.co.uk/",
  "venue-everyman-theatre-cheltenham": "https://www.everymantheatre.org.uk/",
  "venue-grand-opera-house-belfast": "https://www.goh.co.uk/",
  "venue-hall-for-cornwall": "https://www.hallforcornwall.co.uk/",
  "venue-his-majestys-theatre-aberdeen": "https://www.aberdeenperformingarts.com/",
  "venue-hull-new-theatre": "https://www.hulltheatres.co.uk/",
  "venue-newcastle-theatre-royal": "https://www.theatreroyal.co.uk/",
  "venue-norwich-theatre-royal": "https://norwichtheatre.org/",
  "venue-nottingham-royal-concert-hall": "https://www.trch.co.uk/",
  "venue-theatre-royal-plymouth": "https://theatreroyal.com/",
  "venue-venue-cymru": "https://www.venuecymru.co.uk/",
  "info-llandudno": "https://www.venuecymru.co.uk/chicago-3",
  "venue-wales-millennium-centre": "https://www.wmc.org.uk/",

  // The file page each venue photograph came from, and the licence it is
  // published under. Both are named in the caption under the picture
  // because the licence requires it — and both go through the hop, like
  // every other outbound address on this site.
  "photo-coca-cola-arena": "https://commons.wikimedia.org/wiki/File:Westlife_at_Coca-Cola_Arena_-_1.jpg",
  "photo-everyman-theatre-cheltenham": "https://commons.wikimedia.org/wiki/File:Everyman_Theatre,_Cheltenham-4077863023.jpg",
  "photo-grand-opera-house-york": "https://commons.wikimedia.org/wiki/File:Grand_Opera_House,_York_Feb_2022_02.jpg",
  "photo-hall-for-cornwall": "https://commons.wikimedia.org/wiki/File:Hall_for_Cornwall_on_Back_Quay,_Truro_-_geograph.org.uk_-_4429068.jpg",
  "photo-hull-new-theatre": "https://commons.wikimedia.org/wiki/File:Hull_New_Theatre,_Hull_-_geograph.org.uk_-_5233236.jpg",
  "photo-kings-theatre-glasgow": "https://commons.wikimedia.org/wiki/File:King%27s_Theatre,_Glasgow_02.jpg",
  "photo-liverpool-empire": "https://commons.wikimedia.org/wiki/File:Empire_Theatre,_Lime_Street,_Liverpool_-_geograph.org.uk_-_4767710.jpg",
  "photo-new-theatre-oxford": "https://commons.wikimedia.org/wiki/File:New_Theatre_Oxford_Geograph-4785233-by-Steve-Daniels.jpg",
  "photo-new-wimbledon-theatre": "https://commons.wikimedia.org/wiki/File:New_Wimbledon_Theatre_-_geograph.org.uk_-_3809753.jpg",
  "photo-norwich-theatre-royal": "https://commons.wikimedia.org/wiki/File:Norwich_Theatre_Royal_-_geograph.org.uk_-_7566091.jpg",
  "photo-nottingham-royal-concert-hall": "https://commons.wikimedia.org/wiki/File:Theatre_Royal-Royal_Concert_Hall,_South_Sherwood_Street_-_geograph.org.uk_-_7397361.jpg",
  "photo-opera-house-manchester": "https://commons.wikimedia.org/wiki/File:Opera_House,_Manchester_-_geograph.org.uk_-_5624967.jpg",
  "photo-orix-theater": "https://commons.wikimedia.org/wiki/File:ORIX_Theatre.jpg",
  "photo-sheffield-lyceum": "https://commons.wikimedia.org/wiki/File:Lyceum_Theatre,_Sheffield_(1).JPG",
  "photo-sunderland-empire": "https://commons.wikimedia.org/wiki/File:Sunderland_-_High_St_West_%5E_Empire_Theatre_-_geograph.org.uk_-_7939436.jpg",
  "photo-theatre-royal-brighton": "https://commons.wikimedia.org/wiki/File:Theatre_Royal,_New_Road,_Brighton_(NHLE_Code_1380103)_(May_2020)_(2).JPG",
  "photo-theatre-royal-plymouth": "https://commons.wikimedia.org/wiki/File:Theatre_Royal,_Plymouth.jpg",
  "photo-venue-cymru": "https://commons.wikimedia.org/wiki/File:Venue_Cymru_(geograph_5294767).jpg",
  "photo-woking-theatre": "https://commons.wikimedia.org/wiki/File:New_Victoria_Theatre,_Victoria_Way,_Woking_(June_2015)_(2).jpg",
  "photo-alhambra-theatre-bradford": "https://commons.wikimedia.org/wiki/File:The_Alhambra_Theatre,_Bradford_-_geograph.org.uk_-_7153310.jpg",
  "photo-birmingham-hippodrome": "https://commons.wikimedia.org/wiki/File:Birmingham_Hippodrome.jpg",
  "photo-blackpool-opera-house": "https://commons.wikimedia.org/wiki/File:The_Winter_Gardens_-_geograph.org.uk_-_5551191.jpg",
  "photo-bournemouth-pavilion": "https://commons.wikimedia.org/wiki/File:Bournemouth_Pavilion_%5E2_-_geograph.org.uk_-_1923963.jpg",
  "photo-bristol-hippodrome": "https://commons.wikimedia.org/wiki/File:Hippodrome_Theatre,_Bristol._-_panoramio.jpg",
  "photo-cliffs-pavilion-southend": "https://commons.wikimedia.org/wiki/File:Cliffs_Pavilion_-_geograph.org.uk_-_4224824.jpg",
  "photo-congress-theatre-eastbourne": "https://commons.wikimedia.org/wiki/File:Congress_Theatre,_Eastbourne,_East_Sussex_-_geograph.org.uk_-_8173313.jpg",
  "photo-edinburgh-playhouse": "https://commons.wikimedia.org/wiki/File:Edinburgh_Townscape_,_The_Playhouse_Theatre_-_geograph.org.uk_-_2271383.jpg",
  "photo-grand-opera-house-belfast": "https://commons.wikimedia.org/wiki/File:Belfast_City_Centre_-_Grand_Opera_House_-_geograph.org.uk_-_3703186.jpg",
  "photo-his-majestys-theatre-aberdeen": "https://commons.wikimedia.org/wiki/File:Front_elevation_of_His_Majesty%27s_Theatre,_Aberdeen.jpg",
  "photo-newcastle-theatre-royal": "https://commons.wikimedia.org/wiki/File:Theatre_Royal_Newcastle_1145840.jpg",
  "photo-orchard-theatre-dartford": "https://commons.wikimedia.org/wiki/File:Orchard_Theatre,_Dartford_(Southeast_View).jpg",
  "photo-regent-theatre-stoke": "https://commons.wikimedia.org/wiki/File:Regent_Theatre,_Stoke-on-Trent.jpg",
  "photo-wales-millennium-centre": "https://commons.wikimedia.org/wiki/File:Wales_Millennium_Centre_Illuminated_Facade.jpg",
  "licence-cc-by-2-0": "https://creativecommons.org/licenses/by/2.0/",
  "licence-cc-by-sa-2-0": "https://creativecommons.org/licenses/by-sa/2.0/",
  "licence-cc-by-sa-3-0": "https://creativecommons.org/licenses/by-sa/3.0/",
  "licence-cc-by-sa-4-0": "https://creativecommons.org/licenses/by-sa/4.0/",
  "licence-cc0": "https://creativecommons.org/publicdomain/zero/1.0/",
};

/** Path for an outbound link, e.g. go("tickets-dubai-ticketmaster") -> "/go/tickets-dubai-ticketmaster/" */
export function go(slug: string): string {
  return `/go/${slug}/`;
}
